### ISSUE TITLE
Javascript error in search for some search values

### ISSUE THREAD

**Issue by 304NotModified** [EWSoftware/SHFB#100]
Hi,

When searching, We get sometimes (depended of search value) as Javascript error and the page keeps saying "searching". 
Chrome: "Uncaught RangeError: Invalid array length"
IE: "Array length must be assigned a finite positive number"
Firefox: "RangeError: invalid array length"

We don't use server side search and it looks like the error shows up on popular search values.

Live example: (errors)
http://nlog-project.org/documentation/v3.2.1/search.html?SearchText=logmanager
http://nlog-project.org/documentation/v3.2.1/search.html?SearchText=layout
http://nlog-project.org/documentation/v3.2.1/search.html?SearchText=logger

works fine:
http://nlog-project.org/documentation/v3.2.1/search.html?SearchText=debug

built with 2015.5.2.0

**Comment by 304NotModified** [comment]
Chrome says that the exception in thrown here (bit strange)

https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/PresentationStyles/VS2013/Web/scripts/branding-Website.js#l447

**Comment by EWSoftware** [comment]
It turns out it's a JavaScript thing.  Because I initialized `wordDictionary` with square brackets, it's treating the keyword "length" as a property on the array and failing because it can't assign the index array to the integer `length` property.

Change the `wordDictionary` declaration to use curly braces so that it's an object and it fixes the problem:

``` JavaScript
var wordDictionary = {};
```

**Comment by 304NotModified** [comment]
Yes, that sounds the solution

**Comment by 304NotModified** [comment]
and confirmed, this will crash in the console of chrome
```var dict=[]; dict["length"]= "asdads"```

and this will work: ```var dict={}; dict["length"]= "asdads"```

**Comment by 304NotModified** [comment]
PR created

**Comment by 304NotModified** [comment]
Any idea when this will be released?

**Comment by EWSoftware** [comment]
In a month or so probably.  No set date.  I'm in the middle of making some changes to the build engine at the moment.

**Comment by 304NotModified** [comment]
OK thanks. As far as I understand this bug only occurs when:

- no server side search
- searching something starting with the character L

**Comment by EWSoftware** [comment]
No server side search and the keyword "length" specifically appears in the keyword index.
