### ISSUE TITLE
Deprecated `select` attribute usage in docs source

### ISSUE THREAD

**Issue by Ste1io** [EWSoftware/SHFB#1002]
The verbiage at the two locations below still reference the deprecated `select` attribute, rather than `path`.

https://github.com/EWSoftware/SHFB/blob/2ea7eae7c5c7a8db75be8a5c51fba9ef66861eea/TestCaseProject/DocumentationInheritance/DocumentationInheritance.cs#L119-L120

https://github.com/EWSoftware/SHFB/blob/2ea7eae7c5c7a8db75be8a5c51fba9ef66861eea/TestCaseProject/DocumentationInheritance/DocumentationInheritance.cs#L220-L221

**Comment by EWSoftware** [comment]
Thanks.  I fixed it in the XML Comments Example code too.
