### ISSUE TITLE
Sandcastle reports parameter documentation is 'missing' even though they exist

### ISSUE THREAD

**Issue by ketchup201** [EWSoftware/SHFB#1004]
I have the following class (sample here is from Framework 4.8, but I also am experiencing this in .NET 6.0)...

```
    public class Program
    {
        /// <summary>
        /// Blah. blah blah blah.
        /// </summary>
        public enum ACLType
        {
            /// <summary>
            /// Blah blah.
            /// </summary>
            Select,

            /// <summary>
            /// Blah blah.
            /// </summary>
            Update,

            /// <summary>
            /// Blah blah.
            /// </summary>
            Delete
        };


        /// <summary>
        /// Blah blah blah
        /// </summary>
        /// <param name="instId">Blah blah</param>
        /// <returns>Blah. blah. Blah.</returns>
        public Dictionary<ACLType, int[]> GetACLs(long instId)
        {
            return null;
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World");
        }
    }
```

Generated Sandcastle documentation states:
### Parameters
instId  [Int64]
**[Missing <param name="instId"/> documentation for "M:SandcastleBug.Program.GetACLs(System.Int64)"]**

### Return Value
Dictionary<Program.ACLType, Int32[]>
**[Missing <returns> documentation for "M:SandcastleBug.Program.GetACLs(System.Int64)"]**

From everything I researched, there should be no reason why Sandcastle is reporting these missing. Am **I** missing something?

**Comment by EWSoftware** [comment]
Are you using the assemblies as the documentation source or the project?  What framework version have you got selected in the SHFB project?

**Comment by ketchup201** [comment]
Sorry, I never got a notification you responded!
I'm using the assemblies as the documentation.  Tried with Framework 4.8 for both c# project and sandcastle.

**Comment by ketchup201** [comment]
![image](https://github.com/EWSoftware/SHFB/assets/7560811/864be008-64db-4f80-bf8e-f6862b235f7a)

**Comment by EWSoftware** [comment]
Did you add the XML comments files to the SHFB project as well?  Did you check to see that they exist and are current?  Typically, you're better off using the project as the documentation source as then SHFB will resolve the assemblies, comments files, and references for itself.

**Comment by ketchup201** [comment]
THANK YOU! That was the issue. SHFB was able to resolve what it wasn't able to before. This issue can be closed as user error.

**Comment by ketchup201** [comment]
User error.
