### ISSUE TITLE
Method not found error after updating

### ISSUE THREAD

**Issue by millennIumAMbiguity** [EWSoftware/SHFB#1011]
![image](https://github.com/EWSoftware/SHFB/assets/37588844/37c87ff4-9d6c-4008-979c-9c968c5eb6c7)

After selecting the build tab, I get this error.
I tried deleting the `EWSoftware/Sandcastle Help File Builder` and the `/HTML Help Workshop` folder and installed it again. but still get errors.

After selecting a presentation style it crashes.

﻿
```
Unexpected error loading syntax generators and presentation styles: The composition produced a single composition error. The root cause is provided below. Review the
CompositionException.Errors property for more detailed
information.

1) Method not found: 'Void Sandcastle.Core.PresentationStyle.PresentationStyleSettings.set_TopicTranformation(Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore)'.

Resulting in: An exception occurred while trying to create an instance of type Sandcastle.Presentation Styles.Default2022.Default2022PresentationStyle'.
Resulting in: Cannot activate part 'Sandcastle.PresentationStyles.Default2022.Default2022PresentationStyle'.
Element:
Sandcastle.PresentationStyles.Default2022.Default2022PresentationStyle -->
Sandcastle.PresentationStyles.Default2022.Default2022PresentationStyle --> AssemblyCatalog (Assembly="Sandcastle. PresentationStyles, Version=2022.8.14.0, Culture=neutral,
PublicKeyToken=c8895f0c125eff20")

Resulting in: Cannot get export
Sandcastle.PresentationStyles.Default2022.Default2022PresentationStyle
(ContractName="Sandcastle.Core.PresentationStyle.Presentati onStyleSettings")' from part
'Sandcastle.PresentationStyles.Default2022.Default2022PresentationStyle'.
Element:
Sandcastle.PresentationStyles.Default2022.Default2022PresentationStyle
(ContractName="Sandcastle.Core.PresentationStyle.PresentationStyleSettings") -->
Sandcastle.PresentationStyles.Default2022.Default2022PresentationStyle --> AssemblyCatalog (Assembly="Sandcastle.PresentationStyles,
Version=2022.8.14.0, Culture=neutral,
PublicKeyToken=c8895f0c125eff20")

**Comment by EWSoftware** [comment]
The version in the error is 2022.8.14.0 so it's finding another older copy of SHFB somewhere in the paths it's searching for presentation styles.  You can find those in the log file.  You might also check that SHFBROOT is pointing to the right location.

**Comment by millennIumAMbiguity** [comment]
where do I find the logs? since I never get to start a build, I don't get a build log.

**Comment by millennIumAMbiguity** [comment]
I used WizTree to search for any file or folder containing "Sandbox" but there were no results outside the expected ones.

**Comment by EWSoftware** [comment]
Sandcastle not Sandbox.  I misunderstood your original message.  It does try to locate components when switching between tabs in the project properties as well though.  If you do build the project, the build log will contain the folders it searches.

**Comment by millennIumAMbiguity** [comment]
> Sandcastle not Sandbox. I misunderstood your original message. It does try to locate components when switching between tabs in the project properties as well though. If you do build the project, the build log will contain the folders it searches.

I'm sorry, I miss-typed. I meant Sandcastle.

I can not build it as it crashes when selecting a presentation type.

**Comment by EWSoftware** [comment]
Are you using the standalone GUI?  If using Visual Studio, you can just open and build the project.  You can try building from the command line with MSBuild as well as an alternative.  There's an outdated version somewhere that it's finding.

Outside of the actual installation folder, it will search the project file's folder and subfolders, [third party components folders](https://ewsoftware.github.io/SHFB/html/a24489fb-45d6-46f4-9eaa-9a9c4e0919b2.htm), and the Component Path property in the project if set.  Another possibility is if you've got the older SHFB NuGet packages referenced by the project or perhaps in one of the search paths and it's finding that.

As a last resort, uninstall SHFB and make sure all of the files are gone from the Program Files folder.  If they are, reinstalling should work.  If it fails after that, then you are back to the above where it's finding an older copy somewhere while scanning for components.

**Comment by millennIumAMbiguity** [comment]
I'm using the standalone GUI. I was unable to resolve the issue or get any logs. I have restored my previous version and will continue to use that.
