### ISSUE TITLE
How do I export XML?

### ISSUE THREAD

**Issue by millennIumAMbiguity** [EWSoftware/SHFB#1012]
Given a `.dll` and an `.xml` generated from a c# project, I would expect that I would be able to export a modified xml file using the exclusions that I have defined. But I am unable to find how I would do that.

**Comment by EWSoftware** [comment]
Do you mean an XML comments file containing only the documented members?  If so, add the [IntelliSense Component](https://ewsoftware.github.io/SHFB/html/5d546511-6aec-455a-ba09-9daffb124c6d.htm) to the SHFB project on the Components tab.
