### ISSUE TITLE
Exclude Inherited from Control members

### ISSUE THREAD

**Issue by jhon65496** [EWSoftware/SHFB#1013]
Exclude Inherited from Control members

How to exclude Inherited from Control members

I have generated the documentation.
The documentation displays the members `Inherited from Control'.

How do I make SHFB generate documentation that does not display `Inherited from Control'?

![04 08 2023_18-02-16](https://github.com/EWSoftware/SHFB/assets/128128859/4293dc6c-1cd4-4d91-96f3-c4f99e39703d)

**Comment by EWSoftware** [comment]
If you don't care to show any inherited base framework members, you can turn off the options starting with "Inherited .NET Framework" in the [Visibility category](https://ewsoftware.github.io/SHFB/html/3c489bd6-598c-4684-aafb-fbe9400864d3.htm) to remove them.

If you want to be more selective, use the [API filter](https://ewsoftware.github.io/SHFB/html/7df16a60-f718-4b8f-bfa2-88c42906070c.htm) in the same category.  Using the Inherited APIs tree node, you can exclude specific base framework members from their selected types.

**Comment by jhon65496** [comment]
@EWSoftware 
I got the result, but not completely what I expected.
There are no `Form1_Load`, `Form1_Closing` and so on events in the generated documentation.

What am I doing wrong?

![05 08 2023_13-02-45](https://github.com/EWSoftware/SHFB/assets/128128859/85789b94-0211-425e-ac1b-8a667790d863)
![05 08 2023_13-03-40](https://github.com/EWSoftware/SHFB/assets/128128859/7d849128-a42d-4118-952c-f62e9edd7062)

**Comment by EWSoftware** [comment]
Can you attach an example so that I can see what options you are using?
