### ISSUE TITLE
How do I display the method body or the entire method in the documentation?

### ISSUE THREAD

**Issue by jhon65496** [EWSoftware/SHFB#1014]
How do I display the method body or the entire method in the documentation?

**Comment by EWSoftware** [comment]
It can't be done automatically.  The best option if the code is hosted online such as at GitHub is to use the `baseSourceCodeUrl` argument in the [Transform Component Arguments](https://ewsoftware.github.io/SHFB/html/c584509f-0b18-49a8-ab06-114b0058a739.htm) category in conjunction with the Source Code Base Path property in the [Paths](https://ewsoftware.github.io/SHFB/html/e6fcfa33-e7ee-430a-abfe-6b7962e6d068.htm) category to allow it to generate a link to the online repository for each member.

If you want to include the actual source code in the help topic, you'd need to use the `source` and `region` attributes on the XML comments [code element](https://ewsoftware.github.io/XMLCommentsGuide/html/1abd1992-e3d0-45b4-b43d-91fcfc5e5574.htm) to import the related code into each topic via each member's XML comments.  That would be a lot of work and most likely error prone.

**Comment by jhon65496** [comment]
@EWSoftware 
Could you use the example of this project to show how to do this for a local project?

In other words, not for a project that is on `GitHub`, but for a project that is located on a computer.

https://github.com/jhon65496/WinFrmsApp1

**Comment by EWSoftware** [comment]
It won't work if the source code is located on a local PC.  The web browser would block access to the local file system.
