### ISSUE TITLE
Where is the ConvertHtmlToMaml.exe command line utility mentioned in the documentation located?

### ISSUE THREAD

**Issue by dkimbell13** [EWSoftware/SHFB#1015]
I have seen references to an Extras folder, but there was not Extras folder after installing the desktop version of SHFB.

**Comment by EWSoftware** [comment]
That tool is really old and not used much anymore so it was removed from the SHFB package in version 2022.8.14.0.  The code can now be found in its own [repository](https://github.com/EWSoftware/HtmlToMamlConverter).  I did keep the [documentation online](https://ewsoftware.github.io/HtmlToMamlDocs/html/83b3d408-4e02-42d2-beed-0b13294f23f2.htm) though.
