### ISSUE TITLE
Installation in Docker image

### ISSUE THREAD

**Issue by NETSphereSoft** [EWSoftware/SHFB#1017]
I referencing the issue #794 here also.

There are two questions around this:

a) How does SHFB installation detect the existience of HTML Help compiler and also during the (MS)Build?
b) Is there a way to install SHFB in a quiet mode? "msiexec /i SandcastleHelpFileBuilder.msi /quiet /norestart" seems not to work.

**Comment by EWSoftware** [comment]
Also replied in the other work item:

The guided installer just searches for the folder "HTML Help Workshop" under the Program Files folder. If it finds it, it assumes it's installed. The SHFB build tools do the same thing. Quiet mode should work since it's just a function of the MSI file rather than anything specific to the SHFB tools.

**Comment by NETSphereSoft** [comment]
HHC searched in "Program Files" or "Program Files (x86)"?

**Comment by EWSoftware** [comment]
The (x86) version since HHC is a 32-bit application.

**Comment by NETSphereSoft** [comment]
Thanks, that's what I expected and have prepared. The installation test I will repeate next week.

**Comment by NETSphereSoft** [comment]
Found a way to install SHFB with HTML Help 1 Compiler

- Install HTML Help 1 Compiler
  - As from download here from repository [`htmlhelp.exe`](../raw/master/ThirdPartyTools/htmlhelp.exe)
    - Should install 7Zip before
    - Download `htmlhelp.exe` from this repository
    - Extract `htmlhelp.exe` as a cabinet with `7z x htmlhelp.exe -tcab -o"%ProgramFiles(x86)%\HTML Help Workshop"`
  - As from Visual Studio Build Tools (`Microsoft.VisualStudio.Component.VC.ATLMFC`)
    - It requires additional installation for Windows Client files `itircl.dll` and `itss.dll`
    - So pull related Windows image to get those files (like `mcr.microsoft.com/windows:ltsc2019`)
    - Start this image as container with a mapped directory on your host
    - Copy files `itircl.dll` and `itss.dll` from `C:\Windows\SysWOW64` to your mapped host directory
    - Leave the container
    - Add instructions to you docker file for adding those files to `C:\Windows\SysWOW64`
    - You need then to add run instructions to COM/ActiveX register those files with regsvr32  
      `C:\Windows\SysWOW64\regsvr32.exe /s C:\Windows\SysWOW64\<FileName>`
    - Download Visual Studio Build Tools installer (https://aka.ms/vs/<Version\>/release/vs_BuildTools.exe)
    - Run installer with add of component `Microsoft.VisualStudio.Component.VC.ATLMFC` and use of `installPath`
- Install SHFB
    - Download SHFB from repository releases (https://github.com/EWSoftware/SHFB/releases/download/<Version\>/SHFBInstaller_<Version\>.zip)
    - Extract the ZIP archive somewhere
    - Run installer `msiexec` with the `SandcastleHelpFileBuilder.msi` from sub directory `InstallResources` and options `ADDLOCAL=ALL` and `/qn`


***Docker instructions***

Visual Studio Build Tools

```docker
# Add Visual Studio Build Tools components (https://visualstudio.microsoft.com/de/downloads/#build-tools-for-visual-studio-2022)
ARG MICROSOFT_VS_BUILD_TOOLS_VERSION=17

RUN echo Resolving / Downloading Visual Studio Build Tools %MICROSOFT_VS_BUILD_TOOLS_VERSION% ... `
    && curl -fSLo vs_BuildTools.exe https://aka.ms/vs/%MICROSOFT_VS_BUILD_TOOLS_VERSION%/release/vs_BuildTools.exe `
    && echo Adding Components ... `
    && start /w vs_BuildTools `
         --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools" `
         --add Microsoft.VisualStudio.Component.VC.ATLMFC `
         --quiet --norestart --nocache --wait `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del vs_BuildTools.exe
```

Missing Windows Client components

```docker
# Add missing Windows Client component itircl.dll for HTML Help 1 Compiler (https://stackoverflow.com/a/59824188/1734201 / https://stackoverflow.com/questions/56816350/how-do-you-compile-a-html-help-workshop-project-inside-a-docker-container)
COPY itircl.dll C:\Windows\SysWOW64


# Register missing Windows Client component itircl.dll for HTML Help 1 Compiler
RUN echo Register itircl.dll ... `
    && C:\Windows\SysWOW64\regsvr32.exe /s C:\Windows\SysWOW64\itircl.dll `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }"


# Add missing Windows Client component itss.dll for HTML Help 1 Compiler (see component itircl.dll also)
COPY itss.dll C:\Windows\SysWOW64


# Register missing Windows Client component itss.dll for HTML Help 1 Compiler
RUN echo Register itss.dll ... `
    && C:\Windows\SysWOW64\regsvr32.exe /s C:\Windows\SysWOW64\itss.dll `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }"
```

Sandcastle Help File Builder

```docker
# Install Sandcastle Help File Builder (https://github.com/EWSoftware/SHFB/releases)
ARG SHFB_VERSION=2024.2.18.0

RUN echo Resolving / Downloading Sandcastle Help File Builder %SHFB_VERSION% ... `
    && curl -fSLo SHFBInstaller.zip https://github.com/EWSoftware/SHFB/releases/download/%SHFB_VERSION%/SHFBInstaller_%SHFB_VERSION%.zip `
    && echo Extracting ... `
    && md temp `
    && md temp\shfb `
    && "%ProgramFiles%\7-Zip\7z" x -y SHFBInstaller.zip -o"temp\shfb" `
    && echo Installing ... `
    && msiexec /i temp\shfb\InstallResources\SandcastleHelpFileBuilder.msi ADDLOCAL=ALL /qn /norestart `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && rmdir temp /S /Q `
    && del SHFBInstaller.zip
```

***Alternate with 7-Zip and HTML Help 1 Compiler from this repository***

7-Zip

```docker
# Install 7Zip (https://7-zip.de/download.html)
ARG SEVEN_ZIP_VERSION=2404

RUN echo Resolving / Downloading 7Zip %SEVEN_ZIP_VERSION% ... `
    && curl -fSLo 7z-x64.exe https://7-zip.org/a/7z%SEVEN_ZIP_VERSION%-x64.exe `
    && echo Installing ... `
    && 7z-x64.exe /S `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del 7z-x64.exe
```

HTML Help 1 Compiler

```docker
# Install HTML Help 1 Compiler
RUN echo Resolving / Downloading HTML Help Workshop ... `
    && curl -fSLo htmlhelp.exe https://github.com/EWSoftware/SHFB/raw/master/ThirdPartyTools/htmlhelp.exe `
    && echo Installing ... `
    && "%ProgramFiles%\7-Zip\7z" x htmlhelp.exe -tcab -o"%ProgramFiles(x86)%\HTML Help Workshop" `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del htmlhelp.exe
```

**Comment by NETSphereSoft** [comment]
There is an easier way to shorten the copy of Windows Client files `itircl.dll` and `itss.dll` when using HTML Help 1 Compiler from Visual Studio Build Tools (`Microsoft.VisualStudio.Component.VC.ATLMFC`)

```docker
FROM mcr.microsoft.com/windows:ltsc2019 as windows
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

COPY --from=windows C:\Windows\SysWOW64\itircl.dll C:\Windows\SysWOW64
RUN echo Register itircl.dll ... `
    && C:\Windows\SysWOW64\regsvr32.exe /s C:\Windows\SysWOW64\itircl.dll `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }"

COPY --from=windows C:\Windows\SysWOW64\itss.dll C:\Windows\SysWOW64
RUN echo Register itss.dll ... `
    && C:\Windows\SysWOW64\regsvr32.exe /s C:\Windows\SysWOW64\itss.dll `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }"
```

**Comment by VBWebprofi** [comment]
Hint: A smaller installation of HTML Help 1 Compiler from Visual Studio Build Tools you can find documented in issue #1060.
