### ISSUE TITLE
When empty, remove "Website Ad Content" div column in footer, for "Default 2022" presentation style.

### ISSUE THREAD

**Issue by YImhof** [EWSoftware/SHFB#1020]
Hello,

In "Default 2022" presentation style, the footer is compound with "Additional footer content" and "Website Ad Content", creating a `<div class="column">` for each ... even when those options are empty, adding a `&nbsp;` content.

Problem is, for example, when you only have an additional footer content without ad, for devices larger than 769px or landscape display, footer goes only half of the page width:
<img width="541" alt="FooterHalfWidth" src="https://github.com/EWSoftware/SHFB/assets/60145713/f0246481-b059-43a8-94d2-168dc5ebc4c8">

I am using SHFB 2023.7.8.0 as VS2022 (17.7.4) integration package. Imho, each div column should be created only when the corresponding configuration option is non empty. Or is there a way to bypass this behavior?

**Comment by EWSoftware** [comment]
I'm not seeing that behavior and can't duplicate it with varying footer properties set or empty.  Can you provide an example that I can use to duplicate it?

**Comment by YImhof** [comment]
Here is a full .Net 8 solution reproducing the case.  
You can directly launch the `SHFBWebServer` executable in the `bin` directory to see the HTML documentation in your default browser.
[SHFBExample.zip](https://github.com/EWSoftware/SHFB/files/13858402/SHFBExample.zip)
