### ISSUE TITLE
Display Signature of Methods that Aren't Overloaded - Previous Fix from Issue 261 No Longer Works

### ISSUE THREAD

**Issue by SomeEnormousBear** [EWSoftware/SHFB#1021]
Hello!  I want to get method parameters showing in the member list pages, for all methods (not just overloaded ones). As per the suggestions in Issue 261 (from Feb 2016) it used to be possible to do this by editing utilities_reference.xsl, but utilities_reference.xsl doesn't seem to exist in more recent versions of SHFB.

Is there another way to do this now?

Thank you :)

**Comment by EWSoftware** [comment]
I've added a ShowParametersOnAllMethods transformation argument to all presentation styles to allow showing parameters on all methods, not just overloads, on member list pages.  It'll be in the next release due out soon.

**Comment by SomeEnormousBear** [comment]
Many thanks for this, and all the work you do on SHFB!
