### ISSUE TITLE
Issue when compiling inside Docker Container

### ISSUE THREAD

**Issue by Clumi** [EWSoftware/SHFB#1023]
Hi,
I hope this is the right forum for questions! I have installed SHFB inside a Docker container to compile to Help1 files. However there is a problem in the final build step:
```
<buildStep step="CompilingHelpFile">
Compiling HTML Help 1 file...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe - Build1xHelpFile.proj]
HHC5010 : error : Cannot open &quot;c:\builds\development\Documentation\Test_API\Help\Working\Output\HtmlHelp1\Test_API.chm&quot;. Compilation stopped. [C:\builds\development\Documentation\Test_API\Help\Working\Build1xHelpFile.proj]
  
C:\builds\development\Documentation\Test_API\Help\Working\Build1xHelpFile.proj(52,5): error MSB3030: Could not copy the file &quot;C:\builds\development\Documentation\Test_API\Help\Working\Output\HtmlHelp1\Test_API.chm&quot; because it was not found.
    Last step completed in 00:00:01.3600
</buildStep>
```
And indeed, Test_API.chm does not exist. I tested the same process on my machine, and it works just fine. I have attached the full log of the failed build. How can I get more troubleshooting info out of SHFB to figure out what the actual problem is? I'd appreciate any hints.
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/12817444/LastBuild.log)

**Comment by Clumi** [comment]
Thank you very much for this useful link. It seems the itircl.dll and itss.dll are usually supplied by the windows installation, but are not part of the windows docker images. I was able to resolve this issue by adding them to the container as described on stackoverflow.

**Comment by VBWebprofi** [comment]
@Clumi, a question how got you SFHB installed in Docker container. My tests some time ago haven't be successful.
