### ISSUE TITLE
HTMLHelp CHM file contains destroyed? icons

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#1028]
I'm using SHFB v2023.7.8.0 to create compiled HTMLHelp files (*.chm). The final output looks like described already in issue #858 . In the working output the icons are OK. When I "decopile" the CHM file with 7Zip the icons are destroyed.

During compilation I get the following HTML Compiler v4.74.8702.0 (03/DEC/1999) ? output for each icon:

```
HHC3004 : warning : AlertCaution.png : The HTML tag &quot;•Y&#227;&#252;&#175;&#248;18&#165;B&#193;&#193;`&#202;IEND&#174;B`‚&quot; is not a valid HTML tag (it does not begin with an alphanumeric character). [C:\_Storage\Projects\SnapLogic\SnapLogic.Help\Help\Working\Build1xHelpFile.proj]
```

Do I compare the contents output for HtmlHelp1 and the "decoplied" CHM file then the HTML, JS and CSS files are equal. But all icons (ICO, PNG and GIF) are different.

Why this happens?

**Comment by VBWebprofi** [comment]
I found a way of a solution. It seems the creation of the HTMLHelp1 project file (`Help1x.hhp`) is wrong. When I move all file entries except the HTML from section `[FILES]` to section `[INFOTYPES]` then I get no errors and the icons are OK.

The only problem is, when a section get collapsed, then still I have no icon there.

**Comment by EWSoftware** [comment]
Are you sure it isn't a problem with the path like that described in #858?  The help compiler can do weird things if that is the case.  As noted there, using a different output path without the problem characters can work around it.

**Comment by VBWebprofi** [comment]
Yes, I'm sure in case of the general problem that no icon will be displayed after a normal compilation with the latest SHFB version.

When I move it in the other section and compile it again, all icons will be visible.

One single problems still remains, the display of the sectionCollapsed icon does not work.

Later I can add three pictures to show what I mean.

**Comment by EWSoftware** [comment]
Based on your screenshots and the BE0060 warning in the build log, I think it is an issue with the path as you've got ".H" in there (IssueSample.1028.Help).  It doesn't matter if it's a single letter or the start of a word as in this case.  Any ".H" in the path [will mess it up](https://ewsoftware.github.io/SHFB/html/e076c319-ff84-40dc-bb00-ff4c72718215.htm).

As noted in the other work item, change the working path to something that doesn't contain ".H".  If necessary, you can use the output deployment plug-in to move the build output where you really want it after it's been generated.

**Comment by VBWebprofi** [comment]
You got me on the track, but is isn't the `Output Deployment` plugin, it's the `HTML content output path` in `Path` / `Output Paths`.

**Comment by VBWebprofi** [comment]
Ok, with path for setting `Path` / `Output Paths` / `Help content output path` that not contains a `.h` or `.H` it works to get an output without errors. Using then the `Output Deployment` plugin can bring the file to the expected place where the path then can include a `.h` or `.H`.

**Comment by VBWebprofi** [comment]
For a convenient usage, the `Help content output path` should support expand of environment variables.
