### ISSUE TITLE
Markdown output contains links without file name extensions

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#1029]
When I use Markdown as presentation style, the generated files are not navigable as the links don't have the file extension of `.md`

**Comment by EWSoftware** [comment]
Use the property in the [Help 1/Website category](https://ewsoftware.github.io/SHFB/html/7d28bf8f-923f-44c1-83e1-337a416947a1.htm) to add the extensions.

**Comment by VBWebprofi** [comment]
Thanks for the advice. I had in mind that I've seen such option but didn't found it later. Works as expected.
