### ISSUE TITLE
CHM created to network share results in "This page can't be displayed" errors

### ISSUE THREAD

**Issue by cdipierr** [EWSoftware/SHFB#103]
If you are creating CHM (Help/1) files, and you have a directive like this:
    <OutputPath>\\server.domain.com\path\v10.5\JSAPI\Documentation</OutputPath>

The CHM will be produced, but navigating to any page other than the root page will result in this error:

This page can’t be displayed
Make sure the web address //ieframe.dll/dnserrordiagoff.htm# is correct. 
Look for the page with your search 

Interestingly, if you map the drive and use something like:
    <OutputPath>n:\JSAPI\Documentation</OutputPath>

This will work properly (as will CHM produced to local drives).

This doesn't seem to be related to CHM's security settings, in that if you copy the produced file from the share to a local drive, it still displays the same error, and there's no "some content blocked.." to turn off as you have to do with downloaded CHM files.

**Comment by cdipierr** [comment]
Sorry about that, previous comment ate tags, should be:
\<OutputPath>\\\\server.domain.com\path\v10.5\JSAPI\Documentation\</OutputPath>

And

\<OutputPath>n:\JSAPI\Documentation\</OutputPath>

**Comment by EWSoftware** [comment]
More likely than not it is a security issue and is related to this [FAQ topic](http://ewsoftware.github.io/SHFB/html/097c63eb-3ceb-4d5b-bbe4-1e55c56d39b7.htm#Help1NotLoading1).  The reason it doesn't work if copied to a local drive is that the OS is blocking the file itself and you need to edit its properties and explicitly unblock it.  Applying the registry change noted in the FAQ should allow it to work though you may still need to unblock any existing files.

**Comment by cdipierr** [comment]
Yeah, I'm aware of that security item, but this issue does not resolve with that change. As noted above, the "n:\" drive mapped above is the same as the network share in question and works properly. When the UNC path is used instead, then this error occurs. 

The file does not have the "Block content" property on it (like when you download a .chm from a web site for instance) and setting the regkey does not resolve the issue.

**Comment by EWSoftware** [comment]
I don't think there's any other workaround other than compiling on a mapped or local drive.  It's an issue with the compiled help file or the help compiler itself.  It's not something I can fix in SHFB.
