### ISSUE TITLE
MSBuild property values not passed to linked projects

### ISSUE THREAD

**Issue by nblackburn77** [EWSoftware/SHFB#1033]
We have a help project (Help.shfbproj) that has an additional reference link to another help project (ThirdPartyReferences.shfbproj).

Both projects use a custom MSBuild property in each of its documentation sources e.g.:

```
<DocumentationSources>
  <DocumentationSource sourceFile="$(InstallPath)\CefSharp.WinForms.dll" />
  <DocumentationSource sourceFile="$(InstallPath)\CefSharp.WinForms.xml" />
</DocumentationSources>
```

We build Help.shfbproj as follows, specifying the value of InstallPath:

`msbuild Help.shfbproj /p:InstallPath=c:\buildoutput`

The documentation sources specified in Help.shfbproj resolve fine, but not for ThirdPartyReferences.shfbproj. So it fails with the following error in LastBuild.log:

```
SHFB: Warning BE0006: Unable to locate any documentation sources for &#39;C:\CefSharp.WinForms.dll&#39; (Configuration: Debug Platform: AnyCPU)
...
SHFB: Error BE0042: You must specify at least one documentation source in the form of an assembly or a Visual Studio solution/project file
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

It looks as though current property values are not passed to linked projects when they are built?

We are using version 2023.3.4.0.

**Comment by EWSoftware** [comment]
If it's referenced through the additional reference links plug-in, then no, they won't make it over to the other project since it's built separately from the main project.  If you can put the value in a separate project file that can be imported into both ahead of all other properties, it should evaluate properly in them then.

The property value project:

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <InstallPath>C:\buildoutput</InstallPath>
  </PropertyGroup>
</Project>
```

Import it into each SHFB project:

```
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <!-- Import the custom property values ahead of everything else -->
    <Import Project="$(MSBuildThisFileDirectory)\MyCustomProperties.proj" />
    .
    .
    .
```

**Comment by nblackburn77** [comment]
Thanks, we build the InstallPath dynamically, so we've managed to work around it by setting an environment variable in a batch file.
