### ISSUE TITLE
Nested `private protected` types incorrectly included in documentation

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#1036]
Given the following code

```cs
/// <summary>A public class.</summary>
public class DocTest {

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected DocTest() { }

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected int Field;

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected int Property { get; set; }

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected void Method() { this.Event?.Invoke(42); }

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected readonly struct MemberStruct { }

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected sealed class MemberClass { }

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected delegate void Delegate(int n);

  /// <summary>**DO NOT DOCUMENT**</summary>
  private protected event Delegate? Event;

}
```

(and `VisibleItems` set to `Attributes, ExplicitInterfaceImplementations, InheritedMembers, InheritedFrameworkMembers, Protected, ProtectedInternalAsProtected`), the expectation would be to see only the `DocTest` class in the documentation, without any member/contents.

However, the nested types (`MemberClass`, `MemberStruct` and `Delegate`) do appear in the documentation (and the code box has things like ` readonly struct` (i.e. the access specifier is not created).

The other members are correctly excluded.

**Comment by EWSoftware** [comment]
It looks like that's a C# 7.2 feature so it wasn't around when MRefBuilder was developed.  I can add support for it.  However, since they are visible within the same assembly to derived classes or those granted access with `InternalsVisibleTo`, I suppose a case could be made for documenting them so perhaps it can be configurable but default to not showing them.

**Comment by Zastai** [comment]
I would agree that they should be included if I had configured the docs as including `internal`, but I have not - and `ProtectedInternalAsProtected` most definitely should _not_ apply to `private protected`.

More importantly, it's currently inconsistent, because the issue affects only nested types, not fields/properties/constructors/methods.

But yes, a separate visibility checkbox would make sense, even if they could initially be lumped in with `internal` items.
