### ISSUE TITLE
C# `init` property accessors documented as `set`

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#1037]
Given a property

```cs
  public int Foo { get; init; }
```

the generated documentation will show

```cs
  public int Foo { get; set; }
```

instead.

These are identified by a `modreq` on the set accessor's return type (i.e. void), using `System.Runtime.CompilerServices.IsExternalInit`.

**Comment by EWSoftware** [comment]
What version of SHFB are you using?  Support for that was added in v2022.10.15.0.  It's working as far as I know but I can test it be sure if you're using that version or later.

**Comment by Zastai** [comment]
I'll recheck during working hours tomorrow; we were using a very old 2020 version and I was in the process of bringing that up to date, so I may have checked with the old version.

**Comment by Zastai** [comment]
Yes, this works in the recent version.
