### ISSUE TITLE
BE0066: ResolveReferenceLinksComponent: [...] Member ID URL resolver service failed.

### ISSUE THREAD

**Issue by koszeggy** [EWSoftware/SHFB#1040]
When I try to build a help project using the latest release I get the following warning:

```
BE0066: ResolveReferenceLinksComponent: [T:MyNamespace.MyType] Member ID URL resolver service failed.  No further look ups will be performed for this build.
Reason: The remote server returned an error: (403) Forbidden.
```

As a result, none of the MS references are resolved in the documentation (though the mentioned type in the warning is mine). I found the already closed #762, which seems to be a similar issue but I think this must be some different change in the service as this was working recently.

**Comment by koszeggy** [comment]
Ah, I see, and thank you for the quick fix.

Btw, if you need an alternative solution for `BinaryFormatter` that is mainly compatible with it, I can offer [mine](https://github.com/koszeggy/KGySoft.CoreLibraries#binary-serialization).

**Comment by EWSoftware** [comment]
The links are generated locally in code now so the service and the need to cache the URLs has gone away.

**Comment by EWSoftware** [comment]
It's official.  The resolver service is [being shutdown](https://github.com/dotnet/docfx/issues/9659).  It says on March 8th but as we know, it stopped working a couple of weeks ago.  I've got the changes made that no longer need it and they are checked in.  It's just a matter of finding the time to publish the update.  Most people probably won't notice unless the local cache file is deleted or it tries to resolve something that isn't in the cache and tries to use the service.

**Comment by EWSoftware** [comment]
Version 2024.2.18.0 is now available.  It contains the new resolver that no longer needs the service.
