### ISSUE TITLE
`See` element and override within sealed class

### ISSUE THREAD

**Issue by brinko99** [EWSoftware/SHFB#1041]
I have a `See` element which is producing a "BE0066: ResolveReferenceLinksComponent" "Unknown reference link target" warning.

It appears to relate to the fact that the reference is an override of a protected method within a sealed class. I can't find a syntax that will avoid the warning. Visual Studio / Roslyn has no issue with it and finds the reference correctly.

Removing `sealed` causes the warning to go away.

Example:

```
using System;
using System.ComponentModel.DataAnnotations;

namespace Sandcastle.Repo
{
    /// <summary>
    /// My Validation attribute.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = true)]
    public sealed class MyValidationAttribute : ValidationAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MyValidationAttribute"/> class.
        /// </summary>
        /// <remarks>
        /// <para>Produces BE0066: <see cref="IsValid"/>.</para>
        /// <para>Produces BE0066: <see cref="IsValid(object, ValidationContext)"/>.</para>
        /// </remarks>
        public MyValidationAttribute()
            : base()
        {
        }

        /// <inheritdoc />
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            return ValidationResult.Success;
        }
```

Note, the base `ValidationAttribute` defines the following overloads. Note one method is `public`, the other `protected`:

```
public virtual bool IsValid(object value) { }
protected virtual ValidationResult IsValid(object? value, ValidationContext validationContext) { }
```

**Comment by EWSoftware** [comment]
You've probably got the "Protected members of sealed classes" option in the Visibility category of project properties turned off which is the default.  When off, it removes the protected members from sealed classes.  Turn it on the member will be included in the docs and the links will then be resolvable even if it isn't usable outside of the class in which it appears.

**Comment by brinko99** [comment]
Yes, that's exactly it!

I see why it might be undesirable/unnecessary to document protected members in sealed classes. I'll need to reconsider my reference.

Thank you.
