### ISSUE TITLE
[Question] My help file builds successfully but only has one namespace

### ISSUE THREAD

**Issue by alex13lopez** [EWSoftware/SHFB#1044]
Hi, this is probably a noob question but I've been trying for so long now and I even looked up the FAQs and haven't found any solution...

So I have 2 libraries, in both of them I followed the same steps and for the first, the help file is built correctly displaying all namespaces with their public classes and interfaces.

Following the same steps with my second library I'm only able to get the main namespace for the repository and doesn't display that landing page where you can click on each namespace and be redirected to that namespace documentation.

The steps I followed are as described below:

1. Create a Documentation project on VS and add it to my solution
2. Enable API XML comments documentation on build for the project
3. Add as Documentation source both the XML with the comments and the .csproj
4. Delete the Content folder with the default topics that VS creates since I don't need conceptual topics only technical documentation of my API.

Is there any step I forgot doing in my second project and it's the reason why it's not working as expected?

**Comment by alex13lopez** [comment]
> You only need the .csproj as the documentation source.  SHFB will figure out what it needs from that (assemblies, references, and comments files).  If you delete the content folder, remove the content layout file too.  I assume you did since there would likely be build errors otherwise about the missing conceptual topics.  Assuming the APIs you want to document are public, they should appear.  If they're not public, they won't appear by default unless you enable the appropriate options in the Visibility project property category.
> 

Yeah maybe I didn't explain myself correctly I'll try to illustrate it with the following:

Imagine I have the following namespaces:

- MyLibrary.Repositories => This namespace has public classes and they are detected by the Help builder.

- MyLibrary.Repositories.Definition => This namespace only contains public interfaces. This should be detected by the help builder and documented but it doesn't at the moment.

- MyLibrary.Repositories.Implementation => This namespace contains the internal classes that implement the interfaces of the above namespace. As they aren't public they aren't detected as expected and not shown in the documentation.


But the thing is that the namespace MyLibrary.Repositories.Definitiom doesn't appear at all when it should.

**Comment by EWSoftware** [comment]
Can you provide an example I can build to duplicate the issue?

**Comment by alex13lopez** [comment]
Nvm, I fixed it. I deleted de documentation project and created it anew and now it works fine ! Also I left the title box empty this time, maybe that is what fixed the problem, leaving it here in case someone encounters the same issue:
![image](https://github.com/EWSoftware/SHFB/assets/72864689/3f588e3e-25d7-4e9f-8aca-be019ef46c6b)
