### ISSUE TITLE
Enable TOC using current presentation style

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#1046]
We are migrating to the current version from a rather old one (2020.3.6).

With the default presentation style of the old version, we had a table of contents on the left hand side, enabling navigation:

![image](https://github.com/EWSoftware/SHFB/assets/13708975/06abdf69-90e3-4ac8-9da8-10e1c6d98958)

The exact same .shfbproj now produces Website output that does not include such a table of contents:

![image](https://github.com/EWSoftware/SHFB/assets/13708975/689fe898-28ad-4f04-83bb-bd166903511a)

Reducing the browser window size causes a "show/hide toc" item to appear seems to suggest that one is intended to be present (but clicking it only adds/removes a bit of spacing):

![image](https://github.com/EWSoftware/SHFB/assets/13708975/6868b77f-5c6c-474b-b017-7276e22c9712)

The log has

```
Loading and initializing plug-ins...
Website Table of Contents Generator Version 2024.2.18.0
Copyright &#169; 2006-2024, Eric Woodruff, All Rights Reserved
```

which suggests something is running, just without producing a usable TOC in the final result.

Note: our build system leverages MSBuild imports (and Directory.Build.props) to keep the .shfbproj files small; unfortunately that does mean that the GUI can't be used on them (it seems to treat them as raw XML files).

However, if I use the standalone GUI to create a project from scratch, that lacks the TOC too.

What changes/additions need to be made to the project to make the TOC appear?

Potentially relevant sections of the .shfbproj (and the props/targets files it imports):

```xml
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
    <SHFBSchemaVersion>2017.9.26.0</SHFBSchemaVersion>
  </PropertyGroup>
```

```xml
  <PropertyGroup>
    <ComponentConfigurations>
      <ComponentConfig id="IntelliSense Component" enabled="True">
        <component id="IntelliSense Component">
          <output includeNamespaces="true" namespacesFile="Namespaces" folder="{@OutputFolder}\IntelliSense" boundedCapacity="1" />
        </component>
      </ComponentConfig>
    </ComponentConfigurations>
    <PlugInConfigurations>
    </PlugInConfigurations>
  </PropertyGroup>
```

```xml

  <PropertyGroup>
    <ContentPlacement>AboveNamespaces</ContentPlacement>
    <CopyrightText>$(AnubexCopyright)</CopyrightText>
    <HelpFileFormat Condition=" '$(HelpFileFormat)' == '' ">Website</HelpFileFormat>
    <Language>en-US</Language>
    <MaximumGroupParts>2</MaximumGroupParts>
    <MissingTags>Summary, Parameter, Returns, AutoDocumentCtors, Namespace, TypeParameter, IncludeTargets, AutoDocumentDispose</MissingTags>
    <NamespaceGrouping>False</NamespaceGrouping>
    <NamingMethod>Guid</NamingMethod>
    <Preliminary>true</Preliminary>
    <RootNamespaceContainer>True</RootNamespaceContainer>
    <SdkLinkTarget>Blank</SdkLinkTarget>
    <SyntaxFilters>C#</SyntaxFilters>
    <VendorName>Anubex</VendorName>
    <VisibleItems>Attributes, ExplicitInterfaceImplementations, InheritedMembers, InheritedFrameworkMembers, Protected, ProtectedInternalAsProtected</VisibleItems>
  </PropertyGroup>
```

```xml

  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)resources\anubex-logo\**\*.*">
      <Link>icons\anubex-logo\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <ExcludeFromToc>True</ExcludeFromToc>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <TransformComponentArguments>
      <Argument Key="logoFile" Value="anubex-logo/anubex.tiny.png" />
      <Argument Key="logoHeight" Value="" />
      <Argument Key="logoWidth" Value="" />
      <Argument Key="logoAltText" Value="Anubex" />
      <Argument Key="logoPlacement" Value="right" />
      <Argument Key="logoAlignment" Value="left" />
      <Argument Key="maxVersionParts" Value="" />
      <Argument Key="defaultLanguage" Value="cs" />
    </TransformComponentArguments>
  </PropertyGroup>
```

**Comment by EWSoftware** [comment]
If viewing it locally, make sure you're using the option to view the website output.  If you just open a file from the folder, the script will be blocked and it will cause all sorts of odd issues with the page display.

**Comment by Zastai** [comment]
How do you mean "option to view the website output"? In the GUI? We don't use that.
JavaScript is enabled in the browser though, so scripts should work.

This feels like a fairly significant regression for us; we ship the HTML docs with our libraries, and without the TOC the usability is rather limited.

**Comment by Zastai** [comment]
OK, just threw the output into IIS and sure enough, that way the table of contents does show up.

**Comment by EWSoftware** [comment]
It's the browser that blocks the script so I have no control over it.  There's an option in the standalone GUI and the Visual Studio extension to view the help output.  For website output, it will launch an IIS Express instance to view the output so that scripts work.
