### ISSUE TITLE
Cannot edit summaries when SharePoint project is included.

### ISSUE THREAD

**Issue by AcuCHiro** [EWSoftware/SHFB#105]
Ive tried to created document project in my solution, in included the sharepoint project but its giving me an error. I removed the SharePoint Project and its working.

Can any body help me on this project. I really need to document the SharePoint project too.

![Uploading Sandcastle SharePoint Issue.png…]()

**Comment by EWSoftware** [comment]
I've never used SharePoint or created projects for it.  Are they managed code?  If not, you won't be able to document them with SHFB.  If they and you can upload an example or e-mail it to me, I'll take a look at it.

**Comment by AcuCHiro** [comment]
Here.. please see attached

**Comment by AcuCHiro** [comment]
![sandcastle sharepoint issue](https://cloud.githubusercontent.com/assets/11975596/7885996/8cbd9138-0659-11e5-9c51-0c2075728745.png)


see attached...

**Comment by EWSoftware** [comment]
By "example", I meant an actual SharePoint and SHFB project that I can test and duplicate the issue, not a screen shot.

That said, if it's failing in the Namespace Summary dialog, you should be able to build the project normally as stated in the error message to get the actual reason the build is failing.

**Comment by AcuCHiro** [comment]
Please see attached File. Use password “Sample01” to access it. Thanks HIRO

**Comment by EWSoftware** [comment]
Did you e-mail it to me?  If so, it didn't arrive.  If you replied to the GitHub message it probably dropped it.  Try sending it to my normal e-mail address which you can find in the footer of the pages in the SHFB help file.

**Comment by AcuCHiro** [comment]
Please see attached.

**Comment by EWSoftware** [comment]
Two problems:

1. From the screen shot on GitHub, you appear to be using the standalone GUI.  From the build log in the download, I can see that it didn’t find the bin\Debug copy of the assembly.  The bin\Release version does exist so be sure in future to set the Configuration and Platform settings in the standalone GUI’s toolbar to the configuration/platform you want to use.  In this case, set the configuration to Release and it will find the existing assembly.
2. In the example SharePoint project, the one and only class in it had no explicit visibility declared so it was private and thus not included in the build.  Either explicitly declare classes you want to include as public or enable the Include Private Members and/or Include Internal Members options found in the Visibility category of project properties.  If you do so, you may need to use the API Filter to remove unwanted types and members from the help file.
