### ISSUE TITLE
An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException

### ISSUE THREAD

**Issue by mgzhenhong** [EWSoftware/SHFB#1055]
SHFB: Error BE0065: BUILD FAILED: TransformComponent: [Overload:ASW.Utility.ActionResult.WhenSuccessRun] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiTypeMemberLists(TopicTransformationCore transformation)
   在 Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderApiMemberList(TopicTransformationCore transformation)
   在 Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderTopic()
   在 Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   在 SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(String componentName, MessageLevel level, String key, String message) 位置 C:\GH\SHFB\SHFB\Source\SandcastleBuilderUtils\BuildEngine\BuildAssemblerInternal.cs:行号 275
   在 Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentCore.WriteMessage(String key, MessageLevel level, String message, Object[] args) 位置 C:\GH\SHFB\SHFB\Source\SandcastleCore\BuildAssembler\BuildComponent\BuildComponentCore.cs:行号 160
   在 Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   在 Sandcastle.Tools.BuildComponents.SwitchComponent.Apply(XmlDocument document, String key)
   在 SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.Apply(IEnumerable`1 topics) 位置 C:\GH\SHFB\SHFB\Source\SandcastleBuilderUtils\BuildEngine\BuildAssemblerInternal.cs:行号 431
   在 SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_0() 位置 C:\GH\SHFB\SHFB\Source\SandcastleBuilderUtils\BuildEngine\BuildAssemblerInternal.cs:行号 339
   在 System.Threading.Tasks.Task.Execute()

发生一个或多个错误。
   在 System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.BuildTopics() 位置 C:\GH\SHFB\SHFB\Source\SandcastleBuilderUtils\BuildEngine\BuildAssemblerInternal.cs:行号 365
   在 SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build() 位置 C:\GH\SHFB\SHFB\Source\SandcastleBuilderUtils\BuildEngine\BuildProcess.cs:行号 1272

SHFB Version is 2023.7.8.0

![code_capture](https://github.com/EWSoftware/SHFB/assets/30331534/85e634e3-ce6d-4df8-affd-483367cec7ea)

**Comment by EWSoftware** [comment]
I can't duplicate this error with the latest release.  Can you try it with that?  If it still fails, attach an example that I can use to reproduce the error.

**Comment by mgzhenhong** [comment]
it works ok in the last version, thanks

**Comment by mgzhenhong** [comment]
it works ok in the last version, thanks
