### ISSUE TITLE
Problem with installer when only VS 2022 is installed.

### ISSUE THREAD

**Issue by stevejackson80** [EWSoftware/SHFB#1056]
Firstly I just want to say that this is a cracking project - and has dug me out of a hole when it comes to building respectable looking documentation...so thank you for all of the effort that has gone into SHFB thus far.

I have, however, run into a small issue.

The installer gets itself into a right state if you have VS 2022 installed, but not 2017/2019.  Specifically the point where it tries to install the VSIX extensions.  As it cannot detect VS 2017/2019 it errors and then won't let you install the VS 2022 version...it just gets stuck.

I got around this by manually editing the InstallerConfiguration.xml and removing the reference to the 2017/2019 VSIX file - worked like a charm.

Frustratingly the latter section regarding installing the MAML schema and snippets _DO_ detect that VS 2017/2019 is not installed and just ignores that option - it then proceeds to install said items into VS 2022 (Though Intellisense in VS 2022 for .AML files is not working, has Microsoft changed something perhaps?)

I'm not currently in a position to share screen shots of the issue, however later tonight (will be quite late - UK based) I will replicate on a different machine to share said screen shots to better describe what it is doing.

Once again, thanks for making and maintaining this project.

**Comment by stevejackson80** [comment]
Ok, I can't replicate on a clean machine with just VS 2022 installed - so it must be some odd combination, perhaps where VS Build Tools 2019 is installed rather than the whole VS 2019?

I'll try to do some more digging to see if I can find the root cause - though I am not sure if it is possible to work out the specific type of VS that is installed (IE, Build Tools).

**Comment by hikariuk** [comment]
I can pretty much confirm that the issue is if you have VS Build Tools installed; once I removed them it worked fine. 

For what it's worth, the detected versions list in the installer does say it's "Build Tools", so at worst a clumsy glob to ignore VS installations with "Build Tools" in their name might work. Although I strongly suspect that might be a localized name, so it would be far from perfect.

**Comment by warent** [comment]
On the off chance this fixes it for anyone else: in my case it was just due to Visual Studio being freshly installed without reboot. Rebooting the machine fixed this issue.

**Comment by EWSoftware** [comment]
The easiest workaround for odd cases where it's detecting the build tools or not detecting a version it should is to just run the VSIX installer from the .\InstallResources folder.  You can then skip past it and carry on with the rest of the steps as needed.
