### ISSUE TITLE
Sandcastle is running out of memory

### ISSUE THREAD

**Issue by dasdebas** [EWSoftware/SHFB#1059]
Hi There:
sandcastle is failing in the last steps ( CompilingHelpFile) because of no memory available error.  I closed all other application, still getting same error, tried other things still fails. It might be that sandcastle is not able to process 130,255 generated html files when compiling help files. What can we do? My machine has 32GB physical  memory, sandcastle process if hardly taking max ~5GB. I also tried x64 ( see the attached image), still fails. Your help is greatly appreciated. Thanks
........................
CompilingHelpFile
 
SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

pls see the attached image

![sandcastle_memory](https://github.com/EWSoftware/SHFB/assets/170025432/1f6c20da-64b7-4d8a-8d95-fb27dc3b2ba2)

**Comment by EWSoftware** [comment]
The x64 setting applies to the platform selected for the solution/project documentation sources.  SHFB is itself 64-bit so no issues there.  If you're building a Help 1 file though, that is the issue since the help 1 compiler is a 32-bit application so won't use all available memory.  There's nothing SHFB can do about that.  Switching to website or Open XML output for standalone help are the only alternatives.

**Comment by dasdebas** [comment]
Thanks a lot Eric. I was able to generate help using one of the 2 approaches you mentioned.

**Comment by dasdebas** [comment]
can 64 bit of "help 1 compiler" be integrated with SHFB? I see many posting in web due to memory limit issue, integrating 64 bits of  "help 1 compiler" will help a lot. Thanks

**Comment by EWSoftware** [comment]
As far as I know there is no 64-bit version of the help 1 compiler (part of the HTML Help Workshop).  It's really old and 32-bit only.

**Comment by VBWebprofi** [comment]
> can 64 bit of "help 1 compiler" be integrated with SHFB? I see many posting in web due to memory limit issue, integrating 64 bits of "help 1 compiler" will help a lot. Thanks

You might try the HTML Help 1 Compiler from Visual Studio resources, see my HowTo  issue #1060.

**Comment by EWSoftware** [comment]
They're still the same 32-bit components so it likely won't make any difference.

**Comment by VBWebprofi** [comment]
It could be a newer version might manage the memory better than an old one. This was the intension behind.
