### ISSUE TITLE
Resources not documented

### ISSUE THREAD

**Issue by Ardamecoder** [EWSoftware/SHFB#106]
I have a class library with a lot of resource files. They are converted with the custom tool PublicResXFileCodeGenerator and are public. So this results in public classes with static properties. None of all my resources is documented. Why?

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseTool.ResourceLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LicenseTool.ResourceLibrary.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }

**Comment by EWSoftware** [comment]
They are marked as compiler generated.  Compiler generated classes are skipped since they are typically unwanted and undocumented.  There isn't currently an option to include compiler generated types.  It could be added.  However, if enabled, you may end up having to filter out other unwanted types with the API filter.  I suppose that could be mitigated somewhat by only including public compiler generated types if enabled.

**Comment by Ardamecoder** [comment]
Hi. Can't find an option "include public compiler generated types" in project properties window.

**Comment by EWSoftware** [comment]
The API filter is based on what is contained in the reflection information file.  As such, it can't know what can be filtered out until its generated.  You'd have to regenerate the filter every time the assembly changed to pick up any new compiler generated stuff to omit by default.  Not the most efficient or user friendly way of doing it.

The option to enable inclusion for public compiler generated types and then using the filter to remove what you don't want is the better option.  The vast majority of compiler generated types are private or internal so unless you're including private/internal stuff, they won't show up anyway.  Chances are good that you'll only see what you want and won't have to use the API filter at all unless there's something you really don't want included.

**Comment by Ardamecoder** [comment]
You're fully right. Best will be just a visibility option for compiler generated staff. Will such a change be a big thing?

**Comment by EWSoftware** [comment]
No, it should be pretty straightforward.  I'll see about getting it into the next release.

**Comment by Ardamecoder** [comment]
Nice. Is there already a schedule?

**Comment by EWSoftware** [comment]
No, I don't have a set schedule.
