### ISSUE TITLE
HowTo - Install current HTML Help 1 Compiler for Client, Server or Docker image

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#1060]
Here I like to share some information about the installation of a current HTML Help 1 Compiler from Microsoft sources.

## Required components of HTML Help 1 Compiler

| Path | Component | ActiveX/COM<br/>registration | Source |
| --- | --- | :-: | --- |
| C:\Program Files (x86)\HTML Help Workshop | hha.dll |  | Visual Studio |
| C:\Program Files (x86)\HTML Help Workshop | hhc.exe |  | Visual Studio |
| C:\Program Files (x86)\HTML Help Workshop | itcc.dll | X | Visual Studio |
| C:\Windows\SysWOW64 | itircl.dll | X | WIndows Client |
| C:\Windows\SysWOW64 | itss.dll | X | WIndows Client |

### Install with current Visual Studio version

- Start Visual Studio Installer
- Choose "Modify" on entry point
- Choose "Individual Components" / "Compiler, BuildTools and Runtimes" / "MSVC v\<Version\> C++x64/x86-Buildtools (newest)"  
  (you can choose a specific version instead "newest" also)

### Getting files only

- Download Visual Studio (BuildTools) installer (https://visualstudio.microsoft.com/downloads/)
- Let create a "Layout"  
  `vs_<VSType> --add Microsoft.VisualStudio.Component.VC.ATLMFC --layout <OutputDir>`
- Lookup directory "\<OutputDir\>\Microsoft.VisualCpp.HTMLHelpWorkshop.Msi,version=\<Version\>"
- Extract file "cab1.cab" into default HTML Help 1 Compiler directory "C:\Program Files (x86)\HTML Help Workshop"  
  `expand -F:* "<OutputDir>\Microsoft.VisualCpp.HTMLHelpWorkshop.Msi,version=<Version>\cab1.cab" "C:\Program Files (x86)\HTML Help Workshop"`
- Rename files "FL_*" without that prefix
- Register file "itcc.dll" with regsvr32  
  `C:\Windows\SysWOW64\regsvr32 "C:\Program Files (x86)\HTML Help Workshop\itcc.dll"`
- On a server you might to copy and register client files "itircl.dll" and "itss.dll" also

### Install on a Docker image with Microsoft .NET SDK

Here as sample I will use the image pair:  
`mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019`   and  
`mcr.microsoft.com/windows:ltsc2019`.

- Use image `mcr.microsoft.com/windows:ltsc2019` as "windowsClient" stage
- Use image `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019` as "htmlWorkshop" stage
  - Install component "Microsoft.VisualStudio.Component.VC.ATLMFC" from Visual Studio BuildTools
- Use image `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019` for your final image
  - Copy "itircl.dll" and "itss.dll" from stage "windowsClient"
  - Copy HTML Help 1 Compiler from stage "htmlWorkshop"
  - Register files "itcc.dll", "itircl.dll" and "itss.dll"
 
Here a partial `Dockerfile` sample:

```docker
# escape=`

FROM mcr.microsoft.com/windows:ltsc2019 as windowsClient


FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 as htmlWorkshop

SHELL ["cmd", "/S", "/C"]

RUN echo Resolving / Downloading Visual Studio Build Tools 17 ... `
    && curl -fSLo vs_BuildTools.exe https://aka.ms/vs/17/release/vs_BuildTools.exe `
    && echo Installing ... `
    && start /w vs_BuildTools modify `
         --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools" `
         --add Microsoft.VisualStudio.Component.VC.ATLMFC `
         --quiet --norestart --nocache --wait


FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

SHELL ["cmd", "/S", "/C"]

COPY --from=windowsClient C:\Windows\SysWOW64\itircl.dll C:\Windows\SysWOW64

RUN C:\Windows\SysWOW64\regsvr32.exe /s C:\Windows\SysWOW64\itircl.dll

COPY --from=windowsClient C:\Windows\SysWOW64\itss.dll C:\Windows\SysWOW64

RUN C:\Windows\SysWOW64\regsvr32.exe /s C:\Windows\SysWOW64\itss.dll

COPY --from=htmlWorkshop ["C:\\Program Files (x86)\\HTML Help Workshop", "C:\\Program Files (x86)\\HTML Help Workshop"]

RUN C:\Windows\SysWOW64\regsvr32.exe /s "C:\Program Files (x86)\HTML Help Workshop\itcc.dll"

```

**Comment by VBWebprofi** [comment]
## In addition to HTML Help 1 Compiler, here the way to install SHFB in a Docker image:

```docker
# escape=`

FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

SHELL ["cmd", "/S", "/C"]

# Install Sandcastle Help File Builder (https://github.com/EWSoftware/SHFB/releases)
RUN echo Resolving / Downloading Sandcastle Help File Builder ... `
    && curl -fSLo SHFBInstaller.zip https://github.com/EWSoftware/SHFB/releases/download/2024.2.18.0/SHFBInstaller_2024.2.18.0.zip `
    && echo Extracting ... `
    && powershell -Command "Expand-Archive SHFBInstaller.zip SHFBInstaller" `
    && echo Installing ... `
    && msiexec /i SHFBInstaller\InstallResources\SandcastleHelpFileBuilder.msi ADDLOCAL=ALL /qn /norestart `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && rmdir SHFBInstaller /S /Q `
    && del SHFBInstaller.zip
```

**Comment by VBWebprofi** [comment]
Hint: Installation of SHFB in Docker is documented in issue #1017 .

**Comment by EWSoftware** [comment]
I've added links to this and #1017 in the "XCOPY/NuGet Build Server Deployment" help topic for the next release.
