### ISSUE TITLE
Build fails with "System.Drawing.Common is not supported on this platform" error when using '<alert>' element in '.aml' conceptual doc and 'Open XML Document' output style

### ISSUE THREAD

**Issue by ESS-1** [EWSoftware/SHFB#1062]
When creating a new SHFB project with the 'Open XML Document' output style and adding an <alert> element to a .aml conceptual document, the build fails with the following error:

`SHFB(0,0): error BE0065: BUILD FAILED: System.Drawing.Common is not supported on this platform.`

This issue is reproduced with Visual Studio 2022 version 17.10.0 but is not reproduced with version 17.7.4.

Environment:
SHFB ver. 2024.2.18.0
Visual Studio 2022 ver. 17.10.0
Operating System: Windows 11 22H2

A sample project that reproduces the issue is attached: [SHFB-Issue.zip](https://github.com/EWSoftware/SHFB/files/15435762/SHFB-Issue.zip)

**Comment by ESS-1** [comment]
This issue occurs because Visual Studio loads the System.Drawing.Common.dll from "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\PublicAssemblies\". The file located there is a .NET Standard 2.0 version of the DLL, which does not support the Image class (all its methods throw exceptions). However, SHFB expects the .NET 4.6.1 version of the DLL. Does anyone have ideas on how to resolve this?

**Comment by EWSoftware** [comment]
This is new behavior for VS 2022.  As a workaround for now until I can look into fixing it, if you have VS 2019 it works as would build from the command line with MSBuild or dotnet build.

**Comment by ESS-1** [comment]
Thank you! I didn't think to try MSBuild. This workaround works for me.
