### ISSUE TITLE
Add some text in HTML documentation

### ISSUE THREAD

**Issue by happydaf** [EWSoftware/SHFB#1063]
Hi. Please tell me how to add some text in HTML documentation after SandCastle.

For example I need to insert the next code in resulting HTML files:

<script async src="https://www.googletagmanager.com/gtag/js?id=G-Nwe34535rqwrwH"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-Nwe34535rqwrwH');
</script>

**Comment by EWSoftware** [comment]
Use the Website Ad Content property in the [Help 1/Website](https://ewsoftware.github.io/SHFB/html/7d28bf8f-923f-44c1-83e1-337a416947a1.htm) property category.  It lets you add script like the above after the page footer.

**Comment by SautinSoftSupport** [comment]
Yes. I know about this option but I get the next issues: 
![1](https://github.com/EWSoftware/SHFB/assets/79837963/e8d3807c-7a7d-4d67-8851-1ae09d2bd700)
![2](https://github.com/EWSoftware/SHFB/assets/79837963/f6a82a20-74fa-4b75-80fc-090c03fdd7af)

**Comment by EWSoftware** [comment]
Content items including that property's content are stored in XML files and it appears it doesn't like the async attribute since it isn't being assigned a value.  Removing it should work around the issue.
