### ISSUE TITLE
Comment XML not recognized

### ISSUE THREAD

**Issue by warent** [EWSoftware/SHFB#1064]
Hey there, thank you for your awesome work on this project.

Using Visual Studio 2022, I'm trying to generate docs for my open source project: https://github.com/Heavenlode/HLNC

The entire SHFB project is here: https://github.com/Heavenlode/HLNC/tree/main/Documentation

It seems to mostly work: https://heavenlode.github.io/HLNC

Except I'm getting `Missing <summary> documentation` even though it exists. For example:
https://heavenlode.github.io/HLNC/html/T_HLNC_NetworkRunner.htm
https://github.com/Heavenlode/HLNC/blob/main/addons/HLNC/NetworkRunner.cs#L10-L12

I noticed the build logs say `Unknown reference link target` for various things, but I'm not sure why or if it is related.

I've been researching this fairly extensively before creating this issue. In particular, two that I found which seemed related are these: https://github.com/EWSoftware/SHFB/issues/715 https://github.com/EWSoftware/SHFB/issues/1004

Unfortunately, neither of these fixed my problem. Any ideas what I might be doing wrong here?

Thanks for your help.

**Comment by warent** [comment]
Hello, just gently following up on this. I tried my best to keep the info to-the-point and condensed to minimize the time needed on this 🙏 

Let me know if there's anything else I can do to help with this.

**Comment by EWSoftware** [comment]
I downloaded your project and there are some issues.  It's missing a package reference for Newtonsoft.Json which I added to get it to build.  It also isn't generating any XML comments file.  I added `<GenerateDocumentationFile>True</GenerateDocumentationFile>` to the project and it generates one.  At that point it does generate XML comments but many public types are missing them.  Your example above, `NetworkRunner` does have some but not all public members documented and the comments that are there do show up as expected in the generated help.

**Comment by warent** [comment]
Oops, thanks for catching the dependency issue. That is newer and unrelated.

Yes, the issue was the missing `<GenerateDocumentationFile>True</GenerateDocumentationFile>`. I'm a dotnet/C# noob and wasn't aware of this simple little thing.

It's all working now. Thank you so much for your help!

**Comment by warent** [comment]
For future reference if anyone else comes across this, I believe it's documented here: https://ewsoftware.github.io/XMLCommentsGuide/html/57C91630-95D6-4E3E-AF24-3415CC569AC8.htm

I either misunderstood what this document was saying, or just overlooked it entirely. Either way, it's my bad Thanks again sir
