### ISSUE TITLE
Linked content files in SHFB project get not resolved

### ISSUE THREAD

**Issue by NETSphereSoft** [EWSoftware/SHFB#1065]
I want share particular content files between different SHFB projects. So I wanted to use the "Add" / "Existing Item..." file dialog with the choice at "Add" button for "Add As Link".

This happens then in such XML entry in SHFB project file:

```xml
<ItemGroup>
  <None Include="..\..\OtherProject\Source\SubProject\HelpContent\Configuration.aml">
    <Link>HelpContent\OtherProject\Configuration.aml</Link>
  </None>
  <None Include="..\..\OtherProject\Source\SubProject\HelpContent\Samples\DialogCaptions.xml">
    <Link>HelpContent\Samples\DialogCaptions.xml</Link>
  </None>
</ItemGroup>
```

The `Configuration.aml` get solved correctly for processing. Inside the `Configuration.aml` is a `code` tag with `source="HelpContent\Samples\DialogCaptions.xml"`. No the processing tries to find the `HelpContent\Samples\DialogCaptions.xml` "physically" in the consuming SHF project, it don't uses the existing "virtual" reference `HelpContent\Samples\DialogCaptions.xml` from the project file to the "physical" content `..\..\OtherProject\Source\SubProject\HelpContent\Samples\DialogCaptions.xml`. Is happens in the Error

*MAML code*

```xml
<code language="xml"
      numberLines="true"
      source="HelpContent\Samples\DialogCaptions.xml" />
```

*Error message*

```
SHFB(0,0): error BE0065: CodeBlockComponent: [774c4eb0-dc24-4359-8149-8e879c6db664] Unable to load source file 'C:\_Storage\Projects\Project\Project.Help\HelpContent\Samples\DialogCaptions.xml'.  Cause: Could not find file 'C:\_Storage\Projects\Project\Project.Help\HelpContent\HelpContent\Samples\DialogCaptions.xml'.
```
 
This should be solved to lookup linked content files when physically don't exist.

Relevant part seems to be [CodeBlockComponent.LoadCodeBlock](https://github.com/EWSoftware/SHFB/blob/9d46bf03f639cb91a1a5b8eb0c7cf7b428d5f21b/SHFB/Source/BuildAssembler/BuildComponents/CodeBlockComponent.cs#L877) but don't see a way to the SHFB project from this class.

**Comment by NETSphereSoft** [comment]
Here a sample project to illustrate the behavior.

[SHFB.Issue.1065.zip](https://github.com/user-attachments/files/15825216/SHFB.Issue.1065.zip)

In the configuration `DebugHelp` it compiles the SHFB help projects and in `Debug` is a demonstration how i could be solved with the evaluation of SHFB project file. Finally something how the variable `linkItems` contains should be available in [CodeBlockComponent.LoadCodeBlock](https://github.com/EWSoftware/SHFB/blob/9d46bf03f639cb91a1a5b8eb0c7cf7b428d5f21b/SHFB/Source/BuildAssembler/BuildComponents/CodeBlockComponent.cs#L877).

So there could a check added

```cs
sourceFile = Environment.ExpandEnvironmentVariables(sourceFile);

// Changed to proceed with GetFullPath in general in next step
if(!Path.IsPathRooted(sourceFile))
  sourceFile = Path.Combine(basePath, sourceFile);

// Ensure we have the absolute path in hand for comparison
souceFile = Path.GetFullPath(souceFile);

if((!File.Exists(souceFile)) && linkItems.ContainsKey(sourceFile))
  sourceFile = linkItems[sourceFile]
```

**Comment by EWSoftware** [comment]
The code block component has no knowledge of the MS Build project, any of its properties such as linked items, or even the path to the file its processing.  Like all other components, it just gets the document content to transform.  It always resolves relative paths based on the base path specified in its configuration.  If one isn't specified, it is defaulted to the project folder when the configuration file is generated.  Assuming all files you reference are in the same place, you may be able to specify the common path there.  Using your example, you'd add the Code Block Component to the project and set the path to *{@HtmlEncProjectFolder}..\SHFB.Issue.1065.HelpProjectOther*.  It then finds the files it needs.

**Comment by NETSphereSoft** [comment]
That's not what I expected. In that case ALL code samples for code blocks must be in that configured path and it's for one language only.

I look for a solution that takes care for several "linked" project parts and in several languages, actual C#, VB and C++.

**Comment by NETSphereSoft** [comment]
Sorry, haven't read carefully in the dialog. C# is the default language, so I can change the concept and use this component together with the `PreBuildEvent` and `PostBuildEvent` I can copy the code block files in a specific directory (working directory can't be used, will be cleaned up during build process) for code blocks and can this path configure in the component. Later then the path of code blocks get removed.

Thanks, it's working now in the expected behavior, but different to configure.

**Comment by NETSphereSoft** [comment]
Sorry, haven't read carefully in the dialog. C# is the default language, so I can change the concept and use this component together with the `PreBuildEvent` and `PostBuildEvent` I can copy the code block files in a specific directory (working directory can't be used, will be cleaned up during build process) for code blocks and can this path configure in the component. Later then the path of code blocks get removed.

Thanks, it's working now in the expected behavior, but different to configure.
