### ISSUE TITLE
Possible to change first letter of class name to lower case?

### ISSUE THREAD

**Issue by donaldlim** [EWSoftware/SHFB#1066]
I need to change first letter of class name to lower case, is that possible?
e.g. File.Move->file.Move

**Comment by EWSoftware** [comment]
No, it documents it as is.  You'd have to change your code to match.  If this is for a particular language syntax, you could probably create your own syntax generator so that the syntax section shows the method syntax based on that language.

**Comment by donaldlim** [comment]
Many thanks for your reply. I am new to this project, which specific part of the code should be altered? I am using OpenXML to generate help docs.

**Comment by EWSoftware** [comment]
Assuming you want to create a syntax generator, see the [topic on creating one](https://ewsoftware.github.io/SHFB/html/5e80d139-811c-48ed-9b52-dcd8a3f5aef3.htm).  If you want to base it on one of the existing ones, the code for them can be found [here](https://github.com/EWSoftware/SHFB/tree/master/SHFB/Source/BuildAssembler/SyntaxComponents).

**Comment by donaldlim** [comment]
Thanks, I will try it out.
