### ISSUE TITLE
Class Program not documented

### ISSUE THREAD

**Issue by Ardamecoder** [EWSoftware/SHFB#107]
I have a  class Program in two namespaces. In both namespaces I can't find that class in the documentation. Why?

-------------------------------------------------

    /// <summary>
    /// The main program of the gathering command line tool
    /// </summary>
    class Program
    {
        
        /// <summary>
        /// Main method for the tool
        /// </summary>
        /// <param name="args">The arguments given on command line</param>
        /// <seealso cref="Gather"/>
        /// <seealso cref="AdIntegration"/>
        static void Main(string[] args)

-------------------------------------------------

    /// <summary>
    /// The main program of the gathering windows service
    /// </summary>
    static class Program
    {

        /// <summary>
        /// The main entry point for the application. Instantiates the service class and launches the Run method.
        /// </summary>
        static void Main()

**Comment by EWSoftware** [comment]
They're both private.  Lack of an explicit visibility makes them private.  The same goes for the members.  You can enable the "private members" and, if you have them "internal members" visibility options to include them.  Just be aware that you'll probably end up with a lot of other private and internal stuff that you will likely need to use the API filter on to remove.

**Comment by Ardamecoder** [comment]
Now clear. Thanks for your help.
