### ISSUE TITLE
SHFB complains of missing namespace doc even when provided.

### ISSUE THREAD

**Issue by PaulStSmith** [EWSoftware/SHFB#1077]
I created a standalone project in VS2022 and set my Documentation source to several projects.
SHFB read those projects correctly and loaded all the namespaces.
Then I went to Project Properties > Summaries > Edit namespace Summaries
All the namespaces were listed correctly.
I filled the summaries for all namespaces.
Compiled the SHFB project and got several warnings:

```
SHFB(0,0): warning BE0066: ShowMissingComponent: [N:MyNamespace1] Missing <summary> documentation
SHFB(0,0): warning BE0066: ShowMissingComponent: [N:MyNamespace2] Missing <summary> documentation
SHFB(0,0): warning BE0066: ShowMissingComponent: [N:MyNamespace3] Missing <summary> documentation
SHFB(0,0): warning BE0066: ShowMissingComponent: [N:MyNamespace4] Missing <summary> documentation
SHFB(0,0): warning BE0066: ShowMissingComponent: [N:MyNamespace5] Missing <summary> documentation
```
I checked in the SHFB project file and, sure enough, there they were:

``` lang-xml
<NamespaceSummaries>
  <NamespaceSummaryItem name="MyNamespace1" isDocumented="True">...</NamespaceSummaryItem>
  <NamespaceSummaryItem name="MyNamespace2" isDocumented="True">...</NamespaceSummaryItem>
  <NamespaceSummaryItem name="MyNamespace3" isDocumented="True">...</NamespaceSummaryItem>
  <NamespaceSummaryItem name="MyNamespace4" isDocumented="True">...</NamespaceSummaryItem>
  <NamespaceSummaryItem name="MyNamespace5" isDocumented="True">...</NamespaceSummaryItem>
</NamespaceSummaries>
```

I have other SHFB project, but this one is not standalone, meaning, I have it in the same solution as the programs/libraries begin documented. This other project compiles without problems.

**Comment by EWSoftware** [comment]
Can you attach an example that I can use to reproduce the issue?

**Comment by PaulStSmith** [comment]
The attached ZIP file contains the SHFB project with the bare minimum to replicate the problem.
The SHFB solution is in `Telecom.Documentation\Telecom.Documentation.sln`

[Documentation.zip](https://github.com/user-attachments/files/16663482/Documentation.zip)

**Comment by EWSoftware** [comment]
The first two namespaces have an invalid `br` element.  Move the slash to the end of the element so that they are self-closing and it will fix the issue.  There's an incorrect condition in the namespace generation code that no longer applies that's eating the exception in the build.  I've removed it so that such errors are reported in the next release.
