### ISSUE TITLE
Can't install Visual Studio Package 

### ISSUE THREAD

**Issue by UlliBien** [EWSoftware/SHFB#1081]
Visual Studio 2022, Community 2022 (64-Bit), Version 17.11.2

VSIX installer throws an error. This is the log:

07.09.2024 18:22:42 - Microsoft VSIX Installer
07.09.2024 18:22:42 - -------------------------------------------
07.09.2024 18:22:42 - vsixinstaller.exe version:
07.09.2024 18:22:42 - 17.11.435+d5e02aaeb0
07.09.2024 18:22:42 - -------------------------------------------
07.09.2024 18:22:42 - Command line parameters:
07.09.2024 18:22:42 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\bieno\Desktop\shfb\InstallResources\SHFBVisualStudioPackage_VS2017And2019.vsix
07.09.2024 18:22:42 - -------------------------------------------
07.09.2024 18:22:42 - Microsoft VSIX Installer
07.09.2024 18:22:42 - -------------------------------------------
07.09.2024 18:22:42 - Skipping product Microsoft.VisualStudio.Product.BuildTools (c94018ca) since it does not support extensions
07.09.2024 18:22:42 - Initializing Install...
07.09.2024 18:22:42 - Er wird nach passenden Produkten gesucht...
07.09.2024 18:22:43 - Installiertes Produkt gefunden - Visual Studio Community 2022
07.09.2024 18:22:43 - Installiertes Produkt gefunden - Globaler Pfad
07.09.2024 18:22:43 - Erweiterungsdetails...
07.09.2024 18:22:43 - 	Identifier         : c997d569-ee8e-4947-a46f-9a0717ce39a0
07.09.2024 18:22:43 - 	Name               : SHFB (VS2017 and VS2019)
07.09.2024 18:22:43 - 	Author             : EWSoftware
07.09.2024 18:22:43 - 	Version            : 2024.2.18.0
07.09.2024 18:22:43 - 	Description        : Visual Studio integration for the Sandcastle Help File Builder.
07.09.2024 18:22:43 - 	Locale             : en-US
07.09.2024 18:22:43 - 	MoreInfoURL        : https://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm
07.09.2024 18:22:43 - 	InstalledByMSI     : False
07.09.2024 18:22:43 - 	SupportedFrameworkVersionRange : [4.5,)
07.09.2024 18:22:43 - 	SignatureState     : Unsigned
07.09.2024 18:22:43 - 	Unterstützte Produkte : 
07.09.2024 18:22:43 - 		Microsoft.VisualStudio.Community
07.09.2024 18:22:43 - 			Version : [15.0,17.0)
07.09.2024 18:22:43 - 			ProductArchitecture : x86
07.09.2024 18:22:43 - 	Verweise           : 
07.09.2024 18:22:43 - 	Voraussetzungen    : 
07.09.2024 18:22:43 - 		-------------------------------------------------------
07.09.2024 18:22:43 - 		Identifier   : Microsoft.Component.MSBuild
07.09.2024 18:22:43 - 		Name         : MSBuild
07.09.2024 18:22:43 - 		Version      : [15.0,)
07.09.2024 18:22:43 - 		-------------------------------------------------------
07.09.2024 18:22:43 - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
07.09.2024 18:22:43 - 		Name         : .NET desktop development tools
07.09.2024 18:22:43 - 		Version      : [15.0,)
07.09.2024 18:22:43 - Signaturdetails...
07.09.2024 18:22:43 - 	Extension is not signed.
07.09.2024 18:22:43 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

**Comment by EWSoftware** [comment]
Your log shows that you're trying to install the 2017/2019 version of the extension.  Use the package for VS 2022 instead (SHFBVisualStudioPackage_VS2022AndLater.vsix).  If you're using the guided installer, it can sometimes detect the build tools from 2017/2019 and tries to run the VSIX installer.  If that's the case, just run the installer manually from the .\InstallResourcesFolder and skip the step in the guided installer.
