### ISSUE TITLE
Duplicate file in latest release

### ISSUE THREAD

**Issue by RichardD2** [EWSoftware/SHFB#1082]
The SHFBInstaller_2024.9.12.0.zip file for the latest release contains two copies of the `InstallerConfiguration.xml` file:

![image](https://github.com/user-attachments/assets/25019587-53bc-4c6e-adb4-39ebefad89e3)

This duplicate file is not visible if you open the file in Windows Explorer, but it is visible if you use 7zip.

**Comment by EWSoftware** [comment]
It must be a problem with 7zip as I don't see a duplicate in PKZip either.  Extracting the file only gets one copy and it's the right one.  There's no prompt to overwrite an existing copy either.

**Comment by RichardD2** [comment]
Interesting - thanks for checking. The built-in `ZipFile` class and `SharpZipLib` also only show a single entry for that file.
