### ISSUE TITLE
How to install extension from source?

### ISSUE THREAD

**Issue by PaulStSmith** [EWSoftware/SHFB#1089]
Currently, the installer is failing to install the VSIX (see https://github.com/EWSoftware/SHFB/issues/1045). 

Is there a way to build and install the extension from source?

**Comment by EWSoftware** [comment]
Yes, download the repo's code and [build the appropriate solution file](https://github.com/EWSoftware/SHFB/wiki/System-Requirements-and-Building-the-Code).  However, see my reply on the other issue as I believe you were just using the wrong VSIX file.  You need to use the one specifically for VS 2022.
