### ISSUE TITLE
Failed to include xml documentation for native (c++) interface

### ISSUE THREAD

**Issue by lukas-ais** [EWSoftware/SHFB#109]
I've created xml documentation using VS2005 project. The result look quite similar to other xml documentation files created by C# based projects.
Using the xml file from native project, the reference cannot be resolved. Other sources (linked the csproj file) are resolved without problem.

Here is some xml file content:
```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        "Test.ClientWrapper"
    </assembly>
    <members>
[...]
        <member name="T:Test.Client.CEmEvent">
            <summary>This class implements wrapper class for event to be send to something.</summary>
        </member>
    </members>
</doc>
```

Here is the a documentation snipped:
```xml
[...]
To raise an event from unmanaged (C++) code the use of the class
<codeEntityReference autoUpgrade="true">T:Test.Client.CEmEvent</codeEntityReference>
is recommended.
[...]
```

Sandcastle generates the following warning:
`C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [79441e98-c50e-423e-8efe-ad5824ba66d7] Unknown reference link target 'T:Test.Client.CEmEvent'. [D:\...\Working\BuildConceptualTopics.proj]`

The member identifier is identical. The xml file is part of the "Documentation Sources".
Why the target cannot be resolved? Is this a supported use case?

**Comment by EWSoftware** [comment]
The assemblies you specify in the project's documentation sources are parsed and topics are created for each namespace, type, and member within them.  Reference links are links to those topics, not the comments.  The comments are matched up to the API topics that get created using the member ID.

Since native code assemblies are not supported and no physical topics exist for the `CEmEvent` class, the reference links have no where to go, hence the warning.  What you could do is document the native code classes and/or members using conceptual content (MAML topics).  You can then use a `conceptualLink` element and specify the topic ID as the target.

**Comment by lukas-ais** [comment]
Mmh, ok. But what for the "Document Source XML" is intended for?

**Comment by EWSoftware** [comment]
The comments option is simply to associate an XML comments file with an assembly if not using a solution or project as the documentation source.  You can't use comments alone as they don't contain enough information to determine class ancestry, descendants, interfaces implemented, attribute information, etc.  That info has to come from the assembly itself.

**Comment by lukas-ais** [comment]
Do you think it will be possible in future to support native (C++) projects, e.g. by parsing C++ code?
Therefore the project file could be configured as Documentation Source. This is already possible, but the "compilation" fails with "unspported project type".

**Comment by EWSoftware** [comment]
Managed code projects are supported to retrieve assembly, XML comments file, and reference information automatically.  Parsing source code would be a lot more complex so it's not something I'm willing to tackle.

**Comment by lukas-ais** [comment]
Thanks!
