### ISSUE TITLE
Error messages when opening shfb project properties in Visual Studio 2019

### ISSUE THREAD

**Issue by WegChris** [EWSoftware/SHFB#1090]
Hi,

always when I open the properties of the documentation project I get the following messages:
"no valid syntax generators found" and afterwards "no valid presentation styles found".

Then I can't see any styles in the dropdown, no entris in syntax filters and help file formats.

SHFBROOT is showing to SHFBROOT=C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\

So what can I do. What's the problem?

**Comment by EWSoftware** [comment]
I've seen that happen sometimes.  No known cause though it does seem to happen if the project properties window is left open when closing Visual Studio.  Close the project properties window and restart Visual Studio and it should clear up.  If you've only just installed it, reboot as it sometimes doesn't pick up the environment variable after it's just been added.  Also, if not using it, update to the latest release.

**Comment by WegChris** [comment]
Good Morning,

that's not the case because the properties windows wasn't open and it also happens when I create a new project. 
Reboot is done, set the environment variable by hand with " ", maybe the blank in the foldername is a problem.

Where should the SHFBROOT point to?
Does this entry have to be in the project-file and be changed every time I update the software?

<PropertyGroup>
  <SHFBROOT Condition=" '$(SHFBROOT)' == '' ">$(MSBuildThisFileDirectory)..\packages\EWSoftware.SHFB.xxxx.xx.xx.x\Tools\</SHFBROOT>
</PropertyGroup>

Do I need the NuGet Package and should it be attached to the documentation project? 

Haven't tried it on a different machine, 'cause were no admins and so very limited in installing software on a new PC. 
So every software will be installed via SCCM and I now have to figure out how to get VisualStudio and everything running on a new machine.

**Comment by EWSoftware** [comment]
SHFBROOT should be a system environment variable pointing to the install folder.  The installer will set it for you assuming you did run it (the MSI installer, not the VSIX).  The tools are separate from the VSIX.  The project property is only needed if you'll be running builds on a server where the tools are not installed so it depends on the NuGet packages.
