### ISSUE TITLE
An error when installing VSIX on VS20222

### ISSUE THREAD

**Issue by raczeja** [EWSoftware/SHFB#1091]
I'm getting error when installing  VSIX on latest VS 2022 
could you please help me to solve that issue ?
bets regards

_04.12.2024 09:02:03 - Microsoft VSIX Installer
04.12.2024 09:02:03 - -------------------------------------------
04.12.2024 09:02:03 - vsixinstaller.exe version:
04.12.2024 09:02:03 - 17.12.2069+1ec5133e4b
04.12.2024 09:02:03 - -------------------------------------------
04.12.2024 09:02:03 - Command line parameters:
04.12.2024 09:02:03 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,c:\users\jakub.raczek\downloads\shfbinstaller_2024.9.12.0\InstallResources\SHFBVisualStudioPackage_VS2017And2019.vsix
04.12.2024 09:02:03 - -------------------------------------------
04.12.2024 09:02:03 - Microsoft VSIX Installer
04.12.2024 09:02:03 - -------------------------------------------
04.12.2024 09:02:03 - Skipping product Microsoft.VisualStudio.Product.BuildTools (83a49769) since it does not support extensions
04.12.2024 09:02:03 - Initializing Install...
04.12.2024 09:02:03 - Searching for applicable products...
04.12.2024 09:02:04 - Found installed product - Visual Studio Professional 2022
04.12.2024 09:02:04 - Found installed product - Global Location
04.12.2024 09:02:04 - Extension Details...
04.12.2024 09:02:04 - 	Identifier         : c997d569-ee8e-4947-a46f-9a0717ce39a0
04.12.2024 09:02:04 - 	Name               : SHFB (VS2017 and VS2019)
04.12.2024 09:02:04 - 	Author             : EWSoftware
04.12.2024 09:02:04 - 	Version            : 2024.9.12.0
04.12.2024 09:02:04 - 	Description        : Visual Studio integration for the Sandcastle Help File Builder.
04.12.2024 09:02:04 - 	Locale             : en-US
04.12.2024 09:02:04 - 	MoreInfoURL        : https://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm
04.12.2024 09:02:04 - 	InstalledByMSI     : False
04.12.2024 09:02:04 - 	SupportedFrameworkVersionRange : [4.5,)
04.12.2024 09:02:04 - 	SignatureState     : Unsigned
04.12.2024 09:02:04 - 	Supported Products : 
04.12.2024 09:02:04 - 		Microsoft.VisualStudio.Community
04.12.2024 09:02:04 - 			Version : [15.0,17.0)
04.12.2024 09:02:04 - 			ProductArchitecture : x86
04.12.2024 09:02:04 - 	References         : 
04.12.2024 09:02:04 - 	Prerequisites      : 
04.12.2024 09:02:04 - 		-------------------------------------------------------
04.12.2024 09:02:04 - 		Identifier   : Microsoft.Component.MSBuild
04.12.2024 09:02:04 - 		Name         : MSBuild
04.12.2024 09:02:04 - 		Version      : [15.0,)
04.12.2024 09:02:04 - 		-------------------------------------------------------
04.12.2024 09:02:04 - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
04.12.2024 09:02:04 - 		Name         : .NET desktop development tools
04.12.2024 09:02:04 - 		Version      : [15.0,)
04.12.2024 09:02:04 - Signature Details...
04.12.2024 09:02:04 - 	Extension is not signed.
04.12.2024 09:02:04 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()_

<img width="761" alt="image" src="https://github.com/user-attachments/assets/0275765f-cea4-4f1a-804e-227d2336f6fe">

![image](https://github.com/user-attachments/assets/f7e8a72d-56ba-4ac7-99ce-2688ed02d145)

**Comment by Nikita-Skliarov** [comment]
Having the same issue. Perhaps SandCastle is not updated for versions above 17.0 yet.

**Comment by EWSoftware** [comment]
It's finding the 2019 build tools which is causing it to try and install the 2017/1029 version which isn't there.  Just run the VS 2022 VSIX from the .\InstallResources folder manually.  Is see that it is actually listing the entry as "Build Tools" so I'll see about updating the installer to filter those out.

**Comment by raczeja** [comment]
>  Just run the VS 2022 VSIX from the .\InstallResources folder manually

thanks, it helps
