### ISSUE TITLE
Trouble with adding a media content file

### ISSUE THREAD

**Issue by swnorberg** [EWSoftware/SHFB#114]
I am using the May 2nd release in VS2013. I am having trouble adding a Media Content file.
I have created a MediaContent.xml file:
```
    <stockSharedContentDefinitions>
      <item id="1C5330AC-05FC-4C3C-8213-EE1CE3A34CA8">
        <image file="C:\NorSoftCode\JusticeLink4.0\JLClientSetup\JLSetupDoc\Images\DBLayout.png">
          <altText>Information</altText>
        </image>
      </item>
    </stockSharedContentDefinitions>
```
 I have tried putting this file in various places in the project but every time I build I get a warning. _Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveArtLinksComponent:_

The media link looks like:
```
          <content>
             <para>Add one or more sections with content</para>
            <mediaLink>
              <caption placement="before">Some Caption</caption>
              <image placement="near" xlink:href="1C5330AC-05FC-4C3C-8213-EE1CE3A34CA8"/>
            </mediaLink>
          </content>
```
It seems that the project does not know about my MediaContent.xml file. Is there something that needs to be done to register this file? Or what am I missing?

**Comment by EWSoftware** [comment]
As noted in the [MAML guide](http://ewsoftware.github.io/MAMLGuide/html/3913b321-c875-4bb9-88de-4c65f6363270.htm), SHFB does not use media content files.  Simply add the images to the project and set their Build Action property to Image.  Typically, it'll set that by default.  All you need to do then is change the ID if you want something more descriptive than the default GUID.

**Comment by swnorberg** [comment]
Perfect.

 

Thanks for your response.

 

Scott Norberg

952-997-3888     (Office)

952-380-7545     (Cell)

952-997-6670     (Home)
