### ISSUE TITLE
Distribute NuGet package through GitHub releases

### ISSUE THREAD

**Issue by sharwell** [EWSoftware/SHFB#117]
It appears the GitHub releases page does not have the same 30MiB size limit that NuGet has. This means it should be possible to attach the **.nupkg** file to the release alongside the installer. I've had good success with build scripts [directly referencing NuGet packages via GitHub releases](https://github.com/openstacknetsdk/openstack.net/blob/master/build/build.ps1#L78-L86), which means the **.nupkg** files would be immediately usable if they were attached. :smile: 

:memo: This request will become obsolete and/or automatically resolved if #12 is resolved. However, if #12 will not be part of the upcoming release (whenever that is), this issue offers a usable alternative in the meantime.

**Comment by whut** [comment]
Please do so, I could then upload such nuget to our internal Nuget Server based on Nuget.Server nuget package, there is no such size limit imposed there.

**Comment by EWSoftware** [comment]
Changes to how the reflection data is handled are underway.  They'll make it into the next release so I'm closing this issue.
