### ISSUE TITLE
Plug-in downward compatibility

### ISSUE THREAD

**Issue by varnk** [EWSoftware/SHFB#118]
I have a custom plug-in that I created for Sandcastle 1.9.7.0.  I recently installed the latest version of Sandcastle and soon realized that there seems to be some compatibility issues with my plug-in.  I looked over the new Sandcastle plug--in documentation and it appears as though the architecture of building plug-ins has changed.  I would like to have my plug-in work on older versions of Sandcastle as well as newer versions.  Is there any way to make the plug-in compatible so that it can work on both the 1.9.7.0 version and the latest version?

**Comment by EWSoftware** [comment]
No, breaking changes are sometime necessary.  In this case, the plug-in architecture was updated to use MEF.  As such, you will need to rework the plug-in to work with the latest release and it will not be compatible with prior releases.

In SHFB releases in which no breaking changes were made, the strong name on the affected assemblies remains unchanged and plug-ins will work with new releases without needing to be rebuilt.  The SHFB release notes always contain information on any breaking changes and the components that they affect.
