### ISSUE TITLE
Documenting VB Module 

### ISSUE THREAD

**Issue by Swab** [EWSoftware/SHFB#119]
In a VB Module with extension methods (using the Help File builder with the defaultLanguage set as "vb#") Sandcastle ignores the Module comments AND lists all the extension methods (all marked with &lt;Extension()&gt;) as Public Static Methods except for one (ToSome()) which it correctly identifies as an extension while throwing the following error:

C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Base.Extensions.ToSome``1(System.Object)] Unknown reference link target 'Overload:Base.Extensions.ToSome'. [D:\Dev\Current\Base.Library\Base.Doc\Help\Working\BuildReferenceTopics.proj]

It also lists that one extension method under every Public class in the library.

I would like all the extensions to be recognized as extensions and to suppress the appearance of any of the extensions in the Public classes. How can this be achieved?

**Comment by EWSoftware** [comment]
I need to see the code to understand the problem.  Can you post an example?  You don't have to post the each method's content, just replace it with a simple return statement.  All I really need is the structure of the methods with the comments and attributes.

**Comment by Swab** [comment]
' Took a bit to get the same problem to occur...
' (Don't have problem with the Module comment being ignored! - 
' I had nested the "remark" in the alert instead of...)
' This does show the same behavior as my code (which is much larger.)
' In general VB Extension methods are always marked as Public Static even tho 
' it is clearly recognized that  they are Extension methods.
' But this code also shows the 3rd method "ToSome" being marked as an Extension
' with the Description text displaying "(Defined by Extensions.)"
' So, why are they not ALL marked as extensions?

Imports System.Runtime.CompilerServices

Namespace Global.Base

    ''' &lt;summary&gt;
    ''' Contains type extensions.
    ''' &lt;/summary&gt;
    ''' &lt;author&gt;Swab&lt;/author&gt;
    ''' &lt;remarks&gt;
    ''' &lt;alert class="note"&gt;
    ''' This is a message about the whole module that gets ignored.
    ''' &lt;/alert&gt;
    ''' &lt;/remarks&gt;
    Public Module Extensions

        ''' &lt;summary&gt;
        ''' Strings the extension.
        ''' &lt;/summary&gt;
        ''' &lt;param name="this"&gt;The this.&lt;/param&gt;
        ''' &lt;returns&gt;&lt;/returns&gt;
        &lt;Extension()&gt;
        Public Function IntegerExtension(ByRef this As Integer) As Integer
            Return this
        End Function

        ''' &lt;summary&gt;
        ''' Strings the extension.
        ''' &lt;/summary&gt;
        ''' &lt;param name="this"&gt;The this.&lt;/param&gt;
        ''' &lt;returns&gt;&lt;/returns&gt;
        &lt;Extension()&gt;
        Public Function StringExtension(ByRef this As String) As String
            Return this
        End Function

        ''' &lt;summary&gt;
        ''' To some.
        ''' &lt;/summary&gt;
        ''' &lt;typeparam name="T"&gt;The type.&lt;/typeparam&gt;
        ''' &lt;param name="this"&gt;The this.&lt;/param&gt;
        ''' &lt;returns&gt;&lt;/returns&gt;
        &lt;Extension()&gt;
        Public Function ToSome(Of T)(ByVal this As Object) As String
            Return this
        End Function

        ''' &lt;summary&gt;
        ''' Froms some.
        ''' &lt;/summary&gt;
        ''' &lt;typeparam name="T"&gt;The type.&lt;/typeparam&gt;
        ''' &lt;param name="this"&gt;The this.&lt;/param&gt;
        ''' &lt;returns&gt;&lt;/returns&gt;
        &lt;Extension()&gt;
        Public Function FromSome(Of T)(ByVal this As String) As T
            Return Convert.ChangeType(this, GetType(T))
        End Function

    End Module

End Namespace

' The warnings are:
' C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [N:Base] Missing <summary> documentation [D:\Code\Base\Base.Doc\Help\Working\BuildReferenceTopics.proj]
' C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:Base.Extensions.FromSome``1(System.String)] Missing <returns> documentation [D:\Code\Base\Base.Doc\Help\Working\BuildReferenceTopics.proj]
' C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:Base.Extensions.IntegerExtension(System.Int32@)] Missing <returns> documentation [D:\Code\Base\Base.Doc\Help\Working\BuildReferenceTopics.proj]
' C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:Base.Extensions.StringExtension(System.String@)] Missing <returns> documentation [D:\Code\Base\Base.Doc\Help\Working\BuildReferenceTopics.proj]
' C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:Base.Extensions.ToSome``1(System.Object)] Missing <returns> documentation [D:\Code\Base\Base.Doc\Help\Working\BuildReferenceTopics.proj]
' C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Base.Extensions.ToSome``1(System.Object)] Unknown reference link target 'Overload:Base.Extensions.ToSome'. [D:\Code\Base\Base.Doc\Help\Working\BuildReferenceTopics.proj]
' C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Base.Extensions.ToSome``1(System.Object)] Unknown reference link target 'Overload:Base.Extensions.ToSome'. [D:\Code\Base\Base.Doc\Help\Working\BuildReferenceTopics.proj]

**Comment by EWSoftware** [comment]
There's a bug in how MRefBuilder is matching extension methods to existing class methods.  This particular problem doesn't manifest with C# projects since extension methods are in static classes in C# and the code doesn't add extension method info to static types.  While a VB.NET module is technically static, the VB.NET compiler generates a sealed class rather than a static class so MRefBuilder still adds extension methods to it.  Since it's not currently matching the members properly, it adds the extension methods which then look like overloads hence the incorrect warnings and the erroneous Extension Methods topic section.  I've got it fixed for the next release.

The Extension Methods section will show up on any type that matches or is derived from the extension method's parameter type.  As an example, if you have a base type `Foo` with derived types `Bar1` and `Bar2` and an extension method that takes a `Foo` instance, you'd see the extension method on all three types.  Since there are no types that derive from integer or string, you won't see those extension methods show up on any classes in your help file.

You used `Object` as the parameter type for the method you mentioned above.  Any extension method that uses `Object` as the extension method parameter will get added to all types since everything ultimately derives from `Object`.  That is the expected behavior.  If you want to change that, you'll need to change the presentation style so that it doesn't create that section.

**Comment by Swab** [comment]
Installed the latest version and still getting this message for the Extensions that extend System.Object:
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Base.Extensions.Duck``1(System.Object,``0)] Unknown reference link target 'Overload:Base.Extensions.Duck'. [D:\Current\Base.Library\Base.Doc\Help\Working\BuildReferenceTopics.proj]

I am easily able to suppress the Extension methods appearing on other classes but the result of this warning is to not place the method into the list of Methods for the extension class. Any methods with that warning do not appear on the class page or on the methods page.

**Comment by EWSoftware** [comment]
That's because I haven't published a new release that contains the fix.  It'll be in the next one.
