### ISSUE TITLE
Rework framework metadata and reflection data file handling

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/SHFB#12]
Rather than have one Frameworks.xml file, split the framework metadata out into separate files.  For SHFB they'll be split out by platform though they could be specific to a single platform and version.  This will allow them to be treated like components and will make it easier to add new frameworks in the future.  They can also be treated like project-specific components.  As such, people could generate their own framework metadata file and reflection data for new platforms/versions without having to wait for support to be built into SHFB.

This will also allow the framework reflection data to be distributed in multiple NuGet packages which can be added to a project along with the core SHFB NuGet package to add framework data for just those frameworks that are needed by the project.  This reduces the size of the core package and also gets around the 30MB size restriction on NuGet packages hosted in the public gallery.

**Comment by sharwell** [comment]
Would it be possible to remove the framework data from the NuGet package entirely and have it generated by a build task if it doesn't yet exist? This would dramatically reduce the size of the NuGet package.

**Comment by EWSoftware** [comment]
The plan is to remove the framework data from the core NuGet package.  Since the data is static I think it makes more sense to distribute packages for each of the platforms that can be added as needed rather than forcing the end user to rebuild the data which would occur for everyone that obtained a copy of the project.  It would only need to happen once but it's still additional cost on that first build and it has to put that info somewhere.  Its much quicker to just download the package which the build will do if package restore is enabled and it also ensures everyone building the project is using a consistent set of framework data.
