### ISSUE TITLE
Suppress enum value?

### ISSUE THREAD

**Issue by ericlaw1979** [EWSoftware/SHFB#120]
Apologies if I've missed something, but is there a way to suppress the "Value" column in the documentation of an enum?

As far as I can tell, this wasn't present in docs built by the older Sandcastle.

![unwanted](https://cloud.githubusercontent.com/assets/4192774/8240869/523949cc-15cb-11e5-9163-123e0c8a5b66.png)

**Comment by EWSoftware** [comment]
It was requested to be added quite a while ago so it's been in all presentation styles starting with the VS2005 one.  To remove it, you'd need to modify the presentation style and remove the XSL that generates that particular column.

**Comment by ericlaw1979** [comment]
Ah, good to know. Thanks!
