### ISSUE TITLE
VS 2015 RC does not show SHFB project property page

### ISSUE THREAD

**Issue by TCSCdpr** [EWSoftware/SHFB#121]
A solution that contains an SHFB project created in VS 2010 that loads and compiles fine in VS 2013 and the SHFB GUI will not display the SHFB project property page in VS 2015 RC. (Version 14.0.22823.1 D14REL)
When attempting to open property pages for SHFB project, VS 2015 raises the error:

*An error occurred trying to load the project properties window.  Close the window and try again.
The expression "[System.IO.Path]::Combine(D:\Projects\TCSC\Utilities\IO\CSV\Documentation\, obj\Release|Any CPU\Fakes)" cannot be evaluated. Illegal characters in path.  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Fakes\Microsoft.QualityTools.Testing.Fakes.targets*

**Comment by EWSoftware** [comment]
Based on the error, it would appear to be a problem with an expression in a project file property involving the given expression.  If you can open the property pages in VS 2010/2013 for the same project, perhaps an extension or something is missing in the VS 2015 installation?  If you can upload the project somewhere or e-mail it to me, I can take a look at it.

**Comment by EWSoftware** [comment]
No reply, so I'm closing this for now.  I checked the package with the RC and it's working fine.  As noted, it's probably an issue with the project file itself not being able to resolve an imported targets file or something like a missing extension since it works in the other versions.
