### ISSUE TITLE
Help Viewer 2.x: Blank catalog name causes error during installation

### ISSUE THREAD

**Issue by Nobody84** [EWSoftware/SHFB#122]
If I leave the content catalog name field blank, I got an error during installation of the help file to the "Help Content Manager". If I set the catalog name to "VisualStudio12" than the installation for Help Viewer v 2.1 works fine, but the installation for 2.2 failed.

![shfb_blank_catalogname](https://cloud.githubusercontent.com/assets/8879706/8278312/b45fac20-18ca-11e5-96e7-4ac724b1508c.PNG)
![shfb_blank_catalogname_error](https://cloud.githubusercontent.com/assets/8879706/8278313/b460c3bc-18ca-11e5-9923-9c7650de721a.PNG)

**Comment by EWSoftware** [comment]
What version are you using?  Support for blank catalog names and Help Viewer 2.2 wasn't added until the latest v2014.5.2.0 release.

**Comment by Nobody84** [comment]
Thanks for your reply. I'm using 
Sandcastle Help File Builder version: 2015.5.2.0 
and 
HelpLibraryManagerLauncher.exe version: 15.5.2.0 .
I think this is the current version.

**Comment by EWSoftware** [comment]
The default catalog name isn't being added to the command line arguments passed to the help library manager.  I'll get it fixed for the next release.  In the meantime, you can modify the script that SHFB produces to add the default catalog name based on the version (/catalogName VisualStudio11, /catalogName VisualStudio12, or /catalogName VisualStudio14 based on the help viewer version).
