### ISSUE TITLE
Unable to create reference to overload topic

### ISSUE THREAD

**Issue by dougclutter** [EWSoftware/SHFB#123]
I have a class like this:
    public class FixedWidthRecordLoader
    {
        /// <summary>
        /// Gets or sets a value that controls whether blank lines are ignored by the <see cref="O:Load"/> methods.
        /// </summary>
        public bool IgnoreBlankLines { get; set; }
        /// <summary>
        /// Loads records from the given file.
        /// </summary>
        /// <param name="filename">The full path to the file to load.</param>
        public void Load(string filename)
        {
        }
        /// <summary>
        /// Loads records from the given <see cref="StreamReader"/>.
        /// </summary>
        /// <param name="reader">The reader to load records from.</param>
        public void Load(StreamReader reader)
        {
        }
    }
When building with SHFB, I get the following errors:
6>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [T:Michigan.FixedWidthRecordLoader] Unknown reference link target 'Overload:Load'. [C:\TFS\Corporations Utilities\CorpsUtil\01 - Dev\CorpsUtil\CorpsUtil.Docs\Help\Working\BuildReferenceTopics.proj]
6>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [Properties.T:Michigan.FixedWidthRecordLoader] Unknown reference link target 'Overload:Load'. [C:\TFS\Corporations Utilities\CorpsUtil\01 - Dev\CorpsUtil\CorpsUtil.Docs\Help\Working\BuildReferenceTopics.proj]
6>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [P:Michigan.FixedWidthRecordLoader.IgnoreBlankLines] Unknown reference link target 'Overload:Load'. [C:\TFS\Corporations Utilities\CorpsUtil\01 - Dev\CorpsUtil\CorpsUtil.Docs\Help\Working\BuildReferenceTopics.proj]

From the error message, I can see the O: is being translated to Overload: as expected.  The generated help docs (HTML BTW) do have the Load overload topic as expected.

What am I missing here?

**Comment by sharwell** [comment]
You need to turn that code into a code block. All of the XML elements were removed when displaying the current form. A code block look like this:

    ```
    ↑ starts with three back ticks
    code in the middle
    ↓ ends with three back ticks
    ```

**Comment by dougclutter** [comment]
Let's try this again (sigh)...
```c#
    public class FixedWidthRecordLoader
    {
        /// <summary>
        /// Gets or sets a value that controls whether blank lines are ignored by the <see cref="O:Load"/> methods.
        /// </summary>
        public bool IgnoreBlankLines { get; set; }
        /// <summary>
        /// Loads records from the given file.
        /// </summary>
        /// <param name="filename">The full path to the file to load.</param>
        public void Load(string filename)
        {
        }
        /// <summary>
        /// Loads records from the given <see cref="StreamReader"/>.
        /// </summary>
        /// <param name="reader">The reader to load records from.</param>
        public void Load(StreamReader reader)
        {
        }
    }
```

**Comment by sharwell** [comment]
@dougclutter :bulb: You can edit your first post if you'd like to fix it there. (Now that I can read it, it doesn't matter nearly as much.) :smile:

**Comment by dougclutter** [comment]
How do I edit the original post?  The [Edit] button only seems to allow editing the title.  :(

**Comment by sharwell** [comment]
@dougclutter The problem you are encountering is `cref` references must always be fully-qualified. In many cases, such as `<see cref="Load(string)"/>`, the C# compiler will resolve the reference and then fully-qualify it for you in the XML file produced by the compiler. However, the C# compiler completely ignores references starting with `O:`, which means you'll have to qualify them yourself. In this case, it might look like this:

```csharp
<see cref="O:Namespace.Of.FixedWidthRecordLoader.Load"/>
```

I filed dotnet/roslyn#45 requesting improvements to the C# compiler which would help tremendously with this use case.

**Comment by dougclutter** [comment]
Thanks!  You rock!
One tiny complaint, the generated link says "Load Overload".  What if I just want it to say "Load"?

**Comment by sharwell** [comment]
> How do I edit the original post? The [Edit] button only seems to allow editing the title. :(

It's this sneaky button:

![image](https://cloud.githubusercontent.com/assets/1408396/8284063/817a7fc4-18c0-11e5-953b-f76bb242e363.png)

> One tiny complaint, the generated link says "Load Overload". What if I just want it to say "Load"?

I recommend creating a separate issue for that request, so this one can be closed and marked as answered. :+1:

**Comment by dougclutter** [comment]
Okay.  Will close this one.

> It's this sneaky button:

I'm using IE 11 and that sneaky button is not even visible...but I can click on it.
Thanks for all your help!

**Comment by sharwell** [comment]
@dougclutter No problem. If you agree with the Roslyn feature request I linked to, feel free to add a "This would help me as well" comment to it. :wink:
