### ISSUE TITLE
How can we customize the link text for an overload?

### ISSUE THREAD

**Issue by dougclutter** [EWSoftware/SHFB#124]
If we have a link to an overload like this:
```C#
        /// <summary>
        /// Gets or sets a value that controls whether blank lines are ignored by the <see cref="O:Michigan.FixedWidthRecordLoader.Load"/> methods.
        /// </summary>
```
Then SHFB generates something like this:
Gets or sets a value that controls whether blank lines are ignored by the Load Overload methods. 

How can we get SHFB to generate the link text as "Load" rather than "Load Overload"?

**Comment by sharwell** [comment]
Under the current templates, you should be able to do the following already:

    <see cref="O:...Load">Load</see>

I would leave this open for additional consideration of the wording used by the templates.

**Comment by EWSoftware** [comment]
The overload item text is stored in the resource item files associated with each presentation style.  You can add a resource items file to your project, open it for editing, locate the overload text item (`boilerplate_seeAlsoOverloadLink`) and change it by removing the " Overload" part of the value.

**Comment by dougclutter** [comment]
Thanks for the feedback.  I like @sharwell 's approach best because I can customize based on context.  Good to know that it can be set in the resources.
