### ISSUE TITLE
Unreadable content in VS when using dark theme

### ISSUE THREAD

**Issue by osre77** [EWSoftware/SHFB#125]
Some editor content (like in ContentLayout.content) is not readable when using dark theme in VS, because the default text color is white then, and the background in most SHFB plugin controls is light gray.

**Comment by EWSoftware** [comment]
I'm not seeing any issues when using the dark theme regarding readability.  There are some font sizing issues in the current release which I've fixed for the next release.  The tool windows don't blend in with the dark theme but I may address that at a later date to make it theme aware.

**Comment by osre77** [comment]
I think I solved it, something in my VS Setup was messed up.
I could solve it by switching the theme to blue -> restart -> Switch back to dark -> restart.
Thank you for your time anyway. SHFB is such an great tool.
