### ISSUE TITLE
Defining custom tags like in NDOC

### ISSUE THREAD

**Issue by oleksiizozulenko** [EWSoftware/SHFB#126]
I like sandcastle documentation but I would like to define several custom tags for processing. (like in NDOC http://ndoc.sourceforge.net/content/extensibility.htm )
But I didn't find any posibility to do this in sandcastle. 
Could you add this feature or say how to define custom tags to process with sandcastle?

**Comment by EWSoftware** [comment]
There's a very old blog post that describes how to add custom tags to the XSL transformations for the Sandcastle presentation styles (http://blogs.msdn.com/b/sandcastle/archive/2006/11/22/supporting-custom-tags-in-sandcastle.aspx).

The concept is still the same.  You can apply the changes directly to the installed files but, to keep them separate and avoid losing them with each new release, you can create your own presentation style based on one of the existing ones.  See the [Creating a Presentation Style Component](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) topic in the SHFB help file for more information.
