### ISSUE TITLE
error MSB6006: "HHC.EXE" exited with code -1073741819.

### ISSUE THREAD

**Issue by Yoshihiro-H** [EWSoftware/SHFB#127]
Dear Mr. Eric Woodruff.

I am developing a WPF application using Visual Studio 2013 community Update 4.

Add the "Sandcastle File Help Builder Project" and tried to build the HTML help (.chm) file, the following error has been output.

Compiling HTML Help 1 file...
[C:\Program Files (x86)\MSBuild\12.0\bin\MSBuild.exe]
  Microsoft HTML Help Compiler 4.74.8702
      :
C:\Works\VS2013\Projects\Sample01\Sample01Doc\Help\Working\Build1xHelpFile.proj(41,5): error MSB6006: "HHC.EXE" exited with code  -1073741819.

PNG files and JavaScript and CSS files, had been specified in the [FILES] section of help1x.hpp of the "working" directory.

The Microsoft documentation, has the following description:
 https://msdn.microsoft.com/en-us/library/windows/desktop/ms524266 (v = vs.85) .aspx

  [Open an HTML file and add the <IMG> tag where appropriate. If you are compiling your files, the HTML Help compiler will automatically add any referenced files to your project at compile time.]

From this description, I was set only HTML files to [FILES] section of help1x.hhp, CHM file has been created successfully. 
 
The chm file is confirm that the PNG file, JavaScrpit, the css file is stored.

Therefore, I guess that it should be specified only HTML files to the [FILES] section of hhp file.

Please confirm if it’s correct.

Thank you.

**Comment by EWSoftware** [comment]
No, that's not correct.  The full set of files including images has always been specified and works as expected.  There's probably another issue with your installation of the HTML Help Workshop which contains HHC.EXE.  The error code in question is a generic access violation failure code.  I'd suggest reinstalling it to see if that corrects the issue.  You can download it from here:  https://msdn.microsoft.com/en-us/library/ms669985.aspx

Note that it will probably tell you the help compiler is already installed.  This is normal, just confirm that you want it reinstalled.

**Comment by Yoshihiro-H** [comment]
Dear Mr. Eric Woodruff.

Thank you for your reply.

After re-installation of the HTML Help Workshop, help file was confirmed to be output successfully without modifying the hhp file.

Some of the files needed to run hhc.exe seems was not enough.

I will continue to use the SHFB in the future.

Thank you.
