### ISSUE TITLE
Help file V1 text disappears behind scroll bar in VS2013 style

### ISSUE THREAD

**Issue by simpsonp** [EWSoftware/SHFB#128]
Hi,

I am using the May SHFB build and have a project that creates a great V1 help file using the VS2010 presentation style, but when I build the file using the VS2013 style I get a horizontal scroll bar that I cannot get rid of and sometimes content disappears behind the scroll bar. The image below shows this in the CompatibilityException and TransformUninitialisedException descriptions.

Am I doing something wrong or is this a bug?

Thanks, Peter

![image](https://cloud.githubusercontent.com/assets/13080259/8393619/7641d9ba-1d0f-11e5-82f0-76ed062484e4.png)

**Comment by EWSoftware** [comment]
It's probably an issue with the Help 1 viewer and the style sheet.  There may be a way to tweak the Help 1 styles to fix it but I haven't looked into it.

**Comment by simpsonp** [comment]
Hi Eric,

I am a complete newbe at CSS but managed to work round the issue by adding a new "body" definition to the branding-Help1.css file:

/* Style adjustments for ASCOM */
/* Changed margin-right from auto to 50px to ensure that long lines do not go under the vertical scroll bar when they wrap to the next line */
/* Added overflow-x:hidden to suppress the horizontal scroll bar */
body {
	font-family: 'Segoe UI' , 'Lucida Grande' , Verdana, Arial, Helvetica, sans-serif;
	font-size: 15px;
	padding: 0;
	margin: 0;
	margin-left: auto;
	margin-right: 50px;
	overflow-x: hidden;
	color: #000;
}

In this approach I have copied the entire body definition and altered it. Is there a way in CSS to just specify the changes to the original in this file so that I don't need to be concerned if the primary body definition is revised in a future release?

Thanks, Peter

**Comment by EWSoftware** [comment]
Leaving out the duplicate parts should work.  The format-specific CSS file is loaded after the main one and the styles are merged from all of them.  Later duplicate styles override elements in earlier ones.

**Comment by simpsonp** [comment]
Thanks Eric, that worked perfectly.

Regards, Peter

**Comment by EWSoftware** [comment]
I took another look at this and I think I've come up with a better fix.  Remove the body override and replace it with these three overrides:

```
.pageBody {
	padding-top: 0px 20px 0px 0px;
}

table {
	width: 95%;
	padding-right: 20px;
}

table.members {
	width: 95%;
	padding-right: 20px;
}
```

This adjusts the right margin on the div that contains the topic body and shortens the tables so that they don't exceed the right margin.  The horizontal scrollbar will only appear when needed now.  Note that you still want to leave it enabled as when the topic is narrow enough, horizontal scrolling may still be needed (i.e. for code examples).
