### ISSUE TITLE
Missing schema for .AML file in Sandcastle Documentation ?

### ISSUE THREAD

**Issue by nolme** [EWSoftware/SHFB#130]
Hi,

I've done a first test today and I've got some warning I can't remove. I'm using Visual Studio 2013 Community.
Here's the report :

Message 4 Impossible de trouver des informations de schéma pour l'attribut 'id'. D:\Cloud\Qsync\Dev\DotNET\Nolme\GenericLib4\SandcastleDocumentation\Content\VersionHistory\v1.0.0.0.aml 2 8 SandcastleDocumentation
Message 7 Impossible de trouver des informations de schéma pour l'attribut 'id'. D:\Cloud\Qsync\Dev\DotNET\Nolme\GenericLib4\SandcastleDocumentation\Content\VersionHistory\VersionHistory.aml 2 8 SandcastleDocumentation
Message 5 Impossible de trouver des informations de schéma pour l'attribut 'revisionNumber'. D:\Cloud\Qsync\Dev\DotNET\Nolme\GenericLib4\SandcastleDocumentation\Content\VersionHistory\v1.0.0.0.aml 2 50 SandcastleDocumentation
Message 8 Impossible de trouver des informations de schéma pour l'attribut 'revisionNumber'. D:\Cloud\Qsync\Dev\DotNET\Nolme\GenericLib4\SandcastleDocumentation\Content\VersionHistory\VersionHistory.aml 2 50 SandcastleDocumentation
Message 3 Impossible de trouver les informations de schéma pour l'élément 'topic'. D:\Cloud\Qsync\Dev\DotNET\Nolme\GenericLib4\SandcastleDocumentation\Content\VersionHistory\v1.0.0.0.aml 2 2 SandcastleDocumentation
Message 6 Impossible de trouver les informations de schéma pour l'élément 'topic'. D:\Cloud\Qsync\Dev\DotNET\Nolme\GenericLib4\SandcastleDocumentation\Content\VersionHistory\VersionHistory.aml 2 2 SandcastleDocumentation

These files have not been changed so the warning came from file generation. ?

Vincent

**Comment by EWSoftware** [comment]
Those are from the XML editor.  The topic element, id attribute, and revisionNumber attribute aren't part of the MAML schema, they're just a wrapper that SHFB uses.  As such, those warnings are to be expected.  They're just informational and you can safely ignore them.
