### ISSUE TITLE
How can I create a root folder for generated content in SHFB Visual Studio project?

### ISSUE THREAD

**Issue by SetTrend** [EWSoftware/SHFB#132]
I have created a SHFB project in Visual Studio 2013.

Currently the generated namespaces are always added to the root in the compiled result TOC. But I want them to be added to an arbitrary folder in the TOC.

### How can I archive this?

**This is what I have:**

* Conceptual page #1
* Conceptual page #2
* My.Namespace
* My.Namespace.Other

**This is what I want:**

* Getting Started
   * Conceptual page #1
   * Conceptual page #2
* Reference
   * My.Namespace
   * My.Namespace.Other

**Comment by EWSoftware** [comment]
If you want a root namespace container page (a list of namespaces topic), turn on the *Include root namespace container* option in the [Help File category](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#RootNS) of the project properties.  See also [Content Placement Options](http://ewsoftware.github.io/SHFB/html/ba42b2c2-985d-46f1-ba4c-3d921edcafe3.htm).

If you want a MAML topic to serve as the parent, use the content layout file editor to mark the MAML topic that will serve as the parent to the reference content by setting the topic's *API Content* property to *Insert as child of this topic*.

You can use the content layout editor to create parent/child topics for the other topics such as Getting Started/Page1 and Page 2.  That's covered in the [layout editor help topic](http://ewsoftware.github.io/SHFB/html/54e3dc97-5125-441e-8e84-7f9303e95f26.htm) along with the other properties such as the API placement option.

**Comment by SetTrend** [comment]
Excellent!

Works like a charm. Thanks for helping me on getting to know SHFB.

For me reading the SHFB help sometimes is too cerebral. I don't understand what it's telling me. I just can't imagine the different option's outcome.

If I was asked to put a suggestion: I'm missing screenshots and sample results in the SHFB help.
