### ISSUE TITLE
Strange warnings - reporting missing help tags, though they are actually there - why?

### ISSUE THREAD

**Issue by SetTrend** [EWSoftware/SHFB#136]
I get these three warnings, telling me that some documentation is missing:
```
6>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:... .Client.Untyped.PdfGenerator.CreatePdfFromTemplate(System.String,System.String,... .Shared.Models.CultureInfoDTO,System.Collections.Specialized.NameValueCollection,System.Collections.Generic.Dictionary{System.String, ... .Shared.Models.SwitchAction})] Missing <returns> documentation [D:\Solution\Documentation\Help\Working\BuildReferenceTopics.proj]
6>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:... .ServiceHost.Controllers.DocumentController.CreatePdfFromTemplate(... .Shared.Models.FlattenedDocumentDataDTO)] Missing <returns> documentation [D:\Solution\Documentation\Help\Working\BuildReferenceTopics.proj]
6>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [G:... .ServiceHost] Missing <summary> documentation [D:\Solution\Documentation\Help\Working\BuildReferenceTopics.proj]
```
But all these warnings seem to be wrong, as the following screenshots prove:

![1](https://cloud.githubusercontent.com/assets/9283914/8509098/714cf940-2290-11e5-957f-729d4e31f3fc.png)

![2](https://cloud.githubusercontent.com/assets/9283914/8509099/747bab34-2290-11e5-975c-2e8c53c4c227.png)

![3](https://cloud.githubusercontent.com/assets/9283914/8509100/769d4f80-2290-11e5-8b84-49fbfb5f9863.png)

**What am I doing wrong?**

I'm using SHFB version 2015.5.2.0

**Comment by EWSoftware** [comment]
The one with the "G:" prefix is the namespace group.  Either turn off namespace grouping, add namespace group comments for the missing members to the project using the Namespace Summaries option in the Summaries project categtory or add a NamespaceGroupDoc class to put the group comments in the code.

Regarding the other two, either you've got an overload with missing returns statement or the XML comments are out of date and need to be rebuilt.  Forcing a rebuild on your project (Debug or Release to match what you're building the documentation against should get them up to date.  The XML comments files the build is using are listed in the log file.  You can look there to get the files and see if they contain up to date information.

To suppress missing documentation warnings that you don't care about, use the properties in the Missing Tags category of project properties.

**Comment by SetTrend** [comment]
Oh, yes, you were right.

I forgot that at my client we need to execute a custom build tool to copy the bin folder to a common destination. I was referencing it but didn't run the custom tool.
