### ISSUE TITLE
How can I manually increase spacing?

### ISSUE THREAD

**Issue by SetTrend** [EWSoftware/SHFB#138]
Sometimes the result of my help looks rather bulky, so I want to add more spacing before or after a ` <para> ` element.

**How can I do this?**

I'm currently using a "personal" workaround by adding a dummy paragraph with a non-breaking space:

` <para>&#160;</para> `

... but I don't quit like such kind of hacks. I would very much prefer to have a MAML conform way of adding vertical space between sections.

<br/>
See the difference here (due to confidentiality agreements I'm required to scramble the content here):

![6](https://cloud.githubusercontent.com/assets/9283914/8512426/35d5baac-2342-11e5-8633-9950a6e0a0f9.png)

**Comment by sharwell** [comment]
If your goal is to make it less "bulky", another option is helping update the "lightweight" style currently used for [this documentation](http://rackerlabs.github.io/dotnet-threading/docs-latest/html/e02b9881-f06b-4420-aace-71b176d635db.htm) to work with the default presentation style. It's mostly just a different set of CSS pages for the same content. Some comments regarding this can be seen in #51 and #58.

**Comment by EWSoftware** [comment]
The simplest approach is to use SHFB's [stock content replacement support](http://ewsoftware.github.io/SHFB/html/77d2d693-db84-4ae3-a84c-e33c71f92e9a.htm).  What you do is add a *.\styles* folder to the root of your SHFB project and place a copy of the presentation style's CSS files in it (*branding.css*, *branding-Help1.css*, etc).  You can then make changes to them as you see fit.  When built, the project versions will take precedence and will be used in place of the stock style sheets.

If you need more control over the presentation style as a whole such as needing to change the XSL transformations or you want your changes to always apply, you can [create your own](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) based on the default style.

Eric

**Comment by SetTrend** [comment]
Thank you for trying to help.

I comprehend that there is a CSS based option to alter *all* paragraphs at once. But I'm more searching for a solution to add space to praticular, dedicated paragraphs only.

Is it possible to assign some kind of attribute to paragraphs that add a particular CSS class when converted to any of the other formats?

**Comment by EWSoftware** [comment]
If you create your own presentation style, you can copy one of the existing ones and modify it to suit your needs such as adding extra attributes to paragraph elements, etc.
