### ISSUE TITLE
How to use <codeEntityReference autoUpgrade="true"> with overloads?

### ISSUE THREAD

**Issue by SetTrend** [EWSoftware/SHFB#139]
I couldn't find any documentation on how to reference overloads in conceptual content. Googling didn't result in successful results, either.

All the following sorts of tags won't work (the only difference is the element prefix):

`<codeEntityReference autoUpgrade="true">M:MyNamespace.MyClass.MyMethod</codeEntityReference>`

`<codeEntityReference autoUpgrade="true">O:MyNamespace.MyClass.MyMethod</codeEntityReference>`

`<codeEntityReference autoUpgrade="true">Overload:MyNamespace.MyClass.MyMethod</codeEntityReference>`

They all generate an ` Unknown reference link target ` or ` Invalid reference link target ` warning.

<br/>
**What's the correct way of addressing overloads in SHFB?**

**Comment by SetTrend** [comment]
Ah, it was me missing our manual build step again.

So, here for everyone trying to find an answer to the same question ... The correct answer is:

`<codeEntityReference autoUpgrade="true">Overload:MyNamespace.MyClass.MyMethod</codeEntityReference>`

Would you mind adding the corresponding type to the documentation?

**Comment by EWSoftware** [comment]
You're using the element incorrectly.  See the [MAML guide topic](http://ewsoftware.github.io/MAMLGuide/html/bc490dbf-7d46-432d-a816-3ae16ab6af54.htm) for details.  The `autoUpgrade` attribute will do what you want when set to true as long as you use one of the overloaded member's as the target ID.  It doesn't matter which one.

The Entity References tool window can aid you in adding reference links.  You can look them up and drag and drop them to create the reference links.
