### ISSUE TITLE
"Request sample" button in generated output

### ISSUE THREAD

**Issue by sharwell** [EWSoftware/SHFB#140]
In projects with large public-facing API surfaces, it can be difficult or impossible to provide code samples for every scenario. In order to improve the ability to provide meaningful examples for users, it would be nice if pages for API members had a **Request Example** button (of some form), which when clicked automatically started the process of creating a new issue for the project with basic information about which page the user was browsing, and asked for additional information about the use case they are working on.

:thought_balloon: An initial implementation which only worked with GitHub Issues would be a great start that applies to many projects and allows us to think about what a broader solution would look like (potentially even getting the community to help with additional connectors).

:thought_balloon: Here is my first thought for what the created issue would look like:

> ## Example request: {Page title}
>
> *Add details about your specific use case to ensure the new example is relevant*
>
> --
> Source: {URI}
> Build: {commit hash the docs were built from}

**Comment by EWSoftware** [comment]
Isn't this a duplicate of #19 also submitted by you?  If so, please merge the issues and close one of them.  My comments as to implementation on #19 would apply here too.  Thanks.

**Comment by sharwell** [comment]
Yes, this is an unintentional duplicate. Someone reminded me of the idea today and I did a quick search but I guess I didn't pick the right word.
