### ISSUE TITLE
SHFB: Error BE0019: Unable to transform template 'GenerateMarkdownContent.proj': Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SimoPrG** [EWSoftware/SHFB#141]
Hello,

I tried to generate a help file with markdown content and I received error BE0019. Here is a [link] (https://github.com/SimoPrG/HighQualityCodeHomework/tree/master/VariablesDataExpressionsAndConstants/Statistics) to the project in GitHub.
You can find the LastBuild.log in the Help folder and the xml and the dll files I am working with in the bin/Debug folder.

Best Regards,
Simeon

**Comment by EWSoftware** [comment]
It's caused by the lack of an explicit default topic.  As a workaround, enable the Root Namespace Container option in the Help File category of project properties.  It's already been fixed for the next release due out soon.
