### ISSUE TITLE
How do I add arbitrary hyperlinks?

### ISSUE THREAD

**Issue by SetTrend** [EWSoftware/SHFB#142]
I have seen an ` address ` attribute on several MAML elements. But I couldn't find information on how to add hyperlinks to a topic so I can have the user jump to arbitrary elements in the text.

How can I do this?

Example:

```
<alert class="note" address="Test">
...
</alert>
<para>I want to <??? ???="#Test">jump</???> to the alert.
</para>
```

**Comment by EWSoftware** [comment]
Please read through the MAML guide.  It covers all the elements you'll commonly use and this stuff is covered in there.  Specifically, the [link element](http://ewsoftware.github.io/MAMLGuide/html/53a2b7c6-a269-4916-9313-bdc301ee9398.htm)
