### ISSUE TITLE
Markdown links miss the "md" file extension

### ISSUE THREAD

**Issue by SimoPrG** [EWSoftware/SHFB#143]
Hi again,

Firstly, I would like to thank you for your fast response regarding my previous issue!
I would also like to inform you that the links which SHFB generates miss the "md" file extension. For example
&lt;a href="270cb39d-5592-08d7-c0bc-f40f01bb1ae3"&gt;Printer&lt;/a&gt;
must be
&lt;a href="270cb39d-5592-08d7-c0bc-f40f01bb1ae3.md"&gt;Printer&lt;/a&gt;

Here is a [link] (https://github.com/SimoPrG/HighQualityCodeHomework/tree/master/VariablesDataExpressionsAndConstants/Statistics/Help) to my project markdown documentation for more examples.

Thanks and Regards,
Simeon

**Comment by EWSoftware** [comment]
That's normal.  The output is geared towards GitHub output which doesn't generate extensions on its links either.

**Comment by SimoPrG** [comment]
Thanks for the replay! I didn't realize the output is for the wiki. There the links work like a charm. You helped me a lot and I am very grateful!

Cheers!

**Comment by moethu** [comment]
Hi Guys,
thanks for the reference to this issue.
But once I uploaded the mds they don't work as expected for me. If I follow the example link above, after following the first link I get:
![2015-07-17_14h32_15](https://cloud.githubusercontent.com/assets/8201465/8748187/cac7b212-2c90-11e5-8503-f72c529e37af.png)

**Comment by EWSoftware** [comment]
As noted above, the output is intended for wiki sites, not the source repository.  I could add the extensions but even then, there's no guarantee the content would work as expected in all cases.  Upload the content to the project wiki and it will work as expected.

**Comment by moethu** [comment]
Hi, sorry, my fault, I skipped the wiki part.
What do you think about an optional solution, a checkbox enabling links to contain the md suffix?
I'm asking because if one is maintaining several repos, cloning and maintaining the wiki repo as well doubles the amount of local repos and therefore commit transactions.

**Comment by EWSoftware** [comment]
No, adding the extensions to the links breaks the wiki content as then it just shows the raw content.  As stated, the presentation style is for wiki output not source repos.  The output deployment plug-in can be used to copy the content to the wiki repo location and one extra push doesn't require that much effort.
