### ISSUE TITLE
Search functionality is not working when the project is hosted on IIS. 

### ISSUE THREAD

**Issue by vikasrmahajan** [EWSoftware/SHFB#144]
Search functionality is working fine when we launch the index.html page but it is not working on IIS when the project is hosted on IIS, Please provide me the solution as early as possible.

**Comment by EWSoftware** [comment]
What presentation style are you using?

**Comment by vikasrmahajan** [comment]
We had build the project as web project from sandcastle and added it into
the visual studio solution file. then entire application is hosted into the
IIS.

**Comment by EWSoftware** [comment]
Please answer the questions that I asked:

- What version of the help file builder are you using?
- What presentation style is selected in your project?
- When you do a search, what happens?  Do you see the search page trying to find results?  Does nothing happen?  Something else?

**Comment by EWSoftware** [comment]
No response from OP.  Re-open if you can answer the questions as requested.

**Comment by vikasrmahajan** [comment]
Hi Eric,

Thanks for your responses.

Search functionality is working fine now. i missed some search related
files in previous build.

Thanks
Vikas
