### ISSUE TITLE
Cannot open or create documentation project in VS2015

### ISSUE THREAD

**Issue by thomaslevesque** [EWSoftware/SHFB#149]
After installing VS2015 and SHFB v2015.5.2.0, I can't open any documentation project. It fails because it doesn't find the file "C:\SandCastleHelpFileBuilder.targets". After investigation, it seems to be because the environment variable SHFBROOT is not defined. Defining it to the SHFB install directory fixes the problem.

Shouldn't the installer set this variable?

**Comment by EWSoftware** [comment]
You probably just need to reboot.  It doesn't always take effect immediately.

**Comment by thomaslevesque** [comment]
OK, thanks.

Is it really necessary to reboot just for setting an environment variable, though?

**Comment by EWSoftware** [comment]
It seems to vary.  I typically don't have to but there are some systems that do for whatever reason.  That's why there's the option to reboot at the end of the guided installer.
