### ISSUE TITLE
Warnings with SHFB + Code Contracts

### ISSUE THREAD

**Issue by pswg** [EWSoftware/SHFB#15]
In my project, I'm using SHFB to generate documentation and [code contracts][2]. I've encountered a very peculiar situation where I have an interface that has an associated contract class and a property with XML doc comments:

    /// <summary>Interface which describes an extensible object.</summary>
    [ContractClass(typeof(ExtensibleContract))]
    public interface IExtensible
    {
        /// <summary>Gets the collection of extensions.</summary>
        /// <value>The collection of extensions</value>
        IList<Extension> Extensions { get; }
    }

    [ContractClassFor(typeof(IExtensible))]
    internal abstract class ExtensibleContract : IExtensible
    {
        public IList<Extension> Extensions
        {
            get
            {
                Contract.Ensures(Contract.Result<IList<Extension>>() != null);
                return null;
            }
        }
    }

But when I try to implement it, like this:

    /// <summary>A Foo</summary>
    public class Foo : IExtensible
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Foo"/> class.
        /// </summary>
        protected Foo() { this.Extensions = new List<Extension>(); }

        /// <inheritdoc />
        public IList<Extension> Extensions { get; private set; }
    }

SHFB generates this warning.

> Warning BuildAssembler : warning : ResolveReferenceLinksComponent: [P:My.NameSpace.Foo.Extensions] Unknown reference link target 'M:My.NameSpace.IExtensible.get_Extensions'.

This only seems to happen when I have the `ContractClassAttribute` on an attribute, and indeed the problem seems to related to the way the code contracts rewriter generates the final interface documentation. I opened up the output assembly in dotPeek and found that it had added the following XML doc comments:

    /// In IExtensible ...
    /// <getter><ensures csharp="result != null" vb="result <> Nothing">result != null</ensures></getter>
    IList<Extension> Extensions { get; }

    /// In Foo ...
    /// <getter><ensures inheritedFrom="M:My.Namespace.IExtensible.get_Extensions" inheritedFromTypeName="IExtensible" csharp="result != null" vb="result <> Nothing">result != null</ensures></getter>
    public IList<Extension> Extensions { get; private set; }

It seems to be this `M:….get_Extensions` reference in the rewritten code that's the problem.

**Comment by EWSoftware** [comment]
What presentation style are you using?  There's code in the transformations to strip the ".get_" and ".set_" prefixes from the member IDs but its possible it got missed somewhere.

**Comment by pswg** [comment]
If referring to the output help file formats, I'm only using "Website (HTML/ASP.NET)".

**Comment by EWSoftware** [comment]
No, the presentation style: VS2005, VS2010, VS2013.  Open the project properties and go to the Help File category.  You'll see it listed there.

**Comment by pswg** [comment]
Ah sorry, VS2010. I don't see VS2013, is this because I'm running VS 2012, or do I need to update SHFB?

**Comment by EWSoftware** [comment]
The VS2013 style wasn't added until v2014.5.31.0 and there was a fix for this issue implemented in v2014.11.22.0.  So, if you're running anything older than those, upgrading to the latest release should resolve the issue.  Be sure to read through the release notes as there were some breaking changes that require some updates to the component and plug-in configurations.

**Comment by pswg** [comment]
Thanks, I'm evaluating it now, and will let you know if this solves my issue with code contracts.

**Comment by pswg** [comment]
Thanks again, this has solved my issue with code contracts, and a few more warnings I was seeing. I was upgrading from 2014.2.15.0 Beta, so I basically had to completely re-create the shfbproj from scratch, but this was actually a lot easier than I thought it would be.
