### ISSUE TITLE
Copy feature is not displaying in Chrome browser but it is displaying in internet explorer browser.please let me know how it can display in chrome?

### ISSUE THREAD

**Issue by vikasrmahajan** [EWSoftware/SHFB#150]

**Comment by EWSoftware** [comment]
Chrome doesn't allow access to the clipboard from script, at least it didn't and still doesn't as far as I know.  Note also that the Copy feature is disabled in Chrome on the MSDN site for the same reason.

**Comment by vikasrmahajan** [comment]
Ok, Thanks
