### ISSUE TITLE
Installation EXE not signed

### ISSUE THREAD

**Issue by frankrem** [EWSoftware/SHFB#151]
I noticed that the installation EXE is not signed. Is that because you consider the download from your github repo to be inherently authentic or any other reason? (question is not meant to be suggestive). It may be useful if the EXE is to be published somehere else.

**Comment by EWSoftware** [comment]
I don't recall ever seeing any other open source projects with code signed installers, executables, or other assemblies.  Code signing requires a certificate, renewable every 1 to 3 years, which costs money.  I get a few donations but nowhere near enough to cover such a cost.

This is the official project site so I'd consider it the only trusted source.  If you download the executables from anywhere else, I make no guarantee as to their authenticity.  That said, this is an open source project so, if you don't trust the released executables even from this site, you're free to download the code and built them all yourself.

**Comment by sharwell** [comment]
I agree with @EWSoftware here.

One thing that *could* work is joining the .NET Foundation. One of the benefits provided by the .NET Foundation to member projects is [Authenticode signing for binaries and installers](http://www.dotnetfoundation.org/about). On the [FAQ page](http://www.dotnetfoundation.org/faq) I notice that it does not prescribe a license or governance model, and also noticed that some member projects like [IdentityServer](http://www.dotnetfoundation.org/thinktectureidentityserver) are hosted in their own organizations on GitHub.
