### ISSUE TITLE
Setting visibility for a class with a constructor and one property

### ISSUE THREAD

**Issue by miksh7** [EWSoftware/SHFB#152]
When configuring visibility in API filter for a class with a constructor and one property (or maybe in general for a class with two child items) and if you uncheck one of the child checkboxes then the parent checkbox is unchecked too.
E.g. for
[X]  MyClass
   [X] Constructor
   [X] MyProperty

here what happened after unchecking constructor
[ ]  MyClass
   [ ] Constructor
   [X] MyProperty

**Comment by EWSoftware** [comment]
That's normal.  It's done to produce a more efficient filter and is noted in the [API Filter](http://ewsoftware.github.io/SHFB/html/7df16a60-f718-4b8f-bfa2-88c42906070c.htm#IncludeExclude) documentation.
