### ISSUE TITLE
Enhancement: Add "This class cannot be inherited." to summary of sealed classes

### ISSUE THREAD

**Issue by RalfKoban** [EWSoftware/SHFB#153]
Hi,

it would be nice if SHFB would have an option to automatically add the sentence "This class cannot be inherited." to the end of the summary text of classes that are sealed, so that a summary would look like:

"Provides some methods to do something. This class cannot be inherited."

BR,
Ralf

**Comment by EWSoftware** [comment]
I'm not sure how much benefit this really provides.  It's apparent from the declaration that its sealed.  Also, you're adding text to the user's summary which may or may not flow very well.  Looking at the XML comments for the base framework.  That text is actually in the XML comments for the types so it isn't being automatically added for the MSDN content.
