### ISSUE TITLE
MRefBuilder crashes "not possible but apparently it happened"

### ISSUE THREAD

**Issue by AnEnglishmanInNorway** [EWSoftware/SHFB#154]
Generating documentation for one of our projects which uses a 3rd party charting product, SciChart, I get the crash stack below from mrefbuilder. The critical line is doubtless the one that says:

    No members in the template matched the parameters of the specialization.  This is not possible but apparently it happened.

This is apparently caused by one of the 3rd party classes:

    public class XyzDataSeries<TX,TY,TZ> : Abt.Controls.SciChart.Model.DataSeries.DataSeries<TX,TY>
	    where TX : System.IComparable
	    where TY : System.IComparable
	    where TZ : System.IComparable
        Member of Abt.Controls.SciChart.Model.DataSeries

The project builds fine and the application using it runs. SciChart is downloadable for demo, if anybody wants to look more closely at the assembly

    GenerateRefInfo:
      MRefBuilder (v2015.7.25.0)
      Copyright c 2006-2015, Microsoft Corporation, All Rights Reserved.
      Portions Copyright c 2006-2015, Eric Woodruff, All Rights Reserved.
      Loaded 1 assemblies for reflection and 4 dependency assemblies.
    MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Abt.Controls.SciChart.Model.DataSeries.XyzDataSeries`3<System.DateTime,System.Double,System.Double> [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error : Abt.Controls.SciChart.Model.DataSeries.XyzDataSeries`3<System.DateTime,System.Double,System.Double>.Append(System.Collections.Generic.IEnumerable`1<System.DateTime>,System.Collections.Generic.IEnumerable`1<System.Double>[]) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error : No members in the template matched the parameters of the specialization.  This is not possible but apparently it happened. [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ReflectionUtilities.GetTemplateMember(Member member) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteTypeElements(TypeNode type) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteType(TypeNode type) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitType(TypeNode type) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitTypes(TypeNodeList types) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespaces(NamespaceList spaces) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespaces(NamespaceList spaces) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis() [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj]
    Done Building Project "C:\snip snip\Source\Documentation\Help\Working\GenerateRefInfo.proj" (default targets) -- FAILED.

**Comment by EWSoftware** [comment]
Can you provide a small example that demonstrates the problem?  I can download the demo version but I'll need something to actually produce the error since I'm not familiar with it's use and I may not come up with something that causes the problem.

**Comment by AnEnglishmanInNorway** [comment]
Hi Eric. I think this will do it. If you remove one of the two Append overloads then all is ok. If it doesn't show the error when you try it, let me know and I'll zip up my file structure

	using System;
	using System.Collections.Generic;

	namespace PlotControl
	{
		public abstract class MyDataSeries<TX, TY>
			where TX : IComparable
			where TY : IComparable
		{
			public virtual void Append(IEnumerable<TX> x, params IEnumerable<TY>[] yValues) { }
			public virtual void Append(TX x, params TY[] yValues) { } 
		}

		public class MyDataSeries<TX, TY, TZ> : MyDataSeries<TX, TY>
			where TX : IComparable
			where TY : IComparable
			where TZ : IComparable
		{
			public override void Append(IEnumerable<TX> x, params IEnumerable<TY>[] yValues) { }
			public override void Append(TX x, params TY[] yValues) { }
		}
		
		public class MyTimeDataSeries : MyDataSeries<DateTime, double, double>
		{
		}
	}

**Comment by JaroslavKaas** [comment]
We have same problem after upgrade from SHFB 2014.* to 2015.*.

Much smaller example:

```C#
using System.Collections.Generic;

namespace ShfbCrashTest
{
  public class MyClass<TKey, TValue> : IComparer<KeyValuePair<TKey, TValue>>
  {
    public bool Compare(KeyValuePair<TKey, TValue>[] other, bool nothing) { return false; }
    public int Compare(KeyValuePair<TKey, TValue> x, KeyValuePair<TKey, TValue> y) { return 0; }
  }

  public class MyNewClass : MyClass<int, int>
  {
  }
}
```

Just a small change

```C#
    public bool Compare(KeyValuePair<TKey, TValue> other, bool nothing) { return false; }
```

or

```C#
    int IComparer<KeyValuePair<TKey, TValue>>.Compare(KeyValuePair<TKey, TValue> x, KeyValuePair<TKey, TValue> y) { return 0; }
```

and no exception occurs.

**Comment by EWSoftware** [comment]
This is related to the fix for issue #57.  Prior to fixing that issue, the documentation produced in that case and this one was incorrect as it was just grabbing the first overload.  The fix didn't go quite far enough and only worked for parameters that are intrinsic types.  For generic types, it tries to compare `KeyValue<int, int>` to `KeyValue<TKey, TValue>` and doesn't get a match.  The fix is to add another check to see if both types are generic and, if so, if the template parameter count and names match.  If they do, it's considered a match.

**Comment by EWSoftware** [comment]
I've attached a patched version of MRefBuilder.exe to the release page (https://github.com/EWSoftware/SHFB/releases/tag/v2015.7.25.0).  Extract it and replace the installed version of MRefBuilder.exe with it and see if it fixes the issue.

**Comment by AnEnglishmanInNorway** [comment]
Sorry it took so long for me to test this, I've been on vacation. The patched MRefBuilder.exe works fine on the project which originally caused the problem, so you've definitely got it. Thanks a mint!
