### ISSUE TITLE
Install and user profiles

### ISSUE THREAD

**Issue by gfkeogh** [EWSoftware/SHFB#155]
*FYI - I finally discovered why I could not open shfbproj projects after upgrading to Visual Studio 2015 a few weeks ago. I have pasted below an explanatory email I posted into the 'ozdotnet' mailing list -- Greg*

---

After stuffing around wasting another hour I think I've uncovered the cause of shfbproj files being "not supported", but I'm not sure who is to blame.

My usual 'greg' login account is a normal user, when I need to elevate I have a dummy user called 'max' (aka Max Power from a Simpsons episode) who is an Admin. When installing Sandcastle I was asked to elevate to be max, so it looks like the VS extensions went in under max's profile. Confirmed by running VS2015 as max, then I'm asked to upgrade the help project and it works. Running vs2015 as greg shows no help project support at all.

Then I uninstall, make greg an Admin and reinstall, return greg to a normal user. Now I have help project support in VS2015.

So I'm not sure who to blame: Does VS not support extensions for all users? Does Sandcastle install extensions per-user incorrectly? Did my greg/max flipping convention upset something? Uh?! Anyway, by jumping through a few hoops I now have VS2015 and Sandcastle project support going again.

**Comment by EWSoftware** [comment]
VSIX packages are installed for the current user by default.  You can install them for all users but the Sandcastle Installer doesn't support that option.  You can install the package manually by running the following command:

```
VS2013:
"%VS120COMNTOOLS%\..\IDE\VSIXInstaller" /a SHFBVisualStudioPackage.vsix

VS2015:
"%VS140COMNTOOLS%\..\IDE\VSIXInstaller" /a SHFBVisualStudioPackage.vsix
```

Note also that the schemas and code snippets are installed based on the current user as well.  They too can be installed manually if wanted.

**Comment by sharwell** [comment]
@EWSoftware Since most of the Sandcastle tooling is installed for all users, would it make sense to install the extension for all users as well? We can force the VSIX installer to install the extension for all users [like this](https://github.com/github/VisualStudio/blob/d33b72695a10a32f03f84115dbb45231e06d3e43/src/GitHub.VisualStudio/source.extension.vsixmanifest#L13).

**Comment by EWSoftware** [comment]
I wasn't aware that was an option.  I can update the manifest to install for all users.
