### ISSUE TITLE
Question on in-page links

### ISSUE THREAD

**Issue by Stoffelche** [EWSoftware/SHFB#156]
When I use an in-page link to another section in the same aml-document, it only works, when a display text is explicitly displayed within the opening and closing tag of the link.
From the MAML-documentation I was expecting that when I use the link as self-closing element as for example
`<link xlink:href="#NextSection" />`
the title of NextSection would be used as display text for the link. But instead, the link does not work at all.
Why is this so? I think it would be logical to see the title of the section for the link text and it would be easier to maintain.
Thanks, Stefan

**Comment by EWSoftware** [comment]
As noted in the MAML guide in-page links do require inner text.  They aren't like topic links for which there is metadata loaded at the start of the build.  It may be possible to modify the XSL transformations to attempt to find the target element with the given address and use its inner text but I'm not sure.

**Comment by Stoffelche** [comment]
Thank you for the clarification. I actually did overlook the line in the MAML guide, which states that for in-page links the inner text is required.
Thanks, Stefan
