### ISSUE TITLE
Poor performance on Win10 (Windows Defender)

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#158]
On Windows 10, Windows Defender goes nuts when SHFB is generating documentation, severely impacting performance. While the .html files are being generated, CPU usage by its "antimalware service" will rise to 70-100% (on an i7 quadcore with HT, so that's a huge amount).
Obviously, disabling Windows Defender would help (even though Win10 will just reenable it automatically after a while), as would installing different antivirus software.

What I'm wondering is, would it be viable for the toolchain to produce different extensions (e.g. .dat or .txt) for its intermediate files, to avoid excess scanning? Or produce them as entries in a larger file (e.g. an ESENT database)? Or would that break the final construction of the output file(s)?
Of course, this assumes the scan is triggered by the .html extension, rather than being done on any file creation, which I can't be sure of at this point; it seems likely, however.

**Comment by EWSoftware** [comment]
In rebuilding the SHFB help under Windows 10 I didn't see a significant impact from the anti-malware service.  It averaged around 8-12% for the majority of the build with a short lived spike to 70-80% when the main SHFB help file content was generated.  Overall, the help built a couple of minutes faster on Windows 10 compared to the last build logs which were generated under Windows 8.

If the anti-malware service is causing issues in you case, I'd suggest changing the WIndows Defender settings to exclude the build folder at the minimum or, if you store all projects in a common location, exclude that entire folder from being scanned.  In doing that, the service barely did anything while performing a build.  There are also options to exclude specific file extensions so you may want to use those if you don't want to exclude by folder.
