### ISSUE TITLE
Question on the use of generated xml file instead of the csproj

### ISSUE THREAD

**Issue by Stoffelche** [EWSoftware/SHFB#159]
Is it possible to have Sandcastle work with the generated XML document file alone, instead of extracting all types from the asssembly?
My problem is, that I have a set of DLLs with many classes, of which I only want to document a few.
My approach is to write conceptual content first and add summary only to classes which are referred from the conceptual content. 
I don't want to have automatically generated entries for classes in the documentation, for which I don't have written an documentation myself.
I know I can work with API Filter, but this is quite tedious, because even opening the API Filter window takes quite a while. If Sandcastle would just take the summaries from the generated compiler-generated XML, then I wouldn't have to manually synch API Filter with the changing documentation state. Also, I guess, it could speed up things a lot. If I don't use API Filter the help file builder process  takes veeeeery looooong.
Thanks, Stefan

**Comment by EWSoftware** [comment]
It's not a matter of just using the comments to produce the documentation.  The assemblies have to be parsed in order to determine visibility, inheritance, and all the other stuff that cannot be inferred from the comments alone.

It's possible you could create a plug-in for SHFB that auto-generates an API filter based on the member IDS in the XML comments files.  It's not something I'm going to get to anytime soon so if you need it, I'd suggest having a go at writing it yourself.

**Comment by Stoffelche** [comment]
Thanks a lot for this reply. Could you point to some good starting point for the task to write a plug-in? 
Possibly an other plug-in with similar functionality? Some info about how to install / register the plugin and the like?
Thanks, Stefan

**Comment by Stoffelche** [comment]
I have edited my comment (please see above). As it does not appear as fresh content it might be overlooked, so I write this meaningless comment to draw attention. Sorry but don't know how else...

**Comment by EWSoftware** [comment]
I saw the update yesterday, just didn't get a chance to reply.  You need to be patient.  I reply to requests when I have the time which may take a day or so sometimes.

As to your request, see the help topic [Creating a Build Process Plug-In](http://ewsoftware.github.io/SHFB/html/a14e026e-642f-4ce6-9506-341e57cc3d1f.htm).  There aren't really any existing plug-ins that do something similar to what you want and there isn't much info on the API filter format yet except this old blog post: http://blogs.msdn.com/b/sandcastle/archive/2008/06/18/filtering-apis-using-sandcastle.aspx.

The best approach would probably be to scan your XML comments files and build a list of unique namespaces (fully qualified type names minus the type name itself).  You could also generate all possible root namespaces from each of them too (i.e. `Namespace1.Namespace2.Namespace3` would break down into `Namespace1`, `Namespace1.Namespace2`, and `Namespace1.Namespace2.Namespace3`).

Exclude all namespaces and, within each namespace with commented types, add an API filter entry to include just the types found in the XML comments files.  Your plug-in would run in place of the `GenerateApiFilter` build step.  I'd give that a try first to see if it works.  If not, then you can run the partial build to figure out the actual namespaces and types.  The `AdditionalReferenceLinks` plug-in shows an example of doing that.

**Comment by Stoffelche** [comment]
Hi, sorry for having made too much fuzz about my request. I had made the mistake to edit my first post instead of doing a new one, And then I wanted to draw attention to the fact that its content had changed.
Anyway in the meanwhile I have coded my Plug-In (Name: XmlContentFilter).
If you want me to share it somehow, Please tell me where to put it. Or I could just zip it and mail it to you.
Thanks, Stefan

**Comment by EWSoftware** [comment]
No problem.  You can e-mail the plug-in to me.  My e-mail address is in the footer of the pages in the help file.
