### ISSUE TITLE
Links Between Multiple Help File Projects

### ISSUE THREAD

**Issue by Arno-DQ** [EWSoftware/SHFB#161]
Hello all,

I have a question about project configuration when it comes to working with multiple helfile projects. I have two assemblies. Each has a corresponding helpfile project (API reference). In helpfile project B, I can add codeEntityReference links, in conceptual topics that refer to entities in assembly A: <codeEntityReference qualifyHint="false">T:AssyA.ClassA</codeEntityReference>

When installing helpfile A and B into the Microsoft Help Viewer through Add/Remove content, the links that are part of helpfile B, to entities in helpfile A,  show up as clickable links and function properly.

However, when I introduce a third helpfile project (C), and add the plug-in "Conceptual Only" and then add two code entity references to each class (in assembly A and B), neither links are clickable after installing into the HelpViewer.

What do I need to do to configure helpfile project C properly? I've added the Additional Link References plugin and added both the helpfile project A and B. However, this doesn't seem to be sufficient. All projects have the ESENT data caches enabled.

**Comment by EWSoftware** [comment]
With conceptual content only, there's nothing to use to generate a valid reference link for third-party APIs.  I doubt the Additional Reference Links plug-in is an option as the Additional Content Only plug-in suppresses the build steps it needs to run.  In this case, only links to base framework members would be available.

If it's an option, I'd suggest moving the content of the conceptual content only project into one of the others that has API content.

**Comment by Arno-DQ** [comment]
Thanks for the explanation. I think I will create a dummy assembly and filter out its one class its going to get, this way can can still keep the conceptual helpfile somewhat separate from the API helpfiles.
