### ISSUE TITLE
Entity References: No inherited / additional reference linked entities

### ISSUE THREAD

**Issue by Arno-DQ** [EWSoftware/SHFB#162]
Hello,

Currently, I am unable to h ave the Entity References (Code Entities) to show entities other than those picked up from the documentation sources added to a project. When I refer to another helpfile project through the Additional Link References plugin, the referenced entities do not become available. Even without this, inherited entities do not show up either. Only the .NET framework entities are available.

It it possible to have referenced / inherited entities listed as well? This would increase ease of use a lot.

Thank you.

**Comment by EWSoftware** [comment]
It's not currently possible.  It only scans the XML comments for the documentation sources not for anything references by a plug-in.  I may be able to look for that plug-in specifically and scan the referenced projects.  I'll see what can be done.

**Comment by Arno-DQ** [comment]
Hi there,

Thank you for a quick response and your willingness to look into this. Much appreciated =)

**Comment by VBWebprofi** [comment]
:+1: I need this too.

**Comment by EWSoftware** [comment]
Merged with #899
