### ISSUE TITLE
Version builder plug-in

### ISSUE THREAD

**Issue by sameer-kumar** [EWSoftware/SHFB#164]
I have looked at the usage of **Version Builder** plug-in documented here:
http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm
However, I couldn't find anything related to implementing the version filter like on MSDN documentation. For example, if you go https://msdn.microsoft.com/en-us/library/system.collections.arraylist(v=vs.110).aspx, you will see an option to filter the .NET framework version at top of the page.

I'm new to **SHFB** so pardon my ignorance.

Thanks for your help!
Sam

**Comment by EWSoftware** [comment]
It's not really the same thing.  The Version Builder plug-in will add version information to each topic showing in which versions it appears.  Think of the dropdown on the MSDN site as physically switching between documentation sets, one site per version if you will.  If you pick a prior version, you're looking at the documentation as it was for that version.  There's probably some sort of content management system behind MSDN.  There is no equivalent functionality in the documentation produced by SHFB.

**Comment by sameer-kumar** [comment]
Thanks for confirmation.
I will look if SharePoint can do this.
That makes me realize about deployment. Is there any automated way of
deploying ouptput Html help files? I am using TFS with multiple branches.
So this automated deployment would be triggered from separate build
configurations pointing to separate web servers i.e. Dev, Test and Prod.

Thanks for your advice.

**Comment by EWSoftware** [comment]
The output deployment plug-in can be used to copy the build content to specific locations based on the output type.  However, it probably won't work for varying build configurations without using a [target override file](http://ewsoftware.github.io/SHFB/html/8ffc0d37-0215-4609-b6f8-dba53a6c5063.htm#TargetOverrides) to replace the plug-in configuration property.

A simple solution would be to XCOPY the build output to a location using the Post-Build Event in the project property settings.  There you could vary the location by configuration using the macro variables.
