### ISSUE TITLE
Question on enhancing <see> with equivalent to qualifyHint

### ISSUE THREAD

**Issue by Stoffelche** [EWSoftware/SHFB#167]
Suppose I would want to have the same qualifyHint feature with <see>-tag in the source code documentation as there is with the <codeEntitryReference> tag.
Right now I can add this attribute to the see-tag and it is transported to the comments-file but does not have any effect.
Can you give me some advice how to achieve that this attribute is used to optiionally write the whole namespace.type.member text in the help file?
Thanks, Stefan

**Comment by EWSoftware** [comment]
You'd have to take a look at the XSL transformations and copy how it does it for `codeEntityReference`.  See *utilities_dduexml.xsl* for the `codeEntityReference` template and *main_sandcastle.xsl* for the `see[@cref]` template.

**Comment by Stoffelche** [comment]
Thanks for the hints.
For now I have added it to the main_sandcastle.xsl for VS2013 output:
It looks kind of ugly but it works. It is ugly, because I have repeatedly pasted the qualifyHint-test. This is necessary, because the <referenceLink> tag is added at different positions in the choose-variants. I guess it would be more elegant to restructure the code to first write the <referenceLink> tag only once then do the choose block. But in order to do this there would be more knowledge about xsl necessary than I currently possess. Anyway I have pasted the changed  code. I did the same to the seealso-transformation.
What do you think about adding this feature to the tool, then I would not need to maintain my own changes?
Thanks, Stefan

<xsl:template match="see[@cref]" name="t_seeCRef">
<xsl:choose>
  <xsl:when test="starts-with(@cref,'O:')">
  <referenceLink target="{concat('Overload:',substring(@cref,3))}" display-target="format"
    show-parameters="false">
    <xsl:if test="@qualifyHint">
    <xsl:attribute name="show-container">
      <xsl:value-of select="@qualifyHint"/>
    </xsl:attribute>
    <xsl:attribute name="show-parameters">
      <xsl:value-of select="@qualifyHint"/>
    </xsl:attribute>
    </xsl:if>
    <xsl:choose>
    <xsl:when test="normalize-space(.)">
      <xsl:value-of select="." />
    </xsl:when>
    <xsl:otherwise>
      <include item="boilerplate_seeAlsoOverloadLink">
      <parameter>{0}</parameter>
      </include>
    </xsl:otherwise>
    </xsl:choose>
  </referenceLink>
  </xsl:when>
  <xsl:when test="normalize-space(.)">
  <referenceLink target="{@cref}">
    <xsl:if test="@qualifyHint">
    <xsl:attribute name="show-container">
      <xsl:value-of select="@qualifyHint"/>
    </xsl:attribute>
    <xsl:attribute name="show-parameters">
      <xsl:value-of select="@qualifyHint"/>
    </xsl:attribute>
    </xsl:if>
    <xsl:apply-templates/>
  </referenceLink>
  </xsl:when>
  <xsl:otherwise>
  <referenceLink target="{@cref}">
    <xsl:if test="@qualifyHint">
    <xsl:attribute name="show-container">
      <xsl:value-of select="@qualifyHint"/>
    </xsl:attribute>
    <xsl:attribute name="show-parameters">
      <xsl:value-of select="@qualifyHint"/>
    </xsl:attribute>
    </xsl:if>
  </referenceLink>
  </xsl:otherwise>
</xsl:choose>
</xsl:template>

**Comment by EWSoftware** [comment]
Use a [fenced code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to post the code.

**Comment by Stoffelche** [comment]
Thanks for this advice. I did so and updated my post.
Stefan
