### ISSUE TITLE
Windows 10 UWP Class Library won't compile

### ISSUE THREAD

**Issue by flamewave000** [EWSoftware/SHFB#168]
I've started working with Sandbox and so far it's been an awesome solution to handle my documentation needs. But I've run into a wall while working on a Windows 10 UWP app.

I'm getting the following error:
```SHFB: Error BE0073: A project with a different or higher framework version was found but that version (.NETCore 5.0) or a suitable redirected version was not found on this system.  The build cannot continue.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()```

I decided to try and just reference the xml documentation directly instead of using the CSProj. But that only ends up getting me this error instead:

```MRefBuilder : error : Unresolved assembly reference: Windows.Foundation.UniversalApiContract (Windows.Foundation.UniversalApiContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) required by ...```

Given that Windows 10 UWP is still fairly new and Sandcastle doesn't provide a framework option for UWP, is there a work around that I can use to get my help file to compile?

Thanks in advance!

**Comment by EWSoftware** [comment]
A reflection data set file can be created to define what makes up that particular framework.  You can probably copy the *.NETCore_4.5.1.reflection* file to *.NETCore_5.0.reflection* and modify the title and paths it contains to point to the .NETCore 5.0 folders.  You'll find the file in the *%ProgramFiles(x86)%\EWSoftware\Sandcastle Help File Builder\Data\.NETCore* folder.

The [Reflection Data Manager tool](http://ewsoftware.github.io/SHFB/html/032f1fab-6625-4ffb-9316-57fb3e4a03ff.htm) found in the SHFB installation folder can be used to create and edit the reflection data set files.  Once you create the file for .NETCore 5.0, you should be able to select it as a framework in the SHFB project properties after exiting and restarting Visual Studio if it was open when the file was added.

If you can tell me where you installed the UWP stuff from, I can create the file and include it for the next release.

**Comment by flamewave000** [comment]
Hey Eric,
Thanks for the info. I've been trying to set up the profile but I'm now getting
```Process is terminated due to StackOverflowException```

Here is a link to the .NETCore_5.0.reflection file I've generated by copying the 4.5.1 file like you suggested and then trying to fill in the holes the best I can. There currently is no general DLL assemblies in v5.0 like there was for 4.5.1. The folder structure and file system has completely changed.

https://onedrive.live.com/redir?resid=2BD6A68FA7F4E70!142650&authkey=!ACs6YJAyBwRuiKY&ithint=file%2creflection

**Comment by EWSoftware** [comment]
Where do you get the UWP stuff to install?  I've got Windows 10 and VS2015 but don't see any of the folders.  I installed VS2015 before the upgrade to Windows 10.  Do I just need to run the VS2015 installer again or is this something extra that needs to be downloaded?

**Comment by flamewave000** [comment]
In the VS2015 RTM installer (not the 2015 Preview), there is an option for installing "Universal Windows App Development Tools" which installs the Windows 10 UWP SDK.

**Comment by EWSoftware** [comment]
I didn't see it when installed under Windows 8 but perhaps its hidden there as it's not applicable.  I'll rerun it when I get the time and see if it's there now under Windows 10.

**Comment by flamewave000** [comment]
I'm working directly on a Surface Pro 3 i7 running Windows 10 (10525) with VS2015 Community RTM.

**Comment by raulplanas** [comment]
Any updates on when Windows 10 UWP will be supported?

**Comment by EWSoftware** [comment]
I'll see if I can take a look at it this weekend.

**Comment by flamewave000** [comment]
Cool, I hope you can get it up to speed with UWP. Thanks!

**Comment by EWSoftware** [comment]
Technically, this is .NETCore 5.0 but it differs significantly from past versions.  The assemblies are distributed as part of the Microsoft SDKs and Windows Kits SDKs rather than being found in the reference assemblies folders as with past versions.  The structure of the SDK folders also differs (one folder per assembly rather than all assemblies in one folder).  In addition, when used in applications, the references are added as a series of NuGet packages.

To properly support this I've had to make some changes to how the information in the reflection data set file is stored for this particular case.  The reflection data will also be separate from the prior .NETCore data since it differs so much.

I'm aware of two locations for assemblies.  There may be others but they'll have to be added as I'm made aware of them.  It'll be a week or two before I issue a new release.

**Comment by flamewave000** [comment]
Thanks Eric for looking into this. I'll be excited to test out the new version when you get it ready!

**Comment by rip327** [comment]
Yes. Very much looking to this update. Please let us know as soon as ready.

**Comment by damyanp** [comment]
Just in case anyone else is as stumped as I was, and they come across this thread while looking for the answer like I did:

The FrameworkVersion to use for UniversalWindows is ".NET for Universal Windows".

**Comment by pdefreitas** [comment]
I'm having this issue even with ".NET for Universal Windows" selected on my UWP dll project.

**Comment by EWSoftware** [comment]
@pdefreitas:  If you're using VS2015 Update 3, see issue #322

**Comment by pdefreitas** [comment]
@EWSoftware exactly that :+1:
