### ISSUE TITLE
Question: Is there anyway to get help pages created for Methods that dont exist?

### ISSUE THREAD

**Issue by netx123** [EWSoftware/SHFB#169]
To explain, I currently generate my help documentation from my managed C# code.
Which produces excellent documentation (for the C# methods)
However I also have wrappers for other languages such as C, VB, Perl etc...

Some of these wrappers include methods that are NOT in the C# code and therefore are not included in the help documentation.

Is there any way that I can get Sandcastle to also generate help pages for these conceptual methods? that look the same as the pages created for real existing methods? perhaps via conceptual pages or can <summary> tags be added for methods that don't exist in the my C# code?

**Comment by EWSoftware** [comment]
If the methods are not managed code, there's no way to generate topics for them automatically.  You can add conceptual help topics and document the methods using MAML.  You can mimic the API topic layout for the most part.
