### ISSUE TITLE
Launch button is disabled

### ISSUE THREAD

**Issue by SoftCircuits** [EWSoftware/SHFB#170]
Installed the compiled project. Rebooted. Ran the Sandcastle Help File Builder Project Launcher. Nothing I can do within the dialog will cause the Launch button to become enabled.

Located the GUI exe and ran it okay.

**Comment by EWSoftware** [comment]
The project launcher is only a means of defining how you want .shfbproj files opened if you were to double click on one in Windows Explorer.  In that case, this tool would open and the Launch button would be enabled.  If launched standalone using its shortcut, it simply lets you define whether you want SHFB projects opened in the standalone GUI or Visual Studio by selecting a radio button as a default method.  Checking the "Don't ask again" checkbox causes it to use the selection without showing the dialog if you double click a SHFB project in Windows Explorer.

If you just want to open the standalone GUI without a project, use its shortcut.  If using Visual Studio, you can launch it and open the project too.

**Comment by SoftCircuits** [comment]
In Windows 10, that seems to be the only command that is placed at the time of the Start Menu, so it's a little confusing. But I can get it working.

Thanks.

**Comment by EWSoftware** [comment]
On my system (also WIndows 10), the GUI shortcut is two places below the project launcher, fifth one overall in the Sandcastle Help File Builder group under All Apps.  There is no shortcut placed in the Start menu unless you're referring to the Most Used group which is controlled by the OS.

**Comment by SoftCircuits** [comment]
On my system, the launcher showed up in the main part of the Start menu. But I had to go to the Apps section and scroll down to find the GUI app.

Not really sure the rules Win10 uses. None of them show up initially in the Start menu now.
