### ISSUE TITLE
can't add codeEntityReference to interface method?

### ISSUE THREAD

**Issue by Petoj87** [EWSoftware/SHFB#173]
When i write the following `<codeEntityReference qualifyHint="true">M:Namespace.Interface.Method</codeEntityReference>` it just outputs Method in a bold font with no link?

**Comment by EWSoftware** [comment]
If you typed it in by hand, Is the ID correct?  Open the Entity References tool window, select Code Entities,  locate the member using the search option, and drag and drop it into the topic.  It will give you the correct ID format.

**Comment by Petoj87** [comment]
Thanks that resolved the issue!
