### ISSUE TITLE
Default HTML Table of Contents only showing one entry

### ISSUE THREAD

**Issue by ironsheik** [EWSoftware/SHFB#174]
I've built my help project and the CHM looks great. It has several root entries in the table of contents. However when I look at the HTML that is built, only the very first entry is displayed on the table of contents. I do see that all the individual HTML pages are built however it looks the Table of Contents doesn't list them.

html:

![html](https://cloud.githubusercontent.com/assets/8271253/9587472/94a93862-4fd7-11e5-900a-9f0856bb33e8.JPG)

chm:

![chm](https://cloud.githubusercontent.com/assets/8271253/9587479/9857c802-4fd7-11e5-8e77-fafdd5684609.png)

**Comment by EWSoftware** [comment]
The HTML table of content only shows what's relevant to the topic displayed.  Expanding the nodes on the left should show everything.  If you're building the content using different projects, make sure they're looking at the same set of assemblies.  If you're just changing the output format in the same project, the output should match.

**Comment by ironsheik** [comment]
sorry this issue was due to opening the index.html locally in chrome. It was blocking the load of roottoc.xml as a cross-origin request. I opened it up in IE and allowed blocked content and the navigation is fine in the HTML version.
