### ISSUE TITLE
Building just Intellisense files

### ISSUE THREAD

**Issue by gfraiteur** [EWSoftware/SHFB#175]
We are using SHFB to build our XML intellisense files. However these files currently come as a byproduct of generating the full documentation. Is it possible to generate just these files? This would help getting the build time much lower.

We have a documentation build too, but we don't build the documentation as a part of the normal product build.

**Comment by sharwell** [comment]
You are looking for the [IntelliSense Only Plug-In](http://ewsoftware.github.io/SHFB/html/1fcdf9d3-06fb-4a7b-a584-f55b6ea5baae.htm).
