### ISSUE TITLE
v2015.1.12.0 and v2015.7.25.0 Are not working with VS 2013 Update 5

### ISSUE THREAD

**Issue by AGICS** [EWSoftware/SHFB#176]
I have just removed VS 2012 and installed VS 2013 but when trying to install SHFB it will not migrate any existing documentation project.  Neither is there a template option to add a new documentation project to a solution.

The migration message says:

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Documentation, "C:\Users\AGI\Clients\AGI\Framework\Documentation\Documentation.shfbproj"

Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - Framework, "C:\Users\AGI\Clients\AGI\Framework\Solutions\Framework.sln"

The SHFB doesn't show on the list of installed VS products although it does show in windows programs and features.

The VS information is.
Microsoft Visual Studio Professional 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.5.51209

**Comment by EWSoftware** [comment]
I'd suggest uninstalling the SHFB package from Visual Studio if it's listed and reinstalling it.  Note also that there were project format changes in the latest release so it will ask to upgrade the project format.  You can run the VSIX file that comes with the guided installer by itself to install the package.  If there are issues, it will let you view the log to find out why it's not installing.

**Comment by AGICS** [comment]
Installing the extension independently of the executable solved it.  Interesting that it didn't work as part of the installer.

Thank you for your help.
