### ISSUE TITLE
Problem with reference dependancies

### ISSUE THREAD

**Issue by afx2004** [EWSoftware/SHFB#178]
I have two separate solutions I am trying to document and I am getting an MRefBuilder error:

MRefBuilder : error : Unresolved assembly reference: NationalInstruments.Common (NationalInstruments.Common, Version=13.5.40.173, Culture=neutral, PublicKeyToken=dc6ad606294fc298) required by NationalInstruments.DAQmx [D:\Development\Production\Manufacturing\New Ball Grading Rig\Documentation\Microsyn Ball Grader\Code\Help\Working\GenerateRefInfo.proj]

The problem is with the NationalInstruments.DAQmx reference.  Apparently it is looking for version 13.5.40.173 of NationalInstruments.Common.  The problem is it doesn't exist on my PC.  The current version of NationalInstruments.Common is 15.0.40.49154.  Visual Studio gets around the problem by adding an entry to app.config so that it points to the correct version and I was wondering if there was a way of pointing Sandcastle to the correct version the way Visual Studio does.  I am currently using version 2015.5.2.0 of SHFB.

**Comment by EWSoftware** [comment]
Use the [Assembly Binding Redirection](http://ewsoftware.github.io/SHFB/html/f5051d32-b973-4fe1-9ffe-e30531007691.htm) plug-in to redirect the older version to the newer one.  That's effectively what happens in app.config.

**Comment by afx2004** [comment]
Thanks, that has sorted it.  Although I noticed that it didn't seem to like capital letters for the public key token.  I initially just copied the value from the app.config file and it didn't work, it just gave the same error.  When I copied the public key token from the error message (that used only lower case letters) it worked fine.
