### ISSUE TITLE
Creating single website from different projects

### ISSUE THREAD

**Issue by pascalberger** [EWSoftware/SHFB#179]
We have an internal framework consisting of several NuGet packages, each having its own versioning and is in its own repository, and contains one assembly. The namespaces can be split across the assemblies and packages. Therefore we would like to generate a single documentation website for all our packages.
Is it possible with SHFB to create a single website (with a common TOC) from different sandcastle projects?
What we would like to achieve is, if a new version of a certain package is released we would like to build the documentation for this project on our build server and update the documentation site with the documentation for the updated project.

**Comment by EWSoftware** [comment]
You can use the Version Builder Plug-In to merge the projects at build time to produce a single website.  It's geared toward different versions of one or more assemblies but people have used it to combine different projects into one.  You can use the framework label and version values however you like.  The version value doesn't have to be numeric.

However, it isn't possible to build one project and merge its output into another so you'd always need to build the project containing the plug-in that references the other projects to refresh all of the content.

**Comment by pascalberger** [comment]
Thanks! Using Version Builder Plugin might work for our case

**Comment by AshShip** [comment]
I have the similar requirement to combine multiple documentation projects in single website. Can someone guide me to achieve that using Version builder, please?
