### ISSUE TITLE
Add support for sealed/NotInheritable to <see langword="..."/>

### ISSUE THREAD

**Issue by RobSiklos** [EWSoftware/SHFB#180]
The `<see langword="..."/>` construct currently has support for the `abstract` and `virtual` inheritance-related keywords (and their VB.Net equivalents), but for some reason the `sealed` keyword (and VB.Net equivalent) is not included.

Please add support for this.

**Comment by sharwell** [comment]
:+1: 

How would we support F#, which uses `[<Sealed>]` for this?

**Comment by EWSoftware** [comment]
I think using similar language as the other shared content items and the neutral text (sealed) for language specific spans will suffice.

**Comment by RobSiklos** [comment]
I think I fixed it - see pull request #182.
