### ISSUE TITLE
Adding new microsoft assemblies.

### ISSUE THREAD

**Issue by CharlesCross** [EWSoftware/SHFB#181]
I have a project which makes reference to a few items in EnvDTE.dll, which comes with VSSDK.  Unfortunately this assembly is not supported by Sandcastle.  Is there any way I can add this assembly to sandcastle so as to resolve the references?

Thanks in advance for any support,

Charles Cross

P.S.  The XML Schema Documentor does not support the latest version of Sandcastle.  Is this likely to be rectified any time soon?

**Comment by EWSoftware** [comment]
You can probably use the Additional Reference Links plug-in to accomplish this for the time being.  Create a project with the Visual Studio assemblies as the documentation sources.  Add that project as an entry in the plug-in's configuration.  Set the link type to MSDN.  When built, it should generate the necessary reflection data and references to the MSDN content for those types.  Longer term, I'll be looking into better support for this sort of thing using the reflection data set files which I think are a better approach for third party libraries like that.  I haven't gotten around to it yet though.

I don't support the XML Schema Documenter.  You'll have to open an issue on it's project site.

**Comment by CharlesCross** [comment]
Thanks
