### ISSUE TITLE
Document the App.config or settings.settings file

### ISSUE THREAD

**Issue by BuddyWork** [EWSoftware/SHFB#183]
I would like to know if it is possible to use Sandcastle to document the App.config key value settings 

Example
<AppSettings>
  <app key="mykey" value="my value" />
</AppSettings>

I could use the xml comment tag to document this key.

**Comment by EWSoftware** [comment]
Your example didn't come through but assuming it's the actual XML, there isn't a way to document XML files with code comments.  The classes behind settings and resource files could but are compiler generated.  Compiler generated classes are automatically excluded as they typically do not contain comments nor anything that should be publicly exposed.  In the last release, an option was added to expose public compiler generated classes such as those for data sets and entity models.  However, in this case, it won't help as the settings and resource classes are generated as internal classes.

Adding a conceptual topic and documenting them there is probably the only option in this case.
