### ISSUE TITLE
NamespaceDoc working beautifully - usually

### ISSUE THREAD

**Issue by NickLocke** [EWSoftware/SHFB#184]
I guess I have probably done something stupid, but I can't see what.  I have several occurrences of NamespaceDoc in my project, and then in the XML comments file.  Most of them, such as this one:

![rs4851](https://cloud.githubusercontent.com/assets/7830040/9982940/e62794e6-5fe4-11e5-87e4-b9c43c782404.PNG)

work fine:

![rs4852](https://cloud.githubusercontent.com/assets/7830040/9982970/9e9058ce-5fe5-11e5-935a-db1539a943cc.PNG)

But, this one is being very stubborn:

![cbus1](https://cloud.githubusercontent.com/assets/7830040/9982971/adc3733a-5fe5-11e5-8f8b-697426c34acf.PNG)

![cbus2](https://cloud.githubusercontent.com/assets/7830040/9982973/b86ab082-5fe5-11e5-9e22-1eb1e153361d.PNG)

Looking at the build log, I can see that something is not happy with that one:

![missing](https://cloud.githubusercontent.com/assets/7830040/9982974/c9411ec8-5fe5-11e5-8c7c-5486b95d73c5.PNG)

So, although I can see the appropriate bit in the XML file, it is being reported as missing.  I can't fathom why!  The whole XML file is a bit lengthy, and I can't see an obvious way to attach a file to this post anyway.

All help welcome, and I really do hope I have done something stupid!

Thanks, Nick.

**Comment by EWSoftware** [comment]
Check the build log to see what XML comments file it's using.  Check that file to see if it contains the namespace doc comments.  It could be out of date (i.e. debug vs release).

**Comment by NickLocke** [comment]
Hi Eric, thanks for the prompt response.
I've been caught out by the debug/release mismatch before, so I have already checked that.  So far as I can see everything looks fine.  Here are three bits of the log file:

![lb1](https://cloud.githubusercontent.com/assets/7830040/9986713/eadfd806-6037-11e5-9cc7-eac6a1e6bfc4.PNG)

![lb2](https://cloud.githubusercontent.com/assets/7830040/9986715/eee3a63a-6037-11e5-87c8-1c4d5c9fbac5.PNG)

![lb3](https://cloud.githubusercontent.com/assets/7830040/9986719/f30a697e-6037-11e5-9c8e-9bc5d2ca665e.PNG)

Then, the XML file itself:

![f1](https://cloud.githubusercontent.com/assets/7830040/9986722/fe52f698-6037-11e5-80df-8369eee70abb.PNG)

![f2](https://cloud.githubusercontent.com/assets/7830040/9986726/02a1efe2-6038-11e5-86f9-ed650d460ded.PNG)

That all looks ok (unless I'm missing something obvious), with everything coming from debug, but the comment is still reported as missing in the build log.

I'm not sure where to go from here.

Thanks,  Nick

**Comment by NickLocke** [comment]
Eric,
I have found the issue - and apologies for wasting your time.
In case it helps others....

I had a NamespaceDoc file elsewhere in my solution which, incorrectly, had the same Namespace as the file that was causing me problems.  So, the "empty" file from elsewhere [empty because I have not yet put any content into it] was being picked up by the build process, rather than the correct file.  As it has no data in it, it causes the "missing" report.  

Thanks again.  Lesson learned!
Nick
