### ISSUE TITLE
Downloads from CodePlex

### ISSUE THREAD

**Issue by FantasticFiasco** [EWSoftware/SHFB#185]
Hi.

I am looking for _Sandcastle Help File Builder v1.9.3.4 Beta 2_ but didn't find it anymore on CodePlex. Did you move it here or where can I find it?

**Comment by EWSoftware** [comment]
It's an old release so it's currently hidden.  I'll make it visible again.  However, since it is so old, I'd suggest upgrading to a later version since a number of fixes and new features have been added since then.

**Comment by FantasticFiasco** [comment]
Thanks! I really appreciate it and agree with you, we should probably upgrade.

At times like these I wonder why companies pay for support agreements from thirdparty developers where they get no help when the support from good open source owners are of this quality.
