### ISSUE TITLE
Welcome to the [TODO: Add project name]

### ISSUE THREAD

**Issue by aamirghanchi** [EWSoftware/SHFB#187]
Hi. I am a newbie. Where can I edit the Welcome message so that it shows the name of the actual project?

Thank you.

AMG

**Comment by aamirghanchi** [comment]
Answering my own question.
in the Project Explorer pane when I click the  ContentLayout.content file, I get the option to type in my text  for the Title on the new window.

**Comment by EWSoftware** [comment]
The help topics in the [Conceptual Content](http://ewsoftware.github.io/SHFB/html/3d4edd2d-7883-4508-b9d2-bd7b4d848b0d.htm) section of the help file provide details on working with conceptual content and the content layout file.
