### ISSUE TITLE
Side by side installation of different versions

### ISSUE THREAD

**Issue by gnimor** [EWSoftware/SHFB#188]
We have different code branches based on different versions of sandcastle. So my question is, is it possible to install different versions of SHFB on the same machine?

**Comment by EWSoftware** [comment]
You cannot install different versions of the Visual Studio package.  However, you can install separate versions of the build engine if building using MSBuild or a build server.  There's also a NuGet package available for use starting with the latest release.  See the [XCOPY/NuGet Build Server Deployment](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) topic for details.
