### ISSUE TITLE
 Error BE0065: BUILD FAILED: Access to the path 'C:\dev\myassembly.dll' is denied

### ISSUE THREAD

**Issue by acormier** [EWSoftware/SHFB#189]
SHFB: Error BE0065: BUILD FAILED: Access to the path 'C:\dev\myassembly.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

What could be causing that?
Thanks

**Comment by EWSoftware** [comment]
It's either open or locked by some other process.  If you've pointed your output folder at the same location as the assembly and are building website/markdown content, it will try to clear the folder and may be failing when it tries to delete the assembly.  Point the output folder somewhere else or to a subfolder.

**Comment by acormier** [comment]
Locked.  Of course!  Thanks for the quick response.
