### ISSUE TITLE
Document constant values

### ISSUE THREAD

**Issue by RobThree** [EWSoftware/SHFB#190]
I would like SHFB to, optionally, document constant **values** when specified as a transform argument similar to the `includeEnumValues` transform argument ([here](https://github.com/EWSoftware/SHFB/issues/120)).

````c#
public static class Foo
{
    /// <summary>
    /// The default maximum number of BAR values.
    /// </summary>
    public const int BAR = 3141592;
}
````

**Comment by EWSoftware** [comment]
I've had this on my To Do list for a little while to look into.  However, I think it's better implemented in the syntax generators as it can be output as part of the declaration.  There's only one value and it may have a non-numeric type.  The syntax generators handle this for attribute and optional values.

**Comment by RobThree** [comment]
Awesome! Thanks!
