### ISSUE TITLE
Ordering of API output

### ISSUE THREAD

**Issue by nbred5** [EWSoftware/SHFB#191]
Is it possible to select the order in which API documentation is produced?

I am currently using SHFB to produce some API Documentation for a .Net assembly, this is the primary API I am documenting, however this API uses classes from other referenced assemblies for which I also wish to produce the API documentation for typically using <see cref="" /> so I have also included those assemblies as Documentation Sources. 

The issue I have is that the output API Documentation (currently in OpenXML format) always seems to be in Alphabetical order by Assembly Name, whereas I would like the output API Documentation to be ordered with the primary API first

So for example I have the following Assemblies (names are for illustration purposes only)

AssemblyA
AssemblyB
AssemblyC
AssemblyD - Primary Assembly
AssemblyE

The Output API Documentation currently gives:

AssemblyA
AssemblyB
AssemblyC
AssemblyD - Primary Assembly
AssemblyE

Whereas I would like:

AssemblyD - Primary Assembly
AssemblyA
AssemblyB
AssemblyC
AssemblyE

Any insight or help in achieving this would be much appreciated.

**Comment by EWSoftware** [comment]
It's always ordered by namespace.  You'd have to modify the TOC transformations and maybe some of the presentation style transformations to sort it differently.

**Comment by nbred5** [comment]
Thanks for the information, I will have a look at the TOC transformations, looks like its time to brush up on my XSL knowledge, been a while since I have been there.
