### ISSUE TITLE
Error opening project settings in VS2015

### ISSUE THREAD

**Issue by situssoft** [EWSoftware/SHFB#192]
I'm seeing this error on both a completely new and empty SHFB project and on a older upgraded project when I attempt to open the project settings from solution explorer.

An error occurred trying to load the project properties window.  Close the window and try again.
Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "obj\Release|Any CPU\ProjectName.exe". Illegal characters in path.  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets

I'm using VS2015 Pro.

Any help most gratefully received

Thanks

Chris

**Comment by EWSoftware** [comment]
I'm not able to duplicate the issue.  Is there another project in the solution?  What if you just create a brand new SHFB project by itself and open the project properties without adding any documentation sources?

**Comment by situssoft** [comment]
I just created a brand new solution containing only a documentation project. I get the same error.

An error occurred trying to load the project properties window.  Close the window and try again.
Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "obj\Debug|Any CPU\Documentation1.exe". Illegal characters in path.  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets

Its late here now and I'm away tomorrow but I will attempt to get the sources for the VS extension and debug to gain some more insight into the problem. I will report back here when I have done so.

Thanks for taking the time to look at the issue.

Chris.

**Comment by situssoft** [comment]
The issue appears to be caused by having the Windows 10 DDK installed on my development system.

I have reproduced on a clean virtual machine using the following steps.

1. Install Visual Studio 2015 community edition.
2. Install SHFB latest release and restart machine.
3. Create an empty documentation project.
4. Open the documentation project property page - opens successfully.
5. Install the Windows 10 DDK and restart machine.
6. Open the documentation project, the property page displays correctly when auto opened by project state.
7. Close the property page 
8. Open the property page - Errors on open


With framework source stepping switched on the error can be seen occurring in RegexReplacement.cs at line 293 with the following call stack which suggests that DriverTestPackage.dll!Microsoft.DriverKit.WdkTestPackage.DriverTestPackage.Exec is involved. So I'm not sure how to proceed.

Chris

` 	Microsoft.Build.dll!Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(string resourceName, object[] args)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation(bool condition, string resourceName, object arg0, object arg1, object arg2)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(string currentDirectory, string itemSpec, string definingProjectEscaped, string modifier, ref string fullPath)	Unknown
Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ItemExpander.MetadataMatchEvaluator.GetMetadataValueFromMatch(System.Text.RegularExpressions.Match match)	Unknown
System.dll!System.Text.RegularExpressions.RegexReplacement.Replace(System.Text.RegularExpressions.MatchEvaluator evaluator, System.Text.RegularExpressions.Regex regex, string input, int count, int startat) Line 293	C#
System.dll!System.Text.RegularExpressions.Regex.Replace(string input, System.Text.RegularExpressions.MatchEvaluator evaluator, int count, int startat) Line 1096	C#
System.dll!System.Text.RegularExpressions.Regex.Replace(string input, System.Text.RegularExpressions.MatchEvaluator evaluator) Line 1058	C#
Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ItemExpander.IntrinsicItemFunctions<Microsoft.Build.Evaluation.ProjectItem>.ExpandQuotedExpressionFunction(Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem> expander, Microsoft.Build.Shared.IElementLocation elementLocation, bool includeNullEntries, string functionName, System.Collections.Generic.IEnumerable<System.Tuple<string, Microsoft.Build.Evaluation.ProjectItem>> itemsOfType, string[] arguments)	Unknown
Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ItemExpander.Transform<Microsoft.Build.Evaluation.ProjectItem>(Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem> expander, bool includeNullEntries, System.Collections.Generic.Stack<Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ItemExpander.TransformFunction<Microsoft.Build.Evaluation.ProjectItem>> transformFunctionStack, System.Collections.Generic.IEnumerable<System.Tuple<string, Microsoft.Build.Evaluation.ProjectItem>> itemsOfType)	Unknown
Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ItemExpander.Transform<Microsoft.Build.Evaluation.ProjectItem>(Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem> expander, bool includeNullEntries, System.Collections.Generic.Stack<Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ItemExpander.TransformFunction<Microsoft.Build.Evaluation.ProjectItem>> transformFunctionStack, System.Collections.Generic.IEnumerable<System.Tuple<string, Microsoft.Build.Evaluation.ProjectItem>> itemsOfType)	Unknown
Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ItemExpander.ExpandSingleItemVectorExpressionIntoItems<Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectItem>(Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem> expander, string expression, Microsoft.Build.Evaluation.IItemProvider<Microsoft.Build.Evaluation.ProjectItem> items, Microsoft.Build.Evaluation.IItemFactory<Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectItem> itemFactory, Microsoft.Build.Evaluation.ExpanderOptions options, bool includeNullEntries, out bool isTransformExpression, Microsoft.Build.Shared.IElementLocation elementLocation)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ExpandSingleItemVectorExpressionIntoItems<Microsoft.Build.Evaluation.ProjectItem>(string expression, Microsoft.Build.Evaluation.IItemFactory<Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectItem> itemFactory, Microsoft.Build.Evaluation.ExpanderOptions options, bool includeNullItems, out bool isTransformExpression, Microsoft.Build.Shared.IElementLocation elementLocation)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.CreateItemsFromInclude(string rootDirectory, Microsoft.Build.Construction.ProjectItemElement itemElement, Microsoft.Build.Evaluation.IItemFactory<Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectItem> itemFactory, string unevaluatedIncludeEscaped, Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem> expander)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateItemElement(bool itemGroupConditionResult, Microsoft.Build.Construction.ProjectItemElement itemElement)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateItemGroupElement(Microsoft.Build.Construction.ProjectItemGroupElement itemGroupElement)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.Evaluate()	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.Evaluate(Microsoft.Build.Evaluation.IEvaluatorData<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition> data, Microsoft.Build.Construction.ProjectRootElement root, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, int maxNodeCount, Microsoft.Build.Collections.PropertyDictionary<Microsoft.Build.Execution.ProjectPropertyInstance> environmentProperties, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Evaluation.IItemFactory<Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectItem> itemFactory, Microsoft.Build.Evaluation.IToolsetProvider toolsetProvider, Microsoft.Build.Evaluation.ProjectRootElementCache projectRootElementCache, Microsoft.Build.Framework.BuildEventContext buildEventContext, Microsoft.Build.Execution.ProjectInstance projectInstanceIfAnyForDebuggerOnly)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Project.CreateProjectInstance(Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation, Microsoft.Build.Execution.ProjectInstanceSettings settings)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Project.CreateProjectInstance()	Unknown
 	Microsoft.VisualStudio.Project.dll!Microsoft.VisualStudio.Project.ProjectNode.SetConfiguration(string config) Line 3764	C#
 	SandcastleBuilder.Package.dll!SandcastleBuilder.Package.Nodes.SandcastleBuilderProjectNode.SetConfiguration(string config) Line 868	C#
 	Microsoft.VisualStudio.Project.dll!Microsoft.VisualStudio.Project.ProjectConfig.GetMsBuildProperty(string propertyName, bool resetCache) Line 725	C#
 	Microsoft.VisualStudio.Project.dll!Microsoft.VisualStudio.Project.ProjectConfig.GetConfigurationProperty(string propertyName, bool resetCache) Line 201	C#
 	Microsoft.VisualStudio.Project.dll!Microsoft.VisualStudio.Project.ProjectNode.Microsoft.VisualStudio.Shell.Interop.IVsBuildPropertyStorage.GetPropertyValue(string propertyName, string configName, uint storage, out string propertyValue) Line 5962	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	DriverCommonPackage.dll!Microsoft.DriverKit.DriverCommonPackage.GetProjectProperty(EnvDTE.Project project, string propertyName, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy projectNode)	Unknown
 	DriverCommonPackage.dll!Microsoft.DriverKit.DriverCommonPackage.IsDriverProject(EnvDTE.Project proj)	Unknown
 	DriverCommonPackage.dll!Microsoft.DriverKit.DriverCommonPackage.IsDriverProjectLoaded()	Unknown
 	DriverTestPackage.dll!Microsoft.DriverKit.WdkTestPackage.Utilities.DriverDeployer.Exec(ref System.Guid pguidCmdGroup, uint nCmdId, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown
 	DriverTestPackage.dll!Microsoft.DriverKit.WdkTestPackage.DriverTestPackage.Exec(ref System.Guid pguidCmdGroup, uint nCmdId, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown`

**Comment by NerdyDuck** [comment]
+1. I have the same problem. Win 10 DDK installation seems to break the project settings, but only in VS. The standalone GUI seems to be unaffected. I will try to have a closer look at it next week.

**Comment by EWSoftware** [comment]
I'm not able to duplicate this issue.  I installed the WDK from here: https://msdn.microsoft.com/en-us/windows/hardware/dn913721.aspx

Are you using something different?  Can you send me an example that fails?

**Comment by NerdyDuck** [comment]
That's where I got the WDK from. [This project](https://github.com/NerdyDuck/NerdyDuck.CodedExceptions) is where I get the error, but it requires some setup to build (described in its Wiki). I still haven't had time to investigate the problem myself, maybe at the end of the week.

**Comment by situssoft** [comment]
I have an Azure VM you can access which displays the problem. Just need a way of passing you the access credentials.

What operating system are you testing on. My problem occurred on W10, I have reproduced on VMs running W10 and W Server 2012.

Chris.

**Comment by EWSoftware** [comment]
If you right click and select Properties, the error occurs.  If you just double click the Properties node, it’ll open just fine.  For now, use that as a workaround.  I'll look into why it's not working using the context menu.

**Comment by EWSoftware** [comment]
It appears to be a bug in VS2015 or an incompatibility with the older MPF project system used by SHFB.  An invalid configuration value gets passed to the project ("Debug|Any CPU" rather than just "Debug").  As a workaround, I now have it trim off the invalid part.

**Comment by EWSoftware** [comment]
Fixed with the latest commit.

**Comment by somtiwari** [comment]
Hi, 
Issue was coming due to WDK 10.0.
I resolved this issue by overriding get_CanonicalName(out string name) in my class which implements ProjectConfig.cs .
As this method will called only if you installed WDK.
and this method is passing configuration name as "Debug|Plateform". Below code fixed my issue.
public override int get_CanonicalName(out string name)
        {
            string name1 = string.Empty;
            int res = ((IVsCfg)this).get_DisplayName(out name1);
            name = name1.Substring (0,name1.IndexOf('|'));
            return res;
        }

**Comment by nadaHan** [comment]
Just change the name of the project folders to some shorter names, i had this issue because the solution was in many long names folders
