### ISSUE TITLE
Errors while starting a new project

### ISSUE THREAD

**Issue by RossManson** [EWSoftware/SHFB#195]
Just installed, tried to start a new project and get-
 "Unexpected error loading plug-ins: Access to the path 'C:\Users\<username>\Documents\My Music' is denied."
-and then-
"Object reference not set to an instance of an object.".

**Comment by EWSoftware** [comment]
It's trying to search for build components in the project folder.  Move the project to a subfolder so that it doesn't try to access the protected folders and all will be well.
