### ISSUE TITLE
Unexpected error preventing compile of doc project

### ISSUE THREAD

**Issue by michaeltagmose** [EWSoftware/SHFB#197]
Hi EW

I can`t seem to get around this one:

An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Hellosam.Net.Collections.ObservableDictionary`2<Invisio.Common.Dtos.FrequencyEnum,System.Double> [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]

The library containing the ObservableDictionary called Hellosam is not mine and I would like to exempt it from documentation. I`m not getting anywhere though, since most operations requires the project to compile. What to do?

Best regards

**Comment by EWSoftware** [comment]
Is that the full error?  It's not much to go on.  If you aren't using the latest release, upgrade.  That may fix the issue depending on what it is.  If you're using the solution as a documentation source, add the individual projects and exclude the failing one.  You may need to add it as a reference assembly in the SHFB project if it's used by the others.

**Comment by michaeltagmose** [comment]
Sorry for the delay. The full error looks like this:

<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2015.7.25.0" projectFile="C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\FittingProto Documentation.shfbproj" started="20-10-2015 09:29:26">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\&#39;
Locating components in the following folder(s):
    C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Framework reflection data location: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework
Using presentation style &#39;VS2013&#39; located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013&#39;
Loading and initializing plug-ins...
Lightweight Website Style Version 2015.7.25.0
Copyright &#169; 2006-2015, Eric Woodruff, All Rights Reserved
Portions Copyright &#169; 2014, Sam Harwell, All Rights Reserved
-------------------------------
Clearing any prior web/markdown output...
</buildStep>
<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: C:\Dev\Prototypes\FittingProto\FittingPrototype.sln
    Found project &#39;C:\Dev\Prototypes\FittingProto\FittingPrototype\FittingPrototype.csproj&#39;
    Found project &#39;C:\Dev\Prototypes\FittingProto\FittingService\FittingService.csproj&#39;
    Found project &#39;C:\Dev\Prototypes\FittingProto\Interfaces\Interfaces.csproj&#39;
    Found project &#39;C:\Dev\Prototypes\FittingProto\DTOs\Dtos.csproj&#39;

Parsing project files
    Found assembly &#39;C:\Dev\Prototypes\FittingProto\FittingPrototype\bin\Release\FittingPrototype.exe&#39;
    Found assembly &#39;C:\Dev\Prototypes\FittingProto\FittingService\bin\Release\FittingManager.dll&#39;
    Found assembly &#39;C:\Dev\Prototypes\FittingProto\Interfaces\bin\Release\Interfaces.dll&#39;
    Found assembly &#39;C:\Dev\Prototypes\FittingProto\DTOs\bin\Release\Dtos.dll&#39;

References to include (excluding framework assemblies):
    AutoMapper, Version=4.0.4.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005, processorArchitecture=MSIL
    EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL
    EntityFramework.SqlServer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL
    Hellosam.Net.Collections, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL
    Microsoft.Expression.Interactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Microsoft.Practices.Prism.Mvvm, Version=1.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Microsoft.Practices.Prism.Mvvm.Desktop, Version=1.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Microsoft.Practices.Prism.SharedInterfaces, Version=1.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Prism, Version=6.0.1.0, Culture=neutral, processorArchitecture=MSIL
    Prism.Wpf, Version=6.0.1.0, Culture=neutral, processorArchitecture=MSIL
    ServiceModelEx, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d0f8277329bba7a0, processorArchitecture=MSIL
    System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
SHFB: Warning BE0062: No XML comments files found.  The help file will not contain any member comments.
</buildStep>
<buildStep step="GenerateSharedContent">
Generating shared content files (en-US, English (United States))...
<plugIn name="Lightweight Website Style" behavior="After" priority="1000">
</plugIn>    Last step completed in 00:00:00,1397
</buildStep>
<buildStep step="GenerateApiFilter">
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00,0060
</buildStep>
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
[C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe - GenerateRefInfo.proj]
Build started 20-10-2015 09:29:28.
Project &quot;C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj&quot; on node 1 (default targets).
PrepareForBuild:
  Creating directory &quot;obj\Debug\&quot;.
GenerateRefInfo:
  MRefBuilder (v2015.7.25.0)
  Copyright &#184; 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright &#184; 2006-2015, Eric Woodruff, All Rights Reserved.
  Loaded 4 assemblies for reflection and 64 dependency assemblies.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Hellosam.Net.Collections.ObservableDictionary`2&lt;Invisio.Common.Dtos.FrequencyEnum,System.Double&gt; [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error : Hellosam.Net.Collections.ObservableDictionary`2&lt;Invisio.Common.Dtos.FrequencyEnum,System.Double&gt;.CopyTo(System.Collections.Generic.KeyValuePair`2&lt;Invisio.Common.Dtos.FrequencyEnum,System.Double&gt;[],System.Int32) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error : No members in the template matched the parameters of the specialization.  This is not possible but apparently it happened. [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ReflectionUtilities.GetTemplateMember(Member member) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteTypeElements(TypeNode type) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteType(TypeNode type) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitType(TypeNode type) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitTypes(TypeNodeList types) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespace(Namespace space) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespace(Namespace space) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespaces(NamespaceList spaces) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespaces(NamespaceList spaces) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis() [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj]
Done Building Project &quot;C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\GenerateRefInfo.proj&quot; (default targets) -- FAILED.

Build FAILED.

Time Elapsed 00:00:00.81
    Last step completed in 00:00:00,9751
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>

**Comment by EWSoftware** [comment]
Upgrade to the latest release (2015.10.10.0) and it should resolve that issue.

**Comment by michaeltagmose** [comment]
The issue seems to be solved, but this thing annoys me:
BuildAssembler : warning : ShowMissingComponent: [T:Invisio.Client.App] Missing <summary> documentation [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\BuildReferenceTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Invisio.Client.App.InitializeComponent] Missing <summary> documentation [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\BuildReferenceTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Invisio.Client.App.Main] Missing <summary> documentation [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\BuildReferenceTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [T:Invisio.Client.Bootstrapper] Missing <summary> documentation [C:\Dev\Prototypes\FittingProto\Doc\FittingProto Documentation\Help\Working\BuildReferenceTopics.proj]


I get a lot of these messages, and said component DO have summary entries. How do I get rid of all these warnings?

**Comment by EWSoftware** [comment]
Make sure the XML comments files are actually being generated when the assemblies are being built and that they are up to date based on the configuration you are using (Debug vs Release for example).  The build log will tell you what XML comments files it found, which ones it didn't, and where they are located.  You can check them to see if the noted comment elements do exist in the files it used for the build.
