### ISSUE TITLE
SEO friendly URLs

### ISSUE THREAD

**Issue by acormier** [EWSoftware/SHFB#200]
I recently upgraded and my help files url look like this:
... A7FBC69C.htm
but they used to look like this:
... T_Eto_Forms_ThemedControls_ThemedSpinnerHandler.htm

Sorry if this is obvious but I don't see what changed and how to change it back so I get SEO friendly urls.

Regrards,
Alain

**Comment by EWSoftware** [comment]
The Naming Method property probably got set to GUID.  Change it to Member Name.

**Comment by acormier** [comment]
Thanks a lot!  It was obvious (-:

**Comment by joriszwart** [comment]
Is there any way of doing this for conceptual documentation as well?

**Comment by EWSoftware** [comment]
@joriszwart: The IDs for MAML topics always default to GUIDs when the topics are created.  However, there is no longer any restriction that requires that it be a GUID.  You can change the IDs to something more readable.  However, it then becomes your responsibility to ensure that they are all unique.

**Comment by joriszwart** [comment]
Thanks. This works perfectly.

Additional explanation: this cannot be done from the Sandcastle GUI because the topic GUID is readonly. The GUIDs must be changed by hand in *.content* and *.aml* files.
