### ISSUE TITLE
Cannot build help for my PCL: .NETPortable 5.0 support/workarounds?

### ISSUE THREAD

**Issue by Myrmex** [EWSoftware/SHFB#201]
I'm trying to add documentation to my PCL targeting .NETPortable 5.0 but it seems SHFB is still not handling this version. Are there any workarounds to get it compile? You can easily reproduce the issue by creating a new PCL solution from VS2015 and adding a documentation project:

1. create a new portable library using the default VS2015 targets (.NET Framework 4.6, Windows Universal 10, ASP.NET Core 5). Of course, set the library properties under `Build` so that the `XML documentation file` is built.
2. add a new SHFB documentation project to the same solution.
3. add the PCL as the source in the `Documentation Sources` of the documentation project. Under `Project Properties` choose `.NET Portable Library 4.6`.
4. build: I get the error `A project with a different or higher framework version was found but that version (.NETPortable 5.0) or a suitable redirected version was not found on this system.  The build cannot continue`.

Thanks!

**Comment by EWSoftware** [comment]
It needs a reflection data set file.  As a workaround, you may be able to copy the *.\Data\.NETPortable_4.6.reflection file and change the title, version, and paths to the assembly locations accordingly.

**Comment by EWSoftware** [comment]
.NET Portable 5.0 actually appears to be more like the .NET Core 5.0 framework and uses the same set of assemblies.  As such, I've created a reflection data set file for it that gets placed in the Data\UniversalWindows folder.
