### ISSUE TITLE
Files to ignore in documentation project 

### ISSUE THREAD

**Issue by gugat** [EWSoftware/SHFB#202]
I added a documentation project to my solution using SHFB in Visual Studio 2015. What files should I ignore or not before pushing the project to a git repository? Is there a .gitignore for this ?

**Comment by EWSoftware** [comment]
Exclude the build output folder (.\Help under the project folder by default), the working folder (typically under the build output folder by default unless you change it), per-user settings files (*[ProjectName].shfbproj_[UserId]*), and output deployment plug-in folders if you use it.  For example:

```
# Sandcastle Help File Builder is a documentation generator add-in
Documentation/**/Help/
Documentation/WebHelp/
**/Doc/Help/
*.shfbproj_*
```

The above is from the SHFB .gitignore file.  Most of my documentation projects are under .\Documentation with a few separate projects with their own .\Doc folder.  Excluding the .\Help folder for each gets rid of the build output and the working folders.  The Documentation\WebHelp folder is the web output which is copied by the Output Deployment plug-in so I exclude it.  I don't have any per-user settings files but the last entry is there for completeness.  Everything else is included.  Adjust as needed.

**Comment by bleis-tift** [comment]
Are [these patterns](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore#L124) old?

**Comment by EWSoftware** [comment]
@bleis-tift:  Those are for [DocProject](https://docproject.codeplex.com/) not SHFB.
