### ISSUE TITLE
NuGet packages not building remarks or code examples.

### ISSUE THREAD

**Issue by ThadHouse** [EWSoftware/SHFB#204]
When using the NuGet packages instead of a local install of SHFB, remarks and code examples do not get added to the web help created. Using the same project file without the NuGet packages builds properly.

**Comment by EWSoftware** [comment]
Check the build log.  It will tell you what XML comments files are being used.  Check them to be sure that they XML comments you expect are actual there.  You may just need to rebuild them.  Or, if you tested it will the installed version afterwards, it may have rebuilt the project and regenerated the XML comments files.  Using the NuGet package may work now.

There's no difference in the tools between the two so I can't see any reason other than outdated or missing comments files for the comments to not show up.

**Comment by ThadHouse** [comment]
So I figured out what was happening. The project has an Intellisense only sandcastle project to grab the XML comments from <inheritdoc>. It also has a master project which creates all the online documentation. The intellisense only project is deleting the remarks and code tags, and then when the master documentation script runs, it does not have any of those tags in the xml file. Is there a way for the Intellisense only project to keep the remarks and code example tags in the xml file?

**Comment by EWSoftware** [comment]
No, the point of the IntelliSense only plug-in is to generate XML comments files that are suitable for use with IntelliSense.  Since it doesn't require the full set of XML comments, it strips out the unnecessary comment elements to reduce the file size.  Use the original XML comments files for the documentation build.

**Comment by ThadHouse** [comment]
Ok. Closing.
