### ISSUE TITLE
Adding documentation for generic type

### ISSUE THREAD

**Issue by dlipkie** [EWSoftware/SHFB#205]
I am trying to generate documentation for generic method 
```
static public T StringToEnum<T>(string nameOrCaption) where T : struct
```

using /// in Visual Studio 2013 the template is
```
        /// <summary>
        /// My Summary
        /// </summary>
        /// <typeparam name="T">Generic Type for an enum</typeparam>
        /// <param name="nameOrCaption">String to be converted to enum of type T</param>
        /// <returns></returns>
```
I am getting the following error in my generated help file.

```
===========
Return Value
Type: T

[Missing <returns> documentation for "M:TerraTechnology.TerraUtilLib.EnumUtils.StringToEnum``1(System.String)"]
============
```
Other non-generic methods are documented without error.

How do I supply documentation for the type T, e.g. 
   "T is a enum type"

**Comment by EWSoftware** [comment]
You've got an empty returns element.  Fill in the content for that element and the warning will go away.

**Comment by dlipkie** [comment]
Perfect solution. THANKS.
