### ISSUE TITLE
BHT0001 Warning with VS2015 Update 1

### ISSUE THREAD

**Issue by damyanp** [EWSoftware/SHFB#208]
Whenever I run sandcastle on a VS2015 Update 1 command prompt I get a BHT0001 warning:

    SHFB : warning BHT0001: Unable to get executing project:  Unable to obtain matching project from the global collection.  The specified project will be loaded but command line property overrides will be ignored. 

Is there a way to suppress this?  Or maybe fix the root cause?

This is with the EWSoftware.SHFB.2015.10.10.0 nuget package.

This repro contains a repro for this issue: https://github.com/damyanp/SandCastleRepros.  This exact same project works fine on VS2015.

**Comment by damyanp** [comment]
@rainersigwald

**Comment by EWSoftware** [comment]
This warning would indicate that something changed internally in MSBuild  Update 1 is still an RC so I'm not going to look at this until it's RTM since things may still change, I don't want to install it on my system until it is, and I don't currently have the time to set up a VM to try it out.

**Comment by damyanp** [comment]
I can confirm that this is still occurs when using the RTM version of VS2015 Update 1.

**Comment by EWSoftware** [comment]
The build task uses reflection to get the project instance being built.  MSBuild 14.0 changed the internal field names it looks for by prefixing them with an underscore.  For the time being use MSBuild 12.0.

**Comment by rainersigwald** [comment]
@EWSoftware Is there any way to avoid reflecting over internal MSBuild data structures?  What information are you trying to extract from the running msbuild?

**Comment by EWSoftware** [comment]
@rainersigwald  There are dozens of properties in a SHFB project along with various file collections and their metadata.  Custom properties that the build engine doesn't know about may also be referenced in files processed to replace substitution tags that use them.  It's just much more practical to [get the project instance](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderUtils/MSBuild/BuildHelp.cs#L409) from the build engine.

**Comment by kfertitta** [comment]
If I run "msbuild /tv:12.0 Foo.shfbproj", then I still see the warning.

**Comment by rainersigwald** [comment]
@kfertitta That switch affects behavior and the loading of some non-core DLLs like tasks; it doesn't control the core MSBuild engine.  You'll have to open a "Developer Command Prompt for VS2013" or explicitly invoke the 12.0 version of msbuild.exe (usually installed at `C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe`).

**Comment by kfertitta** [comment]
Got it.  Thanks.

**Comment by kfertitta** [comment]
So, is it at all safe to ignore this warning, or do I really have to build my help project separate from the rest of my product now (which does actually seem to need MSBuild 14.0)?  A quick try doesn't reveal anything obvious that's wrong with the resulting Help Viewer content.

Thanks much in advance.

**Comment by EWSoftware** [comment]
It's only a problem if you override project properties from the command line or, as with the OP, rely on wildcard expansion to generate multiple file items.  Those changes won't be found.  Other than that, it'll work fine.

**Comment by kfertitta** [comment]
Great.  Thanks Eric

**Comment by JamesNK** [comment]
I'm also getting this issue.

**Comment by JamesNK** [comment]
Hi

When do you think this fix will be available?

**Comment by EWSoftware** [comment]
Probably in a few weeks whenever I get time to document the changes made and publish it.  The changes are in source control if you want to build it from the source.
