### ISSUE TITLE
Wildcards and <Image> do not work on VS2015 Update 1

### ISSUE THREAD

**Issue by damyanp** [EWSoftware/SHFB#209]
We have a project that uses this technique to include images in the documentation by wildcard:

    <WildcardImages Include="media\*.svg"/>
    <Image Include="@(WildcardImages)">
      <ImageId>%(Filename)</ImageId>
      <CopyToMedia>True</CopyToMedia>
    </Image>

This works fine on VS2015, but on VS2015 Update 1 this fails with:

    SHFB : error BE0065: BUILD FAILED: Could not find file 'C:\prj\sc\@(WildcardImages)'. 

It looks as if it is not evaluating the @(WildcardImages) on Update 1.  This exact same code works fine on VS2015.

A repro of this can be found at https://github.com/damyanp/SandCastleRepros

**Comment by damyanp** [comment]
@rainersigwald

**Comment by EWSoftware** [comment]
The image element was never intended to work that way nor are any of the other file elements.  The fact that it did is a fluke and isn't something I did anything to support.  One file per element is the intended usage.  I don't have any intention of supporting wildcards in that manner.

**Comment by sharwell** [comment]
@EWSoftware Everything in the example aside from the `<ImageId>%(Filename)</ImageId>` is standard MSBuild syntax (even the `ImageId` could be standard, but I haven't used it myself). If it's not working, it means a custom build task is making an incorrect assumption about the form of items within an MSBuild project. I would mark it as a :bug: and put it on the backlog (perhaps up for grabs). Also consider marking it blocked pending confirmation that it behaves this way in the final release of VS 2015 Update 1.

**Comment by EWSoftware** [comment]
@SHarwell: They are standard MSBuild constructs but they aren't supported if you load the project in Visual Studio.  This only works if you build directly with MSBuild outside of Visual Studio.  Like I said, it's not something I've coded for specifically so MSBuild is doing something when the project is loaded.  He has another issue with VS2015 Update 1 in which the executing project instance can't be retrieved.  It's possible once that's resolved this will be resolved too.  Item expansion and variable resolution is something that MSBuild has to do, it's not something I want to implement within the build engine.
