### ISSUE TITLE
inheritdoc not working?

### ISSUE THREAD

**Issue by bjoernNaef** [EWSoftware/SHFB#210]
I've tried to use the <inheritdoc />tag which to my knowledge should be supported without success. The documentation from the implemented interface, or from a .NET base class such as Object, won't be inherited. I've tried several syntactical variants of the tag, according to the documentation, such as using the "cref" attribute or the "search" attribute, but whatever I tried no documentation had been inherited. Is there a way to get this tag working?

**Comment by EWSoftware** [comment]
All you should need to do is put the `inheritdoc` tag on the interface member or overridden member and it should resolve it when the help file is built.  One thing to check is that your XML comments files are up to date and include the tag.  The build log will tell you what XML comments files it found and you can check them to be sure it's really there.  The Generate Inherited Documentation build step in the log will report any issues it finds so look there too.

**Comment by bjoernNaef** [comment]
Many thanks for your quick reply, Eric! It turned out to be a configuration issue on my side, the XML documentation file could not be accessed. Everything is fine now, thanks again.

Issue closed.
