### ISSUE TITLE
Help file (.chm) content is missing when moving the help file to other computer

### ISSUE THREAD

**Issue by arefworks** [EWSoftware/SHFB#211]
hello everyone...
I'm using Sandcastle help file builder. After building my help file as  (.chm)  file it works in my PC but  when i send the file to other PC location. the tree view is shown while the main content is missing (empty).
I hope if anyone can help me with that.
thanks

**Comment by EWSoftware** [comment]
From the FAQ:  [Why doesn't my help file load?](http://ewsoftware.github.io/SHFB/html/097c63eb-3ceb-4d5b-bbe4-1e55c56d39b7.htm#Help1NotLoading1)

In this case, it probably needs to be unblocked.

**Comment by simonmurdock** [comment]
Any time I send one of these it's invariably because it is blocked or being opened from a network location.
