### ISSUE TITLE
Problems using versioning

### ISSUE THREAD

**Issue by chrisbrokke** [EWSoftware/SHFB#212]
I have a sandcastle project in which I want to use versioning of the help file
The content folder has a VersionHistory folder with the files v1.0.0.0.aml, v1.1.0.0.aml and versionhistory.aml. V1.1.0.0 aml is a copy of v1.0.0.0.aml with the id guid changed.

VersionHistory has the following lines

``` XML
<section>
   <title>Version History</title>
      <content>
          <para>Select a version below to see a description of its changes.</para>
          <list class="bullet">
	<listItem><para><link xlink:href="b80ed9a5-6847-4aed-9e09-d6b9830c47cf" /></para></listItem>
	<listItem><para><link xlink:href="ef1dba5d-bb3b-4d27-9ccf-6f1ec8d1e793" /></para></listItem>
         </list>
      </content>
</section>
```

In the generated word document, the first item in the list is a link, and the second item is only the GUID of the referenced v1.1.0.0.aml file. I know that the v1.0.0.0.aml file was auto generated and the contents of this file show correctly in the help file.

Google hasn't been able to direct me on how to properly use versioning. Is there someone who can direct me in the right direction given the above information.

Thanks in advance 

Chris Brokke

**Comment by EWSoftware** [comment]
Did you add the new file to the content layout file?  If not it hasn't been included in the output.

**Comment by chrisbrokke** [comment]
Thanks. This was the simple thing I had overlooked. You taking the time to answer is really appreciated.
