### ISSUE TITLE
Generating hierarchical markdown folder structure 

### ISSUE THREAD

**Issue by simonmurdock** [EWSoftware/SHFB#214]
A lot of the tools used to generate API docs require the documents to be inserted into the relevant folders, by namespace for example. In my case mkdocs. But at the moment it appears that sandcastle generates a "flat" output, is it possible to get a structured output for markdown?

**Comment by EWSoftware** [comment]
No, not unless you want to rework the presentation style and/or write a plug-in to handle the new layout.

**Comment by simonmurdock** [comment]
Are there any plans to modernise sandcastle to the latest and greatest outside of community contributions? I'm trying to create documents as nice as http://elixir-lang.org/docs/stable/elixir/Kernel.html and https://code.visualstudio.com/docs/editor/extension-gallery

**Comment by EWSoftware** [comment]
There are no plans on my part.  Presentation styles do require quite a bit of work.  I can't keep up with all the different ways of presenting documentation and knowing what the community might want.  Also, web development isn't my thing so coming up with web-based presentation style layouts isn't something I care for at all.  Unless I'm feeling ambitious, alternate presentation styles are going to be left to the community to contribute.

**Comment by simonmurdock** [comment]
That's a shame. 

Fortunately I found the official tool used to generate the MSDN documentation.
