### ISSUE TITLE
vs2015 can't set as default

### ISSUE THREAD

**Issue by jrobb229** [EWSoftware/SHFB#216]
Two questions: 1) I try to set Open With Sandcastle Help File Builder Project Launcher as the default when I double click on the shfb project file in the Solution, but Set as Default option remains grayed out when that program is selected from the list , 2) is there a way to compile a shfb project in th VS IDE?

**Comment by EWSoftware** [comment]
it should have set the launcher as the default program associated with *.shfbproj* files when you installed SHFB.  As long as you installed the Visual Studio package using the guided installer or ran it manually, you can open SHFB project files within Visual Studio 2013 or later and build them.

If you haven't done so, I'd suggest running the guided installer as it will step you through all of the requirements and install the missing tools.

**Comment by jrobb229** [comment]
Thanks for your quick response and for the excellent SHFB you are maintaining (I sent you a small donation a while ago and should probably do so again.) I've been using SHFB for many years; I know of no other program as good. I downloaded the latest version (2015.10.10.0) of SHFB and ran the guided installer after uninstalling the previous version. I think I answered in the affirmative most if not all the choices during the install (e.g.; VS2015 installation, Spell checker - a great addition since my spelling is often not the best as I learned when your program looked at some of my files :-), and any other options that seemed appropriate for my situation.)

 

Several things I'm having problems with:

 

When I added my SHFB `project to my solution as a new project and tried to rebuild (release option) my solution something very unexpected (keeps life interesting) happened. All of the files in the root directory of my main project (a Windows Forms app), everything (forms, code files, the chm file, etc.), was unrecoverably deleted. Fortunately, over the years I've learned to backup frequently, I only lost a day or so work (and my application is nearly in its beta phase so much of the work done during that time was  to fix minor issues.) I can't figure out how it happened; I've could have inadvertently done something wrong although I've been using Visual Studio for years. Hence my question "can I compile an SHFB project in VS."

Also, when I try to run the SHFB project file (which I added to my solution after the SHFB project compile “event” and subsequent removal of the SHFB project from the solution) by right clicking on it, selecting "Open With" then selecting the SHFB Project Launcher from the a list in the dialog box which appears, I am able to open the SHFB GUI with the project file loaded (created previously in the standalone SHFB GUI), but I am not able to set the project launcher as the default program to open that SHFB project file (the option to do that remains greyed out in the dialog) as I did in previous versions of VS. Of course, I'm unable to figure out if it is a VS bug, something I've done wrong, or even a SHFB problem. You are probably better able to determine if others are having the same problem.

 

Finally, I'm uncomfortable with the verbosity of this reply, and ask for your indulgence as I try to find a resolution. I'm not sure how much background you need to help me solve my problem...

**Comment by EWSoftware** [comment]
Check the help output and working folder properties of your SHFB project.  If pointed at your other project's folder and you're building web or markdown output that would explain why everything got deleted.  SHFB contains safety checks to make sure you don't delete certain well known folder locations or the SHFB project folder itself.  However, if pointed at a folder outside the project folder or a subfolder beneath the project folder it will purge them without warning.

Regarding the project launcher, that's really only used by the shell (Windows Explorer).  If you're adding projects to a solution in Visual Studio, use the *Add New Project/Add Existing Project* options.  Don't add them as solution items.  Once added to the solution as a true project, you can maintain them from within Visual Studio just like any other project.  If you want to open them in the standalone GUI for some reason, you can right click on the project and select the *Open Project in Standalone GUI* option.

The [Visual Studio Integration Package](http://ewsoftware.github.io/SHFB/html/b128ad2a-787e-48c7-b946-f6953080c386.htm) for details on using the Visual Studio projects.

**Comment by jrobb229** [comment]
I think you’ve got it. I am putting output to the folder that got deleted. I’ll try to use the help  output folder and load the project again  into my solution (of course after I do another backup J.) 

I followed the link to the Visual Studio Integration Package and it was very helpful (I don’t how I misses that when I Googled the problem.)

Thanks for your quick response; do you ever take time off???

**Comment by jrobb229** [comment]
Well, I was able to get VS2025 SHFB project in the solution but then the problems began. The original SHFB project had been developed in a previous version of SHFB and I build a viable chm file from it. When I tried to update the MAML topic files in the VS IDE I began to get messages and warnings that prevented the SHFB project compiling. When I went back to the SHFB GUI I was able to successfully build the chm but then, after further modifying them in the VS IDE and choosing yes to reloading the modified files in the GUI I got the following message:

SHFB: Error BE0055: The conceptual topic 'Stress Reduction' (ID: 17cfa18c-bec1-4e4e-ba83-f5615e11f7b2) must either specify a topic file or it must contains sub-topics

   at SandcastleBuilder.Utils.ConceptualContent.TopicCollection.GenerateConceptualTopics(String folder, BuildProcess builder, IEnumerable`1 validNamespaces)

   at SandcastleBuilder.Utils.ConceptualContent.ConceptualContentSettings.CopyContentFiles(BuildProcess builder)

   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

yet the ContentLayout had a file with the same ID associated with the topic?

**Comment by EWSoftware** [comment]
Check your content layout file for a topic with that ID.  It's most likely just a place holder topic with no associated topic.  Associate the topic with that ID and all should be well.

**Comment by jrobb229** [comment]
Fixed (everything now works in both environments; whew). Pilot error; somehow had two contentlayout files. Thanks for your patience and time.

**Comment by jrobb229** [comment]
EW responded numerous times quickly and helpfully for a difficult situation that ultimately I, not SHFB, was responsible for. It is so nice to interact with an ethical and motivated developer...
