### ISSUE TITLE
Unknown reference link target 'T:Oracle.DataAccess.Client.OracleDataReader'

### ISSUE THREAD

**Issue by Mark-Boyer** [EWSoftware/SHFB#218]
BuildAssembler : warning : ResolveReferenceLinksComponent: [P:VaultKeeperUtilities.BatchConfig.ExceptionOracle] Unknown reference link target 'T:Oracle.DataAccess.Client.OracleException'. [C:\Users\boye007\Documents\Arvato\Work\Vault Keeper\VaultKeeper\VaultKeeperDocumentation\Help\Working\BuildReferenceTopics.proj]
BuildAssembler : warning : ResolveReferenceLinksComponent: [M:VaultKeeperUtilities.Oracle.GetBoolean(Oracle.DataAccess.Client.OracleDataReader,System.Int32)] Unknown reference link target 'T:Oracle.DataAccess.Client.OracleDataReader'. [C:\Users\boye007\Documents\Arvato\Work\Vault Keeper\VaultKeeper\VaultKeeperDocumentation\Help\Working\BuildReferenceTopics.proj]

how do i include the oracle odp so shfb can find the reference link target?

**Comment by EWSoftware** [comment]
Use the [Additional Reference Links plug-in](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm).  It probably won't resolve to anything on MSDN so set the link type for the subproject to None in the plug-in configuration.

**Comment by Mark-Boyer** [comment]
Eric,

Thanks for the response.  It does not matter if I point to the Hx files or the dll the plug-in does not know with to do with files.  The plug-in is looking for shfbproj files.

Within  the plug-in what file do I reference?


Severity

Code

Description

Project

File

Line

Error



Unexpected error while executing plug-in 'Additional Reference Links': Microsoft.Build.Exceptions.InvalidProjectFileException: The element <HelpTOC> is unrecognized, or not supported in this context.  C:\Program Files (x86)\Oracle Corporation\Oracle Data Provider for .NET Help\DataProviderHelp.HxT

VaultKeeperDocumentation

SHFB

0

**Comment by EWSoftware** [comment]
See the plug-in's help.  Create a SHFB project and add the Oracle assembly and XML comments file to it.  Add that project to the plug-in's configuration and set the link type to None.

**Comment by Mark-Boyer** [comment]
Eric,

Sorry for being a pain but where do I find odp xml comments file? What documentation sources do I list for the oracle odp only shfb project?

A little more detail would be appreciated, thanks,

Mark

Severity

Code

Description

Project

File

Line

Error



The project does not have any documentation sources defined

OracleODPDocumentation

SHFB

0

Error



Unexpected error while executing plug-in 'Additional Reference Links': SandcastleBuilder.Utils.BuilderException: Unable to build additional target project: C:\Users\boye007\Documents\Arvato\Work\Vault Keeper\VaultKeeper\OracleODPDocumentation\OracleODPDocumentation.shfbproj

VaultKeeperDocumentation

SHFB

0

**Comment by EWSoftware** [comment]
Add the ODP assembly as the documentation source.  I don't know where the XML comments file for it would be.  There might not be one.  It isn't required so just the assembly will do.

**Comment by Mark-Boyer** [comment]
Thanks.

I turned off the warnings in the ODP doc project and it looks like the warnings have been cleaned up.
