### ISSUE TITLE
BuildAssembler : error : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mozzis** [EWSoftware/SHFB#219]
"Sandcastle Help File Builder and Tools" version="2015.7.25.0"

My SHFB build fails in the BuildReferenceTopics phase with the error in the subject. More details are below. How do I find out what is causing this problem? The system we are documenting is a CLI/C++ dll, and the MSVC++ XML output is used as an input to the SHFB build.

BuildAssembler : error : Object reference not set to an instance of an object. [D:\code\Optonicus\WONAT\wonat\src\help\Help\Working\BuildReferenceTopics.proj]
  CopyFromIndexComponent: &quot;reflection&quot; in-memory cache entries used: 4 of 15.
  CopyFromIndexComponent: &quot;comments&quot; in-memory cache entries used: 7 of 30.
Done Building Project &quot;D:\code\Optonicus\WONAT\wonat\src\help\Help\Working\BuildReferenceTopics.proj&quot; (default targets) -- FAILED.

**Comment by EWSoftware** [comment]
Is there any call stack info shown in the log?  Can you try it with the latest release?  If that doesn't work, can you e-mail me an example?  My e-mail address is in the footer of the pages in the help file.

**Comment by mozzis** [comment]
No call stack. Output above what I quoted from the log is normal BuildAssemblerCore output. I just replicated the problem with the latest (2015.10.10.0) version.

I put the project on a OneDrive folder and will email you the link. Thanks for looking into this.

**Comment by EWSoftware** [comment]
The VB syntax generator isn't handling the assignment operators correctly.  I've fixed it for the next release.  You can turn off the VB syntax generator in the Syntax Filters property to work around the issue for the time being.

**Comment by mozzis** [comment]
Thank you for the prompt reply. I cleared the checkbox labeled “Syntax filters” in the “Help File” section of the project, and it got past the place where it crashed before (an in fact just finished as I was writing this.)
I had actually tried clearing the F# option there before but did not pursue that trial to other (presumably more frequently used) languages. Thanks again!
