### ISSUE TITLE
@Version value

### ISSUE THREAD

**Issue by oblaise** [EWSoftware/SHFB#220]
Dear All,

Playing with SHFB I found references to {@Version} which apprently relates to being {@Major}.{@Minor}.{@Build}.{@Revisoon} (Doc: Help File Category Properties) but didn't find a clue how these properties are being set.

KR

**Comment by EWSoftware** [comment]
See the project's [User Defined Properties](http://ewsoftware.github.io/SHFB/html/c4e3ce8e-6881-47a7-a429-49ec5c755c8c.htm) category.  They're probably defined there.
