### ISSUE TITLE
[2015.10.10.0] ResolveReferenceLinksComponent

### ISSUE THREAD

**Issue by nolme** [EWSoftware/SHFB#221]
Hi,
I have some warnings I can't remove. I think this is an issue.
The external code is from e-IceBlue Spire Office.NET

```
/// <summary>
        /// Set background image in sheet.
        /// </summary>
        /// <param name="workSheet">The sheet.</param>
        /// <param name="image">The image bitmap.</param>
        /// <exception cref="System.ArgumentNullException">Fired when null argument is passed to function.</exception>
        public static void ReplaceBackgroundImage(XlsWorksheet workSheet, Bitmap image)
        {
            if (workSheet == null) throw new ArgumentNullException(nameof(workSheet));
            if (image == null) OutputUtility.WriteLine("Replace image background : No bitmap (null)");

            //set the image to be background image of the worksheet
            workSheet.PageSetup.BackgoundImage = image;
        }
```

The warning message is : 
*Avertissement		BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Spire.Utilities.ExcelGeneratorUtility.ReplaceBackgroundImage(Spire.Xls.Core.Spreadsheet.XlsWorksheet,System.Drawing.Bitmap)] Unknown reference link target 'T:Spire.Xls.Core.Spreadsheet.XlsWorksheet'. [D:\Dev\DotNET\e-IceBlue\Documentation\Help\Working\BuildReferenceTopics.proj]	Documentation	C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets	40*

Thanks,
Vincent

**Comment by EWSoftware** [comment]
It's just missing reference information used to generate a link to a related help topic for a member in a reference assembly.  You can ignore them since in this case the topics don't exist.  If the warnings bother you, you can use the [Additional Reference Links plug-in](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm) to suppress them.
