### ISSUE TITLE
generated chm documentation not displayed and web documentation can not search

### ISSUE THREAD

**Issue by khacminh** [EWSoftware/SHFB#222]
I am using SHFB version 2015.10.10.0 to generate documentation for my project. 
1. When I generate web documentation, everything seems fine. However I cannot search any content, always "nothing found". 
2. When I generate chm documentation, I can open the file. All of my class, methods,... are listed, but when I choose any item, nothings is displayed, always blank.

**Comment by EWSoftware** [comment]
If built the help file locally on your hard drive, you should be able to view the CHM file content.  You've most likely got the help file located on a network folder or have copied it to a different PC.  You can either unblock the file or apply a registry fix to view it in those cases.  See the [FAQ topic](http://ewsoftware.github.io/SHFB/html/097c63eb-3ceb-4d5b-bbe4-1e55c56d39b7.htm#Help1NotLoading1) for information on how to do both.

As for the web output, it should be searchable.  However, if running from the local file system, it may be blocking the content.  If running from the development web server or an actual web server, you should be able to search and have it return results.  See the [SHFB Help content](http://ewsoftware.github.io/SHFB/search.html?SearchText=web%20search) as it is searchable.

You might try clearing your browser cache.  There was a bug in an older version of the script that caused search problems.  If that's still cached on your system it may be causing the problem.

**Comment by khacminh** [comment]
I got it. Thank you
