### ISSUE TITLE
Silent installation

### ISSUE THREAD

**Issue by pascalberger** [EWSoftware/SHFB#224]
I would like to package SHFB as a Chocolatey package for deployment. Is a silent installation of SHFB possible and what are the required switches?

**Comment by EWSoftware** [comment]
You should be able to use the /quiet or /qn option with msiexec to perform a silent install of the MSI.  The /quiet or /q option for the VSIX installer makes it do a quiet install.

This has come up before (#25).  My comments there would apply here too.

**Comment by qmfrederik** [comment]
Hi,

We maintain a Chocolatey package for SHFB. You can install it by typing the following command:

```
choco install -y sandcastle --version=2015.10.10.0`
```

The package source can be found [on GitHub](https://github.com/quamotion/chocolatey/tree/master/sandcastle).

Maintaining Sandcastle packages is not my core business; if anyone else wants to maintain the package, that's fine by me.

Frederik.

**Comment by pascalberger** [comment]
Thanks @qmfrederik! Will test it out
