### ISSUE TITLE
PlantUML support?

### ISSUE THREAD

**Issue by KarloX2** [EWSoftware/SHFB#226]
Hi!

Is there any existing tool that could automatically generate UML graphics from PlantUML text Syntax?

For example, it would be great to write PlantUML in MAML Topics and have SHFB call the graphics generator for it and embed the graphic in the Topic.

Thanks

**Comment by EWSoftware** [comment]
You can probably create a plug-in to handle it.  I'm not familiar with PlantUML so I can't say how you'd do that specifically.  However, you can take a look at the [latex component](https://github.com/EWSoftware/latex-sandcastle) that someone created to handle LaTex statements.  I only updated that fork to work with the latest release of SHFB so I can't provide support for it.

**Comment by KarloX2** [comment]
Ok, here's roughly what I want to create:

- find PlantUML snippets by embedding them in some special element, e.g.

/// <plantuml>
/// Bob->Alice : Are you there?
/// Alice->Bob : Yes!
/// </plantuml>

- Find such snippets both in the documentation that comes from c# Solutions as well as in MAML Topics.
- Start the subprocess that generates an .png Image or so from the text. This would be a sequence diagram in the above case.
- Place the Image in a paragraph instead of the original plantuml Syntax (without modifying the original file)

Do you think this can be done and is the Latex component a good pattern for this?

Thanks!!

**Comment by EWSoftware** [comment]
It should work since it follows a similar pattern.

**Comment by KarloX2** [comment]
Ok, I was able to implement what I needed. Thanks for your help !

**Comment by jbaehr** [comment]
would you mind sharing your plugin? It would make a great addition to SHFB
