### ISSUE TITLE
How can I add notes/warnings/etc to inline code XML docs?

### ISSUE THREAD

**Issue by jstedfast** [EWSoftware/SHFB#229]
When writing documentation in MAML, it's possible to use `<alert class="note">...</alert>`, but using alert in XML docs within the source code does not work.

What is the suggested way of doing this?

While I'm sure I could clone the HTML generated when using alert in MAML docs, is this the suggested way of doing it?

**Comment by EWSoftware** [comment]
See  the XML Comments Guide, specifically the [note](http://ewsoftware.github.io/XMLCommentsGuide/html/4302a60f-e4f4-4b8d-a451-5f453c4ebd46.htm) element.

**Comment by jstedfast** [comment]
D'oh, thanks. How'd I miss that? :)
