### ISSUE TITLE
UnauthorizedAccessException when VS2013 style is used

### ISSUE THREAD

**Issue by stefanov-stefan** [EWSoftware/SHFB#230]
I came to an issue when the VS2013 style is used. In my case in the WebTOC.xml I have couple entries that do not have URL specified
```
<HelpTOCNode Id="4a7d73ef-0c4e-422c-8f96-598c16130f6d" Title="T:MyNamespace">
<HelpTOCNode Id="c2c356b3-5258-4d76-8059-f53bb5f4f9c0" Title="Fields.T:MyNamespace">
<HelpTOCNode Title="F:MyNamespace.someFieldName" Url="" />
```

Not sure why this happens, but looking at the code that builds the WebTOC.xml it seems as a valid scenario if you already have a title with this key.

Not when the build executes the LightweightWebstiteStylePlugIn it has the following code: 
```
string path = Path.Combine(builder.WorkingFolder, @"Output\Website", current.Attribute("Url").Value);
string outputFile = File.ReadAllText(path, Encoding.UTF8);
```

Here is combines the working folder, with some subfolder and the contents of the URL attribute, expeting to reach a file and the to read its contents. As the URL is an empty string, such file does not exists, hence the UnauthorizedAccessException is being thrown.

I think that there might be an issue here and it could be protected, hence my report.

If more information is needed, please let me know.

**Comment by EWSoftware** [comment]
See [pull request 228](https://github.com/EWSoftware/SHFB/pull/228).  I think that covers this issue and fixes it.

**Comment by stefanov-stefan** [comment]
Yes, this should cover it. Thanks.
