### ISSUE TITLE
Error C:\SandcastleHelpFileBuilder.targes was not found

### ISSUE THREAD

**Issue by sapphire-9** [EWSoftware/SHFB#231]
This error appears after SHFB installation on a new machine and opening a solution containing SHFB project in it. I use latest version on SHFB 2015.10.10.0 with step by step guided installation with every option istalled (schemas,snipets etc.).

![shfb](https://cloud.githubusercontent.com/assets/9817513/11941810/42a72514-a843-11e5-8b9d-fb29771d9485.PNG)

**Comment by EWSoftware** [comment]
You probably just need to reboot so that the SHFBROOT environment variable takes effect.

**Comment by sapphire-9** [comment]
Thanks a lot! Everything is fine after reboot. May be it will be a good idea to ask user for reboot after SHFB installation

**Comment by EWSoftware** [comment]
There's a link on the final page of the guided installer that offers a reboot option if the SHFB installer ran.
