### ISSUE TITLE
Generic IEnumerable is not resolved correctly in implementation list

### ISSUE THREAD

**Issue by aluanhaddad** [EWSoftware/SHFB#234]
I am using version 2015.10.10.0, and my projects target .NET 4.6. I build my help file in the ```Website (HTML/ASP.NET)``` format.

I noticed an issue in the interface list portion of the type declaration generated for types deriving from the ```System.Collections.Generic.IEnumerable<T>``` interface. 
The output shows the type as deriving from the ```System.Collections.IEnumerable``` interface when it should show the ```System.Collections.Generic.IEnumerable<T>``` as well.

For example, we have an interface declared as: 
```C#
public interface IAggregateLexical<out TLexical> : ILexical, IEnumerable<TLexical> 
where TLexical : ILexical 
{ }
```
and the resulting output is:
```C#
public interface IAggregateLexical<out TLexical> : ILexical, IWeightable, IEnumerable
where TLexical : ILexical
```
while the expected output is:
```C#
public interface IAggregateLexical<out TLexical> : ILexical, IWeightable, 
IEnumerable<TLexical>, IEnumerable
where TLexical : ILexical
```

When I say the _expected output_, I am referring to the output produced by previous versions (within the last year but I do not know the specific version) of SHFB.

The msdn help topic link resolves to ```System.Collections.IEnumerable```.
The extension method list _does_ include methods from referenced assemblies which are only defined for values of type ```System.Collections.Generic.IEnumerable<T>```.
Properties, parameters and return values of methods are correctly resolved.

The link to the live help topic: http://lasi-project.org/apireference/html/83905019.htm
The link to the source file: https://github.com/lasiproject/LASI/blob/07a1f72fa97fd0fc627cb93ce0eb60a28e5f555b/LASI.Core/LexicalStructures/UnderpinningTypes/IAggregateLexical.cs

Thanks for creating and maintaining this awesome project.

**Update**

I noticed that other generic types were missing from type declarations. For example, a generic type with some type parameter ```T``` that implements ```IEquatable<T>``` does not list IEquatable<T> in its interface list.

**Comment by EWSoftware** [comment]
Using the classes by themselves or LASI.Core, I'm not able to duplicate this issue.  The syntax section contains the base classes expected.  Your project contains no SHFB project so I can't see what options you're using.

**Comment by aluanhaddad** [comment]
Thanks for investigating this.
