### ISSUE TITLE
System.Net.Primitives unresolved

### ISSUE THREAD

**Issue by gfkeogh** [EWSoftware/SHFB#237]
I have a portable library project in VS2015.1 targeting .NET Framework 4.5, ASP.NET Core 5.0 and Windows Phone Silverlight 8. Referencing and building a 15.10.10 help project produces this in the log:

`MRefBuilder : error : Unresolved assembly reference: System.Net.Requests (System.Net.Requests, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) required by RCS.Aggregate.WebApi.Portable [K:\webs\dochelp\rubyportable4\Working\GenerateRefInfo.proj]`

I spent almost an hour trying all sorts of tricks to find and reference the missing assembly, but everything failed to have any effect. Am I using an invalid combination, or trying something not supported? -- *Greg*

**Comment by EWSoftware** [comment]
I'll see if I can duplicate the problem.  In the meantime, you can use the Assembly Binding Redirection plug-in to ignore the missing System.Net.Requests reference.

**Comment by gfkeogh** [comment]
Thanks for hint there, I never noticed the Plug-ins > Assembly Binding Redirection > Ignore if Unresolved tab. Putting `System.Net.Primitives` and `System.Net.Requests` in the list lets it build okay. My portably library just full of POCOs, so the resulting help looks fine by me, with no ill effects from the ignores -- *Greg*

**Comment by EWSoftware** [comment]
Can you attach an example that duplicates this problem?
