### ISSUE TITLE
SHFB will not run

### ISSUE THREAD

**Issue by wesphillips** [EWSoftware/SHFB#24]
I installed SHFB and successfully used it a couple of times. then recently i went to use it again, and nothing seems to happen. When i check the Application event log, i see two(2) errors and one(1) informational messages from the attempted run. they are as follows:

Application: SandcastleBuilderGUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Configuration.ConfigurationErrorsException
Stack:
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at SandcastleBuilder.Gui.StartUp.Main(System.String[])

and

Faulting application name: SandcastleBuilderGUI.exe, version: 15.1.12.0, time stamp: 0x54c6b927
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54505737
Exception code: 0xe0434352
Fault offset: 0x0000000000008b9c
Faulting process id: 0xe6c0
Faulting application start time: 0x01d04ba569cd15da
Faulting application path: E:\Program Files (x86)\Sandcastle Help File Builder\SandcastleBuilderGUI.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: a7bb4518-b798-11e4-82ab-54271ebdfa15
Faulting package full name: 
Faulting package-relative application ID: 

and 

Fault bucket 94682567721, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: SandcastleBuilderGUI.exe
P2: 15.1.12.0
P3: 54c6b927
P4: System.Xml
P5: 4.0.30319.34209
P6: 53489a76
P7: 9bd
P8: 0
P9: IOIBMURHYNRXKW0ZXKYRVFN0BOYYUFOW
P10: 

Attached files:
C:\Users\Wesley\AppData\Local\Temp\WER2725.tmp.WERInternalMetadata.xml
C:\Users\Wesley\AppData\Local\Temp\WER291A.tmp.appcompat.txt
C:\Users\Wesley\AppData\Local\Temp\WER295A.tmp.dmp
C:\Users\Wesley\AppData\Local\Temp\WER29E7.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\Users\Wesley\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_SandcastleBuilde_b4f3b76ab4cc5f1eb3c2b9502447a307eed9bad_c276de63_c0ea29e4

Analysis symbol: 
Rechecking for solution: 0
Report Id: a7bb4518-b798-11e4-82ab-54271ebdfa15
Report Status: 4104
Hashed bucket: 9d31aeebfde6bb4a0f6cb4217bf633fe

I tried uninstalling and re-installing in a different location, but the problem persists. 

Any Ideas?

**Comment by EWSoftware** [comment]
Based on the exception I'd say the configuration file has gotten corrupted somehow.  If you go into the %LOCALAPPDATA% folder you should find an .\Eric_Woodruff folder.  Within that you should see some other folders starting with "SandcastleBuilderGUI".  Deleting those should get rid of the stored configurations.  Once you restart, it should recreate the configuration file using the defaults.

**Comment by wesphillips** [comment]
That was it. Thank you.

**Comment by wesphillips** [comment]
I think I found another issue. when you have a class with the same name as the namespace it is contained in, it does not get added to the output .chm file.


Wes






From: Eric Woodruff
Sent: ‎Wednesday‎, ‎February‎ ‎18‎, ‎2015 ‎2‎:‎57‎ ‎PM
To: EWSoftware/SHFB
Cc: Wesley Phillips





Based on the exception I'd say the configuration file has gotten corrupted somehow. If you go into the %LOCALAPPDATA% folder you should find an .\Eric_Woodruff folder. Within that you should see some other folders starting with "SandcastleBuilderGUI". Deleting those should get rid of the stored configurations. Once you restart, it should recreate the configuration file using the defaults.

**Comment by EWSoftware** [comment]
Make sure the class is declared public or protected.  If private or internal, it won't get included unless you enable the internal and/or private member options in the Visibility category.  Also, check to make sure it isn't being excluded by the API filter or an <exclude /> XML comments element.

**Comment by wesphillips** [comment]
The class is public and static. the same as many other classes that are not the same name as the namespace. the API filter says “An API filter has not been defined”. When I click on the “Edit API Filter” button, the aforementioned class is not even listed for me to include/exclude. I haven’t removed anything using an XML comments element.


Wes






From: Eric Woodruff
Sent: ‎Wednesday‎, ‎February‎ ‎18‎, ‎2015 ‎8‎:‎55‎ ‎PM
To: EWSoftware/SHFB
Cc: Wesley Phillips





Make sure the class is declared public or protected. If private or internal, it won't get included unless you enable the internal and/or private member options in the Visibility category. Also, check to make sure it isn't being excluded by the API filter or an XML comments element.
