### ISSUE TITLE
MergeContentFrom method in SandcastleBuilderUtils

### ISSUE THREAD

**Issue by BizH** [EWSoftware/SHFB#242]
A SHFB plug-in is calling MergeContentFrom in SandcastleBuilderUtils  and the build is choking because the method does not exist in 2015.10.10.0 anymore. What equivalent method should the plug-in be calling to resolve this? Or is there a way to retrofit this method into SHFB? Please point me in the right direction. Thanks in advance.

**Comment by EWSoftware** [comment]
Use the `ImageFiles`, `CodeSnippetsFiles`, `TokenFiles`, `ContentLayoutFiles`, and/or `Topics` properties on the build engine instance's `ConceptualContent` property to add additional conceptual content files to the build.

**Comment by BizH** [comment]
So, I do something like this?


			foreach(ImageReference ir in project.ImagesReferences)
			{
				buildprocess.ConceptualContent.ImageFiles.Add(ir);
			}

[Sorry for the dump question,  but] How do I get CodeSnippetsFiles, Token files, etc. from the project object? Can't seem to find a collection of those. Are they FileItems?

**Comment by EWSoftware** [comment]
They are file items so you can probably use the project.FileItems property to enumerate them all and pick out or group what you need by item.BuildAction.

**Comment by BizH** [comment]
Thanks Eric! That helped.
