### ISSUE TITLE
Direct links to topics in legacy style do not navigate to the topic

### ISSUE THREAD

**Issue by tylerohlsen** [EWSoftware/SHFB#243]
I'm not able to get the direct links to work when building with a legacy style.

**Repro Steps**
1. Target a legacy style and build the html help. 
2. Open the built index.htm / aspx and select a deep topic.
3. Select the "direct link" link in the top of the left frame.
4. Copy the link from the popup window.
5. Close all browser windows.
6. Open a fresh browser window and paste the link.

_Expected Result_
- The left table of context frame will select the deep topic from step 2
- The right frame will display the contents of the topic from step 2

_Actual Result_
- The left table of contents frame has all topics collapsed
- The right frame displays the main welcome page

**Comment by tylerohlsen** [comment]
This looks like an error in the regular expression in the [TOC.js](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/PresentationStyles/LegacyWeb/TOC.js#L99).  The link has a guid with dashes in it and the regex does not include the dashes.

I can make this change and submit a pull request.

**Comment by EWSoftware** [comment]
Merged change from pull request.
