### ISSUE TITLE
Change case of Index.html to all lowercase

### ISSUE THREAD

**Issue by atifaziz** [EWSoftware/SHFB#245]
When generating web site output, the root file is named `Index.html`. Consider using all lower cases instead, as in, `index.html`. This will make it readily to deployable to a web server that's using case-sensitive file system and won't server `Index.html`. One such prime example is GitHub Pages. It avoids an extra step for everyone in their build scripts to rename the file (and which then appears in a source control system like Git as a rename/change that needs undoing).

**Comment by EWSoftware** [comment]
Are you perhaps using an older version of SHFB?  The casing on index.html was fixed a long time ago.

**Comment by atifaziz** [comment]
@EWSoftware I'm quite certain I had tried with version 1.9, which is what I had initially, and the latest and observed no change in the file name casing before reporting this issue. However, now I uninstalled the previous SHFB version, re-installed the new, did `git clean` and re-tried and the case of `index.html` is indeed all lower case. Sorry for the noise.
