### ISSUE TITLE
Unable to build using mono xbuild on ubuntu travis machine

### ISSUE THREAD

**Issue by vivsriaus** [EWSoftware/SHFB#248]
Hello,

I have a travis CI workflow setup to build a sandcastle project. When running xbuild, I get the error given below. Can somebody help?

Below is the system info used:
Ubuntu 14.04.3 LTS

$ xbuild SandcastleARM.shfbproj
XBuild Engine Version 12.0
Mono, Version 4.0.5.0
Copyright (C) 2005-2013 Various Mono authors
Build started 2/2/2016 10:41:37 PM.
__________________________________________________
Project "/home/travis/build/vivsriaus/ARMDoc/sdk/dotnet/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/bin/Debug/dnxcore50/SandcastleARM.shfbproj" (default target(s)):
	Target CoreBuildHelp:
SHFB:  warning BHT0001: Unable to get executing project:  Unable to obtain matching project from the global collection.  The specified project will be loaded but command line property overrides will be ignored.
SHFB: error BHT0002: Unable to build project '/home/travis/build/vivsriaus/ARMDoc/sdk/dotnet/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/bin/Debug/dnxcore50/SandcastleARM.shfbproj': System.NotImplementedException: The requested feature is not implemented.
  at Microsoft.Build.Evaluation.Project.SetGlobalProperty (System.String name, System.String escapedValue) [0x00000] in <filename unknown>:0 
  at SandcastleBuilder.Utils.MSBuild.BuildHelp.Execute () [0x00000] in <filename unknown>:0 
	Task "SandcastleBuilder.Utils.MSBuild.BuildHelp" execution -- FAILED
	Done building target "CoreBuildHelp" in project "/home/travis/build/vivsriaus/ARMDoc/sdk/dotnet/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/bin/Debug/dnxcore50/SandcastleARM.shfbproj".-- FAILED
Done building project "/home/travis/build/vivsriaus/ARMDoc/sdk/dotnet/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/bin/Debug/dnxcore50/SandcastleARM.shfbproj".-- FAILED
Build FAILED.
Warnings:
/home/travis/build/vivsriaus/ARMDoc/sdk/dotnet/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/bin/Debug/dnxcore50/SandcastleARM.shfbproj (default targets) ->
/home/travis/SandcastleHelpFileBuilder/SandcastleHelpFileBuilder.targets (CoreBuildHelp target) ->
	SHFB:  warning BHT0001: Unable to get executing project:  Unable to obtain matching project from the global collection.  The specified project will be loaded but command line property overrides will be ignored.
Errors:
/home/travis/build/vivsriaus/ARMDoc/sdk/dotnet/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/bin/Debug/dnxcore50/SandcastleARM.shfbproj (default targets) ->
/home/travis/SandcastleHelpFileBuilder/SandcastleHelpFileBuilder.targets (CoreBuildHelp target) ->
	SHFB: error BHT0002: Unable to build project '/home/travis/build/vivsriaus/ARMDoc/sdk/dotnet/src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/bin/Debug/dnxcore50/SandcastleARM.shfbproj': System.NotImplementedException: The requested feature is not implemented.
  at Microsoft.Build.Evaluation.Project.SetGlobalProperty (System.String name, System.String escapedValue) [0x00000] in <filename unknown>:0 
  at SandcastleBuilder.Utils.MSBuild.BuildHelp.Execute () [0x00000] in <filename unknown>:0 
	 1 Warning(s)
	 1 Error(s)
Time Elapsed 00:00:01.7070770

**Comment by EWSoftware** [comment]
SHFB will work with MSBuild 12 and earlier without issue.  There's currently an issue with MSBuild 14 that will be fixed in the next release (issue #208).  I don't know what XBuild is.  If it's a port of MSBuild it should work as long as it hasn't changed how things work internally since the SHFB task does use reflection to get the details for the executing project.

If it's based on MSBuild 14, the issue may be resolved with the above noted fix.  That said, this isn't something I can officially support since I don't use Ubuntu or Mono.  The Windows platform and standard MSBuild tools are all I can guarantee it with and fix it if there's an issue.
