### ISSUE TITLE
MS Help Index

### ISSUE THREAD

**Issue by renig** [EWSoftware/SHFB#249]
I have two classes in a library both containing a method of the same name. When the help file is installed and I use F1 to access the context sensitive help it will always redirect to the method in the class that is first alphabetically.

E.g. If I click F1 on BTestClass.TestMethod it will open the help for ATestClass.TestMethod.

Is this a known issue?

**Comment by EWSoftware** [comment]
The keywords types generated appear to match what's in the standard framework help topics.  If you can find a similar case in the framework classes you can use that to test it and see what happens.  If the same thing happens, it's a problem with the viewer.  If not, the structure of the keywords in the affected topics could be compared to see how they differ from those generated by SHFB to see if there are differences that may be causing the issue.
