### ISSUE TITLE
Please create package for chocolatey.org

### ISSUE THREAD

**Issue by asd-and-Rizzo** [EWSoftware/SHFB#25]

**Comment by EWSoftware** [comment]
A NuGet package is available for minimal installs within a project with notable limitations.  There isn't one for the current release but I plan on adding support for it back in a later release once the framework data can be distributed separately to overcome the size limitations of the package.

For full installs, there are a number of requirements that I doubt would make this workable.  For one thing, I can't distribute the Help 1 compiler which is need for Help 1 files and isn't always there on end user systems.  The guided installer exists to make sure everything is installed properly and that you are aware of the additional tools that may be needed.
