### ISSUE TITLE
How to add hyperlinks to non-MSDN Microsoft Types using Visual Studio 2015 SHFB project 

### ISSUE THREAD

**Issue by dkemlage** [EWSoftware/SHFB#250]
Hello Eric,

I am using Visual Studio 2015 w/update 1 and the SandCastle Help File Builder version 2015.10.10.0 tools to generate Library Reference API pages.

I need to generate API docs that are based upon both .Microsoft NET Framework Assemblies and Xamarin Assemblies. I have been able to successfully build the API pages. Now, I am doing the fine tuning and it is desired to have hyperlinks appear in the SandCastle generated API pages that link to the Xamarin Types on their web site. Currently, any Xamarin Types that are encountered are just **BOLDED** and there is no hyperlink to their Types like those that are automatically generated for Microsoft MSDN Types.

To build the API docs, I add the required Xamarin .NET based .dlls into the SandCastle project as 'Documentation Sources'. Then, I go into the VS Project menu > [SandCastleProjectName] Properties menu item > Visibility tab > Edit API Filter button and turn off all the Namespaces except for the Assembly that we build and need to document. <-- I realize that I could have just added the dependency .dlls as Refeences but you get more control by being able to turn off specific things - but I digress...

Does the SHFB have some mechanism built in (Component, Plug-In, or other means) where you supply a table/XML file/etc. that contains (1) a non-MSDN Types and (2) their corresponding web hyperlink, so that these hyperlinks can get generated as part of the build process? 

I was thinking of a table something like:

TYPE,HYPERLINK
"View","https://developer.xamarin.com/api/type/Xamarin.Forms.View/"
"VisualElement","https://developer.xamarin.com/api/type/Xamarin.Forms.VisualElement/"
"Element","https://developer.xamarin.com/api/type/Xamarin.Forms.Element/" 
"BindableObject","https://developer.xamarin.com/api/type/Xamarin.Forms.BindableObject/"

Here is a visual representation of the problem we are facing:
![linkstononmicrosofttypes](https://cloud.githubusercontent.com/assets/5495810/12858774/fa15271e-cc06-11e5-9f1f-2b0a09808f75.png)

I tried scouring the SandCastle online documentation (http://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm) but could not figure out how to make this happen.

Thanks for any guidance you could provide.
-Don

**Comment by EWSoftware** [comment]
Only add assemblies/project that you want included in the documentation as documentation sources.  Anything else such as reference assemblies should be left out.  You can only add clickable links for external types that can be found on MSDN.  If the Xamarin types aren't there, you won't be able to do it.

If they are, use the [Additional Reference Links] plug-in to generate the necessary information for them.  You'll create a separate SHFB project for the required assemblies and add them to that.  Add that project to the plug-in's configuration and set the link type to MSDN.  That should then allow the build to generate the necessary links to the MSDN content.

If they are not on MSDN, you can still use the plug-in but only to suppress the warnings by setting the link type to None.

**Comment by dkemlage** [comment]
Probably not the most elegant solution, but I did a post process that iterated through all of the SandCastle generated Type .htm pages, looking for specific strings and replacing them with hyperlinks to web pages for that Type. Thank goodness that SandCastle prefaces all unknown Types with `<span class="nolink">UNKNOWN_TYPE</span>`

Example:
`FIND: <span class="nolink">BindableObject</span>
REPLACE: <a href="https://developer.xamarin.com/api/type/Xamarin.Forms.BindableObject/" target="_blank">Xamarin.Forms.BindableObject</a>`
