### ISSUE TITLE
External link

### ISSUE THREAD

**Issue by NicolasSandCastle** [EWSoftware/SHFB#251]
Hello everyone,

I am trying to add an external link. I read this.
https://ewsoftware.github.io/MAMLGuide/html/d0c9ce6d-115b-4c70-891c-69b4af944dea.htm

There must be something missing. My simple external link is:

![code](https://cloud.githubusercontent.com/assets/16655729/12985929/d889c562-d0c2-11e5-84e9-94c0cb9ce3db.png)

And the result is:
![remarks](https://cloud.githubusercontent.com/assets/16655729/12985942/e6277e9e-d0c2-11e5-8478-502d040ea416.png)

What's wrong?

Best regards,

Nicolas

**Comment by EWSoftware** [comment]
MAML elements such as `externalLink` are used in conceptual content.  They don't work in XML comments.  See the [XML Comments Guide](http://ewsoftware.github.io/XMLCommentsGuide/html/4268757F-CE8D-4E6D-8502-4F7F2E22DDA3.htm) for a list of supported XML comments elements.

In this particular case, for an external link, just use a normal HTML anchor element:

``` XML
/// See <a href="http://www.google.com">Google</a>
```

**Comment by NicolasSandCastle** [comment]
Hello Eric,

Sorry for the delay. Thank you very much for your answer.

Token files are conceptual content. So if I use the default token "SHFB" :

![shfb token](https://cloud.githubusercontent.com/assets/16655729/13088563/bc0ff4f0-d4ba-11e5-9563-9b3527fd38c2.jpg)

With the following code :

![code](https://cloud.githubusercontent.com/assets/16655729/13088616/f1a4e5e4-d4ba-11e5-8b4d-7fe754358630.jpg)

There is no link displayed in the result. Can you tell me why?

![remarks](https://cloud.githubusercontent.com/assets/16655729/13088627/fd5c6678-d4ba-11e5-84f6-1e540810e172.jpg)

Best regards,

**Comment by EWSoftware** [comment]
I guess it should be more clearly stated in the build component's help topic.  It will let you use the MAML token element but the content is restricted to valid XML comments elements.  None of the MAML templates are processed as part of the API build.  This build component was merely a means of accomplishing a similar task in XML comments.

If you want a link in the token, use the normal anchor tag as shown above.

**Comment by NicolasSandCastle** [comment]
OK I understand. 

Thank you for your answer once again. I deeply appreciate your support. Sandcastle is really a wonderfull tool.

The issue is now truly "Closed".
