### ISSUE TITLE
Class members order

### ISSUE THREAD

**Issue by petrdecky** [EWSoftware/SHFB#253]
I've noticed, that reflection.org file contains class mebers in the same order, as declared in source files (probably in the same order as returned by reflection methods). Is it possible to keep that order in reflection.xml file, which I assume is a primary source for help pages (xsl transformations)? Thank you for response.

**Comment by EWSoftware** [comment]
You can search the shared XSL transformations that produce the TOC etc. and the ones in the presentation styles for places where it sorts the content and remove the sort.  However, I doubt there's any guarantee that the members will remain in any particular order.

**Comment by petrdecky** [comment]
Thank you for a hint, it took some time to find a way, but I've finally succeeded, members are now it the same order as in source files. Thanks a lot.

If anyone needs this feature, I've attached modified transformation file. Just replace the file in ProductionTransforms folder. It produces reflection.xml intermediate file with members in the same order as in source files. Last thing you have to do is to alter ordering in presentation style (look for p_sort parameter in utilities_reference.xml transformation).

[ApplyVSDocModel.zip](https://github.com/EWSoftware/SHFB/files/139559/ApplyVSDocModel.zip)
