### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by stomicic** [EWSoftware/SHFB#256]
Hi,
I got a task to clean our Sandcastle project from warnings. Currently we have almost 200 warnings, but there are only 3 different types of warnings that repeats.
After long investigation I believe that none of those are caused by our code. Anyway, need help to resolve them.

**Warning 1 - MSDN URL not found for target 'T:System.Windows.Input.Mouse.PreviewMouseDown'**

`Warning		BuildAssembler : warning : ResolveReferenceLinksComponent: [Methods.T:Company.DataMasking.Activities.Design.Database.DBConnectionScopeDesigner] MSDN URL not found for target 'T:System.Windows.Input.Mouse.PreviewMouseDown'. [D:\...\Working\BuildReferenceTopics.proj]	DataMasking.Help	C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets	`

We have some designer classes, which have parent classes that implements PreviewMouseDown event. This event does not even mention in our code, so it must come in through the reflection. I believe that the error here is the fact the type is marked as T:System.Windows.Input.Mouse.PreviewMouseDown. However, PreviewMouseDown is an event end should have prefix E.

**Warning 2 - Duplicte entries for the key 'N:XamlGeneratedNamespace'**

Again, we do not reference directly this namespace. Getting same error for 'T:XamlGeneratedNamespace.GeneratedInternalTypeHelper' and 'M:XamlGeneratedNamespace.GeneratedInternalTypeHelper.#ctor'

`Warning		BuildAssembler : warning : CopyFromIndexComponent: Entries for the key 'N:XamlGeneratedNamespace' occur in both 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework\XamlGeneratedNamespace.xml' and 'D:\...\Working\reflection.xml'. The last entry will be used. [D:\...\Working\BuildReferenceTopics.proj]	DataMasking.Help	C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.target
`

**Warning 3 - MSDN URL not found for target 'T:System.Data.Object.ObjectContext'**

`Warning		BuildAssembler : warning : ResolveReferenceLinksComponent: [fbe3c1c8-419b-4a83-ad19-06b045f90c07] MSDN URL not found for target 'T:System.Data.Object.ObjectContext'. [D:\...\Working\BuildConceptualTopics.proj]	DataMasking.Help	C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets`

Other classes from same namespace are not reported as warning... 

Any advice would be appreciated.
Kind regards,
Sasa

**Comment by EWSoftware** [comment]
If you're not running the latest release, I'd suggest upgrading to it.

XamlGeneratedNamespace is an autogenerated namespace when you have XAML elements in the assemblies.  You can use the API filter or Namespace Summaries option to mark it as one to exclude.

For the others, I'd suggest deleting the MSDN URL cache and rebuilding the project.  It could be that there are bad entries in the cache.  You can find the cache folder in `%LOCALAPPDATA%\EWSoftware\Sandcastle Help File Builder\Cache`.  Just delete everything in that folder.

The first build after deleting the cache will be slow as it will have to look up all the IDs again.  If all goes well, it should suppress the warnings about the missing framework IDs.

**Comment by stomicic** [comment]
Hi,

have latest release. Tried to delete cache, no result. Where can I set the API filter?

**Comment by EWSoftware** [comment]
Namespace summaries can be set in the Summaries category (click the Edit Namespace Summaries button).  The API filter can be found in the Visibility category (click the API Filter) button.  In either one, uncheck the XamlGeneratedNamespace entry.

If you can supply a couple of samples that cause the above noted warnings, I can check it out.  They should be resolving without issue.

**Comment by stomicic** [comment]
Hi,

using your tips I resolved the XamlGeneratedNamespace warning.

However, I was unable to fix the other two issues. Tried all supposed and a lot of other possible solutions.
Therefore I created the sample solution (VS 2015) in which I reproduced both warnings.
My target is clean build with no warnings.

Thanks for your assistance!

[DemoDll.zip](https://github.com/EWSoftware/SHFB/files/142568/DemoDll.zip)

**Comment by EWSoftware** [comment]
The Object context one is caused by an incorrect namespace in the MAML file.  The correct ID is `T:System.Data.Objects.ObjectContext` (add an "s" to "Object").  If in doubt about an ID in a `codeEntityReference` element, you can search for it and drag and drop it from the [Entity References](http://ewsoftware.github.io/SHFB/html/e49eea91-a9ef-4aa5-ad8f-16ebd61b798a.htm) tool window.

The `T:System.Windows.Input.Mouse.PreviewMouseDown` warnings are caused by an incorrect ID in the framework XML comments file.  Microsoft got it wrong so there isn't anything that you can do to fix it unless you edit the offending XML comments file in the Reference Assemblies folder (*C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Activities.Presentation.xml*).  If there aren't that many warnings for it, you could just ignore them.

**Comment by stomicic** [comment]
Manage to fix both issues... thanks for assistance!
