### ISSUE TITLE
Web help TOC problem

### ISSUE THREAD

**Issue by gembox-marko** [EWSoftware/SHFB#257]
We are using SHFB for building file and web help. Our help has some additional content. Menu in CHM file works normally, but on our web it gets all messed up when you select something from the 'Class Library' section. You can see it [here](http://www.gemboxsoftware.com/spreadsheet/help/html/T_GemBox_Spreadsheet_CellStyle.htm). Order is completely wrong, and additional content is copied multiple times, but if you click on any topic outside 'Class Library', everything is ok.

We are currently using version 2014.11.22.0, but the problem still exist with the newest version (2015.10.10.0).

Any ideas why this is happening?

**Comment by EWSoftware** [comment]
Your Technical Support page redirects to a page outside the website.  Is it perhaps a raw HTML file that you've included in the content layout file?  If so, that may account for the odd behavior since only MAML topics which generate the expected content are supported in the website output.

If that isn't causing the problem, can you attach an example here or send me one that I can build that duplicates the issue?

**Comment by gembox-marko** [comment]
There are no raw HTML files in the content layout. Help web site is composed with SHFB using only AML files and some of them contain links to external pages (<externalLink>). Strange menu behavior is visible when you run web help locally, by opening index.html file. I will look into sending you an example ...

**Comment by gembox-marko** [comment]
Hi,

we managed to identify the issue and it was our fault.

We decided to make some modifications to branding-Website.js. One of the modifications was adding 'ExpandRootToc' function which looks like this:
```
function ExpandRootToc()
{
	var rootA = $("#tocNav > div[data-toclevel='0'] > a[class='tocCollapsed']").get();
	for(var i=0;i<rootA.length;i++)
		Toggle(rootA[i]);
}
```
and calling it at the end of 'InitializeToc' function.

We had a bug in our 'ExpandRootToc' function, but we fixed it now and you can observe how TOC looks like now, for example, by going to our help page http://www.gemboxsoftware.com/Document/help/html/M_GemBox_Document_DocumentModel_Load_1.htm

Perhaps you decide to incorporate this into the future version of SHFB.

Thank you for your time and keep up the good work!
