### ISSUE TITLE
Sandcastle: Use multiple libraries documentation on different topics in single sandcastle project 

### ISSUE THREAD

**Issue by ramiz272** [EWSoftware/SHFB#258]
Suppose I have two ClassLibrary projects i.e. "ClassLibrary1" and  "ClassLibrary2", and I have referenced the csproj files in Documentation Source of Sandcastle project inside visual studio. Now I would like to know if I can have two different API Reference topic nodes in two different location of ContentLayout.content tree then how can I refer (API Content = Insert as child of this topic) for both topic nodes separately. It should be mapped as below

topic=> API Reference 1 => ClassLibrary1 (API documentation)

topic=> API Reference 2 => ClassLibrary2 (API documentation)

**Comment by EWSoftware** [comment]
That isn't possible with SHFB by default.  However, you could look into writing a plug-in that would rearrange the intermediate TOC file during the build before the help output is generated.

**Comment by ramiz272** [comment]
Alright, please tell me is it possible that i create two separate sandcastle projects i.e. Documentation1 and Documentation2 having documentation source as classlibrary1 and classlibrary2 respectively, then can I add the Additional Reference Links Plug-In in Documentation1 project for Documentation2 project. will it concatenate the two help files into a single one?

**Comment by EWSoftware** [comment]
That will only work if you're planning on installing both in MS Help Viewer.  For the other help formats, it won't have any effect since you can't merge their content into a single collection.

**Comment by ramiz272** [comment]
Ok, thanks!
please tell me how can I open an external chm file from within my .aml file reference link? Does sandcastle support this opening another chm file from by linking its physical path or something?

**Comment by EWSoftware** [comment]
As I recall, an external link will work but you have to specify the fully qualified `file://` URL using the location of the external help file (no relative paths).  Unless you know where it's at that may not be feasible.  You may also run into security issues.
