### ISSUE TITLE
Save API filter/pattern with project?

### ISSUE THREAD

**Issue by c-stauffer** [EWSoftware/SHFB#259]
Currently using SHFB against a fairly large solution (30+ projects) and have added the solution file itself as the Documentation Source, so that when we make any changes or additions to the solution, we can choose to rebuild the documentation and pull all of that in.

These projects are all WCF services, and we would only like to include interfaces decorated with `[ServiceContract]` and classes decorated with `[DataContract]` in the documentation. 

Right now, whenever we want to regenerate the documentation, we have to go into the API Filter and manually select just these contracts for inclusion. Is there a way to specify, in the shfbproj (or perhaps elsewhere?), such that the documentation only includes the above elements automatically each time we rebuild the documentation?

**Comment by EWSoftware** [comment]
The API filter is saved in the project.  However, it won't automatically update to include or exclude new types/methods added to the code.  It's possible that you could create a plug-in that would manually search the documented assemblies for types decorated with the attributes that you want and then manually build the API filter settings and replace them in the MRefBuilder configuration file.
