### ISSUE TITLE
Add support for `ReadMe.md` as an alternative for `NamespaceDoc.cs`.

### ISSUE THREAD

**Issue by jgauffin** [EWSoftware/SHFB#260]
I use `ReadMe.md` in my github projects to document folders/namespace. It would be great if SHFB could use that file instead of `NamespaceDoc.cs`.

imho the readme is much more readable when browsing/reading the code.

**Comment by EWSoftware** [comment]
The problem here is that a ReadMe.md file cannot be matched to namespaces.  You might just as well add a MAML topic describing the content or use the built-in Namespace Summaries option.

**Comment by jgauffin** [comment]
How so? In most cases you use a `csproj` or a `sln` to generate the docs, right? Isn't it easy to use something like `Path.GetDirectoryName(projectItem.FullPath)` to get the directory and then check if there is a `ReadMe.md` in that folder? 

Someone using Markdown probably understand the implications of doing so (and are OK with that).

**Comment by EWSoftware** [comment]
The point is that the ReadMe.md has to be merged into the help file somehow.  Markdown isn't a format that's usable in anything but the markdown format.  Even then, it's just a single file and you wouldn't be able to extract namespace specific comments from it without first parsing it which implies it's in a specific layout.  If it's just a single topic you want merged, then just add a conceptual topic.  For all other formats, you'd have to convert it from markdown into HTML/Open XML depending on the format or to the intermediate MAML format first to merge it into the help file.  I'm not seeing any benefit here.
