### ISSUE TITLE
Override Assemblies location path in reflection data set 

### ISSUE THREAD

**Issue by amrmahdi** [EWSoftware/SHFB#262]
Currently the assemblies location path in reflection data set is set to a fixed path, for example for .NetFramework 4.6 it is set to %ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6. I need a way to be able to override the location as in our build servers the assemblies references are stored in a different folder structure.

**Comment by EWSoftware** [comment]
Create a copy, change the path, and put it along with the reflection data files in a folder under your project folder.  You can also put them in some other common location and set the project's component path to that folder.  If found in the project folder or the component path location it will override the default version found in the standard location.
