### ISSUE TITLE
DPI

### ISSUE THREAD

**Issue by LarryC42** [EWSoftware/SHFB#263]
I use a surface book.  When SandCastle initially opened it looked great.  I hit Build and bam everything shrunk to tiny fonts.

The Surface book runs 3000x2000 @ 200 dpi.

**Comment by EWSoftware** [comment]
If you're referring to the build output window in the standalone GUI, you can use the **File | User Preferences** option to change the font.  None of the other UI fonts should be affected by the build.

**Comment by LarryC42** [comment]
Here's an un-edited Alt+PrtScrn.

http://www.cur-ion.net/sc/SandCastle.png

What you're seeing is likely twice the size of what I see on a 13" 3000x2000 monitor.

**Comment by LarryC42** [comment]
One thing that was interesting is the font in File | User Preferences defaulted to 4 pt courier.  Changing that did make the build output usable.  I also changed the Editor font from 4pt courier to 12pt.  Clicking around seems to change some of the metrics but not all of them.  Here's the build page:
http://www.cur-ion.net/sc/Build.png

**Comment by LarryC42** [comment]
Here's what Build looks like when I first start the app.  You'll notice the difference between these.  

http://www.cur-ion.net/Build-Initial.png

While the image might look semi-good on your screen, when I set the zoom to 50%, it's looks exactly like what I see on my screen.

**Comment by LarryC42** [comment]
Setting my display to 1920 x 1200 @ 100% dpi makes the app launch ginormous.  I can shrink the window down and it looks like a normal app.

**Comment by LarryC42** [comment]
I've found that if after I open the program, I drag one of the docked windows around, everything will disappear when I drop it.  If I Shift+Click and choose Move, tap an arrow key, and then move my mouse, the main window will snap to my cursor.  The main window will have normal text now.  To get the docked portion back, I click on the tool bar icon, press Alt+Space, select Move, tap an arrow key, and move the mouse.  The undocked window will snap to the cursor.  I can then double click on the title bar to redock it.  It tends to dock at double the font size.  App seems to be much more usable after doing this.  Hope it helps someone else.  I think the issue may be WinForms not supporting DPI awareness well, there seem to be a lot of posts on it.

**Comment by EWSoftware** [comment]
This isn't something I can test or attempt to fix since I don't have a surface book.

**Comment by LarryC42** [comment]
It should be fairly easy to test.  Just crank up your DPI to 200% and launch.  It will have the downside of making your screen seem small, but just compare the launched app with any other app (say notepad).  You should notice that SandCastle appears unchanged while the UI in notepad is twice as large.

If you want a view of what it would realistically look like, drop pictures of them both into something like Paint.Net and shrink them 50%.

On Windows 10 the setting is in All Settings, System, Display.  Win 7 and before it's in control panel I think under display.

There appear to be solutions for it out there for WinForms but non of them look minor.  I do have the work around noted about that seems to be working well.

**Comment by EWSoftware** [comment]
There is a new DPI setting in the shortcut properties.  Right click on the shortcut you use to start SHFB, select Properties, select Compatibility, and then check "Disable display scaling on high DPI settings".  Then start SHFB using it.  That fixes a number of scaling issues in various applications.  I had to do that for a few when I installed Windows 10.  That may correct the issue for SHFB on your system.

**Comment by LarryC42** [comment]
It helps initially.  The fonts are a bit larger than they should be and the bottoms are cut off.  The work around above seems to be working a bit better so I'll stick with it even though it's a bit more work each time the app is launched.  Thanks for taking time with this.
