### ISSUE TITLE
Contents in Help viewer 2015 is blank

### ISSUE THREAD

**Issue by cbloc** [EWSoftware/SHFB#265]
Hi,

First, the Help Viewer 2.2 is Empty after my help online is generated with sandcastle.
However, the web site is generated correctly. 
helpviewer content 2.x = VisualStudio14

Second, i have a script error in MS help viewer 2.1. Onload('cs') or AddLanguagesetText.
But the website is correct. I don't understand why the production isn't constant in .mshc and .msha?

**Comment by MikeTheFid** [comment]
Do you mean "AddLanguageSpecificTextSet"? 

I think I just reported the same problem: see #266

**Comment by EWSoftware** [comment]
@MikeTheFid : This issue is related to MS Help Viewer not Help 1.

@cbloc: MS Help Viewer and website output are two totally different things.  Why you're getting errors in help viewer I don't know.  I'll have to check and see if I can duplicate the issue.

**Comment by EWSoftware** [comment]
Using the latest release, I am unable to duplicate this issue.  The content is installed and is viewable as expected with no errors.

**Comment by cbloc** [comment]
My .mshc is generated with 300 Mo datas and i can't read the help content because is empty.
Do you know if the .mshc with sandcastle have a size, because element roots are not grouped.
Maybe Help content explodes.

**Comment by EWSoftware** [comment]
Sorry, don't know what you're talking about.  Help file size will vary based on the content documented.  More assemblies or ones with more types will produce larger files.  MSHC files are just ZIP files.  If renamed, you can extract the content and see what's in it.  I doubt they are empty.
