### ISSUE TITLE
Unexpected error detected in last build step.  See output above for details.	SHFB	

### ISSUE THREAD

**Issue by siya123456** [EWSoftware/SHFB#268]
Hi,

Please help me how to solve the problem?

**Comment by EWSoftware** [comment]
I'm going to need more to go on than that.  FIrst of all, do what the error message says and look through the last step of the build to see what failed.  That will more likely than not tell you what went wrong and perhaps how to fix it.  If there's an error number listed, look it up in the help file as it may provide details on how to correct the problem.
