### ISSUE TITLE
No SHFB project shown in VS 2015 Add | New item... dialog

### ISSUE THREAD

**Issue by AnotherKiwi** [EWSoftware/SHFB#269]
I just installed SHFB 2015.10.10 with the extension for VS 2015 and the MAML schemas and snippets. When I try to add a SHFB project to my solution using the Add | New item... command, no Document category is present and I don't see any template for adding the SHFB project.

Have I missed doing something during installation?

Your help getting SHFB to work for me within VS 2015 would be appreciated!

**Comment by EWSoftware** [comment]
If that particular instance of Visual Studio was open when you installed it, it won't show up until after a restart.  Select Tools | Extensions and Updates and the select the Installed category. You should see SHFB listed there.  If not, it wasn't installed.  If it is there, you can remove it and restart Visual Studio to make sure it has been removed.  Close Visual Studio, and then run the *.vsix* file from the installation resources folder to install it manually.

**Comment by AnotherKiwi** [comment]
Hi Eric

 

Thanks for your quick response to my post.

 

I uninstalled the SHFB from VS 2015, and then reinstalled it manually. However, I still don’t see any SHFB project template showing when I try to add a new SHFB project to my VS solution using Add | New item…

 

Any thoughts on how to make a SHFB template show up?

 

Regards

Stephen

**Comment by EWSoftware** [comment]
Do you see SHFB in the Tools | Extensions and Updates?

**Comment by AnotherKiwi** [comment]
Yes, and its options in Tools | Options.

**Comment by EWSoftware** [comment]
You didn't respond to the second part which was added a little later:

Also, I just see you said Add | New Item. Projects are added using Add | New Project. You'll find the Documentation category there.

**Comment by AnotherKiwi** [comment]
Duh…thanks Eric. I can see the SHFB project when I use Add | New Project.
