### ISSUE TITLE
SHFB: Error BE0029

### ISSUE THREAD

**Issue by MulderLiu** [EWSoftware/SHFB#270]
SHFB: Error BE0029: Unexpected error while executing plug-in 'Lightweight Website Style': System.UnauthorizedAccessException: 对路径“E:\XXX\Help\Working\Output\Website”的访问被拒绝。

i Setting permissions for everyone Cannot resolve

i need help..

**Comment by EWSoftware** [comment]
If the build got that far, it must have had permission so I don't know why the plug-in would fail.  I'd suggest changing the output path and/or working folder to another location to see if you can get it to work, perhaps on your local C: drive.

**Comment by EWSoftware** [comment]
You may also be running into issue #227.  It's fixed for the next release.  If you need the fix sooner, the change has been checked in and you can build the tools from the source code.
