### ISSUE TITLE
Reoccurance of Unresolved assembly reference: Windows.Foundation.UniversalApiContract for UWP app

### ISSUE THREAD

**Issue by mjmeans** [EWSoftware/SHFB#272]
I'm developing a UWP app for Windows 10 IoT Core for the Raspberry Pi 2. I've seen the prior closed issue and have changed to the framework to .NET for Universal Windows, but to no avail. I've tried changing the build of the project and the source project to x64 also, to no avail. Any ideas?

**Comment by EWSoftware** [comment]
Can you attach an example that demonstrates the problem?

**Comment by mjmeans** [comment]
Simple. Create a new C# Universal Windows Class Library. Add the reference extension "Windows IoT Extensions for the UWP". Enable XML comments. Change Class1.cs to this:

`using System;
using System.Linq;
using System.Threading.Tasks;
using Windows.Devices.Enumeration;
using Windows.Devices.I2c;

namespace ClassLibrary1
{
    /// <summary>
    /// This class
    /// </summary>
    public class Class1
    {
        /// <summary>
        /// Instantiate
        /// </summary>
        public Class1()
        { }

        /// <summary>
        /// Initializes the object
        /// </summary>
        public async void InitializeAsync()
        {
            var controllerName = "";
            var aqs = I2cDevice.GetDeviceSelector(controllerName);
            await Task.Delay(10);
            // The next line causes the failure in SHFB
            var di = (await DeviceInformation.FindAllAsync(aqs)).FirstOrDefault();
        }
    }
}
`

**Comment by mjmeans** [comment]
Sample project uploaded to https://github.com/mjmeans/SHFB-error/

**Comment by mjmeans** [comment]
Forgot to sync repo to GitHub. Just did it now. Project to demonstrate the problem is now available at the GitHub link above.

**Comment by EWSoftware** [comment]
You didn't say whether you were using the latest release or not.  If not, you might give that a try.  Using my build it does work.  However, I recently regenerated the reflection information so it may be picking up some newer assemblies that perhaps weren't there when I originally generated it the first time.

I'll be publishing a new release in a week or two containing the updated reflection data.  I'm going to close this for now.  If it's still a problem after the new release, you can reopen it.

**Comment by mjmeans** [comment]
I had just downloaded and installed it two days ago. 2015.10.10.0. Here is the build output:

-------------------------------
[Sandcastle Help File Builder and Tools, version 2015.10.10.0]
Creating output and working folders...
Finding tools...
The Sandcastle tools are located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\'
Locating components in the following folder(s):
    C:\GitHub\Adafruit\Doc
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Framework reflection data location: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\UniversalWindows
Using presentation style 'VS2010' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2010'
-------------------------------
Clearing working folder...
-------------------------------
Clearing any prior web/markdown output...
-------------------------------
Validating and copying documentation source information
Source: C:\GitHub\Adafruit\Lib\Adafruit.MotorHat2348\Adafruit.MotorHat2348.csproj
    Found project 'C:\GitHub\Adafruit\Lib\Adafruit.MotorHat2348\Adafruit.MotorHat2348.csproj'

Parsing project files
    Found assembly 'C:\GitHub\Adafruit\Lib\Adafruit.MotorHat2348\bin\Debug\Adafruit.MotorHat2348.winmd'

Copying XML comments files
    C:\GitHub\Adafruit\Lib\Adafruit.MotorHat2348\bin\Debug\Adafruit.MotorHat2348.XML -> C:\GitHub\Adafruit\Doc\Help\Working\Adafruit.MotorHat2348.XML
-------------------------------
Generating shared content files (en-US, English (United States))...
    Last step completed in 00:00:00.0220
-------------------------------
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00.0192
-------------------------------
Generating reflection information...
[C:\Program Files (x86)\MSBuild\12.0\bin\amd64\MSBuild.exe - GenerateRefInfo.proj]
Build started 3/23/2016 9:49:37 PM.
Project "C:\GitHub\Adafruit\Doc\Help\Working\GenerateRefInfo.proj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Debug\".
GenerateRefInfo:
  MRefBuilder (v2015.10.10.0)
  Copyright c 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2015, Eric Woodruff, All Rights Reserved.
  Loaded 1 assemblies for reflection and 0 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: Windows.Foundation.UniversalApiContract (Windows.Foundation.UniversalApiContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null) required by Adafruit.MotorHat2348 [C:\GitHub\Adafruit\Doc\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:01.8435
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by mjmeans** [comment]
An open source project for Windows 10 IoT for a Raspberry Pi 2/3 library for the Adafruit Stepper Motor HAT is on hold until there is a solution.

**Comment by mjmeans** [comment]
FYI, I used the SHFB guided installer, not the NuGet installer. I currently have all of the following versions of Visual Studio installed on the same machine: 2010 Pro, 2012 Premium, 2013 Pro and 2015 Community. This project is using VS 2015 Community. The error occurs if I build within VS2105 or if I right click the doc project and select GUI and build there.

**Comment by EWSoftware** [comment]
Extract the content of the attached ZIP file in the Data\UniversalWindows folder in the SHFB installation folder.  That will replace the reflection data with the updated info and should get you going.

[UniversalWindows.zip](https://github.com/EWSoftware/SHFB/files/188108/UniversalWindows.zip)

**Comment by mjmeans** [comment]
That worked! Thank you. Now to prepare for release!
