### ISSUE TITLE
Support for 4.6.1

### ISSUE THREAD

**Issue by MattVane** [EWSoftware/SHFB#273]
Hi!

I'm using the SHFB Nuget package to build HTML help docs as part of the solution on a TeamCity agent. Whenever I try to build the project on the agent I get the following error:

> SHFB error BE0073: A project with a different or higher framework version was found but that version (.NETFramework 4.6.1) or a suitable redirected version was not found on this system. The build cannot continue.

The doc source project is 4.6.1, and 4.6.1 is definitely installed on the build server (because all the non-SHFB projects build fine). I'm wondering how it detects what version of the framework is installed? Maybe there's a particular file or registry setting that is missing and its tripping SHFB? 
Annoyingly, it works fine on my local workstation (via VS and msbuild). 

Any other clues to look for? Thanks!

M

**Comment by EWSoftware** [comment]
Extract the attached ZIP file and place the reflection data set file in the .\\Data\\.NETFramework folder of the SHFB installation.  That should allow it to find the info in needs for the time being.

This has been added for the next release and I'll be publishing an updated set of NuGet packages that contain it when released, problem in a week or two.

[DotNet461.zip](https://github.com/EWSoftware/SHFB/files/184428/DotNet461.zip)

**Comment by MattVane** [comment]
Thanks for the prompt response Eric!

Good news: the patch worked perfectly.
Bad news: I'm constrained to use nuget restore on the build agent to ensure we don't do funky things (exactly like this), so I'll have to wait for the release in a week or two. But I'll keep an eye on the project and see when the release drops.

Thanks again!

**Comment by twenzel** [comment]
Any schedule for the next release with 4.6.1 support?

**Comment by EWSoftware** [comment]
If I get time, I'll publish it this weekend.  The workaround won't work with v2015.1.12 since it didn't use the reflection data set files.

**Comment by MattVane** [comment]
Thanks for publishing, and not wanting to post egg sucking instructions, but shouldn't there be a new version of SHFB.NETFrameworks to enable the 4.6.1 compatibility?

**Comment by EWSoftware** [comment]
Sorry, forgot to push that package.  It's there now.

**Comment by MattVane** [comment]
All good, ta
