### ISSUE TITLE
Sandcastle should issue a warning that non-summary elements on enum members won't be visible

### ISSUE THREAD

**Issue by RobSiklos** [EWSoftware/SHFB#274]
If you have an enumeration, only the contents of the `<summary>` element are included in the generated documentation for the enumeration members. If you have other elements (e.g. `<remarks>`, `<seealso>`), those will never be included. It would be great if Sandcastle could output a warning indicating that this is the case.

E.g.:

```
/// <summary>My enumeration of great people.</summary>
/// <remarks>This will be visible - no problem.</remarks>
public enum GreatPeople
{
    /// <summary>A great person.</summary>
    /// <remarks>
    ///   We could go into detail here describing why Eric is so great, but it
    ///   won't matter because remarks are never visible in the Sandcastle-output
    ///   documentation.
    ///   A warning would be nice.
    /// </remarks>
    Eric,
}
```

**Comment by EWSoftware** [comment]
Whether or not remarks or other elements appear is entirely up to the presentation style.  Common convention is that enumeration field members topics are suppressed and they are listed in a table within the containing enumeration's topic with only the summary shown as the description.

Remarks could be included by changing the presentation style.  By changing the document model, individual topics could be generated for each enumeration field member at which point, all comments elements would be treated as usual.

I guess that's a long way of saying SHFB can't make assumptions about what a presentation style might or might not do.  This is probably something better noted as conventional behavior somewhere in the XML Comments Guide.

**Comment by RobSiklos** [comment]
Ok - that makes sense. I'll leave it to you to update the guide in whatever way you see fit.

**Comment by EWSoftware** [comment]
I added a list item to the Usage Notes topic that describes the behavior for enumeration comments.
