### ISSUE TITLE
Multiple documentation projects in Single Website

### ISSUE THREAD

**Issue by AshShip** [EWSoftware/SHFB#277]
We have an internal framework consisting of several documentation projects created by Sandcastle and we would like to generate a single documentation website for these separate projects.
Is it possible with SHFB to create a single website from different sandcastle projects?

**Comment by EWSoftware** [comment]
As noted in #179, you may be able to use the [Version Builder Plug-In](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm).

In short, you'd create a help project for each project to document.  Pick one as the primary project.  Add the plug-in to that project and add the other projects to the plug-in's configuration.

**Comment by AshShip** [comment]
Thank you. It worked!
