### ISSUE TITLE
Website Search fails in SearchForKeywords

### ISSUE THREAD

**Issue by deejaygraham** [EWSoftware/SHFB#28]
Using the search from branding-website.js, occasionally seeing some negative indices appearing in the occurrenceIndices array. So that:
		
   // Split out the title, filename, and word count
   var matchingIdx = matchingFileIndices[fileIdx];
   var fileIndex = fileInfo[matchingIdx].split(/\0/);

causes an exception "fileInfo[matchingIdx] is undefined" and kills the search output - no html is generated and it looks like the search is still ongoing. Could it be an overflow error? The content of the website is > 80,000 pages.

**Comment by EWSoftware** [comment]
It should, as far as I know, be using integers for the index values so there shouldn't be a problem with overflows unless JavaScript is doing something unexpected or that I didn't anticipate.  Can you send me your .\fti folder content?  With that, I should be able to test the search and see if I can duplicate the problem.  I shouldn't need any of the other files.

**Comment by deejaygraham** [comment]
Emailed files (22 MB) and screenshot. Thanks.

**Comment by EWSoftware** [comment]
Apparently, JavaScript will only perform bit shift operations on 32-bit values.  As such, it's converting the 64-bit values to 32-bit values and I'm pretty sure that's what's causing the resulting negative values.  If you replace the two bit shift occurrences of `>> 16` in the script files with a division operation of `/ Math.pow(2, 16)`, it will perform the same operation but maintains the result as a 64-bit value so there's no loss of precision.  Let me know if that corrects the problem for you.

**Comment by deejaygraham** [comment]
I tried that replacement in both places but it failed with no results returned! What did work was an unsigned shift (>>>). It looks like it was sign extension causing the negative values so shifting without sign seems to work. So:

        for (var ind in occurrences)
            occurrenceIndices.push(occurrences[ind] >>> 16);

...

                if ((entry >>> 16) == matchingIdx)
                    matchCount += (entry & 0xFFFF);

The returned search items look correct in terms of number and content.

**Comment by EWSoftware** [comment]
The ">>>" operator works only on 32-bit values as well.  So, while it won't produce a negative, it will truncate the 64-bit values down to 32-bit values so it effectively wraps around and you'll see results that don't contain the match once the file index goes above 65535.

I found that the Math.pow() function doesn't always produce a whole number so the fractional part was causing a problem.  Using Math.floor() fixes it.  The following are the corrected changes which will produce accurate results:

```
for(var ind in occurrences)
    occurrenceIndices.push(Math.floor(occurrences[ind] / Math.pow(2, 16)));


if(Math.floor(entry / Math.pow(2, 16)) == matchingIdx)
    matchCount += (entry & 0xFFFF);
```

**Comment by deejaygraham** [comment]
Aha. Thanks.
