### ISSUE TITLE
Add custom styles to a Sandcastle project

### ISSUE THREAD

**Issue by icom85** [EWSoftware/SHFB#280]
Hello,

Is there a way to add custom styles in Sandcastle to be used for a build of Help 3 API Reference?

Thank you.
Hristo

**Comment by EWSoftware** [comment]
If you are referring to replacing the entire presentation style, you can create your own either from scratch or by cloning the content of one of the existing styles.  See the [Creating a Presentation Style Component](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) help topic for details.

If you just want to replace the style sheet, you can do that by including a like named copy of the style sheet in a like-named folder within the help project.  For example, to replace the VS2013 style sheet, you'd add a *styles\* folder and put a copy of your modified *branding.css* in it.  see the [Replacing Stock Content Files](http://ewsoftware.github.io/SHFB/html/77d2d693-db84-4ae3-a84c-e33c71f92e9a.htm) topic for details.

**Comment by icom85** [comment]
Thanks for the info.
