### ISSUE TITLE
Version Builder fails to correctly sort versions

### ISSUE THREAD

**Issue by PedroLamas** [EWSoftware/SHFB#283]
While using the Version Builder plugin, I noticed that version 10.0 was failing to be recognized as a more recent one than 8.0, which led me to check the code where I noticed that a string comparison is currently here:

https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/VersionSettingsCollection.cs#L110

If this is replaced by a proper version comparison, this would fix this issue!

**Comment by EWSoftware** [comment]
Merged.  Thanks.
