### ISSUE TITLE
Working in VS not working on TFS 2015

### ISSUE THREAD

**Issue by theliberator** [EWSoftware/SHFB#285]
I've installed SHFB via SHFBInstaller_v2015.10.10.0 on my local machine and on our TFS-Server (2015 Update 2), added a SHFB-Project to my solution and added a documentation source for one of the projects in the solution.

Building the solution with visual studio is working fine, on TFS however, msbuild exits with the error BE0040. Project binaries are compiled to 'C:\TfsAgents\DefaultAgent\_work\1\s\MySolution\MyProject\bin\**x86**\Debug\MyProject.dll' whereas SFHB is expecting the dll at  'C:\TfsAgents\DefaultAgent\_work\1\s\MySolution\MyProject\bin\Debug\MyProject.dll'.

I also set the SFHB-projects platform to x86 in VS build configuration manager, but the value always reverts back to AnyCPU (even if I edit the .sln file manually, VS resets the platform back to AnyCPU when loading the solution). 

Edit: The default build config for the solution is Debug|x86.
Edit2: grammar and fixing version mistake (see below).

**Comment by EWSoftware** [comment]
There is no such version 2.1.73.  The latest official release can be found here: https://github.com/EWSoftware/SHFB/releases.  I'd suggest installing that and trying again.

**Comment by theliberator** [comment]
Sorry, my fault, mix up between TFSAggregator and SHFB (using both here, wrong browser tab).

Corrected version:SHFBInstaller_v2015.10.10.0

**Comment by EWSoftware** [comment]
Try the latest release.  If you're building the SHFB project separately, you may need to specify the OutDir property so it knows where to look.

**Comment by theliberator** [comment]
Tested with v2016.4.9.0, problem persists (SFHB is looking for .dlls in the wrong directory on TFS and platform in build config in VS cannot be changed).

I'm not building separately, but as mentioned above, the SHFB-project is part of the solution being built with TFS Visual Studio Build.

**Comment by EWSoftware** [comment]
You can try setting the configuration and platform explicitly on the documentation source properties.  I don't have access to a TFS build server so this isn't something I can diagnose any further.
