### ISSUE TITLE
Error: ATL.CComPtr has an invalid token

### ISSUE THREAD

**Issue by oggy22** [EWSoftware/SHFB#286]
Hi

I am building a big SandCastle project (around 100 binaries) within Visual Studio 2015 Update 2 and I am getting this error:

> BuildAssembler : error : &#39;document/reference/elements//element[starts-with(@api, &#39;M:ATL.CComPtr&lt;`anonymous namespace&#39;::Ctre&gt;.#ctor&#39;)]&#39; has an invalid token. [D:\dev\src\SandcastleDocumentation\Help\Working\BuildTopics.proj]

I don't have any reference to _ATL.CComPtr_ and the only external reference I have is:

> C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral\Windows.winmd

I am using the latest SandCastle from April 9th, 2016.

Any thoughts?

Thanks, Ogi!

**Comment by EWSoftware** [comment]
Your code might not have a reference but one of the documented classes most likely inherits it and its members.  You can open the *reflection.xml* file in the working folder after a failed build and search for that ID.  It's probably in there somewhere.

The only place I can find that expression is in the Show Missing Component when its adding auto-documented constructors.  You can turn that option off in the Visibility category of the project properties to see if it works around the issue.  If the expression you gave is correct, it's probably the single quotes in the member ID that are causing the issue.  I'll see if I can duplicate the issue using it.
