### ISSUE TITLE
Where is the logo file/icons directory supposed to be located

### ISSUE THREAD

**Issue by Stephen-Mc** [EWSoftware/SHFB#287]
I am trying to add a logo to the documentation generated by Sandcastle. The help file builder says "Place the file in your project in an icons\ folder and set the Build Action to Content".

So I assume from this description that I need to add an icons folder to my **Visual Studio** project (the help tends to use the term "project" interchangeably for both the help file project and VS project, which is extremely confusing).

I have added an icons folder to the project I am trying to document and added the logo to that folder. I have set the Build Action to "Content".

However, whenever I build the documentation, the icons folder generated by Sandcastle does not contain this image and the link on the pages is dead. If I manually copy my logo to the icons directory in the help output, it is displayed correctly, but overwritten/deleted the next time I generate the documentation.

I have searched the net high and wide and can find nothing on this subject. Can someone please tell me where exactly the icons folder is supposed to be located?

**Comment by EWSoftware** [comment]
If you want folders and content like an image included in the compiled help file, it goes in the help project.  The only thing taken from projects used as documentation sources is the API information obtained by parsing the assemblies in them.

**Comment by kwmacdowell** [comment]
Thanks EWSoftware. I had the same problem and your input helped me solve the problem. I'll add, that  "Place the file in your project in an icons\ folder and set the Build Action to Content" means, go to where your SandCastle project file is, create a folder called icons, put your logo file in it, in your SandCastle Project Explorer (right side), right-click the project file, click Add > Existing Folder >, add the icon folder. You should then see the logo file in your Project Explorer. Select it, then in the window below, to the right of Build Action, click the pulldown arrow and select "Content".

**Comment by Stephen-Mc** [comment]
Thanks for that info kwmacdowell, that is exactly the information I would have needed in May. 

I decided to use Doxygen in the end, as it is a lot easier to get started and has much better documentation.
