### ISSUE TITLE
Allow entire assembly to be excluded via API Filter

### ISSUE THREAD

**Issue by jhennessey** [EWSoftware/SHFB#290]
I'm in a situation where I need to pull in only a few types from an assembly that my project references. I would like to be able to use an API Filter to exclude everything in this assembly except for types I need. Right now, it seems I have to exclude all the namespaces and then add an API Filter to include the one class I need. This makes it very difficult to maintain my project since the referenced assembly changes frequently so I have to then go through and exclude any new namespaces that were added.

Perhaps there is an easier way to do this that I'm just not familiar with?

**Comment by EWSoftware** [comment]
Exclusions are by namespace, type, and member.  There isn't a way to exclude by assembly.  Assemblies can contain multiple namespaces which may appear in other assemblies as well so it's not really practical to exclude by assembly.

If all you are trying to do is include documentation for inherited members on the list pages, I'd suggest using the Additional Reference Links plug-in.  You can use it to provide inherited member documentation and suppress any missing reference link warnings.
