### ISSUE TITLE
SHFB builds of Universal Windows Platform Enumeration TYPEs create unexpected content

### ISSUE THREAD

**Issue by dkemlage** [EWSoftware/SHFB#291]
Hello Eric,

I have been generating Library Reference doc using the Visual Studio SandCastle VSIX extension with the following configurations and both produce the same results:

~ Windows 8.1 Enterprise | Visual Studio 2015 with Update 1 | SHFB 2015.10.10.0
~ Windows 8.1 Enterprise | Visual Studio 2015 with Update 2 | SHFB 2016.4.9.0

The problem is that Library Reference pages for Enumerations are producing undesirable content for Universal Windows Platform SDK builds.

**Steps to reproduce:**

ONE: Use VS2015 to create a Windows Universal Class Library. Make sure an check on building XML documentation in the Project Properties.

TWO: Replace the code for Class1.cs with the following:

```
namespace ClassLibrary_UWP
{
	/// <summary>
	/// Test Class1
	/// </summary>
	public class Class1
    {
		/// <summary>
		/// Test Enumeration
		/// </summary>
		public enum TestLevel
		{
			/// <summary>Level 0</summary>
			Level0 = 0,
			/// <summary>Level 1</summary>
			Level1 = 1,
			/// <summary>Level 2</summary>
			Level2 = 2,
		};
	}
}
```
THREE: Build the project to create the ClassLibrary_UWP.dll

FOUR: Create a VS2015 SandCastle documentation project.

FIVE: Reference the ClassLibrary_UWP.dll as a documentation source. 

SIX: Change the Framework version to ".NET for Universal Windows" in the documentation project's Properties dialog | Build tab.
 
SEVEN: Build the project and examine the resulting .chm for the TestLevel Enumaration.

![image](https://cloud.githubusercontent.com/assets/5495810/14899420/ba60cbf2-0d40-11e6-9d04-d8d95bbe35ef.png)

The output of the LastBuld.log yields the following relevant information:

BuildAssembler : warning : ShowMissingComponent: [F:ClassLibrary_UWP.Class1.TestLevel.value__] Missing &lt;summary&gt; documentation [C:\Temp\SandCastleTest\SC_UWP\SC_UWP\Help\Working\BuildReferenceTopics.proj]

When I perform similar steps to create a WPF version .DLL using the same Class1.cs syntax above and create a SandCastle documentation project using the default Framework version of ".NET Framework 4.5", I do not get any SandCastle compiler warnings in the LastBuild.log and the output of the .CHM looks as I would expect for an Enumeration.

![image](https://cloud.githubusercontent.com/assets/5495810/14899720/41a882b6-0d42-11e6-8d57-6a89d042129c.png)

Can you please confirm if this is an issue that needs to be fixed or tell me if I am doing something incorrectly in producing Universal Windows Platform (UWP) Library Reference documentation,

Thanks,
Don Kemlage
dkemlage@esri.com

**Comment by EWSoftware** [comment]
The UWP assemblies are probably compiled differently.  Note that the enums are actually listed as classes deriving from enum rather than just being enums.  One of the other frameworks or winmd files do something similar.  I'll have to see what MRefBuilder is finding when it parses them.

**Comment by dotMorten** [comment]
@ewsoftware as this is impeding us, what can I do to help try and fix this error? I could probably take a stab at it if I got some pointers where to start looking.

**Comment by EWSoftware** [comment]
In this case it turned out to be a problem with the way MRefBuilder was handling frameworks like .NETCore that redirect all their types out of mscorlib into System.Runtime.  This was causing it to miss that the base type was an enumeration.  The attached patched version corrects the issue.

[MRefBuilderPatched.zip](https://github.com/EWSoftware/SHFB/files/255698/MRefBuilderPatched.zip)

**Comment by dotMorten** [comment]
@EWSoftware Awesome! Thanks Eric.

**Comment by dkemlage** [comment]
Hello Eric,

I just finished testing patch you created and it worked perfectly!

Our Universal Windows Platform (UWP) Enumerations are now generating the correct pages.

Thank you,
Don Kemlage

P.S.
For those SandCastle users experiencing similar problems, make sure that you have SHFB version 2016.4.9.0 installed before you replace the patched version of the MRefBuilder.exe in the directory: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder
