### ISSUE TITLE
Presentation style (sometimes) not usable in VS2015 SHFB project plug-in

### ISSUE THREAD

**Issue by Dany-R** [EWSoftware/SHFB#292]
**SHFB-2016.4.9.0** VS2015 SHFB project plug-in
Selecting a `presentation style` that has _different_ strings for `PresentationStyleExportAttribute` parameters `id` and `title` will be stored in the _shfbproj_ file (`id` string) but when reloading that file (displaying the project properties) the presentation style changes to "VS2013".
This is true for "Open XML Document" as well as for custom presentation styles having such an attribute setting.
Another issue is that some strings seem to be "invalid" as well (e.g. using "VS2005" for both): you might select and store it but reloading jumps back to "VS2013".

P.S.: It is my intention to reactivate the "old" VS2005 style because I find it much clearer (font not too big, table style, header and footer) and more practical (collapsible blocks).

Cheers, Dany

**Comment by EWSoftware** [comment]
Seems to be a bug in the property page.  It gets stored in the project and stays set.  I'll see about getting it fixed.

**Comment by Dany-R** [comment]
Thanks a lot. But starting the build process really uses VS2013 then.
