### ISSUE TITLE
Project Output not supported?

### ISSUE THREAD

**Issue by hvledder** [EWSoftware/SHFB#293]
Eric,

When using an installer like InstallShield or a regular VS Setup project, items to be installed can be specified by adding the output of a project (usually called Project Output Group), which resolves to the end result(s) of a compiled project (i.e. DLL or EXE usually).

![setup configuration](https://cloud.githubusercontent.com/assets/17947342/14951183/5abaecae-1057-11e6-8923-882b0ce0b630.png)

However, SHFB projects do have project output too, especially when generating CHM files. Adding the project output of a SHFB project unfortunately resolves to nothing. Neither do the other content options of the installer in case of an SHFB project.

Having these groups resolve to the results of the compiled SHFB project would allow me to avoid absolute paths to include project results to the installer. Besides, it will won't force me to make the CHM file part of version control, which is a side effect of adding files by absolute path.

Would it be possible to make an SHFB project behave like any other in this context?

Please advise,
Regards,
Hans

**Comment by EWSoftware** [comment]
SHFB generates several output properties from its build task:  Help1Files, HelpViewerFiles, WebsiteFiles, OpenXmlFiles, MardownFiles, and AllHelpFiles.  The last is a merger of all the others in the event that the project is building multiple formats.

I don't know how InstallShield determines "primary output" and bear in mind that SHFB doesn't produce and executable nor necessarily a single file.  You can override the [build targets](http://ewsoftware.github.io/SHFB/html/8ffc0d37-0215-4609-b6f8-dba53a6c5063.htm) within a SHFB project.  You could add an override for the *AfterBuildHelp* target that uses the *AllHelpFiles* property to copies the files to the *OutDir* location or a subfolder beneath it.

**Comment by hvledder** [comment]
Hi Eric,

Thanks for your response. I've done some investigation, because I did not know how this works myself. It appears that the Primary Output of a project is determined by the installer by what is a called an OutputGroup, which is part of the ProjectConfig of the SHFB project, which in turn can specify (resolve to) multiple files and dependencies. 

Apparently, these capabilities are implemented by the [IVsOutputGroup](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsoutputgroup.aspx) interface. Both the OutputGroup and ProjectConfig classes appear to exist within SHFB's code.

Maybe you're willing to take a look at this, because having these capabilities in SHFB projects would be trè chique, and will make SHFB seamlessly integrate with all installers available.

Regards,
Hans

**Comment by EWSoftware** [comment]
The classes are in the MPF assembly but SHFB doesn't use them.  Also, they appear to be based on a project configuration (Debug/Release) which is also something SHFB does not use for its own projects.  I doubt what you're asking for will work in this case.  I'll take a look but to be honest, you're probably better off doing what I suggested above about copying the files in the AfterBuildHelp target override.

**Comment by EWSoftware** [comment]
I'm not able to figure out how this is supposed to work.  If somebody else wants to tackle it feel free but for now, I'm going to suggest the workaround noted above.
