### ISSUE TITLE
How to Align Link to extreme right side of content page

### ISSUE THREAD

**Issue by ramiz272** [EWSoftware/SHFB#295]
Is there a way to align the link text to the extreme right side? is there any style already present in vs2013 style or can i alter the branding.css file in vs2013 presentation styles folder? if yes then how to achieve this? Actually i want my own navigation for next and previous page which I can achieve using link but i am unable to right align the text of that link. So kindly let me know how to right align or any other alternative solution for navigation?

**Comment by EWSoftware** [comment]
You can use HTML anchor tags in XML comments and apply your own style.  However, you won't be able to do so in MAML topics without using a `markup` element to pass through the literal HTML.  The HTML anchor tags won't work in all help formats either such as MS Help Viewer which uses a different URL format.

If you want to change how the presentation style works, you are more likely than not going to have to create your own or clone one of the existing presentation styles and modify it.  That would probably be more efficient than trying to hand code links in every single member's comments or MAML topic.  See the [Creating a Presentation Style Component)[http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm] topic for details.

**Comment by ramiz272** [comment]
Thank you Eric for your response. I just need it to work for .chm file so could you give me a code example for using HTML anchor tags in XML comments and applying a custom style on it?

So far I tried to add "float: right;" in a:Link css snippet of Branding.css but what it does is it makes all the links right aligned which is wrong as I just want one Link to be right aligned rest remain same. I also tried to add a custom css snippet and tried to apply it on Link as shown below but was unable to achieve the required functionality.
<link class="xyz" href:xxx-xxxxx-xxxxxxx>My Right Aligned Link</link>

Therefore, please share a code sample with me if possible, Thanks

**Comment by ramiz272** [comment]
Ok found it in here:
http://ewsoftware.github.io/MAMLGuide/html/aaaff238-1ab4-4c9e-95d8-60ca4d8d4f8e.htm

Thankx

**Comment by EWSoftware** [comment]
The simplest approach would be to use an inline style:

```XML
<a href="http://www.someurl.com" style="float: right;">Some URL</a>
```

If you want to use a class, you can add a custom class with the style to the CSS file for the presentation style.

**Comment by ramiz272** [comment]
I tried your approach the link is right aligned now but i am unable to move to the next content page of chm file when i click on the link button. The code that i used is given below:
`<markup>
        <a href="a49a1885-f8c5-4ef3-85da-87dc65330516" style="float: right;">Next</a>
 </markup>`
Now when user click on "Next" link button he should be moved to the content page whose id is "a49a1885-f8c5-4ef3-85da-87dc65330516". But it isn't happening with the anchor control. 
How can I achieve this functionality with anchor?
