### ISSUE TITLE
Unexpected error since updating to 2016.4.9.0

### ISSUE THREAD

**Issue by iceteagroup** [EWSoftware/SHFB#297]
Since I installed the latest build it cannot build anymore. The log shows:

BuildAssembler : error : SharedContentComponent: [G:] Error replacing item.  Root document element encountered.

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

It building before the update. I needed to update because it was crashing visual studio when adding a new conceptual file to the contentlayout.

Any idea?

**Comment by EWSoftware** [comment]
Check the release notes from the last version you were using through the current release.  It's possible a breaking change is affecting your project and you may need to update the custom component or plug-in configurations by removing and re-adding them.

If none of that helps, can you supply an example them demonstrates the issue?

**Comment by iceteagroup** [comment]
Hi Eric,

Thank you for the quick reply.

I fiddled with the project settings and got rid of the error. Turned the
"include root namespace container" on and it worked. Turned it back off and
it worked.

Best,
Luca Pivato
Ice Tea Group

**Comment by jenaewhitmore** [comment]
That fixed the issue for me too.
