### ISSUE TITLE
Help file build just fails for unknown reason 

### ISSUE THREAD

**Issue by jenaewhitmore** [EWSoftware/SHFB#298]
My help file build fails sporadically for reasons I cant figure out. It just tells me 
"Error replacing item.  Root document element encountered.[.....\BuildTopics.proj]". Its very frustrating as I cannot figure out why it succeeds at certain times and fails on others!

**Comment by EWSoftware** [comment]
See issue #297 as this appears to be the same issue.  My reply there would apply here too if toggling the root namespace container option doesn't resolve it for you.
