### ISSUE TITLE
Fail to use NamespaceGroupDoc class to document namespace group

### ISSUE THREAD

**Issue by dgedge33** [EWSoftware/SHFB#30]
Hi,

First of all, great thanks for this documentation tools and for the regular improvements this tool benefits !
Working on a thin wrapper for a C++ library, I use SHFB to generate the documentation of the wrapped library.
I try to use the NamespaceGroupDoc feature as mentionned here http://ewsoftware.github.io/SHFB/html/48f5a893-acde-4e50-8c17-72b83d9c3f9d.htm.
What I understood of this feature is that it gives the capability to document namespace group (i.e. namespace without any class) by providing in the source code a NamespaceGroupDoc class in the same way that  NamespaceDoc.
But I fail to have documentation generated for my namespace group. I try different doc format but I have the same result.
Do I misunderstand the meaning of NamespaceGroupDoc feature ?

Thanks.
Jerome
 P.S. I use the 2015.1.12.0 version.

**Comment by EWSoftware** [comment]
Namespace groups are used to group namespaces with a common root name.  For example, the .NET [System.Windows](https://msdn.microsoft.com/en-us/library/gg145013(v=vs.110).aspx) namespace contains several child namespaces.  In order for this to work, your SHFB project must enable the [namespace grouping](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#NSGrouping) option in the **Help File** category.  You can also control the nesting level when creating container topics.  The default is two namespace parts.

The `NamespaceGroupDoc` comments are added to the namespace group list page which is similar to the root namespace container page if enabled.  It does not create a page for a namespace that contains no types.  It only creates a page if there are child namespaces.  The help link above contains an example.

**Comment by dgedge33** [comment]
Thanks Eric for your answer.
This is how my test library looks:
- A namespace MyCompany.MyProduct.FirstFeature containing a public class and a NamespaceDoc class

namespace MyCompany.MyProduct.FirstFeature
{
  /// <summary>
  /// These are the namespace comments for <c>MyCompany.MyProduct.FirstFeature</c>.
  /// </summary>
  [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  class NamespaceDoc
  {
  }

  /// <summary>
  /// This is a class which belongs to the <see cref="N:MyCompany.MyProduct.FirstFeature"/>
  /// namespace.
  /// </summary>
  public class Class1
  {
  }
}

- A namespace MyCompany.MyProduct.SecondFeature containing another public class with a NamespaceDoc class

namespace MyCompany.MyProduct.SecondFeature
{
  /// <summary>
  /// These are the namespace comments for <c>MyCompany.MyProduct.SecondFeature</c>.
  /// </summary>
  [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  class NamespaceDoc
  {
  }

  /// <summary>
  /// This is a class which belongs to the <see cref="N:MyCompany.MyProduct.SecondFeature"/>
  /// namespace.
  /// </summary>
  public class Class2
  {
  }
}

- A NamespaceGroupDoc class defined in the namespace MyCompany.MyProduct

namespace MyCompany.MyProduct
{
  /// <summary>
  /// These are the group comments for namespaces in <c>Company.Product</c>.
  /// </summary>
  [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  class NamespaceGroupDoc
  {
  }
}

My help project enable namespace grouping but in the generated documentation I do not see any page for MyCompany.MyProduct group namespace  
![capture](https://cloud.githubusercontent.com/assets/11267064/6482807/70af8272-c26a-11e4-8ddb-2befd7d64eaa.JPG)

Is it the correct behavior ?

Jérôme.

**Comment by dgedge33** [comment]
Nobody to answer me ?
My test case follow the example mentionned in the  [namespace grouping](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#NSGrouping) documentation but I think I do not have the correct output.

Thanks.
Jerome.
