### ISSUE TITLE
Runtime error during building phase

### ISSUE THREAD

**Issue by SesticM** [EWSoftware/SHFB#300]
Please see attached screenshot. Error is being thrown right after building starts:

> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe "D:\Release.shfbproj"
Microsoft (R) Build Engine version 4.6.1055.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

> Build started 26.05.2016 18:24:09.
Project "D:\Release.shfbproj" on node 1 (default targets).
CoreBuildHelp:
  Building D:\Release.shfbproj

Following error is being thrown at this point:

![error](https://cloud.githubusercontent.com/assets/11457703/15582130/b9127468-236f-11e6-8312-123a8eb84fef.png)

Building environment: Windows 7 (64-bit)

**Comment by EWSoftware** [comment]
Is it just with this project or all projects?  What if you try the 32-bit version of MSBuild or MSBuild 12.0 or 14.0 under %ProgramFiles(x86)\MSBuild rather than the older one that comes with the framework files?  Have you tried it on a different PC?

**Comment by SesticM** [comment]
Hi Eric, after lots of trials and errors :-) it seems that this specific 64-bit environment is causing this. 32-bit one works fine. Tried with both .NET 3.5 and 4.0 on 64-bit OS with no luck. Internally I'm using VS2010 but not integrated with Sandcastle. Seems like an issue with specific MS VC library but I'm not an expert on this topic.

**Comment by EWSoftware** [comment]
Using the version of MSBuild shown in your original post, it does work for me on my projects.  I'm not sure why it would fail unless there's an issue on that specific system.  Probably not much I can do about that.

**Comment by SesticM** [comment]
There may be a mismatched dependency to certain Visual C++ libs (.msm package) not supplied with the installer by default. Let me investigate this for a while, will get back with results...

**Comment by SesticM** [comment]
Just a short update - this one actually got fixed in v2016.5.28.0.
