### ISSUE TITLE
No members in the template matched the parameters of the specialization

### ISSUE THREAD

**Issue by cesarsouza** [EWSoftware/SHFB#302]
Hello there,

I have just updated Sandcastle Help File Builder to the latest version. When I try to build my project, I am getting the following error:

  No members in the template matched the parameters of the specialization.  This is not possible but apparently it happened.

Here is part of the log generated:

```
Generating reflection information...
[C:\Program Files (x86)\MSBuild\12.0\bin\MSBuild.exe - GenerateRefInfo.proj]
Build started 06-Jun-16 9:32:25 PM.
Project "C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Debug\".
GenerateRefInfo:
  MRefBuilder (v2016.5.28.0)
  Copyright c 2006-2016, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2016, Eric Woodruff, All Rights Reserved.
  Loaded 27 assemblies for reflection and 3 dependency assemblies.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Accord.MachineLearning.Bayes.NaiveBayesLearningBase`4<Accord.MachineLearning.Bayes.NaiveBayes,Accord.Statistics.Distributions.Univariate.GeneralDiscreteDistribution,System.Int32,Accord.Statistics.Distributions.Fitting.IndependentOptions`1<Accord.Statistics.Distributions.Fitting.GeneralDiscreteOptions>> [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error : Accord.MachineLearning.Bayes.NaiveBayesLearningBase`4<Accord.MachineLearning.Bayes.NaiveBayes,Accord.Statistics.Distributions.Univariate.GeneralDiscreteDistribution,System.Int32,Accord.Statistics.Distributions.Fitting.IndependentOptions`1<Accord.Statistics.Distributions.Fitting.GeneralDiscreteOptions>>.Learn(System.Int32[][],System.Double[][],System.Double[]) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error : No members in the template matched the parameters of the specialization.  This is not possible but apparently it happened. [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ReflectionUtilities.GetTemplateMember(Member member) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteMemberReference(Member member) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteProcedureData(Method method, Member overrides) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteMember(Member member, TypeNode type) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitMember(Member member) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitMembers(MemberList members) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitType(TypeNode type) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitType(TypeNode type) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitTypes(TypeNodeList types) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespace(Namespace space) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespace(Namespace space) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespaces(NamespaceList spaces) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespaces(NamespaceList spaces) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis() [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj]
Done Building Project "C:\Projects\Accord.NET\framework\Docs\Working\GenerateRefInfo.proj" (default targets) -- FAILED.

Build FAILED.

Time Elapsed 00:00:03.50
    Last step completed in 00:00:03.8101
+Failed
```

And the class that is triggering the error seems to be this one: [NaiveBayesLearningBase{TModel, TDistribution, TInput, TOptions}](https://github.com/accord-net/framework/blob/development/Sources/Accord.MachineLearning/Bayes/Learning/Base/NaiveBayesLearningBase%604.cs)

**Comment by EWSoftware** [comment]
Your code is generating a rather complex signature that's hard to match when finding all the inherited members. I've updated MRefBuilder to at least work around the issue.  It should generate the proper matches.  Try the attached patched version of MRefBuilder.  Extract it and put it in the *%ProgramFiles(x86)\EWSoftware\Sandcastle Help File Builder* folder.

[MRefBuilderPatched.zip](https://github.com/EWSoftware/SHFB/files/309594/MRefBuilderPatched.zip)

**Comment by cesarsouza** [comment]
Thanks ;-) I hope you could just pretend I made the rather complicated signature just to exercise Sandcastle Help File Builder. I will test it within a few days and check if it works. Thanks!

**Comment by EWSoftware** [comment]
@cesarsouza: Did the patched version work?

**Comment by cesarsouza** [comment]
Thanks, the patched version indeed fixed the original issue regarding the "No members in the template matched the parameters of the specialization" error. However, the generation kind of hangs after a while. It has been more than 2h that the both the output window and the log file have not been updated. Visual Studio CPU usage is mostly at 3%. 

I am trying to isolate the class that is causing this by ignoring a few namespaces from the documentation. Is there any known issue that might result in similar behavior?

Thanks a lot for the help!

**Comment by EWSoftware** [comment]
There are no hang issues that I'm aware of with MRefBuilder.  There is one with the GenerateInheritedDocs tool (#299) but that's a very specific case related to some ill-formed inheritdoc XML comments.

**Comment by cesarsouza** [comment]
I have been able to isolate a few classes that were causing the hanging issue. Actually, as soon as I had left only a few classes (~20) the problem changed from a hang issue to multiple PathTooLongExceptions. If I remember correctly, it seemed to me that the exceptions were being raised inside a parallel block, but I don't have the log anymore to paste here.

In short, the problem was that I had options to generate descriptive filenames when generating a website (i.e. Namespace_Class_Method.htm) instead of GUIDs, and I also had the option for documenting explicit interface implementations enabled. To tell the truth I am not sure how this option affects the filenames for the generated files, but it was definitely playing a role in the issue. Some generic classes were explicitly implementing some explicit interfaces inside some somewhat deep namespaces, leading to filenames with more than 260 characters and thus the exceptions.

Disabling the option to document explicit interface implementations and moving the output folder to the root of the drive solved the hang issue (just moving the output folder was not enough).

Thanks again for the help!

Regards,
Cesar
