### ISSUE TITLE
BuildComponentCore still has ReferenceBuildPlacement and ConceptualBuildPlacement

### ISSUE THREAD

**Issue by KarloX2** [EWSoftware/SHFB#304]
Hello,

I've written my own Build Component, originally using SHFB v2015.10.10.0.

Now I read in the release notes of v2016.4.9.0 about some breaking changes. I was concerned of this mentioned in the release note: "Removed BuildStep.BuildConceptualTopics and BuildStep.BuildReferenceTopics and replaced them with a common BuildStep.BuildTopics step that generates both the conceptual and API topics.".

In fact my code include the following lines:

```
public Factory()
{
  //Set placement for both reference builds and conceptual builds
  base.ReferenceBuildPlacement = new ComponentPlacement(PlacementAction.Before, "XSL Transform Component");
  base.ConceptualBuildPlacement = new ComponentPlacement(PlacementAction.Before, "XSL Transform Component");
}
```

From what I read in the release notes I expected that I need to change this somehow. But now I installed v2016.5.28.0, successfully recompiled my code and ran it and it seems that it still just works fine.

Am I missing something, or is it true that the breaking changes to the latest version just don't affect me?

Thanks
Karlo

**Comment by EWSoftware** [comment]
The removal of the build steps affects plug-ins.  The placement action for components is still valid and didn't change as there are still separate component stacks for conceptual and API topics.  As long as you updated the references to use the latest SHFB assemblies, you should be all set.
