### ISSUE TITLE
No XML help found in .sqlproj project

### ISSUE THREAD

**Issue by lucvdv** [EWSoftware/SHFB#307]
Are .sqlproj projects unsupported?
I have such a project in Visual Studio 2015 that generates a CLR stored proceduse for SQL server.
Source is in VB.Net.
The SHFB build succeeds, but none of the XML help in my source files is included in the help file.
What I do find is this in the build log:
`<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: D:\_Projects\A2S-TCP\A2S System\Controls-Modules-Tools\SqlServerA2SExtensions\SqlServerA2SExtensions Module\SqlServerA2SExtensions Component.sqlproj
    Found project &#39;D:\_Projects\A2S-TCP\A2S System\Controls-Modules-Tools\SqlServerA2SExtensions\SqlServerA2SExtensions Module\SqlServerA2SExtensions Component.sqlproj&#39;

Parsing project files
    Found assembly &#39;D:\_Projects\A2S-TCP\A2S System\Controls-Modules-Tools\SqlServerA2SExtensions\SqlServerA2SExtensions Module\bin\Release\SqlServerA2SExtensions.dll&#39;

References to include (excluding framework assemblies):
    None
SHFB: Warning BE0062: No XML comments files found.  The help file will not contain any member comments.
</buildStep>
`

**Comment by EWSoftware** [comment]
I haven't added any support for *.sqlproj* files specifically but if it's a flavored project type (i.e. a version of a C# or VB.NET project) that's probably why it's able to parse it and find the assembly.  Assuming it's like other C#/VB.NET projects, you need to enable the option in the SQL project properties to generate the XML comments file.  As long as SHFB can find the property in the project containing the XML comments filename it should pick it up and use it.

**Comment by lucvdv** [comment]
Thanks, that was it.
'Generate XML documentation file' seems to be off by default for SQL projects, while the default is on for regular projects.
