### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by griggsrl** [EWSoftware/SHFB#309]
Hi, trying to set up a new computer and installing all my dev tools. We currently use version 2015.10.10.0 of SHFB so that's what I'm installing currently.

During the installation of the Visual Studio package an error pops up: "Unexpected exit code returned from VSIX installer trying to uninstall any prior version of the package: 1002"
See the attached screenshot also.

![sfhb-error](https://cloud.githubusercontent.com/assets/3331954/16160867/196917d2-3490-11e6-912a-30d1062777be.PNG)

I've got VS2013 Pro and 2015 Enterprise installed and no prior versions of SHFB have been installed on this machine. I've tried running the install as administrator and it doesn't seem to help. 

Any ideas?

**Comment by EWSoftware** [comment]
That issue has been fixed.  Download the latest release or redownload the 2015.10.10.0 installer.

**Comment by griggsrl** [comment]
I had downloaded a fresh copy of the 2015.10.10.0 installer so not sure why it still had that problem. Oh well.

Anyway, downloaded the latest version and it seemed to install correctly so I'll have to get the rest of my team updated also. Thanks for quick response.
