### ISSUE TITLE
New UWP issue Error BE0056

### ISSUE THREAD

**Issue by mjmeans** [EWSoftware/SHFB#310]
SHFB: Error BE0065: BUILD FAILED: A numeric comparison was attempted on "$(TargetPlatformMinVersion)" that evaluates to "10.0.10586.0" instead of a number, in condition "'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'".  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)...

The project is a Windows Runtime Component targeting Universal Windows version 10.0 Build 10586 with min version set to 10.0 Build 10240.

This is using SHFB version 2016.5.28.0 and Visual Studio Community 2015 version 10.0.25123.00 Update 2.

**Comment by EWSoftware** [comment]
Please attach an example project that demonstrates the issue.

**Comment by EWSoftware** [comment]
No reply so closing.  If you can supply an example as requested, feel free to reopen.

**Comment by mumford** [comment]
I just ran into this same issue and I haven't found a fix for it yet. I've attached a simple project that reproduces the problem.

[doc-test.zip](https://github.com/EWSoftware/SHFB/files/642870/doc-test.zip)

**Comment by EWSoftware** [comment]
See issue #376
