### ISSUE TITLE
Trying to build .chm with framework version 4.6.1, however generating reflection refers to 4.0.30319

### ISSUE THREAD

**Issue by michelebryk** [EWSoftware/SHFB#312]
Trying to build .chm with framework version 4.6.1, however "Generating Reflection Information" refers to 4.0.30319. This should be 4.6.1, both are installed on machine.

**Comment by EWSoftware** [comment]
Please be more specific.  Are you getting an error?  Can you post the relevant part of the build log?

**Comment by EWSoftware** [comment]
No reply so closing.  If you can provide more info, feel free to reopen it.
