### ISSUE TITLE
Conceptual Markup doesn't show IFRAME content using same URL reference

### ISSUE THREAD

**Issue by AcousticGuitar** [EWSoftware/SHFB#313]
Given this xml for a conceptual topic, the code tag finds the SomeContent.html and displays it as code.  This proves the address is correct.  If I attempt to insert the same address in an IFrame using the src attribute with the same address, it won't display the content as a web page. 
```
    <section address="Section1">
      <title>Optional section title</title>
      <content>     
        <code language="html" source="Content\SomeContent.html"></code>
        <para>
          <markup>
            <iframe src="Content\SomeContent.html"></iframe>
          </markup>
        </para>         
      </content>
    </section>
```

I've tried the following with no luck

```
 <iframe src=".\Content\SomeContent.html"></iframe>
 <iframe src="..\Content\SomeContent.html"></iframe>
 <iframe src="..\.\Content\SomeContent.html"></iframe>
```

How does one show content in an IFRAME using the MAML markup tag?

Please advise..

**Comment by AcousticGuitar** [comment]
I found the root cause of this issue.  I had created HTML content in other folders and dropped it into the project's back end folder.  The code comment is ok with this and looks us the content even if it's not included in the project.  To get the other stuff to show it has to be included in the project with the build property set to "Content".  doh!

**Comment by EWSoftware** [comment]
Assuming your HTML file is included in the project in the *.\Content* folder and has it's build action set to `Content`.  It should work with a relative path of *..\Content\SomeContent.html*.   Remember that for viewing the end result, the path is relative to the *.\html* folder.  For building, code elements use a path relative to the project folder.

Examples (works with Help 1 and Website output):
Sample conceptual topic:

``` XML
<?xml version="1.0" encoding="utf-8"?>
<topic id="0387f4c9-0675-4fbd-b7e6-a7d0e7fe0109" revisionNumber="1">
	<developerConceptualDocument xmlns="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink">
		<introduction />

		<section>
			<content>
				<markup>
					<iframe src="..\Content\SomeContent.html"></iframe>
				</markup>
			</content>
		</section>

		<relatedTopics />

	</developerConceptualDocument>
</topic>
```
SomeContent.html

``` XML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>New Page</title>
</head>

<body>
	<strong>This is in an IFrame</strong>
</body>

</html>
```

Project layout:
![image](https://cloud.githubusercontent.com/assets/10552523/16430281/b7b171f8-3d2f-11e6-94b7-eee52044da9f.png)

**Comment by EWSoftware** [comment]
I was just finishing composing the reply when you close the issue.  Glad you found the cause.

**Comment by AcousticGuitar** [comment]
Thanks Eric;
  I’m sorry for the post actually, but now I know that the CODE MAML seeks files not in the project whereby html markup must have the content in the project.  I should have known that… I feel stupid!!!! But hey….


  Anyway thanks so much for your support on this product.  I recently checked out the DOC FX which looks promising but there still a few kinks there.

On a side note, I’ve really been diving in deeply to functional programming styles (a bit late) but am doing it in C# only.  My life had changed!  It’s a great way to create massive helper functions!

John Peters

**Comment by AcousticGuitar** [comment]
Thanks Eric your excellent help is much appreciated out here.
