### ISSUE TITLE
Can't add multiple code sections in a tabbed way

### ISSUE THREAD

**Issue by vivelys** [EWSoftware/SHFB#315]
Hello,
I would like to know if it is possible to display two (or more) code snippets in the same way the syntax is displayed.
I mean : I have 3 pieces of code (Http Request, Http Response and Formated JSon Response) and all I can have is code displayed one below the other.

```
<code title="Request">
...
</code>
<code title="Response">
...
</code>
<code title="Formated Json response">
...
</code>

```
Thank you.

**Comment by EWSoftware** [comment]
No, grouping doesn't support what you are trying to do.  Its purpose is to keep common examples for multiple unique languages together in a group similar to the syntax section.  Snippets with a title such as in your example automatically get separated into a standalone group regardless of their associated language.  Snippets with a defined language and no title are grouped and sorted based on the syntax generator language definition.  If multiple snippets are found with the same language they are bumped to a new group.  As such, you could have two examples for C# and VB and each would be grouped into two tabbed sets each containing a C# and VB tab.  Selecting a tab keeps the syntax section and related code snippets in synch with the selected language.

**Comment by vivelys** [comment]
That's what I thought.
:(
