### ISSUE TITLE
Error thrown when namespace grouping is enabled without a root container

### ISSUE THREAD

**Issue by swirlywonder** [EWSoftware/SHFB#316]
When I attempt to build website documentation (VS2013) with namespace grouping but without a root container, I receive the following warnings and error:

> BuildAssembler : warning : SharedContentComponent: [G:] Missing shared content item. Tag: 'include'; Id:'topicTitle_'. [...\Working\BuildTopics.proj]
> BuildAssembler : error : SharedContentComponent: [G:] Error replacing item.  Root document element encountered. [...\Working\BuildTopics.proj]

I made sure that all plugins and components were disabled. The following two settings are sufficient to produce the error.

- Include root namespace container : Disabled
- Enable namespace grouping if supported : Enabled

Note: Disabling the root namespace container does work as expected when a root namespace is used.

**Comment by EWSoftware** [comment]
It's a problem with the presentation styles and is fixed for the next release.  Currently, they aren't handling the root group topic correctly.
