### ISSUE TITLE
SHFB: Error BE0065: BUILD FAILED: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by shrutishinde790** [EWSoftware/SHFB#32]
this error arised after build complete require guidance to get rid of it please help

**Comment by EWSoftware** [comment]
In which build step did it occur?  What's the last part of the build log prior to it failing?

**Comment by shrutishinde790** [comment]
this the whole build log -----------
--------------------
[Sandcastle Help File Builder, version 2014.11.22.0]
Creating output and working folders...
Finding tools...
The Sandcastle tools are located in 'C:\Program Files\EWSoftware\Sandcastle
Help File Builder\'
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in 'C:\Program Files\HTML Help Workshop\'
Locating components in the following folder(s):
   C:\Documents and Settings\Admin\My Documents
Using presentation style 'VS2013' located in 'C:\Program
Files\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013'
Loading and initializing plug-ins...
Lightweight Website Style Version 2014.11.22.0
Copyright © 2006-2014, Eric Woodruff, All Rights Reserved
Portions Copyright © 2014, Sam Harwell, All Rights Reserved
-------------------------------
Clearing working folder...
-------------------------------
Validating and copying documentation source information
Source: D:\Shruti\SDCC_CBSWEB\CBSUI\CBSUI.csproj
    Found project 'D:\Shruti\SDCC_CBSWEB\CBSUI\CBSUI.csproj'

Parsing project files
    Found assembly 'D:\Shruti\SDCC_CBSWEB\CBSUI\bin\CBSUI.dll'

References to include (excluding framework assemblies):
    AjaxControlToolkit, Version=3.0.20820.23153, Culture=neutral,
PublicKeyToken=28f01b0e84b6d53e, processorArchitecture=MSIL
    CBSReports_Accounts, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_Bills, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_Clearing, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_DailyReports, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_DDPayable, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_Deposits, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_FinalReports, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_General, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_HoAccounts, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_HoConsolidation, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_HoInvestment, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_HoLoans, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_HoShares, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_HoTDL, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_Interest, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_InwardOutward, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_Karkhana, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_LoanReports, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_MiscMasters, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_MISReports, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_Pigmy, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    CBSReports_SchoolSalary, Version=1.0.0.0, Culture=neutral,
processorArchitecture=MSIL
    Microsoft.Office.Interop.Excel, Version=12.0.0.0, Culture=neutral,
PublicKeyToken=71e9bce111e9429c
    Microsoft.Practices.EnterpriseLibrary.Common, Version=5.0.414.0,
Culture=neutral, processorArchitecture=MSIL
    Microsoft.Practices.EnterpriseLibrary.Data, Version=5.0.414.0,
Culture=neutral, processorArchitecture=MSIL
    Microsoft.Practices.EnterpriseLibrary.ExceptionHandling,
Version=5.0.414.0, Culture=neutral, processorArchitecture=MSIL
    Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging,
Version=5.0.414.0, Culture=neutral, processorArchitecture=MSIL
    Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.414.0,
Culture=neutral, processorArchitecture=MSIL
    Microsoft.Practices.EnterpriseLibrary.Logging.Database,
Version=5.0.414.0, Culture=neutral, processorArchitecture=MSIL
    Microsoft.Practices.EnterpriseLibrary.Security, Version=5.0.414.0,
Culture=neutral, processorArchitecture=MSIL
    Microsoft.Practices.ServiceLocation, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Microsoft.Practices.Unity, Version=2.0.414.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Microsoft.Practices.Unity.Interception, Version=2.0.414.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
    Microsoft.ReportViewer.WebForms, Version=9.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
    SDCC_CBSReports_General, Version=0.0.0.0, Culture=neutral,
processorArchitecture=MSIL

Copying XML comments files
    D:\Shruti\SDCC_CBSWEB\CBSUI\bin\CBSUI.xml -> C:\Documents and
Settings\Admin\My Documents\Help\Working\CBSUI.xml
-------------------------------
Generating shared content files (en-US, English (United States))...
    Last step completed in 00:00:00.3906
-------------------------------
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00.5938
-------------------------------
Generating reflection information...
[C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe]
Build started 17/03/2015 12:35:09 PM.
Project "C:\Documents and Settings\Admin\My
Documents\Help\Working\GenerateRefInfo.proj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\Debug\".
GenerateRefInfo:
  MRefBuilder (v2014.11.22.0)
  Copyright c 2006-2014, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2014, Eric Woodruff, All Rights Reserved.
  Loaded 1 assemblies for reflection and 35 dependency assemblies.
  Wrote information on 75 namespaces, 1045 types, and 31861 members
  Copying file from "reflection.org" to "reflection.all".
  XslTransform (v2014.11.22.0)
  Copyright c 2006-2014, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2014, Eric Woodruff, All Rights Reserved.
  Applying XSL transformation 'C:\Program Files\EWSoftware\Sandcastle Help
File Builder\ProductionTransforms\MergeDuplicates.xsl'.
Done Building Project "C:\Documents and Settings\Admin\My
Documents\Help\Working\GenerateRefInfo.proj" (default targets).

Build succeeded.

Time Elapsed 00:02:32.17
    Last step completed in 00:02:33.2031
-------------------------------
Transforming reflection output...
[C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe]
Build started 17/03/2015 12:37:42 PM.
Project "C:\Documents and Settings\Admin\My
Documents\Help\Working\TransformManifest.proj" on node 1 (default targets).
TransformManifest:
  XslTransform (v2014.11.22.0)
  Copyright c 2006-2014, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2014, Eric Woodruff, All Rights Reserved.
  Applying XSL transformation 'C:\Program Files\EWSoftware\Sandcastle Help
File Builder\\ProductionTransforms\ApplyVSDocModel.xsl'.
  Copying file from "reflection.xml" to "reflection.nofilenames".
  XslTransform (v2014.11.22.0)
  Copyright c 2006-2014, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2014, Eric Woodruff, All Rights Reserved.
  Applying XSL transformation 'C:\Program Files\EWSoftware\Sandcastle Help
File Builder\ProductionTransforms\AddFilenames.xsl'.
  XslTransform (v2014.11.22.0)
  Copyright c 2006-2014, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2014, Eric Woodruff, All Rights Reserved.
  Applying XSL transformation 'C:\Program Files\EWSoftware\Sandcastle Help
File Builder\ProductionTransforms\ReflectionToManifest.xsl'.
Done Building Project "C:\Documents and Settings\Admin\My
Documents\Help\Working\TransformManifest.proj" (default targets).

Build succeeded.

Time Elapsed 00:46:07.78
    Last step completed in 00:48:31.0938
-------------------------------

SHFB: Error BE0065: BUILD FAILED: Exception of type
'System.OutOfMemoryException' was thrown.

**Comment by shrutishinde790** [comment]
hi Eric,
          i would like to know where and how should be the comments added
in a program so tat the sandcastle will fetch it to display the description
in the help file. please guide its important.

thank you.

**Comment by EWSoftware** [comment]
Check the working folder, typically .\Help\Working\ under the project folder unless you changed it in the project settings.  Look for reflection.xml.  How big is it?  Chances are that it's just too big for the build engine to load and parse.

You've got a single assembly with 75 namespaces, 1045 types, and 31861 members.  That's a significant number for several assemblies let alone one.  I'd suggest using the API filter to remove unwanted elements to see if you can get the size down but since it has to create the reflection data the same way and load the file to find the members, you're probably still out of luck.

If you've got a 64-bit system with more memory, you may give that a try.

**Comment by shrutishinde790** [comment]
hi Eric,
         Thank you for the reply now i have a different problem please
guide, i have a project where i have added xml comment to a cbsui.csproj
which could not build the help file due to some exception but yes the dal
and bll file of my project were build the problem is i have written the
summary i.e description above every class in <summary> tags but are not
visible in the help file how does sandcastle exactly fetches these xml
comments can u please guide.As the description is the main thing that needs
to be viewed in the help file.Please reply as it is very urgent.


Thank you.

**Comment by EWSoftware** [comment]
As long as the class is showing up in the help file, the comments should as well.  If they're not, typically you've either not enabled the option to generate the comments, not rebuilt the project to get an up to date XML comments file, or you're using a different configuration (Debug vs Release) that isn't up to date.  The build log will tell you which XML comments files are being used or if one was not found.  If found, you can open them to see if the member comments are in it.  You can also do Rebuild All to make sure everything is up to date.

**Comment by shrutishinde790** [comment]
Hi Eric,
           Thank you for your valuable reply.
regarding the help file for a project with 75 namespaces i could not divide
the program so is there anything else i can do to have a help file build
for it do suggest .


Thank you.

**Comment by EWSoftware** [comment]
If you've got a 64-bit system with more memory, you may give that a try.  Other than that, you're probably out of luck.

**Comment by shrutishinde790** [comment]
Hi Eric,
          i would like to know the print options for the help file
generated though sandcastle in wat format it will print like my boss asked
me to first view the file tat will be generated i clicked the print option,
i selected print the topic selected, and then selected a printer and
enabled the print to file option, then i saved the file type as .prn but it
is not opening, so i saved it in .chm format but  it is still not opening
please guide as what should be done to get a proper print of help-file.

reply its urgent.

Thank You.

**Comment by EWSoftware** [comment]
What ever options are available in the viewer for Help 1, Help 2, and MS Help Viewer are what's available.  For website output, it's the print option in whatever browser you're using.  If you generate an Open XML document, you can open it in something like Microsoft Word and print part or all of it from there.

**Comment by shrutishinde790** [comment]
Hi Eric,
           I am using sandcastle help file builder it is running great but
the problem now i have occurred is this way i have built my project and
after adding the documentation sources i.e the .dll and .xml files there is
a part pf project which doesn't shows the comments added as the comments
are seen in the project its like its not fetching the comments given to
some files can u please help me on this.

Thank you.

**Comment by EWSoftware** [comment]
If comments aren't showing up it's either picking up the wrong comments files (Debug vs. Release for example) or the XML comments files are not up to date.  Check the build log to see which XML comments files its using and then check those files to be sure the content you are expecting to find is actually there.  You may just need to force a full rebuild to regenerate the comments files.

**Comment by shrutishinde790** [comment]
Hi Eric,
         What does this warrning means and how to reslove it BuildAssembler
: warning : ResolveReferenceLinksComponent:
[T:BLL.Balance.HoCons_GlTypeBalance] Unknown reference link target
'T:DAL.Balance.HoCons_GLTypeBalance'. [C:\Documents and Settings\Admin\My
Documents\Help\Working\BuildReferenceTopics.proj]


Thank You.

**Comment by EWSoftware** [comment]
That can occur when you've got a type derived from something in a reference assembly.  Since it isn't documented, it doesn't know from where to get the reference information to create a link to the related topic.  You can ignore these warnings for the most part.  If you find them bothersome, you can use the Additional Reference Links plug-in to generate reference link information to suppress the warnings.  See the plug-in's help topic for details.

**Comment by shrutishinde790** [comment]
Hi Eric,
          My machine configuration i.e its has 2 gb ram,x86 processor then
y does the error occurs as exception out of memory.

Thank You.

**Comment by EWSoftware** [comment]
Already asked and answered earlier in this thread: https://github.com/EWSoftware/SHFB/issues/32#issuecomment-82556529

**Comment by shrutishinde790** [comment]
Hi Eric,

I run the program in 64 bit and 4gb environment and it run properly thank
you, the help file has been built appropriately.

Thank you.
