### ISSUE TITLE
Custom content in OpenXml

### ISSUE THREAD

**Issue by binpick** [EWSoftware/SHFB#320]
Hi,

i created a custom OpenXml presentation style where i would like to add a predefined title page. That is a snippet i am including in the /document template. Basically, the title page is included but that page/snippet contains elements with text, e.g.:

```xml
...
<wp:positionH relativeFrom="page">
<wp:align>center</wp:align>
</wp:positionH>
<wp:positionV relativeFrom="page">
<wp:posOffset>3629025</wp:posOffset>
</wp:positionV>
...
```

Now the problem is that when BuildOpenXmlFile is executed, there is a method WrapStrayElementNodes that surrounds textual elements with paragraphs and ranges. The result looks as foolows and yields to an invalid OpenXml document:

```xml
...
<wp:positionH relativeFrom="page">
              <wp:align>
                <w:p>
                  <w:r>
                    <w:t xml:space="preserve">center</w:t>
                  </w:r>
                </w:p>
              </wp:align>
            </wp:positionH>
            <wp:positionV relativeFrom="page">
              <wp:posOffset>
                <w:p>
                  <w:r>
                    <w:t xml:space="preserve">3629025</w:t>
                  </w:r>
                </w:p>
              </wp:posOffset>
```

Is it possible to make that WrapStrayElementNodes method optional? Or is there good way to include snippets in OpenXml format?

Regards

**Comment by EWSoftware** [comment]
The method is required.  If not, stray text can cause the resulting document to appear corrupted.  In this case, I think the best solution is to add the `align` and `posOffset` elements as ones that it ignores if they are the parent of the text.
