### ISSUE TITLE
An attempt was made to set a read-only or ignored property: CONFIGURATION   Value: Release 

### ISSUE THREAD

**Issue by aragon321** [EWSoftware/SHFB#321]
Hi,
I'm trying to implement the documentation generation into our build process. 
Therefore we created a Documentation Solution with SHFB Visual Studio Integration Package. It works well if I start building the Solution with msbuild directly from commandline (using buildprocess account) . If the buildserver starts the generation task i get the following error: 
##[error]An attempt was made to set a read-only or ignored property: CONFIGURATION   Value: Release ---> SandcastleBuilder.Utils.BuilderException: An attempt was made to set a read-only or ignored property: CONFIGURATION   Value: Release

Attached you can find the whole logfile.

What could be the reason for this behaviour?

[4_Sandcastle Documentation erstellen.txt](https://github.com/EWSoftware/SHFB/files/393468/4_Sandcastle.Documentation.erstellen.txt)

**Comment by aragon321** [comment]
I found the problem. 
The property selection in LoadProperties() method (line 1773-1847) had not been caseinsenitive.
Attached you can find the fixed version of the SandcastleProject.cs.
Perhaps you could fix this for future versions.

[SandcastleProject.cs.txt](https://github.com/EWSoftware/SHFB/files/396151/SandcastleProject.cs.txt)

**Comment by EWSoftware** [comment]
Thanks.  I'll get it fixed for the next release.

**Comment by bugedone** [comment]
Is this fix likely to be released to NuGet soon?

**Comment by EWSoftware** [comment]
I plan on publishing the next release this weekend.  The NuGet packages will be updated then as well.
