### ISSUE TITLE
Adding 3rd party library reflection information to global configuration

### ISSUE THREAD

**Issue by maoserr** [EWSoftware/SHFB#326]
Hi, I'm new to this tool and I've been trying to figure out a way to suppress the 7000+ warnings from Unknown reference link targets from using 3rd party libraries. I saw the "Additional Reference Links" plugin, but it could not compile all my 3rd party libraries because they are too big. In any case, I would like to find a way to include these libraries in the global configuration if at all possible because even if I could figure out a way to build the 3rd party libraries, it would likely take a long time.

I was able to use the MRefBuilder.exe program and XslTransform.exe program to general reflection xml and manifests, but I'm unclear on how to add this to the configuration files.

For MS help files, I tried adding to "C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013\Configuration\BuildAssembler.config" file 

Under  `<component id="Resolve Reference Links Component">` tag, I added
```
<targets base="{@FrameworkReflectionDataFolder}" recurse="true" files="*.xml" type="{@HtmlSdkLinkType}" id="FrameworkTargets">
										{@ReferenceLinkNamespaceFiles}
</targets>

```
And also tried
`<targets files="Libraries.xml" type="Local" id="None" />`

But it seemed to not have any effect, is this possible? What would be the best way to suppress these warnings on a global level if possible?

Thank you

**Comment by EWSoftware** [comment]
I suggest writing a [plug-in](http://ewsoftware.github.io/SHFB/html/a14e026e-642f-4ce6-9506-341e57cc3d1f.htm).  That way, you don't have to change the presentation style files.  With it, you can handle the `CreateBuildAssemblerConfigs` step and add your additional reference link files to the Resolve Reference Links Component configuration at build time.  You'd need to add a `targets` element something like:

``` XML
    <targets base="C:\PathTo\MyRefelectionFiles\" recurse="true" files="*.xml" type="None" />
```

Note that there are multiple copies of the component in the configuration file, one for each potential output format.  You need to find each and add the `targets` element to them.
