### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by hudsonphilipe** [EWSoftware/SHFB#328]
1- SHFB: Error BE0065: BUILD FAILED: Bad Length. (Exception from HRESULT: 0x80090004) 
2- Runtime Error  (R6034)

the SHFB can't load the style.

**Comment by EWSoftware** [comment]
Unfortunately, that's not much to go on.  The only info I can find about error R6034 is something to do with the Visual C++ runtime which SHFB doesn't use.  I'd suggest uninstalling SHFB, downloading the latest release, install that and try again.  Also, try it on another PC.  If it works there, it could be an issue with the PC.

**Comment by hudsonphilipe** [comment]
I have a project("SandcastleDemo.shfbproj") save on my pc and run without problems but if I try create a new or just open the SHFB I recived a error saying "No valid syntax generators found" and "No valid presentation styles found".

The "solution" a copy the project("SandcastleDemo.shfbproj") and edit for what a need and run without problem

**Comment by EWSoftware** [comment]
Do you have the system environment variable SHFBROOT pointing to the right location?  Sorry, but that last sentence makes no sense.
