### ISSUE TITLE
Sandcastle Help File Builder generate API reference lowercase urls

### ISSUE THREAD

**Issue by dessyordanova** [EWSoftware/SHFB#330]
Hello,

After some research, I couldn't find how to control the URLs for the generated API. We need to have lowercase URLs for our API documentation. Is there any setting that I can use? Thank you in advance.

**Comment by EWSoftware** [comment]
There is no guarantee or option to specify that all URLs will be in upper or lowercase.

**Comment by dessyordanova** [comment]
Hello again,

after debugging the sandcastle source code, I have found that the build uses the AddFilenames.xsl to generate the names of the HTML files considering the NamingMethod option. We need to modify the C# code for generating the name by just adding "ToLower()" for the MemberName case.  Thus, the URLs for our API will be always with lower case. Is there an easy way to specify what AddFilenames.xsl to be used (or a custom one) or creating a plugin to modify the file on the fly is the only option? Thank you in advance.

**Comment by EWSoftware** [comment]
You can [create a plug-in](http://ewsoftware.github.io/SHFB/html/a14e026e-642f-4ce6-9506-341e57cc3d1f.htm) that runs before the `TransformReflectionInfo` build step that modifies the *TransformManifest.proj* file in the working folder to substitute the name of the XSL transformation that you want to use.

If you add conceptual content to the help file (MAML topics).  Just make sure the IDs in each topic are in lower case.  Those are used to name the conceptual topics.
