### ISSUE TITLE
Build Fails on a Non-Existent Topic "G:"

### ISSUE THREAD

**Issue by KenCox** [EWSoftware/SHFB#332]
The reflection process seems to be finding phantom empty members in my assemblies. At build time, these phantoms are causing a failure. Does it have anything to do with the assemblies being protected? Using the latest release.

Thanks,

Ken

 BuildAssemblerCore: Building topic G:
BuildAssembler : warning : SharedContentComponent: [G:] Missing shared content item. Tag: &#39;include&#39;; Id:&#39;topicTitle_&#39;. [C:\AuctionWorxAPI\v3.0\SandcastleHelpFileBuilder\AuctionWorx.v3.0\AuctionWorx.v3.0\Help\Working\BuildTopics.proj]
BuildAssembler : warning : SharedContentComponent: [G:] Missing shared content item. Tag: &#39;include&#39;; Id:&#39;topicTitle_&#39;. [C:\AuctionWorxAPI\v3.0\SandcastleHelpFileBuilder\AuctionWorx.v3.0\AuctionWorx.v3.0\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [C:\AuctionWorxAPI\v3.0\SandcastleHelpFileBuilder\AuctionWorx.v3.0\AuctionWorx.v3.0\Help\Working\BuildTopics.proj]
**BuildAssembler : error : SharedContentComponent: [G:] Error replacing item.  Root document element encountered.** [C:\AuctionWorxAPI\v3.0\SandcastleHelpFileBuilder\AuctionWorx.v3.0\AuctionWorx.v3.0\Help\Working\BuildTopics.proj]

**Comment by EWSoftware** [comment]
It's a problem with the presentation styles not handling the root topic when the root namespace container option isn't enabled.  Turn it on to work around the issue.  It's fixed for the next release due out in a few weeks (see also #316 and #323).
