### ISSUE TITLE
Copy to Clipboard not working properly

### ISSUE THREAD

**Issue by SmartBuster** [EWSoftware/SHFB#333]
When creating chm/website output a "copy" link is created to code snippets.

This works well for chm but does not work well for others.
Edge & Chrome show this link at all.
IE 11 shows a security warning for each page
Firefox throws an alert and asks to change a config setting (which for me even does not work, possibly due to the latest security changes. I am using Firefox 48)

I took a quick look at the sources and found outdated clipboard code for Firefox.
More recent documentation of clipboard access is [here] (https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Using_the_clipboard)
Beside that the test for Chrome is done by checking the user agent and not by probing any features.

Possibly a including a cross browser solution like [clipboardjs] (https://clipboardjs.com/) might help or a configuration option to disable copy to clipboard at all when creating website output.

**Comment by EWSoftware** [comment]
The existing behavior and whether the link is visible or not is a limitation of the current code.  I've got the cliboardjs code implemented for website output.  It doesn't work in Help 1 and  MS Help Viewer so for those two formats, it falls back to the old code which does work in them.

**Comment by SmartBuster** [comment]
Many thanks for the fast fix!
