### ISSUE TITLE
Enable namespace grouping is not working in this release?

### ISSUE THREAD

**Issue by hulinning2** [EWSoftware/SHFB#336]
If I do not enable this option then I can create help file without
error. It does not happen in the previous version.

I got this error at the end:
  BuildAssemblerCore: Building topic G:
BuildAssembler : warning : ShowMissingComponent: [G:] Missing <summary> documentation [..\V1.0.0.0\Doc2\Help\Working\BuildTopics.proj]
BuildAssembler : warning : SharedContentComponent: [G:] Missing shared content item. Tag: 'include'; Id:'topicTitle_'. [..\V1.0.0.0\Doc2\Help\Working\BuildTopics.proj]
BuildAssembler : warning : SharedContentComponent: [G:] Missing shared content item. Tag: 'include'; Id:'topicTitle_'. [..\V1.0.0.0\Doc2\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [..\V1.0.0.0\Doc2\Help\Working\BuildTopics.proj]
BuildAssembler : error : SharedContentComponent: [G:] Error replacing item.  Root document element encountered. [..\V1.0.0.0\Doc2\Help\Working\BuildTopics.proj]
  CopyFromIndexComponent: "reflection" in-memory cache entries used: 3 of 15.
  CopyFromIndexComponent: "comments" in-memory cache entries used: 2 of 30.
Done Building Project "..\V1.0.0.0\Doc2\Help\Working\BuildTopics.proj" (default targets) -- FAILED.

Thanks for helping me.

**Comment by EWSoftware** [comment]
Already reported and fixed for the next release (#316, #323, and #332).  Enable the Root Namespace Container option to work around it for the time being.
