### ISSUE TITLE
Documenting C++ tracking references

### ISSUE THREAD

**Issue by mozzis** [EWSoftware/SHFB#337]
I have functions in my project of the form:

```
bool foo(String^ a, String^ b, [Out]Object^% ret);
bool foo(String^ a, [Out]Object^% ret);

```
If I write the XML doc comments for the version with the longest parameter list, they do show up in the output help files.
I would like to use <inheritdoc/> on the other versions:

```
/// <inheritdoc cref="foo(String^, String^, [Out] System::Object^%)" />
bool foo(String^ a, [Out]Object^% ret);
```

but this generates:

> SHFB(0,0): warning GID0002: No comments found for cref '!:foo(String^, String^, [Out] System::Object^112364456' on member 'M:Project.MyClass.foo(System.String,System.Object@)'

And no help document content is present for this method.
I can see from the warning that the “%” sign in the tracking reference ret is likely a problem, as I would expect since it is an XML reserved character. So I tried escaping it with:
```
/// <inheritdoc cref="foo(String^, String^, [Out] System::Object^&#37;)" />
bool foo(String^ a, [Out]Object^% ret);
```
but this just produces:

> SHFB(0,0): warning GID0002: No comments found for cref '!:foo(String^, String^, [Out] System::Object^108563368' on member 'M:Project.MyClass.foo(System.String, System.Object@)'

Taking my cue from the end of the warning, I also tried:

`/// <inheritdoc cref="foo(String^, String^, [In, Out]System::Object@)" />`

with the result:

> SHFB(0,0): warning GID0002: No comments found for cref '!:foo(String^, String^, [Out] System::Object@)' on member 'M:Project.MyClass.foo(System.String,System.Object@)'

Do you have any idea how to successfully use <inheritdoc/> with a C++/CLI tracking reference? There are quite a few functions with several permutations each that use them in our code.

**Comment by EWSoftware** [comment]
You shouldn't need the `[Out]` attribute in the ID.  They don't carry over into the IDs.  The '!:' prefix in the ID means that the C++ compiler couldn't resolve it to a valid reference when it wrote it to the XML comments file.  If removing the `[Out]` attribute doesn't fix it, see if you can use a standard `see` or `seealso` element to generate a link to the member.  Build your C++ project and take a look at the member comments in the XML comments file to see if it generated that link correctly.  That may help narrow down the syntax.

I seem to recall that the C++ compiler has problems generating `cref` links to things it hasn't seen yet (forward references).  You may be running into that here too.

As a last resort, take a look at the XML comments file and find the ID for the API member you are targeting.  Use that fully qualified name including the "M:" prefix.  That should stop the compiler trying to resolve it and just write it out literally.

**Comment by mozzis** [comment]
I was able to construct a working <inheritdoc/> phrase by copying the fully qualified reference for the parent function from generated the XML file.
Thank you for your help.
