### ISSUE TITLE
TFS build fails with "SandcastleHelpFileBuilder.targets" was not found" but NuGet package EWSoftware.SHFB is installed

### ISSUE THREAD

**Issue by lanthonyneville** [EWSoftware/SHFB#339]
I am attempting to build a solution containing a SHFB project on a TFS 2013 Build Server. The build server does not have any SHFB GUI installed.

The solution builds perfectly on my local PC running VS 2013, and which has the SHFB GUI installed.

To prepare for building the project via TFS I added the following NuGet packages:

- Sandcastle Help File Builder (Id: EWSoftware.SHFB) ..... the description of this implies it allows SHFB projects to be built on a build server without the SHFB tools installed

- .NET Framework Reflection Data Set (Id: EWSoftware.SHFB.NETFramework) .... I think this is the only reflection data set I need as I am just building a Help file for a C# class library.

However, the TFS build fails with this error:

_G:\Builds\Agents\.... long path to my project ....\Documentation.shfbproj (159): The imported project "G:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk._

I read elsewhere that this is because the SHFBROOT environment variable is missing, and this is created by installing the SHFB GUI. However, the TFS build server doesn't have this and the above NuGet package implies it doesn't need it.

What am I missing?

Thanks

**Comment by EWSoftware** [comment]
See the [NuGet ReadMe file](https://github.com/EWSoftware/SHFB/blob/master/NuGet/ReadMe.txt).  You also need to set the Component Path project project and add a conditional `SHFBROOT` project property so that the reflection data and tools can be found on the build server.

**Comment by lanthonyneville** [comment]
I have now made the 2 changes described, but I am getting the same error on build. My updated .shfbproj now has these 2 additions:
`    <ComponentPath>..\packages\</ComponentPath>`
(this is the right relative path to the nuget packages folder from the .shfbproj folder)
```
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <SHFBROOT Condition=" '$(SHFBROOT)' == '' ">$(MSBuildThisFileDirectory)..\packages\EWSoftware.SHFB.2016.5.28.0\Tools\</SHFBROOT>
  </PropertyGroup>
```
(this is the right relative path to the EWSoftware.SHFB package in the nuget packages folder)

**Comment by EWSoftware** [comment]
You probably need to edit the project file in a text editor and ensure that the SHFBROOT property is in the first property group and appears before the import that brings in the SHFB targets file.  If you added it through the User Defined property page, it probably added it after the import so it's not been seen early enough to get resolved before importing the SHFB targets.

**Comment by lanthonyneville** [comment]
OK, that helped - that particular error is gone.
But now there's a new build error:
SHFB: Project assembly does not exist: G:\Builds\Agents\17\ ... path ... \MyLibrary.dll

The SHFB project uses a reference to a .csproj file in the DocumentationSources:

```
    <DocumentationSources>
      <DocumentationSource sourceFile="..\Library\MyLibrary.csproj" />
    </DocumentationSources>
```

**Comment by EWSoftware** [comment]
Assuming they are part of the same solution, it's possible it's trying to build the help project before the documentation source assembly has been built.  You should be able to correct that by adding the same documentation source project as a reference under the References node in the SHFB project and setting its `ReferenceOutputAssembly` property to false.  That will allow MSBuild to determine that the SHFB project should be built after the documentation source project.

Note also that if the `OutDir` MSBuild property is set, that will override the documentation source's output folder when built on the build server.

**Comment by lanthonyneville** [comment]
Still not working, but thanks for your help so far! 

I looked at the build order and tried your suggestion, but the documentation source assembly was already definitely being built before the help file. I also checked that Copy Local was True on the added references.

Although I am not explicitly setting the OutDir, in a TFS build the output folder (i.e. OutDir) is automatically set to a "drop" folder (e.g. MySolutionName_20160919.3), not the usual "bin" folder.

Some of the log file from my build is below. It shows the doc source library being built first and output to obj\Release\MyLibrary.dll (presumably after this it gets copied to the drop folder). Then when the SHFB project starts building it is looking for bin\MyLibrary.dll

```
Build started 19/09/2016 12:13:46.
     1>Project "G:\Builds\Agents\17\DevelopmentSTP1\MySolution\src\MySolution.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "TfsBuild|Any CPU".
		 
		 (lots of details cut out)

       CoreCompile:
         C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /doc:bin\MySolutionLibrary.XML /define:TRACE /highentropyva+ /reference:"G:\Builds\Agents\17\DevelopmentSTP1\MySolution\src\External Libs\DataContext.dll" /reference:"G:\Builds\Agents\17\DevelopmentSTP1\MySolution\src\External Libs\Shared.dll" /reference:"G:\Builds\Agents\17\DevelopmentSTP1\MySolution\src\External Libs\Framework.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Runtime.Serialization.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.ServiceModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\MyLibrary.dll /subsystemversion:6.00 /resource: lots of resource files cut out"
     5>CoreBuildHelp:
         ValidatingDocumentationSources
     5>SHFB : error BE0040: Project assembly does not exist: G:\Builds\Agents\17\DevelopmentSTP1\MySolution\bin\MyLibrary.dll [G:\Builds\Agents\17\DevelopmentSTP1\MySolution\src\Documentation\Documentation.shfbproj]
         Failed
         Build details can be found in G:\Builds\Agents\17\DevelopmentSTP1\MySolution\src\Documentation\Output\LastBuild.log
     5>Done Building Project "G:\Builds\Agents\17\DevelopmentSTP1\MySolution\src\Documentation\Documentation.shfbproj" (default targets) -- FAILED.
	 
		 (lots of details cut out)

```

**Comment by EWSoftware** [comment]
I don't have a build server I can try to reproduce this on.  The best I can suggest is explicitly specifying the OutDir folder to see if the SHFB project picks it up.

**Comment by lanthonyneville** [comment]
I can try but I think setting the OutDir might mess up the way the build server outputs each build into a distinct drop folder. In a TFS build, OutDir seems to be set automatically to the drop folder.

Is there a way to set the documentation source DLL of the SHFB project dynamically? If I could set it to look in the OutDir of the source project, this might work.

**Comment by EWSoftware** [comment]
As far as I know OutDir is global to the build not specific to each project.
