### ISSUE TITLE
Is it possible to include a custom .targets file in a .shfbproj project file?

### ISSUE THREAD

**Issue by lanthonyneville** [EWSoftware/SHFB#340]
In all my regular C# projects I use a custom .targets file to ZIP binaries, release notes etc up into a package that I can easily distribute. So now I have a SHFB project I am attempting to do the same thing to ZIP up the .CHM file that is built.

In the same way that I do for the C# projects I edited the project file and added an import below the main .targets file as follows:
```
  <Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" />
  <Import Project="$(MSBuildProjectDirectory)\DocumentationBuild.targets" />
```

The DocumentationBuild.targets file is fairly simple and uses a ZIP task from MS Build Community Tasks (NuGet package). The ZIP task is triggered by `<Target Name="AfterBuild">`.

However, it looks like DocumentationBuild.targets is never run. There are no errors during the build. I have done all the usual things like restarting VS, and I have done this process dozens of times before with C# projects.

Do SHFB projects just not support custom .targets files?

**Comment by EWSoftware** [comment]
The target `AfterBuildHelp` should do what you want.
