### ISSUE TITLE
CHM is broken when I add 2 properties to an assembly

### ISSUE THREAD

**Issue by shibaev** [EWSoftware/SHFB#342]
We successfully use SHFB to build CHM and online documentation to our class library. However, at this week we detect really strange issue:
1) CHM file is successfully build and opened for some state of our source code. Here is the build log and resulting CHM file:
https://dl.dropboxusercontent.com/u/9287830/Help-ok.zip

2) Then we add 2 simple properties (text in "summary" tags does not matter) to some existing class (PdfPath):
```
/// <summary>
/// TODO
/// </summary>
public PdfBrushInfo Brush
{
    get { return null; }
}

/// <summary>
/// TODO
/// </summary>
public PdfPenInfo Pen
{
    get { return null; }
}
```

There is no other changes in the code.

3) Rebuild the project and CHM documentation.

=> CHM is build without errors. However file is 2 times larger than the one from step 1. And it can't be opened or decompressed:

> Cannot open the file: mk:@MSITStore:C:\<..path here..>\Docotic.Pdf.chm.

Here is the build log and resulting CHM file:
https://dl.dropboxusercontent.com/u/9287830/Help-error.zip

Checked the build on 2 different computers with Windows 10 - result is the same.

HTML files are correct (including new properties), so it might be a bug in CHM compiler, not in SHFB.
@EWSoftware I will appreciate if you take a look at this issue and hopefully advice a workaround. Thanks in advance!

**Comment by EWSoftware** [comment]
Based on the two build logs I don't see anything significant.  The help compiler output only differs in the topic and link counts so there's nothing obvious that accounts for the significant size difference.  What you could do is enable the build option that retains the working folder after the build.  Build the good one and save a copy of the working folder.  Then build the one that's failing and compare its working folder to the other to see if there's anything obviously different between the content that gets compiled into the help file.  If not, you may be running into a help 1 compiler issue.

It may not change anything but you might try downloading and reinstalling the HTML Help Workshop to see if it fixes anything.

**Comment by shibaev** [comment]
Thank you for your advices!

I compared working directories with WinMerge and did not find any interesting. Just two properties were properly added.
Re-installing of HTML Help Workshop does not help.

The bug is easily reproduced from HTML Help Workshop if I compile \Working\Output\HtmlHelp1\Help1x.hhp.
Probably the problem does not relate to SHFB, so I am closing this issue.

Let me know if you want to research this issue - I can send you "\Working\Output\HtmlHelp1" directory to reproduce.

**Comment by shibaev** [comment]
FYI - the problem disappeared when I added a new topic to the documentation.
