### ISSUE TITLE
Support of UltraHD resolutions

### ISSUE THREAD

**Issue by nZeus** [EWSoftware/SHFB#344]
Currently SandCastle doesn't support UltraHD resolutions and it is extremely hard to use it. E.g.:

![image](https://cloud.githubusercontent.com/assets/2727326/18815003/9e5e00ec-8323-11e6-9d90-85922eaba717.png)

**Comment by EWSoftware** [comment]
The latest release should look good up to 3840x2160 scaled up to 150%.   The property pages are all Windows Forms controls and scaling is the biggest issue.  Anything above 150% will cause clipping.  The settings I use I've found to work best across a wide variety of resolutions and scaling sizes but, as with all scaling options in Windows Forms, they aren't perfect.  Short of rewriting all of the controls to use WPF I don't think there's a good way of pleasing everyone with regard to the UI scaling.

The file designers such as for content layout and the topic preview tool window do use WPF controls so they should look fine since WPF handles scaling much better.  The property pages in Visual Studio don't support WPF controls as far as I know so that would mean doing some sort of odd hosting of a WPF control within a Windows Forms user control.  That might prove rather difficult.  I may take a look at it but I can't say when that might get done.

**Comment by nZeus** [comment]
I'm using 250% (this is recommended, and to use less than 200% is not the case - very hard to read text).
But just to experiment I changed scaling to 150%, and restarted - but still see problems with the UI:

![image](https://cloud.githubusercontent.com/assets/2727326/18818006/34329db8-836e-11e6-92db-6e19c8721ab3.png)

Strange that VS doesn't support WPF controls as it is written in WPF...

Is it possible to detect scaling setting and use it in the calculations for the UI?

**Comment by EWSoftware** [comment]
The AutoScaleMode property on forms and user controls is supposed to do that but it doesn't do it very well.  As I recall, if you use the Font setting, you've pretty much got to do all development work at 96DPI to get any kind of consistency but for me, that's was never feasible so I don't use it.  Google can help you find the details, there's plenty about it.  I just recently got a 27" 4K monitor and it's fine but if you're using a smaller screen such as on a tablet with a higher scaling factor, not so much I guess.

The Visual Studio UI is mostly WPF and hosts Windows Forms and WPF controls but at it's core it's still a native mode application with a lot of C++/COM.  Not all of its underlying interfaces have been updated to be all WPF.  Lower priority stuff I guess.  The interface for property pages interacts through a window handle (HWND) and setting the parent on the control to it.  It may be possible to host a WPF control but I'm not sure how difficult that may be.

**Comment by NerdyDuck** [comment]
I've got the same problem. Working on a 15" laptop with 4k resolution - madness, but this is a world where only superlatives sell. Using less than 250% scaling is not an option. But this seems to be a common problem. I just tried the project property pages of the Windows Installer XML (Wix) extension, and while it is not as scrambled as the pages of SHFB, it still doesn't look good. But maybe you can get some clues from their code on how to enhance the spacing. Well, for the time being I'll reserve changes on documentation for the times when I have display with a reasonable resolution attached.

**Comment by BernhardJ** [comment]
Hi

I had the same issue with my WinForms Applications on a Surface Book. The solution was a manifest.
For users, you can put a manifest with the correct name beside the exe. In this case: SandcastleBuilderGUI.exe.manifest (see attached file, the txt extension is for upload reason)
[SandcastleBuilderGUI.exe.manifest.txt](https://github.com/EWSoftware/SHFB/files/1339788/SandcastleBuilderGUI.exe.manifest.txt)

Content of the manifest file:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <windowsSettings> 
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">False</dpiAware> 
    </windowsSettings> 
  </application> 
</assembly>
```

For the developer, in the project, you can add the manifest an put the flag in there.
```
  <!-- Indicates that the application is DPI-aware and will not be automatically scaled by Windows at higher
       DPIs. Windows Presentation Foundation (WPF) applications are automatically DPI-aware and do not need 
       to opt in. Windows Forms applications targeting .NET Framework 4.6 that opt into this setting, should 
       also set the 'EnableWindowsFormsHighDpiAutoResizing' setting to 'true' in their app.config. -->
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
    </windowsSettings>
  </application>
```
