### ISSUE TITLE
Transform Args Do Not Escape HTML Characters

### ISSUE THREAD

**Issue by swirlywonder** [EWSoftware/SHFB#345]
In attempting to leverage the TransForm Args feature for custom presentation types, I am unable to pass html characters. These characters are properly encoded in the Sandcastle project file, however during compilation, these values are not passed to the sandcastle.config correctly.

For example, the TransformComponentArguments in the sandcastle .shfbproj file may look something like this.
`<Argument Key="myHtml" Value="This is &lt;i&gt;my&lt;/i&gt; html." />`

The generated sandcastle.config file during compilation of this project would look something like this.
`<argument key="myHtml" value="This is <i>my</i> html." />`

This would obviously break during the XmlDocument load of this config.

The same issue also occurs if I pass the value in through `<transform>` arguments in the presentation BuildAssembler.config.

I realize this usually wouldn't normally come up in the default presentation styles unless someone set the LogoFile to something like http://cdn.example.com/mylogo.png?width=100&height=75 (which would also break xml).

For my use case, I have 3 distinct themes for the documentation (Nightly Build, Pre-Release, and Production). I added the ability in my custom presentation style to add an optional build-specific "notification banner" displayed on all pages. For this example, Nightly Build and Pre-Release contain a warning and link back to the production version of the documentation which contain html markup.

Thanks for all your hard work in keeping this invaluable project active.

**Comment by swirlywonder** [comment]
During further testing to find a potential workaround, I discovered the following:

Input into BuildAssembler.config `<transform>` arguments:
`This is &lt;i&gt;my&lt;/i&gt; html.`

Will result in this in the sandcastle.config:
`<argument key="myHtml" value="This is <i>my</i> html." />`

Double escaping the input into BuildAssembler.config `<transform>` arguments:
`This is &amp;lt;i&amp;gt;my&amp;lt;/i&amp;gt; html.`

Will result in this in the sandcastle.config:
`<argument key="myHtml" value="This is &lt;i&gt;my&lt;/i&gt; html." />` which is correct.

I haven't tested this workaround in Transform Args in the project file, but this would require either double or triple escaping the values to make it work.

This is enough for me to get by but as you can guess editing and maintaining that string can get pretty awful. Correcting this issue would be a breaking change at this point but that's a pretty simple change for me if it comes to that. I would MUCH rather clean up my project file if I get the choice.

**Comment by EWSoftware** [comment]
The `TransformComponentArgument` constructor supports a version that takes an `XElement` for the content.  This will manage the value as an XML value with proper encoding.  You'll get a text area for editing the XML.  It's how the `languages` property is passed in for the syntax languages.  Using that should accomplish what you want without the encoding issues.  You'll need to handle the parameter as an XML nodeset in the XSL transformation but that shouldn't be an issue.

**Comment by swirlywonder** [comment]
Wow... thank you so much!

All it took was changing this in my BuildAssembler.config:
`<argument key="MyArg" value="{@MyProperty}" />`

To this:
`<argument key="MyArg">
{@MyProperty}
</argument>`

And then change my `<xls:value-of ...` to `<xsl:copy-of ...` in the xslt transform

I'm passing the value from a custom property so I can change it based on which build I choose. The project file is SO much better now... Thanks again!
