### ISSUE TITLE
Can't Build Helpfile by using the Microsoft.AspNetCore Libary

### ISSUE THREAD

**Issue by thiel-st** [EWSoftware/SHFB#346]
By Building a HelpFile for a Microsoft.AspNetCore Projekt it will came a error.
SHFB: Error BE0043: Unexpected error detected in last build step.

GenerateRefInfo:
  MRefBuilder (v2016.5.28.0)
  Copyright &#184; 2006-2016, Microsoft Corporation, All Rights Reserved.
  Portions Copyright &#184; 2006-2016, Eric Woodruff, All Rights Reserved.
  Loaded 11 assemblies for reflection and 149 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: Microsoft.AspNetCore.Routing.Abstractions (Microsoft.AspNetCore.Routing.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60) required by Microsoft.AspNetCore.Mvc.Core [.\Documentation\Help\Working\GenerateRefInfo.proj]

The Missing Assembly is a reference in the Projekt and is existing.

**Comment by EWSoftware** [comment]
I haven't used ASP.NET Core.  Can you attach an example so that I can duplicate the issue?

**Comment by EWSoftware** [comment]
Closing due to no reply.  Feel free to reopen if you can attach an example as requested.
