### ISSUE TITLE
Visual Studio Extensions creation error during install

### ISSUE THREAD

**Issue by ppatt1722** [EWSoftware/SHFB#348]
After uninstalling a prior version an install using SHFBInstaller_v2016.9.17.0.zip was attempted but it failed when trying to create the Vtudi on Extensions from .vsix package with the following message which apparently means there was an exception:

"Unexpected exist code returned from VSIX installer trying to uninstall any prior version of the package: 3001"

Presumably some of the bits were not cleaned up by a prior uninstall. On another machine I experienced Visual Studio templates that remained after an uninstall but I managed to delete them myself then install a new version of SHFB. However with the current problem we are stuck and unable to move forward with the install using SHFBInstaller_v2016.9.17.0.zip.

I'd be happy to supply any further doc you might need. I have exhumed the contents of the VSIX package and think I understand where all the installed files reside but see none that don't appear to be cleaned up by prior install.

Thanks for any help you might provide.

- Pat Pattillo

**Comment by EWSoftware** [comment]
It sounds like you've done this already but you can make sure it's uninstalled in Visual Studio by going to Tools | Extensions and Updates and making sure it isn't there.  If it is, remove it there and restart Visual Studio which should remove all the old files.

3001 is a generic catch-all VSIX error code.  You can try running the VSIX package manually.  Just go into the *.\InstallResources* folder and run the *SHFBVisualStudioPackage.vsix* file that you find there.  If it fails, it should give you the option to view the log file which should contain information about what failed.

Note that you need to run it as an administrator as it is installed for all users.  Prior to v2015.10.10, it was installed per-user so the location of the files has changed.  If you were using an earlier per-user version, that may be what's causing the problem.  Running it manually should let you install it.

**Comment by ppatt1722** [comment]
Beautiful. Many thanks Eric. We’ll give it a try. After looking into the .vsix file it seems like the only pieces to uninstall would be in :


·        c:\Program Files (x86)\EWSoftware for executables

·        c:\users\<username>\AppData\Local\Microsoft\VisualStudio\12.0 which seems mapped to same item and project templates as in next bullet

·        C:\Program Files (x86)\Microsoft Visual Studio 12.0 for extensions, item templates and project templates

Hopefully that is everything but I will try manual VSIX uninstall. It was a prior version that had been uninstalled, most likely not as administrator. Hopefully the uninstall of later version rather than repeat uninstall of the partially uninstalled prior version will still catch any remnants of early install of prior version.

Many thanks!

**Comment by EWSoftware** [comment]
The stuff in *C:\Program Files (x86)\EWSoftware* should be left.  That's part of the base SHFB package installed by the MSI installer.  The VSIX package makes use of those tools but doesn't install them.
