### ISSUE TITLE
How to exclude some class from documentation

### ISSUE THREAD

**Issue by WonderGnagno** [EWSoftware/SHFB#349]
Hi,
i've some classes that are public and i don't want them in my documentation.
is there a way to exclude some object?

Thanks

**Comment by EWSoftware** [comment]
You can use the [API Filter](http://ewsoftware.github.io/SHFB/html/7df16a60-f718-4b8f-bfa2-88c42906070c.htm) in the *Visibility* category of project properties to exclude types or members that you don't want included in the help file.
