### ISSUE TITLE
SHFB crashes when trying to build a documentation for Deedle

### ISSUE THREAD

**Issue by Svancara** [EWSoftware/SHFB#356]
SHFB crashes when I am trying to build help for Deedle [https://github.com/BlueMountainCapital/Deedle](url)  (Deedle.DLL)

My comp environment is in Czech so please try it yourself. 
Just add Deedle to the project and you will see.

Full Deedle in Visibility ends with this error: 
BuildAssembler : warning : ShowMissingComponent: [G:Deedle.Vectors] Missing &lt;summary&gt; documentation [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
  **BuildAssemblerCore: Building topic G:Deedle.Indices**
BuildAssembler : warning : ShowMissingComponent: [G:Deedle.Indices] Missing &lt;summary&gt; documentation [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]

  
I removed almost everything in the Visibility to find where the problem is. 
It starts to crash when "DataSegment" is included.

The error is  **BuildAssemblerCore: Building topic R:Project_Documentation** then.

This is a tail of the build window output:
===========================================

BuildAssembler : warning : ShowMissingComponent: [M:Deedle.DataSegment.GetKind``1(Deedle.DataSegment{``0})] Missing <param name="ds"/> documentation [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Deedle.DataSegment.GetKind``1(Deedle.DataSegment{``0})] Unknown reference link target 'T:Deedle.DataSegment`1'. [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Deedle.DataSegment.GetKind``1(Deedle.DataSegment{``0})] Unknown reference link target 'T:Deedle.DataSegmentKind'. [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   v SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   v SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

This is a tail of the log file:
===========================================

BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Deedle.DataSegment.GetKind``1(Deedle.DataSegment{``0})] Unknown reference link target &#39;T:Deedle.DataSegment`1&#39;. [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Deedle.DataSegment.GetKind``1(Deedle.DataSegment{``0})] Unknown reference link target &#39;T:Deedle.DataSegmentKind&#39;. [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
  BuildAssemblerCore: Building topic R:Project_Documentation
  Processed 77 topic(s)
  133 warning(s)
  CopyFromIndexComponent: &quot;reflection&quot; in-memory cache entries used: 4 of 15.
  CopyFromIndexComponent: &quot;comments&quot; in-memory cache entries used: 2 of 30.
  SaveComponent: Waiting for the document writer task to finish (26 Website API file(s) remaining)...
BuildAssembler : error : An unexpected error occurred trying to execute the BuildAssembler MSBuild task: System.AggregateException: Do&#231;lo k jedn‚ nebo vˇce chyb&#160;m. ---&gt; System.ArgumentException: Cesta obsahuje neplatn‚ znaky. [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.IO.Path.Combine(String path1, String path2) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Microsoft.Ddue.Tools.BuildComponent.SaveComponent.WriteDocuments() [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.Threading.Tasks.Task.Execute() [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    --- Konec trasov&#160;nˇ z&#160;sobnˇku pro vnit&#253;nˇ vějimku --- [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Microsoft.Ddue.Tools.BuildComponent.SaveComponent.Dispose(Boolean disposing) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v SandcastleBuilder.Components.MultiFormatOutputComponent.Dispose(Boolean disposing) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Microsoft.Ddue.Tools.BuildComponent.SwitchComponent.Dispose(Boolean disposing) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Sandcastle.Core.BuildAssembler.BuildAssemblerCore.ClearComponents() [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Sandcastle.Core.BuildAssembler.BuildAssemblerCore.Dispose(Boolean disposing) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Microsoft.Ddue.Tools.BuildAssemblerConsole.Main(String[] args) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Microsoft.Ddue.Tools.MSBuild.BuildAssembler.Execute() [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error : ---&gt; (Inner Exception #0) System.ArgumentException: Cesta obsahuje neplatn‚ znaky. [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.IO.Path.Combine(String path1, String path2) [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v Microsoft.Ddue.Tools.BuildComponent.SaveComponent.WriteDocuments() [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :    v System.Threading.Tasks.Task.Execute()&lt;--- [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj]
Sestavenˇ projektu E:\SandCastle\TestingDeedleProject\Help\Working\BuildTopics.proj (s věchozˇmi cˇli) bylo dokonźeno: CHYBA.

Sestavenˇ SE NEZDA&#252;ILO.

Uplynulě źas 00:00:05.96
    Last step completed in 00:00:06.0738
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   v SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   v SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>

**Comment by EWSoftware** [comment]
The F# compiler generates some odd member names containing the pipe character which isn't being accounted for when using the Member Name naming option (i.e. `DataSegment.|Complete|Incomplete`).  As a workaround, use the Guid or Hashed Member Name naming option instead.

Also, the Visual Basic and Visual Basic Declaration syntax generators don't handle some of the properties as they don't include a return type.  As a workaround, disable them by unchecking them in the Syntax Filters section in the Help File category of project properties.
