### ISSUE TITLE
Display Flags as binary

### ISSUE THREAD

**Issue by tightDev** [EWSoftware/SHFB#358]
It would be great if enumerations which have the flags attribute will be displayed as binary instead of decimal.

Like (now):
Value_1 = 1
Value_2 = 2
Value_3 = 4
Value_4 = 8
…
Better would be:
Value_1 = 1 << 0
Value_2 = 1 << 1
Value_3 = 1 << 2
Value_4 = 1 << 3
…

Specially for high bits the decimal values gets confusing.

**Comment by EWSoftware** [comment]
I'm don't think the left shift notation is much better.  Now you've got to do the left shift to figure out the numeric value.  Perhaps a hex or binary literal (0b001100) value might be better in addition to the integer value.

**Comment by tightDev** [comment]
For microcontroller I totally agree with you, but 0b is not supported, at least in VB.Net. Also this would be confusing for 64 Bit wide flags. But the code example I wrote does work, you can type it exactly this way and you instantly see which bit is set, no need to calculate the value. ;)

Maybe it is possible to specify the format individually? For example:
<Flags(), SHFB_NumberType(Shift)> MyFlags …
Could be decimal, hex, shift, binary. Or something inside of the xml documentation. Don't know if (and which) is possible for you.

**Comment by EWSoftware** [comment]
My point was that when looking at the help file, code doesn't help you figure out what the value is.  You've either got to run it or try to figure it out in your head.  When I'm looking at the docs, tell me what the value is, don't make me figure it out.  The numeric or binary literals are more useful in documentation.  I don't think I've ever seen flag values in code specified using bit shifts either, they're more commonly written as numeric or hex values.

Parameters passed to the presentation style can specify what values to show much like the existing property to show/not show the value.  No need for customized XML comments or attributes.

**Comment by tightDev** [comment]
For the most scenarios you are right, that's why I said optional.

In my case I need to evaluate data from a device. It sends it's display data bitwise (each bit is a segment on the display). So my Enum would be like:
```
Enum DisplaySigns
    ...
    BatteryDead = 1 << 14
    AutoPowerOff = 1 << 15
    ...
    MemoryFull = 1 << 27
    ...
End Enum
```
So I clearly see that each bit is a sign on the display and can use it much easier:
`If (Value And 1 << 14) <> 0 Then MsgBox("Warning: Battery empty!")`
If it is displayed decimal it would looks like
```
BatteryDead = 16384
AutoPowerOff = 32768
MemoryFull = 134217728
```
Confusing numbers (at least the larger ones), it's not clear to see that this is one bit per sign, it could be also a combination.
Even hex would be a good choice, too, for flags I prefer this one.

I will not show or hide the values, just changing the number style. If this is already possible, please point me into the right direction, I haven't found anything about it yet.

**Comment by EWSoftware** [comment]
See the Transform Args category of project properties.  There's an `includeEnumValue` option that lets you turn off the value column in the generated help file.  There are no options to change the numbering style yet though.

**Comment by VBWebprofi** [comment]
Hello, I would prefer hex values instead of shift bits.

**Comment by EWSoftware** [comment]
Combined with #868
