### ISSUE TITLE
How to suppress ResolveReferenceLinksComponent warnings

### ISSUE THREAD

**Issue by JJoe2** [EWSoftware/SHFB#359]
I am trying to use SHFB to document a custom log4net Appender.   It generates a lot of ResolveReferenceLinksComponent unknown reference link target warnings.

I see that someone else on StackOverflow has a similar problem with an assembly that used NHibernate: http://stackoverflow.com/questions/30212064/remove-external-library-from-reference-lookup-in-sandcastle

Is there a way to suppress these warnings?  I don't need log4net documentation included in my help file.

I have the following to the project file, but it makes no difference:

```
  <PlugInConfig id="Assembly Binding Redirection" enabled="True">
    <configuration useGAC="false">
      <assemblyBinding />
      <ignoreIfUnresolved>
        <assemblyIdentity name="BusinessObjects.Licensing.KeycodeDecoder" />
        <assemblyIdentity name="lognet.dll" />
        <assemblyIdentity name="Microsoft.VisualStudio.TestTools.UITest.Playback" />
      </ignoreIfUnresolved>
    </configuration>
  </PlugInConfig>
```

**Comment by JJoe2** [comment]
This is a duplicate: I found the solution in the answer to this thread: https://github.com/EWSoftware/SHFB/issues/67

I think this is a sufficiently common requirement to justify a mention in a FAQ - e.g. see also http://stackoverflow.com/questions/30212064/remove-external-library-from-reference-lookup-in-sandcastle

**Comment by EWSoftware** [comment]
I'll add a FAQ entry.
