### ISSUE TITLE
VS 2015 Extension causes '</' to be replaced with '<!--/-->/' in any comment block beginning with '///'

### ISSUE THREAD

**Issue by ack210** [EWSoftware/SHFB#361]
When the SHFB extension is installed in Visual Studio 2015, typing '</' in any line that begins with '///' results in the text being replaced with '/'.  This is highly annoying when trying to type XML documentation as every time I need to close an XML tag I have this issue occur.  As soon as I uninstall the SHFB extension the behavior stops.

A SO user pointed out that '!--' is the first intellisense suggestion when you type '<'.  So it seems like something with the extension is causing intellisense to be triggered in the '///' code block when a '<' is typed, and as soon as it does not recognize the '/', it replaces it with the !-- match.

**Comment by EWSoftware** [comment]
For the time being you can use Tools | Options, go to the Sandcastle Help File Builder category, and uncheck the "Enable extended XML comments completion options" checkbox.  That'll turn off the additional completion options related to that feature.  Just close and reopen any files and it'll take effect.
