### ISSUE TITLE
New Installation failure when installing as normal user

### ISSUE THREAD

**Issue by rowen01** [EWSoftware/SHFB#362]
Running vanilla Windows 10 with VS2015 Community Edition.
Downloaded the latest installer whilst running as a normal user in Windows.
Extract the zip file into my user Download directory.
Run SandcastleInstaller.exe as a user, enter the admin password for UAC.
When it tries to install the Sandcastle Help File Builder, by spawning the installation programme the process just hangs and the external installer doesn't get spawned.

I could work around this by copying the installation programmes to c:\Temp then switching user to Admin before executing SandcastleInstaller.exe.

I'm guessing it couldn't start the external installer but didn't pick up on an error message.

**Comment by EWSoftware** [comment]
You can find both installers in the .\InstallResources folder.  If permissions are preventing them from running, you can run them manually from there and provide the necessary elevation of privileges.
