### ISSUE TITLE
Question about generated web-page

### ISSUE THREAD

**Issue by StefH** [EWSoftware/SHFB#365]
Hello, I've some questions about the generated html web-site:

1. Is there an easy way to define which project/namespace or class will be displayed as first ?
2. Is there a way to include this generated html easily into another website, except by using IFrame ?

**Comment by EWSoftware** [comment]
The namespaces and types are sorted alphabetically.  You can modify the presentation style to change the order.  You will also have to change the TOC-related transforms if you want it to be reflected there as well.
