### ISSUE TITLE
How to force different class names in index for the same class name in different namespaces

### ISSUE THREAD

**Issue by jotkol** [EWSoftware/SHFB#366]
I have two different classes in two different namespaces. Unfortunetely both classes have the same name: **Dokument**. Is there any way to distinguish them in index, because this is very frustrating to see this result when you can't decide which one is the right one you are looking for. Sorry for pl-localized screenshot, but I think it's clear.
![sfera pomoc - powielone dokument class](https://cloud.githubusercontent.com/assets/15212353/20271560/76f96520-aa8b-11e6-995e-daf4cfadc744.PNG)

**Comment by EWSoftware** [comment]
The index entries are based off of the topic titles.  You can probably modify the presentation style XSL transformations to output the full namespace and type name for the index entries.

**Comment by jotkol** [comment]
Thanks a lot. I'll try this method, but it will take some time, because it's not my main job actually.

**Comment by jotkol** [comment]
Following Your suggestion, I've added some code to utilities_reference.xsl chcnging template t_typeNamePlain:
```
<xsl:template match="type" mode="plain" name="t_typeNamePlain">
    <!-- my extension BEGIN -->
    <xsl:param name="p_includeNamespace" select="true()" />
    <xsl:if test="$p_includeNamespace">
      <xsl:if test="normalize-space(substring-after(/document/reference/containers/namespace/@api,':'))">
        <xsl:value-of select="normalize-space(substring-after(/document/reference/containers/namespace/@api,':'))"/>
      </xsl:if>
      <xsl:text>.</xsl:text>
    </xsl:if>
    <!-- my extension END -->
```

This works as I wish:

![sfera dokumentacja - rozroznienie nazw przez namespace - rozwiazane](https://cloud.githubusercontent.com/assets/15212353/20435645/2af57be4-adad-11e6-8032-08d06abb9757.PNG)

**Comment by EWSoftware** [comment]
Since that's used by all templates that need to get the name, you will most likely see the fully qualified name show up everywhere such as in topic titles.  If that's not what you want, you can make a copy of that template and give it a different name and then just update the call in the one that generates the index entries.
