### ISSUE TITLE
Properties missing from web output

### ISSUE THREAD

**Issue by BRR-LASERS** [EWSoftware/SHFB#367]
Generating docs from my VB projects, I can see everything in the chm file, but the Properties are not showing up on the web output (which, of course, is what I really want to make available to the other developers). Any Ideas?

**Comment by BRR-LASERS** [comment]
Oh - and the MS Help Viewer version is also missing the Properties...

**Comment by EWSoftware** [comment]
Are the properties public?  If not, they won't show up by default.  If they are, can you give an example of the code for a property that doesn't show up?

**Comment by BRR-LASERS** [comment]
Actually, I think I figured it out. It has something to do with Namespace Grouping. Not sure how/why some of my classes were showing up, since they were in a "sub" namespace, but those were the ones that did not show the properties. Once I realized that the Grouping setting was not correct, magically - all the classes show up in their proper Namespaces and their Properties show up, as well.
