### ISSUE TITLE
links missing

### ISSUE THREAD

**Issue by Bortxx** [EWSoftware/SHFB#368]
I am rendering HTML format. Switched rendering from 2010 format to 2013. In 2010 links were generated for method attributes, implemented interfaces, and inherited classes in the syntax block. Is there a way to turn that back on with 2013 styles. Don't see a GUI setting for this. 

I believe in the 2010 format there was a hack to turn this on with attribute renderReferenceLinks="true" in VS2010.config. How is this done with 2013 format?

**Comment by EWSoftware** [comment]
Add the Syntax Component to the project.  You'll find it in the Components category of project properties.  In it's configuration is the option to enable reference links in the syntax section.

**Comment by Bortxx** [comment]
That worked, thanks.
Is there any documentation on these Syntax Component Configurations? Don't know what the other check boxes do or what other configuration elements are valid possibilities.

**Comment by EWSoftware** [comment]
Typically, it isn't needed unless you want to enable the link option, change the sort order of the topics, or enable the "No Example" tabs on code examples when a given language isn't present for the example.

What documentation there is right now can be found in the [Syntax Component configuration topic](http://ewsoftware.github.io/SHFB/html/3127217a-9b11-424e-aeb4-b88ca4569bad.htm).  The VB syntax generator is the only one that contains a sub-configuration element used to control whether or not to show line continuation characters.

**Comment by Atrejoe** [comment]
For posterity's sake:

Although the UI suggests this is about external content only, this works for links to custom attributes too:

![image](https://user-images.githubusercontent.com/585091/99653353-31269480-2a59-11eb-9c09-b4b0eddd48bf.png)

Example:
Both the attribute as the constructor arguments are linked to internal content.
![image](https://user-images.githubusercontent.com/585091/99654433-975fe700-2a5a-11eb-9924-641182829d84.png)
