### ISSUE TITLE
problem with Configuration or Platorm properties ..

### ISSUE THREAD

**Issue by JanghyeokYun** [EWSoftware/SHFB#370]
I'm include a Sandcastle project in a VS2015 Solution. 
I Set Documentation Source (.csproj file)

-My CS project build evironment :
Debug / x86 
(I don't have AnyCPU mode.)

I Cannot build Sandcastle project.
- Error : Unable to obtain assmbly name from project file ... '~~.csproj'.. using Configuration 'Debug', Platform 'AnyCPU'

please tell me how to this problem 
Is there any solution with shfbproj file editing..
My cs project have only Debug/x86, Debug/x64, Release/x86, Release/x64 modes.

I am sorry for the lack of English..

please reply.

**Comment by EWSoftware** [comment]
For some reason, Visual Studio won't track the selected platform and configuration for SHFB projects anymore using the Configuration Manager.  As a workaround, you should be able to add the solution/project as the documentation source and, on the documentation source's properties, specify the platform and configuration to use for the build there.  Those override any platform/configuration settings used when the SHFB project is built.
