### ISSUE TITLE
Edit project file programmatically

### ISSUE THREAD

**Issue by abertram** [EWSoftware/SHFB#371]
Hi,

I would like to add some api filters programmatically. I tried something like

var project = new SandcastleProject(filename, true, false);
project.ApiFilter.MergeExclusionEntry(ApiEntryType.Namespace, MyNamespace);
project.SaveProject(project.Filename);

It doesn't work. I assume because ApiFilter property is read only?

Alex

**Comment by EWSoftware** [comment]
The SandcastleProject class is now just a read-only wrapper around the MSBuild project used for the build.  If you want to set the `ApiFilter` MSBuild property, you'll need to do so through the MSBuildProject property which gives you access to the underlying MSBuild project instance.  Alternatively, you can load the project as an XML file and modify the property through the XDocument/XElement classes in .NET.
