### ISSUE TITLE
Path Denied Error when Upgrading form ver. 2015.01.12.0 to ver. 2016.9.17.0

### ISSUE THREAD

**Issue by rmckay49** [EWSoftware/SHFB#372]
I am very new to the SandCastle app.  I intitally installed SHFBGuidedInstaller_2015.01.12.0.  I worked through the sample compile described in the help file using SandcastleBuilder.WPF.dll and SandcastleBuilder.Utils.dll.  The compile proceeded without a problem.  I then installed SHFBInstaller_v2016.9.17.0.  I again worked through the sample compile using the same files and the GUI. The compile did not complete and I received the fllowing error:

Locating components in the following folder(s):
    C:\Users\Rod
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
    Last step completed in 00:00:00.0687
-------------------------------

SHFB: Error BE0065: BUILD FAILED: Access to the path 'C:\Users\Rod\AppData\Local\Application Data' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at Sandcastle.Core.Reflection.ReflectionDataSetDictionary..ctor(IEnumerable`1 componentLocations)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

I then tried to complie using the Visual Studio 2015 add-in.  The compile completed without a problem.  To rule out a bad installation I uninstalled the SHFBInstaller_v2016.9.17.0 installation with Revo Uninstaller Pro and reinstalled SHFBGuidedInstaller_2015.01.12.0.  Using the same files and the GUI the compilation proceeded correctly.  I then uninstalled SHFBGuidedInstaller_2015.01.12.0 and reinstalled SHFBInstaller_v2016.9.17.0.  There was no change.  Error when using the GUI and no problems when using the VS 2015 add-in.

I probably have a path incorrectly set but am so unfamiliar with SandCastle I don't know what to trouble shoot.

Thanks in advance to anyone with suggestions.

Rod McKay

**Comment by EWSoftware** [comment]
You've either entered *C:\Users\Rod* or some variation of it in the project as the component path or your project is perhaps stored there which would be rather odd.  You typically don't need to specify a component path unless you've got custom components that you want the project to find.  Make sure you put the SHFB project itself in a subfolder under My Documents or some other location where you have read/write permissions.

Visual Studio typically creates projects under My Documents or another folder that you've told it to use(see Tools | Options | Projects and Solutions).  That may be why it's working but the standalone GUI isn't.
