### ISSUE TITLE
Example for 'MemberName'

### ISSUE THREAD

**Issue by alangryali** [EWSoftware/SHFB#373]
Please include an example for `MemberName`.

*TODO (optional): Describe a specific scenario you would like to see addressed*

---

Member: `FullyQualifiedMemberName`
Page: http://url.to/docs/html/page.htm

**Comment by EWSoftware** [comment]
Were you just playing around or did you intend to fill this out with something specific?  If you're trying to implement this for your own project, please replace the values in the Transform Args category of the project properties with links to your own project site.
