### ISSUE TITLE
OutOfMemoryException only in Command Line

### ISSUE THREAD

**Issue by nenrault** [EWSoftware/SHFB#374]
Hello,

I'd like to generate doc in command line using MSBuild.
When using the builder GUI I have no problem but when using MSBuild command, by providing the same shfbproj file I end up with an OutOfMemoryException in class LightweightWebsiteStylePlugIn.cs, line 296:
if(pos != -1)
                    outputFile = outputFile.Insert(pos, leftNav.ToString(SaveOptions.DisableFormatting));
Do you have any advice regarding this issue?
I've been reading lot of posts about OutOfMemoryException and did all workarounds but still getting this error...
The weird thing is that it happens only in command line.

Any help/advice or feedback would be greatly appreciated! :)

Thank you!

**Comment by EWSoftware** [comment]
Assuming you are talking about the standalone GUI and you have a 64-bit system, the standalone GUI runs as a 64-bit process and would have access to all available memory.  Unless you are running the 64-bit version of MSBuild, it's a 32-bit process so would only be constrained to the maximum memory for a 32-bit process.  Try using the 64-bit version of MSBuild usually found in the *amd64* folder (i.e. *%Program Files(x86)%\MSBuild\14.0\Bin\amd64*).

**Comment by nenrault** [comment]
Worked like a charm!
Thank you very much.
