### ISSUE TITLE
Where is the Build Action setting?

### ISSUE THREAD

**Issue by guidros** [EWSoftware/SHFB#375]
I am trying to add a logo to the documentation. The help file builder says "Place the file in your project in an icons\ folder and set the Build Action to Content".

I have added an icons folder to the project I am trying to document and added the logo to that folder but I can't find any Build Action to set to "Content" in Sandcastle application nor in Visual Studio.

Where is this setting?

Thank you

**Comment by EWSoftware** [comment]
Select the file in the Solution Explorer (Visual Studio) or Project Explorer (standalone GUI) tool window.  The Build Action is part of the file properties shown in the Properties tool window.  In the standalone GUI, the file properties are at the bottom of the Project Explorer.  In Visual Studio, if the Properties tool window isn't visible, right click on the file and select Properties and it will take you to it.

**Comment by guidros** [comment]
Thank you!
