### ISSUE TITLE
SHFB with NuGet: error BE0028  Plug-in loading errors

### ISSUE THREAD

**Issue by rainman110** [EWSoftware/SHFB#377]
I am trying to use SHFB on appveyor for CI. I can build our project (https://github.com/rainman110/CPACS) on my workstation without any issues. On appveyor, I installed SHFB and its plugins with NuGet. 

During the build, I get the error BE0028 (Plug-in loading errors):
https://ci.appveyor.com/project/rainman110/cpacs/build/2.3.1.26.0

This project uses the XSD Documenter Plugin (https://github.com/terrajobst/xsddoc).
I installed the following Nuget packages:
 - EWSoftware.SHFB -Version 2015.10.10.0
 - EWSoftware.SHFB.NETFramework -Version 4.6
 - SHFB.XsdDocumentationPlugin -Version 15.10.10

Unfortunately, the build directly stops and I have no chance to look at the logfile.

I tried to follow the rules for SHFB with NuGet. Here's my project file:
https://github.com/rainman110/CPACS/blob/da3bbb484a87d3212bdfc1054b8c61fb02fd5610/documentation/Cpacs_doc_project.shfbproj

and my appveyor config:
https://github.com/rainman110/CPACS/blob/da3bbb484a87d3212bdfc1054b8c61fb02fd5610/appveyor.yml

Do you have an idea, what the problem could be?

If it helps, I am really new to SHFB and msbuild. Thus, the problem is probaby trivial.

**Comment by EWSoftware** [comment]
When using MSBuild 14.0 you need SHFB 2016.4.9.0 or later as prior versions do not work correctly with it.  If you can't use a newer SHFB release, you might see if there's an option to use MSBuild 12.0 if that's possible.

**Comment by rainman110** [comment]
Thanks for the hint! Unfortunately, switching to e.g. MSBuild 12 doesn't solve the problem:
https://ci.appveyor.com/project/rainman110/cpacs/build/2.3.1.27.0

**Comment by EWSoftware** [comment]
Check the SHFB build log.  Do you see any additional info in there?

**Comment by rainman110** [comment]
Unfortunately, appveyor stops directly after the build failure. So I have not found a way to inspect the log, as subsequent commands (like ```more C:\projects\cpacs\build\doc\LastBuild.log```) are not called anymore by appveyor.

There's probably a way to ignore the exit code of msbuild, but I haven't figured it out. 

Normally, I work on Linux and Bash, so excuse my beginner-ish questions.

**Comment by EWSoftware** [comment]
Can you get to the SHFB log manually?  You really need to see it's content to figure out why it's failing to load the plug-ins.

**Comment by EWSoftware** [comment]
If you can add the MSBuild command line option `/p:DumpLogOnFailure=True`, the build task should dump the SHFB build log on failure so that you can see its content.

**Comment by rainman110** [comment]
Thanks, that was helpful. SHFB cannot find the plugin XSD Documenter:
https://ci.appveyor.com/project/rainman110/cpacs/build/2.3.1.31.0

It is installed under c:\projects\cpacs\packages\SHFB.XsdDocumentationPlugin.15.10.10 (https://ci.appveyor.com/project/rainman110/cpacs/build/2.3.1.31.0#L69)

I already have set the ComponentPath. Do I have to configure it differently?

**Comment by EWSoftware** [comment]
As long as it's in the component path and the package is there it should find it.  I suppose it's possible it's failing for some other reason like the plug-in configuration being invalid.  You could try removing the plug-in from the project, adding it back, and reconfiguring it to make sure it's okay.  Other than that, I don't know.

**Comment by rainman110** [comment]
I figured out by using some local tests with the nuget packages, that the problem is the file  ```XsdDocumentation.PlugIn.dll``` of the nuget XSD Documenter package.

If I replace it with the Dll from the original installation, it works.

Therefore I am closing this issue and will report it at the proper place.

Thanks for the help!
