### ISSUE TITLE
Error BE0065: BUILD FAILED

### ISSUE THREAD

**Issue by CHALM5** [EWSoftware/SHFB#380]
when I followed the steps of instruction in Walkthrough : Creating Your First Project from SHFB Documentation, there was an error that is Error BE0065: BUILD FAILED: the key value can't be null,in  System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add),in  SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
in  SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build().
I don't know what is the meaning of the error and can't fix it .Could you help me  handle it and build the project successfully?
Following is the context of output window:
-------------------------------
[Sandcastle Help File Builder and Tools, version 2016.9.17.0]
Creating output and working folders...
Finding tools...
The Sandcastle tools are located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\'
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in 'C:\Program Files (x86)\HTML Help Workshop\'
Locating components in the following folder(s):
    F:\work\接口文档\自动生成
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Using framework reflection data for '.NET Framework 4.5' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework'
Using presentation style 'VS2013' located in 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013'
Loading and initializing plug-ins...
Lightweight Website Style Version 2016.9.17.0
Copyright © 2006-2016, Eric Woodruff, All Rights Reserved
Portions Copyright © 2014, Sam Harwell, All Rights Reserved
-------------------------------
Clearing working folder...
-------------------------------
Validating and copying documentation source information
    Last step completed in 00:00:00.0120
-------------------------------

SHFB: Error BE0065: BUILD FAILED: 值不能为 null。
参数名: key
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   在 SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

![image](https://cloud.githubusercontent.com/assets/10841721/21536430/1364f5e6-cdbe-11e6-906c-716428532430.png)

**Comment by EWSoftware** [comment]
I tried to reproduce the error but when I go through the walkthrough it builds without issue.  I'd suggest just using your own solution or project file as the documentation source and see if you can build a help file.

**Comment by CHALM5** [comment]
I found that I used vs2015 and it supports vs2010 and vs2013. So I doubt that whether it support vs2015 or not.

**Comment by EWSoftware** [comment]
Not quite sure what you mean.  If you're asking whether SHFB supports VS2015, it does.  The Visual Studio Package can be installed in VS2013 or VS2015.  The standalone GUI isn't affected by Visual Studio version.  Both support various versions of the .NET framework which you can change using the Framework Version project property.
