### ISSUE TITLE
Fails for types with generic arity specifications

### ISSUE THREAD

**Issue by MulleDK19** [EWSoftware/SHFB#383]
I have some methods that SHFB reports "Missing documentation" for everything on, even though, they're clearly there. I've narrowed it down to methods that has delegate parameters with generics, eg. `Func<bool>^`

```csharp
/// <summary>
/// Yields the executing fiber until the specified condition is met.
/// </summary>
/// <param name="condition">The condition.</param>
/// <param name="timeOut">The maximum time to sleep. If set to 0, the call will not time out.</param>
static void SleepUntil(Func<bool>^ condition, int timeOut);
```

Error:
```
[Missing <summary> documentation for "M:Fiber.SleepUntil(System.Func{System.Boolean},System.Int32)"]
```

XML:
```xml
<member name="M:Fiber.SleepUntil(System.Func`1{System.Boolean},System.Int32)">
	<summary>
	Yields the executing fiber until the specified condition is met.
	</summary>
	<param name="condition">The condition.</param>
	<param name="timeOut">The maximum time to sleep. If set to 0, the call will not time out.</param>
</member>
```

If I duplicate the member and remove the generic arity specification (`1), it works, so SHFB is looking for the wrong type name.

I've worked around it by creating a custom delegate without generics instead of using `Func<TResult>`.

**Comment by EWSoftware** [comment]
Add the [Member ID Fix-Ups plug-in](http://ewsoftware.github.io/SHFB/html/17d977a6-e3dc-4ef4-9bbf-718ef4823854.htm) to the project on the Plug-Ins category property page.  Click the *C++ Fixes* button to add the common fix-ups for managed C++.  That should resolve the issue.  If not, other expressions can be added to correct any not covered by the plug-ins default expressions.

**Comment by MulleDK19** [comment]
Yea, that fixes it. Cheers.
