### ISSUE TITLE
<inheritdoc /> issue according "Help file language"

### ISSUE THREAD

**Issue by Nicolas4tin** [EWSoftware/SHFB#385]
Hello everyone,

The tag ```<inheritdoc />``` doesn't work if "Help file language" is "French (France)". It does if it's "English (United States)".

I was able to reproduce the issue only by using doc inheritance between an interface and a class that implements it.

```
    /// <summary>
    /// Gère l'authentification à une base de données en permettant à l'utilisateur d'entrer 
    /// ses informations d'identification pour se connecter, réinitialiser son mot de passe
    /// (s'il est expiré) et fermer la connexion.
    /// </summary>
    /// <remarks>
    /// Auteur : Nicolas Fortin (Q068)<br/>
    /// Date   : 2016-11-11
    /// </remarks>
    public interface IGestAuthnBDBase : IDisposable
    {
    (...)
    }

    (...)

    /// <inheritdoc />
    public abstract class GestAuthnBDBase : IGestAuthnBDBase
    {
    (...)
    }
```
See the result below.

"Help file language" is English:

![documentation en](https://cloud.githubusercontent.com/assets/16655729/21941994/4201594e-d999-11e6-8a7f-cb4d2cb86d11.jpg)

"Help file language" is French:

![documentation fr](https://cloud.githubusercontent.com/assets/16655729/21942003/4943fd2e-d999-11e6-92fc-bce41bc6185a.jpg)

I use SHFB 2016-9.17.0 and the project was build with VS2015.

Best regards,

Nicolas

**Comment by EWSoftware** [comment]
Can you attach a small example that demonstrates the problem?  The only XML comments files that are localized are the framework XML comments files.  The documentation sources don't localize so the comments would be the same regardless of language.  If inheritance wasn't working, I'd expect to see no comments, no comments in a different language.

**Comment by Nicolas4tin** [comment]
Hello Eric,

Thank you very much for helping. I am in training and out of office today and tomorrow. I'll give you an answer not later than Wednesday.

Have a nice day,

Nicolas

**Comment by Nicolas4tin** [comment]
Hello Eric,

I have the same problem with the following small example:

[RMQ_TestDocInheritance.zip](https://github.com/EWSoftware/SHFB/files/714307/RMQ_TestDocInheritance.zip)

You can see here the documentation files that have been built:

- $\RMQ_TestDocInheritance\RMQ_TestDocInheritance_cpo\Help\Documentation - en.chm 
"Help file language" is "English (United States)": **there is** doc inheritance between the class and the interface.
- $\RMQ_TestDocInheritance\RMQ_TestDocInheritance_cpo\Help\Documentation - fr.chm
"Help file language" is "French (France)": **there is no** doc inheritance between the class and the interface.

The SHFB file used to build the documentation files is:

$\RMQ_TestDocInheritance\RMQ_TestDocInheritance_cpo\RMQ_TestDocInheritance_cpo.shfbproj

Thank you for helping me.

Have a nice day,

Nicolas

**Comment by Nicolas4tin** [comment]
Hello Eric,

Did you find something ?

Thanks,

Nicolas

**Comment by Nicolas4tin** [comment]
Hello Eric,

Thank you for your answer and for taking time to find the cause of this issue. I won't close the thread. You can close it if you want or keep it opens as a reminder.

Thanks again. Have a nice day.

Nicolas
