### ISSUE TITLE
Error "The value of the property 'AddLanguageSpecificTextSet' is null or undefined, not a Function object" on opening any page of a large help file.

### ISSUE THREAD

**Issue by zcollins0** [EWSoftware/SHFB#386]
Using Microsoft Help Viewer 2.2, this error occurs when opening any page in a large .mshc file. The help file in question is ~200MB. Using all of the same settings in Sandcastle, a smaller help file ~2MB has no errors.

I am not sure that this is a problem with SHFB, but it seems to be since this error is dependent on the size of the help file generated.

**Comment by EWSoftware** [comment]
It is a limitation of the help viewer.  There is a 200MB limit.  See [this link](https://social.msdn.microsoft.com/Forums/vstudio/en-US/032d9584-a774-434e-afb8-74b4d66ec57e/ms-help-viewer-2x-problem-with-big-mshc-files-import-generated-by-sandcastle?forum=visualstudiogeneral).  Unfortunately, I don't think anything is being done about it.

**Comment by zcollins0** [comment]
Thanks for your help!
