### ISSUE TITLE
hierarchical table of contents plug-in

### ISSUE THREAD

**Issue by bai-reilly** [EWSoftware/SHFB#387]
I have an older SHFB project that I haven't built in some time. It configured the "Hierarchical Table of Contents" plug-in. In version 2016.9.17.0, SHFB says it can't find this plug-in. Was it removed?

Great software.

-reilly.

**Comment by EWSoftware** [comment]
It was deprecated in [version 2014.1.26.0 Beta](http://ewsoftware.github.io/SHFB/html/1139ca15-af64-48a2-9187-ccc1aec389d4.htm) and eventually removed in version [2015.7.25.0](http://ewsoftware.github.io/SHFB/html/90c2bedf-fe6e-4f99-8a33-84b441701269.htm).  It did not work with MS Help Viewer output and was superseded by the [namespace grouping support](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#NSGrouping) in the Help File category of project properties.  Use the new namespace grouping options instead.

**Comment by bai-reilly** [comment]
Thanks very much!
