### ISSUE TITLE
Error BE0065 when building project on Team City

### ISSUE THREAD

**Issue by mbcrawfo** [EWSoftware/SHFB#389]
I'm trying to get documentation to build for one of my projects in Team City.  The documentation is set up as a project in my solution, made using the documentation project template.  The SHFB projects are excluded from the normal build, so in Team City they are run as a MSBuild step after the project has build and tests pass.  However, the SHFB build always fails with the error in the title during the `ValidatingDocumentationSources` step.  

Manually building the SHFB project locally in VS works fine.  After the Team City build fails, I can copy its working directly and manually run the MSBuild command, and it works fine.  We have several other projects (probably half a dozen, or more) that use Team City to build SHFB documentation, and I haven't seen this problem on any of them.

I'm looking for some idea of what's going wrong, because I'm completely out of ideas for what might be causing the problem.  This particular piece of documentation only references one project (see below) and the SHFB log is here: [LastBuild.txt](https://github.com/EWSoftware/SHFB/files/717657/LastBuild.txt)

    <DocumentationSources>
        <DocumentationSource sourceFile="..\ProductCatalog.ApiClient\ProductCatalog.ApiClient.csproj" />
    </DocumentationSources>

**Comment by EWSoftware** [comment]
It's not an issue I'm aware of.  Are you using the same version locally as on the server?  Have you tried updating to the latest release?

**Comment by swirlywonder** [comment]
@mbcrawfo I also automate document generation with TeamCity but haven't had this issue. For lack of further detail, I have two suggestions.

1. Be sure that the dlls for the project have been build in a step prior to the SandCastle build step. If those files are not physically present, you may see an error like you are describing.
2. In our case, I don't use project references but instead target the dll and xml files explicitly. If these files are built by another configuration, you could simply drop them in place as build artifacts, or of course run the project build in a step immediately before the MSBuild of SandCastle.

**Comment by mbcrawfo** [comment]
@EWSoftware, I finally discovered the cause of this.  The Team City project had some parameters set globally that were passed in to all instances of MSBuild. Two of them, PublishOnBuild=true, and PublishProfile={Release|QA|UAT}, cause SHFB to fail. No idea why,  but altering the build to pass those parameters only to the main code compilation instance has fixed the problem.
