### ISSUE TITLE
Code blocks with inline ASP.NET markup

### ISSUE THREAD

**Issue by swirlywonder** [EWSoftware/SHFB#390]
I am including some ASP.NET .aspx files as code examples in the documentation. The 'XML' language type works well in most cases except inline code like the following:

```
<%# string.Format("(Item-{0})", 123) %>
```
Since the colorizer is not set up to understand these tags, it seems to treat these as having no closing tag and corrupts some of the subsequent ASP.NET markup.

I have tested this as both XmlDocs and MAML markup but produced the same result.

It would also be nice if the colorizer could highlight code within script blocks as well. For example:
```
<script language="C#" runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        // Todo: Insert code here...
    }
</script>
```

The first issue is the most important since the document code is being broken and the latter would just be nice to have.... Is this something that could be included in a future release?

**Comment by EWSoftware** [comment]
The colorizer can't handle multiple languages within one block of text.  If you say it's XML, it treats it all as XML.  The best I can probably do is adjust the regular expressions used to parse the text to handle the `<%....%.>` elements so that they are treated as single, self-closing elements.

**Comment by swirlywonder** [comment]
I understand. I was just hoping highlighting could be scoped to use the C# highlighting scheme inside a server-side script block.

The other issue is more important since it's actually changing the output, not just how it's colored. I also noticed that HTML may not render properly in all cases when using HTML5 (which of course is not XML compliant) but there are no HTML or ASP.NET specific parsing instructions to deal with these edge cases. 

Would separating the XML language highlighter from HTML or ASP.NET languages allow more complex colorization? If removing the map from html/asp.net/aspnet to xml and creating an additional parser/highligher is not an option (even if it's mostly a clone of xml for now), then adjusting the regex would be acceptable. In either case, you may find this helpful:

[https://weblogs.asp.net/ahmedmoosa/embedded-code-and-inline-server-tags](url)

I believe you are correct that all variants of the inline syntax start with `<%` and end with `%>` despite the additional directives that follow.

**Comment by EWSoftware** [comment]
The colorizer uses a set of regular expressions to parse the text and figure out how it should be highlighted.  The HTML/ASP.NET keywords are all mapped to [XML](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/CodeColorizer/ColorizerLibrary/Template/highlight.xml#L25).  The [rules for XML](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/CodeColorizer/ColorizerLibrary/Template/highlight.xml#L1264) define how it's broken up.  If a set of expressions and states can be defined for HTML, they could be separated out.  However, as noted, it won't handle multi-language highlighting such as supporting script blocks even with a different set of rules.

**Comment by EWSoftware** [comment]
> HTML may not render properly in all cases when using HTML5 (which of course is not XML compliant)

I couldn't find a case where this made a difference.  If you can supply an exampleI'll take a look at it.  Note that any inline script elements will mess up the layout until using the corrected rules that handle them.

**Comment by swirlywonder** [comment]
Sadly, HTML5 enables developers to be as lazy as possible. Here are two examples:

Quotes for attributes are considered optional as long as there are no spaces
(but I think this example may already be working as expected)
`<link rel="stylesheet" href="/styles/print.css" media=print>`

Some attributes don't even require values
`<script src="/scripts/analytics.js" async></script>`

The last output would look like this when processed:
`<script src="/scripts/analytics.js" asyncscript>`

Thank you for taking the time to look at these. I appreciate it.

**Comment by EWSoftware** [comment]
The lack of an attribute value was throwing the context state off.  I was able to add some additional rules that get it back on track regardless of the mix of attribute with and without values.

**Comment by swirlywonder** [comment]
Great thanks!
