### ISSUE TITLE
Installer for newest release can't find VSIX package installer (bug).

### ISSUE THREAD

**Issue by Browman** [EWSoftware/SHFB#393]
When installing the newest Sandcastle release (v2017.1.28.0) on both Windows 7 and Windows 10 with Visual Studio 2015: Community Edition, the installer complains that it is unable to locate the VSIX installer, producing the error below:

> **Unable to locate the VSIX package installer.**
> This could be because a supported version Visual Studio is not installed on this PC.  The extension package cannot be installed.  If you will not be using Visual Studio to create help projects, you can safely skip this step.

The VSIX installer is correctly installed on the system, and the plug-in can be installed properly by double-clicking on the `SHFBVisualStudioPackage_VS2015AndLater.vsix` file in the installation ZIP file.

**Comment by EWSoftware** [comment]
Just go into the .\InstallationResources folder and run it manually.  That should work.

**Comment by Browman** [comment]
As stated in the original report, manually running it works just fine. Everything's good except a small, mildly irritating bug in the installer.

**Comment by EWSoftware** [comment]
Understood.  My note was for anyone else who runs into the same issue until it's resolved.

**Comment by Browman** [comment]
Ah, OK. Sorry if I came across a little strong. By the way, thanks for Sandcastle!
