### ISSUE TITLE
Custom fonts in sandcastle project

### ISSUE THREAD

**Issue by Nawalkhan** [EWSoftware/SHFB#394]
Hi,
Can we add custom fonts to a sandcastle project?

**Comment by EWSoftware** [comment]
Yes, you can add them to the project and set their Build Action property to Content.  This will include them in the help file or website when built.  If placed in the root of the project, they'll be copied to the root of the help file/website content.  If placed in a folder, the content will be copied to a like-named folder in the help file/website content.

If you need to add references to the fonts in the style sheet, you'll need to create a folder called *styles\\* in the help file project, place a modified copy of the presentation style's style sheet file in it (i.e. *branding.css*), and set its Build Action to Content as well.  This will override the default stylesheet from the presentation style when the help file is built.

**Comment by Nawalkhan** [comment]
The problem is solved . Thank you for the solution :)
