### ISSUE TITLE
OpenXML format Properties section repeats the Members table

### ISSUE THREAD

**Issue by ApolonTorq** [EWSoftware/SHFB#396]
I just upgraded to the latest Sandcastle and have found the OpenXML docx file format output option to be very useful in communicating API concepts in a single easily transferred file format. It does however repeat the information in the Members section in the Properties section. Is there anyway I can disable the generation of the Properties section of the document?

**Comment by EWSoftware** [comment]
I assume you're talking about the Class page which lists all the members of the class.  You should be able to suppress the member list by going into the MainSandcastle.xsl transformation for the Open XML presentation style and commenting out `xsl:when` element with the `$g_apiTopicGroup='type'` condition in the `t_body` template at around line 131.

I can add a transformation argument to allow including or excluding them conditionally in a future release.

**Comment by ApolonTorq** [comment]
Eric,

Thanks muchly. I ended up commenting the mode=”Member” section to get what was wanted.

Is there any way of removing the page break after boilerplate_seeAlsoNamespaceLink item?
I did have a go at identifying how myself, but the ramp up on xsl, open-xml etc is massive.

Apolon.

**Comment by EWSoftware** [comment]
Page breaks are inserted between each topic when they are merged into a single document.  If there's a page break occurring after a section header, it's a soft page break and is just how the content gets laid out.  Not much you can do about that as far as I know.  I'm not sure if there's some sort of "keep together" option for text elements.

**Comment by ApolonTorq** [comment]
Ok, thanks for the reply.
