### ISSUE TITLE
<exclude/> on one method hides all overloads

### ISSUE THREAD

**Issue by chm-tm** [EWSoftware/SHFB#406]
Consider the following code:
```csharp
namespace ClassLibrary1 {

    /// <summary>Class1 documentation</summary>
    public class Class1 {

        /// <summary>This method is actually not documented because the other overload is excluded.</summary>
        public void Overload() { }

        /// <exclude/>
        public void Overload(int arg) { }

        /// <summary>This method is documented.</summary>
        public void SomeOtherMethod() { }
    }
}
```
Neither the `Overload()` nor the `Overload(int)` methods get documented in the HTML Help file.
Instead, I expect the `Overload()` method to be documented.
If there were a documented `Overload(string)` method, additionally, an `Overloads` page should be generated where the Overload(int) method is not shown.

No API filter is involved.

A [Repro](https://github.com/EWSoftware/SHFB/files/806437/Repro.zip) is attached. You will need to adjust the ComponentPath property.

**Comment by EWSoftware** [comment]
That is by design.  The exclude tag effectively creates an API filter.  The API filter does not distinguish by parameters so if one overload is excluded, all of them are.

**Comment by chm-tm** [comment]
And now I realize that this is actually [well documented](http://ewsoftware.github.io/XMLCommentsGuide/html/a8ade450-e201-401a-923d-1a1169ef7828.htm).
Since the exclude tag is deprecated (unfortunately), I don't request this as a feature.

**Comment by chm-tm** [comment]
Note that I didn't originally find the exclude tag documentation since I wasn't aware of the fact that there are 5 different help documentations and that the nice search feature on [the homepage](http://ewsoftware.github.io) isn't global over these collections.
