### ISSUE TITLE
Unable to locate the VSIX package installer on VS2017 Professional

### ISSUE THREAD

**Issue by xtomik** [EWSoftware/SHFB#407]
Hello,

Guided Installation (v2017.1.28.0): Unable to locate the VSIX package installer.

Please add support for VS2017 Professional
Default install location: %ProgramFiles(x86)%\Microsoft Visual Studio\2017\Professional\

**Comment by EWSoftware** [comment]
For now, just run the VSIX file from the .\InstallResources folder to install it manually.

**Comment by xtomik** [comment]
Ok, thanks
