### ISSUE TITLE
Sandcastle links to C# Interface from Welcome page

### ISSUE THREAD

**Issue by GregJF** [EWSoftware/SHFB#409]
I have successfully built a help file of my C# solution using a SandCastle project.

In the SandCastle project there is a Welcome page.

I wish to have a link from this welcome page to a page in the help file.

The Sandcastle doco on links says I ought to use the GUID to the topic Id

But my generated Help file doesn't have topic Id for the section I wish to go to.

I viewed the source to ascertain this.

So how can I create a link to the help page that I wish to go to?

I tried this, but it is not a link:
`<para>
    <link xlink:href="e0b76020-d63f-a2e9-5219-3dfc990041c0.htm">IBillingExtractionService</link>
 </para>
`

**Comment by EWSoftware** [comment]
Use the [link element](http://ewsoftware.github.io/MAMLGuide/html/53a2b7c6-a269-4916-9313-bdc301ee9398.htm) for other conceptual topics.  Just specify the GUID, no extension.

To link to API members from conceptual topics, use the [codeEntityReference element](http://ewsoftware.github.io/MAMLGuide/html/bc490dbf-7d46-432d-a816-3ae16ab6af54.htm).

In either case, the [Entity References tool window](http://ewsoftware.github.io/SHFB/html/e49eea91-a9ef-4aa5-ad8f-16ebd61b798a.htm) can help you insert such links with the proper element and formatting.

**Comment by GregJF** [comment]
Thanks for that answer. 
I can now link to API elements.
But I also wish to link to:

- Namespaces  (which I can search for)

- Section  headers by name

**Comment by EWSoftware** [comment]
To link to namespaces, use the `codeEntityReference` element and specify the namespace prefixed with "N:" as the inner text.  Namespaces won't show up in the Entity References tool window unless you've got a `NamespaceDoc` class in the code for their comments.

Anchor targets to sections within conceptual topics are supported.  You add the `address` attribute to the `section` element and use that ID after the hash character in the `link` element's target ID.

Anchor targets to section headers in API topics are not supported.  Support could probably be added for them but they're generated by the presentation styles so there's no guarantee that all sections get them and for those that do that they'd be consistent.  You'd have to go figure them out by looking at the transformations or the rendered topics.
