### ISSUE TITLE
Chm HH3002/HH3004 compilation warnings when the directory contains a . (dot)

### ISSUE THREAD

**Issue by cklam2** [EWSoftware/SHFB#41]
When you store a Sandcastle project in a directory that contains a dot then the compilation of the chm fails with following warnings:
```
HHC3004 : warning : AlertCaution.png : The HTML tag "•Yãü¯ø18¥BÁÁ`ÊIEND®B`‚" is not a valid HTML tag (it does not begin with an alphanumeric character). [E:\Test.Help\Test\Help\Working\Build1xHelpFile.proj]
HHC3004 : warning : AlertNote.png : The HTML tag "ñ+®ç*x™²<¹$9E[-qWW.(ÎI+6aaš@.Ây™24àóÌ ‘..." is not a valid HTML tag (it does not begin with an alphanumeric character). [E:\Test.Help\Test\Help\Working\Build1xHelpFile.proj]
(etc)
```
And all images in the generated chm are broken (missing).

It doesn't matter which folder has the dot, as long as the full directory has at least 1 dot. In my case it was "E:\Test.Help\Test\". When removing the dot then I don't see the warnings anymore. 

While this workaround sounds easy, our folders in the development branch are all with a dot. Don't ask me why but this is what has been agreed upon years ago and our build processes do expect a dot :(

**Comment by EWSoftware** [comment]
Unfortunately this is a limitation with the Help 1 compiler (noted in the FAQ and also in a warning in the log file ([BE0060](http://ewsoftware.github.io/SHFB/html/e076c319-ff84-40dc-bb00-ff4c72718215.htm)).  It's actually the ".h" that is the issue.  It also has problems with commas in the path.  A period by itself is fine.  Your only solution is to remove the dot or rename the ".Help part to something else such as ".Docs".  Also note that the help viewer has problems with hash signs (#) in the path when viewing help files too.

**Comment by cklam2** [comment]
You're right, now indeed see build warning BE0060 (The file path contains a comma or '.h' which may cause the Help 1 compiler to fail), missed that completely. After renaming to .DocHelp it compiles successfully. Thanks for the support.

**Comment by wim07101993** [comment]
Personally I think this is an issue. In my case solution directory is named `{Company}.{Product}.{ProductPart}.{...}`. Same as how namespaces is built. As you probably now this is a very common way to name directories in C#. When one part of the namespace contains a ".H..." like ".Handshakes", the documentation output path needs to be outside the solution directory.
