### ISSUE TITLE
Unable to locate information for the project framework version

### ISSUE THREAD

**Issue by couven92** [EWSoftware/SHFB#410]
I have a SHFBPROJ file that I invoke using the MSBuild task as described here: http://ewsoftware.github.io/SHFB/html/ec822059-b179-4add-984d-485580050ffb.htm

In order to do that I install the `EWSoftware.SHFB` Version `2017.1.28` NuGet package on build and set the `SHFBROOT` property according to the NuGet package directory path. Since I am producing documentation for a .NETCore project, I have also installed the `EWSoftware.SHFB.NETCore` NuGet package.

SHFB immediately fails with the following error message
> SHFB : error BE0071: Unable to locate information for the project framework version '.NETCore 4.5.1' or a suitable redirected version on this system.  See error number help topic for details.

Here's my `LastBuild.log`: (User specific directory paths have been replaced with equivalent MSBuild property monikers)
``` XML
<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2017.1.28.0" projectFile="$(MSBuildProjectFullPath)" started="08.03.2017 00.23.59">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;$(UserProfile)\.nuget\packages\EWSoftware.SHFB\2017.1.28\tools\&#39;
The SHFBROOT system environment variable was not found.  This variable is usually created during installation and may require a reboot.  It has been defined temporarily for this process as: SHFBROOT=$(UserProfile)\.nuget\packages\EWSoftware.SHFB\2017.1.28\tools\
Locating components in the following folder(s):
    $(UserProfile)\.nuget\packages\EWSoftware.SHFB.NETCore\4.5.1\tools\Data\.NETCore\
    $(ProjectDir)
    $(ProgramData)\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    $(UserProfile)\.nuget\packages\EWSoftware.SHFB\2017.1.28\tools\
    Last step completed in 00:00:00,0230
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0071: Unable to locate information for the project framework version &#39;.NETCore 4.5.1&#39; or a suitable redirected version on this system.  See error number help topic for details.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>
```

**Comment by EWSoftware** [comment]
Can you give me an example or a walkthrough that I can use to duplicate the problem?  I don't do .NET Core development so I'm not familiar with what project type to select etc. to create a test to use for the documentation source.

**Comment by couven92** [comment]
Well because of that I simply select the `.dll` and `.xml` file as `DocumentationSource` properties in the `shfbproj`. Then I create myself a separate bundling project with the right dependencies to ensure that all `.dll` and `.xml` files are in the right places for SHFB.

With the new .NET Core tooling in VS2017, there is no big difference to the usual `.csproj` files, but if you'd like an example you can look at https://github.com/couven92/thnetii-interopservices/blob/vs2017/bundle/THNETII.InteropServices.Documentation

**Comment by EWSoftware** [comment]
I don't know what you're doing with regard to a "bundling project".  [That example](https://github.com/couven92/thnetii-interopservices/blob/vs2017/bundle/THNETII.InteropServices.Documentation/THNETII.InteropServices.Documentation.shfbproj) is not a valid SHFB project file.  As such, there is no guarantee that it will build.  If I create a standard SHFB project, add your C# projects as documentation sources, set the framework version, and build it, it completes properly.  Stay with the proper format and it should work without issue.

**Comment by couven92** [comment]
I compared my file to a default produced by SHFB GUI and I don't see how mine is incompatible. The only a little more sophisticated MSBuild stuff I do, are steps I do independent of the SHFB build process.

But well, of you're saying that you completely intolerant of any customization, I'll just have to create a competing MSBuild compatible tool instead.

-- 
Fredrik Høisæther Rasch 
Bruveien 9 
9020 Tromsdalen 
Norway 

Phone: +47 94847169 
Email: fredrik.rasch@gmail.com 

Sent from my HTC

----- Reply message -----
