### ISSUE TITLE
Plugin suggestion: Github reference links

### ISSUE THREAD

**Issue by WildCard65** [EWSoftware/SHFB#411]
A plugin that adds github repos as a location for reference links.

Reason for suggestion: I have a project using SHFB but I'm getting unresolved reference warnings because I'm referencing content from a nuget package, the source code for the package is on github.

**Comment by EWSoftware** [comment]
The [Additional Reference Links plug-in](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm) already exists for this.  Reference links are built off of the assemblies and XML comments for the list pages are pulled in from the related XML comments files.  That info can't be obtained from a repo.

You should be able to set up an additional project for the plug-in configuration that uses the assembly and XML comments file from the packages folder.  That should be enough for it to generate the link info to suppress the warnings.

**Comment by WildCard65** [comment]
How do I configure that plugin? I tried it with my project's SHFB and a test for <inheritdoc/ and got this warning:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		No comments found for cref 'M:SteamKit2.WebAPI.AsyncInterface.TryInvokeMember(System.Dynamic.InvokeMemberBinder,System.Object[],System.Object@)' on member 'M:SteamBotV2.Steam.Web.Authenticate(System.UInt32,SteamKit2.SteamClient,System.String)'	DocGenerator	SHFB	0	
```
