### ISSUE TITLE
Overload cref in C++/CLR header does not produce link.

### ISSUE THREAD

**Issue by mozzis** [EWSoftware/SHFB#413]
Given the following code (in C++/CLR):
```csharp
namespace Name
{
    public ref class Bar
    {
        public:
        /// <summary>
        /// Does something useful <see cref="O:Name.Bar.Foo"/> methods.
        /// </summary>
        public bool DoSomething();
        /// <summary>
        /// Produces foo result of int.
        /// </summary>
        /// <param name="param">The int to with which to foo.</param>
        public void Foo(int param);
        /// <summary>
        /// Produces foo result of string.
        /// </summary>
        /// <param name="param">The string with which to foo.</param>
        public void Foo(string param);
   ```
The generated HTML will have just  `<span class="nolink">Foo</span>` in the summary for `DoSomething` so the help page will just show **DoSomething** in bold with no link.

**Comment by WildCard65** [comment]
in C++ /CLR to reference stuff, you do it in C++ syntax (eg: System::Console::WriteLine("X"); // Calls Console.WriteLine)

**Comment by EWSoftware** [comment]
Check your C++ project's build log.  Unless you've suppressed it, there's probably a warning in there about it not liking the unknown symbol "O:Name.Bar.Foo".  In the resulting XML comments file for the assembly, you'll probably see that the ID is prefixed with "!:" indicating that it's not valid.

The C++ compiler appear to always validate the IDs even when fully qualified unlike the C#/VB compilers.  You can use the Member ID Fix-up plug-in to fix the IDs.  Use a match expression of "!:O:" with a replacement expression "O:".  That should take care of it.

**Comment by WildCard65** [comment]
@EWSoftware I've used C++ /CLR myself and xml docs require using C++ syntax to reference stuff.
example:
```
/// <summary><see cref="System::String::Equals(System::String)"/> is valid XML DOC.</summary>
```
vs
```
/// <summary><see cref="System.String.Equals(System.String"/> isn't valid XML DOC.</summary>
```

**Comment by EWSoftware** [comment]
@WildCard65:  That's not what's being asked about here.  The case here is a special ID prefix that links directly to an Overloads topic page, not a specific overloaded member topic.  That's done using the [O: prefix](http://ewsoftware.github.io/XMLCommentsGuide/html/ee5d612e-914f-411f-bd95-23478b15e4de.htm).  The overload topic ID has no parameter info.

**Comment by mozzis** [comment]
Thanks, @EWSoftware. I think that this is in fact the issue. FWIW I am able to use C# syntax in XML doc comments and it seems to work. Will follow up after I try the fix you suggested,

**Comment by mozzis** [comment]
OK, that fixed it. For the record, I fully qualified one of the overload references using C++ syntax and that one still did not work. Changing it to C# syntax fixed it. I know that sometimes the C++ syntax has worked for this project but apparently not for this case (or this VS version?)

**Comment by EWSoftware** [comment]
I'll add the expression as one of the common C++ fix-ups.

**Comment by mozzis** [comment]
Thanks, @EWSoftware! As always great support for this (free) product.
