### ISSUE TITLE
Sample generated files for API reference available?

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#417]
Hello,

I have to document some none .NET APIs manually, but would like to use the same style that's generated for .NET assemblies. So I'm looking for some "samples" of generated files to use this kind of documentation for my manually tasks. I'm interested especially in the part below the code snippet in the "Syntax" region for parameter description and return value for a documented function. Could not reproduce it with a conceptual template "Reference With Syntax". Another interest is on the page with the class overview/summary of constructors, fields, properties, etc.

Are the generated files of MAML syntax or different?

Regards

Holger

PS: Many thanks for your work out of Sandcastle Help File Builder. I start since two weeks to use it for a wide range of documentation.

_Sample pictures:_

Method description

![methoddescription](https://cloud.githubusercontent.com/assets/10100623/23830887/42a437c8-0715-11e7-8273-cd301c31a487.png)

Class overview

![classoverview](https://cloud.githubusercontent.com/assets/10100623/23830886/42a2c4d8-0715-11e7-9d4f-a666177d8590.png)

**Comment by EWSoftware** [comment]
There are a couple of conceptual templates for API topics but support for them is hit or miss and not all elements they include are present in the XSL transformations.  There's been no real call for them since the API stuff is generated off of the assemblies so I've not bothered to try and support all the various MAML elements.

That said, it's easy enough to create your own template that mimics the API topic layout using the existing MAML elements.  You can create them for [Visual Studio](http://ewsoftware.github.io/SHFB/html/ece3a395-589f-45c3-9f0e-2a25b8b6c537.htm#!) or for the standalone GUI by putting them in the [user-defined file templates folder](http://ewsoftware.github.io/SHFB/html/a24489fb-45d6-46f4-9eaa-9a9c4e0919b2.htm#FileTemplates).

You can use standard `section` elements to create the sections and `code` elements to create the syntax section examples.  You'd have one `code` element for each of the various languages.  They'd be grouped into tabs as usual when the topic was built.

Lists like those for the members can be created with the `table` element.

**Comment by VBWebprofi** [comment]
That's in your answers is what I could easily develop by my own.

a)
But how the sub-section? of "**Parameters**" is made by MAML tags? I sticked around but found no right solution. Using a "_list_" gave me no ride of the italic parameter names.

b)
Next in this section is how to get line break (not paragraph?) between "Type" and description of parameter without using a "_markup_" and HTML "_br_" tag?

c)
The other question is to the class overview for the different sections, currently I develop as tables - is the a special MAML tag set to structure this?

d)
I understand right, that MAML isn't used for generating the reference of the assemblies from XML and reflection? It's true XSL transform of VS XML documentation file and an reflection XML of your own?

**Comment by EWSoftware** [comment]
You can use a `sections` element nested within a `section` element to create sub-sections.  See the standard [conceptual topic](http://ewsoftware.github.io/MAMLGuide/html/30797814-3a36-4844-b348-9c97b61c74f2.htm) example.  That should take care of the spacing issue between sections.

Using a [definition table](http://ewsoftware.github.io/MAMLGuide/html/cb59e91c-f3cd-4086-a7ea-e2413a626e3d.htm) you can come close to the parameters section layout with the parameter names and an indented description.  As above, that should take care of any spacing issues between parameters.

As noted, you can use sub-sections to create the Methods, Properties, Events etc. sections.  The list of members with each can be generated using MAML [table element](http://ewsoftware.github.io/MAMLGuide/html/ec11472a-8a9c-44e7-9d32-45f671526922.htm).

You can come close but you won't get an exact match to the API topics.  As noted, the API topics are generated directly from the reflection data and XML comments.  They don't get translated to MAML first.

**Comment by VBWebprofi** [comment]
OK, i tried first also the _[definition table](http://ewsoftware.github.io/MAMLGuide/html/cb59e91c-f3cd-4086-a7ea-e2413a626e3d.htm)_ for parameter description but got not ride of changing the bold of "_definedTerm_" to italic.

Last problem on this MAML topic not cleared (was question _b_ an my former reply):

How to get a simple line ("_br_" in HTML) break in MAML without the doble encoding with "_markup_" and "_br_"?

**Comment by EWSoftware** [comment]
Like I said, you won't get an exact match for the style.  The formatting of the definition list is different than that used for the parameters section in the API topics.  If you want full fidelity with the API topics your only option is to create a presentation style that implements the [Reference with Syntax](http://ewsoftware.github.io/MAMLGuide/html/1a3f0cb3-4ea0-467a-8f53-32daffe3336b.htm) elements completely.

There is no equivalent of a line break element in MAML.  That may seem odd but there's rarely if ever a need for one when you use the standard MAML elements.  That said, it wouldn't be too hard to add one to the presentation styles as a custom element.

If you use the definition list, you'll get a natural line break between the term and the definition.  If you want to use a paragraph element and want an actual line break within it, then you do need to use a markup element to insert the HTML `br` element.

**Comment by VBWebprofi** [comment]
OK, I expected that answer. :disappointed_relieved:

Have now build a some "templates" for my purposes as mix from MAML and markups with HTML.

[1] Sample from my template
![sampleparameters](https://cloud.githubusercontent.com/assets/10100623/23837975/c1e35458-0790-11e7-9d9d-0aa7e6413a1c.png)
