### ISSUE TITLE
Rendered MAML alerts "implement" and "inherit" missing title

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#421]
If I use ``<alert class="implement">...</alert>`` or ``<alert class="inherit">...</alert>`` both rendered alert boxes having no title, see attached screenshot 2. It occurs in VS2010 and VS2013 presentation styles as seems independend from chosen language (tested with "en-US" and "de-DE"). Same as "note" with type "implement" get rendered well.

Is there any "short" fix in XSL or so?

 

[1] Screenshot code

<img width="298" alt="alerts code" src="https://cloud.githubusercontent.com/assets/10100623/23832071/35559dd2-072e-11e7-94fb-fbf0cf5b995d.png">

[2] Screenshot rendered

<img width="106" alt="alerts rendered" src="https://cloud.githubusercontent.com/assets/10100623/23832079/665d4f92-072e-11e7-812c-93b83f2afafa.png">

[3] Note "implement" rendered

<img width="167" alt="note implement" src="https://cloud.githubusercontent.com/assets/10100623/23832084/81b90b1e-072e-11e7-8179-81a9db890d44.png">

**Comment by EWSoftware** [comment]
The three title elements for implement, inherit, and caller need to be moved from the reference content file to the shared content file with the other alert/note titles in each presentation style.  I'll get it fixed for the next release.

**Comment by VBWebprofi** [comment]
Cant I easly make this with the current release? Can you guide me?

**Comment by VBWebprofi** [comment]
OK, could follow your answer and solved the problem:

Take the three tags

```xml
<item id="text_NotesForImplementers">Notes to Implementers</item>
<item id="text_NotesForCallers">Notes to Callers</item>
<item id="text_NotesForInheritors">Notes to Inheritors</item>
```

**from** file "_[reference_content.xml](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/PresentationStyles/VS2013/Content/reference_content.xml#L205)_" (around line 205) **to** file "_[shared_content.xml](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/PresentationStyles/VS2013/Content/shared_content.xml#L33)_" under section "alert titles" (around line 33).

**Comment by EWSoftware** [comment]
Yes, that's correct.

**Comment by VBWebprofi** [comment]
Small piece of code to handle that task for all files:

```c#
    static void Main(string[] args)
    {
      //const String DIR = @"C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles";
      const String DIR = @"C:\_Storage\Tests\SHFB\Issue.421\PresentationStyles";

      XmlDocument source = new XmlDocument();
      XmlDocument target = new XmlDocument();
      String targetFile;
      XmlNode insertAfter;
      Int32 fileCount = 0;
      Int32 count;

      Console.Write("Start move ... ");

      foreach(String file in Directory.EnumerateFiles(DIR,
                                                      "reference_content.xml",
                                                      SearchOption.AllDirectories))
      {
        Console.SetCursorPosition(16,
                                  Console.CursorTop);
        Console.Write(++fileCount);

        targetFile = Path.Combine(Path.GetDirectoryName(file),
                                  "shared_content.xml");

        source.Load(file);
        target.Load(targetFile);

        insertAfter = target.SelectSingleNode("/content/item[@id='alert_title_visualJ#']");

        if(insertAfter != null)
        {
          count = 0;

          foreach(XmlNode item in source.SelectNodes("/content/item[@id='text_NotesForImplementers' or @id='text_NotesForCallers' or @id='text_NotesForInheritors']"))
          {
            insertAfter.ParentNode.InsertAfter(target.ImportNode(item,
                                                                 false),
                                               insertAfter);
            item.ParentNode.RemoveChild(item);

            count++;
          }

          if(count != 3)
          {
            Console.WriteLine();
            Console.WriteLine("ERROR: Only {0} of 3 items contained in file \"{1}\"!",
                              count,
                              targetFile);
          }

          target.Save(targetFile);
          source.Save(file);
        }
        else
        {
          Console.WriteLine();
          Console.WriteLine("ERROR: item \"alert_title_visualJ#\" missing in file \"{0}\"!",
                            targetFile);
        }
      }

      Console.WriteLine();
      Console.WriteLine("DONE.");

      Console.WriteLine();
      Console.Write("Press any key ...");
      Console.ReadKey();
    }
```
