### ISSUE TITLE
Is there any support of environment variables?

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#422]
Is there any support of environment variables to use in Token or Settings of Project except in pre and post build events?

Something like ``%USERNAME%`` or ``$(USERNAME)`` or ``{@USERNAME}`` or ``{@Env:USERNAME}`` ?

**Comment by EWSoftware** [comment]
Typically, you can use `{@CustomPropertyName}` within most text-valued properties like the header text, footer text, title etc. to insert a custom property value into a SHFB project property value.  That should also work within files such as token files to substitution property values within the text of their elements.

Environment variables are only pulled in as part of the build when using MSBuild directly from the command line or on a build server.  They aren't if built from within Visual Studio or the standalone GUI.

You can use the [User Defined](http://ewsoftware.github.io/SHFB/html/c4e3ce8e-6881-47a7-a429-49ec5c755c8c.htm) category to define custom project properties.  If building using MSBuild, you can use the `/p:Property=Value` command line option to override it.  You can use a conditional property named the same as an environment variable to supply an appropriate default if built from within Visual Studio.  If build using MSBuild, the environment variable value will override the conditional property value.

**Comment by VBWebprofi** [comment]
Thanks for that hint! :thumbsup: :sweat_smile:

**Comment by VBWebprofi** [comment]
Found a simpler way to do that (sample is USERNAME), in batch files as ''%USERNAME%''.

The build supports it directly without extra ``/p:Property=Value``.

Seems the common use of environment variable during build is ``$(<VariableName>)``, so I was able to create under "[User Defined](http://ewsoftware.github.io/SHFB/html/c4e3ce8e-6881-47a7-a429-49ec5c755c8c.htm)" a variable called ``USERNAME`` with Value ``$(USERNAME)`` and used it with ``{@USERNAME}`` on the my expected place in the "[Project Properties](http://ewsoftware.github.io/SHFB/html/c4e3ce8e-6881-47a7-a429-49ec5c755c8c.htm)".
