### ISSUE TITLE
Limit API output to .NET COM types only

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#425]
How can I configure a project to document **only public .NET types** from a _[COM visible library](https://msdn.microsoft.com/en-us/library/1h52t681.aspx)_ (`[assembly: ComVisible(true))` having no or _[ComVisibleAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.comvisibleattribute.aspx)_ with value "_true_"?

And two additional questions on that subject (may possible by selectiing value with XPath expression?):

a) How can I reference the _[GUID](https://msdn.microsoft.com/en-us/library/system.guid.aspx)_ value from the _[GuidAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.guidattribute.aspx)_ of such type?
b) How can I reference an optional _[ProgIdAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.progidattribute.aspx)_ value?

**Comment by EWSoftware** [comment]
There are no provisions for filtering by attribute type.  The API Filter is based only on the namespaces, types, and members.  A plug-in could be written to extend or replace the API Filter such as the Documented Entities Only Plug-In.  Other than that, you'd have to set the API filter manually.

I assume you want the values of the attributes for inclusion in an API topic.  If you enable the [attributes on types and members](http://ewsoftware.github.io/SHFB/html/3c489bd6-598c-4684-aafb-fbe9400864d3.htm#DocAttrs) Visibility category option, the Syntax Section will include attribute information including most COM-related attributes.  I think there are a few that don't show up though as they just don't appear anywhere in the assembly metadata that I could find.

The attribute values would be accessible at build time to the XSL transformations but there's no support for treating them like substitution tags.  You'd have to add a custom element to the presentation style XSL transformations to handle it.  As noted, that would only work for the ones that can be found in the assembly metadata.

**Comment by VBWebprofi** [comment]
❓ Go I right, only attributes, placed in the VS XML output can be handled?

**Comment by EWSoftware** [comment]
Attributes on types, members, and parameters in the code like GuidAttribute end up in the reflection.xml file produced by the MRefBuilder tool.  That info is combined with the XML comments to produce the topics.  Hopefully that answers the question.

**Comment by VBWebprofi** [comment]
You have it on board :smiley: !

Found the plugin "_[XPath Reflection File Filter](https://ewsoftware.github.io/SHFB/html/cd68ef02-3493-4af6-96de-1957b0aaf858.htm)_" which exludes the XPath selected elements, so it does exactly what I was looking for and the predefined query for contructors was also useful. I added the following filter:

```
/reflection/apis/api[attributes/attribute[type/@api='T:System.Runtime.InteropServices.ComVisibleAttribute']/argument/value = 'False']
```
, disabled all Options in the "_[Project Properties Window](https://ewsoftware.github.io/SHFB/html/e32086c6-de17-4e54-a746-1ac80bf0c45a.htm)_" at "_[Visibility](https://ewsoftware.github.io/SHFB/html/3c489bd6-598c-4684-aafb-fbe9400864d3.htm)_" except option "_[Attributes on types and their members](https://ewsoftware.github.io/SHFB/html/3c489bd6-598c-4684-aafb-fbe9400864d3.htm#DocAttrs)_" and got my expected output.

**Comment by VBWebprofi** [comment]
An additional exclude has to be placed for all extensions:

```
/reflection/apis/api/elements/element[@source = 'extension']
```

**Comment by VBWebprofi** [comment]
Another exclude placed for all "static" members:

```
/reflection/apis/api[memberdata/@static='true']``
```

**Comment by VBWebprofi** [comment]
One exclude I haven't documented here - excluding all constructors:

```
/reflection/apis/api[contains(@id,"#ctor")]
```
