### ISSUE TITLE
MAML content copy from other document possible per reference?

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#426]
As same as the generation of the API renders the summary of a member to overview (namespace, class, interface). Is it possible to do that also with MAML in manual build documentation?

I mean an analog system like the reference links, that linking the topic and unchanged having the title of that topic also. But now for content - reference to topic by ``xlink:href`` and an ``xpath`` attribute for content selection of which should be copied to the current document. Could be a MAML tag named like ``contentCopy`` without element content.

Sample code:
```xml
<contentCopy xlink:href="07b5dabc-85aa-4ba9-b8bf-0cbc79edfcad"
             xpath="developerConceptualDocument/introduction"/>
```

In that way the text can be edited on **one** place but used on several places.

**Comment by EWSoftware** [comment]
There isn't anything to do that now though a [build component](http://ewsoftware.github.io/SHFB/html/e6d18448-2459-46f1-bbdc-a7db415f2bda.htm) could probably be written to do it.  Given a topic ID, the related files can be found in the *.\ddueXml* sub-folder of the working folder during the build.

**Comment by VBWebprofi** [comment]
OK, have to study that subject.

**Comment by VBWebprofi** [comment]
❓ Is there any simple/small build component which I can use as blue print / template?

**Comment by EWSoftware** [comment]
You can take a look at the [project template files](https://github.com/EWSoftware/SHFB/tree/master/SHFB/Source/SandcastleBuilderPackage/Templates/Projects/BuildComponentCS).  That provides the basic framework and is referenced by the walkthrough topic.  If you copy them, note that you'll have to replace the substitution tags with a name of your choosing.

For live components see any of the [stock Sandcastle components](https://github.com/EWSoftware/SHFB/tree/master/SHFB/Source/BuildAssembler/BuildComponents).  The Additional Header Resources component is probably the simplest one.

**Comment by VBWebprofi** [comment]
Thanks for your advise. The component [ResolveConceptualLinksComponent](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/BuildAssembler/BuildComponents/ResolveConceptualLinksComponent.cs) seems to be a good blue print also for the ``legacyLf`` request #431.

But if the merge during rendering it would not go right. I have to manipulate the XML document before rendering in case I see a [``navigator.DeleteSelf();``](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/BuildAssembler/BuildComponents/ResolveConceptualLinksComponent.cs#L262) after rendering is done.

**Comment by EWSoftware** [comment]
`legacyLf` can be handled purely through the XSL transformations so no need for build component on that one.  It will go in the presentation styles.  Build components are only needed when there's something you need to do that can't be done in an XSL transformation such as more complex manipulation of the content such as adding colorization to code snippets or merging content from external files as in this case.

Documentation is rather sparse on the underlying build tools.  Its something I keep meaning to get around to but haven't yet.  The BuildAssembler tool is passed a configuration file containing the component stack to load and a manifest file containing a list of all the topics.

Build components are initialized once before any topics are rendered.  A component to copy content from other topic files probably wouldn't need much beside a configuration option telling it what the working folder is for the build.  That can be done with an element that has the `{@WorkingFolder}` substitution tag as its content so no need for a configuration dialog.  Note that you'll be loading the raw topics to copy content from, not the ones created by the BuildAssembler tool.

The `Apply` method is called once for each topic.  It's passed the topic ID and the document content as it exists at the point in time the component is called.  Your component would probably do something like the following:

- Search for all instances of `contentCopy` in the current topic.
- For each one, get the topic ID and the XPath query used to copy the content.
- Look in the working folder in the *.\ddueXml* folder for a file named with the topic ID and a *.xml* extension.
- If found, load that file and execute the XPath query to get the content to copy.
- Replace the `contentCopy` element in the current topic with the copied content.

If you're curious, you can turn off the *Clean intermediate files after a successful build* option in the Build category.  It will leave the working folder in the output path and you can see all the files related to the build.

**Comment by VBWebprofi** [comment]
:repeat: Additional point would be to detect cycles.

**Comment by EWSoftware** [comment]
The build components use MEF (Managed Extensibility Framework).  You define a factory class within the component with the necessary export attribute so that it can be found and created by SHFB.  The factory class defines the placement options, default configuration, etc.  See the [template component](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPackage/Templates/Projects/BuildComponentCS/BuildComponent.cs) for an example.
