### ISSUE TITLE
Missing syntax highligthing for batch commands

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#427]
I have also batches to document, but syntax highlighting is not available, tried to use "powershell" but with less success. Powershell may have a more different command set.

Is this a problem of existing Microsoft components or is syntax highlighting part of SHFB implementation?

How can the problem solved?

**Comment by EWSoftware** [comment]
There is some support for PowerShell for syntax highlighting but nothing specific to batch files.  Syntax highlighting is provided by SHFB using the open source Code Colorizer library.  It's got a [configuration file](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/CodeColorizer/ColorizerLibrary/Template/highlight.xml) that defines the languages supported and the expressions used to classify the text and color it accordingly.  Search through that for "pshell" and you'll see the stuff that it handles for PowerShell.

**Comment by VBWebprofi** [comment]
❓ How about supporting "_outlining_" for batch files?

**Comment by EWSoftware** [comment]
It might be possible.  Right now it only looks for code-like directives (nothing other than whitespace before the directives #if, #region, #else, and #endregion).  Those aren't typically found in batch files so they'd have to be in a comment statement of some sort.

**Comment by EWSoftware** [comment]
I've added rules to the colorizer for batch files.  I've opted not to support outlining though.
