### ISSUE TITLE
Region rendering of Batch code with MAML code tag inaccurate

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#428]
Rendering a Batch file with ``rem #region`` and ``rem #endregion`` has an "unremoved" rem at the end of code (from #endregion).

Reference

```xml
<code language="powershell"
      region="Output"
      source="Batch.bat"/>
```

to this file content

```batch
@echo off

rem #region Output
echo output comes from here
rem #endregion

echo more output here
```

renders

```batch
echo output comes from here
rem
```

but should render only
```batch
echo output comes from here
```

**Comment by EWSoftware** [comment]
The Code Block Component doesn't know about the batch file REM prefix on regions.  It currently only knows about XML/XAML style "<--", C style "/*", and SQL style "--" prefixes.  It can be updated to include "REM" too.

**Comment by VBWebprofi** [comment]
That would be fine.

I had expected it removes the whole lines as it identifies both matching region tags?

**Comment by EWSoftware** [comment]
For code files, #endregion typically does appear on its own line with nothing preceding it except whitespace.  For non-code files that's typically not the case as they have to be embedded in a comment of some sort so the component has to remove the comment prefix.
