### ISSUE TITLE
MAML code tag supported "numberLines" and "outlining" attributes missing in XML schema

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#429]
I checked out the using of both attributes at MAML "_[code](http://ewsoftware.github.io/SHFB/html/7f03ba39-09f8-4320-bdbd-ed31a3bd885f.htm)_" tag and they work. But I don't got them with XML schema IntelliSense. Maybe the other notified attributes too?

So XML schema should be enhanced with them.

**Comment by EWSoftware** [comment]
Visual Studio only knows about the standard set of XML comment tags and their attributes.  Sandcastle extensions won't show up in Visual Studio.  There is some support for inserting the extensions if the SHFB package is installed.  I don't recall off-hand if the MAML schemas were updated with the extensions.  Not all of them might be there.

See the [XML Comments Guide](http://ewsoftware.github.io/XMLCommentsGuide/html/4268757F-CE8D-4E6D-8502-4F7F2E22DDA3.htm) for a list of the comments tags and their attributes.  The topics list which ones are standard and which ones are extensions.

The [MAML Guide](http://ewsoftware.github.io/MAMLGuide/html/303c996a-2911-4c08-b492-6496c82b3edb.htm) provides similar info for the MAML elements supported by SHFB.

**Comment by VBWebprofi** [comment]
That's not true, if you add them to "_[code](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Deploy/Schemas/Authoring/blockSoftware.xsd#L22)_" element like your extensions with "_[title](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Deploy/Schemas/Authoring/blockSoftware.xsd#L60)_", "_[source](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Deploy/Schemas/Authoring/blockSoftware.xsd#L68)_" and "_[region](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Deploy/Schemas/Authoring/blockSoftware.xsd#L76)_", it works, tested yet.

**Comment by EWSoftware** [comment]
Sorry, I saw "XML schema IntelliSense" and thought "XML comments IntelliSense".  The elements and attributes from the guide are all supported but, as noted, the extensions may not be in the schemas.  The extensions that have been added should all be marked with a comment noting they are Sandcastle/SHFB extensions.

**Comment by VBWebprofi** [comment]
There is an improvement of all supported tags and attributes (from your documentation) required. Found also ``removeRegionMarkers`` missing at the ``code`` element.

Do you have a list of all supported elements and their attributes?

**Comment by EWSoftware** [comment]
The XML comments guide and the MAML guide are the source to go to for all supported elements and their attributes.

**Comment by VBWebprofi** [comment]
Pull request added for improved "_code_" element.

**Comment by EWSoftware** [comment]
Fixed by pull request #444.
