### ISSUE TITLE
Missing MAML legacy tags for superscript and subscript

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#430]
Can the support of this two styles added as ``legacySup`` and ``legacySub``?

**Comment by EWSoftware** [comment]
The [subscript](http://ewsoftware.github.io/MAMLGuide/html/27f10273-2112-47fd-baf4-5ee90e79fba4.htm) and [superscript](http://ewsoftware.github.io/MAMLGuide/html/6a9e1e0c-4e15-43e0-af9f-8ac9c1ab3b0c.htm) elements should work unless there's a difference in how they should be handled.

**Comment by VBWebprofi** [comment]
Oh, yes. Sorry overseen it.
