### ISSUE TITLE
Request legacy line feed support

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#431]
I'm missing a legacy support of line feed  (not paragraph) like HTML "br" tag especially for organizing table content.

The tag named ``legacyLf`` should be an inline tag without content.

**Comment by EWSoftware** [comment]
Yes, that should be pretty straightforward.

**Comment by EWSoftware** [comment]
A later revision of the MAML spec includes a `lineBreak` element.  I've add support for that to the presentation styles and schema.
