### ISSUE TITLE
Nuget EWSoftware.SHFB: not working without installed SHFB

### ISSUE THREAD

**Issue by ptr1120** [EWSoftware/SHFB#433]
The description of the nuget says: "This package allows you to deploy the Sandcastle Help File Builder tools inside of a project to build help files without installing the tools manually such as on a build server.", but I can not find a possible way without installing SHFB.

Steps to reproduce:
* create a .Net4.5 Project
* Install-Package EWSoftware.SHFB
* Install-Package EWSoftware.SHFB.NETFramework
* create a documentation project with sandcastle gui
   * add your project as documentation source 
   * select Help Format: Markdown
   * select Help File -> Presentation Style -> Markdown
  * add manually into the the .shfbproj file (beginning of first PropertyGroup):
 ```
 <ComponentPath>..\..\packages\</ComponentPath>
      <SHFBROOT Condition=" '$(SHFBROOT)' == '' >$(MSBuildThisFileDirectory)..\..\packages\EWSoftware.SHFB.2017.1.28.0\Tools\</SHFBROOT>
```
* build project
* rename C:\Program Files (x86)\EWSoftware
* build Help: MSBuild.exe  /p:Configuration=Release myProject.shfbproj

Expected: Markdown Help File beeing generated
Actual: Building of Help fails:

```
Transforming reflection output...
[C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe - TransformManifest.proj]
Build started 17/03/2017 16:12:00.
Project MyProject\Help\Working\TransformManifest.proj&quot; on node 1 (default targets).
TransformManifest:
  XslTransform (v2017.1.28.0)
  Copyright &#169; 2006-2017, Microsoft Corporation, All Rights Reserved.
  Portions Copyright &#169; 2006-2016, Eric Woodruff, All Rights Reserved.
XslTransform : error : The transform file &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\\ProductionTransforms\ApplyVSDocModel.xsl&#39; could not be loaded. The error is: Could not find a part of the path &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\ProductionTransforms\ApplyVSDocModel.xsl&#39;. [MyProject\Help\Working\TransformManifest.proj]
Done Building Project &quot;MyProject\TransformManifest.proj&quot; (default targets) -- FAILED.
```

**Comment by EWSoftware** [comment]
Renaming the installation folder isn't enough if you've actually got the tools installed normally.  Remember that the SHFBROOT system environment variable is still defined and the tools ran by the tasks will still find and use it.  That's why you still see the standard installation path in the error message.

You need to execute `SET SHFBROOT=` from the command line first to undefine the environment variable in the current instance of the command prompt.  After that, the tools will default to using their location as the root folder which will be in the packages folder.

**Comment by ptr1120** [comment]
Many thanks! You are right, everything works as expected when doing `SET SHFBROOT=`

Have a nice weekend,
Peter
