### ISSUE TITLE
Why translations in each PresentationStyle?

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#434]
❓ I saw each presentation style has its own translations. Why? Why not having one translation file for each language which will be used independend in all presentation styles?

**Comment by EWSoftware** [comment]
Not all presentation styles have the same elements or the same format.  For example, Open XML doesn't contain all of the same localizable elements as the others and it is not HTML-based.  The Markdown style also differs in formatting in some cases.  Also, it would require that each and every presentation style commit to using identical IDs and the same text and formatting for all of the shared items.  Those would be a pretty tough rules to enforce.

Each presentation style is a standalone entity which can change independently of the others.  As older presentation styles age out and get deprecated, I don't have to maintain them with any new stuff or updates that get add to the current ones like support for new elements or changes to existing ones.

**Comment by VBWebprofi** [comment]
OK, I will start improving the German translation next time.
