### ISSUE TITLE
Request of anchors for line numbers in "code" rendering

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#435]
I miss an anchor (``<a name="$CodeLineNumber$"/>``) at each code line rendered.

Second, if scripts are possible, then highlightning like here on githubs code display should be done (see [line 6 of MasterBuild.bat](https://github.com/EWSoftware/SHFB/blob/master/MasterBuild.bat#L6) following the underlaying link).

``$CodeLineNumber$`` should be combined from "_address_" of "_[code](https://ewsoftware.github.io/SHFB/html/7f03ba39-09f8-4320-bdbd-ed31a3bd885f.htm)_" tag and "L" prefixed line number. If _address_ of _code_ not set then only "L" prefixed line number should be rendered.

Samples:

``<a name="MyCode_L123"/>`` with available _code_ _address_
``<a name="L123"/>`` without _code_ _address_

**Comment by EWSoftware** [comment]
I don't see much value in this for code examples within topics.  They're generally small enough that linking to specific lines isn't of much use.  Trying to add line highlighting would also probably require an overhaul of how the code is rendered.  That's probably a lot of work for a feature that I don't see getting much use.

It makes sense for viewing the API source code files and the ability already exists to generate [links to the online repo](http://ewsoftware.github.io/SHFB/html/e6fcfa33-e7ee-430a-abfe-6b7962e6d068.htm#SourceCodeBasePath) for those.

**Comment by VBWebprofi** [comment]
I have longer pieces of code (complete files) to document in such case it's helpful not only have the line numbered, also to can jump to it.

**Comment by EWSoftware** [comment]
After due consideration, I'm going to decline this request.  I feel that it would involve a lot of work as it would require changes to the code colorizer plus the presentation styles.  It would probably also have to handle the combined examples in some way (i.e. multiple languages combined into the tabbed sections).  I just don't see enough use out of it for the time that would be needed to implement the changes.
