### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by sooqua** [EWSoftware/SHFB#440]
How can I generate the documentation for a .NET Standard library?
I get this error, because the structure of .csproj was significantly changed for .NET Standard projects:
`SHFB: Error BE0065: BUILD FAILED: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.`

**Comment by EWSoftware** [comment]
The version of MSBuild that SHFB is built against doesn't know how to handle the .NETStandard project format nor does SHFB know about the .NETStandard project type.  For now, add the assembly and XML comments file as documentation sources rather and pick a framework version that's close to what it's supposed to support.  You may have to experiment with the framework version for now.

Work on support for .NETStandard is ongoing.

**Comment by DecaTec** [comment]
That's a good hint with referencing the assembly and XML directly.
Even better than the workaround with the dummy project (with linked files) for documentation as described here: https://github.com/EWSoftware/SHFB/issues/255
