### ISSUE TITLE
Request of "linkAlternateText" attribute at "codeEntityReference"

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#441]
I want request a "_linkAlternateText_" attribute for rendering a tooltip (anchor title attribute) at a "_[codeEntityReference](http://ewsoftware.github.io/MAMLGuide/html/bc490dbf-7d46-432d-a816-3ae16ab6af54.htm)_" link, following the "_linkAlternateText_" element at "_[externalLink](http://ewsoftware.github.io/MAMLGuide/html/d0c9ce6d-115b-4c70-891c-69b4af944dea.htm)_".

**Comment by EWSoftware** [comment]
What purpose would it would serve?  Code entity references just go to API members.  I'm not sure I see any real need for alternate text on those, they're pretty self-explanatory.

**Comment by VBWebprofi** [comment]
Yes and No. A well formed HTML has a _title_/tooltip. I want add a title like "See class System.Exception at MSDN ...".

```xml
<codeEntityReference qualifyHint="true"
                     linkAlternateText="See class System.Exception at MSDN ...">T:System.Exception</codeEntityReference>
```

Otherwise a question back, what's purpose of "_linkText_" attribute?

**Comment by EWSoftware** [comment]
`linkText` does have a purpose much like specifying inner text on the XML comments `see` element.  It lets you specify wording for the link that flows better with the context of its use.

``` XML
There are several different <codeEntityReference
    linkText="project types">T:MyNamespace.ProjectType</codeEntityReference>
    available for use.
```

Adding a title attribute that tells you the class name specified as the link text is on MSDN which you can see in the URL when you hover over the link adds no real benefit as there isn't any new information that isn't already there.  The title attribute should only [add additional or advisory info](https://www.searchenginejournal.com/how-to-use-link-title-attribute-correctly/).

The presentation styles simply render a `referenceLink` element which is then processed by the `ResolveReferenceLinksComponent` to render the actual link based on the help file format.  It would have to change as well to support the alternate text.  It's a fairly straightforward change too.  However, I still don't see it adding any value.  It's of benefit to `externalLink` as they are generic links that can go anywhere.  `codeEntityReference` is for API links so there isn't really anything else to add.

**Comment by VBWebprofi** [comment]
OK, see different view points of us. So I like to ask, what's happen as I make that changes also in ``ReferenceLinkInfo`` and in ``ResolveReferenceLinksComponent`` would you pull this changes or not?

**Comment by EWSoftware** [comment]
Sorry, in this case, I'm going to decline the change request.

**Comment by VBWebprofi** [comment]
OK, so I leave it in a separate master branch of my repoository.
