### ISSUE TITLE
Custom Error Page

### ISSUE THREAD

**Issue by Rabadash8820** [EWSoftware/SHFB#445]
This may be too large of a request for one issue, but I figured I'd just put it out there.  I host my built documentation website with AWS S3/CloudFront, which allows me to configure custom error pages for 4xx and 5xx HTTP errors.  I assume that other services like Azure offer similar features.  A custom error page would make my docs feel much more professional, rather than just an ugly empty page saying "404 Not Found" with nothing to do but click the browser's back button.  It would be really great if there was an option in the SHFB project to add a custom error page, in the current presentation style, for at least a subset of those error codes.

**Comment by EWSoftware** [comment]
There is a Web.config file which you could probably customize to do it assuming your site is running ASP.NET.  You can place a copy of it in the root of the SHFB project along with any relevant custom error page, set their Build Action property to Content, and they'll get copied to the root of the website output when the project is built.

If you can or must configure such error page redirections on the server, you can still include the custom error page in the project that you redirect to as noted above without the Web.config file.

**Comment by Rabadash8820** [comment]
@EWSoftware  I know _how_ to do the error redirects, I'm just not good enough with HTML/CSS to _design_ a custom error page.  So I'm requesting that such an error page be a part of SHFB, using the presentation styles that you have already defined.  Users could just check a checkbox in the Project Properties for whether they want to include these error pages in their builds.

**Comment by EWSoftware** [comment]
Can you tell me what you want the page to say and what kinds of errors to cover if that's applicable?  If so, I can put together a page that fits with the presentation style.  I can throw together a generic "An error occurred" page but if there's something more you want, I need to know.

**Comment by Rabadash8820** [comment]
Well first of all, I guess error pages aren't really necessary for the non-internet help formats because users can't just type whatever they want into a browser bar.  So this issue only goes for the "Markdown (md)" and "Website (HTML/ASP.NET)" help formats.

Personally, I would just want an error page that is consistent with the websites that the existing presentation styles are based on.  For example, here is a 404 error page from MSDN, which I imagine you based the Website format on:

![image](https://cloud.githubusercontent.com/assets/8388785/24473178/5b6fd71a-1496-11e7-97e5-1ea5345e83e3.png)


and here is the 404 error from GitHub, which I assume you based the Markdown format on (I'm not sure because I can't build the Markdown in VS2015) :

![image](https://cloud.githubusercontent.com/assets/8388785/24474097/89639604-1499-11e7-9cbf-e38f4a51cf3e.png)

As for the error codes that you should support, I would personally like to see the codes returned by AWS covered.  [This page](https://docs.aws.amazon.com/AmazonS3/latest/dev/CustomErrorDocSupport.html) lists the error codes currently returned by S3, and [this page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distributionconfig-customerrorresponse.html#w1ab2c19c17d101b9) lists the error codes returned by CloudFront.  The MSDN one serves as a nice template; you could just change the title to say something like "Forbidden" or "Malformed Request" when those HTTP errors are returned.  That first link also shows a screenshot of the default S3 error page, which I am currently receiving when 404 errors occur, and is obviously not in keeping with the MSDN look and feel.

**Comment by EWSoftware** [comment]
I'm not sure there's much point in doing anything for markdown.  You have no control over error redirects unless the site you upload to lets you.  For example, enter an invalid page title here in GitHub and at least for the SHFB site's wiki, it just doesn't do anything.  As far as formatting goes, markdown is easy enough to create so adding a few pages if you can configure the error codes for redirection can be done using the method noted in my first reply.

I'll see what I can come up with for the HTML sites.

**Comment by Rabadash8820** [comment]
I did come across this article:

[Creating a custom 404 page for your GitHub Pages site](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/)

However, that's just for GitHub, and just for 404; as you say, there are plenty of other sites where users might upload a Markdown help file where custom errors are _not_ supported.  I'm obviously most interested in the HTML sites, so anything you can come up with there would be awesome.

Either way, thanks for your responses!

**Comment by EWSoftware** [comment]
I added GeneralError.htm and PageNotFound.htm to the VS2010 and VS2013 presentation styles and updated their Web.config files to use them for general errors and 404 errors respectively in website output.  If these aren't sufficient or you want to change the wording, you can add them to an .\html folder in the SHFB project and customize them as you see fit.  You can also clone them and update the Web.config file to handle any other specific error codes that you want.
