### ISSUE TITLE
SHFB attempts to document properties that don't exist

### ISSUE THREAD

**Issue by victor-david** [EWSoftware/SHFB#446]
When you have a static definition for an attached dependency property that includes corresponding static methods to get /set the DP, SHFB attempts to document the corresponding .NET property even though it doesn't exist. For instance:
```c#
public static DependencyProperty DoubleClickCommandProperty = DependencyProperty.RegisterAttached
(
  "DoubleClickCommand", typeof(ICommand), typeof(DataGridExtended), new PropertyMetadata(DoubleClickPropertyChanged)
);

public static ICommand GetDoubleClickCommand(DependencyObject obj)
{
    return (ICommand)obj.GetValue(DoubleClickCommandProperty);
}

public static void SetDoubleClickCommand(DependencyObject obj, ICommand value)
{
    obj.SetValue(DoubleClickCommandProperty, value);
}
```

SHFB then attempts to document the corresponding .NET property, i.e.

```c#
public ICommand DoubleClickCommand
{
   get { ... } 
   set { ... } 
}
```

even though this property is not declared. During the build, SHFB says

My.Namespace.DoubleClickCommand Missing &lt;summary&gt; documentation 

and inserts a non-existent property into the output help file with the red "Missing" notice. The topic for this property does say "See GetDoubleClickCommand, SetDoubleClickCommand", but there seems to be no way to correct the missing summary since the property doesn't actually exist.

**Comment by EWSoftware** [comment]
This is by design.  They're attached properties and events.  The compiler does create them so they do get included for documentation.  You can use the [AttachedEventComments](http://ewsoftware.github.io/XMLCommentsGuide/html/3563f000-5677-4cd9-afd7-4e3f2a7fe4fc.htm) and [AttachedPropertyComments](http://ewsoftware.github.io/XMLCommentsGuide/html/c0346d23-f376-4948-8f9a-d17b2f1acef3.htm) XML comments elements to document them.

If you don't want them included, you should be able to exclude them with the API filter.

**Comment by victor-david** [comment]
Thank you. I didn't know that about AttachedPropertyComments.

Something a little odd, or maybe I'm just missing something. Your docs say:

> ...**GenerateInheritedDocs** tool. As part of the process of generating inherited documentation, the tool will look for attached property and attached event fields. If it finds them, it will automatically inherit their comments for the related compiler-generated members as default comments to prevent a "missing comments" warning.

Yet, this doesn't work (that is, I get the "missing") until I've used at least one AttachedPropertyComments. Of the four places in my app, once I place an AttachedPropertyComments in a single one of them, the rest do the inheritance like you mention. But not until then. This is reflected in the build output. With at least one usage of AttachedPropertyComments, the build output says:

> Generating inherited documentation...
...
Merging inherited documentation...

But with zero usages of AttachedPropertyComments, this info about inherited docs does not appear in the build output.

So, I don't know if that's the way it's supposed to be or not, but that's my experience. Meanwhile, many thanks for steering me in the right direction on how to get things properly documented.

**Comment by EWSoftware** [comment]
It should be inheriting the backing field's comments in the absence of the other elements.  I'll have to check that out.

**Comment by victor-david** [comment]
Thanks. Meanwhile, I've got things working at my end. Appreciate the tips.

**Comment by EWSoftware** [comment]
I wasn't able to duplicate the problem with the missing comments if inherited from the backing field/event.  As long as there were XML comments they did seem to get inherited correctly.  It could be something specific to your case.  If you'd like to give an example of one that didn't inherit, I can look into it.

**Comment by victor-david** [comment]
I'm not sure what I can give you that I haven't already. In my app, I declare 4 or 5 attached dependency properties without a corresponding .NET property. Therefore, these are the auto-generated ones. With XML comments, here's an example:

```c#
        /// <summary>
        /// Defines an attached dependency property that enables the consumer to manipulate the data columns from a view model.
        /// </summary>
        /// <remarks>
        /// See:
        /// http://stackoverflow.com/questions/3065758/wpf-mvvm-datagrid-dynamic-columns
        /// </remarks>
        /// <AttachedPropertyComments>
        /// <summary>
        /// This attached property provides access to the data columns.
        /// </summary>
        /// </AttachedPropertyComments>
        public static readonly DependencyProperty ColumnsProperty =
            DependencyProperty.RegisterAttached
            (
                "Columns", typeof(ObservableCollection<DataGridColumn>), typeof(DataGridColumns),
                new UIPropertyMetadata(new ObservableCollection<DataGridColumn>(), OnDataGridColumnsPropertyChanged)
            );

        /// <summary>
        /// Gets the <see cref="ColumnsProperty"/> for the specified element.
        /// </summary>
        /// <param name="obj">The dependency object to get the property for.</param>
        /// <returns>The attached property, or null if none.</returns>
        public static ObservableCollection<DataGridColumn> GetColumns(DependencyObject obj)
        {
            return (ObservableCollection<DataGridColumn>)obj.GetValue(ColumnsProperty);
        }

        /// <summary>
        /// Sets the <see cref="ColumnsProperty"/> on the specified element.
        /// </summary>
        /// <param name="obj">The dependency object to set the property on.</param>
        /// <param name="value">The property value to set.</param>
        public static void SetColumns(DependencyObject obj, ObservableCollection<DataGridColumn> value)
        {
            obj.SetValue(ColumnsProperty, value);
        }

```
This works fine because I have the AttachedPropertyComments. If I remove AttachedPropertComments, the auto-generated props do inherit from this declaration as expected. It's when none of the other attached DP's in the project have AttachedPropertyComments that the inheritance functionality of SHFB fails to kick in.

So I'm not sure if that will help. There might be some special combination of factors in my particular case. I haven't found what that is. So far I've only discovered that: Remove all AttachedPropertyComments == inheritance doesn't happen. Have a single AttachedPropertyComments == inheritance does happen on the rest of the DP's.

**Comment by EWSoftware** [comment]
I figured it out.  The step used to generate inherited documentation is skipped if there are no `inheritdoc`, `AttachedPropertyComments` or `AttachedEventComments` elements in the XML comments files.  It would be wasted time if none of those were present.  That has the side-effect of not inheriting the backing field/event comments on dependency properties/events.  To determine whether there are any such properties/events would require looking in the reflection data.

Given that it's probably better to add `AttachedPropertyComments` and `AttachedEventComments` to describe them, I'm going to leave things as they are.

**Comment by victor-david** [comment]
Yes. It's an easy enough thing to do (add the AttachedPropertyComments) - and then everything works great. Thanks again.
