### ISSUE TITLE
Search of cyrillic symbols

### ISSUE THREAD

**Issue by Cyber-EX** [EWSoftware/SHFB#449]
Search did not work with cyrillic words, because regexp \W works with latin only.
File: \PresentationStyles\VS2013\Web\scripts\branding-Website.js
Line: 506
I created pull request #448 which fixes this issue.

Info: http://stackoverflow.com/questions/18471159/regular-expression-with-the-cyrillic-alphabet
> JavaScript (at least the versions most widely used) does not fully support Unicode. That is to say, \w matches only Latin letters, decimal digits, and underscores ([a-zA-Z0-9_])

**Comment by EWSoftware** [comment]
Closed by pull request #448
