### ISSUE TITLE
Visual Studio 2017 plugin not installed automatically

### ISSUE THREAD

**Issue by danners** [EWSoftware/SHFB#450]
Hi,

i tried to install the sandcastle plugin using the master installer on a win7 32bit with Visual Studio 2017 Enterprise installed. It did not detect the Visual studio from the Installer and did not attempt to install it. When i started the installation from the included vsix it worked correctly. 
I suspect this comes from the use of %ProgramFiles(x86)%\ in  Deployment/InstallerConfiguration.xml for Visual Studio 2017.

**Comment by EWSoftware** [comment]
Yes, I forgot to account for 32-bit vs 64-bit handling when I updated the configuration.  Prior versions were able to use the related VS###COMNTOOLS variable but VS2017 changed that with the ability to do side-by-side installation of the various editions.

The MAML IntelliSense schemas won't install either.  For the time being, they can be [installed manually](http://ewsoftware.github.io/MAMLGuide/html/746fc19e-2670-440b-8277-a1ef7dc074d5.htm) if you want them.
