### ISSUE TITLE
How Can I fuzzy search the api from the generated document?

### ISSUE THREAD

**Issue by superqbb** [EWSoftware/SHFB#455]
![image](https://cloud.githubusercontent.com/assets/3818131/25088993/38d9c41a-23ad-11e7-953f-f93da2134abf.png)
![image](https://cloud.githubusercontent.com/assets/3818131/25089005/536d920c-23ad-11e7-9aed-6430f87cb496.png)

**Comment by EWSoftware** [comment]
It's currently implemented as a keyword search only.  If the exact keyword is not found, it won't return any matches for it.  You'd have to change how the search page works and possibly how the index is generated to support fuzzy searches.
