### ISSUE TITLE
Version 10 confuses VersionBuilder plugin

### ISSUE THREAD

**Issue by dsgonline** [EWSoftware/SHFB#456]
My API documentation is based on 23 versions starting from 7.0 up to 9.0 SP3.
Now the new version is 10.0. Unfortunately the VersionBuilder plugin assigns most entries to version 10 even though some (very few) remain assigned to the original version.
Changing the current number to 9.9 fixes the problem.
I tried workarounds like "10", "10.0", '10 SP0' but nothing seems to help.

I updated from 2014.5.31 to current release 2017.1.28.

**Comment by EWSoftware** [comment]
Do you mean that you are seeing the version information out of order, something like "9.0 SP3, 10.0, ..." rather than the expected "10.0, 9.0 SP3, ..."?

**Comment by dsgonline** [comment]
We have it configured to display ony the first/primary version - when the entity was added (we never remove an API function, so displaying a very long history does not make sense for us). So if something was added in 7.0, only 7.0 is displayed. If I change the 'new version' to 10 almost all entities are displayed as added since version 10.

**Comment by EWSoftware** [comment]
Does that mean you've customized the presentation style?  The members aren't assigned to a version, the versions are just shown in reverse order with the latest appearance listed first.  If you're not showing all versions, it probably just looks like everything is assigned to the wrong version since they're out of order.  You can verify that by using the standard presentation style that shows all versions.

Somebody did apply a fix to sort versions more appropriately but it probably isn't handling all cases where there's additional text like "SP1" in the version value and that may be throwing them off.

**Comment by dsgonline** [comment]
You're right:
We customized the styling
	<item id="supportedIn_n">Supported in: {0}, {1}, {2}, {3}, ..</item>
to: 
	<item id="supportedIn_6">Supported in: {0}</item>
So the sorting guaranteed the desired output of the last item in the version list.
Sample output:
	Supported in: 9.9, 9.0 SP5, 9.0, 8.5 SP4, 8.5 SP1, 8.4, 8.2 SP3, 8.2, 8.1 SP2, 8.1, 8.0 SP3, 8.0, 7.6 SP4, 7.6, 7.5 SP2, 7.5

With the current version 10 this approach is not working anymore:
	Supported in: 9.0 SP5, 9.0, 8.5 SP4, 8.5 SP1, 8.4, 8.2 SP3, 8.2, 8.1 SP2, 8.1, 8.0 SP3, 8.0, 7.6 SP4, 7.6, 7.5 SP2, 10

The problem does not change, even if I only use major versions and set the current version to 10.

Currently my best workaround is declaring the current version "10.0" and removing the SPs: 
	Supported in: 10.0, 9.0, 8.5, 8.4, 8.2, 8.1, 8.0, 7.6, 7.5, 7.2, 7.1

To better support our use case, I modified the VersionSettingsCollection.Sort() routine to tolerantly handle trailing text.

Do you see a chance to have the functionality added to the project?

This is the code I modified in VersionSettingsCollection:

```
                if(result == 0)
                {
                    Version versionX, versionY;

                    if (Version.TryParse(x.Version, out versionX) && Version.TryParse(y.Version, out versionY))
                      result = versionY.CompareTo(versionX);
                    else
                    {
                      // try to convert to version as far as possible. Ignore trailing text.
                      _if (VersionExtension.VersionTryParseExtended(x.Version, out versionX) && VersionExtension.VersionTryParseExtended(y.Version, out versionY))
                        result = versionY.CompareTo(versionX);
                      if (result == 0)  // compare trailing text only if leading numbers match exactly_
                        result = String.Compare(x.Version, y.Version, false, CultureInfo.CurrentCulture) * -1;
                    }
                }

                return result;
            });
        }
  }
  _internal class VersionExtension
  {
    private static readonly char[] SeparatorsArray = new char[] { '.', ' ' };
    internal static bool VersionTryParseExtended(string input, out Version result)
    {
      bool foundANumber = false;
      List<int> versionComponents = new List<int>(4) { 0, 0, 0, 0 };
      String[] parsedComponents = input.Split(SeparatorsArray);
      for (int i = 0; i < parsedComponents.Length; i++)
      {
        int parsedComponent;
        if (Int32.TryParse(parsedComponents[i], NumberStyles.Integer, CultureInfo.InvariantCulture, out parsedComponent))
        {
          versionComponents[i] = parsedComponent;
          foundANumber = true;
        }
        if (i == 4)
          break;
      }

      result = new Version(versionComponents[0], versionComponents[1], versionComponents[2], versionComponents[3]);
      return foundANumber;
    }
  }_


```

**Comment by EWSoftware** [comment]
I'll get it fixed for the next release.  It'll probably be out in a week or two.

**Comment by dsgonline** [comment]
Thanks, that's great news!
