### ISSUE TITLE
Latest installer (2017.1.28) still shows old version (2016.9.17) in VS2013

### ISSUE THREAD

**Issue by netx123** [EWSoftware/SHFB#458]
I have installed the latest version 2017.1.28

However when checked in Visual Studio 2013 -> Extension and Update... it still shows the older version

2016.9.17.0 (Visual Studio 2013)
2017.1.28.0 (Visual Studio 2017)

I have tried uninstalling and reinstalling, but I get the same situation where the VS2013 install still shows the old SHFB version.

**Comment by EWSoftware** [comment]
There are two separate VSIX packages in that release, one for VS2013 and one for VS2015 and later.  If you used the guided installer, it should have ran both if found both versions of Visual Studio.  If you didn't use the guided installer or it didn't find VS2013 for some reason, uninstall the existing copy of the package and run the VSIX installer for VS2013 manually.

**Comment by netx123** [comment]
I always use the guided install, both VS2013 and VS2017 were detected and both VSIX installers were ran.

I have also extracted the SHFBVisualStudioPackage_VS2013.vsix installer and ran it manually, with the same result.

In the log file (attached) it seems to think that that vsix installer is the old version 2016.9.17:

[VSIXInstaller_e7c9826c-143f-417b-af03-343590cae995.txt](https://github.com/EWSoftware/SHFB/files/949920/VSIXInstaller_e7c9826c-143f-417b-af03-343590cae995.txt)

**Comment by EWSoftware** [comment]
Looking at the source for that release, it appears I didn't update the version in the 2013 version of the manifest.  It's current but the version number isn't correct.
