### ISSUE TITLE
Cannot reference project whose DLL appears in a framework folder

### ISSUE THREAD

**Issue by ekumlin** [EWSoftware/SHFB#459]
We have a Visual Studio 2017 project whose setup is like this:

    E:\path\to\project\Foo.sln
    E:\path\to\project\src\Foo\Foo.csproj
    E:\path\to\project\src\Foo\bin\Release\net452\Foo.dll
    E:\path\to\project\xmldocs\Foo\foo.shfbproj

*(The `csproj` and `shfbproj` are in the solution. The `shfbproj` has the `csproj` as a documentation source.)*

When I try to build the `shfbproj`, I get this error (notice how it's looking in `bin\Release\*` instead of `bin\Release\net452\*`):

> SHFB(0,0): error BE0040: Project assembly does not exist: E:\path\to\project\src\Foo\bin\Release\Foo.dll

How can I force the `shfbproj` to look in the correct directory?

**Comment by EWSoftware** [comment]
Is your project set to put the assembly there when built (i.e. the Output Path property is set to that folder) or are you using a build event to copy it there after it's built?  What kind of project is it (i.e. .NET Core, .NET Standard, or just a regular C# project)?

**Comment by ekumlin** [comment]
> Is your project set to put the assembly there when built (i.e. the Output Path property is set to that folder) or are you using a build event to copy it there after it's built?

We have not explicitly set the `OutputPath` property nor created a build event. This seems to be the default output directory for `xproj` and VS2017 `csproj` projects.

> What kind of project is it (i.e. .NET Core, .NET Standard, or just a regular C# project)?

The project is a migrated `xproj` built on `net452` and `netstandard1.6`. This is essentially the same as creating a .NET Core library project and setting `<TargetFrameworks>net452;netstandard1.6</TargetFrameworks>`.

Would a repro project help diagnose?

**Comment by EWSoftware** [comment]
Yes, please.  That would help me see what it's doing and handle the new case.

**Comment by ekumlin** [comment]
Aha! While creating the repro project, I figured out the cause.

If `<TargetFramework>` is specified, it correctly searches in the `bin\(configuration)\net452\*` folder. However, if we use `<TargetFrameworks>` (plural) instead, even for one framework, it will search in just `bin\(configuration)\*`.

The repro project is attached. Just rebuild and the error should occur.

[**ExternalLibraryShfbTargets.zip**](https://github.com/EWSoftware/SHFB/files/959638/ExternalLibraryShfbTargets.zip)

**Comment by EWSoftware** [comment]
Just so I know, is `TargetFrameworks` something that can be set in Visual Studio or is that something you do by editing the project in a text editor?

**Comment by ekumlin** [comment]
Actually, I'm not totally sure. I've always done it via a text editor, and I don't see any way to add multiple via the Properties interface. (It just greys out the "target framework" dropdown if you use `TargetFrameworks`.) I'm going to guess probably not.

I know there's easy ways to view your frameworks, like the dropdown at the top, but I can't seem to find any way to *edit* them.

![image](https://cloud.githubusercontent.com/assets/1350074/25463411/e37ad59a-2aaa-11e7-881d-548ab09a851d.png)

**Comment by ekumlin** [comment]
Was this resolved? Do you have a link to the PR containing the fix?


Thanks!

**Comment by EWSoftware** [comment]
The latest commit contains the necessary changes.
