### ISSUE TITLE
Namespace Summary: HTML Table assign="left" Help File CHM display error?

### ISSUE THREAD

**Issue by warrickprocter** [EWSoftware/SHFB#460]
I have included a table in a SHFB Namespace Summary. There seems to be a problem rendering the result of including an assign="left" attribute, e.g. <table assign="left">...</table>.

DOES WORK: (see image)
=========
TEXT1: TO SEE WHAT HAPPENS.
<table>
<tr><td><b>Title:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Version:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Description:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Company:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Product:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Copyright:</b></td><td>Blah, blah, blah.</td></tr>
</table>
TEXT2: TO SEE WHAT HAPPENS.

![shfb03](https://cloud.githubusercontent.com/assets/28168152/25550791/3978c80e-2cd0-11e7-9695-c0747077b090.jpg)

DOESN'T WORK:
-------------
TEXT1: TO SEE WHAT HAPPENS.
<table align="left">
<tr><td><b>Title:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Version:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Description:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Company:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Product:</b></td><td>Blah, blah, blah.</td></tr>
<tr><td><b>Copyright:</b></td><td>Blah, blah, blah.</td></tr>
</table>
TEXT2: TO SEE WHAT HAPPENS.

![shfb01](https://cloud.githubusercontent.com/assets/28168152/25550808/7c2ae5ce-2cd0-11e7-8a5c-b65307e508c0.jpg)
![shfb02](https://cloud.githubusercontent.com/assets/28168152/25550807/7c1cf5d6-2cd0-11e7-9cd8-b08d9f8071b3.jpg)

**Comment by warrickprocter** [comment]
This is not a show-stopper as the align="left" is not required, so no urgency on this, more of a heads-up...

**Comment by EWSoftware** [comment]
Wrap it in a `div` element with a style set to 100%.

``` XML
<div style="width: 100%;">
<table align="left">
   .
   .
   .
</table>
</div>
```

**Comment by warrickprocter** [comment]
Thanks Eric. I make extensive use of SHFB and I'm very pleased you made it.
