### ISSUE TITLE
Deploying Help Viewer content with a VSIX.

### ISSUE THREAD

**Issue by kfertitta** [EWSoftware/SHFB#462]
Hi Eric,

Not strictly a SHFB question, but since you've had to deal a LOT with Help Viewer stuff and VS integration stuff, I thought you might know.  With Dev15, MS wants you to deploy everything as a VSIX.  Do you know if it's possible to deploy Help Viewer content with a VSIX?  We have a big VS package (like SHFB) and this is the last bit that we need to deploy that doesn't seem to fit in the VSIX-only deploy world.

Thanks in advance.

**Comment by EWSoftware** [comment]
There are no configuration options in the VSIX manifest that allow specification of help content that I'm aware of.  I'm pretty sure that like other advanced scenarios such as installing assemblies in the GAC, you have to use an MSI installer to install the VSIX and handle the additional tasks.  I've never used that option so I don't know what's involved.

**Comment by kfertitta** [comment]
Thanks for taking the time to reply Eric.  Indeed, we've been shipping MSIs to do exactly as you suggest for many years (I actually co-founded a company whose entire business is around WiX --- [http://www.firegiant.com](url)

But, VS is really moving to a VSIX-only (or VSIX + NuGet-only) model, and the Help Viewer content is the only product bits we've really not been able to deploy without an MSI.  Probably time to abandon Help Viewer and ship a .chm and online help.  (Good thing we have SHFB... ;-)

Thanks again.
