### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by sephyk** [EWSoftware/SHFB#463]
I have recently downloaded the most updated guided installer, V2017.1.28.0, and I am running into issues all over.  I guess your installation is very particular because it's refusing to find any of the requirements.

First it tells me I don't have the Help Work Shop installed, I do, but I guess your installer is seeking the expected installation directory?  I've tried installing it in two spots, 1) D:\Help Workshop (not found no matter how many times I smacked your Search Again button); 2) C:\Help Workshop (again not found - smacking process repeated to no avail).  So this left me to say F*** it, and move on without it hoping I could fix a configuration or something to fix it later.  Then I ran into the step where it wanted to install the SFHB Visual Studio Package, where I received the beautiful message of:

Unable to locate the VSIX package installer.

I spent some time on your github page attempting to locate an installer, so far I can't find it myself, perhaps I've just missed it somewhere?  I would have assumed the guided installer would know either where to get it, or how to get it itself?  Either way, this resulted in yet another F*** it I'll try to fix the settings later for that one too if needed.

So I proceeded to the next step, MAML Schema IntelliSense.  Here again I am assuming your installer relies on default installation directories, and most likely is purely using this as a method to locate the installations because I again see a number of errors stating the same message for every supported Visual Studio version:

Unable to locate this version of Visual Studio.

(My installation is located again, off on my D:\ ... basically I have one drive running my OS, and another drive containing all the separated installations, applications, games, etc. and another drive holding data... separating each drive to a purpose)

So this is where I stopped entirely because it became very apparent to me that your guided installation only works with a standard setup, and I imagine I will go through the remainder of the process having clicked "Yes" to the "Are you sure you want to continue without it?" boxes on each step.

**Comment by EWSoftware** [comment]
The default paths are stored in the configuration file for the guided installer.  If you don't want to adjust them or use the guided installer at all, just run the MSI for SHFB and the VSIX package installer directly from the .\InstallResources folder which you'll find in the same location as the guided installer's executable.  Instructions for [installing the MAML IntelliSense schemas](http://ewsoftware.github.io/MAMLGuide/html/746fc19e-2670-440b-8277-a1ef7dc074d5.htm) can be found in the MAML guide.

Once you get the tools installed, if the help compiler can't be found to create Help 1 (CHM) files you can [set the path to it](http://ewsoftware.github.io/SHFB/html/e6fcfa33-e7ee-430a-abfe-6b7962e6d068.htm) in the SHFB project file properties.
