### ISSUE TITLE
Trying to fix "SHFB: Error BE0033: No APIs found to document."  

### ISSUE THREAD

**Issue by koljamaier** [EWSoftware/SHFB#464]
Hello,

I followed your advices on the BE0033 and checked for typical mistakes.
Indeed my project only uses the std namespace and doesn't define/use any other custom namespace.
So I tried to edit the API filter without success. I have public classes in my project and I added the .exe and .xml (generated by Visual Studio) to the build process for SHFB.

Sadly, I dont know what to do furthermore.

Cheers

**Comment by EWSoftware** [comment]
When you say the "std namespace", are you referring to C++?  If you're trying to document a native code assembly, it won't work as the tools only work with managed code assemblies.

**Comment by koljamaier** [comment]
Sorry, yes I am referring to C++.

**Comment by EWSoftware** [comment]
Managed code uses the .NET Framework.  Native code just produces regular assemblies that don't have any dependency on the .NET Framework.  If you're not using the .NET Framework at all, you're most likely producing native code assemblies.

One thought comes to mind if you are using .NET.  You said you only use the std namespace.  Assuming that's the same thing as the global namespace, that's probably why you aren't seeing anything as typically, code is placed into namespaces and stuff in the global namespace isn't wanted so it's excluded by default.

If that's the case, you can go to the SHFB project properties, select the Summaries catgory, click the Edit Namespace Summaries button, and in the dialog box that appears, click the checkbox next to the "(global)" namespace option.  That will include stuff in the global namespace as well.  You will most likely see stuff that you don't want documented such as some compiler generated classes.  You can use the API filter to remove those.  The other alternative is to place your code into namespaces.

**Comment by koljamaier** [comment]
Thank you very much for your responese.
Indeed I already read about the global-checkbox and evaluated it before.
Sadly without results - checked or unchecked, I still get BE0033.

Under documentation sources I tried to build the project with all possible combinations of .exe, .xml, and .vcxproj (VisualStudio). Also without success.

**Comment by koljamaier** [comment]
Also my API Filter looks rather strange. 
![image](https://cloud.githubusercontent.com/assets/20371969/26302018/2b8499a6-3ee3-11e7-876d-c6a55cc81691.png)

**Comment by EWSoftware** [comment]
As I mentioned, if your executable is not using .NET then it is probably a native code assembly and is not supported.  Based on what you are seeing, I think that is likely the case.
