### ISSUE TITLE
Hang during BuildAssemblerCore

### ISSUE THREAD

**Issue by esbenbach** [EWSoftware/SHFB#465]
We have a documentation project that for some reason has stopped building in the last few months (we don't build it that often).

What happens is that it will starting building and at some point during "BuildTopics" it justs stops progressing. The msbuild process seems to be going on forever, without doing anything.
BuildTopics:
  BuildAssembler (v2017.1.28.0)
<lots of stuff from the log>
  BuildAssemblerCore: Building topic T:Infosoft.Common.Contracts.DataContracts.Retail.DeliveryDay
  BuildAssemblerCore: Building topic Properties.T:Infosoft.Common.Contracts.DataContracts.Retail.DeliveryDay

And then nothing.
If i terminate the msbuild process SHFB continues (but obviously does not have all topics generated).

Any idea on how to figure out what is going on? 

I seem to recall I had something similar a few years ago, but back then i knew which files were changed and just went back and removed or edited them. This time around thats not really the case.

I can provide you with more details, logs etc, but I am unsure what sort of info to provide.

SHFB Version: 2017.1.28.0
VS2015
The solution is targeting .net 4.6.2
The issue happens both via Visual Studio, SHFB and from MSBuild on the command line.

**Comment by EWSoftware** [comment]
If you've got verbose logging turned on, the last "Building topic XXXX" message should be the one it's hanging up on.  If you've got a large project, with verbose logging enabled, it could be running low on memory.  You can turn off the verbose logging option and have it only log warnings and errors.   If that's the case, it should resolve it.

**Comment by esbenbach** [comment]
I tried filtering out the file it was hanging on, only to have it hang on the very next file.
Then i tried filtering the entire namespace, just happens on the first file in the next namespace.
Currently im trying (with the namespace filter) to build without the verbose logging on, and ill let it be for a few hours just to see what happens.

**Comment by esbenbach** [comment]
As expected it never completes (still running).
Any idea on how i can figure out what is going on?

**Comment by EWSoftware** [comment]
Can you filter it to just the class it was hanging on and duplicate the issue?  Can you reproduce the problem with a small example or send me the project so I can try to duplicate it?

**Comment by esbenbach** [comment]
I will give it a try during the week, it might be rather complicated to
reproduce though.

On 19 May 2017 11:06 pm, "Eric Woodruff" <notifications@github.com> wrote:

Can you filter it to just the class it was hanging on and duplicate the
issue? Can you reproduce the problem with a small example or send me the
project so I can try to duplicate it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EWSoftware/SHFB/issues/465#issuecomment-302811382>, or mute
the thread

**Comment by esbenbach** [comment]
I filtered away everything but the class it would hang on previously. Unfortunately the build then completed with no problems.

**Comment by esbenbach** [comment]
Restting the filter, the build process just stops a "few" topics earlier. Indicating to me that it might indeed be a memory issue, or at least related to the amount of data that I have in the project. It is a bit weird though because the project has not grown by any significant amount in the last year or so, and it is stopping quite fast.

Any other suggestions?

**Comment by EWSoftware** [comment]
Sorry, I don't know what else to suggest.  If you can send me the project, I can take a look at it and see if I can duplicate it.

**Comment by esbenbach** [comment]
I sent you the project in an email.

I downloaded the SHFB source and attempt to build the documentation with the debugger attached.
It seems to always run two processes, probably one as a coordinator and another that does the individual tasks, anyway, the "main" process stops at Microsoft.Ddue.Tools.BuildComponent.Apply, while trying to add the document to the documentlist (I assume that is the main thread i can see more but that is where it breaks when i ask the debugger to pause execution).

The tasks view of VS is showing the tasks as blocked:
![image](https://cloud.githubusercontent.com/assets/1378302/26339433/218568ae-3f88-11e7-9a8e-9cc172843508.png)

A similar thing is happening in the "worker" process. Here it stops in SandcastleBuilder.Utils.BuildEngine.ReadOutputStream - more specifically while doing stream.ReadLine();
As with the main process VS shows a list of blocking tasks.

I haven't had time to actually dig into it and determine if it is a threading issue, but my uneducated guess would be some sort of deadlock/race condition is happening.

**Comment by EWSoftware** [comment]
It was caused by using the Member Name naming method.  Some of the member names are very long and exceed the maximum path length.  This caused the writer task in the Save Component to stop but the error wasn’t making it up to the main thread.  Switch to the GUID or Hashed Member Names naming method so that it generates shorter names that won't exceed the path length.  The next release will report the error.
