### ISSUE TITLE
Any plans for the new DOCS format tools?

### ISSUE THREAD

**Issue by AcousticGuitar** [EWSoftware/SHFB#466]
Eric;
Thanks for all your excellent work on SHFB.  It's just the best and has allowed me to expose APIs to many teams that knew little about the tool and were highly impressed!  A real Career Booster for sure!

Do you have any plans to create a tool for the new DOCS format?  Microsoft apparently still uses the code comments but runs the content through a different process now creating the types we see on their new docs website.  

I recall a while back finding that tool that does the work, but can't recall it's name.  I tried it against C# code commenting and found it worked.  It was designed also to allow of Javascript documentation too.

**Comment by EWSoftware** [comment]
Matching the latest style of MSDN or the Docs site is a matter of implementing a presentation style.  It can be a fair amount of work and if I get time I might but no guarantee on when that might be.

**Comment by AcousticGuitar** [comment]
Hi Eric, 
I finally found the tool I was [referring to above](https://github.com/dotnet/docfx).  
I tried it in the early days and it didn't work too well, but I could see it was heading for success due to it's simplicity.  Just thought I'd give you a heads-up..

**Comment by AcousticGuitar** [comment]
Check this out Eric...
Maybe it was  DOTFX?   Try it out...
First, install the tool, using chocolately => cinst docfx -y
Then get seed project from github => git clone https://github.com/docascode/docfx-seed
Compile it.  => docfx clonedlocation\docfx.json --serve.  
Goto port http://localhost:8080 and the new formats show up!  Nice...

**Comment by EWSoftware** [comment]
I've seen it.  I prefer SHFB for obvious reasons :smile:.
