### ISSUE TITLE
Unhandled Exception starting the GUI

### ISSUE THREAD

**Issue by AntonWedemeier** [EWSoftware/SHFB#467]
Dear reader, 

I have installed SHFB with the installer and the process worked fine.
I use VS 2017 Community. (It is not located on the c-drive but I changed the path in the InstallerConfiguration.xml file.)

But when I start the GUI I get an unhandled exception. I downloaded the source and build the gui myself. The build process went well. But starting the new build I got the same exception. In Debug mode the exception is given just after the MainForm is created and the Application.Run statement is executed (file SandcastleBuilderGui line 55). 

The exception gives the information:
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Kan bestand of assembly Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
  Source=SandcastleBuilderGUI
  StackTrace:
   at SandcastleBuilder.Gui.MainForm.MainForm_Load(Object sender, EventArgs e) in X:\Projecten\Projects 2017\SHFB-master\SHFB\Source\SandcastleBuilderGui\MainForm.cs:line 758
   at System.Windows.Forms.Form.OnLoad(EventArgs e)

(Translated to English: Can not find file or assembly Microsoft.Build ... or one of its dependencies.)

The file Microsoft.Build.dll itself is there (in the Reference Assemblies).
I have not found this issue in the issue list.
I am not a very experienced developer. 

Do you know what can be the cause and what may be the solution ?

Thank you.

**Comment by EWSoftware** [comment]
See the release notes for the latest version.  You probably need to install the [MSBuild Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159).

**Comment by AntonWedemeier** [comment]
That did the trick. Thank you for the quick answer.
