### ISSUE TITLE
Installer does not detect VS2017 (possibly because of non-standard install location)

### ISSUE THREAD

**Issue by detuur** [EWSoftware/SHFB#469]
The most current installer fails to locate VS2017 Professional. I have installed it to a non-standard path (D:\Program Files (x86)\Microsoft Visual Studio). This detection only fails during the installation of the schemas. The snippets install fine.

**Comment by EWSoftware** [comment]
The install locations can be edited in the guide installer configuration file.  If you don't want to do that, you can run the package manually be running the VSIX file from the .\InstallResources folder.

**Comment by mikasoukhov** [comment]
VS 2017 uses MSBuild 15.0. Latest release is incompatible with latest VS

**Comment by EWSoftware** [comment]
The package or the standalone GUI?  Either way, you can install the Microsoft Build Tools 2015 and it should work.  See the release notes for the link.

**Comment by mikasoukhov** [comment]
GUI.

I've seen the notes. Just to inform that the release is incompatible with a fresh VS 2017 installation.
