### ISSUE TITLE
Excluded warning

### ISSUE THREAD

**Issue by mikasoukhov** [EWSoftware/SHFB#470]
While compiling I've got tons of messages like

Unknown reference link target 'T:DevExpress.Xpf.Core.DXWindow' (we uses DevExp for development).

Is it possible to manually exclude dependencies? Warning too much (dont know exact value but it contains around 10k lines). No possible to find really important doc issues in aml topics.

**Comment by EWSoftware** [comment]
You can use the [Additional Reference Links Plug-In](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.) to create the information it needs to suppress those warnings.

**Comment by mikasoukhov** [comment]
SHFB: Error BE0029: Unexpected error while executing plug-in 'Additional Reference Links': Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.  C:\References\DevExpress.Data.v15.2.dll ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath)

**Comment by EWSoftware** [comment]
Create a SHFB project that contains the assemblies and add that to the plug-in configuration.  Don't add the assemblies directly to the plug-in configuration.

**Comment by mikasoukhov** [comment]
SHFB: Error BE0029: Unexpected error while executing plug-in 'Additional Reference Links': SandcastleBuilder.Utils.BuilderException: Fatal error, unable to compile project 'C:\Documentation\ExcludedRefs.shfbproj': System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by EWSoftware** [comment]
There's not enough information to know what's causing that one.  Can you e-mail me the projects in question so that I can try to duplicate it?

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/tree/master/Documentation/en

**Comment by EWSoftware** [comment]
That version doesn't appear to contain the additional reference links plug-in.  It's also missing the import for the SHFB targets file so it won't build anyway.  Is it current?

**Comment by EWSoftware** [comment]
Closing due to lack of response.  If you can supply an example, feel free to reopen it.
