### ISSUE TITLE
MSDN URL not found - for multiple types

### ISSUE THREAD

**Issue by dhallmark** [EWSoftware/SHFB#471]
I know that it is possible to suppress the ResolveReferenceLinksComponent warnings by creating a separate project for a set of resources and including that project via the Additional Reference Links module with the LinkTypes set to none.

What I would like to know is how to troubleshoot the issues so that my helpfile documentation includes accurate links to the MSDN documents for those types if this is possible.  For example, I am including Microsoft.IdentityModel.Tokens in my project and I have arguments that are of type TokenValidationParameters.  Nuget installs the MS-supplied xml file for their library along with the dll.

Is it possible to have those types resolve to valid external links out to MSDN or am I stuck with just disabling the warnings?

Thanks,
Daniel

**Comment by EWSoftware** [comment]
If they're on MSDN, you should be able to use the Additional Reference Links plug-in to resolve them.  Set the link type to MSDN in the plug-in configuration for the project containing those assemblies.

**Comment by dhallmark** [comment]
Please forgive me if I'm being dense.

- My API code has class that inherits from Microsoft.IdentityModel.Tokens.TokenValidationParameters.
- My "API" SHFB project has Visibility set to include inherited .NET framework members.
- When I build the API SHFB project I receive multiple "MSDN URL not found for target" warnings from the ResolveReferenceLinksComponent for the above class and its members.
- I created a second "Framework" SHFB project and included the Microsoft.IdentityModel.Tokens.dll and .xml files as a document source in that project.
- I included the Framework SHFB as an Additional Reference Link in the API SHFB project.

If I set the WebSiteSDKLinkType to None for the included project, then the warnings are suppressed.

If I set the WebSiteSDKLinkType to msdn then I again receive the MSDN URL not found warning.

I have performed the step of clearing out the MSDN cache from AppData/Local/...   and I also have downloaded and installed the 2017-05-15 version of SHFB to make sure I was running the current code.

Note: I also experimented with adding the Microsoft DLL and XML file as a Documentation Source in my project and SHFB did generate HTML output for the Microsoft classes within my Help site, but they did not reference any external MSDN documents (this I expected).

Thanks,
Daniel

**Comment by EWSoftware** [comment]
If they're still not resolving after setting the type to MSDN, then the MSDN web service used to generate the link IDs probably doesn't know about them.  In that case, there isn't anything you can do except set them to None to suppress the warnings.
