### ISSUE TITLE
When only public members are selected for documentation, public methods in private classes are included in the docs

### ISSUE THREAD

**Issue by mdkf** [EWSoftware/SHFB#479]
I would like SHFB to consider scoped visibility to be considered. Public methods in a private class should not be included when the private members flag is not selected.

**Comment by EWSoftware** [comment]
It does this already.  Public members of private classes will not be included unless you enable the option to include private members.

Note that a class declared directly within a namespace without an explicit visibility is considered internal.  You can verify this by looking at the syntax section in the class topic.  In fact, you can't declare such classes private.  Only nested classes can be declared private.

If you've got the Internal Members option enabled, it will include the class and its public/internal members.  If you don't want those to show up, you can use the API filter to exclude them.

**Comment by mdkf** [comment]
@EWSoftware Hi Eric. I don't have internal members enabled however public methods inside an internal class are being included in the documentation.

**Comment by EWSoftware** [comment]
I'm not able to duplicate this.  Can you provide a small example along with the associated SHFB project so I can see what settings are in effect?

**Comment by EWSoftware** [comment]
Closing due to lack of response.  If you can supply an example, feel free to reopen it.
