### ISSUE TITLE
Unable to generate Markdown content

### ISSUE THREAD

**Issue by mhoagland** [EWSoftware/SHFB#480]
> BuildAssembler : error : TransformComponent: [T:DataProvider.DataReaders.QueryableDataReader1] An error occurred while executing the transform '', on line 0, at position 0. The error message was: The variable or parameter 'v_keyword' is either not defined or it is out of scope. [C:\Users\user\Desktop\Help\Working\BuildTopics.proj]
  CopyFromIndexComponent: "reflection" in-memory cache entries used: 1 of 15.
  CopyFromIndexComponent: "comments" in-memory cache entries used: 3 of 30.

`v_keyword` isn't something in my code.

**Comment by EWSoftware** [comment]
There's a bug in the *C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\Markdown\Transforms\MainSandcastle.xsl* transformation.  If you have admin rights, you can edit that file, search for `$v_keyword`, and change it to `@langword`.

**Comment by mhoagland** [comment]
Worked like a charm. Thanks!
