### ISSUE TITLE
Static constructor not extracted and rendered

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#481]
I'm missing the extraction of static constructors (``#cctor``) like for other static elements (properties, methods, ...).

**Comment by EWSoftware** [comment]
They're private so only appear if private members are included.

**Comment by VBWebprofi** [comment]
Thanks, to clearify. Haven't really thought and looked. But it's important to document it. So I will use the qualified setting and filter plug in.
