### ISSUE TITLE
Question - is it possible to link an interface page to its implementors and vice versa

### ISSUE THREAD

**Issue by yowl** [EWSoftware/SHFB#482]
Using the website output, on a class page it shows in the Syntax section the class name and the interface it implements.  Is it possible to make the interface clickable so it goes to the corresponding page in the help.  And conversely, is it possible from the interface page to have the build list the implementors?

**Comment by EWSoftware** [comment]
Add the Syntax Component to the SHFB project.  In it's configuration, enable the "Render reference links" option and the types in the syntax section will be clickable.

Regarding implementers info, it is available in the reflection information but it's never been used in the presentation styles so you'd need to update the XSL transformations to include and render it similar to how the inheritance hierarchy is done.

**Comment by yowl** [comment]
Thanks.  That's great, I'll have a dig around the XSL
