### ISSUE TITLE
Understanding 'Additional Reference Links' Plugin

### ISSUE THREAD

**Issue by green4don** [EWSoftware/SHFB#486]
I have a number of documentation projects that reference component and common libraries.

GameView
 -> AcblMate
      -> TeamLibrary
-> BridgeMate
      -> TeamLibrary
 -> TeamLibrary

There are, then, references in GameView to AcblMate, BridgeMate and TeamLibrary components and references in AcblMate to TeamLibrary and BridgeMate to TeamLibrary .

This seems to be the purpose of this plugin. I would even be happy if the link was not available as I'm not sure how jumping between the four chm help files (HTML Help 1) would work. I'm mainly trying to suppress  the build errors, though I could just ignore them.

When I build my AcblMateAPI project I get the following error:

"Unexpected error while executing plug-in 'Additional Reference Links': SandcastleBuilder.Utils.BuilderException: Unable to build additional target project: C:\Users\Don\Visual Studio 2017\Projects\TeamMate\TeamMateAPI\TeamLibraryAPI.shfbproj"

The configuration of this plugin references the Help File Builder for the TeamLibrary common library and the path shown seems correct. If I go to that project (TeamLibraryAPI) and build it, it builds but when referenced there's a problem.

My documentation is a work in progress and I could be missing something here, or it's possible I simply don't understand what I'm doing.

Help please.

Thanks.

**Comment by EWSoftware** [comment]
The invalid reference link warnings can be safely ignored.  If not found, they render as non-clickable links.  The Additional Reference Links plug-in can be use to suppress them.  Why it's failing, I can't say without more information.  If you look in the main project's working folder after the failed build, you should find a folder with a random name.  It should contain the build output of the failing subproject.  The log file in there should give more information about why it failed to build.

**Comment by green4don** [comment]
One possibility is that the target help file is incomplete at this point. You've given me some things to look at when I get time to work on this some more. Thanks.
