### ISSUE TITLE
SHFB .Net Framework Version

### ISSUE THREAD

**Issue by green4don** [EWSoftware/SHFB#487]
I have some SHFB projects originally build in VS2013 and now managed in VS2017 Community.

When I load the solution containing these projects each SHFB project throws a warning/error as follows:

"The SHFBProject 'XX.shfbproj' is targeting ".NETFramework, Version=V4.0", which is not installed on this machine."

I select the option to change the target to .NET Framework 4.6.1 and continue.

My applications actually target V3.5 as they need to run on Windows XP for a few users and all compiles are done on x86 solution platforms as I need to interface with the Microsoft Jet 4.0 Database Engine  available only in a 32 bit version. This information is likely immaterial to the error.

The SHFB project properties Build configuration is targeting .NET Framework 3.5 as well.

Somewhere there's a component that requires 4.0 but I can't find it or upgrade it or change it or whatever it is I need to do. I've reinstalled Sandcastle a couple of times and all components seem correct. The build works, the CHM file is built and runs but something is amiss.

Thanks.

**Comment by EWSoftware** [comment]
I haven't seen that warning before.  SHFB projects don't contain the `TargetFrameworkVersion` property normally used to identify the framework version since they don't need it.  I suppose it could be a side-effect of the `ToolsVersion` attribute on the main project element.  If you open it in a text editor and change the value to "12.0" or "14.0", perhaps it will suppress the error.  If that doesn't work, you can try adding the `TargetFrameworkVersion` property with a value of "v4.6.1" to see if that gets rid of it.

If you create a brand new SHFB project, does it do it there too?  If not, you may be able to compare the two to see what's different and add stuff in until it gives the warning.

**Comment by green4don** [comment]
The old SHFB projects had "ToolsVersion=12.0" and the new SHFB project have "ToolsVersion=14.0" and both generate the target framework warning. 

Starting a brand new SHFB simple project with nothing in it still generates the error.

Adding a "TargetFrameworkVersion=""v4.6.1" makes no difference, the error is still generated when loading the project.

I've no idea, so will just give up.

[TestAPI.zip](https://github.com/EWSoftware/SHFB/files/1130017/TestAPI.zip)

Thanks.

**Comment by EWSoftware** [comment]
I took a look at your example.  `TargetFrameworkVersion` is a property, not an attribute.  Add it as an XML element in the same section as the `AssemblyName` and `RootNamespace` properties and see if that changes anything:

```XML
<AssemblyName>TestAPI</AssemblyName>
<RootNamespace>TestAPI</RootNamespace>
<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
```

**Comment by green4don** [comment]
I wondered, thanks.
This resolves the load error.
Why the default is v4.0 I've no idea, must be a setting somewhere.

**Comment by EWSoftware** [comment]
It's probably the default in the common targets file which is imported by the SHFB targets file.

**Comment by alekdavisintel** [comment]
Bummer, but this did not work. I reopened the project today and got this warning again:

![image](https://user-images.githubusercontent.com/98194335/175575852-6a20f112-38c6-4261-a4fa-00442c5f9e6d.png)

How do I fix it?

**Comment by alekdavisintel** [comment]
Never mind. Somehow the line `<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>` got lost so it looks like it's okay after I put it back.
