### ISSUE TITLE
Error while installing HelpFile builder v2015.10.10.0

### ISSUE THREAD

**Issue by bob-brezniak** [EWSoftware/SHFB#488]
Trying to run the Sandbox installer, and I get the following error when i reach the 
SHFB Visual Studio Package step.  

![image](https://user-images.githubusercontent.com/30264576/28325929-dc5b4160-6ba4-11e7-81c2-612d36b4f893.png)

**Comment by EWSoftware** [comment]
That issues was fixed in an update to that version's guided installer and subsequent releases (#309).  You can also work around it by running the VSIX installer manually from the .\InstallResources folder.

**Comment by bob-brezniak** [comment]
The download site that I pulled it from is this one:
https://github.com/EWSoftware/SHFB/releases/tag/v2015.10.10.0

According to this site:  https://github.com/EWSoftware/SHFB/tags
It looks like the next version is v2016.4.9.0
Is this the one that you recommend downloading?




Bob Brezniak - Client Infrastructure & HelpDesk
8500 Freeport Parkway | Suite 100 | Irving, TX 75063
Office: 214.441.8887 |  fhlb.com<http://www.fhlb.com/>

[cid:image009.png@01D02F47.707BCF10]

[cid:image002.png@01D29CD1.228EAF80][cid:image003.png@01D29CD1.228EAF80]<https://twitter.com/FHLBDallas>[cid:image004.png@01D29CD1.228EAF80]<https://www.facebook.com/fhlbdallas>[cid:image005.png@01D29CD1.228EAF80]<https://www.linkedin.com/company/federal-home-loan-bank-of-dallas>[cid:image006.png@01D29CD1.228EAF80]<https://www.youtube.com/user/FHLBDallas>

**Comment by EWSoftware** [comment]
If you want to use a later release, I'd suggest updating to the latest but the next one up from the one you are using should also work.  If you want to stay with 2015.10.10.0, just run the VSIX installer manually.

**Comment by bob-brezniak** [comment]
Ok.   Thanks.




Bob Brezniak - Client Infrastructure & HelpDesk
8500 Freeport Parkway | Suite 100 | Irving, TX 75063
Office: 214.441.8887 |  fhlb.com<http://www.fhlb.com/>

[cid:image009.png@01D02F47.707BCF10]

[cid:image002.png@01D29CD1.228EAF80][cid:image003.png@01D29CD1.228EAF80]<https://twitter.com/FHLBDallas>[cid:image004.png@01D29CD1.228EAF80]<https://www.facebook.com/fhlbdallas>[cid:image005.png@01D29CD1.228EAF80]<https://www.linkedin.com/company/federal-home-loan-bank-of-dallas>[cid:image006.png@01D29CD1.228EAF80]<https://www.youtube.com/user/FHLBDallas>
