### ISSUE TITLE
Possible to use without a documentation source?

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#490]
Is it possible to create a completely conceptual help file - no document sources?  I'd like to take advantage of the tools for building HTML Help 1 and website help, but don't have assemblies that I need to document.  If so, how?

Thanks,
Glenn

**Comment by netx123** [comment]
Hi Glenn,
Yes this can be done very easily, just create a new documentation project: File->New->Templates->Documentation
Then right click your project and select "Properties"
In the Plug-Ins tab section, in "Available Plug-Ins" you should see "Additional Content Only", add this to the right hand pane "Plug-Ins in This Project"
You can now Compile your Documentation Project with only conceptual content.

**Comment by glenncarr** [comment]
Fantastic, thank you!
