### ISSUE TITLE
suggestions for displaying large single image

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#491]
I'd like to have a small thumbnail image displayed, and then have the thumbnail a link to a larger image with more detail.  What are some ways and suggestions display just a larger image without creating a new topic page - is that possible?

Thanks,
Glenn

**Comment by glenncarr** [comment]
So, I ended up creating topic with nothing in except an <introduction> containing a <mediaLink>.  Works fine.  For example:

`<topic id="ec9d46c7-794e-4652-972f-b29ae12be259" revisionNumber="1">
  <developerConceptualDocument xmlns="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink">
    <introduction>
       	<mediaLink>
		<caption>Detailed Screenshot</caption>
		<image placement="center" xlink:href="detailed_screenshot"/>
	</mediaLink>
     </introduction>
  </developerConceptualDocument>
</topic>`

**Comment by EWSoftware** [comment]
Another option that may work for you if you don't want a completely separate topic is to use the `markup` element to embed literal HTML in the topic.  That'll work as long as you aren't generating Open XML or MS Help Viewer files.

**Comment by glenncarr** [comment]
Ah, thanks!
