### ISSUE TITLE
[Help] Can't Open the Text Editor inside the GUI

### ISSUE THREAD

**Issue by Artanisx** [EWSoftware/SHFB#494]
Hello,
first of all thank you for the great tool! I'm learning how to use it, and it seems I can't find any way to edit a generated Help file.

I could generate one Help file easily for my project (and it's great), but I would need to manually edit the output to change something, add some more text etc.

Checking the guide, I see there supposedly is a [text editor ](https://ewsoftware.github.io/SHFB/html/a76a88ff-d67f-4eb5-9622-90287c786c1b.htm), but I can't find a way to show it inside Sandcastle Help File Builder. It doesn't appear anywhere, not even in the Window menu.

Sorry for the probably stupid question, but could you help me out?

Thanks!

**Comment by EWSoftware** [comment]
Perhaps I'm misunderstanding what you want but it sounds like you want to compile a help file like a Help 1 (CHM) file and then edit the CHM file.  That's just not possible.  The text editor in the GUI is for editing project files, those within the SHFB project that you can see in the Project Explorer window.

You can add files to the project and edit those.  When you build the help file, that content gets compiled into the resulting help file.  See the [Folder and File Items](https://ewsoftware.github.io/SHFB/html/0a9d6da4-cff6-4664-8b64-b7df04c8a37d.htm) topic for information on adding files.  See the section on [Conceptual Content](https://ewsoftware.github.io/SHFB/html/3d4edd2d-7883-4508-b9d2-bd7b4d848b0d.htm) and its subtopics for more information on adding and managing additional content.

**Comment by Artanisx** [comment]
Oh I see! So while I can't manually edit the help file generated automatically from my project/assembly, I can add additional files that gets compiled in the help file. 

I'll study the links you provided, thank you very much :)
