### ISSUE TITLE
Rendering as chm help: missing space after any <see langword="someword"/>

### ISSUE THREAD

**Issue by NW7US** [EWSoftware/SHFB#495]
![chm-missing-space-example](https://user-images.githubusercontent.com/5557774/28646113-b00803a0-7225-11e7-8dd7-42aed0bb5120.jpg)

As you may see in the screen capture image, after the bold **true** and **false** text, which in the XML comments are defined as `<see langword="true"/>` and `<see langword="false">`, a space is stripped from the rendered XML output into the chm help file.  I cannot find any way to defeat this issue.  Why are there no spaces after any of these XML elements?

**Comment by EWSoftware** [comment]
Are you using the latest release?  There used to be script that inserted an extra space due to this issue but it was modified in issues #451 as it was inserting extra spaces in most cases and no longer appeared to be an issue except in the noted case.

**Comment by RalfKoban** [comment]
I have the same issue and use the latest released version "https://github.com/EWSoftware/SHFB/releases/tag/v2017.5.15.0"

The snippet that produces the issue on my side is:
/// to either <see langword="true"/> or <see langword="false"/>, depending on whatever.
