### ISSUE TITLE
一个问题SHFB: Error BE0043  An unexpected error occurred trying to execute the XslTransform MSBuild task: System.TypeInitializationException

### ISSUE THREAD

**Issue by KingWangYang** [EWSoftware/SHFB#498]
生成启动时间为 2017/8/8 13:56:25。
节点 1 上的项目“E:\Test\Help\Working\TransformManifest.proj”(默认目标)。
TransformManifest:
  XslTransform (v2015.1.12.0)
  Copyright ? 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright ? 2006-2014, Eric Woodruff, All Rights Reserved.
  Applying XSL transformation 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\ProductionTransforms\ApplyVSDocModel.xsl'.
  正在将文件从“reflection.xml”复制到“reflection.nofilenames”。
  XslTransform (v2015.1.12.0)
  Copyright ? 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright ? 2006-2014, Eric Woodruff, All Rights Reserved.
  Applying XSL transformation 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\ProductionTransforms\AddFilenames.xsl'.
XslTransform : error : An unexpected error occurred trying to execute the XslTransform MSBuild task: System.TypeInitializationException: “System.Xml.Xsl.CompiledQuery.Script1”的类型初始值设定项引发异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。 [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor() [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    --- 内部异常堆栈跟踪的结尾 --- [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.Security.Cryptography.HashAlgorithm.Create(String hashName) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.Xml.Xsl.CompiledQuery.Script1..cctor() [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    --- 内部异常堆栈跟踪的结尾 --- [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.Xml.Xsl.CompiledQuery.Script1.GetFileName(String id, String namingMethod) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 <xsl:template match="api">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:xslt-debug}current) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 <xsl:template match="apis">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:xslt-debug}current) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 <xsl:template match="/">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:xslt-debug}current) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 Root(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlWriter writer) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 Microsoft.Ddue.Tools.XslTransformCore.Main(String[] args) [E:\Test\Help\Working\TransformManifest.proj]
XslTransform : error :    在 Microsoft.Ddue.Tools.MSBuild.XslTransform.Execute() [E:\Test\Help\Working\TransformManifest.proj]
已完成生成项目“E:\Test\Help\Working\TransformManifest.proj”(默认目标)的操作 - 失败。

生成失败。

**Comment by EWSoftware** [comment]
By translating the error message, it appears you have the FIPS algorithm policy enabled.  Disabling it should resolve the issue: https://stackoverflow.com/questions/14509354/this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptogra

**Comment by EWSoftware** [comment]
To follow up on this one, a better solution is to change the Naming Method project property from GUID to either Member Names or Hashed Member Names.  Neither uses the MD5 hashing that is causing the FIPS issue.  I'll see about adding code to catch this specific exception and use the recommendation to change the naming method as the exception message.

Changing the GUID naming option to use a different hashing method is a possibility but is a significant breaking change since all previously generated GUID IDs would no longer match on subsequent builds of the same help file which could prove problematic if your using them somewhere else to link to website help topics.  Since this issue doesn't appear to happen all that often, changing the naming method is the better approach.
