### ISSUE TITLE
Excluded overridden method introduces the base one

### ISSUE THREAD

**Issue by prochan2** [EWSoftware/SHFB#500]
For the example bellow,

the expected behavior is to hide the method from the ChildClass documentation completely,

whereas the actual behavior is:

![image](https://user-images.githubusercontent.com/5324719/29158388-194e2ab6-7dab-11e7-965b-8696781da0d7.png)

```
public class BaseClass
{
    // In the base class, I do want the method to be documented.

    /// <summary>
    /// This is my method.
    /// </summary>
    public virtual void MethodWithExcludedDocInChild()
    {
    }
}

public class ChildClass : BaseClass
{
    // In the child class, I do not want the method to be documented.

    /// <exclude/>
    public override void MethodWithExcludedDocInChild()
    {
    }
}

```

**Comment by EWSoftware** [comment]
I've fixed the API filter so that if an overridden member is removed, the matching overridden/virtual members in the base types are also removed.  It'll be in the next release.
