### ISSUE TITLE
The Help Library Manager executable could not be found.

### ISSUE THREAD

**Issue by BernhardJ** [EWSoftware/SHFB#501]
I have following issue:
I start the HelpLibraryManagerLauncher.exe with the generated command line options.
The error is shown:
Sandcastle Help File Builder and Tools, version 2017.5.15.0
Copyright © 2006-2017, Eric Woodruff, All Rights Reserved
E-Mail: Eric@EWoodruff.us

Catalog name not specified, the default catalog name 'VisualStudio14' will be used.

ERROR: The requested operation could not be performed.
Details: The Help Library Manager executable could not be found.  Is it installed?

I have installed:
- Visual Studio 2015 (uses Helpviewer 2.2)
- SQL Server 2016 Management Studio (uses Helpviewer 2.2)
- Visual Studio 2017 (uses Helpviewer 2.3)
- Microsoft Help Viewer 2.2 (C:\Program Files (x86)\Microsoft Help Viewer\v2.2)
- Microsoft Help Viewer 2.3 (C:\Program Files (x86)\Microsoft Help Viewer\v2.3)

Another Computer without SQL Server 2016 Management Studio works fine.

How can I solve this issue?
Thanks

**Comment by EWSoftware** [comment]
Look in *%ProgramFiles(x86)%\Microsoft Help Viewer* and see which versions are installed on that PC.  Specify the appropriate version parameter based on what's installed and what version of Visual Studio you are targeting (`/viewerVersion 2.2` or `/viewerVersion 2.3`).

Since it can't find the executable for the default VisualStudio14 catalog, you probably haven't installed the help viewer for VS 2015 (version 2.2)

**Comment by BernhardJ** [comment]
Hi

Thanks for your reply. Like I wrote in my initial post, I have installed both Help Viewer, because we use VS 2015 an 2017. The installation for the Help Viewer 2.3 works fine.
Dir cmd:
```
C:\Program Files (x86)\Microsoft Help Viewer>dir *.exe /s /b
C:\Program Files (x86)\Microsoft Help Viewer\v2.2\HlpCtntMgr.exe
C:\Program Files (x86)\Microsoft Help Viewer\v2.2\HlpViewer.exe
C:\Program Files (x86)\Microsoft Help Viewer\v2.3\HlpCtntMgr.exe
C:\Program Files (x86)\Microsoft Help Viewer\v2.3\HlpViewer.exe
```

F1 in VS 2015 starts Help Viewer 2.2
F1 in SQL Server 2016 Management Studio starts Help Viewer 2.2 with another catalog
F1 in VS 2017 starts Help Viewer 2.3

Thanks

**Comment by EWSoftware** [comment]
I don't know what else to tell you.  It looks in the registry for the necessary keys to locate the tools.  The error message indicates that it isn't finding the necessary registry keys.

**Comment by BernhardJ** [comment]
Hi

I found the problem in the combination of the source code and the registry.

My registry looks like:
64-Bit Node
![capture20170821072445717](https://user-images.githubusercontent.com/3414941/29505288-b204c844-8645-11e7-9848-315c1ac4956b.png)

WOW6432Node Node
![capture20170821072612096](https://user-images.githubusercontent.com/3414941/29505313-d83f8800-8645-11e7-9341-18506047ebb2.png)

The AppRoot:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Help\v2.2]
"AppRoot"="C:\\Program Files (x86)\\Microsoft Help Viewer\\v2.2\\"
```
is only in the WOW6432Node.

The Programmcode:
![capture20170821073413877](https://user-images.githubusercontent.com/3414941/29505420-7c51a2c0-8646-11e7-8de8-0ce2938c0402.png)

could be changed to
![capture20170821073803917_001](https://user-images.githubusercontent.com/3414941/29505430-89960d18-8646-11e7-99da-22157232a48f.png)

I know, with my code more than one regKeyHandle should be closed.

Could you change the code?

Thanks

**Comment by BernhardJ** [comment]
The cs file with the changes:

[HelpLibraryManagerUnsafeNativeMethods.cs.txt](https://github.com/EWSoftware/SHFB/files/1237922/HelpLibraryManagerUnsafeNativeMethods.cs.txt)
