### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by PCC-UK** [EWSoftware/SHFB#504]
Trying to install on a fresh install of Visual Studio 2017 (15.0) (Enterprise Edition) x64 Windows 10 Version 1703 (OS Build 15063.540)

Microsoft VSIX Installer
-------------------------------------------
Initializing Install...
Extension Details...
	Identifier         : c997d569-ee8e-4947-a46f-9a0717ce39a0
	Name               : SHFB
	Author             : EWSoftware
	Version            : 2017.5.15.0
	Description        : Visual Studio integration for the Sandcastle Help File Builder.
	Locale             : en-US
	MoreInfoURL        : https://github.com/EWSoftware/SHFB
	InstalledByMSI     : False
	SupportedFrameworkVersionRange : [4.5,)

	SignatureState     : Unsigned
	Supported Products : 
		Microsoft.VisualStudio.Community
			Version : [14.0,15.0]

	References         : 
		-------------------------------------------------------
		Identifier   : Microsoft.VisualStudio.MPF.12.0
		Name         : Visual Studio MPF 12.0
		Version      : [12.0,)
		MoreInfoURL  : 
		Nested       : No

Signature Details...
	Extension is not signed.

Searching for applicable products...
Found installed product - Global Location
Found installed product - ssms
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by EWSoftware** [comment]
The package is configured to install on Community Edition or above for 2015 and 2017.

I'm not sure if it makes a difference but if you haven't done so already, run Visual Studio at least once so that it completes its setup.  Also, make sure you're using the VSIX installer for VS 2017 (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstalller.exe).

**Comment by PCC-UK** [comment]
Cheers for getting back, yeah I had run it before. After upgrading to 15.3.1 no extensions would install with errors relating to Windows build expecting 6 not 10 etc so have logged this directly with the VS team.

I had done a clean install of VS to 15.0, ran it, updated all the extensions then went to install SHFB. Seems something somewhere has gotten corrupt so it was quicker to do a clean install of the OS.
