### ISSUE TITLE
Multi-type explicit interface implementations

### ISSUE THREAD

**Issue by kaosborn** [EWSoftware/SHFB#505]
My project is having an issue with generation of the Explicit Interface Implementations section
for classes that subclass generic interfaces with more than one type - specificially, IDictionary<K,V>. Classes that subclass generic interfaces with a single type generate fine.

Besides this nagging issue, the build is clean. The log is showing missing content warnings although it is present in the supplying .xml file. Here is an example SHFB-generated page with the missing content issue:

https://kaosborn.github.io/help/KaosCollections/html/2e99c382-c807-509e-b1e5-24083454166f.htm

I know about the member ID fixup plugin. It there some transformation needed for multiple-type generic subclassing?

KaosCollections library build: .NET cross platform (3.5, 4.0, NetStandard 1.0)
Environment: Visual Studio 2017.2 / C#; SHFB 2017.5.15.0 (integrated)

**Comment by EWSoftware** [comment]
The trick to fixing these is to compare the ID it's failing on with the ID in the XML comments file to identify the difference.  You can then figure out the expression to use in the ID fix-ups plug-in to correct them.  In this case, add an entry to replace `{TKey,TValue}` with `{TKey@TValue}`, no need to use the regex option.

Anything left over as far as missing documentation warnings after adding that is genuinely missing documentation.

**Comment by kaosborn** [comment]
Thanks a lot, that fixed it.  Shoulda tried that in hindsight, seems obvious now.
