### ISSUE TITLE
Show only (by default) Properties list for class (i.e. hide Inheritance Hierarchy, Syntax, Constructors, Methods)?

### ISSUE THREAD

**Issue by lanthonyneville** [EWSoftware/SHFB#507]
For almost every class in my project, I would like to document only the Properties list (i.e. hide the Inheritance Hierarchy, Syntax, Constructors & Methods lists).

The reason is this: the project being documented is a WCF web-service, and the audience is the clients consuming the web-service. For all the data model classes (i.e. data being posted/retrieved via service methods), all they need to know are the properties; they will never directly construct the objects, call methods, and any inheritance hierarchy is meaningless to them.

For a few types however (e.g. the interfaces defining the web-service methods), I DO need the methods to be documented.

I can see that I can exclude constructors and methods on a class-by-class basis using the API Filter. As there are around 100 classes (and more being added!), I would love to see a way to apply a default rule.

Is there a way to do this?

Note: regarding inheritance: I DO need to show inherited properties, I just don't want to show the section called "Inheritance Hierarchy".

I am using HTML Help 1 (CHM) output by the way.

Thanks

**Comment by EWSoftware** [comment]
The [Documented Entities Only plug-in](http://ewsoftware.github.io/SHFB/html/1c05f8f0-71f3-420a-b546-a438c435b759.htm) will generate an API filter at build time based on which members have XML comments on them or ones that are not explicitly excluded using the `exclude` element.  That's the only automated option to creating an API filter.

To remove sections from each topic such as the inheritance hierarchy, you'd need to clone and modify the presentation style.
