### ISSUE TITLE
Feature Request: Hiding Extension Methods

### ISSUE THREAD

**Issue by wmjordan** [EWSoftware/SHFB#509]
Currently SHFB generate documentations for members with applicable extension methods as their members. I checked the `Visibility` section of the project properties dialog, but could not find an option.
Is it possible to provide an option to exclude those extension methods?

**Comment by EWSoftware** [comment]
You can use the API filter to remove the extension methods type.

**Comment by wmjordan** [comment]
Hi,

I'd downloaded the latest release version. The API filter does not provide a filter for the extension methods.
What I want is not to hide the definition of the extension methods, but to hide them from being displayed in other matching members. For instance, there is a struct named `S` and in class `E` has defined an extension method named `Ext` for all struct types. I don't want `Ext` to appear in the member list of `S`. What shall I do?

**Comment by EWSoftware** [comment]
Based on your description it sounded like you wanted them all removed so using the API filter, you'd exclude the extension method's type.  When coding them such that they appear for all types, you can't pick and chose which types the extension methods appear on in code and thus can't in the documentation either.

That said, you may be able to use the [XPath Reflection File Filter](http://ewsoftware.github.io/SHFB/html/cd68ef02-3493-4af6-96de-1957b0aaf858.htm) plug-in to remove the extension method entries from the member lists of the types you don't want them in.  The queries would be something like:

```
/reflection/apis/api[@id='T:My.Type.Name']/elements/element[@source='extension']
/reflection/apis/api[@id='Methods.T:My.Type.Name']/elements/element[@source='extension']
```

Repeat for each type.

**Comment by wmjordan** [comment]
Thanks for the explanation. I am about to get what I want.
I tried to use the `current()` function in the XPath expression, but errors occurred, warning that "an `XsltContext` instance is required".

**Comment by wmjordan** [comment]
Eventually I used the following XPath to exclude extension methods generically targeting `System.Object` and kept other extension methods which were specifically applicable to the extended type.

````
/reflection/apis/api/elements/element[@source='extension' and @api = /reflection/apis/api/@id[../parameters/parameter[1]/type[@api='T:System.Object']]]
````
