### ISSUE TITLE
Configurable parameters for IntermediateTocTransformation

### ISSUE THREAD

**Issue by NerdyDuck** [EWSoftware/SHFB#510]
I created a variation of your Markdown style that does not include API type members in the _sidebar.md, only namespaces and types. I did that by adding a modified version of _CreateVSToc.xsl_. Everything is working fine, but now I would like to make that modification configurable. Unfortunately, `PresentationStyleSettings.TransformComponentArguments` only works for the API pages, but not for _toc.xml_. And while I can set `PresentationStyleSettings.IntermediateTocTransformation` to a `TransformationFile` that has a dictionary of parameters to be used in the transformation, I can see no way to make those parameters configurable via either UI or _.config_ file. Or did I miss something?

**Comment by EWSoftware** [comment]
There is no means of defining or overriding parameters for the TOC transformation through the project like there are for the transform component.  You can use the substitution syntax (`{@ProjectProperty}`) as the value to have it substitute the indicated project property value at build time.  That's how the project node ID is set for the doc model transformation.  You'd just have to ensure that the custom property existed in the projects that use your presentation style.

**Comment by NerdyDuck** [comment]
I'll give it a try. Thanks for your hint!
