### ISSUE TITLE
Update completion list augmentation to address changes in Roslyn 2.5

### ISSUE THREAD

**Issue by sharwell** [EWSoftware/SHFB#511]
Starting with Roslyn 2.5, some completion items previously added only as part of the SHFB extension are directly supported by the editor. After these items ship in a preview release of Visual Studio (should be Visual Studio 2017 version 15.5 Preview 1, whenever that is), we should verify that the SHFB extension still "plays nice".

:link: dotnet/roslyn#21479

**Comment by EWSoftware** [comment]
@sharwell VS 2017 15.5 is now generally available.  I don't see anything different in the completions with or without the option to enable the extra set in SHFB.  Did this get pushed back to a later release?

**Comment by sharwell** [comment]
@EWSoftware No, it definitely shipped. It must just work without extra work. 😄

**Comment by EWSoftware** [comment]
Okay.  I'll consider this closed then.  Feel free to reopen it if needed.
