### ISSUE TITLE
Install package and Build doc with default values

### ISSUE THREAD

**Issue by tojak** [EWSoftware/SHFB#512]
May I am missunderstanding this project, but I would expect the package to be used by just importing it via nuget to the project and voila. The next build should create my source code documentation.

Some further description:
- The include of the package should extend the csproj-File of the project where it is included
- When building the solution/project documentation should be created

**Comment by EWSoftware** [comment]
The NuGet package is for use on build servers, command line builds, or just on systems where you don't have the standalone tools or Visual Studio package installed.  You still need to create a project and define its documentation sources and other project options either through the standalone GUI or Visual Studio before they can be used though.

See the [Getting Started](http://ewsoftware.github.io/SHFB/html/b772e00e-1705-4062-adb6-774826ce6700.htm) topic for details.
