### ISSUE TITLE
Exclude all Methods, Events and Fields automatically using just a flag or a setup parameter

### ISSUE THREAD

**Issue by FMoralesLdG** [EWSoftware/SHFB#514]
Hi, 
I would like to generate a .chm file just with Constructor and Properties information, I can see that I can use the "Api Filter" to find and "uncheck" all the fields that I don´t want to show but I have to to do it one by one.

There is any way to hide and exclude all "Methods, Events and Fields" sections automatically using just a flag or a setup parameter?, I only would like to show the "Properties" section.

Thanks a lot

Francisco Morales

**Comment by EWSoftware** [comment]
No, there are no options to do that.  If you only put triple-slash XML comments on the members you want included you can use the [Documented Entities Only plug-in](http://ewsoftware.github.io/SHFB/html/1c05f8f0-71f3-420a-b546-a438c435b759.htm) which auto-generates an API filter based on which members have XML comments.

Another option is to put the deprecated [exclude XML comments element](http://ewsoftware.github.io/XMLCommentsGuide/html/a8ade450-e201-401a-923d-1a1169ef7828.htm) on all the members you don't want included.  It does something similar by adding them to the API filter for exclusion when the help file is built.
