### ISSUE TITLE
MRefBuilder crashes "not possible but apparently it happened"

### ISSUE THREAD

**Issue by jany-tenaj** [EWSoftware/SHFB#516]
I'm running Version 2017.5.15.0.

When I try to create the [help file](https://github.com/DotSpatial/DotSpatial/tree/master/Source/Documentation) for [my project](https://github.com/DotSpatial/DotSpatial) MRefBuilder crashes as long as my source code contains [public void WriteRaster(T[][] buffer)](https://github.com/DotSpatial/DotSpatial/blob/master/Source/DotSpatial.Data/Raster%7BT%7D.cs#L540). If I remove that method everything works without problem.

Full log: [log.txt](https://github.com/EWSoftware/SHFB/files/1306301/log.txt)

Any idea how to fix this?

**Comment by EWSoftware** [comment]
This is an issue similar to #302.  I need to add some more code to handle this new case.  I'll see about getting a patched version available this weekend.

**Comment by EWSoftware** [comment]
Fixed by the latest commit 7ff2a0f but forgot to note it there.
