### ISSUE TITLE
Use EditorBrowsable attribute to control visibility?

### ISSUE THREAD

**Issue by mike-barnett** [EWSoftware/SHFB#519]
I've seen several very old postings on the internet about this, but didn't see any issue related to it. Is this something that can be supported? Or is already supported?

**Comment by EWSoftware** [comment]
It is not supported directly.  You may be able to use the [XPath Reflection File Filter](http://ewsoftware.github.io/SHFB/html/cd68ef02-3493-4af6-96de-1957b0aaf858.htm) plug-in to remove the unwanted members based on the attribute setting.  I believe a few have done that.  You'll need to enable the attribute visibility option in order to do that.  It's off by default so the attribute info isn't included.

It does filter compiler generated types which is done by attribute so extending it to exclude members with an `EditorBrowsableState` of `Never` should be possible.  I'll look into it when I get some time.

**Comment by mike-barnett** [comment]
Thanks! I think I’ll try the XPath thing to see how easy that is. But I don’t know what the xml looks like that I’m writing the path expression against. Is it exactly the xml that is in the C# generated .xml file? The documentation said it processes the “reflection information file”, but I’m not sure if that is the same thing or not.

Mike

**Comment by mike-barnett** [comment]
Okay, clearly it is *not* the xml file generated by the C# compiler. I’m playing with the filter to see how to make it work. But now I’m worried that this won’t work for us: we do *not* want the attributes shown in generated documentation. Is there any way to make that work? I’m thinking we may need to change the sources to extend the filtering of compiler-generated types. I hope it isn’t too difficult to build a new binary to run.

Mike

From: Mike Barnett
Sent: Thursday, September 21, 2017 1:33 PM
To: 'EWSoftware/SHFB' <reply@reply.github.com>; EWSoftware/SHFB <SHFB@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [EWSoftware/SHFB] Use EditorBrowsable attribute to control visibility? (#519)

Thanks! I think I’ll try the XPath thing to see how easy that is. But I don’t know what the xml looks like that I’m writing the path expression against. Is it exactly the xml that is in the C# generated .xml file? The documentation said it processes the “reflection information file”, but I’m not sure if that is the same thing or not.

Mike

**Comment by EWSoftware** [comment]
It's pretty old but see the last post in the following thread as it contains some expressions that reportedly do what you want including removing the attribute info: http://shfb.codeplex.com/discussions/17719

I did take a look and it is possible to add another visibility setting that lets you exclude members by the editor browsable attribute state.  It may be a few weeks before a new release is issued.  If you need something sooner, let me know.

**Comment by mike-barnett** [comment]
Thanks! I was able to get it to recognize all instances of the attribute, but I can’t seem to get it to filter based on the argument to the attribute. The attribute looks like this:

[EditorBrowsableAttribute(EditorBrowsableState.Never)]

The enum value for “Never” is 1. I’ve tried “System.ComponentModel.EditorBrowsableState.Never”, “EditorBrowsableState.Never”, and “1”, but none of those seem to match. How can I see what the xml is that is being processed so I can see how the attribute’s argument is encoded?

Mike

**Comment by EWSoftware** [comment]
Stop the build before it completes or turn off the "Clean intermediate files" project option.  In the working folder, you'll find the *reflection.xml* file.  Search it for the `EditorBrowsableAttribute` occurrences.

**Comment by mike-barnett** [comment]
I was just writing to you to tell you that I’d found that! Sorry for bothering you. I now have it working. So nice!

Thanks!

Mike

**Comment by mike-barnett** [comment]
Oh, and in case it is useful, here is what I ended up with:

/reflection/apis/api/attributes/attribute[type/@api="T:System.ComponentModel.EditorBrowsableAttribute"]/argument[type/@api="T:System.ComponentModel.EditorBrowsableState"]/enumValue[field/@name="Never"]/../../../..

/reflection/apis/api/elements/element/attributes/attribute[type/@api="T:System.ComponentModel.EditorBrowsableAttribute"]/argument[type/@api="T:System.ComponentModel.EditorBrowsableState"]/enumValue[field/@name="Never"]/../../..

(Plus then the last two lines from that last comment on the post you pointed me to in order to not have any of the attributes show up in the documentation.)

From: Mike Barnett
Sent: Friday, September 22, 2017 11:27 AM
To: 'EWSoftware/SHFB' <reply@reply.github.com>
Subject: RE: [EWSoftware/SHFB] Use EditorBrowsable attribute to control visibility? (#519)

I was just writing to you to tell you that I’d found that! Sorry for bothering you. I now have it working. So nice!

Thanks!

Mike

**Comment by mike-barnett** [comment]
Thanks so much!

**Comment by mike-barnett** [comment]
Hi! I just ran into this issue when installing Sandcastle on a new machine:

https://github.com/EWSoftware/SHFB/issues/529

I have just VS2017 installed and not VS2015. Is there a workaround? Or will Sandcastle get fixed soon enough that I should just wait for the next release?

Thanks!

Mike
