### ISSUE TITLE
Errors installing SHFB with latest VS 2017

### ISSUE THREAD

**Issue by mozzis** [EWSoftware/SHFB#520]
This is with v2017.5.15.0 downloaded today 26 Sep 2017
Guided Installer step "Sandcastle Help File Builder and Tools" failed with "Unable to locate installer: "C:\temp\SHFB\SandcastleHelpFileBuilder.msi"" The MSI file was located at the location noted in the error message. The permissions on the file were correct and I was able to install it manually by double-clicking in explorer. After installation the Guided Installation detected it and was able to proceed to the next step with no error or warning.

Guided Installer step "Sandcastle Help File Builder Visual Studio Package" failed with error "Path to VSIX file 'C:\temp\SHFB\SHFBVisualStudioPackage_VS2015AndLater.vsix' is invalid or you don't have reuired access permissions." Again, the file is present in the indicated location and the permissions were correct. Attempting to install it with from an admin command prompt with 
"vsixinstaller /skuName:Community /skuVersion:15.3.5 SHFBVisualStudioPackage_VS2015AndLater.vsix" results in an error "VSIX Installer Install Failed The install of this extension was not successful for all the selected products... This extension is not installable on any currently installed products." I have the latest VS 2017 Community installed.

The remaining steps in Guided Installation completed successfully.

**Comment by EWSoftware** [comment]
The MSI and VSIX files should be located in the .\InstallResources subfolder after you extract the zip file.  The guided installer will look there for them.  It's possible the zip file content was blocked.  That can cause some odd issues if you don't unblock it before extracting its content.

Regarding the VSIX installer issue, leave of the version number as that may have prevented it from installing if it was doing an exact comparison to the version.  In general you don't need to do that.  Just running the VSIX by itself is usually enough.

**Comment by mozzis** [comment]
It appears that the installer download was corrupted by WinZip. A new download to a different computer, copied to this one, run just fine.

**Comment by alekdavis** [comment]
I had a similar issue. The installer complained that it could not find the VS extension installed or the installation package. I paused the installation, switched to the InstallResources folder, ran the .vsix file manually, opened VS 2017 to verify that the SHFB extension is installed, closed VS, restarted the installer, and got the same message, so I decided to proceed by selecting the option to not us VS integration, and the next dialog the installer complained that it could not find any of the versions of Visual Studio for MAML Schema IntelliSense integration. I have VS 2017 Enterprise, but it is installed on the D drive (instead of C). Could it be the issue? Not sure what to do now.

**Comment by EWSoftware** [comment]
@alekdavis:  The guided installer currently only looks on the C: drive for VS2017.  Instructions for installing the MAML schemas manually can be found in the [MAML guide](http://ewsoftware.github.io/MAMLGuide/html/746fc19e-2670-440b-8277-a1ef7dc074d5.htm).

**Comment by alekdavis** [comment]
Bummer. :-( Thanks.

**Comment by alekdavis** [comment]
Btw, in the MAML Snippet Files step, it does seem to detect the VS 2017 installation and seems to install the snippets fine (at least, does not show any errors).

**Comment by mozzis** [comment]
Please see attached.

**Comment by EWSoftware** [comment]
@mozzis There was nothing attached to your comment.

**Comment by mozzis** [comment]
Sorry, that was because of an email account being hacked.
