### ISSUE TITLE
Sandcastle Topic Grouping

### ISSUE THREAD

**Issue by matsydoodles** [EWSoftware/SHFB#521]
Is there a way to split up the API Documentation created? 

By default, Sandcastle seems to create all of this API documentation at the root of the class but I'd like to ideally split that up into two API's we provide. E.g. Automation API, and Plugin API. So I'd like to have to separate entries rather than a continuous list of a mix of both or at least where I could have it fork off in two directions based of their namespaces (e.g. some.thing.api / some.thing.automation.api).

From a bit of googling I don't think this is feasible as these two links seem to indicate that, with one mentioning a plugin would be needed but the link is dead?! 

https://stackoverflow.com/questions/1162057/sandcastle-topic-grouping
https://github.com/EWSoftware/SHFB/issues/258

Any help, and direction would be greatly appreciated.

**Comment by EWSoftware** [comment]
You can group all namespaces under a common root element using the [Root Namespace Container](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#RootNS) option.  You can further group entries with common namespace root parts using the [Namespace Grouping](http://ewsoftware.github.io/SHFB/html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm#NSGrouping) options.  That may do what you need depending on your namespaces.

Grouping by a set of user-defined rules is not supported.  For that you would need to create your own plug-in that rearranged the TOC at build time.
