### ISSUE TITLE
How To Launch Help File?

### ISSUE THREAD

**Issue by green4don** [EWSoftware/SHFB#522]
This could be education, feature request or impossible.

I use SHFB in Visual Studio (2017) to build both developer API documentation and am now converting my HTML Help user application help to SHFB using the 'Additional Content Only' plug-in. Still a learning curve, but moving forward. My target is a CHM file (HTML Help 1).

I'm used to a compile/run cycle with my C# coding and testing. In an SHFB project, the 'Start' button simply builds the help file (again). Not something that helps me.  To launch my help file I need to open an Explorer window, navigate to the /Help directory and double-click on the help file. Plus remember to close it so that I can rebuild.

Works, but not very effective, especially in my current mode of migration from .html to MAML.

Suggestions are welcome, thanks.

**Comment by EWSoftware** [comment]
The help file viewing options are available in the [View | View Help File](http://ewsoftware.github.io/SHFB/html/78507051-0fc0-479b-9d47-78a10398eaf2.htm#SHFBToolbar) submenu.  There's also a SHFB toolbar that you can show to get to them quickly.

You'll still need to remember to close it to rebuild.

**Comment by green4don** [comment]
Thanks, and the reference to the SHFB help file helps.
Can't find anything under the View menu, so no idea on this.
Enabling the SHFB toolbar adds a 3 item toobar: View Help File, FAQ, Help on Sandcastle.
But the first item is disabled, so maybe doesn't apply to a chm file?
So, better, but still nothing that works.
I'm running Community 2017 15.3.4 with SHFB v2017.5.15.0

**Comment by green4don** [comment]
When I select the SHFB project properties tab, the first item changes to 'View Help Build Log Content' and enables. On all other tabs it's disabled.

**Comment by EWSoftware** [comment]
The commands relevant to the SHFB projects are only enabled when something in  a SHFB project is the selected item in the Solution Explorer tool window.

**Comment by green4don** [comment]
Doesn't seem to matter what I select in Solution Explorer. Anything other than the SHFB project has a disabled icon. The project offers the same build log as above.

Seems to me, that if I make the SHFB project the startup project, then start should display the help file. Right now it just rebuilds the help file.

All in all, since there's work arounds, it's not a big issue.

**Comment by EWSoftware** [comment]
SHFB projects don't build runnable output so they don't do anything if set as the startup project.

**Comment by green4don** [comment]
Technically true, but the run button executes a build. By your logic, maybe it should do nothing. Still, no button I can find or enable to run the help that is built. 

Again, all in all, since there's work arounds, it's not a big issue.
