### ISSUE TITLE
Support for .NET Standard 2 / .NET Core 2

### ISSUE THREAD

**Issue by bleepzter** [EWSoftware/SHFB#523]
Documenting projects targeting the .NET Standard causes following issues:

1. It gets confused between .NET Standard 2.0 and the .NET Framework in regard to the runtime:

Sample error/warning bellow:
```
prepareForBuild:
  Creating directory &quot;obj\Debug\&quot;.
_HandlePackageFileConflicts:
  Encountered conflict between &#39;Reference:C:\Users\*****\.nuget\packages\netstandard.library\2.0.0\build\netstandard2.0\\ref\System.Runtime.InteropServices.RuntimeInformation.dll&#39; and &#39;Reference:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\net47\ref\System.Runtime.InteropServices.RuntimeInformation.dll&#39;.  Choosing &#39;Reference:C:\Users\*****\.nuget\packages\netstandard.library\2.0.0\build\netstandard2.0\\ref\System.Runtime.InteropServices.RuntimeInformation.dll&#39; because file version &#39;4.6.25519.3&#39; is greater than &#39;4.6.25514.4&#39;.
```
This confusion happens for the following assemblies although the assemblies seem to be resolved based on the file version. The list is quite inclusive and spans for the entire .net standard:

System.Runtime.InteropServices.RuntimeInformation.dll
System.Security.Cryptography.Algorithms.dll
System.ValueTuple.dll
Microsoft.Win32.Primitives.dll
netstandard.dll
System.AppContext.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Console.dll
System.Data.Common.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.Diagnostics.Tracing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.dll
System.Globalization.Extensions.dll
System.IO.Compression.dll
System.IO.Compression.ZipFile.dll
System.IO.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Net.Http.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.Sockets.dll
System.Net.WebHeaderCollection.dll
System.Net.WebSockets.Client.dll
System.Net.WebSockets.dll
System.ObjectModel.dll
System.Reflection.dll
System.Reflection.Extensions.dll
System.Reflection.Primitives.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Security.Claims.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Principal.dll
System.Security.SecureString.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.RegularExpressions.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.Xml.ReaderWriter.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll

After the code iterates through all the assemblies of .net standard 2.0 it errors out as follows:

**Unresolved assembly reference: System (System, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089) required by netstandard** 

```
GenerateRefInfo:
  MRefBuilder (v2017.5.15.0)
  Copyright c 2006-2017, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2016, Eric Woodruff, All Rights Reserved.
  No source code context base path specified.  Source context information is unavailable.
  Loaded 1 assemblies for reflection and 124 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: System (System, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089) required by netstandard [C:\Projects\Core2\****\****\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:03.0160
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

**Comment by EWSoftware** [comment]
Can you attach or e-mail me a sample project I can use to duplicate the issue?

**Comment by bleepzter** [comment]
Eric, I appologize but i am not near a computer at the moment. However, I
can give you the steps to reproduce:

Install VS2017 (15.3)
Install Core 2 SDK
Install SHFB V2017.5.15 extension for VS2017

Create new Class Library targeting the net standard. To do so use the "Net
Standard" tab in the VS project creation wizard.

Add the xml comments to Class1.cs that was created by default from the
project creation wizard.

In the same solution add a new Documentation project by right clicking on
the solution, selecting "Add" and clicking on the "New Project" option.

Click on the "Documentation" tab and pick the Sandcastle Help File Builder
project.

Add the Net Standard Project as Documentation source. Add build log file
name in the Documentation project properties. Build.

You should see the error in the build log file. Essentially SHFB has no
clue where the System namespace comes from when dealing with .Net
Core2/Standard 2.

Thanks

**Comment by EWSoftware** [comment]
Did you set the Framework Version project property to "Cross Platform (.NET Core/.NET Standard"?  That may resolve the issue.  If you use one the default .NET Framework setting, the assemblies definitely won't match.

**Comment by bleepzter** [comment]
Changing the framework to Cross Platform (.NET Core/.NET Standard also
didn't work. I tried several frameworks and had the same result.

On Oct 4, 2017 1:01 PM, "Eric Woodruff" <notifications@github.com> wrote:

Did you set the Framework Version project property to "Cross Platform (.NET
Core/.NET Standard"? That may resolve the issue. If you use one the default
.NET Framework setting, the assemblies definitely won't match.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EWSoftware/SHFB/issues/523#issuecomment-334257201>, or mute
the thread

**Comment by EWSoftware** [comment]
> Install Core 2 SDK
Where do you get that?  Is that part of the Visual Studio Installer or a separate download.  If so, where from?

**Comment by bleepzter** [comment]
https://www.microsoft.com/net/download/core

**Comment by EWSoftware** [comment]
I tried to duplicate this using the steps you noted above but was unable to do so.  I used VS 2017 15.3 and also 15.4 and neither has a problem documenting a .NET Standard 2.0 project.  Is this still an issue for you?  Can you provide a failing example?

**Comment by jburzynski** [comment]
I have the exact same problem. My project is .NET Standard 2.0 and I have selected ".NET Core / .NET Standard" in the SHFB GUI. I try to build it with msbuild 15.4.8.

As an example you can use my project, which is open source anyway, so I'm not concerned with code leaking etc.: http://jburzynski.net/TypeGen/api%20ref.zip

Thanks a lot for this great project!
Hope I can help with this example.

**Comment by bleepzter** [comment]
So the only way to get .Net Core if you add the assembly bind redirect and
ignore netcoreapp2.0 or netstandard otherwise SHFB blows up.

**Comment by EWSoftware** [comment]
Attached is a patched version of *MRefBuilder.exe* that should correct this issue.  It automatically redirects the System assembly for .NETStandard.  Replace the copy in the SHFB installation folder or, if using the NuGet package, the package folder.  This update will be in the next release but I don't have an estimate on when that may be yet.

[MRefBuilderPatched_20171028.zip](https://github.com/EWSoftware/SHFB/files/1424568/MRefBuilderPatched_20171028.zip)

**Comment by jburzynski** [comment]
After applying this patch, I receive another error:
`[my_path]\Help\Working\GenerateRefInfo.proj(834,5): error MSB4062: The &quot;Microsoft.Ddue.Tools.MSBuild.MRefBuilder&quot; task could not be loaded from the assembly C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\\MRefBuilder.exe. Could not load type &#39;Sandcastle.Core.VisibleItems&#39; from assembly &#39;Sandcastle.Core, Version=2016.4.9.0, Culture=neutral, PublicKeyToken=c8895f0c125eff20&#39;. Confirm that the &lt;UsingTask&gt; declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

This occurs directly after the list of conflicts (`Encountered conflict between (...)`).

Do you have an idea what can be causing it?

**Comment by EWSoftware** [comment]
I've been moving some stuff around and forgot about those changes.  I'm not ready to issue a new release yet since I'm in the middle of a bunch of changes so this will have to wait until the next release.
