### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by CvanLeeuwenFt** [EWSoftware/SHFB#526]
Sandcastle was working fine with my VS2015.
I add VS2017.3 (15.3.5) community edition.
After the installation of VS2017.3 community, the SANDCASTLE  installer of the Install Package hangs.

I de-installed Sandcastle and I also remove the keys in the registry.
I still getting back the same error:
The extension is already installed to all applicable products.
Unexpected exit code 1001.
And the next steps of the Sandcastle installation will not start.

How I can completely remove Sandcastle?

**Comment by EWSoftware** [comment]
All that's necessary to uninstall the Visual Studio package is to select *Tools | Extensions and Updates* in Visual Studio, find the entry for SHFB, click the Uninstall button, and restart Visual Studio.

If the guided installer is having a problem, you can run the VSIX package directly to install it.  It's located in the *.\InstallResources* subfolder with the guided installer executable.

You'll need at least version  2017.1.28.0 of SHFB to support VS 2015 and 2017.  The latest release is preferred.

**Comment by CvanLeeuwenFt** [comment]
Thanks, after a whole weekend of trying to find a solution, is your suggestion is working.
Both under VS2015  Enterprise  and VS2017 community 
Sandcastle v2017.5.15.0 is working fine now.
