### ISSUE TITLE
Project file wan not processed

### ISSUE THREAD

**Issue by FabioBo** [EWSoftware/SHFB#527]
1. "Compile Remove" syntax is not recognized
2. "Version" into PackageReference and into DotNetCliToolReference is not recognized
After removing "Remove" and "version" keyword we receive this error:
SHFB: Error BE0065: BUILD FAILED: value could not be null. Parameter Name: Key
What does Key parameter mean?

Here is project sample file:
<Project Sdk="Microsoft.NET.Sdk.Web" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Gulliver.Web.Site</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Gulliver.Web.Site</PackageId>
    <UserSecretsId>aspnet-Gulliver.Web.Site</UserSecretsId>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Compile Remove="wwwroot\**\*;node_modules" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
    <None Update="wwwroot\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gulliver.CommonClasses\Gulliver.Web.CommonClasses.csproj" />
    <ProjectReference Include="..\Gulliver.Web.Data\Gulliver.Web.Data.csproj" />
    <ProjectReference Include="..\Gulliver.Web.Routing\Gulliver.Web.Routing.csproj" />
    <ProjectReference Include="..\Gulliver.Web.Security\Gulliver.Web.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExtreme.AspNet.Core" Version="17.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="BundlerMinifier.Core" Version="2.5.357" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0" />
    <PackageReference Include="NETCore.MailKit" Version="2.0.1" />
    <PackageReference Include="SendGrid" Version="9.9.0" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="1.1.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
    <PackageReference Include="UAParser" Version="3.0.0" />
  </ItemGroup>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
  </Target>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.2.281" />
  </ItemGroup>

</Project>

**Comment by EWSoftware** [comment]
Are you using MSBuild 15.0 either from the command line or in Visual 2017?  The newer project format and elements won't be recognized by MSBuild 14.0 or earlier.  The standalone GUI uses MSBuild 14.0 and also will not recognize project documentation sources using the newer format.

**Comment by FabioBo** [comment]
We have installed Visual Studio 2017, MSBuid 15.0 was installed with VS2017.
How could we make documentation using VS extention or other method alternative to GUI?
Thank you

Fabio Borghi

InITeC
Via XXV Aprile 6/g
21023 Besozzo (Va) Italia
Tel. +39 (0332) 971.401
Fax +39 (0332) 774.119



Da: Eric Woodruff [mailto:notifications@github.com]
Inviato: martedì 10 ottobre 2017 23:08
A: EWSoftware/SHFB <SHFB@noreply.github.com>
Cc: Fabio Borghi <fabio.borghi@initec.it>; Author <author@noreply.github.com>
Oggetto: Re: [EWSoftware/SHFB] Project file wan not processed (#527)


Are you using MSBuild 15.0 either from the command line or in Visual 2017? The newer project format and elements won't be recognized by MSBuild 14.0 or earlier. The standalone GUI uses MSBuild 14.0 and also will not recognize project documentation sources using the newer format.

**Comment by EWSoftware** [comment]
I saved your example project and attached it to a SHFB project and it was able to parse it.  It won't build of course because it can't find any of the project references.  Can you provide an example of a failing project that I can build to see what it is that you are seeing?

**Comment by FabioBo** [comment]
Hi Eric,
here is my sample project
Thank you
Fabio


Da: Eric Woodruff [mailto:notifications@github.com]
Inviato: domenica 15 ottobre 2017 23:25
A: EWSoftware/SHFB <SHFB@noreply.github.com>
Cc: Fabio Borghi <fabio.borghi@initec.it>; Author <author@noreply.github.com>
Oggetto: Re: [EWSoftware/SHFB] Project file wan not processed (#527)


I saved your example project and attached it to a SHFB project and it was able to parse it. It won't build of course because it can't find any of the project references. Can you provide an example of a failing project that I can build to see what it is that you are seeing?

**Comment by EWSoftware** [comment]
Building documentation using the example project works as expected in Visual Studio 2017.  Are you perhaps using the standalone GUI to try and build the project?  The standalone GUI doesn't support the newer project formats as it uses a version of MSBuild that doesn't support them.  To build the documentation projects that reference the newer MSBuild project formats you need to use Visual Studio or an appropriate version of MSBuild from the command line.
