### ISSUE TITLE
SHFB: Error BE0032: Reflection data files for the selected framework do not exist yet (.NET Framework 4.0).  See help file for details about this error number.    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

### ISSUE THREAD

**Issue by ekundan** [EWSoftware/SHFB#530]
errr

**Comment by EWSoftware** [comment]
If you're using the NuGet package, you probably haven't installed the corresponding NuGet package containing the framework data set files.  See the [error number description](http://ewsoftware.github.io/SHFB/html/bc38b398-4cca-4972-b4b5-966def8428b4.htm) for more information.  See the [NuGet/XCOPY Build](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) topic as well for additional requirements.

**Comment by DanielCarswell** [comment]
Hi just wanted to mention that I had this error appear even though it was loading the selected framework, don't fully know why the reason caused this problem however it was because of duplicate files from reinstalling and not properly deleting old files so it confused directory I assume.
