### ISSUE TITLE
Word cannot open generated DOCX

### ISSUE THREAD

**Issue by jsmcmn** [EWSoftware/SHFB#531]
Sandcastle 2017.5.15.0 generates a DOCX, no errors given.  Word tries to open it but says "We're sorry.  We can't open MyFile.docx because we found a problem with its contents." "Details: Unspecified error.  Location:  Part: /word/document.xml, Line: 0, Column:0".

It might be a problem with how Sandcastle handles the XML tags 'seealso' and 'para', according to https://stackoverflow.com/questions/46246964/how-might-i-troubleshoot-a-sandcastle-generated-defective-ms-word-file.  

Apparently avoiding using those two tags results in the DOCX being built correctly.

**Comment by EWSoftware** [comment]
The `seealso` element with or without inner text and  `para` elements don't cause any issues that I'm aware of.  Both are quite commonly used and the test cases I've got build without issue using the Open XML format.  The most common cause is invalid content or stray HTML elements that aren't valid in Open XML (i.e. stuff that gets passed through as-is in a `markup` element).  Unlike HTML, Open XML is unforgiving with regard to the structure of the content.

See the [Open XML Format](http://ewsoftware.github.io/SHFB/html/c5e7e920-2cb4-4f78-b167-634361d85263.htm) topic for known limitations and tips on finding out what is wrong in invalid documents by using the project options to produce a better location for the invalid content.

If you can find a case of a `seealso` or `para` element that consistently generates invalid Open XML content, add an example and I'll see if it can be corrected in the presentation style.

**Comment by nicolaceliento** [comment]
I removed the following comments and worked for me. Could be "table list" the issue?

`///     <para>
///         <list type="table">
///             <listheader>
///                <term>MyTerm 1</term>
///                <description>MyDescription 1</description>
///             </listheader>
///             <item>
///                 <term>MyTerm 2</term>
///                 <description>MyDescription 2 <see cref="MyClass.MyField"></see></description>
///             </item>
///         </list> 
///     </para>`

**Comment by EWSoftware** [comment]
See the [Open XML Format help topic](http://ewsoftware.github.io/SHFB/html/c5e7e920-2cb4-4f78-b167-634361d85263.htm) for information on known issues and limitations as well as how to troubleshoot corrupted content to determine its cause.
