### ISSUE TITLE
How to avoid language-based duplicated items in index

### ISSUE THREAD

**Issue by jotkol** [EWSoftware/SHFB#533]
I can't find a way how to get rid of duplicate index items.
In my project, I want to support only C#, but in index appear both C# and VB syntax items.
Sample screenshot:
![shfb - duplicate](https://user-images.githubusercontent.com/15212353/32229926-3b5042e2-be52-11e7-90d2-40d7b76872fd.PNG)

**Comment by EWSoftware** [comment]
It's done as part of the XSL transformations in the related presentation style.  Where exactly I don't recall.  I'd have to go find it.  The presentation style XSL transformations would need to be modified to get rid of the parts that generate the unwanted entries.

**Comment by jotkol** [comment]
Thanks. I'll try to find it myself.
