### ISSUE TITLE
MSDN URL not found for AspNetCore framework classes

### ISSUE THREAD

**Issue by Advitalitum** [EWSoftware/SHFB#534]
MSDN URL not found for target 'M:Microsoft.AspNetCore.Mvc.ControllerBase and others. How can i fix it?

**Comment by EWSoftware** [comment]
If the MSDN web service isn't resolving it, there isn't much you can do besides ignore the warning.  The MSDN web service covers the base framework but doesn't always include link info for supporting assemblies.  If you find the warnings bothersome, you can use the Additional Reference Links plug-in to generate enough information for the assemblies containing the unresolved members to suppress the warnings.
