### ISSUE TITLE
DisplayVersion meta tag in Help Viewer

### ISSUE THREAD

**Issue by claudettecedras** [EWSoftware/SHFB#535]
Hi,
I'm trying to add the new DisplayVersion meta tag (see below) in my Help Viewer generated topics. The DisplayVersion property does not appear in the MS Help Viewer properties page. 

<meta name="Microsoft.Help.DisplayVersion" content="Stuff 5" />

I've tried to add the tag in the Help File page, in the Additional header content text box. The tag is added to the files, but outside the <head></head> tag, in the body of the topic. 

I've also tried to create a user defined attribute named DisplayVersion and containing the meta tag as the value, but it does not get included in the files. 

Is there a way I can do this? I understand that this tag is relatively new, but it's a nice feature.

I'm using the standalone GUI SHFB, v 2017.5.15.0.

Thanks, Claudette

**Comment by EWSoftware** [comment]
It's not one I'm aware of.  Do you have a link to any information about it?  More likely than not it'll need to go in the presentation style XSL transformations.

**Comment by claudettecedras** [comment]
Hi,
I found it in the Help 2 Viewer mvp (http://hv2.helpmvp.com/doc/file-format). I thought it was new, but it was in 2012... I could not find it in the Help Viewer SDK however. In any case it's a useful feature for me, it works well and and I would like be able to use it without having to create a little program to parse through my 9000 topic files...

Thanks, Claudette

**Comment by EWSoftware** [comment]
That will need to be added to the presentation style transformations.  What should it contain?  Would the value come from a new project property separate from all the existing ones or would it be the value of an existing project property such as the Help Title?

**Comment by claudettecedras** [comment]
Well, in my case the Help title would be too long, however, in the mean time, I could use the Product title. I guess it would be preferable to have a separate property. 

Claudette

**Comment by EWSoftware** [comment]
I can add a new project property.  There's already an Additional Header Resources Component in the BuildAssembler configuration file which can add additional metadata elements.  The new value can be added by it rather than changing the transformations.

**Comment by claudettecedras** [comment]
Thanks, that's perfect!

Claudette
