### ISSUE TITLE
Parameter type is recognized as Void in a method signature

### ISSUE THREAD

**Issue by CXuesong** [EWSoftware/SHFB#536]
I've been using SHFB to generate documentation for my library and it works very well. However, I came across a problem on some of the generated pages. For example, I have
https://github.com/CXuesong/WikiClientLibrary/blob/0b4cbacd26d969114d5b9451a96c8d0afb26838c/WikiClientLibrary/Generators/Primitive/WikiPageGenerator.cs#L17-L24

But the generated documentation page seems to have missed something:

https://cxuesong.github.io/WikiClientLibrary/html/7b9d3f40-4bc3-d63a-7b50-1deba2c2f906.htm

The method documentation is missing, and most of all, the type of the parameter is `Void`. I'm not sure if anyone else has met with similar problems, but I just have no idea. Could I have done something wrong when writing documentation or configuring the SHFB?

**Comment by EWSoftware** [comment]
It looks like problem with the .NET Standard support.  I'll take a look at it when I get a chance sometime this week.

**Comment by EWSoftware** [comment]
The build engine isn't handling the package references properly.  The NuGet package folder property has two path's in it separated by a semi-colon which it doesn't currently account for.  Once I get that fixed, it'll work as expected and you won't need the binding redirection plug-in to ignore the currently missing references as it will resolve them all as expected.

The fix will be in the next release which is still a few weeks out.

**Comment by CXuesong** [comment]
I see. So I won't need to add those binding redirects to suppress the missing dependency errors.

But will it also resolve the problem I mentioned here? Because the parameter type [`PageQueryOptions`](https://github.com/CXuesong/WikiClientLibrary/blob/0b4cbacd26d969114d5b9451a96c8d0afb26838c/WikiClientLibrary/Pages/WikiPage.cs#L824) is in my `WikiClientLibrary` package.

**Comment by EWSoftware** [comment]
Yes.  Right now its missing all of the package references.  Once the fix is in place it will find them all and will be able to resolve the types correctly.
