### ISSUE TITLE
[CodeColorizer] regex lookbehind/lookahead support

### ISSUE THREAD

**Issue by GKotfis** [EWSoftware/SHFB#537]
I'm trying to enhance python code style by adding new regex rule:
`(?&lt;=def)\s+([[a-zA-Z_]*)(?=\()`
to catch method declaration like:
`def my_method():`
`def some_other_method():`

After several failures, regex adjusting I looked at the [CodeColorizer.cs](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/CodeColorizer/ColorizerLibrary/CodeColorizer.cs) and see that `ApplyRules` method does not support such things since after positive match it removes matched code and goes ahead. 
Following my example:
1. `def my_method();` - `def` will be matched with one of the defined keywords and removed from the code
2. ` my_method();` - will not match since regex looks behind for `def` token

**Comment by EWSoftware** [comment]
Colorization is context based and only moves in the forward direction as you noted.  It's used mainly to match language keywords and constructs like comments and string literals, not necessarily user-defined elements like method names that may be preceded or followed a keyword.  Adding look behind/look ahead support would require reworking how the colorizer works.  It's not something I plan on supporting.

However, you may be able to do what you want by putting your new rules ahead of the keyword rule.  The expressions are evaluated in the order given as I recall so if something ahead of another rule matches its text, the subsequent rules wouldn't see it.
