### ISSUE TITLE
Problem to document a Remarks

### ISSUE THREAD

**Issue by josselin1503** [EWSoftware/SHFB#539]
Hello,

I am using Sandcastle and I would like to display the values of my constants (propert.
They are stored in the <remarks> tag but they are not documented in the output HTML.

My code:

```
		/// <summary>
		/// Default geometric linear precision (in meters): two points which are less
		/// than this distance apart are considered coincident.
		/// </summary>
		public const double LinearPrecision = 1e-8;
```

The XML:
```
    <member name="F:MyNamespace.MyClass.LinearPrecision">
            <summary>
            Default geometric linear precision (in meters): two points which are less
            than this distance apart are considered coincident.
            </summary>
            <remarks>
                <para>Currently set to 1e-8m.</para>
            </remarks>
    </member>
```

On the other side of my code for documentation, it works (but there are no <para> tag).

Thanks in advance

**Comment by EWSoftware** [comment]
The `remarks` element would have to appear in the code.  If it's in the XML comments file it was there at some point and may just need adding back.  Also note that for simple types such as string, integers, doubles, etc. the constant will appear in the Syntax Section so you may not need the remark at all.

**Comment by jotkol** [comment]
There is note about constant itself, but no info about value. According to XML comments file where there is no info about const value too.

![sandcastle - const in syntax section](https://user-images.githubusercontent.com/15212353/33363854-697ec246-d4e2-11e7-9334-11c67cf11672.PNG)

**Comment by EWSoftware** [comment]
The value is pulled from the assembly metadata not the XML comments file.  If I paste this into a C# project and build a help file:

``` C#
/// <summary>
/// Default geometric linear precision (in meters): two points which are less
/// than this distance apart are considered coincident.
/// </summary>
public const double LinearPrecision = 1e-8;
```

I get this in the help topic for it when using the VS2013 presentation style (latest release but constant values have been output for quite a while):

![image](https://user-images.githubusercontent.com/10552523/33384910-1fc9fd4c-d4dc-11e7-8a7b-0fcac7a9e5c5.png)

**Comment by jotkol** [comment]
Shame to say but I forgot that I'm using version 2015.5.2 because of old plugins.
