### ISSUE TITLE
Changing Parameter names in the 'Parameters' section

### ISSUE THREAD

**Issue by Frogman7** [EWSoftware/SHFB#540]
Hello Sandcastle experts, I'm having a hard time figuring out how to get my variables renamed using my Custom Presentation Style and SyntaxGenerator.

The basics of what I'm doing is this, I'm trying to create documentation for a proprietary language based off a C# library.  Right now I have what's being generated for the "Syntax" section working great, but the Parameters and ReturnValue sections are still showing the C# based names and types.

What are my options to get these other sections generating what I want?  I noticed that there's a 'Build Component' type that I can create and I assume I can make my own and replace the default ones used by SandCastle but please let me know if there's an easier way.

**Comment by EWSoftware** [comment]
Without knowing exactly what you are trying to accomplish, I'm only guessing here.

Parameters are output by the `t_parameters` template in *utilities_references.xsl*.  You can modify that to change how it outputs the parameter name (`@name`).

Type links both in the `t_parameters` template and the `t_returns` template in *main_sandcastle.xsl* are output as `referenceLink` elements that are then handled by the `ResolveReferenceLinksComponent` to generate the link to either the MSDN or local topic.  Typically, the `referenceLink` elements are rendered without inner text so the component determines the inner text based on the type information.  If you change the way those are written out by the transformation to include the inner text of your choice, that may do what you need.  Search for the templates with a `mode="link"` attribute that output a `referenceLink` element and add the necessary inner text to them.

**Comment by Frogman7** [comment]
Well that certainly helps and I'm going through the templates now trying to better understand what they do.  However based off what I've seen so far I take it that manipulating the variable names in this way would require me to handle the logic in the XSL itself which might not provide me the flexibility I need.

**Comment by EWSoftware** [comment]
Depending on what you are trying to do to them, that may be the case.  It may be easier to write out a custom element with the name value and use a build component to change it in some way.

**Comment by Frogman7** [comment]
Thank you again for your assistance.  After researching into the build process for SandCastle a bit more I've determined my best course of action going forward will be to write a SandCastle plugin to hook into the build process and change the names in the reflection document.
