### ISSUE TITLE
Support search without a server

### ISSUE THREAD

**Issue by HarelM** [EWSoftware/SHFB#541]
Hi,

I was wondering if one can create documentation with search capabilities that does not require a server side.
Our current product is a desktop application and we would like to make the API documentation available in offline mode.
I searched a bit and found out I can use `WebDev.WebServer40.EXE` to load a local server and present the documentation using localhost, I was hoping there's a way to do it without the need for a local server.

Keep up the good work!

**Comment by EWSoftware** [comment]
I'd say the best choice would be to use a Help 1 (CHM) file which can be built concurrently with the website output.  It's can be opened locally and contains an index and search features.  Help topics can be opened from within the application using the `System.Windows.Forms.Help.ShowHelp()` method ([see this example from SHFB itself](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderUtils/Utility.cs#L52)).  The help content is compiled into a single compressed file so there's much less to deploy with the desktop application.

If you need a local website, the site can be opened using the file system by opening the `index.html` page but the browser can get much stricter about things like file access on the local file system and the user may get prompted to allow scripts to run etc.  Edge, Internet Explorer, and FireFox seem to work just fine once the blocked content is allowed to run.  Chrome loads the page but doesn't prompt to allow the blocked content and the search and TOC don't work.  There may be a setting somewhere that does allow it to work but I don't know for sure.

Using the local web dev server works and doesn't have any permission issues.  However, it isn't always installed so you can't rely on it being there to run the content.  IIS Express is another option and may be redistributable so perhaps could be deployed with your application though it may be overkill just to show help.

**Comment by HarelM** [comment]
Thanks for the detailed answer.
I wasn't aware the search can work without a server as I was using chrome and as you said it just didn't work.
I can bring web dev if needed with my installation so it's a non issue, but I would prefer not to use it as I'll need to manage a process and a port etc..
CHM is just an eyesore so I prefer a web based UX.
My initial thought, which I saw when looking at a documentation made by our technical writers (which use MadCap flare) is that all the topics are indexed into js files and these files can be used to do a client-side search.
I'm not sure if this can be applied to this library, but it sure is cool.

**Comment by StevenBonePgh** [comment]
My two cents - the .chm is good, however, you need to be aware that if the .chm is on a network drive or unzipped using (at least) windows zip support, the CHM files can be blocked.  Also, you can't read a .chm when it lives in a directory which has any characters like '#', '?', '&', and '+' in the name.  [Here is a post about it, though I saw a better one somewhere else before.](https://blogs.msdn.microsoft.com/jpsanders/2009/06/10/some-chm-files-do-not-work-on-windows-7-process-monitor-navigation-to-the-webpage-was-canceled/)
