### ISSUE TITLE
Show only child namespace

### ISSUE THREAD

**Issue by huffSamuel** [EWSoftware/SHFB#545]
I'm working on documenting a project that has a deep namespace structure and would only like to display a single namespace in this structure, preferably at the root level. For example

Namespace
Namespace.Foo
Namespace.Foo.Bar
Namespace.Foo.Bar.Methods.

A project with those namespaces would have Namespace in the root, foo inside that, etc down to Namespace.Foo.Bar.Methods, which contains the actual documentation I would like to show.

Is there a way to display Namespace.Foo.Bar.Methods at the root level without displaying all the namespaces that come before it?

**Comment by EWSoftware** [comment]
Perhaps I'm misunderstanding you, but if you don't want to see anything in the other namespaces, you can use the API filter to remove them.

**Comment by huffSamuel** [comment]
I apologize, I had namespace on my brain, which was definitely not the right term. See the attached image for a better example. I would like to display Foo Methods at the root level instead of ConsoleApp1.Foo. For my purpose I'm not concerned with seeing the class level or constructor information, just the methods available for that object.


![capture](https://user-images.githubusercontent.com/17741817/33738379-fb4039b4-db4d-11e7-8c3e-cead4f3eea51.PNG)

**Comment by EWSoftware** [comment]
The extra container topics are created by the *ApplyVSDocModel.xsl* transformation and the TOC is created by the *CreateVSToc.xsl* transformation.  You'd have to replace either or both of those with modified versions to create the TOC layout you want.  You'll need to modify the actual presentation style itself as well to remove the unwanted topic processing such as for list pages and constructors and the various links generated to them in things like the See Also sections.

It goes back a long way but you may be able to use the old Prototype presentation style as a model as it had a layout similar to what you want.  The old transforms for it (*AddPrototypeDocModel.xsl* and *CreatePrototypeTOC.xsl) are [located here](https://github.com/EWSoftware/SHFB/tree/4b1ab9445b908cc8cff2e63c77f5c55457a68298/SHFB/Source/XslTransform/ProductionTransforms).  The old Prototype presentation style is [located here](https://github.com/EWSoftware/SHFB/tree/4b1ab9445b908cc8cff2e63c77f5c55457a68298/SHFB/Source/PresentationStyles/Prototype).  Bear in mind that these were obsoleted and removed a long time ago and may not work at all with the latest release of SHFB.

**Comment by huffSamuel** [comment]
Perfect, thanks! I'll look into editing those transforms.
