### ISSUE TITLE
Content layout files popup in VS 2017

### ISSUE THREAD

**Issue by TheFellow** [EWSoftware/SHFB#551]
When opening a solution which includes an SHFB project I receive a popup indicating that the "content layout files must be associated with and opened from a Sandcastle Help File Builder project."

![image](https://user-images.githubusercontent.com/2533155/34006693-1f9e3a52-e0b4-11e7-972f-f25dff6d5316.png)

They are associated with such a project, and the project builds just fine. The popup is more of a nuisance.

**Comment by EWSoftware** [comment]
Content layout files need to know what the active project is when opened.  If you leave a file open and then close the solution, when the solution is reopened, the current project isn't always known when the content layout file is reopened.  I can remove the warning.  If the content layout file isn't the active file when the project opens, the worst that will happen is that the tab will disappear once you click on it.
