### ISSUE TITLE
File rename in solution explorer duplicates the file

### ISSUE THREAD

**Issue by TheFellow** [EWSoftware/SHFB#553]
Steps to reproduce:
1. Create a new SHFB project in VS 2017
2. Select Welcome.aml and hit F2 and rename it to Home.aml
3. Open the file, make an edit, and save it
4. Open the project folder and view the files, notice that there are 2

Furthermore, the Home.aml file that looked like it was being edited, is actually the original Welcome.aml file which still remains on disk. (Note the updated timestamp in the screenshot.)
![image](https://user-images.githubusercontent.com/2533155/34126235-c0825f02-e3ed-11e7-9a27-8d4199f3295d.png)

**Comment by EWSoftware** [comment]
This only appears to be an issue if you have the file being renamed open in an editor window which is the case with the Welcome.aml topic after creating a new project.  If it's closed first, it doesn't appear to occur that I could see in trying it out in various ways.  It's probably an issue with the MPF project system.
