### ISSUE TITLE
'Additional Reference Links' throws 'SandcastleBuilder.Utils.BuilderException: Unable to locate Reflection Index Data component'

### ISSUE THREAD

**Issue by NiklasSkoglund** [EWSoftware/SHFB#554]
Hi!

I'm trying to use the 'Additional Reference Links component in one SandCastle project (project A) to be able to link to types in one of my other SandCastle projects (project B).

When I'm building the project A, I get this exception:

error BE0029: Unexpected error while executing plug-in 'Additional Reference Links': SandcastleBuilder.Utils.BuilderException: Unable to locate Reflection Index Data component in <path to project B>\Help\Working\sandcastle.config
	Failed

If I understand it correct, the build of project A shall cause a partial build of project B, and will use output from the working folder of project B.

I dont even find a file named <path to project B>\Help\Working\sandcastle.config, so that may be the first thing to dig into.
In <path to project A> I can find this file, but in the file I dont find the configuration element for the Reflection Index Data component. I checked in the source code of the Additional Reference Links component but I may have got lost when trying to imagine what the xpath expression is looking for.
[build.log](https://github.com/EWSoftware/SHFB/files/1582058/build.log)
I've attached parts of my build log. 

Any ideas on how to troubleshoot this problem? 

Kind Regards and Merry Christmas
Niklas

**Comment by EWSoftware** [comment]
Is this perhaps an older project or did you recently upgrade to the latest release of SHFB?  If so, it's likely that the data caching component configurations are out of date.  You should be able to resolve the problem by removing them from the project, adding them back, and editing their configuration if necessary.

The last breaking change to the data caching components was in [version 2015.7.25.0](http://ewsoftware.github.io/SHFB/html/90c2bedf-fe6e-4f99-8a33-84b441701269.htm#BreakingChanges).

**Comment by NiklasSkoglund** [comment]
Yes it is. I'll try it out. Thanks!
