### ISSUE TITLE
Duplicate content type in [Content_Types].xml causing exception with NuGet package for latest release

### ISSUE THREAD

**Issue by shunter** [EWSoftware/SHFB#555]
My company has a disconnected NuGet server, and the package for the latest release throws an exception when importing the new .nupkg file into the server:

```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
```

Note that this is coming from opening the file with the .NET standard Packaging API.  Based on the stack trace, I investigated the `[Content_Types].xml` file in the package.  I'm not really familiar with this particular file, but I found that there is a duplicate entry for "rels" in this file, which causes the exception when the entries are loaded into a dictionary:

```
<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="psmdcp" ContentType="application/vnd.openxmlformats-package.core-properties+xml" />
  <Default Extension="dll" ContentType="application/octet" />
  <Default Extension="gif" ContentType="application/octet" />
  <Default Extension="xaml" ContentType="application/octet" />
  <Default Extension="css" ContentType="application/octet" />
  <Default Extension="js" ContentType="application/octet" />
  <Default Extension="xml" ContentType="application/octet" />
  <Default Extension="xsl" ContentType="application/octet" />
  <Default Extension="png" ContentType="application/octet" />
  <Default Extension="ico" ContentType="application/octet" />
  <Default Extension="aspx" ContentType="application/octet" />
  <Default Extension="php" ContentType="application/octet" />
  <Default Extension="html" ContentType="application/octet" />
  <Default Extension="Config" ContentType="application/octet" />
  <Default Extension="htm" ContentType="application/octet" />
  <Default Extension="md" ContentType="application/octet" />
  <Default Extension="rels" ContentType="application/octet" />
  <Default Extension="txt" ContentType="application/octet" />
  <Default Extension="proj" ContentType="application/octet" />
  <Default Extension="hhp" ContentType="application/octet" />
  <Default Extension="msha" ContentType="application/octet" />
  <Default Extension="tokens" ContentType="application/octet" />
  <Default Extension="bat" ContentType="application/octet" />
  <Default Extension="aml" ContentType="application/octet" />
  <Default Extension="exe" ContentType="application/octet" />
  <Default Extension="targets" ContentType="application/octet" />
  <Default Extension="nuspec" ContentType="application/octet" />
</Types>
```

I compared against the `[Content_Types].xml` from the previous release, and found that it looks very different.  The previous file used `<Override>` tags to specify the content type for specific files in the package instead.  I'm assuming this stems from a file extension clash with ".rels" files, because NuGet also uses a special file named ".rels" in its structure.

Let me know if you need any additional information.  If you want to see the actual exception, it's easy to reproduce with a one-liner that just opens the package:

```
using System.IO.Packaging;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var p = Package.Open(@"C:\Temp\EWSoftware.SHFB.2017.12.30.nupkg");
        }
    }
}
```

**Comment by EWSoftware** [comment]
NuGet.org required that anyone publishing packages upgrade to the latest release of NuGet.exe.  I was using an older version for prior releases.  That's the only thing that changed with regard to the generated NuGet package.

I can probably rename the folders in question to work around the issue with NuGet.  I had to do something similar with the Open XML content types and relationships files.  In the meantime, if you aren't building Open XML output, you can probably use WinZip or something similar to open the package and delete the Open XML presentation style folder which contains the files it's having problems with.

**Comment by EWSoftware** [comment]
I just published a new version of the NuGet package (v2017.12.30.1).  It should be available soon.

**Comment by shunter** [comment]
Updated NuGet package works.  Thanks for the quick turnaround!

**Comment by victormamah** [comment]
http://schemas.openxmlformats.org/package/2006/content-types">
