### ISSUE TITLE
VS 2017 Fails to Build project

### ISSUE THREAD

**Issue by Gerolkae** [EWSoftware/SHFB#556]
MRefBuilder : error : An error occurred while loading dependency assemblies. The error message is: Could not find a part of the path &#39;D:\Silver-Monkey 3,0\build\help\silvermonkey\Working\0\packages\EntityFramework.6.2.0\lib\net45&#39;. [D:\Silver-Monkey 3,0\build\help\silvermonkey\Working\GenerateRefInfo.proj]
Done Building Project &quot;D:\Silver-Monkey 3,0\build\help\silvermonkey\Working\GenerateRefInfo.proj&quot; (default targets) -- FAILED.

Getting this Error every time I attempt to Build the scancastle project

**Comment by EWSoftware** [comment]
It could be an issue resolving a PackageReference path.  Can you attach or send me an example project that I can use to duplicate the issue?  I'd need the project files used as a documentation source too.

**Comment by Gerolkae** [comment]
Sure
https://github.com/StarShip-Avalon-Projects/FurcadiaFramework
Yeah the december release

**Comment by EWSoftware** [comment]
The updated release that fixes this issue is now available (v2017.12.30.2).
