### ISSUE TITLE
Link to Constructor, Fields, Properties, Methods, and Events pages.

### ISSUE THREAD

**Issue by Millerni456** [EWSoftware/SHFB#56]
Hello,

I would like to create a link that points to any of the pages listed in the title.  However, my understanding is that you can only link to particular constructors, fields, properties, methods, and events (and also namespaces).

You do this by using the cref notation generated by the XML docs:

    T:Namespace.Class
    F:Namespace.Class.Field
    M:Namespace.Class.Method(params...)
and so on....

Instead, what I would like to do is link to the page that list all of the members of that member type.  For example, the properties page lists all of the different properties of a class on a single page.

Is this possible?  If so, what is the correct cref notation?

**Comment by EWSoftware** [comment]
For the group pages such as properties, methods, etc., you need to fully qualify the name and use the proper group prefix.  Typically, it will be the fully qualified name of the class prefixed with something like "Methods." or "Properties.".  Generic classes will need the generic type parameter count included in their member ID as well.  Method overloads, including those for constructors, are a little different as shown in the examples below:

```
Methods.T:XMLCommentsExamples.GenericClass`2
Properties.T:XMLCommentsExamples.GenericClass`2
Events.T:XMLCommentsExamples.SampleClass
Overload:SandcastleBuilder.Utils.FilePath.#ctor
```
If in doubt, the ID to use can be found by looking at the generated HTML for the page and looking for the ID element depending on which presentation style you're using.  For example, in the VS2013 style, the ID is stored in the "Microsoft.Help.Id" meta element.

For overloads, you can use the `cref` notation "O:SandcastleBuilder.Utils.FilePath.#ctor".  The "O:" prefix will translate to the method overload page.  For the others you'll have to use `href` notation such as:

```
<see href="html/Events.T:XMLCommentsExamples.SampleClass.htm">Sample Class Events</see>
```

**Comment by Millerni456** [comment]
Perfect! Just what I was looking for. :)

Thanks for the help.
