### ISSUE TITLE
Problems with Reflection Data Set - System.Security.AccessControl.xml

### ISSUE THREAD

**Issue by amainiii** [EWSoftware/SHFB#560]
When using Visual Studio 2017 , 15.5.2, with EWSoftware.SHFB 2017.12.30.2 and Reflection Data Set EWSoftware.SHFB.NETFramework 4.7.0, the build fails on System.SecurityAccessControl.xml. Attached Log:
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/1613137/LastBuild.log)

> SHFB: Error GID0001: Unexpected error while generating inherited documentation:
> System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: The 'p' start tag on line 121 position 271 does not match the end tag of 't'. Line 122, position 3.

Upon examination, the **System.Security.AccessControl.xml** file has incorrect xml
Attached xml (renamed as .txt)
[System.Security.AccessControl.txt](https://github.com/EWSoftware/SHFB/files/1613179/System.Security.AccessControl.txt)

Is this a problem in the Reflection Data Set, or in MRefBuilder or is this something I can fix with a configuration change?  I've tried a variety of different settings including unchecking the inherited options, but nothing seems to prevent this error.

**Comment by EWSoftware** [comment]
It's a problem with Microsoft's XML comments file.  From the build log it looks like it's probably coming from a NuGet package so you'll need to track down the location of the NuGet package and fix the bad comment there and report it if possible as a bug in their package's comments file.

**Comment by amainiii** [comment]
I did a search across the entire disk, and found two locations (below). I have corrected all the XML documents I can find, and still encountering the error.
C:\Users\{user}\.nuget\packages\system.security.accesscontrol
C:\Program Files\dotnet\sdk\NuGetFallbackFolder
You have any hints for additional locations?  Is there a place in the SHFB were it looks up the locations for these files?

Also, is it reasonable to suggest that each xml processing be wrapped with a try catch so that the entire help build does not fail for want of a single damaged xml file?  There are a lot of framework files.

**Comment by amainiii** [comment]
Thanks for the advice. Because this is large system, there were a few different solutions with different package sets, and then some didn't have the referenced items, which forced binding to the resources in C:\Program Files\dotnet\sdk\NuGetFallbackFolder.  

I was able to fix System.Security.AccessControl.xml, System.Security.Prinicpal.Windows.xml,  System.Data.SqlClient.xml and System.Collections.Immutable.xml. As there were many errors, and the tool stops at the first error, it took a few hours.

SHFB has been a great tool for us over the last 3-4 years.  I absolutely agree that xml files should be properly formatted. Are the problems with the Framework xml files a recent development, or have we just been lucky in our own development projects thus far?

**Comment by EWSoftware** [comment]
The XML comments that get installed with the SDKs etc. in the Reference Assemblies folder have been fine so far.  It's been the ones in the NuGet packages that tend to be broken.  I can't say why the quality control is worse for them.  It seems to be a recent development.
