### ISSUE TITLE
msbuid shfbproj popup debug error R6034

### ISSUE THREAD

**Issue by JaydenHan1106** [EWSoftware/SHFB#565]
I have a shfbproj and use GUI open it, it's OK. But when I use msbuild cmd line to build shfbproj, when it is Initalizing and BuildTopics, popup a debug error window. the error info is below:
![image](https://user-images.githubusercontent.com/28695394/35133464-2d53f862-fd0b-11e7-8dff-abf8474d5dc6.png)

if click ignore, it will continue and nothing effect with result.

**Comment by EWSoftware** [comment]
You need to use MSBuild 15.0.  If the standalone GUI is working, you've probably got them installed.  You just need to use the v15.0 path to run MSBuild.exe.

**Comment by JaydenHan1106** [comment]
Thanks your answer. My project need VS2015, so is there earlier version of SFHB can use MSBuild 14.0.
