### ISSUE TITLE
Cannot use PCL project that targets Profile7 as a documentation source

### ISSUE THREAD

**Issue by pcoffer** [EWSoftware/SHFB#566]
I have a portable library that targets .NETPortable Profile7.  I have a shfb project that has as its only documentation source the portable library.  I've tried setting the shfb project's Framework Version to every single available choice, and all of them result in a build failing with error BE0070.

BE0070 says that differing frameworks were detected in documentation sources.  There is only one documentation source, so that error isn't actually correct.  I assume that instead it is actually complaining about a difference between the documentation source and the shfb project framework version.  But there is no shfb project framework version that does not produce the error.

Is it not possible to use a PCL project as a documentation source?  I haven't tried all portable profiles, but I have tried Profile49 with the same result.

**Comment by EWSoftware** [comment]
Are you using a more recent version of SHFB that contains the Cross Platform framework version option?  If not, upgrade and choose it as the framework version as it should allow it.

**Comment by pcoffer** [comment]
I'm using version 2017.12.30.0 (the latest, I believe).  It does have the framework version "Cross-platform (.NET Core/.NET Standard) as an option.  But the error still occurs with that option selected.  In fact, it occurs regardless which option is selected.

Here's the build log:

<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2017.12.30.2" projectFile="c:\Users\Pat\Documents\Visual Studio 2015\Projects\ShfbPclProblem\Documentation1\Documentation1.shfbproj" started="1/21/2018 3:55:22 PM">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\&#39;
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in &#39;C:\Program Files (x86)\HTML Help Workshop\&#39;
Locating components in the following folder(s):
    c:\Users\Pat\Documents\Visual Studio 2015\Projects\ShfbPclProblem\Documentation1
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
Using framework reflection data for &#39;Cross-platform (.NET Core/.NET Standard)&#39; located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework&#39;
Using presentation style &#39;VS2013&#39; located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2013&#39;
Loading and initializing plug-ins...
Lightweight Website Style Version 2017.12.30.2
Copyright &#169; 2006-2017, Eric Woodruff, All Rights Reserved
Portions Copyright &#169; 2014, Sam Harwell, All Rights Reserved
</buildStep>
<buildStep step="ClearWorkFolder">
Clearing working folder...
</buildStep>
<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: c:\Users\Pat\Documents\Visual Studio 2015\Projects\ShfbPclProblem\MyPortableLib\MyPortableLib.csproj
    Found project &#39;c:\Users\Pat\Documents\Visual Studio 2015\Projects\ShfbPclProblem\MyPortableLib\MyPortableLib.csproj&#39;

Parsing project files
    Found assembly &#39;c:\Users\Pat\Documents\Visual Studio 2015\Projects\ShfbPclProblem\MyPortableLib\bin\Debug\MyPortableLib.dll&#39;
    Last step completed in 00:00:00.0040
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0070: Differing framework types were detected in the documentation sources (i.e. .NET, Silverlight, Portable).  Due to the different sets of assemblies used, the different frameworks cannot be mixed within the same documentation project.  See the error number topic in the help file for details.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>

**Comment by EWSoftware** [comment]
Can you attach an example or tell me how to create one that duplicates the problem?  It's hard to know exactly how to set the projects up sometimes so it's easier to get an example that exhibits the problem.

**Comment by pcoffer** [comment]
Sure.  Here goes.

[ShfbPclProblem.zip](https://github.com/EWSoftware/SHFB/files/1650619/ShfbPclProblem.zip)

**Comment by EWSoftware** [comment]
It's a bug in the way it's checking for the project platforms used.  As a workaround for the time being, you can add the assembly and XML comments file as documentation sources rather than the project.

**Comment by pcoffer** [comment]
Thanks.  That's the exact workaround I've been using for years.  The consequence of that workaround is that a specific build config assembly and XML has to be added (e.g. Release, Debug) then when building a different configuration, the wrong assembly gets documented.  It's not the end of the world, but that problem reared its ugly head for me today and thought I would report it this time, in case this wasn't the intended functionality.

Thanks for your time, and for a very useful product for me.

**Comment by EWSoftware** [comment]
It'll be fixed in the next release.  No planned date on that yet though.
