### ISSUE TITLE
Abstract classes with no members don't show in help

### ISSUE THREAD

**Issue by Caleb-D** [EWSoftware/SHFB#567]
If you disable the option to auto-document default constructors and you have a public class with no members, it will be excluded from the help and any crefs to it will be broken.

Use case: these classes inherit from a generic base class and specify the type to make it non-generic.  Then there is a specific summary on the inherited class that should show in the help.

**Comment by EWSoftware** [comment]
A public class with no explicit constructor still has a default public constructor generated by the compiler.  That's what the auto-document options are handling.  All it does in turning them off is not include the summary for those default constructors which causes "missing summary" warnings if that option is enabled.

I can't reproduce this behavior.  Can you attach an example that does?

**Comment by Caleb-D** [comment]
Sorry, I forgot to mention that the class is a public abstract class that inherits from another public abstract generic class.  I've attached a sample project that will reproduce this.
[Sandcastle-missing topic.zip](https://github.com/EWSoftware/SHFB/files/1660515/Sandcastle-missing.topic.zip)

**Comment by EWSoftware** [comment]
This issue is caused by the Documented Entities Only Plug-In.  It's not properly handling the case where a type is documented but only contains an auto-documented default constructor.  It's fixed for the next release.
