### ISSUE TITLE
<exclude> tag on one method excludes all overloads

### ISSUE THREAD

**Issue by Caleb-D** [EWSoftware/SHFB#568]
If you put the `<exclude/>` tag on a method, all overloads for that method will be excluded from the help.  Expected behavior is to only exclude the overload that has the `<exclude/>` tag.

**Comment by EWSoftware** [comment]
The [exclude tags](http://ewsoftware.github.io/XMLCommentsGuide/html/a8ade450-e201-401a-923d-1a1169ef7828.htm) are passed through as API filter entries and thus follow its behavior which is to remove all overloads.  You can use a `<tocexclude />` element and the [Table of Contents Exclusion](http://ewsoftware.github.io/SHFB/html/d0e91b66-135e-446b-9239-c02fcafabd09.htm) plug-in.  That will remove the members from the TOC.  They'll still appear on the member list pages though.  The [XPath Reflection File Filter](http://ewsoftware.github.io/SHFB/html/cd68ef02-3493-4af6-96de-1957b0aaf858.htm) plug-in is another option if you do want to physically remove all traces of the individual overload members.

**Comment by Caleb-D** [comment]
Hmm, we want to exclude just one of the overloads completely from the help, so tocexclude won't help.  Several programmers on our team have given us feedback that it isn't expected behavior to exclude all overloads when you put the exclude tag on just one of them...

Is there a way to change the default behavior?

**Comment by EWSoftware** [comment]
No, the API filter has always worked that way.  Changing it now would be a significant departure from how its always worked.  This comes up every so often but not often enough to make it worth supporting.  The `<exclude />` tag was deprecated quite a while ago in favor of the API filter.  As noted, the XPath Reflection File Filter plug-in can be used to remove the unwanted members.

**Comment by Caleb-D** [comment]
It appears that the Xpath plugin only works on a project basis.  Our team needs something that can be placed in source code.

I suppose we will need to custom-bake something.

**Comment by EWSoftware** [comment]
It'll probably be a SHFB plug-in if you want it to run in the help file build.  You could probably take the XPath Filter plug-in as a starting point and rather than manually adding the expressions in a configuration form, build them off of XML comments members that have an `<exclude/>` tag at build time.  You'd effectively want to remove any `api` and `element` elements with a member ID that matches the XML comments member ID.
