### ISSUE TITLE
.NET Framework 4.7.1 and project build

### ISSUE THREAD

**Issue by jhamrsky** [EWSoftware/SHFB#573]
Having several projects targeting new .NET 4.7.1 and SandCastle projects set for them, it is not possible to build documentation for them. Seems that my problem is that I can't even select proper framework in Sandcastle builder (I am using GUI, latest stable v2017.12.30.2, same for Win7/Win10).

I am not sure if that is just a missing feature, bug or some issue on my side. As a workaround, I copied, renamed and modified file `Data\.NETFramework\.NETFramework_4.7.reflection` which seems to be working now, but looks like hack.

Can we get option in SandCastle for that framework target if it isn't completely my wrongdoing?

**Comment by EWSoftware** [comment]
I need to generate the reflection data set file.  I forgot and I guess nobody's tried to use it yet.  Your workaround will be fine for the time being.  You should be able to choose the Cross Platform framework option too as it uses the latest release that it can find in that case.

**Comment by jhamrsky** [comment]
Thanks for the tip, I can live with my hack for the moment. I am leaving closing of the issue on your preference (immediately or when you add reflection data).

**Comment by TheFellow** [comment]
@jhamrsky Can you elaborate on where exactly that file was copied from/to and what edits you made? I have the same issue in my 4.7.1 solution.

**Comment by jhamrsky** [comment]
@TheFellow , what I've done is that I copied `<installation_folder>\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework\.NETFramework_4.7.reflection` to `<installation_folder>\EWSoftware\Sandcastle Help File Builder\Data\.NETFramework\.NETFramework_4.7.1.reflection`. Then I replaced framework target version in the new file to `4.7.1` version (should be on three places).

This solution works well so far. Hope that helps you.

**Comment by EWSoftware** [comment]
The reflection data set has been updated for the next release.
