### ISSUE TITLE
Exception filter causes lockup when exception thrown from instance method

### ISSUE THREAD

**Issue by rickmas** [EWSoftware/SHFB#576]
TinyCLR 0.8.0
VS2017
FEZ Spider (EMX)

In the following contrived example, when the **catch (...) when (...)** expression evaluates to true the system locks up and control never falls into the catch block.  I'm forced to pull power from my board and erase/reload firmware every time.

```c#
using System;

namespace MaschMaker
{
    public class TestANE
    {
        public void ThrowANE() { throw new ArgumentNullException(paramName: "ANE", message: "some message"); }
    }

    class Program
    {
        static void Main()
        {
            try
            {
                new TestANE().ThrowANE();
            }
            catch (ArgumentNullException e) when ("ANE" == e.ParamName)
            { }
        }
    }
}
```

Removing the **when ()** expression makes it work just fine

```c#
            catch (ArgumentNullException e) //when ("ANE" == e.ParamName)
```
**OR**

keeping the **when ()** expression but changing ThrowANE() to a static method also works, probably because Main() is static.

```c#
using System;

namespace MaschMaker
{
    public class TestANE
    {
        public static void ThrowANE() { throw new ArgumentNullException(paramName: "ANE", message: "some message"); }
    }

    class Program
    {
        static void Main()
        {
            try
            {
                //new TestANE().ThrowANE();
                TestANE.ThrowANE();
            }
            catch (ArgumentNullException e) when ("ANE" == e.ParamName)
            { }
        }
    }
}
```
**OR** 

keeping the **when ()** expression but moving ThrowANE() to be a local method works.  This is probably the same case as using a static method but was another test I did.

```c#
using System;

namespace MaschMaker
{
    class Program
    {

        static void Main()
        {
            void ThrowANE() { throw new ArgumentNullException(paramName: "ANE", message: "some message"); }

            try
            {
                //new TestANE().ThrowANE();
                //TestANE.ThrowANE();
                ThrowANE();
            }
            catch (ArgumentNullException e) when ("ANE" == e.ParamName)
            { }
        }
    }
}
```

I obviously have a workaround but would like to use the exception filters if possible.

**Comment by EWSoftware** [comment]
I'm not sure how this relates to SHFB.  Did you post this in the right project?

**Comment by rickmas** [comment]
No, I didn't.  Thanks for pointing that out.

**Comment by StevenBonePgh** [comment]
@rickmas - excellently written bug report for whomever the correct project was, however. I wish more were of this caliber!

**Comment by rickmas** [comment]
@StevenBonePgh - Thanks!  LOL, I'll be more careful next time...
