### ISSUE TITLE
SHFB: Unable to get executing project

### ISSUE THREAD

**Issue by tagru** [EWSoftware/SHFB#578]
Hello,

I am getting the following warning on our Buildserver (TFS2015):

`SHFB: Unable to get executing project: [A]Microsoft.Build.Execution.ProjectInstance cannot be cast to [B]Microsoft.Build.Execution.ProjectInstance. Type A originates from 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.dll'. Type B originates from 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build\v4.0_14.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.dll'..  The specified project will be loaded but command line property overrides will be ignored.`

I have checked, MSBuild2015 is installed. Any idea why it is using version 4.0.0.0 instead of 14.0.0.0?

Thanks in advance and regards,
tagru

**Comment by EWSoftware** [comment]
Sorry, I've no experience with build servers so I can't say why it isn't using the right version of MSBuild.  Are you using the latest release of SHFB?

**Comment by tagru** [comment]
Yes, I installed v2017.12.30.2 today. Unfortunately, I don't know if the warning was also created with previous versions of SHFB.

**Comment by EWSoftware** [comment]
Open the SHFB project in a text editor and make sure the `ToolsVersion` attribute on the `Project` element is set to at least "12.0".  I'm not sure if that would make a difference on the build server but it's worth trying.

**Comment by EWSoftware** [comment]
I did find this which indicates you can tell the build server what version to use: https://social.msdn.microsoft.com/Forums/vstudio/en-US/deabf486-b3dc-4819-a845-ac575bf3f84b/tfs-build-using-wrong-visual-studio-version?forum=tfsbuild
