### ISSUE TITLE
SHFB build error BE0043 unexpected error detected in the last build step.

### ISSUE THREAD

**Issue by rahulkushwaha12** [EWSoftware/SHFB#579]
I am getting this error in my visual studio 2017 while running SHFB documentation project for my DOT NET CORE CONSOLE Application.
PFA build log error file image for more details.
![log](https://user-images.githubusercontent.com/29196710/37023344-9770414c-214b-11e8-9095-ca26755f5300.PNG)

In the above log AEPLCore.logging in the local nuget package configured on my local server.

**Comment by EWSoftware** [comment]
Is AEPLCore.Logging listed in the build log as one of the found references?  If not, you can either add it to the list of references in the project manually.  If there is perhaps a difference in versions between two assemblies that use it, you can use the Assembly Binding Redirection plug-in to point them to the common version or ignore it completely.
