### ISSUE TITLE
MRefBuilder MSBuild task: System.NullReferenceException: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by eosimosu** [EWSoftware/SHFB#580]
A single dll within our binaries is causing the following problem. Is there a way to ignore the null exception somehow? 
I'm using the latest version of SFHB  (v2017.12.30.2).

`GenerateRefInfo:
  MRefBuilder (v2017.12.30.2)
  Copyright ¸ 2006-2017, Microsoft Corporation, All Rights Reserved.
  Portions Copyright ¸ 2006-2016, Eric Woodruff, All Rights Reserved.
  No source code context base path specified.  Source context information is unavailable.
  Loaded 2 assemblies for reflection and 1 dependency assemblies.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.NullReferenceException: Object reference not set to an instance of an object.
`

**Comment by eosimosu** [comment]
I removed a dll in the documentation sources, and it successfully built.. my guess is that removed dll has some references not poointing to an instant.

Is there a way to ignore or get around the blockage as I don't have the capability to ask the author to refrector their code?

**Comment by EWSoftware** [comment]
Is the assembly being documented obfuscated.  I know that can cause problems on occasion.  If not, can you attach an example here or e-mail one to me so that I can try to duplicate the issue?

**Comment by eosimosu** [comment]
I don't know if the assembly is obfuscated but I can find out. 

Actually, the same assemblies built with VS2013 works fine with SFHB. We recently started building the binaries with VS2017 and started encountering this problem.

**Comment by eosimosu** [comment]
The assembly is not obfuscated.

**Comment by eosimosu** [comment]
[#550](https://github.com/EWSoftware/SHFB/issues/550) seem like exactly the same issue I'm having. Were your changes merged into the v2017.12.30.2 release ?

**Comment by EWSoftware** [comment]
Those changes were in the 2017.12.30.0 release.  As noted, that issue was related to obfuscated code in the assemblies.  If you can supply me with an example either attached here or e-mailed to me, I'll be able to diagnose the issue.

**Comment by eosimosu** [comment]
I dug into the source code of `MRefBuilder `and was able to track the null reference error. I added some checks that fixed the issue above. Could you have a look at #583 and hopefully merge it into the next release ?

**Comment by EWSoftware** [comment]
Thanks, I will.  I've been busy lately and haven't had a chance to work on anything.
