### ISSUE TITLE
Enhancement: Add Android .axml format to supported code language

### ISSUE THREAD

**Issue by dkemlage** [EWSoftware/SHFB#584]
With Microsoft acquiring Xamarin, we would like to see Xamarin.Android code examples inside of the Library Reference API documentation pages. Creating the Xamarin.Android UI portions of sample code can be done by using the Android format **.axml**. As of SandCastle version 2017.12.30.2 it currently does not support the .axml 'language' format. As a result there is no code 'AXML' tab generated is that language and the xml content of the .axml file is not colorized.

The following is a sample fragment that would be part of a .DLL's .triple slash generated .XML format:
```
<example>
<para>Android</para>
<para>
Example Name: Test Android Sample
</para>
<para>
This sample demonstrates.......
</para>
<para>
<img border="0" alt="Code example screen shot." src="../media/Test_Sample_Android.jpg"/>
</para>
<code language="CSHARP" source="C:\CodeExamples\Test_Sample_Android_Android.cs"/>
<code language="AXML" source="C:\CodeExamples\Test_Sample_Android_Android.axml"/>
</example>
```

Resulting in a documentation page that looks like:
 
![image](https://user-images.githubusercontent.com/5495810/37538744-d30302ec-290e-11e8-9e2c-ad9b279c821b.png)

**Comment by EWSoftware** [comment]
This is easy enough.  It looks like XAML so adding in an alias for it in the colorizer rules and a title string in the content files and case to map the ID to the content ID in the transformations should take care of it.
