### ISSUE TITLE
BuildAssembler : warning : ResolveReferenceLinksComponent: Unknown reference link target [Web reference]

### ISSUE THREAD

**Issue by KUTlime** [EWSoftware/SHFB#585]
I have some annoying problem with SHFB in one of my project.

I link some web references which are using some Visual Studio generates an access classes. These classes are excluded from SHFB by API filter because they produce +500 warnings (not well documented code :-) )
One of my classes which servers like a routing table for clients, produces several warning, because it uses there references, see below.
![2018-03-21_070729](https://user-images.githubusercontent.com/8374320/37696461-ef556e82-2cd6-11e8-8675-12eacd3ce62b.png)
![2018-03-21_070741](https://user-images.githubusercontent.com/8374320/37696464-f32c9ea4-2cd6-11e8-932d-ee136b1b58e5.png)

- I have tried to elaborate with Additional Reference Links plug-in, no luck. I don't have an assembly to link.
- I have tried to elaborate with Assembly Binding Redirection plug-in, no luck.
- I have tried to inject missing links directly into assembly's XML file, so far manually with manually triggered build of the SHFB project. No luck.

Any suggestion?

**Comment by KUTlime** [comment]
I was able to leverage this warnings by adding two dummy projects into my solution. The first project is an empty project with classes and namespaces according missing links from warnings. The second dummy project is the SHFB project which builds the first project. The second project is linked to the main documentation project. The warnings are gone.

The effort and resources spend on this is quite overkill. I think there should be a better way how to override missing link, e.g. for SomeNamespace.SomeClass, the link is "" or skip warning with this link settings.

**Comment by EWSoftware** [comment]
Merged with #899
