### ISSUE TITLE
Inheritdoc not processing well

### ISSUE THREAD

**Issue by mikasoukhov** [EWSoftware/SHFB#586]
While build get the following

Will put my details. Now SHFB still do not process inheritdoc well. In output I get the following

SHFB: Warning GID0004: No comments found for member &#39;M:StockSharp.Alerts.AlertRuleField.GetHashCode&#39;

BuildAssembler : warning : ShowMissingComponent: [M:StockSharp.Alerts.AlertRuleField.GetHashCode] Missing

documentation
for the following xml
```
<member name="M:StockSharp.Alerts.AlertRuleField.GetHashCode">
  <inheritdoc />
</member>
```

**Comment by EWSoftware** [comment]
For some reason, it's not finding any base members from which to inherit documentation.  Can you supply an example that demonstrates the problem?

**Comment by mikasoukhov** [comment]
https://yadi.sk/d/g5V3Jo-J3TjjoE

Could you also help to setup external components? Millions rows with warning are messing any tracing logs. How I can avoid it? I know you have some plugin but it will be excellent if you can provide any example how to use it.

**Comment by EWSoftware** [comment]
If you're talking about unresolved reference link warnings, use the [Additional Reference Links Plug-In](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm) which can suppress them.

**Comment by mikasoukhov** [comment]
Exactly. Unfortunately I cannot make it workable. Documentation is very rare for the component.

**Comment by EWSoftware** [comment]
It's not a matter of whether or not the reference assemblies have documentation.  It's just about generating reflection information and setting the link type to None in the plug-in so it stops the unresolved reference link warnings for them.

**Comment by mikasoukhov** [comment]
Unfortunately the doc coverage is really weak. So I've just get the whole app crash. We be very appreciate if you can provide more detailed instruction.

**Comment by mikasoukhov** [comment]
SHFB: Error BE0029: Unexpected error while executing plug-in 'Additional Reference Links': SandcastleBuilder.Utils.BuilderException: Fatal error, unable to compile project 'C:\SHBF_Issue586\StockSharp (GitHub)\Documentation\en\ReferenceLinks.shfbproj': System.NullReferenceException: Object reference not set to an instance of an object.
   at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.BuildProject(SandcastleProject project, String workingPath)
   at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.BuildProject(SandcastleProject project, String workingPath)
   at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.GenerateNamespaceSummaries()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

Fatal error, unable to compile project 'C:\SHBF_Issue586\StockSharp (GitHub)\Documentation\en\ReferenceLinks.shfbproj': System.NullReferenceException: Object reference not set to an instance of an object.
   at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.BuildProject(SandcastleProject project, String workingPath)
   at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.BuildProject(SandcastleProject project, String workingPath)
   at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)

**Comment by mikasoukhov** [comment]
My point is described in prev message.

Plugin is very weak documentation coverage. So I think no one use it and sure it is non workable. Please improve documentation for plugins. It will bring more beta-testers.

**Comment by EWSoftware** [comment]
There's not much more to say about using the plug-in.  It's working in all cases that I'm aware of.  If it isn't working for you, submit an example so that I can see how you're using it such that it fails.

**Comment by mikasoukhov** [comment]
https://yadi.sk/d/JMT41WuB3TpwL5

**Comment by EWSoftware** [comment]
The problem appears to be related to the MSBuild `OutDir` property not being defined for some reason.  I only ran into it when using the standalone GUI.  It appears to always be defined if using the Visual Studio package.  As a workaround, add the `OutDir` property to your SHFB projects manually in the first property group

``` XML
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="14.0">
  <PropertyGroup>
    <OutDir Condition=" '$(OutDir)' == '' ">
```

That should work around the issue for the time being.  Once done, the reference links project will build.  However, it's missing a required RssToolkit reference assembly.  Add that or use the binding redirection plug-in to ignore it.

**Comment by mikasoukhov** [comment]
> SHFB: Error BE0029: Unexpected error while executing plug-in 'Additional Reference Links': SandcastleBuilder.Utils.BuilderException: Unable to build additional target project: C:\SHBF_Issue586\StockSharp (GitHub)\Documentation\en\ReferenceLinks.shfbproj
>    at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.Execute(ExecutionContext context)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.GenerateNamespaceSummaries()
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
> 
> Unable to build additional target project: C:\SHBF_Issue586\StockSharp (GitHub)\Documentation\en\ReferenceLinks.shfbproj
>    at SandcastleBuilder.PlugIns.AdditionalReferenceLinksPlugIn.Execute(ExecutionContext context)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)

**Comment by EWSoftware** [comment]
You're probably missing another reference assembly.  Build the reference links project by itself to see what's missing.  As I mentioned above, it's missing a reference to RssToolkit.

**Comment by mikasoukhov** [comment]
I will wait for official patch. Seems I have some problems to make quick and dirty workaround

**Comment by mikasoukhov** [comment]
Would like to inform that the issue still exists even in the latest release.

**Comment by EWSoftware** [comment]
If you can supply an example, I'll take a look at it.

**Comment by mikasoukhov** [comment]
The same example. Was uploaded more than month ago

**Comment by EWSoftware** [comment]
This one?  https://yadi.sk/d/JMT41WuB3TpwL5

If so, it's not there anymore.

**Comment by mikasoukhov** [comment]
Yeah, seems it was expired. So I have only that one but you need to configure Refs proj https://yadi.sk/d/g5V3Jo-J3TjjoE

**Comment by mikasoukhov** [comment]
Did you fix eventually the bug with the plugin?

**Comment by EWSoftware** [comment]
Your example project was missing the import for the SandcastleHelpFileBuilder.targets file.  Once that was added, it built as expected using the latest release.

**Comment by mikasoukhov** [comment]
All files were created by the UI shell. It wasn't changed anything manually. So I think the issue is UI tries to create invalid files.

**Comment by mikasoukhov** [comment]
Did you fix eventually the bug with the plugin?

**Comment by EWSoftware** [comment]
As noted above, I found no issues except the missing import in your example.

**Comment by mikasoukhov** [comment]
Files were created by the software. So maybe the issue that software creates invalid files, no?

**Comment by EWSoftware** [comment]
It creates projects just fine as far as I can tell.

**Comment by mikasoukhov** [comment]
The app do not create valid files. Only after manual modification as you told.

**Comment by EWSoftware** [comment]
- Create a new project in Visual Studio or the standalone GUI.
- Add the documentation source.
- Set the other properties as needed (framework version etc.).
- Build it and it works.

How you got a project without a targets element, I don't know.  I suggest you recreate the project or add the element back as I did.

**Comment by mikasoukhov** [comment]
I think you missed the major conversation part. I'm talking about the plugin.

**Comment by EWSoftware** [comment]
No, you sent me an example and the only thing wrong was a missing targets element.  After adding that back in, it worked as expected.  That had nothing to do with the plug-in.  The plug-in is working as expected too.
