### ISSUE TITLE
Missing $(SolutionDir) when running msbuild *.sln

### ISSUE THREAD

**Issue by TripleEmcoder** [EWSoftware/SHFB#587]
I am building a Sandcastle (2017.12.30) project included with several C# projects in a solution from the command-line using msbuild 15.5.

My projects include additional targets files from `$(SolutionDir)`. Unfortunately during the `ValidateDocumentationSources` step my projects fail to load because the variable is not set and the targets files are not found. I went through the discussion in #238 which I thought was related to the same issue. In my case however, I do build using a solution file, so everything should be fine.

Having run out of ideas of my own and from the web I did some debugging. The problem seems to originate from the fact that `ProjectCollection.GlobalProjectCollection` is empty in my case, which causes `SandcastleBuilder.Utils.MSBuild.MSBuildProject` to load the source projects separately, outside of the solution context. Just to be clear, those source projects are scheduled to build before Sandcastle, using project dependencies configured in Visual Studio, an do run successfully as expected earlier in the process.

Any idea why that happens? Same thing occurs in `SandcastleBuilder.Utils.MSBuild.BuildHelp.Execute` for the Sandcastle project, only there the fallback is to `GetCurrentProjectInstance` which uses reflection and successfully retrieves the project from MSBuild, along with all the solution-related properties.

**Comment by EWSoftware** [comment]
Can you supply an example that demonstrates the problem?  Stuff like this is usually context dependent and I can't always duplicate the same scenario that causes it.

**Comment by TripleEmcoder** [comment]
As soon as I posted my issue I realised that you have answered this already in #238:

> When building under MSBuild, it doesn't load things the same way and the project is not found in the global projects collection so the SHFB build engine has to load it for itself. 

However when I apply the solution:

> What you need to do is use the solution as the documentation source rather than the project. In that case, the SHFB build engine knows that the project it loads is part of the given solution that it searched for projects and will manually set the solution related properties accordingly and it will find the output in the expected location.

I start also seeing the same error in Visual Studio, whereas when referencing csprojs I only see failures with msbuild.

Here's the problematic line of my csprojs:

```xml
<Import Project="$(SolutionDir)\Common.props" />
```

And here's the build output:
```
X:\Sources>msbuild Help.sln
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 22.03.2018 00:58:04.
Project "X:\Sources\Help.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "X:\Sources\Help.sln" (1) is building "X:\Sources\Area\Area.Help\Area.Help.shfbproj" (2) on node 1 (default targets).
CoreBuildHelp:
  Building X:\Sources\Area\Area.Help\Area.Help.shfbproj
  Initializing
  ClearWorkFolder
  ValidatingDocumentationSources
SHFB : error BE0065: BUILD FAILED: The imported project "X:\Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  X:\Sources\Area\Area.csproj [X:\Sources\Area\Area.Help\Area.Help.shfbproj]
  Failed
  Build details can be found in X:\Sources\Area\Area.Help\Area.Help\Help\LastBuild.log
Done Building Project "X:\Sources\Area\Area.Help\Area.Help.shfbproj" (default targets) -- FAILED.
```

In the end I think I am going to settle for just referencing DLLs from bin\$(Configuration) and manual build dependencies so that the files are available when building help files.
