### ISSUE TITLE
build warnings for methods taking or returning system collection types

### ISSUE THREAD

**Issue by adennie** [EWSoftware/SHFB#588]
I'm getting build errors for methods with parameters that are of a collection type from the System.Collections.Generic namespace  (e.g. Dictionary or HashSet), or which return values of those types.  Other methods which take or return non-collection types seem to work fine.

For example:

```
            /// <summary>
            /// Enable detection of multiple features.  The specified features will be added to those already enabled.
            /// </summary>
            /// <param name="features">The features to enable</param>
            virtual void enable(HashSet<Feature> features);
```

```
            /// <summary>
            /// Get the features for which detection is enabled
            /// </summary>
            /// <returns> The enabled features
            property HashSet<Feature>^ EnabledFeatures {
                HashSet<Feature>^ get();
            }
```

```
BuildAssembler : warning : ShowMissingComponent: [M:Affdex.Vision.Detector.enable(System.Collections.Generic.HashSet{Affdex.Vision.Feature})] Missing <summary> documentation [C:\Users\Andy\Dev\projects\affectiva\build\affdex-cpp-sdk\docs\affectiva-vision-sdk-net\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Affdex.Vision.Detector.enable(System.Collections.Generic.HashSet{Affdex.Vision.Feature})] Missing <param name="features"/> documentation [C:\Users\Andy\Dev\projects\affectiva\build\affdex-cpp-sdk\docs\affectiva-vision-sdk-net\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [P:Affdex.Vision.Detector.EnabledFeatures] Missing <summary> documentation [C:\Users\Andy\Dev\projects\affectiva\build\affdex-cpp-sdk\docs\affectiva-vision-sdk-net\Working\BuildTopics.proj]
```

Any ideas?

**Comment by EWSoftware** [comment]
Use the [Member ID Fix-Up Plug-In](http://ewsoftware.github.io/SHFB/html/17d977a6-e3dc-4ef4-9bbf-718ef4823854.htm) and use the C++ Fixes button to add the common set that fix up issues with the C++ member IDs.

**Comment by adennie** [comment]
Thanks, I tried that but it didn't help (although it seemed promising).  Might it be necessary to tweak the match expression or the "replace with" value for the
`(member name=".*?System\.Collections\.Generic.*?)(\^)`
entry?  Any tips on narrowing this down is much appreciated.

**Comment by EWSoftware** [comment]
There may be others.  The button only adds the one's I'm aware of.  The only way to fix ones it doesn't handle is to take the XML comments file for your assembly and find the member ID it's complaining about in the build log warning and see how the IDs differ between the two.  Once you've got that, you need to create an entry to convert the bad ID from the XML comments file to the form used by the tools in the build log warning.  Typically its a superflous character like '^' or generic argument count such as '\`1'.  For some like the `interior_ptr` entry, it needs a different value altogether.
