### ISSUE TITLE
.NET Standard project targeting multiple frameworks: params and return value documentaiton missing

### ISSUE THREAD

**Issue by JJoe2** [EWSoftware/SHFB#590]
Windows 10
 Visual Studio Professional 2017 Version 15.6.4
 SHFB 2017.12.30.2

I've created a .NET Standard Class Library that:
- Targets frameworks netstandard2.0 and net35:
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net35</TargetFrameworks>
  </PropertyGroup>

- references the System.Configuration.ConfigurationManager 4.4.1 NuGet package for netstandard 2.0:

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Configuration.ConfigurationManager">
      <Version>4.4.1</Version>
    </PackageReference>
  </ItemGroup>

- references System.Configuration assembly for net35:

  <ItemGroup Condition="'$(TargetFramework)' == 'net35'">
    <Reference Include="System.Configuration" />
  </ItemGroup>

- XML documentation files are generated for both target frameworks.

I have an SHFB project that references this project as a Documentation Source.

- The documentation is generated without errors.
- The summary for each method is included in the output chm file (which proves that the xml files are generated)
- However there is no documentation for the method parameters or return value in the output chm file

Example method:

        /// <summary>
        /// Gets the appSetting value for the specified key.
        /// </summary>
        /// <param name="key">The key.</param>
        /// <returns>The value.</returns>
        public string GetSetting(string key)
        {
           ...
        }

Example output:

Class1.GetSetting Method  

Gets the appSetting value for the specified key. 

Namespace:  MultiTargeting
Assembly:  MultiTargeting (in MultiTargeting.dll) Version: 1.0.0
See Also
Reference
Class1 Class
MultiTargeting Namespace

**Comment by EWSoftware** [comment]
Can you attach an example that demonstrates the issue?

**Comment by JJoe2** [comment]
Example attached
[MultiTargeting.zip](https://github.com/EWSoftware/SHFB/files/1865332/MultiTargeting.zip)

**Comment by JJoe2** [comment]
I have tried building the same sample project on a Windows 7 machine.

On Windows 7 the build fails with the following error:

MRefBuilder : error : Unresolved assembly reference: netstandard (netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) required by MultiTargeting [C:\TestProjects\MultiTargeting\MultiTargeting\Multitargeting.Documentation\Help\Working\GenerateRefInfo.proj]

...

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

I then added "netstandard" to Plug-Ins > Assembly Binding Redirection > Ignore if unresolved.

After doing this, the document build completes with a warning message, and I get the same output as I got on Windows 10 (i.e. parameters and return values missing):

2>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : MRefBuilder : warning : Ignoring unresolved assembly reference: netstandard (netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) required by MultiTargeting [C:\TestProjects\MultiTargeting\MultiTargeting\Multitargeting.Documentation\Help\Working\GenerateRefInfo.proj]

So it seems the behaviour is OS-dependent, or dependent on sonething that differs between the two development machines.

**Comment by JJoe2** [comment]
I've attached an updated sample project.  This includes a class with extension methods that demonstrates additional, probably related, problems that I was attempting to reproduce when I got the reported error.  For the class with extension methods, I get additional errors:

- Warnings about missing summary, returns and param documentation
- Output document has "Missing summary documentation" warnings.

To date I've only attempted to build this on Windows 7.

[MultiTargeting2.zip](https://github.com/EWSoftware/SHFB/files/1870618/MultiTargeting2.zip)

**Comment by EWSoftware** [comment]
Parameters and return value info is tied to the Syntax section of the topic.  Since you don't include any syntax filters in the SHFB project, that section is removed in its entirety.  If you add one syntax filter such as C# or VB.NET, the Syntax section will be rendered and the parameter and return value info will be included.

**Comment by JJoe2** [comment]
OK thanks for taking the time to analyse this.  I see now that the latest version of SHFB does not add any syntax filters by default when creating a new SHFB project - this is a change from earlier versions, which IIRC had filters for C#, F# and VB.NET by default.  It might be nice to have a warning message if no syntax filters are active.

**Comment by EWSoftware** [comment]
It should have the standard set as the default in new projects.  I'll see why it doesn't and fix it.
