### ISSUE TITLE
[Question] Inheritdoc when implementing generic interfaces

### ISSUE THREAD

**Issue by Crypt32** [EWSoftware/SHFB#592]
Consider the following scenario: My class implements IDictionary interface

```C#
public class MyDictionary : IDictionary<String, Object> {
    /// <inheritdoc cref="IEnumerable{T}.GetEnumerator"/>
    public IEnumerator<KeyValuePair<String, Object>> GetEnumerator() {
        <...>
    }
    /// <inheritdoc cref="IEnumerable.GetEnumerator"/>
    IEnumerator IEnumerable.GetEnumerator() {
        <...>
    }
    /// <inheritdoc cref="ICollection{T}.Add(T)"/>>
    public void Add(KeyValuePair<String, Object> item) {
           <...>
    }
    /// <inheritdoc cref="ICollection{T}.Clear"/>>
    public void Clear() {
       <...>
    }
<...>
```
However, due to some reasons help file builder can't resolve them. Here is build output (relevant part):
```
Generating inherited documentation...
[C:\Program Files (x86)\MSBuild\14.0\bin\amd64\MSBuild.exe - GenerateInheritedDocs.proj]
Sandcastle Help File Builder and Tools, version 2017.12.30.2
Copyright c 2006-2017, Eric Woodruff, All Rights Reserved
E-Mail: Eric@EWoodruff.us

Reflection information will be retrieved from 'reflection.xml'
Inherited documentation will be written to '_InheritedDocs_.xml'
Indexing C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\*.xml
Indexing <LocalPath>\AssemblyName.XML
Indexed 1592 members in 109 file(s).  1 file(s) to scan for <inheritdoc /> tags.
Merging inherited documentation...

SHFB: Warning GID0002: No comments found for cref 'M:System.Collections.Generic.IEnumerable`1.GetEnumerator' on member 'M:MyNamespace.MyDictionary.GetEnumerator'
SHFB: Warning GID0002: No comments found for cref 'M:System.Collections.IEnumerable.GetEnumerator' on member 'M:MyNamespace.MyDictionary.System#Collections#IEnumerable#GetEnumerator'
SHFB: Warning GID0002: No comments found for cref 'M:System.Collections.Generic.ICollection`1.Add(`0)' on member 'M:MyNamespace.MyDictionary.Add(System.Collections.Generic.KeyValuePair{System.String,System.Object})'
SHFB: Warning GID0002: No comments found for cref 'M:System.Collections.Generic.ICollection`1.Clear' on member 'M:MyNamespace.MyDictionary.Clear'
<...>
```
Another case is when I inherit from `AsnEncodedData` class and override `Format(Boolean)` virtual method (http://msdn2.microsoft.com/en-us/library/ffda55sx). I'm using the following line on top of this method: `<inheritdoc cref="AsnEncodedData.Format(Boolean)"/>`

On the other hand, I have classes that implement `IDisposable` and when putting `<inheritdoc cref="IDisposable.Dispose"/>` on top of `Dispose` method, help builder successfully writes inherited help from .NET XML files.

What I'm doing wrong? I can confirm that mscorlib.xml exists in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\` folder and contains all required XML files.

**Comment by Crypt32** [comment]
>  That said, as long as the ID is valid, it should still find and retrieve the comments.

Not in my case. I tried different approaches, but neither worked for me. This is why I raised this question. I thought, it should work even with `<inheritdoc />` tag in XML comments, but no luck so far. Help file writes "Missing blablabla" for every implemented (from interface) member.

> You reference the v4.0 framework folder

yes, my assembly is compiled against .NET 4.0 and appropriate .NET version is specified in SHFB project. I'm using .dll and .xml files as SHFB reference.

**Comment by EWSoftware** [comment]
It could be something specific to the project or the way you're doing something that I'm not replicating.  Can you supply a small example that doesn't work for you?

**Comment by Crypt32** [comment]
Yes, sure. I created minimal project that includes only one class with `inheritdoc` and sample SHFB project file.
[SampleProject.zip](https://github.com/EWSoftware/SHFB/files/1904078/SampleProject.zip)
Project is created against .NET 4.0 (as in my actual case).

Forgot to mention, I'm using the latest SHFB release.

**Comment by EWSoftware** [comment]
I wasn't able to duplicate the issue with the sample project.  One thing that is possible is that if you don't have the XML comments files available in the reference assemblies folder, it wouldn't be able to index them.  Since you're using .NET 4.0, it would look in *C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0* for the XML comments files for the framework.  Other than that, I can't think of any other reasons it wouldn't be able to inherit the documentation.

**Comment by Crypt32** [comment]
> One thing that is possible is that if you don't have the XML comments files available in the reference assemblies folder

I don't think so:

```
PS C:\> dir 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\*.xml'


    Directory: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       20.04.2017     21:11            155 Accessibility.xml
-a----       20.04.2017     21:11            158 CustomMarshalers.xml
-a----       20.04.2017     21:11            153 ISymWrapper.xml
-a----       20.04.2017     21:11            173 Microsoft.Build.Conversion.v4.0.xml
-a----       20.04.2017     21:11            164 Microsoft.Build.Engine.xml
-a----       20.04.2017     21:11            167 Microsoft.Build.Framework.xml
-a----       20.04.2017     21:11            168 Microsoft.Build.Tasks.v4.0.xml
-a----       20.04.2017     21:11            172 Microsoft.Build.Utilities.v4.0.xml
-a----       20.04.2017     21:11            157 Microsoft.Build.xml
-a----       20.04.2017     21:11            158 Microsoft.CSharp.xml
-a----       20.04.2017     21:11            159 Microsoft.JScript.xml
-a----       20.04.2017     21:11            182 Microsoft.VisualBasic.Compatibility.Data.xml
-a----       20.04.2017     21:11            177 Microsoft.VisualBasic.Compatibility.xml
-a----       20.04.2017     21:11            163 Microsoft.VisualBasic.xml
-a----       20.04.2017     21:11            166 Microsoft.VisualC.STLCLR.xml
-a----       20.04.2017     21:11            159 Microsoft.VisualC.xml
-a----       20.04.2017     21:11            150 mscorlib.xml
-a----       20.04.2017     21:11            164 PresentationBuildTasks.xml
<...>
```
The folder contains XML docs for referenced libraries.

**Comment by Crypt32** [comment]
Yes, XML files have exactly the same content as in your case, they reference to v4.X folder that contains full XML files.

**Comment by Crypt32** [comment]
More details:

```
PS C:\> dir "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\"


    Directory: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       30.11.2015     12:01                v3.5
d-----       22.03.2018     19:39                v4.0
d-----       22.03.2018     19:39                v4.5
da----       30.11.2015     11:59                v4.5.1
da----       22.03.2018     19:39                v4.5.2
da----       22.03.2018     19:39                v4.6
da----       31.07.2016     16:58                v4.6.1
da----       23.10.2017     18:08                v4.6.2
d-----       22.03.2018     19:39                v4.X
```
| --- | --- |
| --- | --- |
|v3.5|no XML|
|v4.0|reference to 4.X|
|v4.5|reference to 4.X|
|v4.5.1|full XML|
|v4.5.2|reference to 4.X|
|v4.6|reference to 4.X|
|v4.6.1|full XML|
|v4.6.2|full XML|
|v4.X|full XML|

**Comment by EWSoftware** [comment]
Okay, I'll issue an update next weekend that fixes the issue.

**Comment by Crypt32** [comment]
Ok, thank you very much!

**Comment by twevhdt** [comment]
I think I have been struggling with the same issue: inheritdoc not finding anything for (for example) public override int GetHashCode(). Seems a bit surprising that Microsoft's %PROGRAMFILESDIR% seems to be intended to refer to "C:\Program Files (x86)\" even on my 64-bit copy of Windows.

I look forward to the update.
