### ISSUE TITLE
SandCastle Visual Studio extension breaks Edit.GoTo command

### ISSUE THREAD

**Issue by axodox** [EWSoftware/SHFB#594]
I have installed latest SandCastle recently, and found that the Visual Studio extension shipping with it breaks Edit.GoTo command in Visual Studio 2015 (I have not tested with others). I noticed this since I am using this command from my Visual Studio extension called AxoCover. That being said I removed my extension for confirming the issue is with SandCastle.

How to reproduce?
Open Command Window from View / Other WIndows, open a C# code file. Go back to command window and type: Edit.GoTo 15 (so go to line 15). If SandCastle is installed you will get the following error: "Command "Edit.GoTo" does not accept arguments or switches.", and the go to line operation will not be performed. If I uninstall SandCastle extension it works.

**Comment by EWSoftware** [comment]
It seems to be related to the extended XML comments completion option.  Go to Tools | Options, select the Sandcastle Help File Builder category, and uncheck "Enable extended XML comments completion options".  Once you close and reopen any affected file, it works as expected.  That will work around it for the time being.

**Comment by axodox** [comment]
Thanks. I will try it!

**Comment by EWSoftware** [comment]
A command filter used by the extended completion set option wasn't behaving correctly.  It has been fixed for the next release.  No due date yet, it'll probably be a few weeks.

**Comment by axodox** [comment]
Great! Thanks.

**Comment by jadaml** [comment]
The release v2018.5.14.0 does not install this update to Visual Studio 2017. which is also affected by axodox/AxoCover#146 bug. The installer seems to notice that not all packages were installed, but pressing **Install Package** again does not install anything more. I do not know how could I force it to install.

**Comment by sharwell** [comment]
@EWSoftware The code in `CommandFilter` is based on the implementation in tunnelvisionlabs/vsbase. The reference implementation has since been updated to correctly handle the case that was impacting this issue. You can find the latest version here:
https://github.com/tunnelvisionlabs/vsbase/blob/master/Shell.Utility/CommandFilter.cs

**Comment by EWSoftware** [comment]
@jadaml: The guided installer doesn't look on drives other that the C: drive right now for VS2017.  You can run the VSIX package manually from the .\InstallResources folder.

**Comment by jadaml** [comment]
Thanks! The installer offered to install it for VS2017.
