### ISSUE TITLE
.NET CORE Project Build pipeline

### ISSUE THREAD

**Issue by tpever** [EWSoftware/SHFB#598]
Hi,

I am trying o use Sandcastle for my .NET Core API project.  One of information is looking for how can is use SHFB Nuget package in build pipeline for .NET Core API project.  

As per standard document for .NET framework we need to specify ComponentPath to package folder where tools are installed.  For .NET Core packages will be deployed into profile folder and not directly accessible from current folder.  Also for .NET Core project build system could be Linux 64x based agent will the SHFB tools works on Linux system. 

Requesting you to please provide details for .NET Core project, how to use Nuget packages and define build pilpeline.

Thanks and regards

**Comment by EWSoftware** [comment]
Sorry, I'm not at all familiar with .NET Core or how its project system works.  The SHFB project just needs a path to the tools.  If you can extract them somewhere and point the SHFBROOT project variable at that location, it should work whether it was downloaded as a NuGet package or not.

I'm not familiar with Linux either and have never tried using the tools on such a system.  The SHFB tools are built against the full .NET Framework, not .NET Core or .NET Standard, so I doubt they'd work on Linux without changes.  That's not something I can handle.

**Comment by eriawan** [comment]
@EWSoftware 

I suggest we can start to create new .NET Core template for SHFB, based on .NET Core 2.0 compliant. 
For example: `dotnet new sandcastle` will create new Sandcastle project with necessary class libraries/nuget references that is optimized for .NET Core.

I can help you to create one.
But first, we need to create a .NET Core compliant Sandcastle library that can be published as part of Sandcastle nuget :)

**Comment by zb-z** [comment]
The first and biggest problem is that you'd have to have a 2nd build. For whatever historical reasons "Core" is not on speaking terms with "Framework" (akka normal :-) CLR/VM. That means at least a new .csproj and unless there's an extension. won't be editable in VS (see this: https://weblog.west-wind.com/posts/2017/jun/22/multitargeting-and-porting-a-net-library-to-net-core-20), which is not a big loss :-) but still means work.

Library-wise there aren't any big diffs, unless you are using something "too new" that gets Framework versions 1-2 yrs before Core (like Azure libs and tools, although that might have changed in the past year). Language support wise Core 2.0 is on par with 4.7.2 and VS 2017 and ahead of 4.5 and VS 2015 (proper tuples, ValueTuple, ...).

**Comment by msawczyn** [comment]
@zb-z This has changed. Not sure if it helps any, but a csproj can be multi-targeted to target more than one framework at the same time. You can split up the references conditionally per target framework as well. I've done this with a number of different projects and, as long as the dependency namespaces are the same, it works quite nicely.

Again, since I haven't dug into how Sandcastle builds I can't say that this is helpful information, but just thought I'd throw it out there since the reference you mention is quite a few years old now.
