### ISSUE TITLE
Version Builder ripOldApis and extension methods

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/SHFB#6]
*Moved from [CodePlex](https://shfb.codeplex.com/workitem/35512)*
*Originally submitted by sharwell*

When the Version Builder is used, ripOldApis is true, and the old version of the assembly contains an extension method which is no longer present in the new version, the following occurs.

1. The class where the old extension method was defined does not show the old extension method in the members listing. This is the expected behavior. 
2. The type for which the extension method is defined does show old extension method in its list of extension methods, but it is an unresolved link (build warning, shows as a bold non-hyperlink in the output). I expected the extension method to not be shown.

**Comment by sharwell** [comment]
:sparkles: I am so happy right now. :metal: :dancers:
