### ISSUE TITLE
Customize the output

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#600]
I would like to customize the documentation produced by SHFB, and I have no idea where to start. 
I have already added a syntax filter for our language, but now I would like to change how TOC entries and topics are generated. The changes that I would like to make are:

1. Our language has Functions and Procedures (like Subs in VB). The compiler converts these to methods of a compiler generated Functions class. I would like the TOC entries to be named "Foo() function" in stead of "Foo() method" and I would like to rename "Functions Class" to "Functions" and remove the TOC node "Functions Methods". Also inside the topics there is now a See also link to "Functions Class" which should be renamed to "List of Functions" or something like that.

2. Our language has some special types. For example there is a keyword USUAL which is represented by the XSharp.__Usual type. I have managed to rename this in the syntax filter, but on several other spots the docs still show the "Internal"  name "__Usual" or "XSharp.__Usual", such as in the constructor names, the overloads list, the types for parameters and return types and more. 

I think I will probably have to write a plugin for that but I could use some pointers on where to start.

Robert

**Comment by EWSoftware** [comment]
Given what you want to change, you'll probably need to clone one of the existing presentation styles and modify it along with its resource items.  See the [Creating a Presentation Style Component] topic for details on creating the component.

You'd create a presentation style component project and then copy the existing content, transformations, etc. from one like the VS2013 style and modify them to suit your needs.  The topic titles are in the shared content item files witin the presentation style (shared_content.xml, reference_content.xml).  You can locate the item and change or remove the hard-coded text that reference "Methods", "Class", etc.  Regarding the "__Usual" naming change, you may be able to handle that through the transformations as they contain specify templates that generate the method names for the titles based on the reflection information.

**Comment by RobertvanderHulst** [comment]
Eric,
Thanks for the tips. I will copy one of the presentation styles and will see if I can get it to work.
Robert
