### ISSUE TITLE
Always Builds

### ISSUE THREAD

**Issue by ZipZamZappem** [EWSoftware/SHFB#602]
I'm sure it is something I'm doing wrong but I'm stumped. I have the SandCastle doc project set to depend on the documented component but even when the component does not build (no changes) the SandCastle project does build. Can someone suggest how I get this project to build only if there are changes in the documented component?

**Comment by EWSoftware** [comment]
Setting the dependency just ensures that the SHFB project will build after the documentation sources.  There is no support for suppressing the build if nothing in the documentation sources actually changed.  The best approach is to use the configuration manager to suppress the build for specific configurations such as Debug and only let it build for Release builds for example.
