### ISSUE TITLE
Problems using <inheritdoc> with .NET Framework 4.6.1

### ISSUE THREAD

**Issue by fragmer** [EWSoftware/SHFB#605]
I have a C# project targeting .NET 4.6.1 and I want to use `inheritdoc` to reference classes from CLI standard libraries and WPF. I have a SHFB project with DocumentationSources pointing to my DLL/XML files.

If I configure my SHFB project to use FrameworkVersion 4.6.1, inheritdoc does not work. GenerateInheritedDocumentation produces "No comments found" warnings (GID0002 or GID0004). BuildTopics produces "missing documentation" warnings. Output is missing inherited documentation.

However, if I change my SHFB project to use .NET 4.6.2, everything starts working. No warnings are produced and docs end up exactly as-expected. Notes:
- I did NOT change my library project's target framework (it stayed on .NET 4.6.1).
- This workaround is only effective if DocumentationSources points to my DLL/XML files. If DocumentationSources points my csproj file, inheritdoc still doesn't work.

Repro project can be found here: https://github.com/fragmer/InheritdocRepro
Steps:
1. Build "ExampleWpfLibrary" once in Debug mode, to produce binaries
2. Build "DocProject" (which defaults to 4.6.1). Docs end up incomplete, and warnings are produced: ![2018-05-18_12-26-37_hh](https://user-images.githubusercontent.com/587809/40253988-b6120b56-5a96-11e8-862f-b2b0c5ac6140.png)
```
		GenerateInheritedDocumentation
SHFB(0,0): warning GID0004: No comments found for member 'M:ExampleWpfLibrary.MyContentControl.OnApplyTemplate'
SHFB(0,0): warning GID0002: No comments found for cref 'M:System.Windows.UIElement.OnCreateAutomationPeer' on member 'M:ExampleWpfLibrary.MyContentControl.OnCreateAutomationPeer'
SHFB(0,0): warning GID0002: No comments found for cref 'M:System.Object.ToString' on member 'M:ExampleWpfLibrary.BasicObject.ToString'
		BuildTopics
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:ExampleWpfLibrary.BasicObject.ToString] Missing <summary> documentation [R:\github\InheritdocRepro\DocProject\Help\Working\BuildTopics.proj]
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:ExampleWpfLibrary.BasicObject.ToString] Missing <returns> documentation [R:\github\InheritdocRepro\DocProject\Help\Working\BuildTopics.proj]
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:ExampleWpfLibrary.MyContentControl.OnApplyTemplate] Missing <summary> documentation [R:\github\InheritdocRepro\DocProject\Help\Working\BuildTopics.proj]
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:ExampleWpfLibrary.MyContentControl.OnCreateAutomationPeer] Missing <summary> documentation [R:\github\InheritdocRepro\DocProject\Help\Working\BuildTopics.proj]
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:ExampleWpfLibrary.MyContentControl.OnCreateAutomationPeer] Missing <returns> documentation [R:\github\InheritdocRepro\DocProject\Help\Working\BuildTopics.proj]
```

3. To try the workaround, change "DocProject" FrameworkVersion to 4.6.2 and build again. No warnings will be produced. Docs are complete:
![2018-05-18_12-27-27_hh](https://user-images.githubusercontent.com/587809/40253972-aac5249a-5a96-11e8-9f00-2d2087cefc59.png)

My environment:
- VisualStudio 2017 Professional 15.7.1
- SHFB v2018.5.14.0
- Windows 10 Enterprise version 1709 (build 16299.371)

**Comment by EWSoftware** [comment]
I ran across an issue today where it wasn't inheriting comments for .NET 4.7.1.  The framework XML comments files exist but when you actually open one all it contains is a redirect to a different folder.  Perhaps that's what's happening here.  Open the XML comments files found in *C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1* to see if that's the case.  If it is, all you'll see is something like:

```
<doc redirect=%PROGRAMFILESDIR%Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\XXX.xml />
```
On my system, the .NET 4.6.2 comments files are complete and the example builds without error.  Switching to .NET 4.7.1 does fail with the missing comments though.

**Comment by Crypt32** [comment]
Same as my case: https://github.com/EWSoftware/SHFB/issues/592

**Comment by fragmer** [comment]
@EWSoftware It is just as you described on my PC.

I located xmldoc under `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1`. The contents of PresentationFramework.xml are:

```xml
<?xml version="1.0" encoding="utf-8"?>
<doc redirect="%PROGRAMFILESDIR%Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\PresentationFramework.xml" />
```

The `v4.6.2` and `v4.X` folders contain complete copies of xmldoc.
