### ISSUE TITLE
Possible to build a Sandcastle project on AppVeyor?

### ISSUE THREAD

**Issue by TheFuzzyRiolu** [EWSoftware/SHFB#606]
Hey there. I'd like to automate the building of a Sandcastle project for my game engine. What I want to accomplish is:

1. I make a commit to the engine's GitHub repository.
2. AppVeyor pulls down the engine's code, compiles it, sticks it in an artifact.
3. AppVeyor also compiles an SHFB project for said game engine, outputting HTML for a website as an artifact.
4. The engine's artifact is downloadable from AppVeyor. The help artifact is uploaded to a VPS where it is then accessible at http://docs.watercolorgames.net/ (this just redirects to my community forum until I set this stuff up).

Is this possible, and if so, could someone walk me through setting it up? I'm not super familiar with AppVeyor and using it in an advanced way.

If there's a better place to ask this, do let me know :)

**Comment by sharwell** [comment]
This project does it:
https://github.com/tunnelvisionlabs/dotnet-threading

**Comment by TheFuzzyRiolu** [comment]
Well at least I know it's possible. Though I'm not really good with
PowerShell. Is there possibly a guide for setting this up on my own repo?

**Comment by ritchiecarroll** [comment]
FYI - in case anyone finds this thread, this worked for me:

1) Under "Environment", add an "Environmental variable" for:
   `SHFBROOT = C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\`
2) Under "Build", add the following to the `Cmd`-based "before build script:
    `choco install sandcastle`

Thanks!
Ritchie
