### ISSUE TITLE
How to customize TOC?

### ISSUE THREAD

**Issue by garymooney** [EWSoftware/SHFB#607]
Hi,

I've managed to successfully clone VS2013's Presentation Style Project and I know that it's working correctly because when I modify the reference_content.xml file, I can see the expected changes after compiling SHFB. 

I'm now attempting to change the TOC to behave more conventionally, where siblings of parent nodes are visible. I've been trying to modify the branding-Website.js file for hours and I can't seem to get any noticeable changes in behavior at all. Even commenting out all of the contents in the BuildChildren method does nothing (although if I comment out too much code, the toc eventually just disappears).

Note: viewing any of the html pages source seems to be correctly linking to the modified branding-Website.js.

I'm sure I must be approaching this problem in the wrong direction. Would I be able to please get some guidance.

**Comment by EWSoftware** [comment]
The Lightweight Website Style plug-in inserts the necessary TOC fragment into each topic and generates the TOC file it uses.  More likely than not, you'll need to create a copy of it and modify how it inserts the surrounding TOC elements.

**Comment by garymooney** [comment]
Thanks for the quick response.

So when I include the Lightweight Website plug-in, what does the branding-Website.js file do? Or is the logic mostly overridden? 

I'll have a go over the next couple of days at copying the Lightweight plug-in as you said. 

Thanks for the help

**Comment by EWSoftware** [comment]
The script file contains the methods needed to adjust the TOC panel size, load the child node info, expand and collapse the nodes, etc. within the browser.  The plug-in is what determines what info is initially visible and what nodes to include in the TOC fragment that gets inserted into the topic as well as what goes into the related TOC files that gets generated.
