### ISSUE TITLE
Uninstallation guide

### ISSUE THREAD

**Issue by franklinyu** [EWSoftware/SHFB#609]
Is there any guide about how to uninstall everything installed by SHFB installer? I plan to uninstall Visual Studio; I suppose that SHFB will not be automatically uninstalled, right?

**Comment by EWSoftware** [comment]
There are only two things installed by the guided installer: The SHFB tools and the VSIX package.

If you're removing Visual Studio, there's no need to uninstall the VSIX package any more than you would any other third-party packages you may have installed.  The SHFB Tools are standalone and can be used without Visual Studio.  If you're never going to use them again, they can be removed.

**Comment by franklinyu** [comment]
Does "the SHFB Tools" refer to "Sandcastle Help File Builder" in the "Programs" Control Panel? How about following stuffs I installed during the installation of SHFB:

1. HTML Help Workshop
2. MAML Schema IntelliSense
3. MAML Snippet Files

?

**Comment by EWSoftware** [comment]
Yes, SHFB Tools refers to the Sandcastle Help File Builder.  HTML Help Workshop is a used to build Help 1 files.  Uninstall it if you want to.  The schema and snippet files aren't installed as such, just copied to well-known locations.  Again, no real need to remove them.

**Comment by franklinyu** [comment]
All right. Thank you.
