### ISSUE TITLE
Build automation

### ISSUE THREAD

**Issue by vonlar** [EWSoftware/SHFB#610]
Recently reinstalled on a new machine updated my code and upon commit and automated build I received this error:
>The selected file is for a more recent version of the help file builder. Please upgrade your copy to load the file. ---> SandcastleBuilder.Utils.BuilderException: The selected file is for a more recent version of the help file builder. Please upgrade your copy to load the file. 
>at SandcastleBuilder.Utils.SandcastleProject.LoadProperties()

I went back to the Sandcastle project and had to comment this section out to get it to compile locally
`  <PropertyGroup>
    <SHFBROOT Condition=" '$(SHFBROOT)' == '' ">$(MSBuildThisFileDirectory)..\packages\EWSoftware.SHFB.2017.5.15.0\Tools\</SHFBROOT>
    <ComponentPath>..\packages</ComponentPath>
  </PropertyGroup> `

Then it started giving me this error on the build machine:
> Error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Any thoughts?

**Comment by EWSoftware** [comment]
The SHFBROOT environment variable isn't defined.  If you just installed it, you may need to reboot so that it becomes effective.
