### ISSUE TITLE
Code documentation file not solved

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#612]
Hello,

I have more than one C# project that I want include in a help file. One of those projects has a code snippet include in documentation like this

```C#
/// <code language="VB" title="VBScript use object" source=".\Documentation\Scripts\WindowsIniFile.vbs" region="General"/>
```

If I build the help documentation only on this project all runs well. If I do it with the project package it runs in an exception:

```
BuildAssembler : error :  [D:\Projects\WireDatabase\WireDatabase.ObjectModel\Help\Working\BuildTopics.proj]
BuildAssembler : error : CodeBlockComponent: [N:Common.IO] Unable to load source file 'D:\Projects\WireDatabase\WireDatabase.ObjectModel\Documentation\Scripts\Common.IO.WindowsIniFile.vbs'.  Error: Ein Teil des Pfades "D:\Projects\WireDatabase\WireDatabase.ObjectModel\Documentation\Scripts\Common.IO.WindowsIniFile.vbs" konnte nicht gefunden werden. [D:\Projects\WireDatabase\WireDatabase.ObjectModel\Help\Working\BuildTopics.proj]
  CopyFromIndexComponent: "reflection" in-memory cache entries used: 15 of 15.
  CopyFromIndexComponent: "comments" in-memory cache entries used: 6 of 30.
  SaveComponent: Waiting for the document writer task to finish (71 Help1 API file(s) remaining)...
Done Building Project "D:\Projects\WireDatabase\WireDatabase.ObjectModel\Help\Working\BuildTopics.proj" (default targets) -- FAILED.

Build FAILED.

Time Elapsed 00:00:10.29
    Last step completed in 00:00:10,4566
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   bei SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   bei SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

**Lookup of that code sample file should not go from directory of current help file, should look up relative to XML documentation file** of that project as done in standalone help file of that project.

My project directory/file structure is:
```
...
Projects\Common\Common.shfbproj
Projects\Common\Documentation\IO.WindowsIniFile.vbs
Projects\Common\IO\WindowsIniFile.cs
...
Projects\Common\bin\Debug\Common.dll
Projects\Common\bin\Debug\Common.xml
...
Projects\ObjectModelBase\bin\Debug\ObjectModelBase.dll
Projects\ObjectModelBase\bin\Debug\ObjectModelBase.xml
...
Projects\WireDatabase\WireDatabase.ObjectModel\WireDatabase.ObjectModel.shfbproj
...
Projects\WireDatabase\WireDatabase.ObjectModel\bin\Debug\WireDatabase.ObjectModel.dll
Projects\WireDatabase\WireDatabase.ObjectModel\bin\Debug\WireDatabase.ObjectModel.xml
```
Running ``Projects\Common\Common.shfbproj`` goes well, which only includes ``Common.dll`` and ``Common.xml``.

Same for ``Projects\WireDatabase\WireDatabase.ObjectModel\WireDatabase.ObjectModel.shfbproj`` throws exception/error. There are included ``Common.dll``, ``Common.xml``, ``ObjectModelBase.dll``, ``ObjectModelBase.xml``, ``WireDatabase.ObjectModel.dll`` and ``WireDatabase.ObjectModel.xml``.

Do I remove ``Common.dll`` and  ``Common.xml`` I'm able to build the help project. But I need ``Common.dll`` and  ``Common.xml`` included as well.

Regards

Holger

**Comment by EWSoftware** [comment]
This is by design.  Paths in `source` attributes on `code` elements are always relative to the SHFB project folder unless that's overridden in the Code Block Component configuration.  XML comments files may or may not be part of a Visual Studio project or in the same location depending on the build configuration and `OutDir` setting for example.

In this case, you can configure the Code Block Component in each SHFB project with a common base path of `{@HtmlEncProjectFolder}\..` and `{@HtmlEncProjectFolder}\..\..` respectively so that it equates to the root *.\Projects* folder and update the `source` attributes with appropriate paths relative to it.

**Comment by VBWebprofi** [comment]
Thanks for advise. Can there be multiple _Code Block Components_  active? Where points ``{@HtmlEncProjectFolder}`` to? How can I use ``{@HtmlEncProjectFolder}`` in MAML?

**Comment by EWSoftware** [comment]
There can be only one instance of the code block component.  The `{@HtmlEncProjectFolder}` reference goes in the code block component configuration.  Go to the Components tab in the SHFB project properties, add the Code Block Component, and change the base path setting there.  It gets replaced with the [SHFB project folder](http://ewsoftware.github.io/SHFB/html/69d998a7-1af5-4bf5-889b-59cd00b64000.htm) at build time in the BuildAssembler configuration file

Substitution tags are not handled in MAML topics.  As such, keep the paths relative to the common root as noted above and it will work as expected.
