### ISSUE TITLE
Rendering of simple type names in code blocks

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#616]
:question:  Is there a flag or way to render such code of language depend type names

```C#
public bool Connected { get; }
```
as Framework.NET type names

```C#
public Boolean Connected { get; }
```
?

**Comment by EWSoftware** [comment]
No, all syntax generators write out types in the language keyword syntax rather than using the .NET types.  If it's just for one specific language you could derive your own and override the `WriteNormalTypeReference` method to write out the type names rather than the language keywords.
