### ISSUE TITLE
NamespaceSummaries

### ISSUE THREAD

**Issue by morten-leerhoy** [EWSoftware/SHFB#617]
Is it possible to have the NamespaceSummaries generated with MSBuild? Been looking through the documentation, but haven't found the right switch.

**Comment by EWSoftware** [comment]
Instead of defining them in the project, you can put [NamespaceDoc classes](http://ewsoftware.github.io/SHFB/html/48f5a893-acde-4e50-8c17-72b83d9c3f9d.htm) in your code.  When the help project is built, it will convert the comments for them to the related namespace summaries.
