### ISSUE TITLE
Prebuild XSLT transform support

### ISSUE THREAD

**Issue by ds1709** [EWSoftware/SHFB#618]
I'm using VS 2017 Sandcastle Help project. It will be good to using prebuild XSLT transforms to simplify source XML (aml) code, e.g. source code
```xml
<list class="ordered">
    <listItem>
        <para>Item 1.</para>
    </listItem>
    <listItem>
        <para>Item 2.</para>
    </listItem>
    <listItem>
        <para>Item 3.</para>
    </listItem>
</list>
```
can be simplified to
```xml
<list class="ordered">
    <paraListItem>Item 1.</paraListItem>
    <paraListItem>Item 2.</paraListItem>
    <paraListItem>Item 3.</paraListItem>
</list>
```
with further XSLT transform.

**Comment by EWSoftware** [comment]
I'm not sure this really saves much in the way of time or typing.  It would be a custom element added to all presentation styles to save you from entering a `para` element.  With the schemas installed for IntelliSense, it doesn't take much to enter the extra element.  You'd need to fall back to the standard `listItem` element if you wanted other content in the item as well.

**Comment by ds1709** [comment]
The idea was not to modify builder or creating some new custom element, but just make able to apply XSLT for source xml before build, and after then use resulting xml as source for builder. We have some source xml, templated for transform. After transform we have xml with standard elements, no need to handle any new element or something like this. Resulting xml used to build help.
P.S. Situation with list is just a sample. There're more dificult scenarios.

**Comment by EWSoftware** [comment]
You can [write your own plug-in](http://ewsoftware.github.io/SHFB/html/a14e026e-642f-4ce6-9506-341e57cc3d1f.htm) to do that if the intent is to transform the content at some point in the build.

**Comment by ds1709** [comment]
I created plugin and would like to pull it. What copyright i should specify?

**Comment by EWSoftware** [comment]
You can put your own copyright on it since you wrote it.  I'd rather you just provide a link to the plug-in so that I can include it in the [Links to Resources](http://ewsoftware.github.io/SHFB/html/c18d6cb6-e4e4-4944-84ee-f867aa6cfb0d.htm) topic.

**Comment by ds1709** [comment]
Here is repository where plug-ins source code placed:
https://github.com/ds1709/SHFB-Plugins
