### ISSUE TITLE
Unexpected error in the build step while reaching the XmlAttributeAttribute in the code

### ISSUE THREAD

**Issue by Ramin2c** [EWSoftware/SHFB#621]
Hi!
I am facing an error during the build step of my documentation project in VS 2017. The project is a .net standard 2.0 class library which has [XMLAttribute] or [XMLText] on some of its members. The build fails on its GenerateReflectionInfo step complaining for:

SHFB(0,0): error BE0043: Unexpected error detected in last build step.  See build log for details.

And looking into the logs, I can see the following lines before the failure:

Encountered conflict between &#39;Platform:System.Xml.XmlSerializer.dll&#39; and &#39;CopyLocal:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XmlSerializer.dll&#39;.  Choosing &#39;CopyLocal:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XmlSerializer.dll&#39; because AssemblyVersion &#39;4.0.11.0&#39; is greater than &#39;4.0.10.0&#39;.
GenerateRefInfo:
  MRefBuilder (v2018.5.29.0)
  Copyright &#184; 2006-2018, Microsoft Corporation, All Rights Reserved.
  Portions Copyright &#184; 2006-2018, Eric Woodruff, All Rights Reserved.
  No source code context base path specified.  Source context information is unavailable.
  Loaded 1 assemblies for reflection and 124 dependency assemblies.
  Using automatic redirect &#39;System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&#39; in place of &#39;System.Xml, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&#39;

Process is terminated due to StackOverflowException.
    Last step completed in 00:00:08,6400
</buildStep>
<buildStep step="Failed">

It is to reproduce the error, starte a "class library" project with .NET Standard, add a single public member with XmlAttribute and build the documentation and it should fail. 

Other Observations:

1. The document generation for the same code will pass however on Console Application project type. That I guess is due to the usage of NETCore instead of NETStandard library (that is automatically selected).
2. I can compile the documentation from within the help file builder GUI when I provided a previously compiled all together with XML generated file all the nuget dependencies.
3. I cannot even define an API Filter for my project from the settings. It fails again on the GenerateReflectionInfo.

And since we would like to have our documents being automatically generated on the build server, we cannot use the GUI and thus would be nice to get it work. Hope there is a fix for this issue.

Best Regards
Ramin Toussi

**Comment by Ramin2c** [comment]
As a workaround, I managed to build using MSBuild 15. I guess it should work well on our build server too.

**Comment by EWSoftware** [comment]
I wasn't able to duplicate this issue using the example you gave for a .NET Standard class library project.  If it's still a problem and you can attach an example, feel free to reopen it.
