### ISSUE TITLE
Installing on Windows 10

### ISSUE THREAD

**Issue by Ramin2c** [EWSoftware/SHFB#624]
I am trying to install on Windows 10 via the Guided Installation (v2018.07.08) but the setup hangs on the "Sandcastle Help File Builder and Tools" step after I press the button "Install SHFB" with the text "Installing, please wait ...". I tried many times, even with Run as Administrator option and it is all the same.
Is there any specific setting for Windows 10 or is it the setup file that is not compatible with Windows 10?

**Comment by EWSoftware** [comment]
There's nothing special needed to install on Windows 10.  You can try running the installers directly from the *.\InstallResources* folder.

**Comment by Ramin2c** [comment]
Thanks for the tip. It worked. Looks to be the Windows 10 Smart Screen blocking the execution of the InstallResources process. Running it separately, I could see the Smart Screen warning and "Run Anyway" button.
