### ISSUE TITLE
Trying to install Sandcastle v2018.7.8.0) for Visual Studio 2017 Installing SHFB please wait

### ISSUE THREAD

**Issue by GoDuxs** [EWSoftware/SHFB#626]
It has the status of "Installing .. Please wait " it looks like it is installing something (star spinning) but it never does anything I left it run for 24hrs and nothing happens.  Can't install this application don't know what else to do...

**Comment by EWSoftware** [comment]
Run the installers separately from the .\InstallResources folder.  If there's an issue or popup or something, you should see it and be able to handle it that way.  You can run the guided installer afterwards to install anything else such as the schemas and snippets.

**Comment by EWSoftware** [comment]
No, run the MSI and VSIX files directly.  Do not use the guided installer.

**Comment by GoDuxs** [comment]
Thank you that worked great... :-)...
