### ISSUE TITLE
Missing <param name>, <summary>

### ISSUE THREAD

**Issue by Jagsta2121** [EWSoftware/SHFB#631]
on serveral of my subs/functions sandcastle wont see some or all of the properties/summaries 

        ''' <summary>
        ''' Gets all the Data for Type13 
        ''' and builds a Completed Type13 Class
        ''' </summary>
        ''' <param name="items">List of items to Get data on</param>
        ''' <param name="WareHouse">6 digit WareHouse</param>
        ''' <returns>Completed Type13 Class</returns>

 items works but WareHouse says its missing. a few have all the data others have one parameter missing or more.

**Comment by EWSoftware** [comment]
Make sure your XML comments file is up to date (force a full rebuild of the documentation source projects).  You can also check the XML comments file being used to ensure the elements are actually there.  The XML comments files used in the build are listed in the build log.
