### ISSUE TITLE
Company title and logo on every page 

### ISSUE THREAD

**Issue by Ramin2c** [EWSoftware/SHFB#632]
I know it is possible to add a logo to every page but how is it possible to add two images, one for title and the other one for the log? I would like to have the company title on the left most and the company logo on the right most of every page. Is this possible? if yes, how ....

**Comment by EWSoftware** [comment]
There's only support for one logo placed to the left, right, or above the topic header.  You'd have to modify the presentation style to support two.

**Comment by Ramin2c** [comment]
Thanks for the answer.
