### ISSUE TITLE
How to reference used type at a Generic in MAML?

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#634]
If want create a generated reference of this output:

```
System.Collections.Generic.IEnumerable<System.String>
```

I tried this:

```
<codeEntityReference qualifyHint="true">System.Collections.Generic.IEnumerable{System.String}</codeEntityReference>
```

but got

```
System.Collections.Generic.IEnumerable<String>
```

which is not linked to MSDN.

:question: How can I get a reference I figured out above (first code) where both parts ( ``System.Collections.Generic.IEnumerable<T>`` and ``System.String`` ) are referenced to MSDN?

**Comment by EWSoftware** [comment]
References to generics use the type parameter count suffix.  In this case it would be "`1":

``` XML
<codeEntityReference qualifyHint="false">T:System.Collections.Generic.IEnumerable`1
</codeEntityReference>
```

The curly braces format is for XML comments.  For XML comments, you'd use the placeholder name, {T} in this case.  The concrete type only exists in the compiled code and there would be no link to it online.

If in doubt, you can use the [Entity References tool window](http://ewsoftware.github.io/SHFB/html/e49eea91-a9ef-4aa5-ad8f-16ebd61b798a.htm) to locate the type or member and get a link in the proper format.

You could use the `linkText` attribute to show it with the string type but it would still only link to the `IEnumerable<T>` online documentation, not to `String` as well.

``` XML
<codeEntityReference qualifyHint="false" linkText="IEnumerable&lt;String&gt;">
T:System.Collections.Generic.IEnumerable`1</codeEntityReference>
```
You can combine two separate links to get the intended effect, something like:

``` XML
<codeEntityReference qualifyHint="false" linkText="IEnumerable">
T:System.Collections.Generic.IEnumerable`1</codeEntityReference>&lt;
<codeEntityReference qualifyHint="false">T:System.String</codeEntityReference>&gt;
```
