### ISSUE TITLE
VS2015 Save No such interface supported

### ISSUE THREAD

**Issue by Billyj82** [EWSoftware/SHFB#635]
I've gone through the installation instructions 3 times and every time I create a new project when I try to save I get an error "The operation could not be completed. No such interface supported".    I've searched online and made sure VS SDK tools feature was installed and some DLL's were gac'd according to others that have had this issue.  It still keeps happening.  

Thank you in advance for any help.

**Comment by Billyj82** [comment]
I'm on Update 3.  Version 14.0.25431.01

**Comment by EWSoftware** [comment]
You can try resetting Visual Studio (Tools | Import Export Settings | Reset All Settings).  Other than that, I don't know what else could be wrong.

**Comment by Billyj82** [comment]
Didn't work.  :(

**Comment by Billyj82** [comment]
I spoke with someone and found an old test Sandcastle project.  I can open that make changed and save with no issue.  I do notice a couple of small differences between them.  The old one has a SiteMap.sitemap loaded when the newly created one didn't and the old one has a Layout.Content file while the new one had a ContentLayout.content file.  Not sure if it helps in anyway.  When I click save it created the folder for the project then fails.

**Comment by Billyj82** [comment]
I found a work around.  If I got to VS 2015 and create a new blank solution, then add a sandcastle project to that blank solution after it is created everything works fine.
