### ISSUE TITLE
ASP.NET Core Not Binding

### ISSUE THREAD

**Issue by amainiii** [EWSoftware/SHFB#636]
Using the latest SHFB, we have NuGet references to ASP.NET Core assemblies in an MVC project, and there are no links generated for ASP.NET Core references such as IApplicationBuilder. The error message is
`[Missing <param name="app"/> documentation for "M:GoalsManagement.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment,Microsoft.Extensions.Logging.ILoggerFactory)"]
`
Is there a workaround we can add support for the links to docs.microsoft.com, or is this not supported yet?

**Comment by EWSoftware** [comment]
The warning you include isn't related to linking to the online docs.  It's related to XML comments members.  Are you using `inheritdoc` to inherit documentation from the base member?  If so, the parameter name is missing in the Microsoft XML comments file in the NuGet package.  There isn't much you can do about that except report it and hope they fix the comments.

If you aren't inheriting the documentation, then your project's code is missing the parameter documentation and you need to add it to the member indicated in the warning.

If you don't care about missing XML comments members, you can control which ones are reporting using the Missing Tags category in the SHFB project properties.

If you see a lot of warnings from the `ResolveReferenceLinksComponent` about MSDN URLs not found, that means the member could not be found in the MSDN online content.  Again, not much you can do about that except wait for them to include it.  You can't turn these warnings off, but they can be safely ignored.
