### ISSUE TITLE
Installation of SHFB extensions failes

### ISSUE THREAD

**Issue by AndreasReitberger** [EWSoftware/SHFB#641]
Hi, I tried to run the Installer, however everytime the installation of the "SHFB extension" for vs failes.
This is the error from the log file.

> Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.DiagnosticsHub.Collection.StopService.Install' failed to install
>    bei Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
>    bei Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
>    bei Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
>    bei Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
>    bei Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, InstallFlags installFlags, Boolean downgrade)
>    bei Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, InstallFlags installFlags, Boolean downgrade)
>    bei Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, InstallFlags installFlags, Version targetedVSVersion)
>    bei VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)

I'm running Windows 7 32 Bit and Visual Studio 2017 Community. I already tried to run it as admin, same problem. I attached the complete log file, if this helps. 

Any idea what happening?

Thanks a lot!

[VSIXInstaller_84e6775d-d2e2-49f7-9cea-9f83a4953517.log](https://github.com/EWSoftware/SHFB/files/2377790/VSIXInstaller_84e6775d-d2e2-49f7-9cea-9f83a4953517.log)

**Comment by EWSoftware** [comment]
It looks like it's failing trying to install a dependent Microsoft package.  You might try rebooting and then repairing your Visual Studio installation or updating it to the latest release if you aren't currently up to date.  That's the suggested fix for a similar issue reported at the [VS Developer Community site](https://developercommunity.visualstudio.com/content/problem/24825/microsoftdiagnosticshubcollectionservice-failed-to.html).
