### ISSUE TITLE
SHFB: Error BE0065: BUIL FAILED

### ISSUE THREAD

**Issue by SniperLegacy** [EWSoftware/SHFB#642]
I have an issue while building a project.
The error message is the following:
SHFB: Error BE0065: BUILD FAILED: La balise de début 'br' sur la ligne 580 à la position 40 ne correspond pas à la balise de fin de 'para'. Ligne 581, position 5.

Which clearly indicates that a tag br is wrong.
However, after looking into the working directory, it seems sandcastle retrieve referenced assemblies documentation which is fine if their documentation is correctly structured.

In my case, an assembly named canlibCLSNET is generating the issue.
If I change the xml file to resolve the error, the build generates another error saying that my assembly is missing : 
SHFB: Error BE0065: BUILD FAILED: Impossible de trouver une partie du chemin d'accès [PATH TO ASSEMBLY]

Then if I rebuild again, the file gets replaced and the same error gets generated.

So my question is how can I exlclude/ignore the assembly canlibCLSNET when building the documentation of my project ?

**Comment by EWSoftware** [comment]
This issue was resolved in the 2018.5.29.0 release.  Upgrading to it or the latest release should let you build the project as it will ignore invalid XML comments files now.
