### ISSUE TITLE
Build Error MSB6004

### ISSUE THREAD

**Issue by allen-628** [EWSoftware/SHFB#643]
Sandcastle Help Version 2018.7.8.0
OS Windows 10.0 Pro
error MSB6004: The specified task executable location "C:\Program Files (x86)\HTML Help Workshop\HHC.EXE" is invalid.
The path exists and is valid... hhc  version 4.74.8702

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by EWSoftware** [comment]
MSBuild thinks it's missing for some reason.  You can try reinstalling the HTML Help Workshop to see if that resolves it.

**Comment by allen-628** [comment]
Thank you for the reply;
The issue appeared when I had multiple document sources selected in the project explorer tree. After setting one and only one source the error no longer appeared. The help file compiled as expected.
I did try a re-install to try to resolve another issue; but I have not gone back to try a multiple document source build.
