### ISSUE TITLE
Missing summary warnings despite summaries and remarks in classes

### ISSUE THREAD

**Issue by allen-628** [EWSoftware/SHFB#644]
I am certain this is a setting issue somewhere; but there is absolutely no reference to resolving these type of issues in the help documentation.

Each class and class member has a summary `summary`, in some cases remarks `remarks` and when applicable `param`. Yet, the help file shows missing comments.

For example:
```
        /// <summary>
        /// Loads the data from the xml file provided in the file name parameter
        /// </summary>
        /// <remarks>
        /// The xml file <see cref="CBoundaries.xml"/> holds the bondary data
        /// </remarks>
        /// <param name="fileName">the xml file which contains the boundary data</param>
        private void Load(string fileName)
or
        /// <summary>
        /// Gets an enumeration of the boundary segments loaded upon instantating this class
        /// </summary>
        public IEnumerable<BoundariesSegment> Segments { get; private set; }
```
with these errors in the build output:
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/2386760/LastBuild.log)

**Comment by EWSoftware** [comment]
Regarding the missing comments, see the build log.  The [BE0062 warning](http://ewsoftware.github.io/SHFB/html/270ef6fd-7bec-4db0-875c-5d857294e9c6.htm) tells you that it didn't find the XML comments file.  That means you probably didn't enable generating it in the documentation source project.  See the [topic on enabling and using XML comments](http://ewsoftware.github.io/XMLCommentsGuide/html/57C91630-95D6-4E3E-AF24-3415CC569AC8.htm) for more info.  There are [several other topics on getting started](http://ewsoftware.github.io/SHFB/html/b772e00e-1705-4062-adb6-774826ce6700.htm) if you need help as well.

Also, you're using the `see` element incorrectly.  It's for referencing other types or members, not external XML files.  That won't even generate a valid element in the XML comments file.  See the [XML Comments Guide](http://ewsoftware.github.io/XMLCommentsGuide/html/4268757F-CE8D-4E6D-8502-4F7F2E22DDA3.htm) for element usage.

**Comment by allen-628** [comment]
Thank you, Eric, for your reply.

I tried to follow the instructions in enabling and using Xml Comments but I do not see an Output section that contains  checkbox next to the Xml documentation file.

This is what I see:



Regards,

Allen

**Comment by EWSoftware** [comment]
The picture didn't make it.  Can you attach it or insert it directly in the issue at the project site?

**Comment by allen-628** [comment]
![image](https://user-images.githubusercontent.com/2023769/45665221-ba7e5d00-bac4-11e8-98ea-38296610ce54.png)
Try this

**Comment by EWSoftware** [comment]
Not the Build category in the SHFB project, the Build category in the documentation source project (your C# or VB project file).

**Comment by allen-628** [comment]
Ok I understand now - however, for the sake of improving the documentation include screen shots of what is required. I started with the GUI and none of the help made sense, This is because step by step instructions were clear.

The GUI interface would work if examples where included for an existing project was used.
Then
1. From the Visual Studio Project in the application solution open the project properties 
 ![image](https://user-images.githubusercontent.com/2023769/45790831-a01abf80-bc3b-11e8-90fb-0aa0c2007f33.png)
2. check the XML documentation file 
![image](https://user-images.githubusercontent.com/2023769/45790848-bd4f8e00-bc3b-11e8-871d-79f3a89ff317.png)
3. Build the project
4. Add the XML source from the 3 to Document Sources in Sandcastle Help File Builder
 ![image](https://user-images.githubusercontent.com/2023769/45790994-76ae6380-bc3c-11e8-92ec-7b78448f33d8.png)
5 Build the Sandcastle Help File project
The nuance here is to spell the steps out. Or better yet provide a wizard to assist in the creation of a GUI project.
Thank you for all the support Eric. I appreciate it greatly.
