### ISSUE TITLE
Net 4.6 Framework Error

### ISSUE THREAD

**Issue by allen-628** [EWSoftware/SHFB#645]
This warning 
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\Allen\Documents\visual studio\Projects\SkyMap\Help\Help\Working\GenerateRefInfo.proj]
is superfluous as the help project is for library that does not reference Net frameworks, only system files. So project properties framework version should be set to empty.

**Comment by EWSoftware** [comment]
I don't know what you mean by only referencing system files.  SHFB only documents managed code assemblies which reference some version of the .NET framework whether you want them to or not.  You need to pick the one appropriate to your project type using the Framework Version project property whether that's a version of the .NET Framework, .NET Core, or .NET Standard.
