### ISSUE TITLE
Help in customizing the Sandcastle output

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#646]
We are using sandcastle to produce documentation for our own language X#. Our language is function based. Functions are implemented as static methods in a static class. Each assembly gets its own static class for the functions (and also constants and globals). We have succesfully created a syntax component and can generate syntax description with colors etc and methods are correctly documented as FUNCTION.
An example can be found on https://www.xsharp.info/runtimehelp/html/M_XSharp_Core_Functions_AmPm.htm.
Now we would like to change the way these functions are presented in the index and toc. Right now the TOC contains a Functions class and the functions are listed as Functions Methods.
In the TOC index each function is listed as "Foo Method".
What is the recommended way to do this ? Should we change the template or should we use create a plugin to modify the generated TOC and index after the generation?

There is also another change that we would like to make. Our language has a couple of built in  types, such as ARRAY, USUAL. These are implemented as special types in our runtime (__Array, __Usual). In our syntax examples these are properly translated. On other places, like the parameter types, return types and lists of methods these types are listed in their original form with the underscores.
See https://www.xsharp.info/runtimehelp/html/M_XSharp_VO_Functions_AClone.htm for an example.
What would be the recommended way to fix this?

Robert

**Comment by EWSoftware** [comment]
All of the items can be changed by [creating a presentation style](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm). You can copy the content files and transformations from an existing one such as the VS2013 style to get started.  You can then modify the resource item files to change the labeling on the TOC entries and topic headers etc.

To change the way the type names are output, you'd need to modify the XSL transformation that outputs the type name (`t_typeNamePlain` and `t_typeNameDecorated` in *utilities_reference.xsl* for example in the VS2013 style).  Those should let you handle the __Array and __Usual types accordingly.

If you want to change the layout of the TOC such as getting rid of the groupings or changing how the topics are grouped, you'd need to replace the `IntermediateTocTransformation` transformation file.  The current presentation styles use the *CreateVSToc.xsl* transformation to generate the TOC.
