### ISSUE TITLE
Random whitespaces in generated documents.

### ISSUE THREAD

**Issue by koszeggy** [EWSoftware/SHFB#648]
I use XML docs as the source of the documentation and since several versions the following issue exists in SHFB:

If a member or type name of a link contains generics, in many cases whitespaces appear after the opening angle bracket in the compiled .chm documentation.

Source example:

    /// <see cref="MyDictionary{TKey,TValue}"/>

Result:

    MyDictionary< TKey, TValue>

Similar issue for indexers:

     /// ...the indexer (<see cref="P:MyNamespace.MyDictionary`2.Item(`0)"/> property).

Result:

     ...the indexer (Item[ TKey] property).

I find this quite unpleasant because it suggests I have low documentation standards. The whitespace does not appear in every case but more than in 50% of the cases.

**Comment by EWSoftware** [comment]
It's a side-effect of the Help 1 and MS Help Viewer formats.  They use an older version of the browser control and an extra space is needed to keep things from running together in the language specific text.  The extra space isn't always needed but there's no good way to tell when it is or isn't needed so you get an extra space in some places.

If you're seeing this in website output, try updating to at least v2017.12.30.0 as that was about when it was restricted to doing it only for Help 1 and MS Help Viewer content.

**Comment by EWSoftware** [comment]
Well, I'm not aware of any better way to fix it and expecting everyone to read every topic and put non-breaking spaces into their comments where needed isn't an acceptable alternative so the extra space is what works for now.  If it bothers someone enough, feel free to try and come up with a fix that doesn't produce the extra space and submit it for inclusion in a future release.
