### ISSUE TITLE
Unable to edit namespace summaries

### ISSUE THREAD

**Issue by roryap** [EWSoftware/SHFB#650]
I'm always getting an error now when trying to edit the namespace summaries in a documentation project.  Please open the provided VS solution and edit the namespace summaries in the SHFB project.  The error message screen shot is also attached.

[Unable to edit namespace summaries.zip](https://github.com/EWSoftware/SHFB/files/2425570/Unable.to.edit.namespace.summaries.zip)

**Comment by roryap** [comment]
Thanks for your reply.  I have just tried what you suggested -- building the documentation project and then clicking on the "edit namespace summaries" and I got the same error.  I'm using Visual Studio 2017 Preview 2.0, version 15.9.0.

**Comment by roryap** [comment]
Hi there, I'm just wondering if you have any other thoughts on this.  Unfortunately I can't use the version of Sandcastle with this and issue #649

**Comment by EWSoftware** [comment]
If the namespace summaries editor is failing, it will fail when building normally.  You need to look at the build log for the normal build to see what the problem is.  Regarding the other issue, I haven't had a chance to look into it yet.

**Comment by roryap** [comment]
It's not failing when building normally, yet the namespace summaries editor is still failing.  Here's the build output: 

1>------ Rebuild All started: Project: ClassLibrary13, Configuration: Debug Any CPU ------
1>  ClassLibrary13 -> C:\_Temporary\New folder\ClassLibrary13\ClassLibrary13\bin\Debug\ClassLibrary13.dll
2>------ Rebuild All started: Project: Documentation1, Configuration: Debug Any CPU ------
2>		Removing build files...
2>		Removing build folders...
2>		Building C:\_Temporary\New folder\ClassLibrary13\Documentation1\Documentation1.shfbproj
2>		Initializing
2>		ValidatingDocumentationSources
2>		GenerateSharedContent
2>		GenerateApiFilter
2>		GenerateReflectionInfo
2>		TransformReflectionInfo
2>		GenerateNamespaceSummaries
2>		CopyConceptualContent
2>		CreateConceptualTopicConfigs
2>		CopyAdditionalContent
2>		MergeTablesOfContents
2>		GenerateIntermediateTableOfContents
2>		CreateBuildAssemblerConfigs
2>		MergeCustomConfigs
2>		BuildTopics
2>C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [N:ClassLibrary13] Missing <summary> documentation [C:\_Temporary\New folder\ClassLibrary13\Documentation1\Help\Working\BuildTopics.proj]
2>		CombiningIntermediateTocFiles
2>		ExtractingHtmlInfo
2>		CopyStandardHelpContent
2>		GenerateHelpFormatTableOfContents
2>		GenerateHelpFileIndex
2>		GenerateHelpProject
2>		CompilingHelpFile
2>		CleanIntermediates
2>		Completed
2>		The help file is located at: C:\_Temporary\New folder\ClassLibrary13\Documentation1\Help\Documentation1.chm
2>		Build details can be found in C:\_Temporary\New folder\ClassLibrary13\Documentation1\Help\LastBuild.log
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by EWSoftware** [comment]
Can you attach an example?  As noted, the one from your original post worked fine once the documentation source was built.

**Comment by roryap** [comment]
I've attached the example with screen shots. 
[Unable to edit namespace summaries.zip](https://github.com/EWSoftware/SHFB/files/2460982/Unable.to.edit.namespace.summaries.zip)

**Comment by EWSoftware** [comment]
That appears to be the same one from the original post with some screen shots.  I wasn't able to duplicate the issue.

If you can, get yours to fail and, while leaving the Namespace Summaries dialog box open, go to the partial build folder which will be `C:\Users\[YOURUSERID]\AppData\Local\Temp\SHFBPartialBuild`.  You should find a LastBuild.log file in there that contains the actual problem.  Take a look at that or attach it here so I can see it.

**Comment by roryap** [comment]
Here it is.
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/2462566/LastBuild.log)

**Comment by EWSoftware** [comment]
Based on the build log, it's finding an outdated version of the SHFB assemblies somewhere.  So either your SHFB installation or the Visual Studio package is out of date.  Try uninstalling both and reinstalling the latest version.
