### ISSUE TITLE
Can cref attribute reference a static constructor?

### ISSUE THREAD

**Issue by WithoutHaste** [EWSoftware/SHFB#653]
How do you write a cref to reference a static constructor?  The closest I can get is referencing the normal constructor.

```
class MyType
{
    /// <permission cref="MyType()">...</permission>
    static MyType()
    {
    }

    public MyType()
    {
    }
}
```

**Comment by EWSoftware** [comment]
You'd most likely have to do it using the fully qualified format:

```
<see cref="T:MyNamespace.MyType.#cctor" />
````

Bear in mind that the reference will not be resolvable unless you're including the private members in the documentation.
