### ISSUE TITLE
Unable to open CHM file generated by SHFB

### ISSUE THREAD

**Issue by JJoe2** [EWSoftware/SHFB#654]
Similar problem to #342.
Repro:
- Using SHFB 2017.12.30.2
- A VS2017 solution including an SHFB project that builds successfully, and generates a CHM file that can be opened successfully.
- Added a conceptual topic "v1.1.0.0.aml" with a description of some changes to the library being documented, and updated ContentLayout.content to reference this new file.  The added file contains little content.
- The solution builds successfully.
- If I attempt to open the resulting CHM file I get an error 
---------------------------
Help
---------------------------
Cannot open the file: mk:@MSITStore:C:\...path...\MyFileName.chm.
---------------------------
OK   
---------------------------

I can supply a VS2017 solution that repros the problem but would prefer to do so privately.

**Comment by JJoe2** [comment]
Thanks for the response.

I didn’t find anything relevant in the FAQ, so I’ve created the example at the following link :

https://drive.google.com/file/d/1tFLxgRa-jJ0oyRyST4IF7kFY09BmKJo5/view?usp=sharing

It’s a 12MB zip file with « before » and « after » solutions and a readme file.

Best Regards

**Comment by EWSoftware** [comment]
I got the example.  The included help file did fail as you describe.  However, I rebuilt the project and the resulting help file opened without issue.  All I can suggest is that you try reinstalling the HTML Help Workshop since that's the only component that will affect the compiled help file itself.
