### ISSUE TITLE
BuildTopics.proj  build  error

### ISSUE THREAD

**Issue by wj60387** [EWSoftware/SHFB#655]
![image](https://user-images.githubusercontent.com/20125752/47427577-4f126400-d7c3-11e8-90bd-a0890a3b2db9.png)
hi，dear big  brother, can you help me ? why

**Comment by EWSoftware** [comment]
It's missing the code block component for some reason.  You might try uninstalling and reinstalling in case something is corrupted or missing.  The information at the start of the build log will tell you where it found the tools.  You might check that info to see if it's looking in the right place.

**Comment by EWSoftware** [comment]
Like I said, start with the top of the log file.  It will tell you where it's looking for the components.

**Comment by wj60387** [comment]
> Like I said, start with the top of the log file. It will tell you where it's looking for the components.

![image](https://user-images.githubusercontent.com/20125752/47470976-cc2cf000-d83a-11e8-9e2c-2b08835d147f.png)
You mean these paths, the first is the shfb project directory, I'm not installing shfb, so the directory does not exist, the third is the source code compilation path, but also the SHFBROOT environment variable pointed to the directory, so, where is the problem.

**Comment by wj60387** [comment]
Amazing issues, amazing project, great author.thank you.

**Comment by EWSoftware** [comment]
If you installed the tools with the [guided installer](https://github.com/EWSoftware/SHFB/releases), they'd typically be in the Program Files folder and it would define and set the environment variable.  It looks like you perhaps downloaded the source and built the tools so in that case you would have to [manually set the SHFBROOT environment variable](https://github.com/EWSoftware/SHFB/wiki/System-Requirements-and-Building-the-Code#running-shfb-and-the-sandcastle-tools-with-the-source-code-version).
