### ISSUE TITLE
BuildAssembler WriteDocuments function hitting PathTooLongException causing the build to fail.

### ISSUE THREAD

**Issue by squid-man** [EWSoftware/SHFB#656]
I am unable to built Website (HTML/ASP.NET) documentation due to a PathTooLongException coming from the SaveComponent.WriteDocuments method of the BuildAssembler.

Here is an example of the error I see in the logs:
`BuildAssembler : error : SaveComponent: [M:Very.Long.Nested.Namespaces#LongClassName#LongInterfaceName#LongExplicitMethodImplementation()] An access error occurred while attempting to save to the file &#39;VeryVeryLongFullyQualifiedPath.htm&#39;. The error message is &#39;The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.&#39;`

Win32 long paths are enabled in the OS, however, it appears that the BuildAssembler is targeting .NET Framework 4.5 which does not support long paths.  Can a fix be made to have the BuildAssembler target .NET Framework 4.6.2 or greater?  This is the first version where they _fixed the 260 character (MAXPATH) file name length limitation in the System.IO APIs_.  The same request goes for the EWSoftware.SHFB NuGet package.

see https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/

**Comment by EWSoftware** [comment]
There are no plans to have the tools target to .NET 4.6.2 yet.  For now, use the Working Files Path property and, if necessary, the Help Content Output Path property in the Paths category to move the working folder and output folders to a location closer to the root.
