### ISSUE TITLE
MathML in Topics

### ISSUE THREAD

**Issue by SergeyZhurikhin** [EWSoftware/SHFB#657]
Hi Eric! How can I use MathML tags in reference content? I imagine this through the connection of the script, for example, this 
http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML 
as in the example: http://latex.userpage.fu-berlin.de/math.html
How to connect the script to reference content?

**Comment by EWSoftware** [comment]
There's a build component that inserts additional resources into the topics such as stylesheets and scripts.  The easiest approach would be to [create a plug-in](http://ewsoftware.github.io/SHFB/html/a14e026e-642f-4ce6-9506-341e57cc3d1f.htm) that runs just before the BuildAssembler step that modifies the BuildAssembler configuration file (sandcastle.config in the working folder) by inserting an extra script element into the Additional Header Resources Component configurations.  There are multiple instances, one for each output format in each section for conceptual and API topics.  It would also need to  copy the required script to the output folder.

I can provide more details if you want to pursue this.

**Comment by SergeyZhurikhin** [comment]
I expected that such a plug-in is already there...

**Comment by EWSoftware** [comment]
Somebody might have done but I'm not aware of any.
