### ISSUE TITLE
2017.1.28 VSIX installer does not install builder template

### ISSUE THREAD

**Issue by Spearman47** [EWSoftware/SHFB#658]
When trying to open a new VS Project the Documentation template does not include the builder.  See attached.
![shfbtemp](https://user-images.githubusercontent.com/45330276/48978308-93826f80-f0a1-11e8-9454-3c6c9a319eee.png)

**Comment by EWSoftware** [comment]
Look at the root level for the Documentation category that contains the documentation project templates.  The ones under C# and VB are for the components as shown in the screenshot.  If you don't see it at the root level, try removing and reinstalling it.

**Comment by Spearman47** [comment]
Thank you for your reply.  After uninstall and re-install, I now see the Documentation folder at root level. Sorry to have troubled you.
