### ISSUE TITLE
SHFB : warning BHT0001- Microsoft.Build.Execution.ProjectInstance can't changed (4.0.0.0 => 14.0.0.0)

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#659]
I get following warnings from SHFB:

```
"C:\_Storage\Projects\Siemens.DE.SqlServer.Extensions\Siemens.DE.SqlServer.Extensions.shfbproj" (Standardziel) (1) ->
  (CoreBuildHelp Ziel) -> 
SHFB : warning BHT0001: Unable to get executing project: [A]Microsoft.Build.Execution.ProjectInstance kann nicht in [B]Microsoft.Build.Execution.ProjectInstance umgewandelt werden. Der Typ "A" stammt von der "Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" im Kontext "Default" am Speicherort "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.dll".. Der Typ "B" stammt von der "Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" im Kontext "Default" am Speicherort "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build\v4.0_14.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.dll"...  The specified project will be loaded but command line property overrides will be ignored. [C:\_Storage\Projects\Siemens.DE.SqlServer.Extensions\Siemens.DE.SqlServer.Extensions.shfbproj]
SHFB : warning BHT0001: Unable to get executing project:  Unable to obtain matching project from the global collection.  The specified project will be loaded but command line property overrides will be ignored. [C:\_Storage\Projects\Siemens.DE.SqlServer.Extensions\Siemens.DE.SqlServer.Extensions.shfbproj]
```

Project was first created in VS 2010, now using VS 2015 and using SHFB 2018.7.8.0 to build. How can it fixed? Help file is OK.

**Comment by EWSoftware** [comment]
The `ToolsVersion` attribute on the `Project` element is probably set to "4.0".  Change it to "12.0" or "14.0" and it should be okay.  If you open the project in Visual Studio, make a change to one of the project properties and save it, it should update it automatically.  If not, you can open it in a text editor and do it.

**Comment by VBWebprofi** [comment]
I've done this on SHFB project file, changed to 14.0 but didn't solve the problem. That's why opened this issue.

**Comment by EWSoftware** [comment]
Are you building it from within Visual Studio or from the command line?  If from the command line, are you using at least MSBuild 14.0?

**Comment by VBWebprofi** [comment]
Ok, think I got the right hint. Doing it with command line from at post build event in VS 2015. Where ist the 14.0 MSBuild normally located?

**Comment by EWSoftware** [comment]
MSBuild 14.0 can be found in *%ProgramFiles(x86)%\MSBuild\14.0\Bin*.  For VS 2017 and later, it can be found in the Visual Studio installation folder (*%ProgramFiles(x86)%\\Microsoft Visual Studio\\[Year]\\[Edition]\\MSBuild\15.0\Bin* replacing [Year] and [Edition] with the release year and edition of Visual Studio (Community, Professional, Enterprise).

**Comment by VBWebprofi** [comment]
OK, thanks for advice, found path ``C:\Program Files (x86)\MSBuild\14.0\Bin`` on my private computer and try to check this on my business computer tomorrow.

**Comment by VBWebprofi** [comment]
Both working.
