### ISSUE TITLE
Error BE0043: System.InvalidCastException: Specified cast is not valid

### ISSUE THREAD

**Issue by jjpepper** [EWSoftware/SHFB#661]
Hi there,
I have a BE0043 error and the last step in the build log contains:
```MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidCastException: Specified cast is not valid. [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiFilter.IsEditorBrowsable(AttributeList attributes) [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiFilter.IsExposedMember(Member member) [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ExtensionMethodAddIn.RecordExtensionMethods(XmlWriter writer, Object info) [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.StartElementCallbacks(String name, Object info) [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespaces(NamespaceList spaces) [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis() [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [C:\Users\JessePepper\source\repos\mi-messaging-framework\mi-messaging-framework\Help\Working\GenerateRefInfo.proj]
```

Any suggestions on this?

**Comment by EWSoftware** [comment]
It's having a problem with an EditorBrowsableAttribute value.  I'm not sure why.  Can you provide an example that duplicates the issue?

**Comment by EWSoftware** [comment]
Closing due to lack of response.  If you can supply an example, feel free to reopen it.

**Comment by EWSoftware** [comment]
I ran across this issue by accident when testing some other changes.  It happens in .NET Standard projects and is caused MRefBuilder not using netstandard.dll as the system assembly for the core types.  It's fixed for the next release.

**Comment by jjpepper** [comment]
Ok, cool. Thanks for letting me know

**Comment by Soruk** [comment]
Hi,

I have just installed the latest version of SHFB (2019.4.7.0) and I have the above / following error in some of my other projects:
`
 Using automatic redirect 'System.ObjectModel, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in place of 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidCastException: Specified cast is not valid. [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiFilter.IsEditorBrowsable(AttributeList attributes) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiFilter.IsExposedMember(Member member) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MemberDictionary..ctor(TypeNode type, ApiFilter filter) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteTypeElements(TypeNode type) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.WriteType(TypeNode type) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitType(TypeNode type) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitTypes(TypeNodeList types) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespace(Namespace space) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespace(Namespace space) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitNamespaces(NamespaceList spaces) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.ManagedReflectionWriter.VisitNamespaces(NamespaceList spaces) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.Reflection.ApiVisitor.VisitApis() [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MRefBuilderCore.Main(String[] args) [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
MRefBuilder : error :    at Microsoft.Ddue.Tools.MSBuild.MRefBuilder.Execute() [D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj]
Done Building Project "D:\DEV\SOURCES\LIB\Athic_WinControls\trunk\Documentation\Athic_WinControls.Lib.Documentation\Help\Working\GenerateRefInfo.proj" (default targets) -- FAILED.
`

I passed some time to try to figure out what is wrong but I have no clue :(

**Comment by Soruk** [comment]
Hi again,

I have just spotted that there is a new version (2019.4.14.0) and I have just installed it.
And now it is working :)
