### ISSUE TITLE
Separating Enumerations and Interfaces - how was this done?

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#662]
I'm attempting to bring a 2006/2007 version of Sandcastle-generated docs up to the current version.  For one assembly, the members are grouped by enumerations and interfaces:
![example of grouping by enumerations and interfaces](https://i.imgur.com/Wxhjccg.png)

Is there an option to automatically do this that I'm missing?

Thanks,
Glenn

**Comment by EWSoftware** [comment]
What presentation style were you using?  Two were deprecated and subsequently removed (Prototype and Hana).  The remaining two, VS2010 and VS2013, more closely resemble the MSDN content at the time they were created which doesn't group them that way anymore.

**Comment by glenncarr** [comment]
VS2013.  That makes sense then.  Thanks for the quick response.
