### ISSUE TITLE
cannot build from command line v2 2017 2018.12 version

### ISSUE THREAD

**Issue by jmecosta** [EWSoftware/SHFB#664]
d:\prod\fabsuitedocgenerator\packages\EWSoftware.SHFB.2018.12.10\tools\SandcastleHelpFileBuilder.targets(40,3): error MSB4062: The "SandcastleBuilder.Utils.MSBuild.
BuildHelp" task could not be loaded from the assembly d:\prod\fabsuitedocgenerator\packages\EWSoftware.SHFB.2018.12.10\tools\packages\EWSoftware.SHFB.2018.12.10\tools
\SandcastleBuilder.Utils.dll. Could not load file or assembly 'file:///d:\prod\fabsuitedocgenerator\packages\EWSoftware.SHFB.2018.12.10\tools\packages\EWSoftware.SHFB
.2018.12.10\tools\SandcastleBuilder.Utils.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is corr
ect, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [d:\prod\fab
suitedocgenerator\TeklaFabSuiteAPI_Reference.shfbproj]

**Comment by EWSoftware** [comment]
It looks like you're using the NuGet package deployment.  You probably haven't set the SHFBROOT property so it can't find the tools. See the [XCOPY/NuGet topic](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) for more information.  Also, make sure you're using MSBuild 14.0 or later.

**Comment by jmecosta** [comment]
nah, thats all fine. im using vs 2017 developer command prompt. Can it be some msbuild framework issue?

**Comment by EWSoftware** [comment]
The path to the targets file is in the .\packages folder.  That means it is trying to use the NuGet package version of SHFB.  Without a valid path, it probably isn't finding everything it needs.  Perhaps if you've got a newer release of the package and and older installed version it's finding the environment variable SHFBROOT and trying to load older copies of the assemblies.
