### ISSUE TITLE
Documenting Code-Behind Leads To [Missing <summary> documentation for "N:MyApp.Views"]

### ISSUE THREAD

**Issue by jeansusgodney** [EWSoftware/SHFB#665]
I am currently documenting the ViewModel and the code behind of my UWP app. 

After built: the help file shows [Missing <summary> documentation for "N:MyApp.xxx"] instead of the summary. This is how I commented the codebehind and view model

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /// <summary>   A ViewModel for the detail page. </summary>
    ///
    /// <remarks>   Admin, 02.01.2019. </remarks>
    ////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by EWSoftware** [comment]
The "N:" prefix indicates that it's missing namespace comments.  Namespace comments are not the same as type and member comments.  They are added using either the Namespace Summaries option in the [Summary category](http://ewsoftware.github.io/SHFB/html/eb7e1bc7-21c5-4453-bbaf-dec8c62c15bd.htm) of project properties or a [NamespaceDoc class](http://ewsoftware.github.io/SHFB/html/48f5a893-acde-4e50-8c17-72b83d9c3f9d.htm).

**Comment by jeansusgodney** [comment]
Hi thanks for the quick reply. It turns out I forgot to generate the XML Documentation file from the UWP project, basically sandcastle can't see any xml comment that I put in the project.
