### ISSUE TITLE
OpenXML output does not work with current versions of Word

### ISSUE THREAD

**Issue by sixlettervariables** [EWSoftware/SHFB#667]
The following problems are found in the OpenXML output when loaded in a recent version of Word:
1. The order of elements matters per the Open XML schema, but this is not always respected.
    - `w:ind` and `w:contextualSpacing`
    - `w:rPr` elements
2. Certain elements are not wrapped in the correct parent element.
    - `w:drawing` and `w:br` were not within `w:r`
    - `w:tbl` was sometimes within `w:p`
3. Certain attributes no longer exist in the Open XML schema and have new values.
    - `w:cnfStyle`'s `w:firstRow` attribute is now part of a bitmask attribute `w:val`
4. Certain required elements are missing.
    - `w:tbl` did not have `w:tblGrid` and its `w:gridCol` elements

[OpenXmlValidator](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.validation.openxmlvalidator?view=openxml-2.8.1) was used to discover these issues.

**Comment by EWSoftware** [comment]
The changes have been merged.  Thanks.
