### ISSUE TITLE
SHFB: Error BE0065: BUILD FAILED: Access to the path &#39;D:\System Volume Information&#39; is denied.

### ISSUE THREAD

**Issue by jaydeept** [EWSoftware/SHFB#670]
I am trying to generate the document for my project which is based on **.Net Core 2.2**. In my project I am using a package called **Postsharp**. Initially I was getting an error that reference assembly Postsharp couldn't be found. I then added reference of Postsharp in my shfbproj file like below:
```
<ItemGroup>
    <Reference Include="PostSharp">
      <HintPath>..\packages\postsharp.redist\6.0.32\lib\netstandard2.0\PostSharp.dll</HintPath>
    </Reference>
</ItemGroup>
```

And after that I got below error at the step: `<buildStep step="CompilingHelpFile">`

```
SHFB: Error BE0065: BUILD FAILED: Access to the path &#39;D:\System Volume Information&#39; is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.GatherBuildOutputFilenames()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

**Comment by EWSoftware** [comment]
It looks like your sending the output to the root folder.  It's trying to scan the output folder for the build output and is searching all directories below the output folder.  Change the output location to a subfolder or just clear the property and let it use the default location under the project folder.

**Comment by jaydeept** [comment]
I needed to give permission to "System Volume Information" folder inside D drive.

**Comment by EWSoftware** [comment]
No, permission isn't needed.  Like I said, move the project to a subfolder so that it doesn't scan everything from the root on down.
