### ISSUE TITLE
Sandcastle build fails when a ValueTuple is on the public API

### ISSUE THREAD

**Issue by bsstahl** [EWSoftware/SHFB#672]
As soon as a ValueTuple is on the public API of a method that Sandcastle is trying to interrogate, the build process fails.  I have uploaded a Gist containing a very simple sample class that exhibits the problem and the LastBuild.log file for a build of that class.  I can make a public repo of the full solution if you prefer. The Gist can be found at: https://gist.github.com/bsstahl/be0a0b8927c27892f3b8cd6fa39a9996

**Comment by EWSoftware** [comment]
I tried your example and it worked for me although I get a lot fewer NETSDK1041 warnings.  What version of Visual Studio 2017 are you using?  I'm using version 15.9.6.  Can you attach or send me and example that you've created that fails?  There could be something in the library project settings that I'm not duplicating.

**Comment by bsstahl** [comment]
I'm on Visual Studio Professional 15.9.6.  A full solution using the example in the gist can be found in this repo: https://github.com/bsstahl/Sandcastle_672.  I hope it helps.  If it still works for you and you want to do a remote debugging session from my machine to see what is going on, just let me know.

**Comment by EWSoftware** [comment]
The test case works for me.  The only real difference I see is in the path to the reference assemblies.  I'm not sure why that is but using the path didn't make a difference either.  Are you using the latest release of SHFB?  If not, you might try upgrading to see if it resolves the issue.

**Comment by EWSoftware** [comment]
This issue may be resolved with changes I've just made to fix other issues related to how it was including mscorlib.dll, netstandard.dll, and System.Runtime.dll in the reference assemblies passed to MRefBuilder.  The new release will be available soon.
