### ISSUE TITLE
Sandcastle Help File Builder GUI Tool cannot resolve property for version when using Assembly Binding Redirection Plugin

### ISSUE THREAD

**Issue by Delpire** [EWSoftware/SHFB#675]
I am trying to use the Assembly Binding Redirection Plugin in with the Sandcastle Help File Builder GUI tool.  Inside of my shfbproj I have the following:

```
<MyAssemblyLatestVersion>2.0.0.0</MyAssemblyLatestVersion>

<PlugInConfig id="Assembly Binding Redirection" enabled="True">
  <configuration useGAC="false">
    <assemblyBinding>
      <dependentAssembly>
        <assemblyIdentity name="My.Assembly" />
        <bindingRedirect oldVersion="1.0.0.0" newVersion="$(MyAssemblyLatestVersion)" /> 
      </dependentAssembly>
     </assemblyBinding>
  </configuration>
</PlugInConfig>
```

When I build from the command line using MSBuild, I get no errors, and everything is resolved correctly. But if I open the shfbproj in the Sandcastle Help File Builder GUI, not only can I not configure the plugin, but it is not even letting me build!

**Comment by EWSoftware** [comment]
The plug-in doesn't handle variables in the version number properties so it's trying to convert the string to a version value and failing.  It works when ran from the command line since MSBuild is substituting the value for the variable reference before it gets loaded by the build engine.  That doesn't happen when the GUI or Visual Studio builds the project thus the build fails.

The plug-in will need to be updated to handle variables rather than hard-coded version values.

**Comment by Delpire** [comment]
Just to add some info, it looks like <HelpFileVersion> works just fine with property variables. I think this confirms its on the plug in side.

**Comment by Delpire** [comment]
Nevermind. The previous comment is incorrect and I deleted it. HelpFileVersion also does not work with property variables.

**Comment by EWSoftware** [comment]
You can use the substitution format for things like the help file version property to insert other variables or project property values.  For example `{@Major}.{@Minor}.{@Build}.{@Revision} Beta`

Here's something else I'd forgotten that may help.  Somebody else did something similar using dynamic properties set through a custom build task.  It's documented in the [Using Dynamic Properties](http://ewsoftware.github.io/SHFB/html/76eb8f39-b225-4881-afa2-13cb7829b944.htm) help topic.  That doesn't fix the configuration dialog for the plug-in but should allow the other stuff to work.

**Comment by EWSoftware** [comment]
I've added support for variables in the plug-in configuration.  However, it requires the substitution tag format rather than the MSBuild variable format to reference them in the configuration values (`{@MyAssemblyLatestVersion}` rather than `$(MyAssemblyLatestVersion)`.
