### ISSUE TITLE
Unable to generate markdown

### ISSUE THREAD

**Issue by NN---** [EWSoftware/SHFB#676]
I have project file with the following but while compiling I get html file as output instead of markdown files.

```xml
 <HelpFileFormat>Markdown</HelpFileFormat>
<PresentationStyle>Markdown</PresentationStyle>
```

**Comment by EWSoftware** [comment]
The output is not pure markdown there will be a mix of HTML and markdown.  The API topics are just too complicated to render as pure markdown.  The files will have a .md extension and are valid since markdown files can themselves contain HTML.

**Comment by NN---** [comment]
The problem is that I get HTML extensions and not md.
I compile using MSBuild command line.

**Comment by EWSoftware** [comment]
If the properties are specified correctly, that's not possible.  Have you tried using Visual Studio or the Standalone GUI?  Have you checked the property settings in either of those to make sure they are valid?  If you've been making changes to the project file content by hand or creating one from scratch in an editor, it may not be valid.  Using the property pages in the standalone GUI or Visual Studio will ensure they are saved properly.

**Comment by NN---** [comment]
This is the project file: https://github.com/rsdn/CodeJam/blob/master/CodeJamDoc.shfbproj

**Comment by EWSoftware** [comment]
I downloaded and built your projects and ran MSBuild 15.0 from the command line to build CodeJamDoc.sln and also CodeJamDoc.shfbproj.  Both resulted in markdown output.  I also built the solution with Visual Studio and got markdown output.  What are you running from the command line to build it?

**Comment by NN---** [comment]
Sorry, my bad. :-/
I just looked in the incorrect place.
Thank you for help !
