### ISSUE TITLE
Control Add/Not add classes in the help file from source code file

### ISSUE THREAD

**Issue by dmitrybv** [EWSoftware/SHFB#679]
In Sandcastle Help File Builder (SHFB) Is it possible to control Add/Not add classes in the help file from source code file?

For example, remove classes from help file for classes that doesn't have <summary> comments.

I can use API Filter in Help File Builder. But keeping track of data in a large class tree in the API Filter dialog is deadly boring. 
It would be convenient to mark \ unmark classes (methods, properties) directly in the source files using attributes or special comments.

**Comment by EWSoftware** [comment]
You can use the [exclude](http://ewsoftware.github.io/XMLCommentsGuide/html/a8ade450-e201-401a-923d-1a1169ef7828.htm) XML comment element to exclude unwanted types and members.  It gets translated into an API filter entry.

If you want to exclude anything that isn't documented, you can also try the [Documented Entities Only plug-in](http://ewsoftware.github.io/SHFB/html/1c05f8f0-71f3-420a-b546-a438c435b759.htm).  However, note that it will include types if any members are documented and not excluded.

**Comment by dmitrybv** [comment]
Thanks Eric.
These features completely cover my needs.
