### ISSUE TITLE
syntaxSection does not display in developerXmlReference

### ISSUE THREAD

**Issue by mjanulaitis** [EWSoftware/SHFB#68]
I am trying to document an XML file and the auto generated file does not display the content.

Neither the 'Syntax section title' or the 'Syntax content' displays.  I added a reference to a code snippet and that didn't display either.

**Comment by EWSoftware** [comment]
It's a [known issue](http://ewsoftware.github.io/MAMLGuide/html/b00070c7-9c5e-4b49-ad5c-f55fa866f062.htm).  Several element types for the Whitepaper and XML Reference document types don't render as they aren't present in the presentation styles.  There's been no interest in them so they've never been added.

If your goal is to document an XML schema, try using the [XML Schema Documentation Plug-in](https://github.com/terrajobst/xsddoc) as it will take care of generating the topics based on the schema.

If it's just a general XML file, I'd suggest a general conceptual topic type and use code elements to show any necessary syntax examples.

**Comment by mjanulaitis** [comment]
Thanks for the info.  I got it working now.  I thought I was going crazy.
