### ISSUE TITLE
Cannot install SHFB Visual Studio Package

### ISSUE THREAD

**Issue by sagunpandey** [EWSoftware/SHFB#680]
I received an error while installing the package. 

![capture](https://user-images.githubusercontent.com/3306020/53768771-c8277380-3ea7-11e9-9cfb-b87ae849af82.PNG)

This is my Visual Studio version -

![capture2](https://user-images.githubusercontent.com/3306020/53769199-2a34a880-3ea9-11e9-868c-37768e4fe396.PNG)

Here's the install log:

3/4/2019 10:43:19 PM - Microsoft VSIX Installer
3/4/2019 10:43:19 PM - -------------------------------------------
3/4/2019 10:43:19 PM - vsixinstaller.exe version:
3/4/2019 10:43:19 PM - 15.0.26228.57 built by: D15RTWSVC
3/4/2019 10:43:19 PM - -------------------------------------------
3/4/2019 10:43:19 PM - Command line parameters:
3/4/2019 10:43:19 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe,C:\Users\venio_svc\Downloads\SHFBInstaller_v2018.12.10.0\InstallResources\SHFBVisualStudioPackage_VS2015AndLater.vsix
3/4/2019 10:43:19 PM - -------------------------------------------
3/4/2019 10:43:19 PM - Microsoft VSIX Installer
3/4/2019 10:43:19 PM - -------------------------------------------
3/4/2019 10:43:19 PM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
3/4/2019 10:43:20 PM - Initializing Install...
3/4/2019 10:43:20 PM - Extension Details...
3/4/2019 10:43:20 PM - 	Identifier         : c997d569-ee8e-4947-a46f-9a0717ce39a0
3/4/2019 10:43:20 PM - 	Name               : SHFB
3/4/2019 10:43:20 PM - 	Author             : EWSoftware
3/4/2019 10:43:20 PM - 	Version            : 2018.12.10.0
3/4/2019 10:43:20 PM - 	Description        : Visual Studio integration for the Sandcastle Help File Builder.
3/4/2019 10:43:20 PM - 	Locale             : en-US
3/4/2019 10:43:20 PM - 	MoreInfoURL        : https://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm
3/4/2019 10:43:20 PM - 	InstalledByMSI     : False
3/4/2019 10:43:20 PM - 	SupportedFrameworkVersionRange : [4.5,)
3/4/2019 10:43:20 PM - 
3/4/2019 10:43:20 PM - 	SignatureState     : Unsigned
3/4/2019 10:43:20 PM - 	Supported Products : 
3/4/2019 10:43:20 PM - 		Microsoft.VisualStudio.Community
3/4/2019 10:43:20 PM - 			Version : [14.0,17.0)
3/4/2019 10:43:20 PM - 
3/4/2019 10:43:20 PM - 	References         : 
3/4/2019 10:43:20 PM - 	Prerequisites      : 
3/4/2019 10:43:20 PM - 		-------------------------------------------------------
3/4/2019 10:43:20 PM - 		Identifier   : Microsoft.Component.MSBuild
3/4/2019 10:43:20 PM - 		Name         : MSBuild
3/4/2019 10:43:20 PM - 		Version      : [15.0,)
3/4/2019 10:43:20 PM - 
3/4/2019 10:43:20 PM - 		-------------------------------------------------------
3/4/2019 10:43:20 PM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
3/4/2019 10:43:20 PM - 		Name         : .NET desktop development tools
3/4/2019 10:43:20 PM - 		Version      : [15.0,)
3/4/2019 10:43:20 PM - 
3/4/2019 10:43:20 PM - Signature Details...
3/4/2019 10:43:20 PM - 	Extension is not signed.
3/4/2019 10:43:20 PM - 
3/4/2019 10:43:20 PM - Searching for applicable products...
3/4/2019 10:43:20 PM - Found installed product - Global Location
3/4/2019 10:43:20 PM - Found installed product - Visual Studio Professional 2017 (2)
3/4/2019 10:43:20 PM - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\master.pkgdef

3/4/2019 10:43:20 PM - PKGDEF Information: Creating PkgDefCacheNonVolatile
3/4/2019 10:43:20 PM - PKGDEF Information: Double-checking master pkgdef file
3/4/2019 10:43:20 PM - PKGDEF Information: PkgDefManagement initialized
3/4/2019 10:43:20 PM - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

3/4/2019 10:43:20 PM - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

3/4/2019 10:43:20 PM - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.admin.pkgdef

3/4/2019 10:43:20 PM - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Users\venio_svc\AppData\Local\Microsoft\VisualStudio\15.0_01d68b93\Extensions

3/4/2019 10:43:20 PM - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions

3/4/2019 10:43:20 PM - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
3/4/2019 10:43:20 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
3/4/2019 10:43:20 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
3/4/2019 10:43:20 PM - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
3/4/2019 10:43:20 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
3/4/2019 10:43:20 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
3/4/2019 10:43:20 PM - PKGDEF Information: PkgDefManagement startup complete
3/4/2019 10:43:20 PM - The extension with ID 'c997d569-ee8e-4947-a46f-9a0717ce39a0' is not installed to Visual Studio Professional 2017 (2).
3/4/2019 10:43:20 PM - Found installed product - Visual Studio Build Tools 2017
3/4/2019 10:43:20 PM - System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by EWSoftware** [comment]
It looks like the VSIX installer itself is having problems getting version information on the installed copies of Visual Studio.  The best I can suggest is doing a repair on Visual Studio to see if that fixes the issue.
