### ISSUE TITLE
Relative link to a local file in the chm file.

### ISSUE THREAD

**Issue by dmitrybv** [EWSoftware/SHFB#681]
Hello
How to add Relative link to local file (or folder) in chm file.

I tried next code in aml file

        <para>
          <externalLink>
    		<linkText>/Demos/File1.Txt</linkText>
    		<linkUri>file:///../Demos/File1.Txt</linkUri>
		  </externalLink>
		</para>

		<para>
          <externalLink>
    		<linkText>/Demos/File1.Txt</linkText>
    		<linkUri>../Demos/File1.Txt</linkUri>
		  </externalLink>
		</para>

        <para>          
          <externalLink>
    		<linkText>EhLib\Demos (Folder)</linkText>
    		<linkUri>../Demos</linkUri>
		  </externalLink>
	   </para>

but it all doesn't work.

HelpNDoc allows to create such links.

**Comment by EWSoftware** [comment]
I'm not sure such links will work.  As I recall, both will be blocked by security settings in the help viewer since it's not really a good idea to let help files from an unknown source open files on the local file system.  I'd have to do some testing to be sure.

You can embed said files in the help file as content.  A local path would then open the file in the viewer as I recall.  I do have some examples of that using embedded video files.

**Comment by dmitrybv** [comment]
The next hack works in HTML Help Viewer to open Relative link.


```
<html>
...
<p class="rvps2"><a class="rvts20" onclick="relativelnk('../Hlp/ENG/EhLib Users Guide.doc')" style="cursor: hand">EhLib\Hlp\ENG\EhLib Users guide.doc</a></p>
...
</html>

```

Relative.js
```
function relativelnk(a)
{
  var b,c;
  b=location.href.search(/:/)==2?14:7;
  c=location.href.lastIndexOf("\\")+1;
  a="file:///"+location.href.substring(b,c)+a;
  location.href=a
};
```

Can I add JavaScript code and bind it to onclick event in Sandcastle ?

**Comment by EWSoftware** [comment]
You could probably use the `markup` element to embed the script in the pages that need it and use `markup` elements to insert the HTML links to the folders/documents.  Anything in them passes through to the rendered topic as-is.

**Comment by dmitrybv** [comment]
The implementation using the markup worked.
Thank you.

I used the following inserts.

Box 1, somewhere at the beginning of the file.

```
        <script type="text/javascript">
          function relativelnk(a)
          {
            var b,c;
            b=location.href.search(/:/)==2?14:7;
            c=location.href.lastIndexOf("\\")+1;
            a="file:///"+location.href.substring(b,c)+a;
            location.href=a
          };
        </script>

```

Box 2, in the right place text.

`        <a onclick="relativelnk('../readme.txt')" style="cursor: hand">readme.txt</a>
`


I wonder if it is possible to save the code in a separate file so that it is copied to the content for HtmlHelp1. Then it will be possible to refer to it by a short link.

<script type = "text / javascript" src = "scripts  / relativelnk.js"> </ script>

**Comment by EWSoftware** [comment]
You can add the script file to the project and change it's build action to Content.  It would then be included in the compiled help file as a resource.  If you put it in a *.\scripts* folder in the project, it will put it in the folder in the help content as well and you'll need to include that in the link.

**Comment by dmitrybv** [comment]
Hello
I set up to create a file \Help\Working\Output\HtmlHelp1\scripts\relativelnk.js.
This part works.

But about section in the aml file
	<markup>
	    <script type="text/javascript" src="../scripts/relativelnk.js"></script>
	</markup>
When I put this section in aml file, the output html file doesn't have closing "</script>" part. 
So the html file gets broken.

**Comment by EWSoftware** [comment]
You can try putting a non-breaking space in the script element or perhaps an empty comment.  That should prevent it from converted to a self-closing element.

**Comment by dmitrybv** [comment]
Yes, hack with making any data in script tag works.

```
	<markup>
	    <script type="text/javascript" src="../scripts/relativelnk.js">Empty</script>
	</markup>

```

**Comment by maettu-this** [comment]
Came across this issue while searching for a solution for the very same requirement, a **link to a local file**.

Tried the above described script and use of it, I didn't get it working. Maybe for some incompatibilty of HTML Help, or because javascript is not enabled in my case, or more likely because I didn't do everything right and there is no concluding summary of the solution, e.g. a complete example `.aml`.

However, within a Doxygen project, I found an alternative approach:
```
	<para>
		Refer to
		<markup>
			<object id="hhctrl" type="application/x-oleobject" classid="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11" codebase="hhctrl.ocx">
				<param name="Command" value="Shortcut"></param>
				<param name="Font" value="Segoe UI, 11pt"></param>
				<param name="Text" value="Text:SomeDocument.pdf"></param>
				<param name="Item1" value=",.\SomeDocument.pdf,"></param>
			</object>
		</markup>
		for whatever.
	</para>
```
There is a limitation though: The link is neither properly spaced nor aligned. Workaround:
```
	<para>For whatever, refer to:</para>
	<para>
		<markup>
			<object id="hhctrl" type="application/x-oleobject" classid="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11" codebase="hhctrl.ocx">
				<param name="Command" value="Shortcut"></param>
				<param name="Font" value="Segoe UI, 11pt"></param>
				<param name="Text" value="Text:SomeDocument.pdf"></param>
				<param name="Item1" value=",.\SomeDocument.pdf,"></param>
			</object>
		</markup>
	</para>
```
If either @EWSoftware or @dmitrybv see this, a comment on this alternative approach as well as a complete solution to the inital approach would be appreciated.

**Comment by maettu-this** [comment]
Note https://stackoverflow.com/questions/17223212/how-to-link-to-an-external-file-in-sandcastle that shows the javascript approach right within an `externalLink`.
