### ISSUE TITLE
Separate the <summary> and <remarks> sections into separate files.

### ISSUE THREAD

**Issue by dmitrybv** [EWSoftware/SHFB#682]
Is it possible to separate the `summary` and `remarks` sections into separate files?
I want to take `summary` from VS autogenerated file and take `remarks` section from other manual created file.
I don't want to put whole pile of `remarks` information in the source code.

So I created new file EhLib.WinForms.DetialHelpInfoData.xml 
and added `remarks` for classes like this

```
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>EhLib.WinForms</name>
    </assembly>
    <members>
        <member name="E:EhLib.WinForms.ProgressBarDataCellManager.FormatParamsNeeded">
        </member>
        <member name="T:EhLib.WinForms.DataAxisGridListAxisItemViewState">
            <remarks>
            For DataGridEh  
              Most of Rows have DataBrowse state. When Row position has a corresponding DataGridRow
                and DataGridRow is in Browse state.
                If DataGridRow is in edit mode then the state of Row position is DataEdit
                If DataGridRow is in append mode then the state of Row position is DataNew
              Row position where grid draws virtual new record has VirtualNew state. For this position the 
                DataGridRow is null.
            </remarks>
        </member>
        <member name="F:EhLib.WinForms.DataAxisGridListAxisItemViewState.DataBrowse">
        </member>
        <member name="T:EhLib.WinForms.BaseDataCellManager">
        </member>
    </members>
</doc>

```

then I added the file to the "Documentation Source" of the project add and rebuilded help file.
Builder did not add `remarks` from EhLib.WinForms.DetialHelpInfoData.xml to the .chm file.

**Comment by EWSoftware** [comment]
There are no provisions for merging comments from multiple sources.  What currently happens is that the last set seen for a matching member ID wins.  As such, you're most likely getting the remarks but not the summary elements.

One possible workaround is to use the [include](http://ewsoftware.github.io/XMLCommentsGuide/html/3de64a85-dafb-4a01-85dc-7f69a76ef790.htm) element in your file to import the summary elements from the auto-generated file.  Another option is to write a plug-in that does perform a full merge of all elements for member elements with a common ID.

**Comment by dmitrybv** [comment]
I am thinking about writing a separate program that will merge two doc xml files into one.
And then run this program as Pre-build event in Help File Builder.
