### ISSUE TITLE
在仅只有vs2017的环境中无法使用

### ISSUE THREAD

**Issue by exy3351** [EWSoftware/SHFB#683]

**Comment by EWSoftware** [comment]
Translating the title only gets me "Not available in vs2017 only environments" which isn't much to go on.  Can provide more details?  What problem are you having specifically?

**Comment by exy3351** [comment]
只安装了vs2017，在打开sandcastle是提示错误“未能加载文件或程序集microsoft.build, version =14.0.0.0 ...”,即要求安装vs2015，点击继续后可以打开，不无法进行编译，若创建好的工程用vs2017打开也无法编译

**Comment by exy3351** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 SandcastleBuilder.Gui.MainForm.CloseProject()
   在 SandcastleBuilder.Gui.MainForm.miNewProject_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by EWSoftware** [comment]
If you are using the standalone GUI, it requires the MSBuild Tools 2015 to be installed (see the [installation instructions](http://ewsoftware.github.io/SHFB/html/8c0c97d0-c968-4c15-9fe9-e8f3a443c50a.htm)).  If you have VS 2017, you're better of using that as it will work with the Visual Studio project system and there's no need to use the standalone GUI.

**Comment by exy3351** [comment]
几次安装都提示“Unexpected exit code returned from vsix installer trying to uninstall any prior version of the package :-532462766”,点击确定后，点击next继续安装完成后，GUI和vs都用用不了，在单独安装“SHFBVisualStudioPackage_VS2015AndLater.vsix”也不行，请问是否有计划升级到直接基于vs2017而不是基于vs2015？

**Comment by EWSoftware** [comment]
Sorry, the translation's not that good so I can't get a good idea of what you are asking.  The latest release of the package already works with VS2015, VS2017, and VS2019.  I'd suggest running each version of Visual Studio in which you want it installed and make sure that a prior version of the SHFB extension is not already installed.  If it is, remove it manually in Visual Studio and restart it to make sure it is gone.  Once gone, run the VSIX installer manually to install the package.

Based on the error code, another problem may be that you need to run the install as an administrator.  It does install for all users and does require admin rights to do so.  If you run the guided installer, it will prompt to elevate permissions.  If you want to run the VSIX manually, you'll need to run VSIXInstaller.exe and use the /admin option.

**Comment by exy3351** [comment]
I'm trying. I'll close the question first. If I have any questions, I'll consult you later.
