### ISSUE TITLE
Is there a way to just list all classes regardless from which namespace they come from?

### ISSUE THREAD

**Issue by mabue110** [EWSoftware/SHFB#684]
I "just" want to list all classes but they are coming from 2 different namespaces and changing the source code is not a possible solution. I tried to modify the VS2013 Presentation Style, but first Im not sure if Im doing it right:

I created a Presentation Style like its explained in the sandcastle documentation, then copying all folders from VS2013 Style and including them in the solution. When I try to use the new Presentation Style via the shfb gui it doesnt find certain files so i copied everything into /bin/Debug and now it looks like its working(?).

Further I saw there is a Variable 'SupportsNamespaceGrouping' in the .cs file but if I set it to false nothing changes or at least its not solving my problem I guess(?)

So my conclusion is I need to do changes in the .xsl Files found in the 'Transforms' Folder but Im a bit overwhelmed. Do you know how/where to do the changes that are needed to list all classes on one page without mentioning the namespaces or is there a guide or something I can read about it?
Please help me, I have little to no experience with XSL.

**Comment by EWSoftware** [comment]
Types are always grouped by namespace.  If what you are after is just a flat list of types in the TOC without any grouping, you'll need to change both the presentation style and also create a TOC transformation to use with it.  One doesn't exist that will do what you want so you'd have to create that from scratch.  The changes required would be rather extensive and you would need to be quite familiar with XSL to do it.
