### ISSUE TITLE
Unable to reference projects from .Net Core 2.2 ASP.Net Core generated solution

### ISSUE THREAD

**Issue by johnruck** [EWSoftware/SHFB#685]
This was with SHFB 2018.12.10.0 (which supposedly supports VS2019 format ...) - brand new SHFB project for a .Net Core 2.2 101 ASP.Net Core solution.  When I add in the csproj file I am getting an error saying "Incompatible Visual Studio project file format" and it may be for a newer version.  This was on Visual Studio 2017 15.9.9 (and I also have instazlled Build Tools 2017 15.9.9 as well).

I dont really see any version specific info in the csproj file, maybe the Project line value is new/unexpected?

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>

here are the documentation lines from the project

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>G:\git-base\SystemManagement\SystemManagementServer\SystemManagementServer\SystemManagementServer.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>G:\git-base\SystemManagement\SystemManagementServer\SystemManagementServer\SystemManagementServer.xml</DocumentationFile>
  </PropertyGroup>

**Comment by johnruck** [comment]
ok, I have a little more detail (finally was able to get SHFB to build from sources - silly sgen.exe error).  The error is coming from the throw at line 426 of MSBuildProject.cs.  The exception text is 

"The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format."

Project builds fine in Visual Studio, so I am guessing maybe this is a problem with the MSBuild libraries you are accessing possibly (I see you are using the Microsoft.Build.Evaluation code to parse the project files)?

**Comment by EWSoftware** [comment]
The standalone GUI doesn't support the newer project format as it uses an older version of MSBuild.  Install the Visual Studio package and use Visual Studio if you are using the newer .NET Core/Standard project format.

**Comment by johnruck** [comment]
Ok thanks. All of the examples I saw had the configuration done via the standalone tool - I didnt realize the same configuration functionality was available via the visual studio addin.  Thanks for the insight and a great tool!
