### ISSUE TITLE
Guided Installer only finds Visual Studios installed to C: drive

### ISSUE THREAD

**Issue by johnruck** [EWSoftware/SHFB#686]
Just an FYI ( I cleared off enough space on the C: drive to reinstall and got around the issue), while trying the guided installer, it fails to find Visual Studio 2017 Community (and I am guessing other variants) if it is not installed on the C: (my C: drive had an older VS 2017 Professional install that had expired, so I had installed the Community version to an F drive).  When it got to installing the MAML Schema Intellisense it doesnt find the Visual Studio installed to allow it to be installed.

Mainly adding this as a ticket in case somebody else runs into the issue of it not finding their Visual Studio install.

**Comment by EWSoftware** [comment]
It's a known issue.  As a workaround, the paths can be adjusted in the guided installer's configuration file or you can just run the MSI and VSIX installers manually.  There are topics in the help file for adding the MAML schemas to the Visual Studio cache if needed.
