### ISSUE TITLE
Create link to API Content inside the document

### ISSUE THREAD

**Issue by dmitrybv** [EWSoftware/SHFB#688]
Hello
How to create link to API Content inside the document.
I found ID of "API Content" topic in the Working\Output folder
It is ced9c140-b1bc-c4a9-9cc1-62653203a73d.htm

But link :

```
<para>          
           <link xlink:href="ced9c140-b1bc-c4a9-9cc1-62653203a73d" />
</para>
```

doesn't work.

**Comment by EWSoftware** [comment]
You need to use [codeEntityReference](http://ewsoftware.github.io/MAMLGuide/html/bc490dbf-7d46-432d-a816-3ae16ab6af54.htm) to link to an API topic.  You can use the [Entity References](http://ewsoftware.github.io/SHFB/html/e49eea91-a9ef-4aa5-ad8f-16ebd61b798a.htm) tool window to help find the available members and copy links for them to the clipboard for pasting into topics or you can drag and drop them from the result list.

**Comment by dmitrybv** [comment]
Thank you.
This code works
```
	    <para>          
	       <codeEntityReference >R:Project_EhLib-WinForms-Help</codeEntityReference>
	    </para>

```
