### ISSUE TITLE
TOC: Namespace or conceptual content but not both

### ISSUE THREAD

**Issue by KenBilling** [EWSoftware/SHFB#690]
I'm trying to build a project in VS 2015 that I've successfully built for several years and over numerous SHFB and VS upgrades. I also have VS 2017 installed but loading the project shows it as incompatible and returns 'The application is not installed' error so I'm using 2015, in which it builds successfully. I recently installed the latest SHFB release to no effect.

Even though the generated CHM file shows the full TOC and all content as expected, the website output will contain either the conceptual content or the namespace content but not both depending on the **Conceptual content placement** setting in the project properties or the **API Content** setting of the sibling conceptual content topic. If I place the namespace before the conceptual content, I only get the namespace. If I place the namespace after the conceptual content, I only get the conceptual content.

The WebTOC.xml file contains both branches but only the first one is visible in the output:
<HelpTOC>
  <HelpTOCNode> Conceptual content
  <HelpTOCNode> Namespace
<HelpTOC>

I'm trying to produce a simple layout with the conceptual content parallel to the namespace:

Concept
  Concept
  Concept
Namespace

I must be overlooking something simple, right?

**Comment by EWSoftware** [comment]
Make sure when viewing the content you are using the "View Website (Local Web Dev Server)" option and not the "View Website (Local File System)" option as the scripts can get blocked when using the file system option.

**Comment by KenBilling** [comment]
I wasn't using either option but either View > View Help File > View Website (ASP.NET) in VS 2015 or viewing the published output shows the structure correctly.

Thanks, Eric!
