### ISSUE TITLE
Invalid warnings that enums are missing summary documentation for value_

### ISSUE THREAD

**Issue by kelly987654** [EWSoftware/SHFB#692]
After updating from v2018.7.8.0 to v2019.4.7.0, I'm seeing warnings that my enums are missing summary documentation for the 'value_'

`BuildAssembler : warning : ShowMissingComponent: [F:MyEnum.value__] Missing <summary> documentation [C:\repos\MyRepo\SandcastleDocumentation\Help\Working\BuildTopics.proj]	SandcastleDocumentation	C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets	40	`

It seems like Sandcastle is not resolving the enum type correctly anymore. I've copied below the differences in the generated documentation between the two versions:

v2018.7.8.0 (good)
![image](https://user-images.githubusercontent.com/31869394/55827120-5520a680-5abe-11e9-98e8-99f703b5f04e.png)

v2019.4.7.0 (bad)
![image](https://user-images.githubusercontent.com/31869394/55827059-2f939d00-5abe-11e9-98c4-264d383ba5cf.png)

Related to Resolved Issue #291

**Comment by EWSoftware** [comment]
Can you provide an example project that I can use to reproduce the problem?

**Comment by kelly987654** [comment]
I can't due to company policies, but I'll try to reproduce in a new example project.

Thanks!

**Comment by kelly987654** [comment]
Hi - thanks for looking! I was able to reproduce in the below example project. It seems the issue is happening in the Net Framework 4.7.1 project but not the Net Standard project.

![image](https://user-images.githubusercontent.com/31869394/55833242-1eea2380-5acc-11e9-83c9-0feca5b21a66.png)


[SandcastleIssueRepro.zip](https://github.com/EWSoftware/SHFB/files/3060859/SandcastleIssueRepro.zip)

**Comment by EWSoftware** [comment]
This was caused by mixing of .NET Standard and full .NET Framework assemblies.  MRefBuilder wasn't correctly redirecting the mscorlib reference to the netstandard assembly so it wasn't handling the core types like enum correctly.  A new release that fixes the issue will be available shortly.

**Comment by kelly987654** [comment]
Confirmed the issue is fixed with v2019.4.14.0, thank you!
