### ISSUE TITLE
Extra level of hierarchy in website TOC.

### ISSUE THREAD

**Issue by kfertitta** [EWSoftware/SHFB#695]
Sorry for the basic question here, but I'm trying to eliminate the extra level of hierarchy at the root of my website output.  I'd like to have just a single root node (or perhaps no root node, if ossible???).

 Any help is much appreciated.

See attached screenshots.

<img width="594" alt="TOC" src="https://user-images.githubusercontent.com/1080656/56040814-1a9c5100-5cec-11e9-8058-7acac47a7b41.png">

<img width="497" alt="TocSource" src="https://user-images.githubusercontent.com/1080656/56040842-3142a800-5cec-11e9-87c4-e3907d973073.png">

**Comment by EWSoftware** [comment]
There is no option to eliminate it.  Changes would probably have to be made to the lightweight website style plug-in to get rid of it since it is what generates the fragments that make up the TOC elements within each topic.

**Comment by kfertitta** [comment]
Hi Eric,

Thanks very much for taking the time to reply.  I understand.  The thing that I was curious about, though, is that i don't see this extra level in the Sandcastle web docs themselves:

http://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm

See, you have only a single root node.  I have two - one under the other.  I'd be happy if mine looked like yours.


<img width="418" alt="Untitled" src="https://user-images.githubusercontent.com/1080656/56099152-26d80800-5ebe-11e9-8eee-6960e0559151.png">

**Comment by EWSoftware** [comment]
If you're referring to the "Nimbus Driver Studio" entry in your TOC, that's there because you've structured it that way in your content layout file.  If you drag each of the child elements up and drop them on the root node, they'll become siblings of it rather than children and everything will then be in a flat list.  Start from the last child topic and work your way up so that you don't have to reorder them afterwards.

**Comment by kfertitta** [comment]
Bingo.  That did it.  Thanks very much.

This project has been around forever and I have a vague recollection that perhaps this was done intentionally to accommodate Help 1 .chm files and a need to have root node.  We're not generating .chm anymore and relying solely on web help.  Maybe you're taking care of rooting everything for us now in the web help, where we needed to do it explicitly a long time ago (like 15 years ago maybe).  Does any of that sound familiar, or has we just always had it "wrong"?

Thanks again.

**Comment by EWSoftware** [comment]
Help 2 might have needed it and MS Help Viewer does so that things don't end up in the root TOC in the Visual Studio help viewer.

**Comment by kfertitta** [comment]
Ah, yeah.  That's it then.  We also used to integrate with Help Viewer, but have dropped that as well.

Thanks again for your responsiveness here.
