### ISSUE TITLE
IOException when building a project with an obfuscated documentation source.

### ISSUE THREAD

**Issue by kfertitta** [EWSoftware/SHFB#698]
This occurs with the latest (2019-4-14) bits.  The attached screenshot shows the error and the build log is attached.
<img width="674" alt="Untitled" src="https://user-images.githubusercontent.com/1080656/56461843-259b5500-636e-11e9-890b-bb77d2686613.png">
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/3100563/LastBuild.log)

**Comment by EWSoftware** [comment]
Since a build output file is being used by another process and its well past the point of processing the assemblies, it's more likely that the build process is trying to access the output while its being scanned by a virus scanner and is getting blocked.  Excluding the build output and working folders from being scanned will work around it.

**Comment by kfertitta** [comment]
Hi Eric,

Thanks much for the quick reply.  I agree that it certainly sounds like something like that.  But this is 100% reproducible in an identical fashion on multiple machines -- dev boxes, cloud build VMs, local build VMs, etc.  I have an `msbuild` command switch to flip obfuscation on/off.  If I build with it off, it succeeds -- only takes 30 seconds to build.  If I build with it on immediately afterwards, it fails -- every time.

Now, the fact that it's a global property being passed in to control obfuscation seems to be a hint.  I get the same behavior if the documentation source is a project or if it's just the obfuscated DLL.  In either case, passing in the MSBuild property at the command line will make it fail.  

I've attached a binlog, if that's helpful.  Just change the file extension to binlog.

[msbuild.txt](https://github.com/EWSoftware/SHFB/files/3100654/msbuild.txt)

**Comment by EWSoftware** [comment]
The point its failing at it's trying to access the HTML files which you can see in the error message so it has nothing to do with the assemblies.  It could simply be a matter of timing that causes it to fail or not.  If you can reproduce it with a small example, I'll take a look at it but I don't expect to find anything.  As I suggested, try excluding the build and working folders from being scanned by any virus scanners you may have on the system.
