### ISSUE TITLE
ShowMissingComponent: [M:OSIsoft.AF.UnitsOfMeasure.UOMDatabase.GetWarnings(System.Void)] Missing <summary> documentation

### ISSUE THREAD

**Issue by sseemanosi** [EWSoftware/SHFB#699]
I am having an issue where after upgrading from VS 2017 to VS2019 and upgrading to Sandcastle v2019.4.14.0 I am getting a lot of

```
  C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:OSIsoft.AF.UnitsOfMeasure.UOMDatabase.GetWarnings(System.Void)] Miss
ing <summary> documentation 
  C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:OSIsoft.AF.UnitsOfMeasure.UOMDatabase.GetWarnings(System.Void)] Miss
ing <returns> documentation 
  C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(40,3): warning : BuildAssembler : warning : ShowMissingComponent: [M:OSIsoft.AF.UnitsOfMeasure.UOMDatabase.GetWarnings(System.Void)] Miss
ing <param name="cultureInfo"/> documentation
```
warnings.
However, the actual definitions of the methods the parameter types are not System.Void.

The XML comments are all properly defined in the source code and I have checked the generated XML and they appear correctly there as well.

I have also found that these warnings appear when building with the VS 2017 and VS 2019 versions of MSBuild, and do not appear when building through the stand alone UI or when using v14.0 of MSBuild.

These warnings also do not appear when using VS 2019 and the v2018.12.10.0 version of Sandcastle.

When using the newer versions of MSBuild the manifest.xml file in the Working directory contains the method signatures with the incorrect System.Void parameter type. When using the v14.0 MSBuild the parameter type appears correctly in this file.

**Comment by EWSoftware** [comment]
You've probably got the wrong framework version selected in the SHFB project.  Select the one that is appropriate to the documentation sources.  If you've got a mix (.NET Framework and .NET Standard for example), pick the Cross Platform option.

**Comment by sseemanosi** [comment]
I verified that I have the correct version of .NET selected and also tried using the Cross Platform option and I am still getting the warnings.

**Comment by EWSoftware** [comment]
Can you provide an example I can build to try and duplicate the issue?

**Comment by sseemanosi** [comment]
Sorry about taking a while to get back on this. After poking around some more I found that there were other issues with our .NET version and after resolving those using the Cross Platform option fixed our issue.

Thank you.
