### ISSUE TITLE
Support per-version setting of ripOldApis

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/SHFB#7]
_Moved from [CodePlex](https://shfb.codeplex.com/workitem/35474)_
_Originally submitted by sharwell_

I'm trying to use the Version Builder plugin for two purposes:
- For identifying supported versions of the .NET Framework (e.g. .NET Framework 3.5, 4.0, 4.5) 
- For identifying supported versions of the library (e.g. 1.0.0, 1.1.0, 1.1.1, 1.2.0)

For versions listed in the .NET Framework group, I want ripOldApis=false. For versions listed for old releases of the library, I want ripOldApis=true for all versions except for the current release.

 I have implemented this feature as part of the following pull request:
https://github.com/tunnelvisionlabs/SHFB/pull/76

_EWoodruff wrote Aug 29, 2014 at 11:07 AM_
Doesn't this change make the existing "rip" option which maps to the "/rip" command line option obsolete? Why would it still be needed? It seems confusing to still have both.

**Comment by sharwell** [comment]
> Doesn't this change make the existing "rip" option which maps to the "/rip" command line option obsolete? Why would it still be needed? It seems confusing to still have both.

The existing option would continue to have the same impact, which effectively applies ripOldApis to all versions, as opposed to only applying it to specific versions.

**Comment by EWSoftware** [comment]
So if it's true it overrides all version settings but if false, uses the version settings?  Like I said, seems confusing to have a global option that only works if enabled.  I think I'd rather see an option in the config dialog to toggle the state in all projects on and get the same effect or just remove it altogether.  For backward compatibility, the plug-in could look for the option and apply it accordingly.  If the configuration is later edited, the dialog could remove the old setting so that only the project settings are considered.

**Comment by sharwell** [comment]
Either way would be fine with me. I've never needed to set the option on all versions, so backwards compatibility would not be a concern. The reason I initially implemented it the way I did was based on minimal understanding of the manner in which other users might be using the Version Builder plugin.

**Comment by EWSoftware** [comment]
See pull request #47.  As noted there, feel free to re-open if an example can be supplied that demonstrates how the change affects this in relation to the existing global option.
