### ISSUE TITLE
Question: List all classes tagged with a specific (custom) tag

### ISSUE THREAD

**Issue by Micha4711** [EWSoftware/SHFB#70]
Is there a way to create a list of all classes tagged with a specific (custom) tag in a Sandcastle documentation?

I'm using a custom tag to mark specific behavior in my classes. I mapped this tag in main_conceptual.xsl and the content is shown at the documentation sheet of each class.

Now I want create a special page (as conceptual content?) in the documentation which shows a list of all classes which are tagged with my custom tag. Is there a possibility to do this using sandcastle help file builder(SHFB)? Perhaps in the .xsl transformations? Or using MAML?

**Comment by EWSoftware** [comment]
If you mean something in XML comments then no.  There isn't a way to generate a group topic and put it in the TOC like there is when generating stuff from the reflection information.

A plug-in is probably the best bet.  You could configure it by telling it what conceptual topic ID to use and in what section to put the list of classes using a section address.  The plug-in could search the XML comments files looking for the required element and insert either a list or a table containing the codeEntityReference link elements that would get converted to API member links.
