### ISSUE TITLE
Getting ShowMissingComponent on method with "in" parameter

### ISSUE THREAD

**Issue by Tape-Worm** [EWSoftware/SHFB#700]
So I tried building up some documentation for my project tonight, and I noticed that I keep getting this:
![image](https://user-images.githubusercontent.com/9710137/57005344-a2aba300-6b94-11e9-9a84-c548ae71988c.png)

I found that very strange because the code is indeed documented as you can see [here](https://github.com/Tape-Worm/Gorgon/blob/b9a079f1cdaaf29bd02215df848333ab8bf7c677/Gorgon/Gorgon.Core/_Interfaces/IGorgonEquatableByRef.cs#L49).

I made sure that the my project settings were set for the correct framework version (4.7.2):
![image](https://user-images.githubusercontent.com/9710137/57005388-eb635c00-6b94-11e9-820a-550b4b81a8d0.png)

Is the C# 7.2 support not working?

**Comment by EWSoftware** [comment]
Support for C# 7.2 language features was added in the latest release.  The test cases submitted with the pull request are working as expected but yours is different for some reason.  The attribute name is appended to the parameter in the method signature so it differs from the one in the XML comments file hence the mismatch.

A workaround for the time being would be to use the Member ID Fix-up Plug-In.  You can use it to replace the expression "Equals(\`0@" with  "Equals(\`0@|System.Runtime.InteropServices.InAttribute".  That should fix that specific case without breaking any other IDs in the comments file.

**Comment by Tape-Worm** [comment]
Awesome, I'll give that a try.  Thanks.

**Comment by Tape-Worm** [comment]
OK, so I tried it out and it cleared up most of the issues.

However, I'm still getting this:
`
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.CopyTo(Gorgon.Graphics.Imaging.IGorgonImageBuffer,System.Nullable{SharpDX.Rectangle}@,System.Int32,System.Int32)] Missing <summary> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.CopyTo(Gorgon.Graphics.Imaging.IGorgonImageBuffer,System.Nullable{SharpDX.Rectangle}@,System.Int32,System.Int32)] Missing <param name="buffer"/> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.CopyTo(Gorgon.Graphics.Imaging.IGorgonImageBuffer,System.Nullable{SharpDX.Rectangle}@,System.Int32,System.Int32)] Missing <param name="sourceRegion"/> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.CopyTo(Gorgon.Graphics.Imaging.IGorgonImageBuffer,System.Nullable{SharpDX.Rectangle}@,System.Int32,System.Int32)] Missing <param name="destX"/> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.CopyTo(Gorgon.Graphics.Imaging.IGorgonImageBuffer,System.Nullable{SharpDX.Rectangle}@,System.Int32,System.Int32)] Missing <param name="destY"/> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ResolveReferenceLinksComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.CopyTo(Gorgon.Graphics.Imaging.IGorgonImageBuffer,System.Nullable{SharpDX.Rectangle}@,System.Int32,System.Int32)] Unknown reference link target 'T:SharpDX.Rectangle'. [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.GetRegion(SharpDX.Rectangle@)] Missing <summary> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.GetRegion(SharpDX.Rectangle@)] Missing <returns> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Gorgon.Graphics.Imaging.GorgonImageBuffer.GetRegion(SharpDX.Rectangle@)] Missing <param name="clipRegion"/> documentation [D:\Mike\Code\GitHubRepos\Gorgon\WIP\Docs\Help\Working\BuildTopics.proj]
`

The method signatures are (these are fully commented I assure you):
```csharp
IGorgonImageBuffer GetRegion(in DX.Rectangle clipRegion)
void CopyTo(IGorgonImageBuffer buffer, in DX.Rectangle? sourceRegion = null, int destX = 0, int destY = 0);
```

I tried setting up another rule to handle this, but it doesn't seem to be working (I'm not very familiar with this plug in, so I probably didn't do it right).
