### ISSUE TITLE
Problem in Project .Net Core with generic List<T> as return value

### ISSUE THREAD

**Issue by kosday** [EWSoftware/SHFB#701]
We have problem generating documentation for method that return a value of type List<T>
We are using Sandcastle Help File Builder and Tools Version 2019.4.14.0
We have a .Net Core project. In this project we have a method what return a List<T> value.

```
    /// <summary>
    /// Test Class
    /// </summary>
    public class TestClas
    {
        /// <summary>
        /// Test Method
        /// </summary>
        /// <param name="arg1">This is arg1</param>
        /// <param name="arg2">This is arg2</param>
        /// <param name="arg3">This is arg3</param>
        /// <returns>A new List{T}</returns>
        public List<T> Test<T>(string arg1, string arg2, string arg3)
        {
            List<T> lst = new List<T>();
            return lst;
        }
    }
```

In the Build Output tab page we can see these warnings:

```
MRefBuilder : warning : Ignoring unresolved assembly reference: System.Collections (System.Collections, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) required by MyCoreProject [D:\Documents\SandCastle\Test DOC\Help\Working\GenerateRefInfo.proj]


BuildAssembler : warning : ShowMissingComponent: [M:Test.TestClas.Test``1(System.Void,``0,System.String)] Missing <summary> documentation [D:\DATOS\Documents\SandCastle\Test DOC\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Test.TestClas.Test``1(System.Void,``0,System.String)] Missing <typeparam name="T"/> documentation [D:\DATOS\Documents\SandCastle\Test DOC\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Test.TestClas.Test``1(System.Void,``0,System.String)] Missing <returns> documentation [D:\DATOS\Documents\SandCastle\Test DOC\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Test.TestClas.Test``1(System.Void,``0,System.String)] Missing <param name="arg1"/> documentation [D:\DATOS\Documents\SandCastle\Test DOC\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Test.TestClas.Test``1(System.Void,``0,System.String)] Missing <param name="arg2"/> documentation [D:\DATOS\Documents\SandCastle\Test DOC\Help\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:Test.TestClas.Test``1(System.Void,``0,System.String)] Missing <param name="arg3"/> documentation [D:\DATOS\Documents\SandCastle\Test DOC\Help\Working\BuildTopics.proj]

```

And this is the result of the chm doc file:

![image](https://user-images.githubusercontent.com/47530763/57132393-c1ca5080-6d9f-11e9-8c52-ce1f1c9440e7.png)

The same class, the same method in Net Framework 4.5, does not give any problem. The CHM file is generated correctly.
Does anyone know what is happening?
Thank you.

**Comment by EWSoftware** [comment]
Are you using the Cross Platform option for the Framework Version?  That should resolve the issue.  If not, can you provide an example that I can build to duplicate it?

**Comment by kosday** [comment]
Thank you for answering so quickly
Yes. We are using Cross Platform option.
I send a simple test project for you can duplicate it.
[TestDocSandcastle.zip](https://github.com/EWSoftware/SHFB/files/3144647/TestDocSandcastle.zip)

**Comment by kosday** [comment]
Hi @EWSoftware .
Could you reproduce the error?

**Comment by EWSoftware** [comment]
Sorry, I forgot to follow up on this.  The problem in the example at least is that you're using the assembly and XML comments files as documentation sources.  In the absence of any other references in the SHFB project it falls back to using the full .NET Framework assemblies (.NET 4.7) for the core types which don't match what the assembly was built against.  If you do want to use the assembly as the documentation source, you need to manually add a reference to the SHFB project to the .NET Standard System.Runtime.dll (C:\Users\\[YOURUSERID]\\.nuget\packages\System.Runtime\4.3.0\ref\netstandard1.5\System.Runtime.dll for example).

Using the project as the documentation source allows SHFB to find and add the references automatically.  However, even when using the project as a documentation source in this case, it didn't find any reference assemblies to add as there's nothing more than the SDK reference.  The workaround in this case is to add a NuGet reference to the assembly project to something such as System.Collections which pulls in the other .NET Standard assembly references as dependencies and then they do get found and added when building the documentation.

I need to look into why it's not finding anything in the absence of any other explicit references.

**Comment by kosday** [comment]
I added the reference and now is working.
Thank you very much @EWSoftware
