### ISSUE TITLE
Add an Example for SyntaxGeneratorTemplate Class

### ISSUE THREAD

**Issue by shourabhshukla** [EWSoftware/SHFB#702]
Please add an example for SyntaxGeneratorTemplate Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://ewsoftware.github.io/SHFB/html/d28a52d1-dd73-c553-8c4e-8b00972527e3.htm

**Comment by EWSoftware** [comment]
The best way to see how to implement one is to look at the code for the [existing generators](https://github.com/EWSoftware/SHFB/tree/master/SHFB/Source/BuildAssembler/SyntaxComponents).  It's quite possible you may be able to take one of them and adapt it to your own needs.
