### ISSUE TITLE
Adding content that is conditioned on output type.

### ISSUE THREAD

**Issue by kfertitta** [EWSoftware/SHFB#703]
We're emitting website content, as our users generally prefer this. Some, however, still prefer a CHM.  To accommodate them, I'm experimenting with using the "Additional footer content" to contain a "Download CHM file here" that links to the CHM file on the web server.  Works fine, but one issue is that, of course, the same footer appears in the downloaded CHM.

Is there a way to condition that bit of footer content?  Or, perhaps, there's a better way to achieve my overall goal.

Thanks in advance.

**Comment by EWSoftware** [comment]
There isn't a way to conditionally include or exclude property values based on the format.  However, you may be able to use a bit of script to do it.  The *branding.js* file checks to see if it's running in the Help 1 viewer to support its persisted language filter selection.  See [branding.js, line 39](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/PresentationStyles/VS2013/scripts/branding.js#L39).

You could probably wrap your conditional content in a div or span with an ID and add some inline script either in the Additional Footer Content property or the Website Ad Content property that checks whether it's in the Help 1 viewer or not and hides the div or span if it is.

**Comment by kfertitta** [comment]
Hi @EWSoftware 

Thanks very much for that.  Seems like a perfect solution.  I tried it below and get a "BUILD FAILED":

Build Log is attached.

Here is the test script I tried to inject in the footer.  I'm sure I'm doing something fundamentally wrong, but I've tried the below with and without the `CDATA`:

```
    <HelpFileVersion>1.0.0.0</HelpFileVersion>
    <FooterText>
      <![CDATA[
        <script type="text/javascript">
            var _footer = document.getElementById("pageFooter");
            if (_footer)
            {
                var downloadChmText = document.createTextNode("Hello Kirk!!!");

                _footer.append(downloadChmText);
            }
        </script>
    ]]>
    </FooterText>
```


[LastBuild.log](https://github.com/EWSoftware/SHFB/files/3158379/LastBuild.log)

**Comment by EWSoftware** [comment]
Actually, no script is required after all.  Just put your link HTML in the Website Ad Content property in the Help 1/Website category.  It only gets added to website output and appears below the footer.

**Comment by kfertitta** [comment]
Hi Eric,

Thanks very much.  That's much simpler and works just fine.  Really appreciate it.
