### ISSUE TITLE
Documenting a shared project (.shproj).

### ISSUE THREAD

**Issue by kfertitta** [EWSoftware/SHFB#704]
I have a large library that ships to customers as a shared library project (`.shproj`) so that they can bake it into their own assemblies.  To document that shared library with Sandcastle, I have a "dummy" project in my Sandcastle solution that references the shared library and builds it.  This all works fine, but it does mean that the assembly name that shows up on each reference page is a bogus one.  Ideally, I would exclude the assembly line from each reference page, since it is not meaningful for a shared library project.

Is there a way to achieve this?

Thanks in advance.

**Comment by EWSoftware** [comment]
Add a Resource Items file to the SHFB project.  Locate the items with the IDs `assemblyNameAndModule`, `boilerplate_requirementsAssembly`, `boilerplate_requirementsAssemblyLabel`, and `locationInformation`.  For each one, delete its content.  These will override the items in the presentation style and effectively render them as blank items thus removing the related text from the topic.

**Comment by kfertitta** [comment]
Yes, that works very well.  Thank you again for your help.
