### ISSUE TITLE
.NET Framework 4.8 Build

### ISSUE THREAD

**Issue by philliprlittle** [EWSoftware/SHFB#706]
I have several projects that target the .NET 4.8 Framework but I notice that there is not yet a SHFB.NETFramework package for .NET 4.8 so I cannot set my shfbproj files to target this new framework. This makes it impossible to build the documentation since the documentation projects are targeting an earlier version of .NET (4.6.2). Is there a time frame for when this package will be released, and is there a work around in the meantime? I am using SHFB v2019.4.14.

**Comment by EWSoftware** [comment]
Copy the attached file to your SHFB project folder and rename it to have a *.reflection* extension.  When you open the project, you can select it in the Framework Version property.  Its set up to use the .NET 4.7.2 files for the time being.

It'll probably be a week or so before I release an update with the rebuild data set files that contain support for .NET 4.8.

[.NETFramework_4.8.txt](https://github.com/EWSoftware/SHFB/files/3198376/default.NETFramework_4.8.txt)

**Comment by philliprlittle** [comment]
So I have three SHFB projects that I am building. I copied the file into each one, changed the extension to _.reflection_, and then changed the project properties to target .NET 4.8 from the drop down menu. The first project that builds does so successfully; however, the next two fail with the following error: 

"SHFB : error BE0065: BUILD FAILED: Reflection data files for the selected framework do not exist yet (.NET Framework 4.8)."

**Comment by EWSoftware** [comment]
I forgot that it needs the XML files in the same location.  Put it in a subfolder and copy the XML files from *%ProgramFiles(x86)%\EWSoftware\Sandcastle Help File Builder\Data\\.NETFramework* to that folder.

If you want to share it amongst all the projects, put the folder in a common location that they can all access and set the SHFB project's Component Path property to that location.

**Comment by philliprlittle** [comment]
Looks like that worked. Thanks for the help!
