### ISSUE TITLE
Make VS2013 style mobile friendly

### ISSUE THREAD

**Issue by JamesNK** [EWSoftware/SHFB#71]
The Sandcastle VS2013 style is not mobile friendly, and it fails Google's mobile test:

https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fewsoftware.github.io%2FSHFB%2Fhtml%2Fbd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm

The style should be updated to be mobile friendly, possibly by adding a mobile specific CSS file, or through CSS media queries.

**Comment by EWSoftware** [comment]
Picking a page at random (https://msdn.microsoft.com/en-us/library/system.windows.forms.form(v=vs.110).aspx) MSDN isn't mobile friendly either.  I doubt a mobile-specific style sheet is all that's needed to make a mobile-friendly version of the presentation style.  It would probably require a separate presentation style all on its own.

I'm not a mobile developer so it's not something I will tackle.  If somebody else does, feel free to submit the presentation style for inclusion.
