### ISSUE TITLE
"Edit API Filter" Causes Visual Studios 2017 to crash

### ISSUE THREAD

**Issue by iShorty123** [EWSoftware/SHFB#711]
Hello,

When I go to properties, Visibility, and then click the "Edit API Filter" button in Visual Studios 2017 v15.9.12 it causes Visual Studios to crash. I'm using the SHFB 2019.4.14.0 extension for Visual Studios.

**Comment by EWSoftware** [comment]
I'm not able to duplicate this with any of my projects.  Can you supply an example that causes a crash?

**Comment by iShorty123** [comment]
Im in the middle of finals week, sorry for the delay!

Here is the repo I’m using, it involves Unity 2018, which is a little tricky to get working with sand castle in the first place, the repo readme/documentation explains how to do it. But, if there is another way I can give you an example, something that doesn’t involve you installing Unity or a lot of work on your end, let me know and I’ll see what I can do!

https://github.com/UWB-ARSandbox/ASL

The repo is public, but let me know if you have any troubles with it. 

Thanks for your help!

-Greg

> On Jun 7, 2019, at 12:13 PM, Eric Woodruff <notifications@github.com> wrote:
> 
> I'm not able to duplicate this with any of my projects. Can you supply an example that causes a crash?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
This e-mail message (including any attachments) is for the sole use of the 
intended recipient(s) and may contain confidential, privileged, and/or 
proprietary information. If the reader of this message is not the intended 
recipient, you are hereby notified that any dissemination, distribution or 
copying of this message (including any attachments) is strictly prohibited.


If you have received this message in error, please contact the sender by 
reply e-mail message and destroy all copies of the original message 
(including attachments).

**Comment by EWSoftware** [comment]
Can you attach or send me the Assembly-CSharp.dll and Assembly-CSharp.xml files?  I'll need those to diagnose the issue since the API filter does a build in the background to get the API info.

**Comment by iShorty123** [comment]
Sure thing, attached is a zip of these files.
Unity is a little weird in that it places these in a temp (then bin, then Debug) folder that gets wiped often. Because of this, whenever I want to build documentation, I have to manually build the Assembly-CSharp project (because quite often it doesn't actually exist in a .dll and/or .xml state) and then build documentation. I don't know if that's a reason for why VS crashes, but I figured I'd letcha know the build process for these files.

[Assembly-CSharpFiles.zip](https://github.com/EWSoftware/SHFB/files/3279343/Assembly-CSharpFiles.zip)

**Comment by EWSoftware** [comment]
The Inherited .NET Framework Members option is turned off in your project and the API filter isn't currently handling the missing info properly.  It's fixed for the next release which I should get published this weekend.  As a workaround, you can enable that option before going into the API Filter.

**Comment by iShorty123** [comment]
Got it, thanks!

-Greg

> On Jun 12, 2019, at 11:45 AM, Eric Woodruff <notifications@github.com> wrote:
> 
> The Inherited .NET Framework Members option is turned off in your project and the API filter isn't currently handling the missing info properly. It's fixed for the next release which I should get published this weekend. As a workaround, you can enable that option before going into the API Filter.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
This e-mail message (including any attachments) is for the sole use of the 
intended recipient(s) and may contain confidential, privileged, and/or 
proprietary information. If the reader of this message is not the intended 
recipient, you are hereby notified that any dissemination, distribution or 
copying of this message (including any attachments) is strictly prohibited.


If you have received this message in error, please contact the sender by 
reply e-mail message and destroy all copies of the original message 
(including attachments).
