### ISSUE TITLE
Summary tag not recognized

### ISSUE THREAD

**Issue by SoftCircuits** [EWSoftware/SHFB#715]
Thanks for the help so far. Just one last issue. I have the following two methods (unimportant lines removed):

```cs
public class CsvFileReader : CsvFileCommon, IDisposable
{
    /// <summary>
    /// Reads a row of columns from the current CSV file. Returns false if no
    /// more data could be read because the end of the file was reached.
    /// </summary>
    /// <param name="columns">Collection to hold the columns read</param>
    /// <returns>Returns true if a row was read, or false if the end of the
    /// file was reached.</returns>
    public bool ReadRow(List<string> columns)
    {
        // ...
    }
}

public class CsvFileWriter : CsvFileCommon, IDisposable
{
    /// <summary>
    /// Writes a row of columns to the current CSV file.
    /// </summary>
    /// <param name="columns">The list of columns to write.</param>
    /// <exception cref="ArgumentNullException"></exception>
    public void WriteRow(List<string> columns)
    {
        // ...
    }
}
```
As you can see, both classes derive from `CsvFileCommon`. And both classes have a constructor, a `Dispose()` method, and the method shown above as the only public methods.

And for some crazy reason, the `<summary>`, `<param>`, and `<returns>` tags are not recognized for these two methods.

```
[M:Toxic.Parsing.CsvFileReader.ReadRow(System.Collections.Generic.List1)] Missing <summary> documentation [D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\BuildTopics.proj]
[M:Toxic.Parsing.CsvFileReader.ReadRow(System.Collections.Generic.List1)] Missing <returns> documentation [D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\BuildTopics.proj]
[M:Toxic.Parsing.CsvFileReader.ReadRow(System.Collections.Generic.List1)] Missing <param name="columns"/> documentation [D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\BuildTopics.proj]
[M:Toxic.Parsing.CsvFileWriter.WriteRow(System.Collections.Generic.List1)] Missing <summary> documentation [D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\BuildTopics.proj]
[M:Toxic.Parsing.CsvFileWriter.WriteRow(System.Collections.Generic.List1)] Missing <param name="columns"/> documentation [D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\BuildTopics.proj]
```

I now have every needed tag for every namespace, class, method and property in my project. These two are the only ones not recognized. I even recreated one of them to rule out strange characters and it made no difference.

The symmetry of these two methods is interesting, but I can't think of any reason why these two methods would have this problem.

**Comment by EWSoftware** [comment]
Check the build log to see if it found and XML comments file for the documentation source and, if so, which XML comments.  Check that file to see if it contains the member comments.  Typically when this happens, the XML comments file doesn't exist or is out of date.

**Comment by SoftCircuits** [comment]
I'm not sure what I'm looking for in the log file. I can see I have a new XML file that includes the following. (Note that the XML comments appear fine for the constructor from the same class.)

```
<member name="M:Toxic.Parsing.CsvFileReader.ReadRow(System.Collections.Generic.List{System.String})">
    <summary>
    Reads a row of columns from the current CSV file. Returns false if no
    more data could be read because the end of the file was reached.
    </summary>
    <param name="columns">Collection to hold the columns read</param>
    <returns>Returns true if a row was read, or false if the end of the
    file was reached.</returns>
</member>
```

And:

```
<member name="M:Toxic.Parsing.CsvFileWriter.WriteRow(System.Collections.Generic.List{System.String})">
    <summary>
    Writes a row of columns to the current CSV file.
    </summary>
    <param name="columns">The list of columns to write.</param>
    <exception cref="T:System.ArgumentNullException"></exception>
</member>
```

**Comment by EWSoftware** [comment]
Look at the start of the log file where it's validating the documentation sources.  It lists whether or not it found any XML comments files and which ones it will use if it did.  In this case, it reported the following:

```
Copying XML comments files
    D:\Users\Jonathan\source\repos\Toxic\Documentation\Toxic.Desktop.xml ->; D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\Toxic.Desktop.xml
    D:\Users\Jonathan\source\repos\Toxic\Documentation\Toxic.Web.xml ->; D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\Toxic.Web.xml
    D:\Users\Jonathan\source\repos\Toxic\Documentation\Toxic.xml -> D:\Users\Jonathan\source\repos\Toxic\Documentation\SCHB\Help\Working\Toxic.xml
```

Those are the ones to check for the member comments and that they are up to date.

**Comment by SoftCircuits** [comment]
Yes, in my last message I pasted content from those same files you just listed. And those files are the ones I said were new.

Everything is working now except just the XML comments for these two methods, from two related classes. I've tried everything I can think of but can't find a reason why these methods would be different.

**Comment by EWSoftware** [comment]
From the build log it looks like you are using .NET Standard but have the .NET Framework 4.5 selected in the SHFB project.  Change it to use the Cross Platform framework version.  Most likely it's not matching the core types correctly due to the incorrect framework selection.  Fixing that should get it working.

**Comment by SoftCircuits** [comment]
Thanks, but that isn't the issue.

I'm not sure I understand the role the .NET Framework plays in correctly building a help file, but making the suggested change did eliminate the one warning. But it did not eliminate the missing `<summary>` documentation. And I would've been surprised if it had, given that all other topics are coming up just fine.

Very strange.

**Comment by SoftCircuits** [comment]
One thing I did notice that's different about these two methods is that they accept an argument of type `List<string>`. None of my other methods do this.

And looking at the documentation generated, it doesn't quite get it right:

```cs
public void WriteRow(
	List columns
)
```

It does not show that the list is of type `string`. I don't know if this is expected, or if it could be related to the missing documentation.

**Comment by EWSoftware** [comment]
Can you supply an example that demonstrates the issue?

**Comment by SoftCircuits** [comment]
Well, my first post in this thread is from my actual code. What would be helpful to send? And can I send it privately?

**Comment by EWSoftware** [comment]
I need something I can build with the same settings and assemblies you are using.  You can e-mail it to me if it isn't available publicly or you don't want to attach it here.

**Comment by SoftCircuits** [comment]
Ok, attached.

[Help Project.zip](https://github.com/EWSoftware/SHFB/files/3293474/Help.Project.zip)

**Comment by EWSoftware** [comment]
I need all the documentation sources too.  Without them, I can't build the help file.

**Comment by SoftCircuits** [comment]
Ok, I see. Where can I find your email address?

**Comment by SoftCircuits** [comment]
Sent by email.

**Comment by EWSoftware** [comment]
The compiler is writing out a different method signature in the XML comments file for those members.  Rather than the generic `List``1`, it's writing out the parameter type as `List{System.String}`.  This is a change from past compiler behavior.  The C++ and VB compilers have similar issues and, as with them, the issue can be resolved by using the Name Fix-Ups plug-in.  I've attached an updated version of your SHFB project that includes the plug-in to correct the issue.

[ToxicDocs.zip](https://github.com/EWSoftware/SHFB/files/3294529/ToxicDocs.zip)

**Comment by EWSoftware** [comment]
There doesn't appear to be a way to get the build engine to reliable resolve references in this particular case.  As such, the best solution is to add the missing references to the SHFB project manually.  It's not ideal but I haven't found a better solution.

**Comment by SoftCircuits** [comment]
I appreciate all your help. I must admit I'm at a complete loss why just this item is a problem when everything else seems to work. I will try adding the reference. In the end, it's just to document a class library. There a limit to how much tweaking is worthwhile for me. Thanks again.

**Comment by SoftCircuits** [comment]
One last note: I ported the library over to .NET Standard 2.0 and now everything seems correct. Thanks again.
