### ISSUE TITLE
Build failure InvalidOperationException when building OpenXml format

### ISSUE THREAD

**Issue by dm413** [EWSoftware/SHFB#717]
I recently upgraded from version 2018.7.8 to version 2019.4.14. I have a SHFB project that I run from VS2017 or VS2019. It works fine when building HtmlHelp. However if I change to build OpenXml, the new version (2019.4.14) fails at the end of the process. The build log shows (I shortened the path with ...):

```
<buildStep step="CompilingHelpFile">
Generating Open XML document file...
[C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe - BuildOpenXmlFile.proj]
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018: The &quot;SandcastleBuilder.Utils.MSBuild.BuildOpenXmlFile&quot; task failed unexpectedly.
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018: System.InvalidOperationException: The parent is missing.
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018:    at System.Xml.Linq.XNode.ReplaceWith(Object content)
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018:    at SandcastleBuilder.Utils.MSBuild.BuildOpenXmlFile.CleanupTables(XDocument document)
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018:    at SandcastleBuilder.Utils.MSBuild.BuildOpenXmlFile.ApplyChanges(XDocument document, String key)
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018:    at SandcastleBuilder.Utils.MSBuild.BuildOpenXmlFile.Execute()
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
F:\...\MyAPI\Working\BuildOpenXmlFile.proj(29,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()
    Last step completed in 00:00:00.5150
</buildStep>
```

It fails in both VS2017 and VS2019 with the same error. It does not fail in VS2017 with SHFB 2018.7.8. It only fails for OpenXml output.

Is there anything I can do to avoid this error? Thanks,

**Comment by dm413** [comment]
Further testing shows that this problem occurs in SHFB version 2019.3.13, but does not occur (the build succeeds) in version 2018.12.10. 

This is useful to know because 2018.12.10 supports VS2019, while earlier versions do not. Version 2018.12.10 won't install schemas in VS2019, but other than that it appears to be functional.

**Comment by EWSoftware** [comment]
Some changes were merged to fix issues with the Open XML output so that it is compatible with the specification.  One of those changes was to move tables embedded within paragraphs to the body.  It's not handling cases where more than one table appears in a paragraph.  I've fixed it for the next release due out next week.

As a workaround, if you search your conceptual topics or XML comments for tables within a paragraph and move them out of the paragraph element, that should fix the issue.

**Comment by dm413** [comment]
I can't find any place where I have tables inside paragraphs. I have `<para>` tags inside table `<entry>` tags, but not the other way around. I do have multiple tables inside `<introduction>` tags -- is that an issue? 

I can live with version 2018.12.10 for now, so I guess I'll wait for the next release and see how that works. Thanks,
