### ISSUE TITLE
NullReferenceException thrown by Roslyn extension in VS2019

### ISSUE THREAD

**Issue by MBerantzino** [EWSoftware/SHFB#719]
The following exception is thrown sometimes while writing in VS2019:

System.NullReferenceException: Object reference not set to an instance of an object.at SandcastleBuilder.Package.IntelliSense.RoslynHacks.RoslynKeyboardFilter.HandleCompletion(Char commitCharacter)at SandcastleBuilder.Package.IntelliSense.RoslynHacks.RoslynKeyboardFilter.HandlePreExec(Guid& commandGroup, UInt32 commandId, OLECMDEXECOPT executionOptions, IntPtr pvaIn, IntPtr pvaOut)at SandcastleBuilder.Package.IntelliSense.RoslynHacks.CommandFilter.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& guidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at SandcastleBuilder.Package.GoToDefinition.GoToDefinitionCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.Intellisense.MultiCaretPreemptingFilterProvider.MultiCaretPreemptingFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

It is not a critical issue - as it can be ignored (at least I haven't seen any side effects) from it.

Also, VS2019 complains about the extension is slowing VS2019 down - perhaps it could be optimized a bit for performance?

**Comment by EWSoftware** [comment]
What operations cause the slowdown warning?  That would help me know where to look.

**Comment by MBerantzino** [comment]
Not sure which operation - VS2019 just shows the warning at arbitrary points in time saying it slows down typing. From the log entry regarding the NullReferenceException I get the assumption that everything being typed are processed by the Roslyn extension - why the issues could be related. 

But I must say, that I have only seen this warning 2 times the last week and can be ignored - whereas the NullReferenceException happens daily.

**Comment by StevenBonePgh** [comment]
I am seeing the 'We've noticed that extension 'SHFB' is slowing typing performance.' in VS2019 16.1.3. Then VS slows to a crawl doing everything. The Performance Manager states SHFB is adding 1791 milliseconds on average.  What operations? Basically just typing, not even in a comment area.  I haven't delved into the world of extension development since AddIns were the extension mechanism, so I don't know what else would be helpful to you.  @MBerantzino - where are you seeing the errors?  

I also have R# (latest build) and a handful of other extensions.

**Comment by EWSoftware** [comment]
You can go into Tools | Options, select the Sandcastle Help File Builder category and disable the "Enable extended XML comments completion options".  If that's what's causing the crashes and slowdowns, that should work around it for the time being.  There are a couple of other options related to Go To Defintion within XML comments and MAML topics.  They shouldn't affect typing in the editor since they're more mouse/command based but I'll check.

@sharwell Any idea why this might be causing issues in VS2019?  I know there was talk of adding the extra completions to Visual Studio itself.  If that has happened or will, perhaps it's better to just disable this for VS2019.

**Comment by MBerantzino** [comment]
I'm almost certain that the problem always happens while editing code - more specifically just when the ( has been typed while typing a method call. Now, i write pretty fast - so it might be code completion followed by deleting some of the completed code again to change it.

**Comment by StevenBonePgh** [comment]
Agree with @MBerantzino - I experienced it in code and not in comments.

**Comment by sharwell** [comment]
Random third-party extensions tend to get blamed periodically. All the in-box components have hard-coded exceptions to prevent these spurious reports from showing them. If it's only occasional, I'd assume that's what it is.

If you can reproduce the situation that leads to the warning, try to capture it by following the steps on https://aka.ms/reportPerf and send me the link.

**Comment by EWSoftware** [comment]
I've added null checking to various spots in the method that is throwing the exception so that should stop that.  I suppose it's possible the exception is somehow contributing to the slowdowns.

@sharwell I noticed today that the augmented completion sets are no longer working in VS 2019.  In debugging, the provider is never called to create it.  I found reference to a new `IAsyncCompletionSourceProvider` and the suggestion that languages that use it won't create or invoke providers based on the non-async version.  Is that correct?

**Comment by sharwell** [comment]
@EWSoftware Yes, that's correct. Send me a message in the first half of July and I'll help find a way to resolve this.

**Comment by MBerantzino** [comment]
Just received a new exception - this time a System.InvalidOperantionException.

Happened while typing code.

System.InvalidOperationException: Sequence contains no elementsat System.Linq.Enumerable.First[TSource](IEnumerable`1 source)at Microsoft.VisualStudio.Language.Intellisense.Implementation.ShimCompletionSession.BuildCompletionSet(ComputedCompletionItems recentlyUpdatedItems, IAsyncCompletionSessionOperations session, ShimCompletionSession owner)at Microsoft.VisualStudio.Language.Intellisense.Implementation.ShimCompletionSession.get_SelectedCompletionSet()at SandcastleBuilder.Package.IntelliSense.RoslynHacks.RoslynKeyboardFilter.HandleCompletion(Char commitCharacter)at SandcastleBuilder.Package.IntelliSense.RoslynHacks.RoslynKeyboardFilter.HandlePreExec(Guid& commandGroup, UInt32 commandId, OLECMDEXECOPT executionOptions, IntPtr pvaIn, IntPtr pvaOut)at SandcastleBuilder.Package.IntelliSense.RoslynHacks.CommandFilter.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& guidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at SandcastleBuilder.Package.GoToDefinition.GoToDefinitionCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.Intellisense.MultiCaretPreemptingFilterProvider.MultiCaretPreemptingFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by EWSoftware** [comment]
I've disabled the keyboard filter for VS2019.  It's of no use anyway since the augmented completion sets aren't being used.
