### ISSUE TITLE
CodeEntityReference with indirect generic parameters on method

### ISSUE THREAD

**Issue by MichaelArndt** [EWSoftware/SHFB#72]
Hi,

a Method defined like:
```csharp
public static IEnumerable<TSource> DeepFirst<TSource, TKey>((
            IEnumerable<TSource> source, 
            Func<TSource, TKey> selector, 
            Func<TSource, IEnumerable<TKey>> edges)
```
can or cannot referenced by CodeEntityReference. If it can, than how is the syntax and where is it described?

I tried:
M:TopologicalSort.DeepFirst``1(System.Collections.IEnumerable{``0},System.Func{``0,``1},System.Func{``0,System.Collections.IEnumerable{``1}}

best regards
Michael

**Comment by EWSoftware** [comment]
Find it using the Entity References tool window and drag it from there.  When dropped, it'll insert the code entity reference using the proper ID.

**Comment by MichaelArndt** [comment]
That helps a lot. Thank you.
