### ISSUE TITLE
Combining code snippets causes loss of syntax highlighting

### ISSUE THREAD

**Issue by jonatasbra** [EWSoftware/SHFB#721]
I am using version 2019.4.14.0 with presentation style VS2013, HTML Help1 (chm).

When I combine several snippet IDs within the codeReference tag, as instructed in the documentation, I get the combined result, but the syntax highlighting is lost.

In fact, even in the example provided at the online documentation the syntax highlighting is lost. See the last example at https://ewsoftware.github.io/MAMLGuide/html/91a45341-e368-463e-a9ed-9e05286d2c25.htm

**Comment by EWSoftware** [comment]
This is an old Microsoft component.  I've added support for multi-snippet reference colorization.  However, note that the [code](https://ewsoftware.github.io/MAMLGuide/html/65e7e30a-ba03-4e10-b1f2-763a613b6e27.htm) element has much better support for importing and colorizing code snippets and supports importing them from live source code.
