### ISSUE TITLE
Augmented completion sets are not supported in VS2019

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/SHFB#722]
C# uses asynchronous completion sets in VS 2019.  The augmented completion sets in SHFB are still using the non-asynchronous interface and are thus ignored.  They need to be rewritten to use `IAsyncCompletionSourceProvider` and `IAsyncCompletionSource`.

Note: Since VS 2015 does not support these interfaces, support for it will be dropped as I don't want to maintain a separate package just for this one feature.

**Comment by NerdyDuck** [comment]
Hi!
As I needed the expanded auto-completion in VS 2019 asap, I just created a package myself using your list of CompletionItems. You can find it at https://github.com/NerdyDuck/CSharpDocumentationCompletion2019 . Feel free to reuse my code for your package. Some observations that I made while writing:

- Documentation for the VSSDK, especially the new interfaces is either non-existent, outdated or bad. I finally got it working by looking at a project of @madskristensen .
- My extension works with VS 2019 **only** . I set the vsixmanifest so it would also install on VS 2017, but it wouldn't work (no items added). I think it's not possible to have an extension that references the latest VSSDK NuGets to access the new features, and still have it running on older VS versions. So you might have to maintain multiple extension packages if you want to support more than VS 2019. Maybe completely decouple Intellisense from the SHFB project support part, and put it into its own extension package? I think there may be scenarios where some developers need to write XML doc comments in their code, but are not involved in actually creating the documentation with SHFB.
- Currently my extension always adds all CompletionItems whenever auto-completion is triggered. Your way of filtering by looking at the CompletionItems provided by the default Intellisense to determine what additional items to add does not work with the new interface. At least, I didn't find a way to access CompletionItems from other sources. And I think you can't, as the generation of CompletionsItems is now async, so you'd have to wait for other extensions to provide items. I guess the only way for filtering would be to parse the comment block up to the current location where the auto-completion was triggered. Not sure if that is important enough to warrant the effort - both for coding the filter, and the effect of the filter on the performance of auto-completion.

**Comment by EWSoftware** [comment]
Thanks.  I'll take a look at it when I have some time.  I was under the impression that VS 2017 supported the async completions too so it may be possible to support them there as well by targeting an earlier version of the SDK.  Either way, separating them completely from SHFB may be worthwile too as there's no dependence on anything in SHFB itself and it could be published separately and hosted in the marketplace.

**Comment by madskristensen** [comment]
I think the Async Completion APIs were introduced in 15.6 or 15.7.

**Comment by sharwell** [comment]
I think Roslyn itself supports completion extensions now. I'll need to verify.

**Comment by sharwell** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionProvider.cs,3632bba4d25ec249

**Comment by sharwell** [comment]
As a side note, `inheritdoc` will appear in the standard Roslyn completion lists starting with Visual Studio 2019 version 16.4. I implemented that feature in dotnet/roslyn#36028.

**Comment by NerdyDuck** [comment]
> I think the Async Completion APIs were introduced in 15.6 or 15.7.

You're right, I just checked the NuGet package v15.9.3. Although there are differences in the interfaces of v15.9 and v16.0. I'll try to make my code run against v15.9.3 and see if it runs in both VS2017 and 2019.

**Comment by NerdyDuck** [comment]
> I think Roslyn itself supports completion extensions now. I'll need to verify.

Interesting. Is there an advantage in running completions in Roslyn instead of VS?

> As a side note, inheritdoc will appear in the standard Roslyn completion lists starting with Visual Studio 2019 version 16.4. I implemented that feature in dotnet/roslyn#36028.

Good to know. You wouldn't perchance want to implement the rest of the completions of SHFB, would you? :wink:

**Comment by sharwell** [comment]
> Is there an advantage in running completions in Roslyn instead of VS?

Yes, the augmented completion list is not really the way completion is supposed to work.

> You wouldn't perchance want to implement the rest of the completions of SHFB, would you?

We've done a few, but each one requires separate consideration. I don't think there are any more on the short list to implement.

**Comment by NerdyDuck** [comment]
Well, it wasn't that difficult to copy my code for VS2019 into a VS2017 extension project, reference the Microsoft.VisualStudio.SDK nuget v15.9.3, and make it compile. But it doesn't work, VS 2017 doesn't even create an instance of my class that implements IAsyncCompletionSourceProvider. Although the package installs just fine, and is listed in the extension list. Same goes for debugging. Package is listed, but does nothing, and doesn't hit my breakpoints.

If someone smarter than me wants to take a look, you can find it at NerdyDuck/CSharpDocumentationCompletion2017 .

**Comment by EWSoftware** [comment]
I suspect that it's a case of one or the other, not both with regard to which completion providers are implemented by the language services.  VS 2017 uses the older ones, VS 2019 uses the newer ones.  Neither appear to implement both which makes sense.

I was able to get a Roslyn completion provider working with VS 2019.  My goal is to make it configurable so that it provides the set of extra comments elements and is also extensible so that user-defined custom elements can be offered as completions too.

**Comment by EWSoftware** [comment]
The initial release of the Extended Doc Comments Provider is available in the [marketplace](https://marketplace.visualstudio.com/items?itemName=EWoodruff.ExtendedDocCommentsProvider).

The current set of supported elements, attributes, and attribute values is listed in the [online help](https://ewsoftware.github.io/ExtendedDocCommentsProvider/html/141160ac-ba6a-4f6d-a802-1110aadea932.htm). Issues and feature requests can be added at the [project site](https://github.com/EWSoftware/ExtendedDocCommentsProvider).

I'm leaving this issue open for the time being as a reminder to update the SHFB docs and add an entry for it in the guided installer.

**Comment by SamuelEnglard** [comment]
@EWSoftware I can't find it in the marketplace?

**Comment by EWSoftware** [comment]
Apparently they aren't made public by default when first published.  You should be able to see it now.
