### ISSUE TITLE
"Object reference not set to an instance of an object" when opening Conceptual Content

### ISSUE THREAD

**Issue by smckinney94** [EWSoftware/SHFB#723]
Assembly Builder is building with no issues,
No issues in the HTML or XML,
The Conceptual Content will open but will be blank.

**Comment by EWSoftware** [comment]
I need more information.  Is this in Visual Studio or the standalone GUI.  Are you talking about when you open a topic to edit it?  Are you using the latest release?   Have you tried uninstalling and reinstalling the extension/tools?

**Comment by smckinney94** [comment]
Thanks for getting back to me.

It's in Visual Studio. The build runs successfully and the Conceptual
Content showed the index before.
I have uninstalled and reinstalled Sandcastle and the GUI helper to no
avail.
I have cleaned the project and rebuilt it successfully but it is still not
working.
The issue has moved on from "Object reference not set to an instance of an
object"  now opens an empty 'Conceptual Concent' window.
I attached an mp4 which shows this problem.

Sean.

**Comment by EWSoftware** [comment]
The attachment didn't make it.  You'll need to attach it to the issue in the browser or e-mail it to me directly.

**Comment by smckinney94** [comment]
[ConceptualConcept.zip](https://github.com/EWSoftware/SHFB/files/3358570/ConceptualConcept.zip)

**Comment by smckinney94** [comment]
It also does this initially
[ObjectReferenceNotSetToAnInstanceOfAnObject.zip](https://github.com/EWSoftware/SHFB/files/3358857/ObjectReferenceNotSetToAnInstanceOfAnObject.zip)

**Comment by EWSoftware** [comment]
I guess I should have asked what version of SHFB you are using.  From the video's, it looks like it predates the Visual Studio release by quite some time.  I suggest updating to the latest release which, if you still need it, does include a much newer relase of the standalone GUI.

**Comment by smckinney94** [comment]
SandcastleBuilder Help File Builder GUI - 1.7.0.0

**Comment by EWSoftware** [comment]
Sorry, that's 11 years old and a lot has changed and been fixed since then.  Fixing that specific version now or even knowing why it stopped working isn't an option so you will need to upgrade.  Since all versions after 1.7.0.0 use a standard MSBuild project format you will need to recreate the project.  The old format project converters were removed in 2015.

**Comment by smckinney94** [comment]
Would you know if it has any stacktrace capabilities

**Comment by EWSoftware** [comment]
I'm not sure what you mean.  For that release or the latest?

**Comment by smckinney94** [comment]
For the 1.7 release.
Reason being is that I downloaded the latest version and it cannot read the file which we have from 1.7. Our project is too big to replicated and write again, I'm just trying to figure out what is causing the 'object reference is not set to an instance of an object'

**Comment by EWSoftware** [comment]
Sorry, but I think you're out of luck.
