### ISSUE TITLE
Search feature in html not working?

### ISSUE THREAD

**Issue by SmartFoxServer** [EWSoftware/SHFB#724]
I created a C# DLL for which I need to generate the online documentation for its API.
SHFB (latest standalone version) does the job in creating the HTML output (presentation style is VS2013), but the search feature doesn't work.
It seems there's an issue in generating the content of the files in the **fti** folder. In fact the 11 files that get generated only contain 2-3 keywords each; also, such keywords are totally unrelated to the actual classes contained in my DLL. Here is an example taken from file **FTI_116.json**:

`{"topic":[65537],"title":[1]}`

Here you can see the final output I get from SHFB, which is what I expected to obtain: http://docs2x.smartfoxserver.com/api-docs/csharp-doc/

In the documentation build log, the only reference to the search function is this:

```
-------------------------------
Generating full-text index for the website...

Adding lightweight search and TOC elements to each topic...
    Last step completed in 00:00:24,7496
-------------------------------
```

Am I missing something or doing something wrong? I can't locate specific options related to the search feature. Any help will be much appreciated.
I can provide the DLL and XML generated by Visual Studio (Mac version) and the SHFB project if needed.

**Comment by EWSoftware** [comment]
Please attach the examples here or send them to me by e-mail.  Thanks.

**Comment by SmartFoxServer** [comment]
Hello.
Find attached a zip file containing:

- the DLL and XML files generated by Visual Studio for macOS (latest version)
- the SHFB project and a few additional assets it uses

Thank you very much for your support.

Best regards,

Paolo Bassino
SmartFoxServer Team
www.smartfoxserver.com <http://www.smartfoxserver.com/>



 <https://www.youtube.com/SmartFoxServer> <https://www.youtube.com/SmartFoxServer>

**Comment by EWSoftware** [comment]
I tried your example and it generated a proper index.  Is this being built on a PC?  Are you using the latest release?

**Comment by SmartFoxServer** [comment]
The documentation is being built under Windows 10 using the latest version of SHFB GUI. A few days ago I was using an older version, but the search function in the html build was not working anyway.

**Comment by SmartFoxServer** [comment]
I'm attaching here the content of the generated **fti** folder, in case it helps.
[fti.zip](https://github.com/EWSoftware/SHFB/files/3361624/fti.zip)

**Comment by EWSoftware** [comment]
It looks like there are some words index but for some reason it's not indexing all the files.  Sorry, but I can't say why that might be.  It could be something specific to the VM so perhaps trying it on a standard PC might produce proper results.

**Comment by SmartFoxServer** [comment]
I can't see a reason why a virtual machine should interfere with the building process.
Is there a deeper log we could share with you, to understand what is going on?
Or, as a last resort, would it be possible to have an option not to generate the search feature?

**Comment by EWSoftware** [comment]
Short of debugging the build engine in that environment, I don't know of any other way to find out why it's not indexing the files.  If you don't want to see the search option, you can probably include a modified copy of the *.\\styles\\branding-Website.css* in the project that hides the search elements.  Add it in a *.\\styles* folder and set the Build Action to Content.

**Comment by SmartFoxServer** [comment]
We'll test the project on an actual PC (instead of a virtual machine) as soon as possible, and let you know here if it worked.

**Comment by SmartFoxServer** [comment]
I have additional information on the issue. It seems that it occurs if I load the project's files (dll, xml, etc) from a network drive only. If I copy all the files on the local filesystem, everything works fine (much more _fti_ files get generated and the search works as expected).
Is this something you can test? Thank you.

**Comment by EWSoftware** [comment]
I tried building from a network share and it worked as expected with the proper index files generated.  The location of the documentation sources (DLLs and XML comments) are irrelevant at that point.  The keywords are generated off of the compiled help topics which are in the working folder.  If the sources are out of date that might explain it but I think you'd see outdated info in the topics too.  You could try setting the working folder to a local drive if it isn't already to see if that makes any difference although, again, it shouldn't.

**Comment by SmartFoxServer** [comment]
It seems that did the trick. I set the working folder to the local drive, and now the file indexes are generated correctly. Thank you for your help.

**Comment by thomas1983** [comment]
Having the exact same problem. As you can see the folder does not contain all files as I gues it should start at 01.  It somewhat risky for me to attach the folder output as it is company-related info.

Search leads me to the result pages but states that it has found nothing, even if I use keywords from inside the fti files. 

![fti-folder](https://user-images.githubusercontent.com/29855562/66895492-3e21ba80-eff3-11e9-83ef-2dd64b97058c.PNG)

**Comment by EWSoftware** [comment]
@thomas1983 That's normal.  The numbers represent the ASCII value of the first character of the words indexed in the file.  You won't see all numbers represented, just files for letters starting words that were indexed, typically in the range from 95 to 122 (underscore and a through z).

**Comment by thomas1983** [comment]
Ah ok thanks, 

But still, the search isn't working for me. Tried all major browsers. Not that it is a huge problem for us but it would be a nice plus. 

It is just a warning but I do get a browser message:
_Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/_

Hope this will be of any assistance

**Comment by EWSoftware** [comment]
Are you running the website from the file system or through a server/IIS Express?  If just opening the files on the local file system, it will block a lot of the script.  Running it on a server or locally with IIS Express fixes that.  See the [SHFB site](http://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm) as an example.  The search works and there is no warning.

**Comment by thomas1983** [comment]
> 
> 
> Are you running the website from the file system or through a server/IIS Express? If just opening the files on the local file system, it will block a lot of the script. Running it on a server or locally with IIS Express fixes that. See the [SHFB site](http://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm) as an example. The search works and there is no warning.

Hi Eric, 

On an Ubuntu php server.

thanks for the followup
