### ISSUE TITLE
Build .net Core\Framework on Appveyor

### ISSUE THREAD

**Issue by raczeja** [EWSoftware/SHFB#725]
I'm getting following error  "error MSB4062: The "SandcastleBuilder.Utils.MSBuild.BuildHelp" task could not be loaded from the assembly" when building documentation on CI Appveyor, 
SHFB
 project: https://github.com/ObjectivityLtd/Ocaramba/blob/netCore22/Ocaramba.Documentation/Ocaramba.Documentation.shfbproj

I added `<SHFBROOT Condition=" '$(SHFBROOT)' == '' ">C:\Users\appveyor\.nuget\packages\ewsoftware.shfb\2019.6.24\tools</SHFBROOT>` to the first property group

what else can I change to have it working ?

More details here https://ci.appveyor.com/project/ObjectivityAdminsTeam/ocaramba/builds/25719453 

`   1>Done Building Project "C:\projects\ocaramba\Ocaramba.sln" (Build target(s)) -- FAILED.
     9>Project "C:\projects\ocaramba\Ocaramba.Documentation\Ocaramba.Documentation.shfbproj.metaproj" (9) is building "C:\projects\ocaramba\Ocaramba.Documentation\Ocaramba.Documentation.shfbproj" (7:6) on node 2 (default targets).
     7>C:\Users\appveyor\.nuget\packages\ewsoftware.shfb\2019.6.24\tools\SandcastleHelpFileBuilder.targets(40,3): error MSB4062: The "SandcastleBuilder.Utils.MSBuild.BuildHelp" task could not be loaded from the assembly C:\Users\appveyor\.nuget\packages\ewsoftware.shfb\2019.6.24\tools\SandcastleBuilder.Utils.dll. Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\projects\ocaramba\Ocaramba.Documentation\Ocaramba.Documentation.shfbproj]
     7>Done Building Project "C:\projects\ocaramba\Ocaramba.Documentation\Ocaramba.Documentation.shfbproj" (default targets) -- FAILED.
Build FAILED.
       "C:\projects\ocaramba\Ocaramba.sln" (Build target) (1:2) ->
       "C:\projects\ocaramba\Ocaramba\Ocaramba.csproj" (default target) (2:19) ->
       (GenerateNuspec target) -> 
         C:\Program Files\dotnet\sdk\2.2.203\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(199,5): warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [C:\projects\ocaramba\Ocaramba\Ocaramba.csproj]
       "C:\projects\ocaramba\Ocaramba.sln" (Build target) (1:2) ->
       "C:\projects\ocaramba\Ocaramba.Documentation\Ocaramba.Documentation.shfbproj.metaproj" (default target) (9) ->
       "C:\projects\ocaramba\Ocaramba.Documentation\Ocaramba.Documentation.shfbproj" (default target) (7:6) ->
       (CoreBuildHelp target) -> 
         C:\Users\appveyor\.nuget\packages\ewsoftware.shfb\2019.6.24\tools\SandcastleHelpFileBuilder.targets(40,3): error MSB4062: The "SandcastleBuilder.Utils.MSBuild.BuildHelp" task could not be loaded from the assembly C:\Users\appveyor\.nuget\packages\ewsoftware.shfb\2019.6.24\tools\SandcastleBuilder.Utils.dll. Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\projects\ocaramba\Ocaramba.Documentation\Ocaramba.Documentation.shfbproj]
    1 Warning(s)
    1 Error(s)
Time Elapsed 00:00:11.76
Command exited with code 1`

**Comment by EWSoftware** [comment]
It appears to not be able to find the  System.Windows.Forms assembly on which the SHFB assembly depends.  Is the full framework (at least .NET 4.0) not installed on the server?  I don't know anything about CI Appveyor so I can't offer any solutions.

**Comment by raczeja** [comment]
according to the list https://www.appveyor.com/docs/windows-images-software/ (I'm using Visual Studio 2017) there are several versions of .NET  installed
I'm migrating this project to .net Core, Building documentation used to work with .net Framework version of project  https://ci.appveyor.com/project/ObjectivityAdminsTeam/ocaramba/branch/master?fullLog=true

in new version Windows Server 2012 R2 was change to Windows Server 2016 as OS on build agent and Visual Studio 2015 to Visual Studio 2017

**Comment by EWSoftware** [comment]
The prior log uses MSBuild while the latest log uses "dotnet build".  At a guess, I'd say they two are not equivalent.  SHFB and its build tasks are all built against and use the full framework.

**Comment by raczeja** [comment]
Building documentation for migrated project to .net Core is working on my local machine, but I have “Help File Builder and Tools”  installed from https://github.com/EWSoftware/SHFB/releases, 
so without installed “Help File Builder and Tools” on Appveyor build agent I won't be able to build documentation for .net Core projects?

**Comment by EWSoftware** [comment]
You've probably also got the full framework on your location machine.  As I pointed out, that's the root cause of the problem: It can't find System.Windows.Forms.
