### ISSUE TITLE
Selecting "None" for Namespace Summaries results in build error

### ISSUE THREAD

**Issue by thomasjwalters** [EWSoftware/SHFB#728]
Selecting "None" in Project Properties | Summaries | Namespace Summaries results in an unexpected build error.  Error from log file is: Unexpected error adding namespace groups to reflection data.  Reason: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index. 

Note: After selecting None and attempting to build, the project file is corrupted.  (Make a backup before testing!)

**Comment by EWSoftware** [comment]
Excluding everything results in an empty help file.  I've added additional checks to detect this case when all namespaces are excluded.
