### ISSUE TITLE
Struct property accessor alignment issue in 2019.6.24.0

### ISSUE THREAD

**Issue by ClearScriptLib** [EWSoftware/SHFB#729]
This issue seems to affect structs only and is new in 2019.6.24.0. Here's a screenshot:

![image](https://user-images.githubusercontent.com/12966733/61808464-7016ec80-ae09-11e9-91c0-1679206d712e.png)

It affects multiple syntax languages, and both of the formats we're building (CHM and Website).

**Comment by ClearScriptLib** [comment]
Now it appears that this issue is _not_ specific to the new SHFB version after all. It affects documentation built from XML generated by Visual Studio 2019. Earlier versions of Visual Studio, combined with _any_ recent version of SHFB, produce correct documentation.

**Comment by EWSoftware** [comment]
I'm unable to duplicate this behavior.  Can you provide a small example that I can build?

**Comment by ClearScriptLib** [comment]
Our documentation is sourced almost entirely from XML comments. The SHFB files are [here](https://github.com/microsoft/ClearScript/tree/master/ClearScript/doc). We could also provide the XML output from Visual Studio. Will that suffice?

**Comment by EWSoftware** [comment]
I downloaded your project and built it and the help file with VS2019 version 16.2.2.  Both Help 1 and website output are as expected without the odd wrapping.  Perhaps it's something related to the system and/or browser itself.  I'm using Windows 10 and tried it with Edge, Chrome, and Firefox and it was formatted as it always was.

If it truly is something to do with the XML comments files or the actual website output, you should be able to do a file comparison on the output between the two versions to see what differs.

**Comment by ClearScriptLib** [comment]
Thanks for doing that testing. A question: Of the files that belong to our project or are generated by it, which serve as the inputs to SHFB? Is it just the .SHFBPROJ file and the generated _project_.XML?

**Comment by EWSoftware** [comment]
The .shfbproj file is the one that's built.  The documentation sources in it determine what gets documented.  In this case, it's the ClearScript.csproj file so it will use the DLL and XML comments file produced by it.  The build log will tell you which files are being used.

**Comment by ClearScriptLib** [comment]
Thanks again. We'll see if we can reproduce the issue with newer tools a bit later. Closing for now.
