### ISSUE TITLE
BUILD FAILED: The imported project "C:\Microsoft.Cpp.Default.props" was not found

### ISSUE THREAD

**Issue by Gaspa79** [EWSoftware/SHFB#733]
So basically, while using a c++ project that contains something like

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />

The GUI build doesn't work. Even though the VCTargetsPath does evaluate properly in visual studio when compiling.

Any ideas on how to solve this? =(

Thanks!

**Comment by EWSoftware** [comment]
Unlike Visual Studio, the standalone GUI doesn't know anything about the projects its loading so doesn't define any of the common variables.  If you use the Visual Studio extension to load and build the project is should work.  The workaround would be to define a conditional variable in the project that sets it to the appropriate path if not defined.

**Comment by Gaspa79** [comment]
I'd love to do the workaround. Do you have a starpoint where I can read about it? Like for starters I don't know if you're talking about the sandcastle project or the vs project.

Thanks a lot for your help!

**Comment by EWSoftware** [comment]
Put the variable in the SHFB project.  That way it will be defined when it loads the documentation source.  You can add it in the project properties on the [User Defined category](http://ewsoftware.github.io/SHFB/html/c4e3ce8e-6881-47a7-a429-49ec5c755c8c.htm).
