### ISSUE TITLE
Creating lists of topics based on tags

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#734]
I would like to add some pages to the TOC with lists of topics (and links) based on special XML tags. For example by adding a tag `<category>Category 1</category>`. Then list of topics should be created per category. I looked but could not find this.

Background info:

Our language (X#) is function based. Functions are converted by the compiler to static methods of a compiler generated (Functions) class. This list of functions is (historically) very long. If would be nice if we could produce categorized lists of "String functions", "Date functions", "Array functions" etc.

Is this somehow supported ?

If not, do you have any hints on what I need to do to produce this myself ?
Robert

**Comment by EWSoftware** [comment]
That would need to be done in the presentation style.  You could [create a presentation style](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) based on the existing one and then modify the XSL transformations to handle the custom tags.  If you need to modify the TOC based on the generated topics, you'd also have to replace the intermediate TOC XSL transform.  That's also part of the presentation style.  They all currently use a common transformation (CreateVSToc.xsl).
