### ISSUE TITLE
What is the concept for including help to my nuget package?

### ISSUE THREAD

**Issue by dmitrybv** [EWSoftware/SHFB#735]
Hello 

Suppose I have a library assembly with a set of classes.
And I can create different types of helps for the library using SHFB.
If I put the library in the nuget package and host it on the nuget server.
What is the best scenario to install library help in VS when user install a nuget package in his project?

I am thinking about adding code in Init.ps1 file for nuget package in 
which it will contain a script to install the msha file in VS Help System.

But as only one version of msha file can be installed in VS Help System 
and Init.ps1 will be run every time developer install the package 
for each project that the developer leads.
So may be it is not a good idea.

**Comment by EWSoftware** [comment]
The init.ps1 file is probably the only place to do it so it would run with each package install which is not ideal.  You also can't guarantee that the user has installed the help viewer components with their Visual Studio install.  Another option would be to provide a link to a separate help download that can be installed once.  Again, not ideal and either way, the help would be left behind if the package is removed so it would be up to the user to remove it.

In this case, you are probably better off generating website help and hosting it somewhere such as your own site or somewhere like [GitHub pages](https://pages.github.com/).  A link to the site can be provided in the package's Read Me file.  That's what I do for all of my packages.  All of my projects' help, including SHFB, is hosted on my [GitHub pages site](http://ewsoftware.github.io).  I publish the help content below a subfolder for each one on the main site.

To be honest, I think most help now is hosted on the web and very few actually bother creating and installing help within Visual Studio itself.  I think even Visual Studio defaults to online help and the help viewer isn't installed unless explicitly selected.

**Comment by dmitrybv** [comment]
Thank you.
Then a question about WebHelp.
If I have WebHelp somewhere on a web server,
is it possible to provide contextual help F1 (F1 in source code) in VS with reference to this help?

**Comment by EWSoftware** [comment]
As I understand it, registry changes need to be made to the Visual Studio hive in order for it to use third-party sites for web help in addition to its own site.  So, again, not useful for NuGet deployments.

**Comment by dmitrybv** [comment]
I wonder if the Website help generated by SHFB can be used as Context-sensitive Help (F1-Help) in VS.

There is a utility "HelpLibraryManagerLauncher.exe" in SHFB, that allow install chm and (msha + mshc) files to VS Help system, but it doesn't have parameters to install Website help. Why?

**Comment by EWSoftware** [comment]
The help library manager tool is only used to install the Help 2 content in the help collection.  The CHM format is Help 1 and does not require that tool as it's a standalone file and doesn't integrate with Visual Studio.  Visual Studio does not provide support for external website help beyond the mention of modifying the registry manually.  It's not something that's within the scope of the tool as it doesn't handle website content.

Messing with the registry is not something I'd want a NuGet package doing.  Chances are you'd run into rights restrictions anyway.  As with installing Help 2 content, it's best left as a standalone step that people can run if they want to.
