### ISSUE TITLE
$(TargetFramework) property not supported for XML path

### ISSUE THREAD

**Issue by Gwindalmir** [EWSoftware/SHFB#737]
I have a .NET SDK project, which builds our assembly for .NET 3.5, and .NET Standard 2.0.
What's in each assembly varies by version, so ideally I'd have separate documentation for each.

Now, support for that in SHFB is virtually non-existent from what I've seen, but that's not really the problem.

The problem is it can't find the XML file if I make the <DocumentationFile> element include the $(TargetFramework) property.

Simply adding the following:
```
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
```

Triggers the following error:
```
<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: C:\Temp\MultiTargetTest\MultiTarget\MultiTarget.csproj
    Found project &#39;C:\Temp\MultiTargetTest\MultiTarget\MultiTarget.csproj&#39;

Parsing project files
    Found assembly &#39;C:\Temp\MultiTargetTest\MultiTarget\bin\Release\net35\MultiTarget.dll&#39;
    Last step completed in 00:00:00.0460
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0065: BUILD FAILED: Project XML comments file does not exist: C:\Temp\MultiTargetTest\MultiTarget\bin\Release\\MultiTarget.xml
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ValidateDocumentationSources()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
```
Notice the double slash after `Release`, indicating the property was empty.

[MultiTargetTest.zip](https://github.com/EWSoftware/SHFB/files/3518086/MultiTargetTest.zip)

This is with Visual Studio 2017 15.9.7
SHFB 2019.6.24.0

**Comment by Gwindalmir** [comment]
For reference, I was able to work around it by using this instead:
```
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>
```
As documented here: https://github.com/dotnet/standard/issues/614#issuecomment-354273682

**Comment by EWSoftware** [comment]
That property is required in order for the .NETCore/.NETStandard format projects to create the XML comments file when built that SHFB looks for.  It won't create it otherwise.

**Comment by Gwindalmir** [comment]
I'm not sure what you mean, I never had to specify that property before to create the XML file. In fact the XML already exists, as we've already shipped it. I was simply making some changes to the build when I found this issue.

The sample project I submitted creates the xml file without the `GenerateDocumentationFile` property specified.

**Comment by EWSoftware** [comment]
A misunderstanding on my part then.  When I was learning about enabling XML comments for those project types, the two properties were always mentioned as a pair thus I've always thought of them as both required.
