### ISSUE TITLE
How to use go to definition?

### ISSUE THREAD

**Issue by tzm1119** [EWSoftware/SHFB#739]
Hi,I am a newer.
I use  vs2019 , and Sandcastle Help File Builder. I want to use the "go to definition"  function.
![image](https://user-images.githubusercontent.com/36020806/63630826-92db3180-c651-11e9-890e-b93c914eb6ce.png)

![image](https://user-images.githubusercontent.com/36020806/63630861-f5343200-c651-11e9-9fa5-ec0ec5da59f8.png)

![image](https://user-images.githubusercontent.com/36020806/63630953-2eb96d00-c653-11e9-8f19-69543cfcaa43.png)

![image](https://user-images.githubusercontent.com/36020806/63630962-514b8600-c653-11e9-9869-d4461f148ba1.png)

I can use "go to definition" in MAML file,but I can not use "go to definition" in c# source code file. Am I missing something?

thank you very much

**Comment by EWSoftware** [comment]
I removed the C# go to definition option as go to definition for types is built in.  However, I forgot about the support for conceptual links in code so I'll have to add that bit back in.
