### ISSUE TITLE
Installing SHFB non-interactively?

### ISSUE THREAD

**Issue by eli-darkly** [EWSoftware/SHFB#742]
Am I right that the only options for installing these tools currently are 1. use the guided installer or 2. build from source?

If so, I'd like to suggest providing an alternate packaging that can be installed from a script. This would be helpful for people who run their builds on a Windows CI service and don't have access to the GUI.

**Comment by EWSoftware** [comment]
You can just run the MSI installer and the VSIX installer from the .\InstallResources folder if you like.  Both provide options for silent installs.

**Comment by eli-darkly** [comment]
Thanks. It might be worth adding a note about that to the Getting Started docs. Maybe it would be obvious to someone with more Windows experience, but it wasn't to me.

**Comment by EWSoftware** [comment]
I've added a note about manually running the installers to the Installation Instructions topic for the next release.
