### ISSUE TITLE
Sandcastle 1.7.0.0 Download

### ISSUE THREAD

**Issue by smckinney94** [EWSoftware/SHFB#745]
Hi Eric, 
Is there anywhere I can download Sandcastle 1.7.0.0 from ? 
Sean.

**Comment by EWSoftware** [comment]
There isn't anywhere you can get a version that old that I'm aware of.  The earliest release here is v2015.1.12.0.  All older versions were hosted on CodePlex and were lost when it shut down.  Going back that far you'd also have to find a matching set of the Sandcastle Tools which were being managed by Microsoft at that time.

**Comment by twocs** [comment]
The 204 MB archive on Codeplex https://archive.codeplex.com/?p=shfb has a releases folder. Inside each are zip files (without extensions). They are not well documented so I cannot tell what's what, but maybe they are the releases from Codeplex?

Direct link: https://codeplexarchive.blob.core.windows.net/archive/projects/SHFB/SHFB.zip

**Comment by EWSoftware** [comment]
Those are only the public releases.  All of the hidden ones, the older releases prior to 1.9.3.4, are not there.  There's a JSON file in the .\releases folder that maps the IDs to the folders (releaseList.json).  Folder 3 just contains the Sandcastle tools that were used at the time for the SHFB releases that are included.

**Comment by twocs** [comment]
@EWSoftware Yes, you understand what the files are much better than me. Rereading the readme, I see that it says "Install the Sandcastle May 2008 release" but the release isn't included.

As for the Sandcastle.msi created on May 28, 2008, the binary installer still seems to be available in the MS archives:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=10526

The comments says, "This installer database contains the logic and data required to install Sandcastle." The version number is given as 2.4.10520.
![image](https://user-images.githubusercontent.com/72763/66291058-5bd28e00-e928-11e9-83bb-0f77814c5339.png)
