### ISSUE TITLE
Build error in ci farm

### ISSUE THREAD

**Issue by jmecosta** [EWSoftware/SHFB#746]
hi,

<buildStep step="TransformReflectionInfo">
Transforming reflection output...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe - TransformManifest.proj]
Build started 30/09/2019 21:42:28.
Project &quot;D:\prod\structures\BuildDrop\Work\Sandcastle\TransformManifest.proj&quot; on node 1 (default targets).
TransformManifest:
  XslTransform (v2019.9.15.0)
  Copyright &#169; 2006-2019, Microsoft Corporation, All Rights Reserved.
  Portions Copyright &#169; 2006-2019, Eric Woodruff, All Rights Reserved.
XslTransform : error : The transform file &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\\ProductionTransforms\ApplyVSDocModel.xsl&#39; could not be loaded. The error is: Could not find a part of the path &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\ProductionTransforms\ApplyVSDocModel.xsl&#39;. [D:\prod\structures\BuildDrop\Work\Sandcastle\TransformManifest.proj]
Done Building Project &quot;D:\prod\structures\BuildDrop\Work\Sandcastle\TransformManifest.proj&quot; (default targets) -- FAILED.
    Last step completed in 00:00:00.2250
</buildStep>

Tools are correctly located

Finding tools...
The Sandcastle tools are located in &#39;D:\prod\structures\Packages\EWSoftware.SHFB.2019.9.15\tools\&#39;
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in &#39;C:\Program Files (x86)\HTML Help Workshop\&#39;
Locating components in the following folder(s):
    D:\prod\structures\MSBuild\..\Packages\EWSoftware.SHFB.NETFramework.4.7\tools\Data\.NETFramework\
    D:\prod\structures\DotNetInterface
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins\
    D:\prod\structures\Packages\EWSoftware.SHFB.2019.9.15\tools\

I would expect SHFBROOT set to proper location that this
C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\\ProductionTransforms
wouldnt be seen in log. 

im using the package from nuget.org and it contains the files

![image](https://user-images.githubusercontent.com/1041352/65906885-f6344e00-e3cb-11e9-9e78-3dc07cf521d7.png)

**Comment by EWSoftware** [comment]
Have you [defined SHFBROOT in your project](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) to point to the tools folder?  If it's conditional and SHFBROOT does happen to be defined on the server in an environment variable, it would override it so that's the first thing to check.

**Comment by jmecosta** [comment]
yep, it mostly works! it track it down to a custom style we have  
![image](https://user-images.githubusercontent.com/1041352/65914719-942f1500-e3da-11e9-9fd9-647b52e3d93d.png)

for some reason if i use SHFBROOT in the custom style it comes out with program files... u can see that actually the SHFBROOT  since 

"
Finding tools...
The Sandcastle tools are located in 'D:\prod\structures\Packages\EWSoftware.SHFB.2019.9.15\tools
"

i do copy our custom style under D:\prod\structures\Packages\EWSoftware.SHFB.2019.9.15\tools\PresentationStyles and that is detected... 
![image](https://user-images.githubusercontent.com/1041352/65914862-db1d0a80-e3da-11e9-9b6e-a4336787ad1a.png)

but if i run with the %SHFBROOT% it comes up like that... if doing ..\..\ then it works fine... but thats not optimal because if i want to deploy to custom style to ProgramData is not going to work

are those correctly expanded if passed from  custom style?

**Comment by jmecosta** [comment]
well bummer, now nother works anymore! 

<buildStep step="Failed">

SHFB: Error BE0065: BUILD FAILED: Cannot cast the underlying exported value of type &#39;OpenApiStyle.OpenApiStyle (ContractName=&quot;Sandcastle.Core.PresentationStyle.PresentationStyleSettings&quot;)&#39; to type &#39;Sandcastle.Core.PresentationStyle.PresentationStyleSettings&#39;.
   at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.ExportServices.&lt;&gt;c__DisplayClass11_0`2.&lt;CreateStronglyTypedLazyOfTM&gt;b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>

**Comment by jmecosta** [comment]
@EWSoftware the previous error is caused by the fact that we have the old style in C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins so if we place under SHFROOT is still looks that one... how can i make sure the new style is in use... i cant dlete the C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins because it will break older versions

**Comment by EWSoftware** [comment]
The folders are [searched in a specific order](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm).  If duplicate components are found, the first one found is used based on the folder search order.  The ComponentPath folder takes precedence so if it is placed there, that is the one that will be used.

**Comment by jmecosta** [comment]
@EWSoftware this is indeed the case! ive change the deployment to ComponenetPath and now it doesnt clash anymore.
