### ISSUE TITLE
Support for netstandard 2.1?

### ISSUE THREAD

**Issue by ritchiecarroll** [EWSoftware/SHFB#747]
Hi Eric,

Was building a new library using VS2019 and targeting .NET Standard 2.1, is this supported yet or do I need to update something in the config for it? See build log details below...

Thanks.
Ritchie

```
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe - GenerateRefInfo.proj]
Build started 10/3/2019 10:42:24.
Project &quot;D:\Projects\gemstone\threading\src\DocGen\Help\Working\GenerateRefInfo.proj&quot; on node 1 (default targets).
PrepareForBuild:
  Creating directory &quot;obj\Debug\&quot;.
GenerateRefInfo:
  MRefBuilder (v2019.9.15.0)
  Copyright c 2006-2019, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2019, Eric Woodruff, All Rights Reserved.
  No source code context base path specified.  Source context information is unavailable.
  Loaded 1 assemblies for reflection and 1 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: netstandard (netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) required by gemstone.threading [D:\Projects\gemstone\threading\src\DocGen\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:00.8710
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0065: BUILD FAILED: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
```

**Comment by ritchiecarroll** [comment]
FYI, .NET Standard 2.0 seems to work OK...

**Comment by EWSoftware** [comment]
What framework version are you using in the SHFB project?  If you use the Cross-Platform option, it should work.

**Comment by RobThree** [comment]
> What framework version are you using in the SHFB project? If you use the Cross-Platform option, it should work.

I have the same issue; I'm trying to build a .Net Core 3.0 project:

	...
	...
	GenerateBindingRedirects:
	  No suggested binding redirects from ResolveAssemblyReferences.
	GenerateRefInfo:
	  MRefBuilder (v2019.4.14.0)
	  Copyright © 2006-2019, Microsoft Corporation, All Rights Reserved.
	  Portions Copyright © 2006-2019, Eric Woodruff, All Rights Reserved.
	  No source code context base path specified.  Source context information is unavailable.
	  Loaded 1 assemblies for reflection and 1 dependency assemblies.
	MRefBuilder : error : Unresolved assembly reference: netstandard (netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) required by MyProject [D:\path\to\project\ProjectDocumentation\Help\Working\GenerateRefInfo.proj]
		Last step completed in 00:00:05,1281
	</buildStep>
	<buildStep step="Failed">

	SHFB: Error BE0065: BUILD FAILED: Unexpected error detected in last build step.  See build log for details.
	   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
	   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
	   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by ritchiecarroll** [comment]
Hi Eric,

I have confirmed that:

1) The Framework version in the `shfbproj` is cross-platform
2) netstandard2.0 works
3) netstandard2.1 fails:

```xml
<TargetFramework>netstandard2.1</TargetFramework>
```

This is in Visual Studio 2019 Community.

Thanks!
Ritchie

**Comment by ritchiecarroll** [comment]
Here is an example project you can test:

https://github.com/gemstone/threading

**Comment by RobThree** [comment]
Hmm, I was under the assumption I was on the latest version but I guess that I only updated my personal workstation and not the workstation @work. I was on v2019.4.14.0.

I updated to v2019.9.15.0 and now I get (in VS2019):

	1>------ Build started: Project: MyProjectDocumentation, Configuration: Release Any CPU ------
	1>		Building D:\path\to\myproject\MyProjectDocumentation.shfbproj
	1>		Initializing
	1>		ClearWorkFolder
	1>		ValidatingDocumentationSources
	1>SHFB(0,0): error BE0065: BUILD FAILED: The framework version is set to Cross-platform (.NET Core/.NET Standard) but no reference assemblies were specified.  Unable to determine core types assembly.  See the error number topic in the help file for more information.
	1>		Failed
	========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

And in the logfile:

	...
	...
	<buildStep step="ClearWorkFolder">
	Clearing working folder...
	</buildStep>
	<buildStep step="ValidatingDocumentationSources">
	Validating and copying documentation source information
	Source: D:\path\to\project\bin\Release\netstandard2.1\MyLib.dll
		Found assembly 'D:\path\to\project\bin\Release\netstandard2.1\MyLib.dll'
	Source: D:\path\to\project\bin\Release\netstandard2.1\MyLib.xml

	Copying XML comments files
		D:\path\to\project\bin\Release\netstandard2.1\MyLib.xml -&gt; D:\path\to\projectDocumentation\Help\Working\MyLib.xml
		Last step completed in 00:00:00,0080
	</buildStep>
	<buildStep step="Failed">

	SHFB: Error BE0065: BUILD FAILED: The framework version is set to Cross-platform (.NET Core/.NET Standard) but no reference assemblies were specified.  Unable to determine core types assembly.  See the error number topic in the help file for more information.
	   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

	</buildStep>
	</shfbBuild>

**Comment by EWSoftware** [comment]
@RobThree If you use the assembly and XML comments file as the documentation source and the Cross Platform framework type, there isn't enough information to resolve all of the necessary reference assemblies.  In such cases, you must add all of the necessary references to the SHFB project.  Your better off using the assembly's solution or project file as the documentation source so that SHFB can examine them and figure out all of the reference assemblies needed for you.

**Comment by RobThree** [comment]
That solved it (though still lots of warnings even though I have documented everything; I'll need to look into that but could be entirely my mistake).
So, in the end, for me, the issue was that I was on an old version of SHFB; updating to the latest version got it to document my project.

**Comment by ritchiecarroll** [comment]
@EWSoftware -- unlike RobThree, my issue persists.

I am using latest SHFB release build, v2019.9.15.0. FYI. Updated to very latest VS 2019 this morning, v16.3.4, with the same results.

I note that I consistently get the following error, 2.0 or 2.1, which I think is unrelated but it is certainly not valid:
```
MRefBuilder : warning : The program database (PDB) file associated with &#39;D:\Projects\gemstone\threading\build\Release\netstandard2.0\gemstone.threading.dll&#39; is out of date.  Source context information is unavailable. [D:\Projects\gemstone\threading\docs\help\Working\GenerateRefInfo.proj]
```
After debugging of `MRefBuilder` to find out why `netstandard2.1` fails when `netstandard2.0` works I find that for .NET Standard 2.0, references come from here:
```
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\ref\
```

I note that in that location there is no `netstandard2.1` folder. Even though my library project builds from Visual Studio just fine for .NET Standard 2.1, I am really not sure "where" the binaries live.

Also, as a secondary test I am installing VS 2019 (fresh install) with latest SHFB on a separate machine to see if the issue persists there as well...

If you want to debug also, you can clone `https://github.com/gemstone/threading.git` and edit the `gemstone.threading.csproj` project file changing `<TargetFramework>netstandard2.0</TargetFramework>` to `<TargetFramework>netstandard2.1</TargetFramework>`. Ultimately I want to multi-target the library, like so:
```
<TargetFrameworks>netstandard2.1;netstandard2.0</TargetFrameworks>
```

Thanks,
Ritchie

**Comment by ritchiecarroll** [comment]
FYI - same issue from fresh install on separate machine.

**Comment by EWSoftware** [comment]
I haven't had a chance to look at it yet.  As a workaround, you can try specifying the targets in the opposite order (netstandard2.0 first then netstandard2.1).  SHFB only uses the first target it finds so that may work around the issue with 2.1 not working.

**Comment by ritchiecarroll** [comment]
Sure - that works. FYI - this is not holding me up - I can document against 2.0 - just wanted you to be aware.

Thanks!
Ritchie

**Comment by EWSoftware** [comment]
When .NETStandard 2.0 is used, there's a package reference available when the project is loaded so it's able to find the assemblies it needs to resolve.  When using .NETStandard 2.1, the package reference is not there anymore so it can't find any assemblies needed to resolve the references.  I don't have a fix for this.  For now, the workaround of listing .NETStandard 2.0 first will have to be used.  I'll take a look at it later when I have more time.

**Comment by ritchiecarroll** [comment]
No worries - thanks for your continued investment.

**Comment by thomaslevesque** [comment]
>  SHFB only uses the first target it finds so that may work around the issue with 2.1 not working.

Would you consider adding the ability to specify the desired target framework explicitly?

Do you have plans to actually support multiple targets, with TFM-specific information? e.g. like the "Applies to" section on MS docs?

**Comment by EWSoftware** [comment]
It would be possible to support specifying which target framework to use.  It could be a property on the documentation source like the configuration and platform.  If not specified, it could pick the first one as it currently does.

Version information is supported to a certain extent through the [Version Builder plug-in](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm).  It can be used to come close to platform support information but not entirely.  There is some platform support in the presentation styles but the version builder tool has never fully supported it.  There hasn't been much demand for it over the years so I haven't taken any time to look into what it would take to fully support it.

**Comment by thomaslevesque** [comment]
> It would be possible to support specifying which target framework to use. It could be a property on the documentation source like the configuration and platform. If not specified, it could pick the first one as it currently does.

That would be perfect!

> Version information is supported to a certain extent through the [Version Builder plug-in](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm). It can be used to come close to platform support information but not entirely. There is some platform support in the presentation styles but the version builder tool has never fully supported it. There hasn't been much demand for it over the years so I haven't taken any time to look into what it would take to fully support it.

I'm surprised there hasn't been more demand. These days, most reasonably popular libraries use multi-targeting (typically netstandard1.*, netstandard2.0 and net4*). I'll look into Version Builder, thanks!

**Comment by ritchiecarroll** [comment]
Hi Eric,

I haven't checked in for a while, as we are on the cusp of a NET 5.0 deployment which will all but leave the the framework behind - have you given any more thoughts to the DotNetCore branch?

Thanks,
Ritchie

**Comment by EWSoftware** [comment]
I think I've finally got all of the issues with the implicit package references resolved so that .NET Standard 2.1 and the new .NET 5.0 project types can be used directly as documentation sources.  The changes will be in the next release due out soon.
