### ISSUE TITLE
Unexcepted error detected in last build step. ESentResolveReferenceLinksComponent: Primary index is corrupt.

### ISSUE THREAD

**Issue by scegg** [EWSoftware/SHFB#749]
Error in building docs.

Here is the last part of the building log:
`BuildTopics:
  BuildAssembler (v2019.9.15.0)
  Copyright c 2006-2019, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2019, Eric Woodruff, All Rights Reserved.
  Loading configuration...
BuildAssembler : error :  [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
BuildAssembler : error : ESentResolveReferenceLinksComponent: Primary index is corrupt. The database must be defragmented [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
BuildAssembler : error :  [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Resolve Reference Links (ESENT Cache)&#39;. The error message is: See log for details [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
BuildAssembler : error :  [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Multi-format Output Component&#39;. The error message is: See log for details [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
BuildAssembler : error :  [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Switch Component&#39;. The error message is: See log for details [D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj]
Done Building Project &quot;D:\VSProjects\scegg\RemoteHub\docs\Working\BuildTopics.proj&quot; (default targets) -- FAILED.
    Last step completed in 00:00:01.6659`

**Comment by scegg** [comment]
Tried to remove and re-add the Resolve Reference Links (ESENT Cache), not fixed.

**Comment by scegg** [comment]
By removing Resolve Reference Links, it built without any problem now.
I don't find anything in built docs related to this removal yet.

**Comment by scegg** [comment]
Workaround:
Delete the cache folder and add xml/dll files directly to documentation sources.

**Comment by EWSoftware** [comment]
See the [v2019.8.24.0 release notes](http://ewsoftware.github.io/SHFB/html/3bb3e240-7c36-456b-bebd-972ff1508c15.htm).  The format of the database changed to support the new link resolver.  This was a breaking change that requires any old version of the cache databases be deleted and the components be deleted, re-added, and configured in the project.

**Comment by scegg** [comment]
hmm. my problem seems to be related to multi targets building also. All referenced projects are set to build on more than one target frameworks. By adding xml/dll files as well as the project files, the problem is gone for good.

**Comment by EWSoftware** [comment]
I don't think multi-targeting has anything to do with it.  SHFB only picks the first target in that case.  I just downloaded your project and it built without any problems using just the projects as documentation sources after removing the assemblies and XML comments files as documentation sources.

**Comment by scegg** [comment]
Thanks for your clarification. I found the problem: after I add the last project to "Documentation Sources", the project is not selected under "Project Dependencies". When SHFB doc building, the project is not built in advanced. After select it, I can remove all xml/dll files from "Documentation Sources".

I cleaned all caches to make sure that the my found is the only reason.

This issue could be closed now. Thanks for your help again.

Now I need to face how to reference the Redis docs in mine...

**Comment by scegg** [comment]
> I don't think multi-targeting has anything to do with it. SHFB only picks the first target in that case. I just downloaded your project and it built without any problems using just the projects as documentation sources after removing the assemblies and XML comments files as documentation sources.

There is a small problem related but not in my case.
If:
the projects have multi-targets;
the targets of all projects are not listed in the same sequence; and,
methods defined are not exactly same on different targets (#if block used).
Then:
Maybe some documentation node will be missing?

If so, it's a good idea to clear it in documentation, known issues section for example, make sure the sequences of targets should be remained same among projects, at least the 1st target should be same.
