### ISSUE TITLE
Cannot build with Code Block Component enabled. Missing files.

### ISSUE THREAD

**Issue by MulleDK19** [EWSoftware/SHFB#75]
I can't build my help project with the Code Block Component is enabled. It's looking for files in a folder called Colorizer, which does not exist. I've tried repairing the installation but the folder is just not included.

**Comment by EWSoftware** [comment]
Have you added the Code Block Component to your SHFB project?  If so, remove it and re-add it as the configuration needs to be updated because the files did move.

**Comment by MulleDK19** [comment]
Yea. Readding it fixed it. Thanks!
