### ISSUE TITLE
Add an Example for ProjectExplorerWindow Class

### ISSUE THREAD

**Issue by gowthamguptha** [EWSoftware/SHFB#750]
Please add an example for ProjectExplorerWindow Class.

I want to filter the left-hand navigation before displaying in the help filer using custom presentation.

Help Topic: https://ewsoftware.github.io/SHFB/html/9e42ed08-9138-0c86-23bc-50f8f5c7acd0.htm

**Comment by EWSoftware** [comment]
What do you want to filter?  The topics?  There is a search option already.

**Comment by gowthamguptha** [comment]
Hi Eric,

I am doing custom  presentation via code. When I doing I have requirement
that I need to show only methods in the table of contents others I should
not show. So how can I manage this via code?

**Comment by EWSoftware** [comment]
You'd probably have to create a custom TOC transformation and perhaps modify the TOC plug-in to add extra attributes to the TOC nodes to identify what type of member they are (property, method, event, etc.).  Your client-side script would then have to do something to show or hide the nodes based on the filter settings.  Web development isn't my thing so I can't really provide any guidance on how you might go about doing that.
