### ISSUE TITLE
Understanding how TOC navigation occurs in SandCastle

### ISSUE THREAD

**Issue by dkemlage** [EWSoftware/SHFB#751]
Hello Eric,

My company creates multiple .NET platform API's for one of our products. It is starting to become unwieldy to manage a corporate website that has multiple SandCastle generated website TOC's for essentially the same API product just compiled on different platforms (WPF, UWP, Xamarin.Forms, Xamarin.Android, Xamarin.iOS, .NET Core, etc). 

There is a desire in our company to go to an aggregate shared TOC that spans all the .NET platforms for our API product. Something similar to what Microsoft docs has with their "Applies To" section of their API reference pages. See the following screen shot:
![image](https://user-images.githubusercontent.com/5495810/66762951-cc633880-ee5b-11e9-8611-c7fb66bc4a04.png)

We have used SandCastle for many years and the results have been awesome. Over the years, we have created custom build processes that have really enhanced the information that is displayed in our SandCastle generated API pages. 

One part of our custom build process identifies the full API signature for each member type found in the SandCastle generated .html pages and lists them in a master ASCII text file. Comparing the full set of member type signatures across 5 platform API SandCastle builds should not be an over difficult issue to solve to generate a master "Applies To" listing.

The challenge would be how to inject a type (with its accompanying .html page) from one platform (say from Xamarin.Android) into the TOC for another platform (say WPF). From my understanding the TOC navigation is based on JavaScript functions baked into the SandCastle generated .html pages during the build process. 

Do you have any recommendations on how this might be accomplished via SandCastle? Is there already a SandCastle add-on/extension or something else available that could do this? Have you considered adding capability as a future enhancement for SandCastle? 

I really look forward to hear your thoughts.

Thanks,
-Don Kemlage

**Comment by EWSoftware** [comment]
The [Version Builder plug-in](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm) does this to a certain extent.  It takes multiple versions of an assembly and lets you merge them into a single help file.  Each topic contains a section with the framework label and versions to which the member applies.  In this case though, the framework label and versions apply to your assemblies, not the .NET Framework types (platforms).

There is some .NET platform related support built into the transformations but it was never fully implemented as I recall.  I didn't get an requests to support it so I haven't looked into it in a long time.
