### ISSUE TITLE
Visual Studio 2019 and .NET Core 3.0

### ISSUE THREAD

**Issue by tandreasr** [EWSoftware/SHFB#752]
Hi,
I've just installed and tested the latest version 2019.9.15.0 inside VS2019.
Before my project used VS2017 and .NET Core 2.0, where Sandcastle worked just as expected.
But now I had to upgrade both VS and .NET Core and it doesn't work any longer.
I've attached the __build.log for reference.

There are some things which I observed:

1.) Parsing project files:
     here it now finds the EXE (instead of the DLL in VS2017/2.0)
2.) GenerateRefInfo:
     No source code context base path specified.  Source context information is unavailable.
     Loaded 0 assemblies for reflection and 157 dependency assemblies.
     Wrote information on 0 namespaces, 0 types, and 0 members
3.) Finally resulting in:
    SHFB: Error BE0065: BUILD FAILED: No APIs found to document. 

Do you have any clue?
Best regards
Andreas Rost

[__build.log](https://github.com/EWSoftware/SHFB/files/3766428/__build.log)

**Comment by EWSoftware** [comment]
If you can duplicate it with a simple test project, that's all I need.

**Comment by tandreasr** [comment]
Hi Eric,
I've stripped down my project in order to be allowed to send it to you.
So don't expect anything meaningful :-)
But it reproduces the error inside VS2019.
Best regards,
Andreas Rost
[__StrippedProject.zip](https://github.com/EWSoftware/SHFB/files/3770875/__StrippedProject.zip)

**Comment by EWSoftware** [comment]
The output type of the project is Exe thus SHFB look for and finds an executable.  However, in this case, it appears to be some sort of native code runtime host thus it doesn't contain any of the actual code.  That ends up in an DLL assembly in the same folder with the same base name.  I've added a check to the build engine that checks the `TargetExt` property and if it isn't ".exe" when the output type is Exe, uses the `TargetExt` value instead which in this case is ".dll".  That should resolve this.  I'll be publishing an update soon with the fix.
