### ISSUE TITLE
Wrong constructor generic signature and file still open error

### ISSUE THREAD

**Issue by catester** [EWSoftware/SHFB#755]
I got the same error as in #698 and I discovered ".. file is being used by another process" error is caused for consecutive builds if WorkingPath was not cleared. Normally this folder can be overwritten by SHFB so something was weird. I examined the HTML file in the error and saw that actually there was a doc generating problem in this file. So SHFB was having a problem during writing this file and it left this file open (not disposed) because of it.

In my case, the doc generating problem is caused by this class which have 2 similar constructors:

```c#
public Class1(Class2 param1, Func<byte[]> param2)
{
}

public Class1(Class2 param1, Func<Stream> param2)
{
}
```

The second parameter generic `Func<T>` is not resolved correctly and for both constructors a file with same name, "Class1__ctor_2.htm" is generated. So in the docs, 2 different constructors are listed with same signature:

```c#
public Class1(Class2 param1, Func param2)
{
}

public Class1(Class2 param1, Func param2)
{
}
```

and XmlComments for the  parameters are ignored ([Missing <param name="param1"/> documentation for ...) for these constructors.

So it seems there is a problem handling generic parameters in SHFB, I am using **2019.9.15.0**.

**Comment by EWSoftware** [comment]
As noted I the referenced issue, the file access problem is most likely related to a virus scanner scanning the files.  Exclude the folder from its scans to work around it.  The problem with the method signature is most likely due to selecting an incorrect framework version in the SHFB project.  If you use the solution or project as the documentation source SHFB should figure out the right framework version to use.  That may not happen if you are using a .NET Core or .NET Standard project.  In that case, use the Cross-Platform option for the framework version.

**Comment by catester** [comment]
Ok I solved the problem. For future reference:

1. It's not about virus scanner (Windows 10 machine with only Defender).
2. The error was intermittent but consistently happened for a specific project out of 4 projects but not on every build. Probably because that specific project had multiple constructors that are likely to conflict (if corlib type was not resolved correctly)
3. It's not about obfuscated DLLs, it happened also with clean DLLs.

In my case the problem was that I had a wildcard reference to a folder which contained netstandard.dll (the facade DLL was there for some cross compiling).
The actual project was targetting .NET Framework 4.0 but the presence of netstandard.dll caused SHFB to confuse corlib types like Func<>, after removing that DLL, the build completed without errors and all missing parameter comments are restored.

By the way, is it possible to display something like "Supported in .NET Framework 4.0 and .NET Standard 2.0" (similar to microsoft docs) if we add both net40 and netstandard2.0 targeted DLL to .shfbproj ?

**Comment by EWSoftware** [comment]
You can use the [Version Builder plug-in](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm) to do something similar to the "supported in" info in the Microsoft Docs.
