### ISSUE TITLE
Installer doesn't check for .NET 4.7.2

### ISSUE THREAD

**Issue by Gwindalmir** [EWSoftware/SHFB#757]
So, I made some changes to my build project to also document my .NET standard assembly, but at the same time upgraded from 6.24 to 9.15 to fix the MSDN links. This worked fine on my local machine (Win 10), but as soon as I ran the build on our build machine (Win 7), I got several errors:

> MRefBuilder : error : Unresolved assembly reference: netstandard (netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)

I tried adding the AssemblyBinding plugin to ignore the reference, but then encountered this error:

> Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

I did some sleuthing, and determined it was related to .NET 4.7. Since this particular machine is a build machine, it's not updated regularly except for security updates (still on VS 2017 15.9.4).
I noticed .NET 4.7 was installed (4.7.0).
I loaded Visual Studio installer, selected .NET Core Runtime, and .NET 4.7.2 SDK and Targeting pack, and installed them.

Once I rebooted, the build was successful, no errors of any kind, just like on my development machine.

When I upgraded, I just downloaded the most recent release, extracted and ran the installer, like usual. It didn't report any issues with the .NET Framework runtime.

I guess it only checks for .NET 4.7, not specifically the .NET 4.7.2 point release.

**Comment by EWSoftware** [comment]
The installer only checks for a minimum .NET version the tools are built against (currently .NET 4.5).  Anything higher than that is optional and it won't check for nor force you to install them.

Typically, the documented assemblies are built just before the help file so if they fail to build they won't exist for SHFB to find if it even gets that far.  As such, the build engine doesn't check for framework existence either.  However, if it can't find the targeting pack which is uses for the reference assemblies and comments, it does issue a warning so there was probably a warning earlier in the build log about it redirecting to the nearest available version.  For .NET Core/.NET Standard all references comes from NuGet packages so there's no targeting pack to find and it has to rely on what it can find in the documentation source projects for references and their comments files.

**Comment by Gwindalmir** [comment]
Problem is, I don't even target .NET 4.7 for anything.
The particular assembly is multitargeted for .NET 3.5 and .NET Standard, which yes, I get a warning, as it tells me it redirects to .NET 4.5.2. However I've always received that warning, and it doesn't seem to cause a problem.
I've tried, but I don't understand why it says that, or how to fix it.

Only thing that might reference .NET 4.7.2 is .NET standard 2.0, which is what I target as well. It's supposed to work against .NET 4.6.1 though. Microsoft says .NET 4.6 might have issues with nuget references, but this assembly doesn't have any nuget references, so that note shouldn't apply.

In all, if you don't target it specifically, I don't understand why it wants 4.7.2, since I don't use it at all.
In fact, the product itself only requires 4.5, and is what is installed, and everything works fine on end-user machines.

**Comment by EWSoftware** [comment]
Based on your original post, I thought the error was coming from MRefBuilder looking for a missing reference.  With the additional context, I can see that it's actually the build engine throwing an exception.  I do reference System.ValueTuple in it (through the NuGet version) and it is deployed as part of the installed file set.  You should see it in the SHFBROOT folder.

I'm not sure why it wouldn't find it in your particular setup.  Installing .NET 4.7.2 works around it as it's a part of that framework version so it finds it by default in the GAC.

**Comment by Gwindalmir** [comment]
That's correct, I saw the file in the folder.

According to dotPeek, that particular file is built for the 4.7.2 runtime.
![image](https://user-images.githubusercontent.com/1127170/68008051-c2eb1600-fc3a-11e9-818c-27b83b24f807.png)

**Comment by EWSoftware** [comment]
When built, it's choosing the .NETStandard 1.0 assembly from the package.  I was under the impression that should work with .NET 4.5 and up but that doesn't appear to be the case.  Anyway, I'll probably just remove it and move all the projects up to .NET 4.7.  It's been three months since I started using it and this is the first report of an issue so moving up to the newer framework is probably the better choice.
