### ISSUE TITLE
Include common content into AML file

### ISSUE THREAD

**Issue by ritchiecarroll** [EWSoftware/SHFB#758]
I am creating a suite of libraries, each with its own help file. I would like to "include" a common set of MAML into the default developerConceptualDocument topic - like an "about section" that would live in a separate file.

For example, if you had a file like "AboutProj.aml":
```
    <section>
      <title>About the XYZ Library</title>
      <content>
        <para>
          The XYZ Library is a collection of handy open source .NET code assemblies based on...
        </para>
        <para>
          See other XML Library Projects:
        </para>
      </content>
    </section>
```
Can this be "included" in the source MAML with some tag like:
```
<include filename="..\..\AboutProj.aml" />
```

Sorry if this is a common question, but after some searching, I'm still not finding an easy way to do this.

I did find a `token` tag that might be an option, but it doesn't look like the right use case.

Thanks,
Ritchie

**Comment by EWSoftware** [comment]
A token should work.  It's typically used as an inline element but there shouldn't be anything stopping it from being used as a top level element to pull in an entire section.  The only thing to ensure is that if you put addresses on anything such as the section element, just make sure they're unique and not used anywhere else.

**Comment by ritchiecarroll** [comment]
By prefixing all MAML tags with `<ddue:...>`, the token option for "includes" seems to work fine.

I'll just synchronize the token file among help projects.

Thanks for your help!

Ritchie
