### ISSUE TITLE
Member ID URL resolver service failed

### ISSUE THREAD

**Issue by cjwatterson** [EWSoftware/SHFB#762]
Hi, I just discovered our generated help files are no longer linking to MSDN docs. I've tried the latest version of Sandcastle (2019.9.15.0) and I'm getting the following errors. I've remove some details from the log for privacy reasons.

BuildAssembler : warning : ResolveReferenceLinksComponent: [N:MYASSEMBLYNAME] Member ID URL resolver service failed.  No further look ups will be performed for this build. [SNIP\Docs\BuildTopics.proj]
BuildAssembler : warning : Reason: The underlying connection was closed: An unexpected error occurred on a send. [SNIP\Docs\BuildTopics.proj]
BuildAssembler : warning : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. [SNIP\Docs\BuildTopics.proj]
BuildAssembler : warning : An existing connection was forcibly closed by the remote host [SNIP\Docs\BuildTopics.proj]

**Comment by EWSoftware** [comment]
It appears that the server hosting the resolver service requires TLS 1.2 now when connecting.  The tools are build using .NET 4.5 which doesn't use that by default.  I'll push out an update this weekend that explicitly sets it for the connection it to work around it until I update to a later version of the .NET framework.
