### ISSUE TITLE
The file path contains a comma or '.h' which may cause the Help 1 compiler to fail

### ISSUE THREAD

**Issue by wim07101993** [EWSoftware/SHFB#766]
Unfortunately this is a limitation with the Help 1 compiler (noted in the FAQ and also in a warning in the log file ([BE0060](http://ewsoftware.github.io/SHFB/html/e076c319-ff84-40dc-bb00-ff4c72718215.htm)).  It's actually the ".h" that is the issue.  It also has problems with commas in the path.  A period by itself is fine.  Your only solution is to remove the dot or rename the ".Help part to something else such as ".Docs".  Also note that the help viewer has problems with hash signs (#) in the path when viewing help files too.

_Originally posted by @EWSoftware in https://github.com/EWSoftware/SHFB/issues/41#issuecomment-83656538_

**Comment by wim07101993** [comment]
Personally I think this is an issue. In my case solution directory is named {Company}.{Product}.{ProductPart}.{...}. Same as how namespaces is built. As you probably now this is a very common way to name directories in C#. When one part of the namespace contains a ".H..." like ".Handshakes", the documentation output path needs to be outside the solution directory.

**Comment by EWSoftware** [comment]
As noted, this isn't something I can fix.  It's an issue with the help 1 compiler.  I'm not sure what else there is to be done about it.
