### ISSUE TITLE
Do not keep state in contentlayout file

### ISSUE THREAD

**Issue by mikasoukhov** [EWSoftware/SHFB#767]
selected expanded attributes should be stored in some local file. Be friendly for git repository.

**Comment by EWSoftware** [comment]
It only stores it if you change and save the file.  Changing the selected node or expansion state does not mark the file as dirty so it's only saved if other changes are made to the topic entries.  I don't think such attributes warrant a separate state file.

**Comment by mikasoukhov** [comment]
Unfortunately, it makes git history dirty.

**Comment by EWSoftware** [comment]
I don't see how if you're making changes to the file anyway.

**Comment by mikasoukhov** [comment]
Unfortunately, I don't. Your app makes them self what it brings dirty into git history.

**Comment by EWSoftware** [comment]
Well, we'll have to agree to disagree.  It's not something I'm going to change.

**Comment by mikasoukhov** [comment]
Too sad. It makes git history dirty.
