### ISSUE TITLE
Add an Example for SyntaxGeneratorExportAttribute.IsConfigurable Property

### ISSUE THREAD

**Issue by gowthamguptha** [EWSoftware/SHFB#768]
Please add an example for SyntaxGeneratorExportAttribute.IsConfigurable Property.

I want to show some custom configuration message box for my plugin.  

Help Topic: https://ewsoftware.github.io/SHFB/html/0ae85662-4766-f604-0542-2c567dc775ab.htm

**Comment by EWSoftware** [comment]
A syntax generator or a plug-in in general?  If it's a syntax generator, the `DefaultConfiguration` and `CurrentConfiguration` properties supply the default and current configuration.  The `SynaxComponent` handles editing of the syntax component configurations so there's nothing to do within your component specifically.

For a general plug-in, see any of the existing plug-ins that provide a configuration such as the [DbcsFixPlugIn](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/DbcsFixPlugIn.cs).   The `ConfigurePlugIn` method handles showing the form and updating the configuration.

**Comment by gowthamguptha** [comment]
Thanks, EWSoftware :)

This really helps me. But I have one more question on Syntax Generator.
For Plug-in as you mentioned we can show a form and update the configuration. This is fine.
But I need to use the same configuration which is saved in the above plug-in in the Syntax generator.

How can I access those configurations?

**Comment by EWSoftware** [comment]
I'd have your plug-in locate your syntax generator in the *sandcastle.config* file during the after execution stage of the `MergeCustomConfigs` build step and then insert the configuration elements into the syntax component's configuration element.  The syntax generator would then access it normally when loaded by BuildAssembler.

**Comment by gowthamguptha** [comment]
Hi EWSoftware,

As you suggested i was adding the configiration in MergeCustomConfig and this is how it looks in Syntax componet.

`
            <component id="Syntax Component">
              
              <syntax input="/document/reference" output="/document/syntax" />
              
              <generators>
                <generator id="Json" />
              </generators>
              
              <containerElement name="codeSnippetGroup" addNoExampleTabs="true" includeOnSingleSnippets="false" groupingEnabled="true" />
			  **            <configuration>
					<AppConfigLocale value="Namespace" />
			</configuration>**`


And in  My Custom Syntax Generator -> Initialize method I was trying to access the above-added configuration But it was not accessing.

Could you please suggest if I am wrong?

**Comment by EWSoftware** [comment]
Your syntax component will be passed its `generator` element for the configuration.  You need to add the configuration elements as children of that element:

```
<generators>
    <generator id="Json">
        <YourConfiguration Goes="Here"..... />
        <Etc />
    </generator>
</generators>
```

Also, remember that there are two copies of the syntax component, one for conceptual content and one for API content, so you'll want to insert them in both copies.

**Comment by gowthamguptha** [comment]
Thanks, EWSoftware.

It worked :)

Thank you so much again for your quick response.

Have a nice day :)
