### ISSUE TITLE
Many non English chars interprets like a shortcuts.

### ISSUE THREAD

**Issue by mikasoukhov** [EWSoftware/SHFB#770]
Maybe you wanna fix it. It will be great cause the bugs go many years.

**Comment by EWSoftware** [comment]
Examples?

**Comment by mikasoukhov** [comment]
Х

In editor. The char is the upper case is can be created by Shirt+{ what is mean [. I think you have some accelerators issue.

**Comment by EWSoftware** [comment]
In Visual Studio or the standalone GUI?  If in Visual Studio, key mappings are based on the default collection you chose when Visual Studio was first started plus any modifications you've made.  The SHFB package doesn't define any shortcuts on its commands to avoid issues with other key mappings.

In the standalone GUI, there are shortcuts but all involve Ctrl plus some other key combo.  They're shown in the menus.  Ctrl+Shift+X will clear the output window.  Shift+X by itself inserts an uppercase X in the editor.  The '[' key and Shift+[ insert the corresponding character.  If you've got the option enabled, they will insert the closing brace too.  That can be turned off in the options.  I'm not seeing and nobody has ever reported the issue that you describe.

**Comment by mikasoukhov** [comment]
Ok, up to you.
