### ISSUE TITLE
Can not build API documentation for .NET core project cause project assembly does not exist

### ISSUE THREAD

**Issue by BlackyTheDruide** [EWSoftware/SHFB#771]
Maybe I use the sandcastle builder in the wrong way but I can not build .NET core projects. I always get the following error: 

`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" "NetCoreTest.shfbproj" /p:platform="x64" /p:configuration="Debug"`

`SHFB : error BE0065: BUILD FAILED: Project assembly does not exist: C:\Users\xxx\source\repos\SandcastleError\SandcastleTest\Source\NetCoreTest\..\..\..\bin\AnyCPU\Debug\netcoreapp2.2\NetCoreTest.dll [C:\Users\xxx\source\repos\SandcastleError\SandcastleTest\shfb\NetCoreTest.shfbproj]`

There is now build mode configured with AnyCPU in the .csproj or in the shfbproj. Is there some invalid configuration in my example or why sandcastle is always looking into AnyCPU output?

@EWSoftware You can find an example project in your mail inbox

**Comment by EWSoftware** [comment]
For some reason, the `Platform` property isn't in the conditioned properties the build engine checks when setting the configuration and platform.  Usually when that happens, `PlatformName` is being used instead so it sets that.  I've fixed it for the next release by setting both if it doesn't see `Platform`.
