### ISSUE TITLE
Every member with Span or ReadOnlySpan argument is treated as non-documented

### ISSUE THREAD

**Issue by koszeggy** [EWSoftware/SHFB#772]
When I build a .NET Core 3.0 project containing members with `Span<T>` or `ReadOnlySpan<T>` parameters SHFB treats them as if they werent't documented at all. For example:

```
BuildAssembler : warning : ShowMissingComponent: [M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan`1)] Missing <summary> documentation [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan`1)] Missing <typeparam name="T"/> documentation [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan`1)] Missing <returns> documentation [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan`1)] Missing <param name="item"/> documentation [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
BuildAssembler : warning : ShowMissingComponent: [M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan`1)] Missing <param name="set"/> documentation [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
```

However, the compiled .xml help contains the member:

```xml
<member name="M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan{``0})">
    <summary>
        Gets whether <paramref name="item"/> is among the elements of <paramref name="set"/>.
        <br/>See the <strong>Examples</strong> section of the <see cref="M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,``0[])"/> overload for an example.
    </summary>
    <param name="item">The item to search for in <paramref name="set"/>.</param>
    <param name="set">The set of items in which to search the specified <paramref name="item"/>.</param>
    <typeparam name="T">The type of <paramref name="item"/> and the <paramref name="set"/> elements.</typeparam>
    <returns><see langword="true"/>&#160;if <paramref name="item"/> is among the elements of <paramref name="set"/>; otherwise, <see langword="false"/>.</returns>
    <remarks>
        <para>This overload uses generic <see cref="T:System.Collections.Generic.IEqualityComparer`1"/> implementations to compare the items for the best performance.
        <note>If elements of <paramref name="set"/> are complex expressions consider to use the <see cref="M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.Func{``0}[])"/> overload instead to prevent evaluating all elements until they are actually compared.</note></para>
    </remarks>
</member>
```

What I noticed is that the warning refers the member as
```
M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan`1)
```
whereas the same member in the .xml is
```
M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan{``0})
```

**Comment by EWSoftware** [comment]
The compiler doesn't always output an XML comments signature that matches the metadata in the assembly.  You can use the [Member ID Fix-Ups Plug-In](http://ewsoftware.github.io/SHFB/html/17d977a6-e3dc-4ef4-9bbf-718ef4823854.htm) to correct them so that they match.

**Comment by koszeggy** [comment]
Thank you for the hint, I did not know about that plugin.

Now the result is now somewhat better, my members get documented; however, it's still could be better:

* The generic parameter is not displayed (unlike the overload with the `Func<T>`, for example):
![image](https://user-images.githubusercontent.com/27336165/69898439-f44e2300-1359-11ea-91a2-7006712d1a46.png)
* If I open the page of the method, is is displayed as ```ObjectExtensions.In<T> Method (T, ReadOnlySpan`1)``` (with the generic parameter definition name as the second parameter)
* The `ReadOnlySpan<T>` type is not recognized (is not a link). During the compile there is a warning for it:
```
BuildAssembler : warning : ResolveReferenceLinksComponent: [M:KGySoft.CoreLibraries.ObjectExtensions.In``1(``0,System.ReadOnlySpan`1)] MSDN web service failed.  No further look ups will be performed for this build. [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
BuildAssembler : warning : Reason: Unable to connect to the remote server [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
```

Is there a way to fix these issues as well?

Btw, this is a .NET Core 3.0 project, not a C++ one.

**Comment by koszeggy** [comment]
And I still have a more severe issue:

A method with `Span<char>, ReadOnlySpan<char>` arguments turn into `Span, Void` (???).
After manually resolving the members by the aforementioned plugin I get the following output:

![image](https://user-images.githubusercontent.com/27336165/69898861-fe265500-135e-11ea-8a96-5b515dab8324.png)

As you can see there is a 'ghost' duplicate of the last method, which is actually this member:
```
M:KGySoft.CoreLibraries.RandomExtensions.NextChars(System.Random,System.Span{System.Char},System.ReadOnlySpan{System.Char})
```

The warning during the compile:
```
BuildAssembler : warning : SharedContentComponent: [Overload:KGySoft.CoreLibraries.RandomExtensions.NextChars] Missing shared content item. Tag: 'includeAttribute'; Id:'altText_pub'. [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
```

**Comment by EWSoftware** [comment]
There was an issue with the resolver service that was fixed in the latest release (v2019.11.17.0).  If you're using that release and are behind a firewall or proxy, that may cause issues as well.  Those can usually be resolved with some settings in the [BuildAssembler.exe.config file](http://ewsoftware.github.io/SHFB/html/79b4dbda-239c-4bae-9bf5-bfb53384fe6d.htm#Proxy).

The `Void` type in the method signatures typically indicates the wrong framework type has been selected in the SHFB project.  Since this is .NET Core, you should be using the Cross-Platform framework option so that it picks up all the necessary references from the project.

**Comment by koszeggy** [comment]
Thank you for the response. Yesterday I noticed that though I upgraded to v2019.11.17.0 my build scripts used a copy-deployed version of v2019.4.14.0. I apologize for the confusion.

I used v2019.4.14.0 also with the Cross-platform framework version, which produced the symptoms I posted earlier.

With version v2019.11.17.0 I got a [BE0065](http://ewsoftware.github.io/SHFB/html/cdaaca46-b815-4763-9dac-c4a57cdb2a58.htm) error:
```
SHFB: Error BE0065: BUILD FAILED: The framework version is set to Cross-platform (.NET Core/.NET Standard) but no reference assemblies were specified.  Unable to determine core types assembly.  See the error number topic in the help file for more information.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

which I could finally fix by the help of the similar [BE0035](https://ewsoftware.github.io/SHFB/html/230e5a68-858d-4272-a3a2-eea156cf379b.htm) error. Though adding the project file instead of the .dll/.xml did not work ("Incompatible Visual Studio project file format."), adding the `System.Private.CoreLib.dll` as reference solved the build issue. And the links are working again (maybe mentioning these details can be helpful for others, too).

However, I still have the Span/Void issue.

I still get the warnings during the compile:
```
BuildAssembler : warning : SharedContentComponent: [Overload:KGySoft.CoreLibraries.RandomExtensions.NextChars] Missing shared content item. Tag: 'includeAttribute'; Id:'altText_pub'. [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
BuildAssembler : warning : SharedContentComponent: [Overload:KGySoft.CoreLibraries.RandomExtensions.NextChars] Missing shared content item. Tag: 'includeAttribute'; Id:'altText_pub'. [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
```

I uploaded a fresh documentation, you can investigate the result [here](http://docs.kgysoft.net/corelibraries/?topic=html/Overload_KGySoft_CoreLibraries_RandomExtensions_NextChars.htm), for example. And the corresponding help project file is [here](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/master/KGySoft.CoreLibraries/KGySoft.CoreLibraries.WebsiteHelp.shfbproj). Feel free to download/fork the whole repo if it helps to analyze the issue.

**Comment by EWSoftware** [comment]
I've fixed the problem with the incorrect error number being reported.  Anyway, what that error means is that since you're using a .NETStandard assembly as the documentation source you need to manually include all references including all of the core framework assemblies (netstandard.dll, System.*, etc.).  Without those, it's going to use the standard .NET Framework assemblies which don't match up and thus cause the issue.

It's much easier to just specify the documentation assembly's project and let it figure all of those out.  There are currently a couple of issues.  The first is that the project must contain a `GenerateDocumentationFile` property set to `True` or it may not find the XML comments file.  And when using multi-targeting, it uses the first target framework specified in the project file.  In your case, that's `net35` which won't be appropriate.  The next release should contain support for specifying the target framework to use when multi-targeting.  For now, just put `netstandard20` as the first framework in the set.  Once you update the SHFB project to use the project as the documentation source, you should get the expected results.

**Comment by koszeggy** [comment]
I cannot build based on the .csproj file:
```
SHFB: Error BE0065: BUILD FAILED: Incompatible Visual Studio project file format. 
```

It seems as if it supported only the MSBuild format. You mentioned the issues with multi-targeting, which gave me the hint that somehow the support of the new .csproj format can be enabled. Btw. I tried
* to rearrange the order of the targets, so `netcoreapp3.0` or `netstandard2.1` was in the first position
* to use just `TargetFramework` with a single target instead of `TargetFrameworks`
* to add `xmlns="http://schemas.microsoft.com/developer/msbuild/2003"` to the `<Project>` element (which obviously would make sense only in case the MSBuild format)
* to add `GenerateDocumentationFile` explicitly, which was needed for the MSBuild format to produce the .xml files

but none of them worked. Is there a way to enable the support of the new .csproj format?

So finally I returned to the dll-xml combo, added every missing reference for .NET Core 3.0 on top of the the core `System.Private.CoreLib.dll`. Now I still have the Span-Void issue along with some new warnings, such as:

```
BuildAssembler : warning : ResolveReferenceLinksComponent: [Methods.T:KGySoft.Security.Cryptography.Crc32] Invalid reference link target 'M:System.Security.Cryptography.HashAlgorithm.TryHashFinal(System.Span`1,System.Void)'. [D:\Nyelvek\CSharp\KGySoft\KGySoft.CoreLibraries\KGySoft.CoreLibraries\HelpOut\Working\BuildTopics.proj]
```

Please note that I do not override or reference this member anywhere. Apparently it has been discovered as a base member in .NET Core 3.0 and as you can see it was also misinterpreted with this weird Span-Void signature. Despite of the fact I set the Cross-platform version and added every needed .NET Core reference assemblies.

**Comment by EWSoftware** [comment]
Are you using the standalone GUI?  If so, it doesn't currently support the newer project file format.  The next release will.  If you can, install and use the Visual Studio package as it will be able to load them.

**Comment by koszeggy** [comment]
Wow, thank you for the info, now I switched to VS build and it finally works!

It wasn't easy though. Here are some further fails I encountered:

* My `<DocumentationFile>` element in the .csproj file looked like this: `bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml`, which caused a compile error because `TargetFramework` was resolved to empty string. I had to replace `DocumentationFile` to `bin\$(Configuration)\netcoreapp3.0\$(AssemblyName).xml`
* Firstly I put `netcoreapp3.0` to the first place in the frameworks list because that has the widest functionality in my libraries.
* Without adding the reference assemblies I got a bunch of `Ignoring unresolved assembly reference` warnings so I added them again.
* But all this produced the same Span-Void anomalies in the end as before.

Finally, I switched to **.NET Standard 2.1**, which basically covers the functionality of the .NET Core 3.0 build. Without adding any references the build failed with
```
MRefBuilder : error : Unresolved assembly reference: netstandard (netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51) required by KGySoft.CoreLibraries
```
so I added `%ProgramFiles%\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\netstandard.dll` as a reference assembly. Interestingly, I had to turn off the Member ID Fix-Ups plugin as the signatures were the correct ones again and now everything works if I build from VS2019.

I hope these details may help others, too. Maybe it is worth mentioning these possible pitfalls somewhere in the docs/FAQ.

Thank you so much for your assist.

**Comment by EWSoftware** [comment]
Adding a `GenerateDocumentationFile` property set to True will fix the issue with it not resolving the `TargetFramework`.  I've also got a fix for that in the next release so the other property workaround isn't needed.

There's a known issue with netstandard21.  It's unable to find the package references it needs in the project when it's loaded.  That may be true of netcoreapp30 as well.  Putting netstandard20 first works around that as does adding the reference to the assembly explicitly as you found.
