### ISSUE TITLE
Nullable reference types

### ISSUE THREAD

**Issue by thomaslevesque** [EWSoftware/SHFB#773]
Currently SHFB doesn't seem to take C# 8 nullable reference types into account. For instance, I have this method:

```csharp
public static IEnumerable<TSource> DistinctBy<TSource, TKey>(
	this IEnumerable<TSource> source,
	Func<TSource, TKey> keySelector,
	IEqualityComparer<TKey>? keyComparer = null
)
```

But the rendered documentation doesn't include the `?` in `IEqualityComparer<TKey>?`.

It would be nice to support nullable type references so that signatures can be correctly represented. (to be fair, even the MS documentation doesn't include nullability annotations... But it should!)

**Comment by EWSoftware** [comment]
I did some experimenting.  Nullability is indicated through a combination of `NullableAttribute` and `NullableContextAttribute` instances on the type, method, method parameters, and return value.  In the absence of the `NullableAttribute` on the method parameter or return value, it defers to the `NullableContextAttribute` on the method or, if that doesn't exist, the type itself.  That all seems pretty straightforward but things get much more complex when dealing with arrays, generic types, and especially nested generic types/arrays.  In that case it generates the `NullableAttribute` on the overall type expression with a byte array indicating the nullability of the various nested parts.

I will probably end up modifying MRefBuilder to determine if a part of the type expression is nullable and output an extra attribute along with the type information for each nullable part in some way.  It will probably take a while to figure that out given the variability of how that info is defined.

**Comment by thomaslevesque** [comment]
[This article](https://codeblog.jonskeet.uk/2019/02/10/nullableattribute-and-c-8/) by @jskeet might help. It's a bit old (from before C# 8 was completely stabilized), but I think it's still relevant.

**Comment by EWSoftware** [comment]
Support for this has been implemented and will be in the next release due out soon.  It appears to handle everything as expected but there are bound to be some odd cases that it might not handle correctly.  Those will have to be dealt with as they are found.
