### ISSUE TITLE
ProductVersion and Copyright should change dynamically based on Build update

### ISSUE THREAD

**Issue by gowthamguptha** [EWSoftware/SHFB#774]
Currently, I see the Copyright and Product version is a constant variable.

But I want to change this dynamically.  My build will change the Assembly Version (Assembly.cs) based on the release it is going dynamically.

Now how can I update this accordingly to my Plugin?

**Comment by EWSoftware** [comment]
If your version information is in project properties, they can be added to the SHFB project as custom properties and referenced in the copyright and product version SHFB properties using the substitution syntax ({@MajorVersion}.{@MinorVersion} for example).  I know others have done it that way though I don't recall the specifics.

**Comment by dwhearn** [comment]
I have defined the copyright and footer as follows in the SHFB project:
    <CopyrightText>&amp;#169%3b 2004-{%40BuildDate:yyyy} Company Name. All Rights Reserved.</CopyrightText>
    <FeedbackEMailAddress>documentation%40osisoft.com</FeedbackEMailAddress>
    <FooterText>Version: {%40FullBuildNumber}&amp;lt%3bbr/&amp;gt%3bBuild Date: {%40BuildDate:MMMM d, yyyy}</FooterText>

And FullBuildNumber is a property defined as follows:
    <FullBuildNumber>$(MajorVersionNumber).$(MinorVersionNumber).$(BuildVersionNumber)</FullBuildNumber>

**Comment by gowthamguptha** [comment]
Hi,

The above comments are related to copyright in SHFB.
But my question was I created a custom plugin, where I need to mention the version and Copyright attributes right.

These values I need to do it dynamically.

[HelpFileBuilderPlugInExport("PlugIn", Version = **AssemblyInfo.ProductVersion**,
        **Copyright = AssemblyInfo.Copyright**, Description = "plug-in", IsConfigurable = true)]


Currently, these values are getting from the assembly info class. But these values I should populate dynamically based on AssemblyVersion which my build will update.

**Comment by EWSoftware** [comment]
You mention that your build is modifying the AssemblyInfo.cs file, you should be able to get the attribute values that it is updating from the executing assembly.  As an example, see the [About form in the standalone GUI](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderGUI/AboutDlg.cs#L62).
