### ISSUE TITLE
SeeAlso: Can we customize the see also section

### ISSUE THREAD

**Issue by gowthamguptha** [EWSoftware/SHFB#775]
Currently, When I build the Sandcastle project I see below things in the see also section
**See Also**
**-> Class Name
->Namespace name
-> Reference methods**

But _my requirement_ is to show only _reference methods_ in the _see also section_.

1. how can I achieve this in my custom presentation project?
2. If we don't have anything to be shown then See Also section should not be shown?

**Comment by EWSoftware** [comment]
See the `t_putSeeAlsoSection` template in *main_sandcastle.xsl*.  You probably just need to comment out the call to the `t_autogenSeeAlsoLinks` template which generates the other links.
