### ISSUE TITLE
ResolveReferenceLinksComponent2: MSDN URL not found for target 'T:System.Runtime.InteropServi ces.GuidAttribute'

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#776]
First of all, I apologize for the fact that we're using a very old version of SandCastle (Sandcastle Help File Builder Console, version 1.6.0.0).  We're planning to move to the latest version soon.  But in the meantime, any suggestions as to why we've started getting an error like this?

`warning : ResolveReferenceLinksComponent2: MSDN URL not found for target 'T:System.Runtime.InteropServices.GuidAttribute'.`

Thanks,
Glenn

**Comment by EWSoftware** [comment]
It's hard to say.  That version uses the old MTPS content web service which has become somewhat unreliable as has the MSDN2 site to which the links it generated went.  The latest release uses the newer Microsoft Docs cross reference service which generates direct links to the current Docs.Microsoft.com website.  If you get the same result with that, I can investigate it but it should work.

**Comment by glenncarr** [comment]
Thanks.  I just need to upgrade.

Thanks for the prompt response.

**Comment by glenncarr** [comment]
Hey @EWSoftware, do I need to do something to enable the external MSDN links to be created with the latest version?

![image](https://user-images.githubusercontent.com/367292/70559365-1f9bf380-1b4c-11ea-9840-2afe2c32c1fe.png)

Thanks again.

**Comment by EWSoftware** [comment]
Add the Syntax Component to the project and in its configuration, enable the "Render reference links to online content" option.

**Comment by glenncarr** [comment]
Thanks again.
