### ISSUE TITLE
How to disable the Namespace Section completely?

### ISSUE THREAD

**Issue by gowthamguptha** [EWSoftware/SHFB#778]
Hi Team,

I am looking for disabling the "Namespaces" completely in my helper document.

Can you suggest how can I disable the namespaces section in the custom presentation? 
or
Is there a way where I can show only specific (or few ) Namespaces in the Namespaces section?

**Comment by EWSoftware** [comment]
You can use the API filter to exclude types from the help file.  If you exclude all of the types, the namespace will go away too.

**Comment by gowthamguptha** [comment]
Ya this is fine.
But my requirement is I need those methods to be included but I don't want to show those namespaces in the helper file.

**Comment by EWSoftware** [comment]
In that case, you'll likely need to create a custom presentation style and create a custom TOC transformation that lists the types at the root level rather than the namespaces.
