### ISSUE TITLE
Question about <see> tags in generated help files

### ISSUE THREAD

**Issue by SpaceBeeGaming** [EWSoftware/SHFB#780]
I have noticed that the <see> tags in summaries in the generated help files lack the class names in front of them. eg `<see cref="DateTime.UtcNow"/>` inside `<summary>` tags results in a link with the text `UtcNow`. 

Screenshot from the documentation:

![image](https://user-images.githubusercontent.com/12137642/71450724-f6947900-276f-11ea-85e7-dfd97865b8fb.png)

Not very descriptive. Id like it to be `DateTime.UtcNow`

Is there a setting that controls this or do I have to add an inner text manually to every `<see>` element (and remember to update it if I rename something).

If there isn't is there a possibility of adding it. Something like: "show class name" as an attribute to see.

I'm using the Visual Studio extension.

**Comment by EWSoftware** [comment]
It is the standard convention to omit the namespaces from types and the type name from members in link text.  The [qualifyHint attribute](http://ewsoftware.github.io/XMLCommentsGuide/html/983fed56-321c-4daf-af16-e3169b28ffcd.htm) can be used to make it show them in the link text when set to true.

**Comment by SpaceBeeGaming** [comment]
It doesn't seem to have any effect, neither do these:

`<see cref="DateTime.UtcNow">DateTime.UtcNow</see>`
`<see cref="DateTime.UtcNow" qualifyHint="true">DateTime.UtcNow</see>`

They still output `UtcNow`

**Comment by EWSoftware** [comment]
Specifying inner text will always show the inner text regardless of the attribute setting.  For example:

```
/// <para>No attribute, no inner text: <see cref="DateTime.UtcNow" /></para>
/// <para>Attribute, no inner text: <see cref = "DateTime.UtcNow" qualifyHint="true" /></para>
/// <para>No attribute with inner text: <see cref="DateTime.UtcNow">DateTime.UtcNow</see></para>
/// <para>Attribute with inner text: <see cref = "DateTime.UtcNow" qualifyHint="true">DateTime.UtcNow</see></para>
```

Results in:

```
No attribute, no inner text: UtcNow
Attribute, no inner text: DateTime.UtcNow
No attribute with inner text: DateTime.UtcNow
Attribute with inner text: DateTime.UtcNow
```

This also assumes you are using the latest version and not a really old version prior to support for the attribute (prior to about version 2015.10.10.0).
