### ISSUE TITLE
How to add text dynamically for "Copyright notice text" in Sandcastle?

### ISSUE THREAD

**Issue by gowthamguptha** [EWSoftware/SHFB#781]
Hi Team,

I want to add the text dynamically for the "Copyright notice text" field in the sandcastle.

ex: If the current text contains (c) copy right., 2019. Here year has to be dynamic if year changes to 2020 then it should change automatically.

can you suggest how we can achieve this?

**Comment by EWSoftware** [comment]
You can use the `BuildDate` substitution tag with a format specifier: `Copyright (c) {@BuildDate:yyyy}`
