### ISSUE TITLE
MSDN URL not found for target

### ISSUE THREAD

**Issue by ManjunathD46** [EWSoftware/SHFB#784]
We are using sandCastle in our product builds but, we see below warnings in build logs. 

Type: WARNING (Pattern: [Ww][Aa][Rr][Nn]:)
[exec] Warn: ResolveReferenceLinksComponent2: MSDN URL not found for target 'T:System.XXXXXX'.

So, we tried installing the new sandcastle(v2019.11.17.0) from the link(https://github.com/EWSoftware/SHFB/releases) but, now we are seeing the below error on our product builds.

13:18:21 Running sandcastle
[exec] MRefBuilder (v2019.11.17.0)
Error: Unknown target framework version ' 2.0'.
[exec] Result: 1
[exec] XslTransform (v2019.11.17.0)
[exec] Copyright ¸ 2006-2019, Microsoft Corporation, All Rights Reserved.
[exec] Portions Copyright ¸ 2006-2019, Eric Woodruff, All Rights Reserved.
[exec] Info: Applying XSL transformation 'ApplyVSDocModel.xsl'.
[exec] Error: The input file 'reflection1.xml' could not be loaded.  The error is: Could not find file 'reflection1.xml'.
[exec] Result: 1
Info: Applying XSL transformation 'RemoveExplicits.xsl'.
[exec] Error: The input file 'reflection2.xml' could not be loaded.  The error is: Could not find file 'reflection2.xml'.
[exec] Info: Applying XSL transformation 'RemoveInstance.xsl'.
[exec] Error: The input file 'reflection3.xml' could not be loaded.  The error is: Could not find file 'reflection3.xml'.
[exec] Info: Applying XSL transformation 'ReflectionToManifest.xsl'.
[exec] Error: The input file 'reflection.xml' could not be loaded.  The error is: Could not find file 'reflection.xml'.
[exec] Error: 
[exec] BuildAssemblerCore: Each component element must have an id attribute that specifies the component's unique ID.

Could some one please check and let us know the reason for failure.
Kindly let us know in case of any more details.

**Comment by EWSoftware** [comment]
That doesn't look like standard build output from SHFB.  There are no transforms called RemoveExplicits.xsl and RemoveInstance.xsl in SHFB and the reflection files don't have numeric extensions.  Are you using a plug-in or custom tool of some sort or are you using the underlying tools directly?  Are you using a custom presentation style?

**Comment by kishkulk** [comment]
@EWSoftware  bellow is an error we are getting, 

[antz:worker]      [exec] Info: ResolveReferenceLinksComponent2: Creating MSDN URL resolver.
[antz:worker]      [exec] Info: ResolveReferenceLinksComponent2: Searching directory 'C:\Sandcastle\Data\Reflection' for targets files of the form '*.xml'.
[antz:worker]      [exec] Info: ResolveReferenceLinksComponent2: Searching directory 'E:\data\dotnetdoc' for targets files of the form 'reflection.xml'.
[antz:worker]      [exec] Info: ResolveReferenceLinksComponent2: Loaded 170417 reference targets.
[antz:worker]      [exec] Info: SaveComponent: Instantiating component.
[antz:worker]      [exec] Info: BuildAssembler: Building topic N:****.****
[antz:worker]      [exec] Info: BuildAssembler: Building topic T:****.****.*****
[antz:worker]      [exec] Warn: ResolveReferenceLinksComponent2: MSDN URL not found for target 'T:System.IDisposable'.

in sandcastle.config we have bellow configuration

        
        <component type="Microsoft.Ddue.Tools.ResolveReferenceLinksComponent2" assembly="C:\Sandcastle\ProductionTools\BuildComponents.dll" locale="en-us" linkTarget="_blank">
          <targets base="C:\Sandcastle\Data\Reflection" recurse="true" files="*.xml" type="msdn" />
          <targets files="reflection.xml" type="local" />
        </component>

We upgraded the Sandcastle version to v2.4.10520.1 but still getting the same error. What should be our approach to solve this error ?

**Comment by EWSoftware** [comment]
@kishkulk  The Sandcastle tools are all integrated with SHFB and have been for many years.  There is no need to install anything older that was previous distributed by Microsoft.  Those older versions will not be used and I cannot provide any support for them.

I suggest you remove the old tools, install the [latest release of SHFB](https://github.com/EWSoftware/SHFB/releases), and recreate your project using it in Visual Studio or the provided standalone GUI.
