### ISSUE TITLE
MSBuild property to disable SHFB

### ISSUE THREAD

**Issue by savornicesei** [EWSoftware/SHFB#785]
Hi all,
Since SHFB does not support Linux, it would be great to be able to disable SHFB at build time.
```
msbuild My.sln /t:Build /p:SHFBDISABLE=true
```

Thank you.

**Comment by EWSoftware** [comment]
No need for a property.  You can configure the solution to exclude the SHFB project from the build.

**Comment by savornicesei** [comment]
True. But that it's quite inconvenient when building in AppVeyor / TravisCI on both win and linux.

Thank you.

**Comment by ritchiecarroll** [comment]
My suggestion would be to create another build configuration, e.g., `Posix` that excludes the SHFB project, then you can just target that configuration:
```
    msbuild /p:Configuration=Posix  My.sln
```

**Comment by savornicesei** [comment]
Inconvenient but yes, that will work.

Thank you.
