### ISSUE TITLE
Collapsible regions for code not working

### ISSUE THREAD

**Issue by AndreyAlenikov** [EWSoftware/SHFB#789]
When including multiple `example` tags with `code` tag referencing an external file not all regions collapse. It depends on the ordering of `example` tags: 
If in one `example` tag (say ex1) all regions are collapsing fine, in a second `example` tag (say ex2) just some of them are collapsing. But if you switch `example` tags' positions, now ex2 is working fine and ex1 has not collapsible regions.

**Comment by EWSoftware** [comment]
Can you provide a code example to illustrate the issue?  Also, it's not clear whether you are referring to the code in Visual Studio or in the compiled help file.

**Comment by AndreyAlenikov** [comment]
/// <summary>
    /// Provides data from AS400 as DataTables<br />
    /// Contains SQL code and ODBC connection to AS400
    /// </summary>
    /// <example><code source="..\..\Analytics\Analytics comments\AS400_Data.cs" region="Declarations" title="Declarations" /></example>
    /// <example><code source="..\..\Analytics\Analytics comments\AS400_Data.cs" region="Properties" title="Properties" /></example>
    /// <example><code source="..\..\Analytics\Analytics comments\AS400 database.cs" region="Transport tables" title="Transport tables" /></example>
    /// <example><code source="..\..\Analytics\Analytics comments\AS400 database.cs" region="Inventory tables" title="Inventory tables" /></example>    
    /// <example><code source="..\..\Analytics\Analytics comments\AS400 database.cs" region="SO tables" title="SO tables" /></example>
    /// <example><code source="..\..\Analytics\Analytics comments\AS400 database.cs" region="TAG tables" title="TAG tables" /></example>
    /// <example><code source="..\..\Analytics\Analytics comments\AS400 database.cs" region="Requisitions tables" title="Requisitions tables" /></example>
    class AS400_Data

It's referencing from Visual Studio itself to external files containing code samples and notes separated by regions. All this info is displayed perfectly. The issue is - some collapsible regions in several <example> tags may not work. But when you switch those <example> tags (move them up or down) and recompile the project - regions become collapsible in one <example> tag but some previously working regions in the other <example> tags become 'frozen' and always stay open.

**Comment by EWSoftware** [comment]
Can you attach the actual source code file with the defined regions that are being imported?  You can strip out the code in the method bodies if you like.  I just need something I can build to see what you're seeing without having to guess at how the regions look in your code.

**Comment by AndreyAlenikov** [comment]
[AS400 database.txt](https://github.com/EWSoftware/SHFB/files/4351801/AS400.database.txt)

Here it is. 
Thank you.

**Comment by EWSoftware** [comment]
The collapsible regions use the starting line number of the region as an identifier.  However, with multiple code sections, the IDs can be duplicated.  In this case, that occurs for the first collapsible region of each section and occasionally another region when the line numbers match.  I've fixed it for the next release by making the region IDs unique across all topics.

**Comment by EWSoftware** [comment]
Fixed in 54f57b63526df352721cd22eeb8e3fedf0dcac63
