### ISSUE TITLE
Use File Version of DLL instead of Product-Version

### ISSUE THREAD

**Issue by derchirurg** [EWSoftware/SHFB#791]
Is it possible to configure SHFB to use the File Version of a DLL instead of the Product-Version for showing in the documentation?

The nuget DLLs have for example the file version 2.0.3, the product version is 2.0.3+4.BranchFOO as of git flow.

**Comment by EWSoftware** [comment]
To change which attribute it uses for the version information you'd have to replace the ApplyVSDocModel.xsl transformation which is where that information is generated.  That would require cloning a presentation style and using a customized version of the transformation.

A workaround would be to open the SHFB project properties, go to the Transform Args category, and set the `maxVersionParts` argument to 2 or 3.  That will trim off all information after the specified part.  So, for the above example, it would show "2.0" or "2.0.3+4" as it only splits the version number on the period.
