### ISSUE TITLE
Unable to build documentation with latest VS 2019 Build Tools (16.5.3)

### ISSUE THREAD

**Issue by tomasmaruska** [EWSoftware/SHFB#792]
Hi, 

I've encountered issue that could be reproduced as follows:
Server virtual machine running on Windows 10 with:
- VS Build Tools v16.5.3
- Sandcastle v2020.3.6.0

When I'm trying to create HTML documentation, even from simple dll, I got following error message:

```
C:\Users\Tomas\Desktop\project\Help\Working\GenerateRefInfo.proj(49,5): error MSB4002: There was a failure retrieving the attributes for parameters in the "Microsoft.Ddue.Tools.MSBuild.MRefBuilder" task. Could not load type 'Microsoft.Build.Framework.IBuildEngine5' from assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
C:\Users\Tomas\Desktop\project\Help\Working\GenerateRefInfo.proj(49,5): error MSB4060: The "Microsoft.Ddue.Tools.MSBuild.MRefBuilder" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.

```

I've tried VS2017 Build Tools and manuals build was successful, but that's not an option for me as we use latest VS Build Tools on Continuous Integration servers.

Any idea how to make it work? 
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/4450193/LastBuild.log)

**Comment by EWSoftware** [comment]
This is related to issue #790.  If you are building from the command line or the standalone GUI, you'll probably have to go back to the prior release for the time being.

**Comment by tomasmaruska** [comment]
You said 'command line or the standalone GUI'.

Is there a way of build that (might) work with latest VS tools?

**Comment by EWSoftware** [comment]
If you're not building the project from within Visual Studio, use the prior release for the time being.
