### ISSUE TITLE
Context ID (Keyword)

### ISSUE THREAD

**Issue by gnimor** [EWSoftware/SHFB#793]
Not sure if I missed something here. I created a CHM file with conceptual topics only. In my .NET application I try to open the help file with a dedicated keyword/context id. Something like this:

form.Help.ShowHelp(null, fileName, keyword);
or...
form.Help.ShowHelp(null, fileName, form.HelpNavigator.Topic, "MyTopic");
or...
form.Help.ShowHelp(null, fileName, form.HelpNavigator.TopicId, 23332);

So the file opens, but the topic doesn't show up. Any hint how I can assign a dedicated context id / topic in the MAML so that I can open this topic directly later on?

**Comment by EWSoftware** [comment]
The ID to use is the one for the topic, typically the GUID generated when the topic is created unless you changed it to something else.  You also need to include the subfolder and filename extension.  You can also include an ID to a link within the page at the end to jump to it as well ("#inPageID")

```
Help.ShowHelp(form, path, HelpNavigator.Topic, "html/" + topicID + ".htm" + inPageLinkID);
```
