### ISSUE TITLE
Question: How to copy Icons to ..\Help\icons folder

### ISSUE THREAD

**Issue by michaldengusiak** [EWSoftware/SHFB#796]
I am trying to add Logo into documentation,
I noticed that every time I rebuild 

`..\Help\icons`

so I added my icons to 

`..\icons`

![image](https://user-images.githubusercontent.com/26113670/80963361-b1abdd80-8e06-11ea-82f5-924da0d5621a.png)

however, I can not see Incons in my documentation help file and also  `..\Help\icons`
Do I need to set up post-build event to copy files or there is better way?

**Comment by EWSoftware** [comment]
Logos are implemented by the presentation styles.  Include the image in the project and make sure its Build Action is set to Content.  In the Transform Args project property category, specify the name of the image in the `logoFile` property.  Fill in the other logo related properties as needed.  The logo property descriptions contain more information on how they are used.
