### ISSUE TITLE
where i will get new presentation style

### ISSUE THREAD

**Issue by BornDeveloper** [EWSoftware/SHFB#798]
Hi,

Where i will get new presentation style for sandcastle project?

How i can add Welcome page and License Agreement page?

**Comment by EWSoftware** [comment]
The only presentation styles available are those that come with SHFB.  If other people have published them, I'm not aware of any.  You can add help topics to the content layout file.  The new project template contains one along with a default welcome topic.  See the [Getting Started](http://ewsoftware.github.io/SHFB/html/b772e00e-1705-4062-adb6-774826ce6700.htm) topics for an overview of working with SHFB.  See the [Conceptual Content topics](http://ewsoftware.github.io/SHFB/html/3d4edd2d-7883-4508-b9d2-bd7b4d848b0d.htm) for information specific to adding things like Welcome and license agreement topics.

**Comment by BornDeveloper** [comment]
Hi Eric,
Thanks for a quick response.
Hope you are doing well...
The first time I am using this tool, feeling very happy.
I hope, the client will appreciate this documentation as I am doing this as a non-funtional requirement and I will get a chance to appreciate you also.
Regards,
Amol Sagvekar.



 

    On Thursday, 21 May, 2020, 10:20:18 pm IST, Eric Woodruff <notifications@github.com> wrote:  
 
 


The only presentation styles available are those that come with SHFB. If other people have published them, I'm not aware of any. You can add help topics to the content layout file. The new project template contains one along with a default welcome topic. See the Getting Started topics for an overview of working with SHFB. See the Conceptual Content topics for information specific to adding things like Welcome and license agreement topics.
