### ISSUE TITLE
Add Arduino support

### ISSUE THREAD

**Issue by nolme** [EWSoftware/SHFB#799]
I'm using Arduino which code is very similar to C++ code.
I'm documenting my code like I do on Visual Studio.
Is it possible to generate documentation using Sandcastle with .INO files (and librairies .C/.CPP/.H) ?
Thanks,
Vincent

**Comment by EWSoftware** [comment]
The Sandcastle tools only work with managed code assemblies.  If they are not managed code assemblies, it will not work with them.  That's why it doesn't support native C++ assemblies.

**Comment by nolme** [comment]
ok thanks for the information.
