### ISSUE TITLE
"Install SHFB" button doesn't do anything

### ISSUE THREAD

**Issue by MGODOY-BR** [EWSoftware/SHFB#802]
I'm trying install the latest version, but the "Install SHFB" button doesn't work.

I've have already an older version of SandCastle. Should I remove it?

**Comment by EWSoftware** [comment]
Try running the installer manually from the .\InstallResources folder.

**Comment by MGODOY-BR** [comment]
I've got it. The problem was that I've ran it from Download Windows folder. I changed and it worked. Thanks.
