### ISSUE TITLE
Markdown Output corrupt when using <code> Tag  in Class Description

### ISSUE THREAD

**Issue by BlackyTheDruide** [EWSoftware/SHFB#803]
Hi,

it seems that the created table in markdown gets corrupt when tag <code> is used in a class description.

![Summary](https://user-images.githubusercontent.com/42168238/86348929-adfad280-bc60-11ea-932e-e2034ff20535.PNG)

![ErrorDescriptionOfClass](https://user-images.githubusercontent.com/42168238/86348719-578d9400-bc60-11ea-8f11-23e6acc6fff1.PNG)

Complete code example available, if needed.

**Comment by EWSoftware** [comment]
The summary element is intended to be brief description with no other block-level elements.  Put the code example in the remarks or example element instead.

**Comment by BlackyTheDruide** [comment]
Ok, thank you than we have to fix it in the code summaries.
