### ISSUE TITLE
Markdown link in syntax description not working

### ISSUE THREAD

**Issue by BlackyTheDruide** [EWSoftware/SHFB#804]
Hi,

it seems that links in syntax description not working / can not be displayed correctly.

![ErrorSyntaxDescription](https://user-images.githubusercontent.com/42168238/86349504-822c1c80-bc61-11ea-887b-ce655d42b1a1.PNG)

Complete code example available, if needed.

**Comment by EWSoftware** [comment]
I'll need to see an example of what you are doing.

**Comment by BlackyTheDruide** [comment]
> I'll need to see an example of what you are doing.

I have send you an email with the example.

**Comment by EWSoftware** [comment]
Links and other HTML elements don't appear to be supported in markdown code blocks.  You can either remove the syntax component from the project's configuration or, if you're using it for other options, just disable the "Render references links" option in it.  I'll add Markdown in the note about unsupported formats.

**Comment by BlackyTheDruide** [comment]
> Links and other HTML elements don't appear to be supported in markdown code blocks. You can either remove the syntax component from the project's configuration or, if you're using it for other options, just disable the "Render references links" option in it. I'll add Markdown in the note about unsupported formats.

Thank you for the fast answer. I will set the render references links option to false and it worked for my.
