### ISSUE TITLE
Source button in generated CHM file does not execute the Bookmark for the line number

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#806]
I have included a baseSourceCodeUrl in our project properties that points to the GitHub page of our project.
When I click on the [Source] button in a generated CHM file then the right page is opened but the bookmark of the line number is not passed to the browser.
When I do the same for the webhelp then it works as expected.
I inspected the properties of the [Source] button in the CHM file and the URL behind that button is correct.
When I copy and paste that URL in my browser it opens the file on the correct line number.
Is this a known limitation of CHM files ?

Robert

**Comment by EWSoftware** [comment]
Yes, it appears to be a limitation of the CHM file.

**Comment by RobertvanderHulst** [comment]
Ok, Eric thanks for the confirmation.

Robert
