### ISSUE TITLE
Change text for feedback email

### ISSUE THREAD

**Issue by lg2de** [EWSoftware/SHFB#807]
When clicking on the feedback link, the local mail client will be opened with a "new mail" including the configured feedback email address, etc.

The new mail is created with predefined text: _Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed._ It is defined as `feedback_body` in `c:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\PresentationStyles\VS2010\SHFBContent\en-US.xml`.

Is there an option to change this text for a single project or (even better) for multiple projects without changing the installed template file?

Working with SHFBInstaller_v2020.3.6.0

**Comment by EWSoftware** [comment]
Add a Resource Item file to the project.  Open it for editing, locate the feedback_body item and change its text.  When built, the text from the project's resource item file will be used instead.

**Comment by lg2de** [comment]
Ok, this works. Thanks!

There is a pitfall. When adding newline and/or carriage return to the editor, the created CHM will raise error messages and the link is broken. These special characters needs to be masked/reformatted.

The next days I'll try to create a PR therefore.
