### ISSUE TITLE
frame based HTML files with newer SFHB

### ISSUE THREAD

**Issue by kishkulk** [EWSoftware/SHFB#808]
We have upgraded SFHB to 3.6.0. The older SFHB used create frame based HTML pages so we had Table of content ( TOC ) and contents in different frames, now that with the newer SFHB both TOC and contents are embeded in a same page. Is there a way I can get the older style output using the newer SFHB. 

Basically we are looking something where we have TOC and content in a separate HTML pages. 

Thanks in advance.

**Comment by EWSoftware** [comment]
Use the VS2010 style which still uses the older frame based layout.
