### ISSUE TITLE
Return of ValueTask<T> breaks documentation for method

### ISSUE THREAD

**Issue by vonzshik** [EWSoftware/SHFB#809]
If return type of method is `ValueTask<T>` (for example, `ValueTask<int>`), in html documentation return type becomes `ValueTask`, type of the first argument becomes `void` and summary shows 'missing documentation'.

There is an example [here](https://github.com/vonzshik/SandcastleValueTaskBug).

May be similar to #763.

**Comment by EWSoftware** [comment]
There's a known issue where SHFB can't obtain the package references to the later versions of the .NET Core and .NET Standard packages.  It can typically be worked around by manually adding a reference in the SHFB project to *C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\netstandard.dll*.

**Comment by vonzshik** [comment]
Works like a charm. Thank you!
