### ISSUE TITLE
What is a good resource for the Sandcastle syntax?

### ISSUE THREAD

**Issue by RobThree** [EWSoftware/SHFB#813]
Edit: Wait... I just realized how stupid my question was... 🤦‍♂️

\***snip**\* question removed

More generally: Is there a good resource on this syntax anywhere that contains most of the available elements like `<para>`, `<codeEntityReference>`, `<section>` etc.?

**Comment by EWSoftware** [comment]
If you're looking for general information on the XML comments and MAML elements, see the [XML Comments Guide](http://ewsoftware.github.io/XMLCommentsGuide/html/4268757F-CE8D-4E6D-8502-4F7F2E22DDA3.htm) and the [MAML Guide](http://ewsoftware.github.io/MAMLGuide/html/303c996a-2911-4c08-b492-6496c82b3edb.htm).

If you have specific questions about particular elements, you can ask them here.  With regard to the code entity links, if you need help figuring out the member ID, the [Entity References tool window](http://ewsoftware.github.io/SHFB/html/e49eea91-a9ef-4aa5-ad8f-16ebd61b798a.htm) can help you search for them and insert them in the proper format.

**Comment by RobThree** [comment]
Thank you! All added to my bookmarks! 👍
