### ISSUE TITLE
BE0071 when using PackageReference for EWSoftware.SHFB and EWSoftware.SHFB.NETFramework

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#815]
When using
```
  <ItemGroup>
    <PackageReference Include="EWSoftware.SHFB" Version="2020.3.6" />
    <PackageReference Include="EWSoftware.SHFB.NETFramework" Version="4.7.2" />
  </ItemGroup>
```
(as actively recommended by a newly-created .shfbproj, although it points to an old package), the build fails with BE0071:
```
SHFB : error BE0071: Unable to locate information for the project framework version '.NET Framework 4.7.2' or a suitable redirect
ed version on this system.  See error number help topic for details.
```

The help page for the error suggests what causes this - it looks like the assumption for the NuGet packages is that their contents will be located under the project directory. When that is not the case, `ComponentPath` should be set.

This is doable when using `packages.config`. However, when using `PackageReference`, it is not. Packages will be restored at the machine level (typically in the user's .nuget folder), and no variables are set that point there.

So in order for this to work, it looks like the `EWSoftware.SHFB.NETFramework` package should include a .props file that either just sets `ComponentPath`, or sets some other property that can be used to set it in the project,

**Comment by Zastai** [comment]
Looks like there _can_ be a `PkgEWSoftware_SHFB_NETFramework` variable set by package restore. It will depend on the NuGet and MSBuild versions.
For my purposes, this is enough to make this issue non-blocking, but it would definitely be nicer if the `EWSoftware.SHFB.NETFramework` package handled this itself.

**Comment by EWSoftware** [comment]
See issue #748 as it appears to be related and may contain a solution.

**Comment by Zastai** [comment]
Looks like with MSBuild 15.x (with x = 8 or 9; not sure), you can add `GeneratePathProperty="true"` to a `PackageReference`.
A restore will then set (in the .g.props file) a `PkgFoo_Bar` variable (i.e. a `Pkg` prefix followed by the package id, with periods mapped to underscores) whose value is the full path to that package's folder (e.g. `C:\Users\Initech\.nuget\foo.bar\42.0.0`).

In MSBuild 16.x, the default behaviour seems to be that any package containing a `tools` folder (like the SHFB packages) automatically gets such a variable set.

That's safe enough for me, for now (we have standardised on VS2019, so we can be sure of support).
