### ISSUE TITLE
"Unresolved assembly error" trying to resolve a private static method

### ISSUE THREAD

**Issue by goyzhang** [EWSoftware/SHFB#816]
I'm using the build 2020.3.6 and I have an assembly A.dll that reference B.dll which contains a class called `RemoteConfig`. 

So I want to generate docs of public interface of A, this works fine and generates the docs
```
        public static int CreateDefault(string info)
        {
            // new RemoteConfig()
           //.....
        }
```

But if I wrap the creation of RemoteConfig into a private method:
```
        public static int CreateDefault(string info)
        {
            RemoteConfig config = CreateConfig(info);
            //.....
        }
        private static RemoteConfig CreateConfig(string info)
        {
            //.....new RemoteConfig()....
        }
```
It ends up with an error: 

> MRefBuilder (v2020.3.6.0)
>   Copyright &#184; 2006-2020, Microsoft Corporation, All Rights Reserved.
>   Portions Copyright &#184; 2006-2020, Eric Woodruff, All Rights Reserved.
>   No source code context base path specified.  Source context information is unavailable.
>   Loaded 1 assemblies for reflection and 1 dependency assemblies.
> MRefBuilder : error : Unresolved assembly reference: 

I didn't check the private member generation. 
I can bypass this by using the assembly binding redirect plugin to ignore but shouldn't SHFB simply ignore resolving a private member? At least it's good for performance? and I don't have to add a reference to a member that's not part of the `public` interface that I want to generate against.

**Comment by EWSoftware** [comment]
If you use the solution or project as the documentation source, it should resolve the references for you automatically.  There's a lot that goes into parsing the assemblies so it's not just a matter of ignoring members that you don't want.

**Comment by goyzhang** [comment]
> If you use the solution or project as the documentation source, it should resolve the references for you automatically. There's a lot that goes into parsing the assemblies so it's not just a matter of ignoring members that you don't want.

OK...So it's a technical limitation? In my CI env, I can only reach A.dll and A.xml for documentation generation. It references some other assembly internally as private members (they are from an authorized server I can't get them all at the doc generation stage) but all A's public interface types are self-contained for documentation. I guess I will have to manually add them all to the ignore list😢.

**Comment by EWSoftware** [comment]
If you can't add them as references to the SHFB project, you will have to use the plug-in to ignore them.

**Comment by goyzhang** [comment]
OK thank you! Looks like I need to go for the hard way 😅. Is this by design that you have to reference all assemblies even they are private and not visible in docs? If there is a plan or possibility to discuss this further?  otherwise, I can close this issue.
