### ISSUE TITLE
CopyFromIndexComponent warning: Entries for the key 'G:' occur in both....

### ISSUE THREAD

**Issue by MarcelVersteeg** [EWSoftware/SHFB#817]
I am documenting my solution and to fix ResolveReferenceLinksComponent warnings, I created a child project with all my referenced third party assemblies I do not want in my documentation. That child project is not built, but is configured main project in the Additional Reference Links plug-in with all the link types set to None.

However, when I then build the main project, I get an entry that says:
`CopyFromIndexComponent warning: Entries for the key 'G:' occur in both 'intermediate\7434A0B4\reflection.xml' and 'intermediate\reflection.xml'`

I also had similar warnings on regular types and methods and was able to suppress these by applying an API filter in the child project. However, I do not know how to suppress this one. I guess it has to do something with globals, but none of the globals of the child project are set to visible in the API filter.

Can you give a hint on how to solve this one?

**Comment by EWSoftware** [comment]
Just ignore them.  They won't affect the output.

**Comment by MarcelVersteeg** [comment]
I wish I would be able to ignore it. Our build output analyzer has a zero-tolerance on warnings (and errors). And a warning will simply make the build fail.

Is there really no way to configure the child project to exclude the 'G:' entry?

**Comment by EWSoftware** [comment]
There's an option on the component to suppress duplicate warnings but it's only enabled for comments files as it can and does happen with them.  It isn't used or exposed for the reflection files since there aren't typically duplicate members.  You'd have to write a plug-in to modify the configuration file options for the component.  It would quicker and easier to relax the warning level of your build for the documentation project.

**Comment by MarcelVersteeg** [comment]
I have been looking through the options of the SandCastle Help File Builder, but I can't find anything that has to do with the warning level of the documentation project.

The only option that makes any difference is the option "BuildAssembler Verbosity", that has three options:
- **All Messages**: The warning is emitted
- **Only warnings and errors**: The warning is still emitted
- **Only errors**: The warning is no longer emitted, but also warnings about missing documentation are no longer emitted. And I want to keep those.

Or do you mean to relax the parsing of the documentation project output in our build process?

**Comment by EWSoftware** [comment]
I meant in your build process since that's what appears to be preventing a successful build even with warnings.  If you've got some sort of "warnings as errors" setting for example, relax that for the SHFB project build.

**Comment by MarcelVersteeg** [comment]
We have modified our build process now to explicitly only exclude this warning.
