### ISSUE TITLE
Visual Studio 2019 16.8.0 Preview 5.0: Incompatible project

### ISSUE THREAD

**Issue by jefflill** [EWSoftware/SHFB#818]
SHFB project fails to load with **Visual Studio 16.8.0 Preview 5.0**.  VS migration report says" _"Incompatible Project"_

1. I had the **SHFB 09-2019** release installed originally which was working fine (as always) for VS 16.7.x (I don't remember the patch version I was on).
2. I uninstalled VS 16.7.x 
3. ...and then installed VS 16.8.0 preview 5
4. VS could not open a SHFB project
5. I uninstalled SHFB 09-2019 release and downloaded and **installed the SHFB 03-2020** release.
6. VS still could not open a SHFB project
7. I uninstalled the SHFB 03-2020** release and then **double clicked the VSIX** from the SHFB 03-2020 InstallResources folder to install it that way
8. VS still could not open a SHFB project

The Visual Studio solution output shows from the last step:
```
C:\src\neonKUBE\Websites\CodeDoc\CodeDoc.shfbproj : error  : The imported project "C:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the expression in the Import declaration "\SandcastleHelpFileBuilder.targets" is correct, and that the file exists on disk.  C:\src\neonKUBE\Websites\CodeDoc\CodeDoc.shfbproj
```

**Comment by EWSoftware** [comment]
It looks like it can't find the SHFBROOT environment variable.  You might try rebooting in case it's related to that.  If the VSIX installs successfully, it should be able to load the projects.

**Comment by jefflill** [comment]
That fixed it: **THANKS!**

...and I had tried the full install first and then saw you recommend installing the VSIX in an earlier unrelated issue so I thought I'd try that before bugging you.
