### ISSUE TITLE
Table of Contents exclusion plug-in crashes when all API items excluded from TOC

### ISSUE THREAD

**Issue by MarcelVersteeg** [EWSoftware/SHFB#819]
Let's say I have a project that only has one namespace and I added a few conceptual content pages. In the generated documentation I want to exclude the namespace from the Table Of Contents of the generated help file (.chm).

I have added the "Table of Contents Exclusion" plugin and added the `<tocexclude />` tag to the namespace documentation (it does not matter how I add this documentation, either via the Summaries configuration in the project, or via an external xml comments file). When I then build the documentation, the following error occurs:
`SHFB(0,0): error BE0029: Unexpected error while executing plug-in 'Table of Contents Exclusion': System.InvalidOperationException: Operation is not valid due to the current position of the navigator.`
and the documentation is not built.

**Comment by EWSoftware** [comment]
If you don't want API content, leave out the documentation sources and use the Additional Content Only plug-in to generate a help file containing only the conceptual content.  If you include API content, there has to be at least one namespace there.  The TOC exclusion plug-in can remove selected entries but not everything.
