### ISSUE TITLE
Unable to link to code references within namespace summaries

### ISSUE THREAD

**Issue by mjanulaitis** [EWSoftware/SHFB#82]
Although I've logged this as an issue I imagine I'm just doing something wrong.  I have added a namespace summary and included a link to a class I've referenced.  I used the following tag:

<codeEntityReference>T:MyNamespace.MyClassName</codeEntityReference>

Once compiled the tag is removed from the output but the reference is not linked.  If I copy and past the link to a topic, the link works so I know I haven't included a typo.  Any help would be greatly appreciated.

**Comment by EWSoftware** [comment]
Namespace comments entered in the project are just HTML.  As such, you need to use an anchor element and the topic's ID:

``` HTML
<a href="html/1b2dff59-92cc-4578-b261-f3849f30c26c.htm">MyClassName</a>
```
The ID is based on the Naming Method project property.  You can view the topic's HTML and find the ID.

If using a NamespaceDoc class, the normal `see` element with a `cref` attribute containing the class name should work as expected.

**Comment by mjanulaitis** [comment]
Thanks for your response. I got it working now.
