### ISSUE TITLE
More flexibility in building the help file layout/ToC

### ISSUE THREAD

**Issue by MarcelVersteeg** [EWSoftware/SHFB#820]
I have some general thoughts to be more flexible in building the layout of the generated help file including the Table of Contents using a `.layout` file.

- Allow to add only a certain subset of the API to be added as a child of a certain topic in the .layout file. Currently it is only possible to add the entire API to the ToC as a child of a certain topic or at the start or beginning of the ToC.
- Allow to add a specific API generated file in the ToC by using a reference like used in the MAML `<codeEntityReference>` and then also change the title of this topic
- Generally be able to change the (generated) titles of API topics

**Comment by EWSoftware** [comment]
This can probably be done now to some extent with a plug-in (see #865).  The new API TOC generator may also be of use.  Planned future changes to the presentation style components will likely address being able to use custom topic names.
