### ISSUE TITLE
Link generation to external .Net API doc reference posses risk of reverse tabnabbing

### ISSUE THREAD

**Issue by srprash** [EWSoftware/SHFB#821]
Hi,
I am using SHFB to build API docs for the [AWS X-Ray SDK for .Net](https://github.com/aws/aws-xray-sdk-dotnet). Link to the generated doc can be found [here](https://docs.aws.amazon.com/xray-sdk-for-dotnetcore/latest/reference/html/M_Amazon_XRay_Recorder_Handlers_SqlServer_TraceableSqlCommand_InterceptAsync__1.htm).
I noticed that the doc page for a method (for instance [this](https://docs.aws.amazon.com/xray-sdk-for-dotnetcore/latest/reference/html/M_Amazon_XRay_Recorder_Handlers_SqlServer_TraceableSqlCommand_InterceptAsync__1.htm) one) has reference to the Microsoft .Net API with the HTML tag `<a href="https://docs.microsoft.com/dotnet/api/system.threading.tasks.task-1" target="_blank">Task</a>` without using `rel="noopener noreferrer"` to cut the parent page's back link. This opens up a [reverse tabnabbing](https://owasp.org/www-community/attacks/Reverse_Tabnabbing) vulnerability in the API docs.

I am using the latest version of SHFB (2020.3.6.0) to generate the API help docs and [here](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/buildtools/API_Reference/AWSXRayDotNetCoreDocumentation/AWSXRayDotNetCoreDocumentation.shfbproj) is my SHFB project file. Is there something I can change in my project for a quick workaround? Thanks!

**Comment by srprash** [comment]
Hi, any update this?
Thanks in advance!

**Comment by EWSoftware** [comment]
It will require changes to the link generating components and perhaps the presentation styles to add the necessary attribute to all external links.

**Comment by srprash** [comment]
Thanks for the update! Any idea what would be the ETA on that?
Also, meanwhile is there a workaround possible to add the `rel=` attribute to the links while generation?

**Comment by EWSoftware** [comment]
No, there's isn't a workaround.  I don't have an estimate on when it will be added.

**Comment by EWSoftware** [comment]
All changes have been applied and will be in the next release due out soon.
