### ISSUE TITLE
Private members of base class cannot be kept out of documentation

### ISSUE THREAD

**Issue by MarcelVersteeg** [EWSoftware/SHFB#822]
Currently there are a few options in the visibility configuration that control how members of base classes are handled when creating the documentation of a class:
- Inherited base class members
- Inherited .NET Framework members
- Inherited .NET Framework internal members
- Inherited .NET Framework private members

Next to this there are visibility settings that control which members of the class itself need to be added to the documentation:
- Internal members
- Private fields
- Private members
- Protected members
- Protected members of sealed classes

However, I now have a situation like this (in C#):
```
public class A
{
    private int _privateToA;
    public abstract void DoSomething();
}

public class B : A
{
    private int _privateToB;
    public override void DoSomething() { }
}
```

Now I have enabled both the options "Inherited base class members" and "Private fields" when generating the documentation. In that case, the documentation of class `B` also includes the field `_privateToA`. While correct based on the given settings, I would like to exclude these inherited private (and internal when they are from another assembly) members in the documentation, as I cannot do anything directly with it from class `B`.

Preferrably this would be done using options similar to the ones offered for the .NET Framework.

**Comment by EWSoftware** [comment]
I've added a new visibility option to include internals from other assemblies and private members of base types and defaulted it to off so they will be excluded by default.  It will be in the next release.
