### ISSUE TITLE
Wrong documentation of default value for value type parameter

### ISSUE THREAD

**Issue by KGuetter** [EWSoftware/SHFB#823]
For the method

`public Task ConnectAsync(CancellationToken cancellationToken = default)`

SHFB 2020.3.6.0 creates the wrong C# documentation

`public Task ConnectAsync(CancellationToken cancellationToken = null)`

This code would not compile. Changing the declaration to "= default(CancellationToken)" does not make a difference.

**Comment by EWSoftware** [comment]
Fixed for the new release due out soon.
