### ISSUE TITLE
Add an Example for CustomPropertyGrid Class

### ISSUE THREAD

**Issue by sasiit23** [EWSoftware/SHFB#827]
Please add an example for CustomPropertyGrid Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://ewsoftware.github.io/SHFB/html/05ff2a02-c32f-2a90-7d77-4f32747e699f.htm

**Comment by EWSoftware** [comment]
This is just a custom control used by the SHFB standalone GUI.  There is no other documentation beyond what is given or examples of use as it's not needed for using SHFB in general.  All it does is add a `PropertyNamePaneWidth` property to allow setting the initial property grid name pane and a context menu to allow showing and hiding the description pane and resetting the selected property.  If you want an example of its use, see the [UserPreferencesDlg.cs and UserPreferencesDlg.Designer.cs files](https://github.com/EWSoftware/SHFB/tree/master/SHFB/Source/SandcastleBuilderGUI).  There's nothing more to it and would be used exactly the same as the base property grid with regard to placing it on a form.
