### ISSUE TITLE
Still: The Tools Version 15.0 is unrecognized.

### ISSUE THREAD

**Issue by KarloX2** [EWSoftware/SHFB#829]
Hello,
I've read the other ticket #797 which is marked as closed, but I still see this issue.
I have VS 2019 on my machine, no older VS versions installed.
And I just installed the latest bits of SHFB (SHFBInstaller_v2020.3.6.0).
Then tried to crate a new project in the Sandcastle Helper File Builder GUI. Right after entering the new project name I get this error and can't work on the project at all.
I'm not allowed to install older tools at the moment. We had a lot of other issues coming from older installations and we want to keep the installation clean.

Thanks for you help
Karlo

**Comment by EWSoftware** [comment]
It's fixed and the changes have been checked in.  I just haven't published a new release containing the fix.  For now, the same workaround applies: Use the Visual Studio package or install the VS 2015 tools if you really need the standalone GUI.

**Comment by KarloX2** [comment]
Thanks Eric. I wasn't really aware that I can do all the same in VS link in the standalone GUI.

**Comment by DiskCrasher** [comment]
> 
> 
> It's fixed and the changes have been checked in. I just haven't published a new release containing the fix. For now, the same workaround applies: Use the Visual Studio package or install the VS 2015 tools if you really need the standalone GUI.

The current release is nearly a year old now. Is this project dead?

**Comment by EWSoftware** [comment]
It's still alive.  I just haven't had much time to work on it.  Since this issue really only affects the standalone GUI and there are workarounds it's not been a high priority to publish an update just for this.

**Comment by DiskCrasher** [comment]
Some of us only use the standalone GUI. I can understand the time issue, but having a bug that potentially affects everyone running VS2019, workaround available or not, qualifies as high priority to me. A new user isn't going to know about the workaround and would likely be inclined to view SHFB as unreliable/abandoned software. Also look at how many times this issue has been reported.

**Comment by Spydrouge** [comment]
I genuinely just downloaded Sandcastle, followed its instructions for how to get started, and ran into being unable to make a new project because tools version 15 is not supported. There is no alternative 'getting started' guide for whatever workaround I'm supposed to use and since I just started I know nothing about Sandcastle or what it's done to my installation of VS. I'm completely in the dark. At the time of writing I have no idea how to use it to generate documentation.

**Comment by EWSoftware** [comment]
@Spydrouge If you have Visual Studio, install the Visual Studio extension and use Visual Studio to create the SHFB projects as it doesn't have an issue with the MSBuild version.  If you must use the standalone GUI for some reason, install [Build Tools for Visual Studio 2017 or later](https://download.visualstudio.microsoft.com/download/pr/3e542575-929e-4297-b6c6-bef34d0ee648/639c868e1219c651793aff537a1d3b77/vs_buildtools.exe) as it will resolve the issue.
