### ISSUE TITLE
hhc.exe fatal application exit

### ISSUE THREAD

**Issue by zcstkhk** [EWSoftware/SHFB#832]
The last step went wrong, throw an exception.
 There is no enough memory available for this task. Quit one or more programs to increase available memory, and then try again. 
But there is about 8GB memory still available.
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/5761252/LastBuild.log)

**Comment by EWSoftware** [comment]
HHC.exe is a 32-bit application so at best it'll only make use of 4GB on a 64-bit system.  Your project has over 102,000 topics which is extremely large.  If you can't trim down what is included such as only documenting public members if you are including private members for example, your only option if you want to produce a Help 1 file is to split it up into multiple projects and produce multiple Help 1 files.  If you want to keep it together as one set, I'd suggest switching to website output and host the content somewhere.

**Comment by zcstkhk** [comment]
> HHC.exe is a 32-bit application so at best it'll only make use of 4GB on a 64-bit system. Your project has over 102,000 topics which is extremely large. If you can't trim down what is included such as only documenting public members if you are including private members for example, your only option if you want to produce a Help 1 file is to split it up into multiple projects and produce multiple Help 1 files. If you want to keep it together as one set, I'd suggest switching to website output and host the content somewhere.
