### ISSUE TITLE
Optional listHeader tag of multi column list=table from XML not rendered

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#833]
I don't got rendered the listHeader with SHFB in my out. A code segment you can see below.

```XML
  /// <remarks>
  /// Usage of properties:
  /// 
  /// <list type="table">
  ///   <listHeader>
  ///     <term>Usage type</term>
  ///     <term>ParentId</term>
  ///     <term>Level</term>
  ///     <term>ChildId</term>
  ///   </listHeader>
  ///   <item>
  ///     <description>List Simple (General)</description>
  ///     <description>ListType (Tag; equal to mapping type)</description>
  ///     <description>0</description>
  ///     <description>Entry</description>
  ///   </item>
  /// ...
```

This I got rendered, but then I don't have a header for that table:

```XML
  /// <remarks>
  /// Usage of properties:
  /// 
  /// <list type="table">
  ///   <item>
  ///     <term>Usage type</term>
  ///     <term>ParentId</term>
  ///     <term>Level</term>
  ///     <term>ChildId</term>
  ///   </item>
  ///   <item>
  ///     <description>List Simple (General)</description>
  ///     <description>ListType (Tag; equal to mapping type)</description>
  ///     <description>0</description>
  ///     <description>Entry</description>
  ///   </item>
  /// ...
```

Output from the second code segment:

![image](https://user-images.githubusercontent.com/10100623/104341943-9dbe8c80-54fa-11eb-8314-b6b147363c35.png)

**Comment by EWSoftware** [comment]
There's a typo in the syntax section in the [XML comments guide](http://ewsoftware.github.io/XMLCommentsGuide/html/e433d846-db15-4ac8-a5f5-f3428609ae6c.htm) but the example section shows it correctly.  It should be `listheader` (all lowercase).  I'll fix it in the next release.  If you've got the Extended XML Doc Comments Provider extension installed, it is correct in the suggestions list.

**Comment by VBWebprofi** [comment]
´´listHeader´´ works with lowerUppercase right for (old?) "table" with

```XML
<list type="table">
  <listHeader>
    <term>Multi-column table header</term>
    <description>Add additional term or description elements to create new header columns</description>
  </listHeader>
  <item>
    <term>Multi-column table</term>
    <description>Add additional term or description elements to create new columns</description>
  </item>
  ...
</list>
```

when you use the single ``term`` and ``description`` combination at a line, that what the list type "definition" now defines.

Is the "definition" new? When, since which version? Didn't had this in mind.

**Comment by VBWebprofi** [comment]
Ok, now it works 😄
