### ISSUE TITLE
Error: SandcastleHelpFileBuilder.targets not found.

### ISSUE THREAD

**Issue by sparksustc** [EWSoftware/SHFB#834]
Environment:

VS2019, SHFB 2020.

After installing SHFB following the instructions, and trying to create a new project, vs pops up an error : 
The imported project "C:\SandcastleHelpFileBuilder.targets" was not found. 
Confirm that the expression in the Import declaration "\SandcastleHelpFileBuilder.targets" is correct, and that the file exists on disk.  

SHFB 2020:
https://github.com/EWSoftware/SHFB/releases/tag/v2020.3.6.0

Installation Instructions
http://ewsoftware.github.io/SHFB/html/8c0c97d0-c968-4c15-9fe9-e8f3a443c50a.htm

"When using the guided installation, you can skip the Requirements section below"

**Comment by EWSoftware** [comment]
Have you rebooted?  Sometimes the SHFBROOT environment variable does not take effect until after a reboot.  I should move the note about it up the the first section.
