### ISSUE TITLE
Paths tab on project properties throws an exception

### ISSUE THREAD

**Issue by SpareSimian** [EWSoftware/SHFB#836]
I'm adding a project to an existing VS2019 solution to document a C++-CLI library. After adding the project, I opened its properties to select sources. When I clicked on the Paths tab, I got "Exception has been thrown by the target of an invocation." All the other property tabs seem to function properly. This is my first use of SHFB. Is there a way to add the source list by manually editing the MSBuild project file? Is there an example project I can use to get the tags right?

**Comment by SpareSimian** [comment]
I pulled the project sources and found the test sample with an example I could base my edit on. So I'm able to build my .chm file.

**Comment by SpareSimian** [comment]
I'd added a documentation project to my large closed source project. I'm trying to run SHFB in the debugger with devenv.exe as the executable to debug so I can catch the exception from the "outer" debugger instance, but VS2019 doesn't break when the exception appears. If I switch to another properties tab and back, I see a white property page with no content. 

I cloned the repo, loaded and built the solution for SHFBProjectLauncher, and changed the debug properties to launch devenv.exe from my VS2019 installation. I hit F5 to start devenv and then loaded my own project into that debugger. I opened the properties page and triggered the exception by selecting the Paths tab. It displayed the election-caught message in the properties pane but the outer debugger didn't stop the inner one. Is there a better way to do this?

I'm going by instructions here: https://stackoverflow.com/questions/9281662/how-to-debug-visual-studio-extensions

**Comment by EWSoftware** [comment]
I don't need all your code and executables.  The SHFB project by itself should be enough to duplicate the issue.  Take the SHFB project file, add it to a blank solution and see if the problem can be duplicated.  If so, send that to me.  If you want to try and debug it yourself, you'd be better off building and running the extension project (SandcastleBuilderPackage.sln) as it will run Visual Studio as the target executable and it's just like debugging any other project.

**Comment by SpareSimian** [comment]
I was able to reproduce it on a minimal project. In SandcastleBuilder.Utils.FilePath.GetFullPath(string path) Line 373, System.IO.Path.GetFullPath is throwing "The given path's format is not supported". The argument is "F:\\devel\\shfb\\SHFB\\SHFB\\Source\\SandcastleBuilderPackage\\bin\\Debug\\$([MSBuild]::EnsureTrailingSlash('$(OutputPath)'))". I'm guessing the embedded function calls need to be resolved first. 

Stack:
 	[External Code]	
>	SandcastleBuilder.Utils.dll!SandcastleBuilder.Utils.FilePath.GetFullPath(string path) Line 373	C#
 	SandcastleBuilder.Utils.dll!SandcastleBuilder.Utils.FilePath.RelativeToAbsolutePath(string basePath, string relativePath) Line 550	C#
 	SandcastleBuilder.Utils.dll!SandcastleBuilder.Utils.FilePath.Path.set(string value) Line 149	C#
 	SandcastleBuilder.Utils.dll!SandcastleBuilder.Utils.FolderPath.Path.set(string value) Line 93	C#
 	SandcastleBuilder.Utils.dll!SandcastleBuilder.Utils.FilePath.PersistablePath.set(string value) Line 179	C#
 	SandcastleBuilder.WPF.dll!SandcastleBuilder.WPF.PropertyPages.FolderPathUserControl.PersistablePath.set(string value) Line 112	C#
 	[External Code]	
 	SandcastleBuilder.Package.dll!SandcastleBuilder.Package.PropertyPages.BasePropertyPage.Bind(object control, System.Reflection.PropertyInfo propertyInfo, string boundProperty) Line 499	C#
 	SandcastleBuilder.Package.dll!SandcastleBuilder.Package.PropertyPages.BasePropertyPage.BindProperties(System.Windows.Forms.Control.ControlCollection controls) Line 390	C#
 	SandcastleBuilder.Package.dll!SandcastleBuilder.Package.PropertyPages.BasePropertyPage.Microsoft.VisualStudio.OLE.Interop.IPropertyPage.SetObjects(uint cObjects, object[] ppunk) Line 786	C#
 	[External Code]

**Comment by EWSoftware** [comment]
It appears that a copy of the OutputPath property is being generated in Microsoft.Common.targets that wraps the original's value in the function call to ensure a trailing backslash.  I've updated handling of the unevaluated values for editing so that it always retrieves the value from the property in the SHFB project.  The change will be in the next release due out soon.

In the meantime, you can work around the issue by placing the OutputPath property at the end of the project after the Microsoft.Common.targets import.  That ensures our copy overrides all others.

```
<Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="'$(MSBuildRestoreSessionId)' != ''" />
<PropertyGroup>
    <OutputPath>Help\</OutputPath>
</PropertyGroup>
```
