### ISSUE TITLE
Ignoring code generated by C macro

### ISSUE THREAD

**Issue by SpareSimian** [EWSoftware/SHFB#838]
My exceptions are generated by a macro:

    #define SimpleManagedException(derived_class, base_class) \
        public ref class derived_class : base_class \
        { \
            public: \
                derived_class(const MyNameSpace::derived_class& e) : base_class(e.what()) {} \
            protected: \
                derived_class(const char* what) : base_class(what) {} \
        }

I see no way to automate generating XML comments for that. Is there some way to exclude these so they don't generate warnings?

My documentation source is set to my C++/CLI project. Is there a way to exclude my Exceptions.h?

**Comment by SpareSimian** [comment]
I found the API filter and, with a bit of editor search-and-replace, fabricated appropriate XML lines for the project file to exclude all my exception classes. Although I'm wondering if this is the right way to do this.

**Comment by EWSoftware** [comment]
Assuming you are referring to the `exclude` XML comment element, that will work.  Another option is to tag the class with the `CompilerGenerated` attribute.  Such classes are automatically ignored for documentation unless explicitly included by setting the option in the Visibility category.

**Comment by SpareSimian** [comment]
That sounds like what I should do. I was debating writing a Perl script to generate the header and pump XML comments into it, so "CompilerGenerated" really describes what I'm doing in this case.

**Comment by SpareSimian** [comment]
I found the attribute line in my macro needs to be this:
     [System::Runtime::CompilerServices::CompilerGeneratedAttribute()] \
