### ISSUE TITLE
HTML Help Workshop No longer available

### ISSUE THREAD

**Issue by Adventurer21** [EWSoftware/SHFB#839]
I just went to the link in the guided installation to install the HTML Help Workshop and it's no longer there.  Just a message about the current tech being API based.  

I did find an old copy [here](https://www.helpandmanual.com/download/htmlhelp.exe).  For anybody who needs it.

**Comment by EWSoftware** [comment]
They have that issue once in a while.  The usual page appears to be back but the download link for the HTML help work shop is not working at the moment.  I've also got a copy available on [my website](http://www.ewoodruff.us/downloads/htmlhelp.exe).

**Comment by Adventurer21** [comment]
Cool thanks.  Mostly left this issue as a resource for people who are struggling.
