### ISSUE TITLE
ResolveReferenceLinksComponent due to native parameter types

### ISSUE THREAD

**Issue by SpareSimian** [EWSoftware/SHFB#840]
My C++/CLI project wraps a native C++ DLL. APIs that take a native type as an argument are throwing a ResolveReferenceLinksComponent warning. 

    public ref class MyClass
    {
    public:
    MyClass(myNativeClass& nativeObject); 
    };

These members are for internal use of the library, to be called by an internal factory method. Is there a way to mark them (ie. an attribute) to be ignored for creating documentation?

**Comment by EWSoftware** [comment]
You can use the API filter to exclude them or add an `<exclude/>` XML comment on them to exclude them.  They'll be added to the API filter automatically.
