### ISSUE TITLE
changing location  of  GenerateRefInfo.projAssemblyReference.cache

### ISSUE THREAD

**Issue by jmecosta** [EWSoftware/SHFB#841]
Hi,

im building a few Documentation projects in parallel using msbuild /m and notice that i get some failures because this file is being used by several projects..

is there a way to add assemblyName to the path so they dont compete with the cache file?
<SRC>\ObjDrop\Work\x64\GenerateRefInfo

thanks

Project &quot;E:\prod\ts-build\ObjDrop\Work\Release\x64\SandcastleDmInternal\GenerateRefInfo.proj&quot; on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): error MSB3101: Could not write state file &quot;E:\prod\ts-build\ObjDrop\Work\\x64\GenerateRefInfo\GenerateRefInfo.projAssemblyReference.cache&quot;. The process cannot access the file &#39;E:\prod\ts-build\ObjDrop\Work\x64\GenerateRefInfo\GenerateRefInfo.projAssemblyReference.cache&#39; because it is being used by another process. [E:\prod\ts-build\ObjDrop\Work\Release\x64\SandcastleDmInternal\GenerateRefInfo.proj]
GenerateBindingRedirects:
  No suggested binding redirects from ResolveAssemblyReferences.
GenerateRefInfo:
  MRefBuilder (v2019.9.15.0)

**Comment by EWSoftware** [comment]
I can probably just give GenerateRefInfo.proj a unique name.  The reference resolution is part of Microsoft.Common.targets so I can't say what it's doing behind the scenes or if it offers a way of naming the cache location.

**Comment by jmecosta** [comment]
but is the variable u use to get that path? i can probably track the property i need to set in the project file... 

the easiest would that the GenerateRefInfo would follow the project name, that way is also "unique" (user defined)

**Comment by EWSoftware** [comment]
This fix has been made and is in the latest release.

**Comment by jmecosta** [comment]
Thanks for the quick fix. A let you know later if all good.
