### ISSUE TITLE
Long Term: .NET Core builds

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/SHFB#843]
Support for .NET Core builds was previously discussed in issue #517.  An evaluation branch was submitted.  I'll be removing that in favor of a much larger overhaul to more cleanly support multi-targeted builds with better separation of the build components from their related UI configuration components.

**Comment by ritchiecarroll** [comment]
Sounds good Eric - best of luck, please let me know if I can help - in any way. I know this is no easy task, but I am excited to keep "the best available tool" for .NET docs relevant for future platforms. The open source community owes you a great debt for your continued perseverance here.

**Comment by glenncarr** [comment]
Ditto to that @ritchiecarroll

**Comment by EWSoftware** [comment]
The major overhaul needed to support both MSBuild.exe and dotnet.exe is complete and the build engine will now run under both.  I've checked in all of the changes to the [DotNetBuildSupport branch](https://github.com/EWSoftware/SHFB/commit/95f05af39e496f413d6a236bd39f536267e621de).

I've tested the major parts but given the amount of code and features, there may be some stuff I've missed and there may be issues with stuff not working as expected.  I've got a few outstanding issues to look into and some more refactoring that I plan on doing but, for the most part, dual build support is complete.  The breaking changes were significant, especially where build components, plug-ins, and presentation styles are concerned to get a clean separation between the platform-specific and non-platform-specific parts.  I'll provide documentation on porting existing components to the new model at a later date.

Still to do: Get rid of the XSL transformations in the presentation styles.

**Comment by ritchiecarroll** [comment]
Nice work Eric! I knew this was going to be a push. I'll try to do some testing on your new branch soon.

**Comment by EWSoftware** [comment]
Progress update:
- Updated all template projects so that they work with the updated build engine.
- Updated all template projects so that they use the new SDK format and generate their output as NuGet packages.  This makes them easier to find and use and no longer requires a common component path setting be used in the help file builder projects to locate them.
- Updated the standalone GUI and Visual Studio package to support adding package references to help file builder projects for build components, plug-ins, presentation styles, and syntax generators interactively with a search dialog box .  The component packages are shown in a separate node in the project/solution explorer tool window.
- Updated the build engine to search for build components, plug-ins, presentation styles, and syntax generators added to the project as NuGet packages by looking for their SHFBComponentPath items.

The next big push will be seeing about VS2022 support so this will be on the back burner for a while.

**Comment by ritchiecarroll** [comment]
Looks like you are making great progress! Yeah, I haven't even installed VS2022 yet, but I am looking forward to 64-bits to take advantage of more memory for large projects.
