### ISSUE TITLE
'GenerateReflectionInfo' build step causes MSB1008 if path contains a whitespace

### ISSUE THREAD

**Issue by RalfKoban** [EWSoftware/SHFB#844]
The "_GenerateReflectionInfo_" build step causes an **MSB1008** MSBuild error in case the path that is provided contains a whitespace.

In such case, the _SandcastleHelpfileBuilder.log_ file contains following:

```
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe - D:\Private\MiKo Solutions\MiKo Aspects\Source\MiKo Aspects Documentation\Help\Working\GenerateRefInfo-2a162baf-e21c-455c-8a70-9d0e349238b6.proj]
MSBUILD : error MSB1008: Es darf nur ein Projekt angegeben werden.
Schalter: Solutions\MiKo

Informationen zur Schaltersyntax erhalten Sie, wenn Sie &quot;MSBuild -help&quot; eingeben.
    Last step completed in 00:00:00,2982
</buildStep>
```

Probably, the issue would go away if the project to build is surrounded with quotes.

**Comment by EWSoftware** [comment]
It's the change I made to give it a unique name.  It retained the full path.  I can just remove the path so it was like it was prior to the change but keeps the unique name.

**Comment by RalfKoban** [comment]
May it is sufficient to just wrap the full path with some `"` quotes so that MSBuild can find the project.

So that
```
MSBuild.exe - D:\Private\MiKo Solutions\MiKo Aspects\Source\MiKo Aspects Documentation\Help\Working\GenerateRefInfo-2a162baf-e21c-455c-8a70-9d0e349238b6.proj
```

would become
```
MSBuild.exe - "D:\Private\MiKo Solutions\MiKo Aspects\Source\MiKo Aspects Documentation\Help\Working\GenerateRefInfo-2a162baf-e21c-455c-8a70-9d0e349238b6.proj"
```

**Comment by EWSoftware** [comment]
A new release is available containing the fix.
