### ISSUE TITLE
Documentation build fails if there is a variable with a single quote ' in the name

### ISSUE THREAD

**Issue by JosephBrooksbank** [EWSoftware/SHFB#845]
Our F# code contains variables with single ticks in the names, ex: `type'`. Sandcastle fails when parsing documentation for these with: `Error adding missing documentation tags: This is an unclosed string. ` even if documentation exists for them.

**Comment by EWSoftware** [comment]
Can you provide a small example that I can build?

**Comment by JosephBrooksbank** [comment]
[845Example.zip](https://github.com/EWSoftware/SHFB/files/6344644/845Example.zip)

**Comment by EWSoftware** [comment]
It appears to be an issue with the missing parameter documentation option.  To work around it, enable generation of the XML comments file in the documentation source project or, if there are still missing XML comments, disable the "param elements" option in the Missing Tags category in the SHFB project.
