### ISSUE TITLE
Unable to download HTML Help (Microsoft link broken)

### ISSUE THREAD

**Issue by anwesa1982** [EWSoftware/SHFB#847]
There is a dependency to install HTML Help to use Sandcastle. I am unable to download HTML Help from Microsoft (https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/microsoft-html-help-downloads?redirectedfrom=MSDN) since the download link is broken. 

Please let me know where to download HTML Help. 

Thanks
Anwesa

**Comment by EWSoftware** [comment]
If you aren't going to create Help 1 (CHM) files, you can skip that step and move on to installing the tools.  If you will be creating them, you can download a copy from [my website](http://www.ewoodruff.us/downloads/htmlhelp.exe).

**Comment by anwesa1982** [comment]
Thanks a ton!!
