### ISSUE TITLE
Unable to locate information for the project framework version (.Net framework 3.5)

### ISSUE THREAD

**Issue by goyzhang** [EWSoftware/SHFB#848]
The dll is targeting .net 3.5. Using SHFB v2021.4.9.0. This pops up when building.
There is no such issue in 2020.3.6.

**Comment by EWSoftware** [comment]
See the [v2021.3.29.0 release notes](http://ewsoftware.github.io/SHFB/html/70b704dc-03c8-4934-b83e-e84d4d7f927a.htm).  I removed many of the older frameworks to cut down on the clutter.  Even though the documentation source targets an earlier version, you should be able to just change the SHFB project to target one of the supplied .NET Framework versions from 4.0 to 4.8 as they are equivalent.

**Comment by goyzhang** [comment]
Resolved by changing the content in .shfbproj to target 4.0. Thanks!
