### ISSUE TITLE
Documentation building failure on Azure DevOps pipline

### ISSUE THREAD

**Issue by raczeja** [EWSoftware/SHFB#850]
I updated [Ocaramba.Documentation.shfbproj](https://github.com/ObjectivityLtd/Ocaramba/blob/documentation/Ocaramba.Documentation/Ocaramba.Documentation.shfbproj) according to comment from #812

but still getting error
##[error]SHFB(0,0): Error BE0071: Unable to locate information for the project framework version '3.2.6' or a suitable redirected version on this system. See error number help topic for details. at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

the "3.2.6" is a tool version set by [Assembly-Info-NetCore@2](https://github.com/ObjectivityLtd/Ocaramba/blob/documentation/azure-pipelines.yml#L52), but only for **/*.csproj'

https://dev.azure.com/ocaramba/Ocaramba/_build/results?buildId=364&view=logs&j=2e509f49-8702-5de8-af5f-da15fc875e1f&t=56724902-0f20-59e9-90b4-9391c9cbdf86&l=47

logs: https://dev.azure.com/ocaramba/Ocaramba/_build/results?buildId=364&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by EWSoftware** [comment]
What SHFB version are you using?  There was an issue in an earlier release where an imported property named the same as a SHFB property was overriding the SHFB property causing a similar failure (see #836).  The latest release resolves that.  If it's still happening in the latest release and is the same issue for this case, moving the FrameworkVersion property to the end of the SHFB project file in its own group after all other imports should resolve the issue.

**Comment by raczeja** [comment]
I'm using the latest version 2021.4.9, I moved the TargetFrameworkVersion to the end of  the SHFB project file in its own group, but I'm still getting error:
##[error]SHFB(0,0): Error BE0071: Unable to locate information for the project framework version '3.2.6' or a suitable redirected version on this system

**Comment by EWSoftware** [comment]
Sorry, I don't know what might be causing that and don't have access to a similar environment to try and reproduce it.  It would appear that something is overriding the SHFB project's FrameworkVersion property though.

**Comment by raczeja** [comment]
with AppVeyor there is an option to keep connection for 1 hour and use RDP https://github.com/ObjectivityLtd/Ocaramba/blob/master/appveyor.yml#L121, https://ci.appveyor.com/project/ObjectivityAdminsTeam/ocaramba/builds/39637097/job/3gaumsjeugn3l7lb
