### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by SalmanZafar214** [EWSoftware/SHFB#851]
i have installed SandCastle latest version and upon execution faced below error 

![image](https://user-images.githubusercontent.com/6292940/122393316-2f409780-cf8e-11eb-8a36-0597d54b654b.png)

![image](https://user-images.githubusercontent.com/6292940/122393339-35cf0f00-cf8e-11eb-9099-8b9d386ad86b.png)

![image](https://user-images.githubusercontent.com/6292940/122393417-4b443900-cf8e-11eb-972b-3bdaf0a86a7c.png)

Can someone help me out whats wrong ?

**Comment by EWSoftware** [comment]
SHFB looks for custom components in the project folder.  Put your SHFB project in it's own folder as you would with any other Visual Studio project rather than in the My Documents folder directly.  That will prevent it from scanning folders it doesn't have access to.

**Comment by SalmanZafar214** [comment]
Thanks @EWSoftware .
