### ISSUE TITLE
Support for VS 2022

### ISSUE THREAD

**Issue by Bassman2** [EWSoftware/SHFB#852]
Please add support for the new Visual Studio 2022 Preview

**Comment by EWSoftware** [comment]
It is planned but this will take a while.  I need to split the project to build a version specific to VS2022.  Thorough testing is also required as some breaking API changes are not apparent at build time and only occur at runtime.  As you can image, there's a ton of stuff to test in the project system.  Whether or not the old MPF project system is usable under 64-bit VS2022 is also in doubt.  I won't know more until I start trying it out.  If it's not feasible to update it, I'll have to consider switching to the Common Project System (#90) which will require a lot more work.  I've been putting off switching to it but may have to now.

**Comment by EWSoftware** [comment]
Support has been added and will be in the next release.
