### ISSUE TITLE
Building XSD documentation

### ISSUE THREAD

**Issue by MarAlder** [EWSoftware/SHFB#853]
Hi,

I'm using SHFB to build the XSD documentation for the [aviation data exchange format CPACS](https://github.com/DLR-SL/CPACS). This requires the [XML Schema Documenter](https://github.com/terrajobst/xsddoc) plug-in, which was last updated in 2016 and has apparently not been further developed since then.  This plug-in requires SHFB 2015.7.25.0.

Because I don't like to work with an outdated version when I have questions about SHFB, I wanted to update to the current SHFB release. Are there ways to document XSD with [SHFB 2021](https://github.com/EWSoftware/SHFB/releases/tag/v2021.4.9.0) or is this no longer possible after the development stop of XSDDoc?

**Comment by EWSoftware** [comment]
The plug-in projects just needed updating for use with the latest release.  I've created a fork here: https://github.com/EWSoftware/xsddoc

Download and build the code using build.cmd in the root folder.  You may need to update the path to MSBuild.exe in it.  After building it, install the plug-in using the MSI file in the bin\Setup folder or just point your project's component path at the bin\Raw folder so that SHFB can find it.

**Comment by MarAlder** [comment]
Thanks @EWSoftware! This is working fine.

**Comment by MarAlder** [comment]
May I ask if something in the XSDDoc plugin needs to be adopted to the new SHFB release? I'm setting up SHFB on a new system, installed the required MSVS packages and SHFB itself. Building the plugin then gives errors like:

```Typy- or namespace name "SandcastleBuilder" not found```

Or did I miss something else?

[msbuild.log](https://github.com/EWSoftware/SHFB/files/8116951/msbuild.log)

**Comment by MarAlder** [comment]
Thank you for your answer. Acutally I already used your fork. Maybe something else is set up differently now, but as SHFB just compiled without problems I was wondering whether it relates to the new SHFB release. Not sure why the namespace "SandcastleBuilder" is not found. I reboot after SHFB installation did not help.

**Comment by EWSoftware** [comment]
XSDDoc is separate from SHFB and is using NuGet packages for the SHFB references so I'm not sure why it would be failing to build.  The packages are binary compatible with the latest release.  I just tried building it using the build.proj file and it worked.   You might try just opening the project in Visual Studio and seeing if it will build there.

**Comment by MarAlder** [comment]
I understand their point, but unfortunately I did not get it compiled. My NuGet and Visual Studio knowledge is probably not enough here. It remains with [this error message](https://github.com/EWSoftware/SHFB/files/8116951/msbuild.log).

Would you possibly provide me with the compiled binaries of the plugin? Then I could continue building the CPACS docs with it.

**Comment by EWSoftware** [comment]
I didn't notice the last time I build it from the command line that I had a minor but necessary change that I had not checked in.  It's been committed so if you fetch the latest changes, it should build now.

**Comment by MarAlder** [comment]
Sorry to be a pain here again. We haven't managed to install `xsddoc` yet. Since there is no issues-board on your fork, I would like to revisit the topic here. 

As background, I must confess that I have no experience with C# and nuget package manager and am just reading up a bit deeper. 

What I did so far:
- downloaded and followed the install procedure of [SHFBInstaller_2022.12.30.0](https://github.com/EWSoftware/SHFB/releases/tag/v2022.12.30.0) (to make sure it is consistent with your xsddoc fork)
- restart computer
- cloned your latest [fork](https://github.com/EWSoftware/xsddoc) & changed the path to my MSBuild.exe in `build.cmd`
- run `build.cmd` fromm windows terminal

This returns errors. The first error states:
```
C:\Workspace\ResearchSoftware\xsddoc\src\XsdDocumentation.PlugIn\Configuration\FilePathCollection.cs(4,7): error CS0246: Der Typ- oder Namespacename "SandcastleBuilder" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [C:\Workspace\ResearchSoftware\xsddoc\src\XsdDocumentation.PlugIn\XsdDocumentation.PlugIn.csproj]
```
or translated:
```
C:\Workspace\ResearchSoftware\xsddoc\src\XsdDocumentation.PlugIn\Configuration\FilePathCollection.cs(4,7): error CS0246: The type or namespace name "SandcastleBuilder" was not found (possibly missing a using directive or assembly reference). [C:\Workspace\ResearchSoftware\xsddoc\src\XsdDocumentation.PlugIn\XsdDocumentation.PlugIn.csproj]
```

XsdDocumentation.PlugIn.csproj shows:
```
 <ItemGroup>
    <PackageReference Include="EWSoftware.SandcastleBuilder.Utils">
      <Version>2022.12.30</Version>
    </PackageReference>
  </ItemGroup>
```

I'm not sure how to run the project from vscode. 

We would be very grateful for further support in troubleshooting.

**Comment by EWSoftware** [comment]
Ignore the version on the package in the XSDDOC project.  It will typically be earlier than the latest actual SHFB release since I don't publish new NuGet packages with each SHFB release.  It's just the latest binary compatible version.  I only update the NuGet packages if something in the API changes.  So, if you install the latest SHFB release, it should build without issue.  It does for me anyway.  Building from within Visual Studio is just a matter of opening the solution file in the src\ folder.

**Comment by MarAlder** [comment]
Thanks, got it :)
