### ISSUE TITLE
Generated links are failing due to Azure folder structure

### ISSUE THREAD

**Issue by CharlyEur** [EWSoftware/SHFB#856]
### Azure publication
Hello,
I use SHFB to generate the comprehensive markdown files related to my classes (through VS2019, nice integration).

When I publish code as wiki in AzureDevOps (Help directly), the issue seems to be that Azure will store every markdown file in a different directory.
Typically, I get _root/**2354**/xxx.md_ while I am expecting _root/xxx.md_. The result is that most of the hyperlinks are broken :sad:
Do you have any clue about how to work this around ?

**Comment by EWSoftware** [comment]
The presentation style expects everything to be in a common folder.  You'd probably have to write a plug-in to post-process the topics and TOC file to fix up the links assuming the folder names can be determined ahead of them being published.

**Comment by CharlyEur** [comment]
Thanks ! I will take a look at it. It seems numbering is deterministic, let's delve in post-processing 😄
Seems AzureDevOps is assuming generated mds has sub-pages 😢 -> https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops
Many thanks for the quick answer.
