### ISSUE TITLE
SectionExpanded.png and SectionCollapsed.png not show

### ISSUE THREAD

**Issue by chuongmep** [EWSoftware/SHFB#858]
I have a problem with image builder, any have same problem ?
![image](https://user-images.githubusercontent.com/31106432/127122697-2a47a498-aa18-4ccf-b407-b2ed70c8011f.png)
It sill include in resource templete
![image](https://user-images.githubusercontent.com/31106432/127122874-c7c2ce0b-72e1-46ed-983e-cfd72170c287.png)
i see a problem same with https://github.com/EWSoftware/SHFB/issues/629

**Comment by EWSoftware** [comment]
You're not getting any images.  See the methods section in the topic and the "Public method" icons are missing too.  Are you perhaps running this off of a network share?  Typically, if that's the case, all the content is blocked though.  If you build the help as a website do you get the images?  Do you see any warnings or errors in the build log?

**Comment by chuongmep** [comment]
Im build a file chm to read in local, only icon SectionExpanded.png and SectionCollapsed.png not show.
![image](https://user-images.githubusercontent.com/31106432/127260549-0f415a17-f512-4ec3-a5a2-c5f64c3a1ace.png)
This is a my log.
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/6890156/LastBuild.log)

**Comment by EWSoftware** [comment]
See your build log.  You're getting a [BE0060 warning](http://ewsoftware.github.io/SHFB/html/e076c319-ff84-40dc-bb00-ff4c72718215.htm) because your path contains ".H".  The help 1 compiler has problems with that and it can cause strange issues like this.  Rename the folder to get rid of the ".H" and all should be good.

**Comment by chuongmep** [comment]
It user name of my computer : ( , whether we should fix bug or fix manual by hand ?

**Comment by EWSoftware** [comment]
This is a limitation of the Help 1 compiler and isn't something that can be fixed.  If you can't move the entire project to a different location, another alternative is to set the [Output Path](http://ewsoftware.github.io/SHFB/html/e6fcfa33-e7ee-430a-abfe-6b7962e6d068.htm#OutputPath) to a different location.  For example, create a folder such as C:\HelpOutput\3DObjectsHelp and set the help project's output path property to that.  Leave the working folder path set to the default and it will output the working folder under that as well during the build.

**Comment by chuongmep** [comment]
Thanks so much, it working for me.
