### ISSUE TITLE
Generated documentation not inserted correctly with sitemap and chm

### ISSUE THREAD

**Issue by nickisely** [EWSoftware/SHFB#859]
So currently upgrading to the latest tooling from a very old version. We are generating a .chm file and we have the new project and it seems to be building fine. However we would like to place the generated API documentaion under a certain section we have defined in our .sitemap. From the GUI editor we have "Api Topic: Insert After this Topic" selected on the topic where we want the generated documentation inserted at. The issue we are having is it is always placing the generated documentation at the end of the TOC at the top level. Is there something else we need to be doing to get this to work correctly?

**Comment by EWSoftware** [comment]
This has been fixed and will be in the next release.

**Comment by EWSoftware** [comment]
This has been fixed and will be in the next release.
