### ISSUE TITLE
Add an Example for EditorCommands.ExpandAll Property

### ISSUE THREAD

**Issue by satinja** [EWSoftware/SHFB#860]
Please add an example for EditorCommands.ExpandAll Property.

Help Topic: https://ewsoftware.github.io/SHFB/html/b8087e6c-68cf-bea5-cf27-a9ce155337ec.htm

**Comment by EWSoftware** [comment]
This is part of the standalone GUI and isn't used by build components etc.  There doesn't appear to be a need for an example.
