### ISSUE TITLE
Possible to reuse same topic ID?

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#861]
I'm attempting to reuse the same topic within different sections of the help content, but I'm getting this error:

`SHFB : error BE0058: Two conceptual content files have the same ID (my_topic_id).  The file with the duplicate ID is '<path to AML file>'`

Is that possible by simply referencing the common file, or do I need to use a token or similar?

Thanks.

**Comment by EWSoftware** [comment]
You can create a link to the same topic from to different places within a topic but each topic file must have a unique ID.  Within topics, each section ID (address attribute) must also be unique if any are defined.  The error above indicates that you have two topic files with the same ID.  For example, you copied the content of one to create another but forgot to change the ID in the new topic.
