### ISSUE TITLE
Include robots meta tag

### ISSUE THREAD

**Issue by pmerwood** [EWSoftware/SHFB#862]
Hi

I'm using SHFB to build a documentation Website (HTML/ASP.NET).  The documentation will be hosted on a public-facing web server so I want to include a robots meta tag in the <Head> of each page SHFB builds, ie; <meta name="robots" content="noindex" />.  If I use the "Additional header content" property on the Help File property page, the meta tag is added but inside the <body> not the <head>.  Can you tell me how I can get the meta tag into the <head> please.  Thanks

Peter

**Comment by EWSoftware** [comment]
There's a build component that inserts additional resources into the topics such as stylesheets, scripts, and metadata.  The easiest approach would be to [create a plug-in](http://ewsoftware.github.io/SHFB/html/a14e026e-642f-4ce6-9506-341e57cc3d1f.htm) that runs just before the BuildAssembler step that modifies the BuildAssembler configuration file (sandcastle.config in the working folder) by inserting an extra metadata element into the Additional Header Resources Component configurations.  There are multiple instances, one for each output format in each section for conceptual and API topics.

I can provide more details if you want to pursue this.

**Comment by pmerwood** [comment]
Thanks for your prompt response Eric.  What you've proposed sounds complicated but I'm up for the challenge :)

I've read through the Creating Build Process Plug-Ins topic and think I follow what needs to be done there.  However, if you have the time to provide more details I'd be grateful of that.  Additional details are sure to save me some time.  Thanks.

**Comment by EWSoftware** [comment]
This is a fairly simple plug-in so you won't have to deal with a configuration for it.  In this case, you'd have it run after the `MergeCustomConfigs` build step.  You can get the `WorkingFolder` location from the build engine instance.  In that folder, you'll find the `sandcastle.config` file.  You'd load that (it's XML), search for all of the `component` elements with an ID of "Additional Header Resources Component", and add the extra metadata element for the robots  value to it as a child element to each one.

A good example to look at is the [Bibliography Support plug-in](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/BibliographySupportPlugIn.cs) as it basically does the same thing but for a different component.   You can use that as a template but ignore the bits the relate to its configuration.

**Comment by pmerwood** [comment]
Thanks Eric.  Adding the Meta tags hasn't bubbled up to the top of my workplan yet but isn't far away.  When I get to it, using the Bibliography Support Plug-in will be a good place to start from.  I've had a good look at the Plug-in code and think I can see what it's doing.

I've got a couple of other questions for you as we develop this help resource that I'll post in separate threads in the next few days.

Cheers
