### ISSUE TITLE
Link to URL fragment

### ISSUE THREAD

**Issue by pmerwood** [EWSoftware/SHFB#864]
Sorry - I've read all the info I can find about links to Conceptual Content but I can't get a link that includes a fragment to work in a web site.

The Sandcastle MAML Guide says "You can link to anchors within the target topic by adding a hash character (#) followed by the anchor name after the topic's GUID. For in-page links, simply specify a hash character (#) followed by the name of the anchor from an element's address attribute. Inner text is required for in-page links."

In a Conceptual Content page I've got the following:  `<para address="Position">Position</para>`
In another page I want to link to that paragraph so I use:  `<link xlink:href="4478e351-65f6-4e9b-a2e0-8022d2d50da2#Position">Position</link>`

The above link works within the Visual Studio Topic Previewer and in an HTML Help (chm) file.  But it will not work when Sandcastle generates a Website.

In the web page Sandcastle builds the hyperlink seems to be correctly constructed (`<a href="4478e351-65f6-4e9b-a2e0-8022d2d50da2.htm#Position">Position</a>`) but the anchor name isn't included - just `<p>Position</p>` is generated.

How do I resolve this dilemma?

**Comment by EWSoftware** [comment]
It may work in the topic previewer as it's just interpreting the MAML directly without any particular adherence to the schema with regard to attribute usage location.  I doubt it's working in the CHM file as the HTML rendering is the same for both it and website output.  It's most likely just linking to the topic but not scrolling down to the link.  If you look at the rendered HTML for the topic, you won't find the required `id` attribute on the paragraph.

Only a handful of elements support an `address` attribute.  These are noted in the MAML guide (`definedTerm`, `introduction`, `listItem`, and `entry`).  The `section`, `glossaryDiv`, and `glossaryEntry` elements also support it but aren't included in the guide except indirectly through the topic type examples.  If added to other elements such as `para`, the presentation styles ignore it as they don't look for it there.

If you can't link to a containing parent element that supports it, you can simulate the use of the attribute using the `markup` element to render a span with the appropriate ID in it to act as the link target.  For example:

```
<para><markup><span id="Position"/></markup>This is the position</para>
```

Markup elements aren't supported in the topic previewer.  It just renders the markup content so the links won't work there but will in the built output regardless of type.

**Comment by pmerwood** [comment]
Thanks.  The list of elements that support the `address `attribute is handy to know and has allowed me to move the attribute from the [para ](url)element to a nearby `listItem `or `entry` element that does the job.
