### ISSUE TITLE
ERROR: There was an error installing the Sandcastle extension for Visual Studio Professional 2017. The exit code returned was 2003

### ISSUE THREAD

**Issue by binbashblog** [EWSoftware/SHFB#866]
Getting this error trying to install:

ERROR: There was an error installing the Sandcastle extension for Visual Studio Professional 2017. The exit code returned was 2003

**Comment by EWSoftware** [comment]
Try updating Visual Studio 2017 with the latest patch (15.9.39).  You can also run the VSIX installer manually from the .\InstallResources folder and, if it fails, view the log file to get more detailed information about why it's failing.
