### ISSUE TITLE
What is the recommended way to exclude a type 

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#870]
What is the recommended way to exclude a type from the documentation that has no (included) properties or methods ?
Is there an XPath filter that I can set ?

**Comment by EWSoftware** [comment]
The [API filter](http://ewsoftware.github.io/SHFB/html/7df16a60-f718-4b8f-bfa2-88c42906070c.htm) is edited through the project.  If you're trying to do it dynamically, then a plug-in would be needed.  The existing [XPath Reflection File Filter Plug-In](http://ewsoftware.github.io/SHFB/html/cd68ef02-3493-4af6-96de-1957b0aaf858.htm) should work.  My XPath is a bit rusty but something like this should work:

```
/reflection/apis/api[apidata/@group="type"]/elements[count(*) = 0]
```
