### ISSUE TITLE
SHE0002 when upgrade project from old version

### ISSUE THREAD

**Issue by scegg** [EWSoftware/SHFB#875]
Today, I upgrade shfb to latest version and try to open a project from older (the 2nd latest) saved and build it up to date.

I got an error in log:
Extracting HTML info for HTML Help 1 and/or website...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe - ExtractHtmlInfo.proj]
C:\VSProjects\RemoteAgency\docs\help.v2\Working\ExtractHtmlInfo.proj(37,3): error SHE0002: Unexpected error: System.NullReferenceException: Object reference not set to an instance of an object.
C:\VSProjects\RemoteAgency\docs\help.v2\Working\ExtractHtmlInfo.proj(37,3): error SHE0002:    at SandcastleBuilder.HtmlExtract.SandcastleHtmlExtract.WriteWebsiteTableOfContents()
C:\VSProjects\RemoteAgency\docs\help.v2\Working\ExtractHtmlInfo.proj(37,3): error SHE0002:    at SandcastleBuilder.HtmlExtract.SandcastleHtmlExtract.ExtractHtmlInfo()
    Last step completed in 00:00:00.4500

**Comment by scegg** [comment]
You can get the whole solution to repo this problem.

Pull from https://github.com/SecretNest/RemoteAgency/tree/v2
In VisualStudio solution explorer, build PublicRelease\NuGet.RemoteAgency.Abstraction, PublicRelease\NuGet.RemoteAgency and PublicRelease\NuGet.RemoteAgency.Neat. Then try to build PublicRelease\Sandcastle.

The problem is repo always.

**Comment by dos-ise** [comment]
We have the same problem.

`Extracting HTML info for HTML Help 1 and/or website...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe - ExtractHtmlInfo.proj]
C:\git\ets\bin\Falcon\Knx.Falcon.Sdk\Help\Working\ExtractHtmlInfo.proj(37,3): error SHE0002: Unexpected error: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
C:\git\ets\bin\Falcon\Knx.Falcon.Sdk\Help\Working\ExtractHtmlInfo.proj(37,3): error SHE0002:    bei SandcastleBuilder.HtmlExtract.SandcastleHtmlExtract.WriteHelp1xTableOfContents()
C:\git\ets\bin\Falcon\Knx.Falcon.Sdk\Help\Working\ExtractHtmlInfo.proj(37,3): error SHE0002:    bei SandcastleBuilder.HtmlExtract.SandcastleHtmlExtract.ExtractHtmlInfo()
    Last step completed in 00:00:01,0302
`

**Comment by dos-ise** [comment]
After looking at the code I think the problem is that in the WriteHelp1xTableOfContents method the key is null if no file is associated.

![topic_file_none](https://user-images.githubusercontent.com/20043350/139838949-a7d2e9d9-024a-4644-bd53-8773d53cd579.JPG)

![WriteHelp1xTableOfContents](https://user-images.githubusercontent.com/20043350/139838972-d04f7952-a66d-4bad-9ff4-9ea96c50efe5.JPG)

**Comment by KGuetter** [comment]
I can confirm. Any "empty container topic" in the ContentLayout.content file will produce the NullReferenceException.

**Comment by EWSoftware** [comment]
Yes, I've got it fixed.  I'll publish a release this weekend.

**Comment by EWSoftware** [comment]
The new release containing the fix is available (v2021.11.7.0).
