### ISSUE TITLE
Error BE0020: Unknown substitution tag ID: 'SHFBFolder'

### ISSUE THREAD

**Issue by RichardD2** [EWSoftware/SHFB#878]
SHFB v2021.11.17
VS2022 v17.0.0

Trying to build a documentation project created in VS2019 fails with the error in the title:

> CopyConceptualContent
> CreateConceptualTopicConfigs
> CopyAdditionalContent
> MergeTablesOfContents
> GenerateIntermediateTableOfContents
> CreateBuildAssemblerConfigs
> MergeCustomConfigs
> SHFB(0,0): Error BE0020: Unknown substitution tag ID: 'SHFBFolder'
> Failed

The error from the build log:

> SHFB: Error BE0020: Unknown substitution tag ID: &#39;SHFBFolder&#39;
>    at SandcastleBuilder.Utils.BuildEngine.SubstitutionTagReplacement.OnFieldMatch(Match match)
>    at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
>    at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
>    at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
>    at SandcastleBuilder.Utils.BuildEngine.SubstitutionTagReplacement.TransformText(String templateText, Object[] args)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.MergeConfigurations(XmlDocument config, Boolean isConceptualConfig)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.MergeComponentConfigurations()
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

The only reference to that tag in the project file is:

```
<colorizer 
    syntaxFile="{@SHFBFolder}PresentationStyles\Colorizer\highlight.xml" 
    styleFile="{@SHFBFolder}PresentationStyles\Colorizer\highlight.xsl" 
    stylesheet="{@SHFBFolder}PresentationStyles\Colorizer\highlight.css" 
    scriptFile="{@SHFBFolder}PresentationStyles\Colorizer\highlight.js" 
    disabled="{@DisableCodeBlockComponent}" 
    language="cs" 
    tabSize="0" 
    numberLines="false" 
    outlining="false" 
    keepSeeTags="false" 
    defaultTitle="true" 
/>
```

My guess would be that this is a 32/64-bit issue? Eg: [MSBuild and 64-bit Visual Studio 2022 - .NET Blog](https://devblogs.microsoft.com/dotnet/msbuild-and-64-bit-visual-studio-2022/)

Unfortunately, I don't know enough about MSBuild and SHFB to dig in any further to try to fix the error.

**Comment by RichardD2** [comment]
Removing and re-adding the code block plugin has changed the line in the project to:

```
<colorizer 
    syntaxFile="{@CoreComponentsFolder}Colorizer\highlight.xml" 
    styleFile="{@CoreComponentsFolder}Colorizer\highlight.xsl" 
    stylesheet="{@CoreComponentsFolder}Colorizer\highlight.css" 
    scriptFile="{@CoreComponentsFolder}Colorizer\highlight.js" 
    disabled="{@DisableCodeBlockComponent}" 
    language="cs" 
    tabSize="0" 
    numberLines="false" 
    outlining="false" 
    keepSeeTags="false" 
    defaultTitle="true" 
/>
```

But the build still fails with an error:

```
<buildStep step="BuildTopics">
Building help topics...
[C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe - BuildTopics.proj]
Build started 16/11/2021 14:43:12.
Project &quot;...\Help\Working\BuildTopics.proj&quot; on node 1 (default targets).
BuildTopics:
  Microsoft.Build (v17.0.0+c9eb9dd64e9a2e8a433900a1a626d65a2bce4428)
  &#169; Microsoft Corporation. All rights reserved.
  Loading configuration...
BuildAssembler : error :  [...\Help\Working\BuildTopics.proj]
BuildAssembler : error : ESentResolveReferenceLinksComponent: Could not load file or assembly &#39;BuildComponents.Targets, Version=2.7.3.0, Culture=neutral, PublicKeyToken=c8895f0c125eff20&#39; or one of its dependencies. The system cannot find the file specified. [...\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [...\Help\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Resolve Reference Links (ESENT Cache)&#39;. The error message is: See log for details [...\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [...\Help\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Multi-format Output Component&#39;. The error message is: See log for details [...\Help\Working\BuildTopics.proj]
BuildAssembler : error :  [...\Help\Working\BuildTopics.proj]
BuildAssembler : error : BuildAssemblerCore: An unexpected error occurred while attempting to create the build component &#39;Switch Component&#39;. The error message is: See log for details [...\Help\Working\BuildTopics.proj]
Done Building Project &quot;...\Help\Working\BuildTopics.proj&quot; (default targets) -- FAILED.
    Last step completed in 00:00:01.0668
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.RunProject(String projectFile, Boolean minimalOutput)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
```

**Comment by EWSoftware** [comment]
There were a number of breaking changes in the latest release.  See the [release notes](http://ewsoftware.github.io/SHFB/html/003c85ec-45ad-4123-a31d-fd63a695b1f3.htm) for details.  For most components, opening and saving the configuration will correct any issues.  For the data caching components, you'll need to clear the caches and let them get rebuilt.  However, they don't really provide that much benefit anymore so you may be better off just removing them and build without them.

**Comment by RichardD2** [comment]
Thanks for the quick reply. Removing the caching component let me build the project, although it took quite a while. I'm not sure whether that's the effect of no caching, a VS2022 issue, or the fact that the project it's documenting now targets .NET 5 and 6 as well as Standard 2.0 and 2.1. :)

**Comment by EWSoftware** [comment]
Without the database caches, it has to build the default caches so the initial build may take longer.  Most of that would be contacting the web service to get the URLs for the base framework member links.

**Comment by GH-07** [comment]
Hi,

I got a new PC and installed VS 2019 and the latest SHFB version.
[myLog.log](https://github.com/EWSoftware/SHFB/files/7827199/myLog.log)

Now I always get the error in my project:
Error BE0020: Unknown substitution tag ID: 'SHFBFolder'.

I have attached the log file

Thank You

**Comment by EWSoftware** [comment]
Check your Components tab in the SHFB project.  You've most likely got a copy of the Code Block Component in the project.  Open and save its configuration to get it to refresh the settings so that they are compatible with the latest release.  See the [release notes](http://ewsoftware.github.io/SHFB/html/003c85ec-45ad-4123-a31d-fd63a695b1f3.htm) for other potential issues due to breaking changes.

**Comment by 304NotModified** [comment]
I got this error and replaced

`{@SHFBFolder}PresentationStyles` with `{@CoreComponentsFolder}`
