### ISSUE TITLE
Error BE0071 with .NET Framework 3.5

### ISSUE THREAD

**Issue by athach** [EWSoftware/SHFB#879]
Hi,
I have shfbproj that builds fine with version 2019.11.17.0. With the latest version 2021.11.7.0 I get error BE0071 claiming .NET Framework 3.5 is not available. It is installed and the code builds fine but somehow SHFB does not find it.

**Comment by EWSoftware** [comment]
Some of the older framework data sets were removed from SHFB.  See the [release notes](http://ewsoftware.github.io/SHFB/html/70b704dc-03c8-4934-b83e-e84d4d7f927a.htm).  Just select one of the available versions for the Framework Version property.

**Comment by athach** [comment]
Thank you very much for the prompt reply. I failed to install the nuget packet in Visual Studio but unzipping the content to the SHFB installation directory solved the problem.
