### ISSUE TITLE
How to Link third-party documentation in Sandcastle C# documentation build

### ISSUE THREAD

**Issue by eirannejad** [EWSoftware/SHFB#882]
I'm building documentation for a plugin I have written, for a third-party application, that has its own API that I use in my plugin. The API is documented elsewhere (website) and I know how to generate urls for each of the API types.

During the docs build of my plugin, [SandCastle](https://github.com/EWSoftware/SHFB) naturally complains about the missing third-party API types since they are not defined in my plugin assembly and are part of the host application API assembly that I have referenced in my plugin project.

I'd like to know how I can configure SandCastle to resolve the missing types to the correct url and include that in the generated .chm or website files as hyperlinks.

SandCastle already does that for all dotnet types and routes them to MSDN documentation correctly. SandCastle seems to have built-in url resolvers for these known sources internally but I don't see any way of extending that, adding my own resolver.

**RE** [Same question on StackOverflow](https://stackoverflow.com/questions/70312291/how-to-link-third-party-documentation-in-sandcastle-c-sharp-documentation-build)

**Comment by EWSoftware** [comment]
There isn't currently a built-in way to generate links to third party documentation.  You can use the [Additional Reference Links plug-in](http://ewsoftware.github.io/SHFB/html/15b6b7be-3778-4487-b524-d558d02e6460.htm) to suppress the warnings if you find them bothersome.  To resolve the links and generate a valid URL, you can create your own [build component](http://ewsoftware.github.io/SHFB/html/e6d18448-2459-46f1-bbdc-a7db415f2bda.htm).  It would run before the standard Resolve Reference Links Component and would look for the same `referenceLink` elements that are within the API you are interested in and would take the API member IDs and translate them to a URL assuming there is a way to translate the ID to a URL.

**Comment by EWSoftware** [comment]
Yes, you'll search the topic XML for `referenceLink` elements and, based on the properties, generate HTML anchor elements to replace them.  You can see the way the [standard component does it for reference](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/BuildAssembler/BuildComponents/ResolveReferenceLinksComponent.cs#L232).  It's a lot more involved because it supports multiple formats and looking up the IDs for the base framework types but you can probably pull out the core processing (the loop, creating the `ReferenceLinkInfo` instance to get the properties, and then skip down to the part where it generates the anchor element to see how it replaces it).

**Comment by eirannejad** [comment]
Yeah your description was a great map for me to look into the build steps and try to figure out how it is done. I dumped the xml documents being passed to `Apply` method before and after the `XSL Transform` step and saw how the html is being generated. Then followed the same pattern as the standard component you linked about and got it figured out. The API that we are working on converts data between two different applications so now both input and output data types link to the third-party documentation correctly.


https://user-images.githubusercontent.com/8197916/146130263-b4e7d917-b9d5-4d72-8207-bebbf17d82e1.mov



I'm going to make this component generic and publish on nuget soon for others to use.

**Comment by eirannejad** [comment]
Closing this. But I'm going to make this component generic and publish on nuget soon for others to use.

**Comment by EWSoftware** [comment]
Let me know where it's at and I'll add a link to it in the SHFB docs.

**Comment by eirannejad** [comment]
@EWSoftware `0.1.0-beta` is [published to NuGet](https://www.nuget.org/packages/ResolveThirdPartyReferenceLinks/0.1.0-beta). Still needs cleanups and bug fixes but I thought I can get it published so I can use it in the CI build of my own project and also get your comments as well

- Repo is here (README is first draft and explains the overall how-it-works) 👉 https://github.com/mcneel/ResolveThirdPartyReferenceLinks
  There are two other URL providers that I thought of and want to add to this. The three of them should cover the majority of cases.

- This is how it is used on my project 👉 https://github.com/mcneel/rhino.inside-revit/blob/bb6c2a321c2c591f692575b92c287d96df3565e0/src/RhinoInside.Revit.Docs/RhinoInside.Revit.Docs.shfbproj#L32
