### ISSUE TITLE
Feature Request: Enhanced help document search

### ISSUE THREAD

**Issue by TwSoft** [EWSoftware/SHFB#883]
suggest：
SearchHelp.aspx

Chinese is often retrieved in two words

`checkWord.Length > 2 `  modify to  `checkWord.Length >= 2 ` 

Filtering supports Contains operations

`if(!wordDictionary.TryGetValue(word, out occurrences))` 
modify to
`occurrences = wordDictionary.Where(p => p.Key.Contains(word)).SelectMany(p => p.Value).ToList();`
`if (occurrences?.Count == 0)`

**Comment by EWSoftware** [comment]
Combined with #868
