### ISSUE TITLE
v2021.11.7.0 chocolatey package fails to install against vs 2022

### ISSUE THREAD

**Issue by JordanWConrad** [EWSoftware/SHFB#885]
Not sure if this is the correct place to report issues with the [chocolatey installer](https://community.chocolatey.org/packages/sandcastle), but figured it would be a good place to start.

Currently the latest choco installer for v2021.11.7.0 fails to install SHFB against VS 2022 and returns error code `2003`. The choco package successfully downloads both `VS2017AndLater.vsix` and `VS2022AndLater.vsix` but the only attempts to use the `2017.vsix` installer for all versions. Modifying the choco package locally and using the `2022.vsix` against the VS 2022 successfully installs the package.

Steps to replicate:
1) Download Visual Studio 2022 Enterprise
2) Install Chocolatey
3) Run `choco install sandcastle -v 2021.1.1.7.0`

![image](https://user-images.githubusercontent.com/47613718/150380887-943dd60a-aa58-4ea9-8c5f-9c61e21c1032.png)

**Comment by EWSoftware** [comment]
I did not create nor do I support the chocolatey installer.  The problem appears to be that it's trying to use the VS2017/2019 VSIX to install it on VS2022.  There's a separate VSIX for VS2022.  Run that and it will install in VS2022.  You can download the official [guided installer](https://github.com/EWSoftware/SHFB/releases/tag/v2021.11.7.0) which contains the current installers.

**Comment by JordanWConrad** [comment]
Appreciate the quick response on this. I'll close out this issue since it's not relevant per your comment.
