### ISSUE TITLE
Unable to use "Edit API Filter"

### ISSUE THREAD

**Issue by leet101** [EWSoftware/SHFB#888]
Hi, I have an issue with SHFB (tried in both v2021.11.7.0 and v2022.1.22.0)
The "Edit API Filter" can no longer be used and shows the following error:
![unnamed](https://user-images.githubusercontent.com/92138113/151251830-7c15a52f-18d1-46d5-9d61-a2b56ec22a70.png)

If I just build the documentation it works fine, there are a few warnings but these shouldn't stop the build working.
Here is the build log from when I build the documentation:
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/7945786/LastBuild.log)

Another thing I noticed is that I have 2 x .csproj in my documentation sources.
If I remove either one of them I am able to open "Edit API Filter"

Please let me know if you have any thoughts on what the issue could be, any help would be much appreciated.
Many thanks in advance.

**Comment by EWSoftware** [comment]
Can you send me the projects in question so that I can duplicate the problem?

**Comment by leet101** [comment]
No unfortunately I am not allowed to share the projects as they contain confidential information.

**Comment by EWSoftware** [comment]
I wouldn't need the code, just the assemblies to use as documentation sources and the SHFB project in order to duplicate the error.  If that's not possible, you can try looking in the temporary files folder when the message appears for the latest folder that contains a .\SHFBPartialBuild folder.  In it, you'll find the log for the partial build which may contain some more information about the cause of the error.

**Comment by leet101** [comment]
Hi Ed, thanks for the information.
I have attached the build log and a project file it was complaining about from the temporary folder.
Please could you have a quick look at this and see if you can advise what the issue is?
Many thanks
Lee

**Comment by EWSoftware** [comment]
It looks like a null reference exception is occurring while trying to merge duplicate reflection information.  It's odd as the only place it looks like it could occur, it should always have an ID to use for the key.  In that same folder, you should find a reflection.org file.  If you can attach that here too, I should be able to try and duplicate the issue using it.

**Comment by leet101** [comment]
Hi Eric
[reflection.org.txt](https://github.com/EWSoftware/SHFB/files/7974334/reflection.org.txt)
Thanks for your reply.
Please find the requested log file attached and let us know if you can identify the cause of the issue.
Many thanks in advance

**Comment by EWSoftware** [comment]
Using the test file I was able to find the issue.  It's an edge case that I didn't run into in any of my other test projects.  The duplicate member it finds is the very last one in the file so when it goes to read the next element, it's not on an element and fails.  I should have a fixed version out this weekend.

**Comment by EWSoftware** [comment]
A new release is available that should fix this issue (v2022.2.6.0).
