### ISSUE TITLE
Issues with custom plugin after upgrading SHFB to the newest Version.

### ISSUE THREAD

**Issue by jakubait** [EWSoftware/SHFB#89]
I developed a plug-in for SHFB, which I recently upgraded to the newest version of SHFB. The plug-in works all fine on my local machine. 

However, a customer of mine has been experiencing some problems with my plugin after upgrading SHFB. They manifest as follows:

1. After deploying my plugin to '%ProgramData%\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins' you can see it under "Plug-Ins" in the property window. However, after removing all plug-in files from that location, the plug-in dosen't disappaer and you can still see it on that list. I can't explain that behavior, but to me it seems, like it would be cached somehow. 
2. Opening a project and clicking on 'Plug-Ins' in the project property window would cause SHFB to hang for a while. It happens regerdless of plugin files being deployed or not. It would take some time to load the plug-in list.  The old version of SHFB was a lot faster. 

I'd like to point out, that these issues occur only on my customer's machine. He's got Windows 7 installed on it, while I've got Windows 8.1. Could it be the reason? 

The plug-in is supposed to run on a build server as part of a build process, but given the circumstances  it is unlikely at the moment. Anyone could help and give me a hint how to address this problem?

**Comment by EWSoftware** [comment]
The OS has no effect.  If you still see the plug-in listed in the left side list on the Plug-Ins property page after exiting and restarting the standalone GUI or Visual Studio, it's finding another copy of the plug-in elsewhere.  Check to make sure that a copy doesn't exist anywhere else under subfolders in the Components and Plug-Ins folder, the project folder itself or subfolders beneath it, and, if defined in the project, the component path or any of its subfolders.

**Comment by EWSoftware** [comment]
No further response so I'm closing this for now.  Re-open if it's still an issue.
