### ISSUE TITLE
VS 2022: "Target framework not supported" message when opening Help file project

### ISSUE THREAD

**Issue by WolfgangHG** [EWSoftware/SHFB#890]
I installed VS 2022 and latest Sandcastle on a virtual machine. VS by default installs only framework 4.8, but no older versions.

When opening the solution containing the Sandcastle project, there is a popup "Target framework not supported" (by Visual Studio?) which claims that the ".shfbproj" file target framework 4.0.
![image](https://user-images.githubusercontent.com/138049/151775223-046232a7-85a9-4a7e-97ae-a27afbec3c51.png)

When clicking "Update the target to 4.8", the project file is checked out, but not change is made. The message comes again the next time when opening the project.

Here is the full project file (it is an older project, converted to recent Sandcastle):
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="14.0">
  <PropertyGroup>
    <!-- The configuration and platform will be used to determine which
         assemblies to include from solution and project documentation
         sources -->
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>2c3fbcd4-c2c4-4168-a3f0-0691496bd044</ProjectGuid>
    <SHFBSchemaVersion>2017.9.26.0</SHFBSchemaVersion>
    <!-- AssemblyName, Name, and RootNamespace are not used by SHFB but Visual
         Studio adds them anyway -->
    <AssemblyName>ToolsDoc</AssemblyName>
    <RootNamespace>ToolsDoc</RootNamespace>
    <Name>ToolsDataDoc</Name>
    <!-- SHFB properties -->
    <FrameworkVersion>.NET Framework 4.8</FrameworkVersion>
    <OutputPath>.\Help\</OutputPath>
    <HtmlHelpName>ToolsDataDoc</HtmlHelpName>
    <Language>en-US</Language>
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
    <DocumentationSources>
      ...
    </DocumentationSources>
    <BuildAssemblerVerbosity>OnlyWarningsAndErrors</BuildAssemblerVerbosity>
    <HelpFileFormat>HtmlHelp1</HelpFileFormat>
    <IndentHtml>False</IndentHtml>
    <KeepLogFile>True</KeepLogFile>
    <DisableCodeBlockComponent>False</DisableCodeBlockComponent>
    <CppCommentsFixup>False</CppCommentsFixup>
    <CleanIntermediates>True</CleanIntermediates>
    <SyntaxFilters>C#, Visual Basic</SyntaxFilters>
    <SdkLinkTarget>Blank</SdkLinkTarget>
    <RootNamespaceContainer>False</RootNamespaceContainer>
    <PresentationStyle>VS2013</PresentationStyle>
    <Preliminary>False</Preliminary>
    <NamingMethod>Guid</NamingMethod>
    <HelpTitle>...clipped...</HelpTitle>
    <ContentPlacement>AboveNamespaces</ContentPlacement>
    <WebsiteSdkLinkType>Msdn</WebsiteSdkLinkType>
    <HtmlSdkLinkType>Msdn</HtmlSdkLinkType>
    <IncludeFavorites>True</IncludeFavorites>
    <BinaryTOC>True</BinaryTOC>
    <ApiFilter />
    <ComponentConfigurations />
    <HelpAttributes />
    <NamespaceSummaries />
    <PlugInConfigurations />
    <BuildLogFile />
    <HtmlHelp1xCompilerPath />
    <HtmlHelp2xCompilerPath />
    <WorkingPath />
    <ComponentPath />
    <MaximumGroupParts>2</MaximumGroupParts>
    <NamespaceGrouping>False</NamespaceGrouping>
    <HelpFileVersion>9.13.0.0</HelpFileVersion>
    <SaveComponentCacheCapacity>100</SaveComponentCacheCapacity>
  </PropertyGroup>
  <!-- There are no properties for these groups.  AnyCPU needs to appear in
       order for Visual Studio to perform the build.  The others are optional
       common platform types that may appear. -->
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|Win32' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Win32' ">
  </PropertyGroup>
  <!-- Import the SHFB build targets -->
  <Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" />
</Project>

```

**Comment by WolfgangHG** [comment]
Sorry, this does not help. And the error also shows when I create a blank project from the template "Sandcastle Help File Builder Project".

Here is a screenshot of the targeting packs available in my VS installer:
![image](https://user-images.githubusercontent.com/138049/151929727-d8585a2d-629b-4cb2-962b-584e4f1e4ecf.png)
No "4.0" in the list.

When selecting the option "Download .NET framework 4.0. targeting pack" in the dialog, I am redirected to [https://dotnet.microsoft.com/en-us/download/visual-studio-sdks](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks), which is just the download page for the framework itself.

**Comment by EWSoftware** [comment]
I'm not sure why it would do that.  You can try adding the following property in the first property group with the AssemblyName and RootNamespace properties:

```
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
```

It's not needed by SHFB but that should tell Visual Studio the project is using .NET 4.8 and may work around the issue.

What OS version do you have in the VM?  I can try creating one similar to see if I can reproduce the issue.

**Comment by WolfgangHG** [comment]
I can confirm that it works with the "TargetFramework" line.

The VM has Win 10x64 21H1.
I migrated my machine to VS2022 (and deinstalled VS2019 before), and here it happens, too. My machine has Win10x64 21H2.

Here are some screenshots about installed components (german installer):
![vs2022_install1](https://user-images.githubusercontent.com/138049/152109049-668938b7-f68f-481b-84b7-2854c4f89489.png)
![vs2022_install2](https://user-images.githubusercontent.com/138049/152109052-4c6ce7d6-fba1-48cd-b90d-9e972a2f8e2b.png)

Targeting pack für .NET framework 4.6.1:
![vs2022_targeting461](https://user-images.githubusercontent.com/138049/152109121-ec87b4d6-d284-4680-92ae-8fb0fec34182.png)

I also installed the offline helpviewer:
![vs2022_install_helpviewer](https://user-images.githubusercontent.com/138049/152109196-c74aa3c9-58f0-42bd-b026-1ff3837313b0.png)

And the "C++ MFC" (group "SDKs, libraries, frameworks"):
![visual_studio_2022_mfc](https://user-images.githubusercontent.com/138049/152109278-5e25974c-9ae7-492e-a264-d5ac24278836.png)

Do you need also a list of additional extensions?

**Comment by EWSoftware** [comment]
That should be sufficient.  I have VS 2017 and 2019 installed as well and they have the 4.0 targeting pack which is probably why I haven't seen the issue.

**Comment by dmcgloin** [comment]
Hello! Experiencing this same problem described above. Fresh Windows installation, with VS 2022 only and latest SHFB. Will try suggested fix ups above.

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎1/‎28/‎2022
OS build	19042.1503
Experience	Windows Feature Experience Pack 120.2212.4170.0

--

Microsoft Visual Studio Enterprise 2022
Version 17.0.5
VisualStudio.17.Release/17.0.5+32112.339
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA919
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.0.795.42246
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.795.42246
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.795.42246
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.4000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.0.795.42246
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.4000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Hive Query Language Service   2.6.4000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.4000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   6.0.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
Provides languages services for ASP.NET Core Razor.

Sandcastle Help File Builder   SHFB
Visual Studio integration for the Sandcastle Help File Builder.
https://GitHub.com/EWSoftware/SHFB

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by dmcgloin** [comment]
Added:

`<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>`

..as prescribed above. This appears to work. Alert goes away after re-opening project in VS 2022. Help file still builds. I can visualize the project settings inside VS 2022.

Will post back if I see anything else.

Thanks VERY MUCH for such a great tool!

**Comment by EWSoftware** [comment]
`FrameworkVersion` is a SHFB project that tells it what reflection data set to use for the documentation sources.  It's unrelated to the other MSBuild property.

**Comment by legistek** [comment]
Oh gotcha. Well, I wish I could tell you why it was still happening for me, but the manual fix still works at least.

**Comment by XomegaNet** [comment]
FYI, we ran into the same problem with our own modeling project type in our [Xomega.Net](https://xomega.net) for VS2022 extension and setting the `TargetFrameworkVersion` MSBuild property to 4.8 did not help.

We finally tracked it down to the `ProjectNode.DefaultTargetFrameworkMoniker` of the MPFProj being set to version 4.0. Changing it to 4.8 fixed the issue for us.

You may find this helpful if you'd also like to fix it in the SHFB for all the other users that may encounter this issue in the future.

**Comment by EWSoftware** [comment]
@XomegaNet  I couldn't get a case where it would return `DefaultTargetFrameworkMoniker`.  There always appeared to be options with the value set the 4.0 though I do have the targeting pack installed so maybe that's why.  I've updated it to 4.8 anyway in case it does have an effect when it's not installed.  Worst case, adding the explicit `TargetFrameworkVersion` property to the SHFB project will still work around it.
