### ISSUE TITLE
"Applies to" section

### ISSUE THREAD

**Issue by maxtoroq** [EWSoftware/SHFB#892]
I think it would be useful to have a standard and structured way to document the version or versions a topic applies to, e.g. "This method is available in v6.3 and higher".

**Comment by EWSoftware** [comment]
This can be done to a certain extent with the [version builder plug-in](http://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm).  It uses the information from prior versions of the assemblies to generate a Version Information section in the API topics.
