### ISSUE TITLE
BE0073 Error after updating Tools package

### ISSUE THREAD

**Issue by sgdowney** [EWSoftware/SHFB#893]
Hello,
I'm building on an on prem Azure DevOps 2020 server.  The library project targets .NETStandard 2.0.  I have configured the Help project to be .NETStandard/.NET Core 3.1.  I have the following packages:
EWSoftware.SHFB 2020.3.6
EWSoftware.SHFB.NETFramework 4.8.0.2.
The project builds successfully on the ADO server with this configuration.

When I attempt to update the tools package to any version above 2020.3.6, I get the following error:

SHFB : error BE0073: A project with a different or higher framework version was found but that version or a suitable redirected version was not found on this system.  The build cannot continue.  Project framework versions: .NETStandard 2.0 [D:\Agent\5\_work\130\s\GoC.Components.Database\WikiDocumentation\WikiBuild.proj]
What should I be looking for to identify the cause of this error.

**Comment by sgdowney** [comment]
Does the generated GenerateRefInfo-<guid>.proj file always contain the entries
```
    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
```
That may be why newer versions of the build package breaks the build.  The build agents don't have that dev pack.
I also updated my Sandcastle GUI install and now the help project won't build locally in the GUI nor in VS2019.

**Comment by EWSoftware** [comment]
If you're targeting .NET Standard 2.0, try changing the project's Framework Version to ".NET Core/.NET Standard/.NET 5.0+" and use the EWSoftware.SHFB.NET.5.0.0.1 NuGet package for the reflection data and the latest EWSoftware.SHFB package.  The same would apply when building locally with the full toolset installed (also using the latest release).

**Comment by EWSoftware** [comment]
The build log shows a successful build.  I notice you are using the E-Sent caching components.  You might try removing them.  They typically aren't needed anyway.

**Comment by sgdowney** [comment]
Removing the E-Sent caching components resolved the build issues.  I will now update the other documentation projects.
