### ISSUE TITLE
Clicked 'Install SHFB' and nothing happens

### ISSUE THREAD

**Issue by PHuhn** [EWSoftware/SHFB#895]
# Sandcastle Environment #

Sandcastle Guided Installation (v2022.2.6.0)

# Problem Description #

On the **Sandcastle Help File Builder and Tools** tab.

Clicked **Install SHFB** button, then the *Installing. Please wait...* appears.  Nothing happens. Waited 4 hours and still displaying the message.

# Windows Environment #

Running Microsoft Windows [Version 10.0.19043.1466]

# Visual Studio Environment #
Microsoft Visual Studio Community 2022
Version 17.0.3
VisualStudio.17.Release/17.0.3+32002.185
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.795.42246
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.795.42246
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.795.42246
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.795.42246
Azure Functions and Web Jobs Tools

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.21293.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   6.0.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python - Django support   17.0.21293.2
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.21293.2
Profiling support for Python projects.

Python with Pylance   17.0.21293.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by EWSoftware** [comment]
It sounds like the installer perhaps didn't run or was blocked.  You can run them manually from the .\InstallResources folder.

**Comment by PHuhn** [comment]
I tried it an found that that the builder installer needs to be unblocked also.  That is both SandcastleInstaller in root folder and the SandcastleHelpFileBuilder in the InstallResources folder need to be unblocked.
Phil==============  Phil Huhn(734) 545-5845============== 

    On Friday, February 11, 2022, 12:18:53 PM EST, Eric Woodruff ***@***.***> wrote:  
 
 


It sounds like the installer perhaps didn't run or was blocked. You can run them manually from the .\InstallResources folder.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EWSoftware** [comment]
Usually if you unblock the .zip file before extracting it, that takes care of it.
