### ISSUE TITLE
Building on CI server

### ISSUE THREAD

**Issue by kfertitta** [EWSoftware/SHFB#900]
I'm still having a bit of trouble getting my project to build on a CI server without the tools installed and using just the NuGet packages.  My `packages.config` looks like this:

```
<packages>
  <package id="EWSoftware.SHFB" version="2021.10.23" />
  <package id="EWSoftware.SHFB.NETFramework" version="4.7.0" />
```

And the `FrameworkVersion` is set as per the previous error in my build, like so:

```
  <PropertyGroup>
    <FrameworkVersion>.NET Framework 4.7</FrameworkVersion>
  </PropertyGroup>
```

Additionally, I've set the `SHFBComponentPath` item to several different values, like this:
```
  <ItemGroup>
    <SHFBComponentPath Include="..\..\Packages\" />
    <SHFBComponentPath Include="..\..\Packages\EWSoftware.SHFB.NETFramework.4.7\" />
    <SHFBComponentPath Include="..\..\Packages\EWSoftware.SHFB.NETFramework.4.7\tools\" />
    <SHFBComponentPath Include="..\..\Packages\EWSoftware.SHFB.NETFramework.4.7\tools\data\" />
    <SHFBComponentPath Include="..\..\Packages\EWSoftware.SHFB.NETFramework.4.7\tools\data\.NETFramework\" />
  </ItemGroup>
```

Yet, I still get the following error in the log file:

```
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe - GenerateRefInfo-b48c5948-fe44-48c8-8aad-f3b7acd68f22.proj]
Build started 3/4/2022 7:36:42 AM.
Project &quot;D:\Repos\MindWorks\NimbusDocs\build\Debug\core\Working\GenerateRefInfo-b48c5948-fe44-48c8-8aad-f3b7acd68f22.proj&quot; on node 1 (default targets).
PrepareForBuild:
  Creating directory &quot;obj\Debug\&quot;.
GenerateRefInfo:
  Microsoft.Build (v16.11.1+3e40a09f830fce5bb34916a4d20255c0876c9b5d)
  c Microsoft Corporation. All rights reserved.
MRefBuilder : error : An unexpected error occurred trying to execute the MRefBuilder MSBuild task: System.InvalidOperationException: Unable to locate information for the framework version &#39;.NETFramework 4.7&#39; or a suitable redirected version on this system 
```

**Comment by EWSoftware** [comment]
There were some issues with the initial packages that used the SHFBComponentPath item and older packages don't contain the item at all.  Use the latest release of the SHFB package and also the latest release of the reflection data set package regardless of what version the framework the project is actually built against as it contains options for the prior versions.  For .NET Framework reflection data, the package version is 4.8.0.2.  The latest SHFB package version is 2022.2.6.

With the latest release you don't need the packages.config file as package references are supported natively in the SHFB project.  The latest reflection data packages also define their own SHFBComponentPath item as well so they are not necessary.  There are certain required elements to enable the package references.  If you add the package references through the SHFB project it should update the project with them automatically.  You can see the elements needed in the [project template](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderUtils/Resources/ProjectTemplate.txt):

- The import at the top to import Microsoft.Common.props.
- The import at the end to import Microsoft.Common.targets just before the SandcastleHelpFileBuilder.targets file.
- Note the condition attribute on all three imports which are required for them to work properly.

**Comment by kfertitta** [comment]
Thanks much @EWSoftware .  My instinct was to update the SDK-style and update to the latest, but needed to see if I could just get by for another build without it.  I'll sit down and migrate it over and let you know if there are probs.

Thanks again.

**Comment by kfertitta** [comment]
Hi @EWSoftware.  Got it working now with the updates you suggested.  Expected to have to go to SDK-style project system, but I can see you got `PackageReference` working without that.  I think I'm in a good place now.  Thanks again for your help.
