### ISSUE TITLE
Possibility to convert error to warning 

### ISSUE THREAD

**Issue by BlackyTheDruide** [EWSoftware/SHFB#904]
Hi,

we use in our build pipeline some custom tasks which are creating shfbproj files based on the given workspace. Some projects are marked fully internal so the following error occurs when we try to build the created sandcastle projects:

**Error BE0033: No APIs found to document.  See error topic in help file for details.**

In our use case we would like to suppress this error and the build step for sandcastle should be succeeded.

Is there any possibility in sandcastle to suppress errors?

**Comment by BlackyTheDruide** [comment]
Thank you for the fast response. 

The problem is that we can not filter all projects which are internal before the sandcastle build step. We have a complete dynamic setup to create the shbproj files. Back in the versions of 2017 sandcastle did not throw an error when no documentation was found it was just a warning. 

We use sandcastle to build the documentation for around 150 projects. Even if we setup the project files to show internal classes (which are not allowed from our architects) we need to hide this in the end result.

**Comment by EWSoftware** [comment]
It's always been an error.  Perhaps it was not triggered in all cases in the older prior releases but is now.  As noted, even if it could get past it, it would fail later on anyway.

A workaround I found is to use a custom *SandcastleHelpFileBuilder.targets* file.  Make a copy of the standard one and, in your SHFB project files, change the import for the standard targets file to point to your custom version.  In your custom version, replace the references to `$(MSBuildThisFileDirectory)` with `$(SHFBROOT)` or a hard-coded path to the tools folder.  On the `SandcastleBuilder.MSBuild.BuildHelp` element in the custom targets file, add the attribute `ContinueOnError="WarnAndContinue"` which tells MBuild to ignore errors from the task and just report them as warnings.

``` XML
<SandcastleBuilder.MSBuild.BuildHelp
	ProjectFile="$(MSBuildProjectFullPath)"
	Configuration="$(Configuration)"
	Platform="$(Platform)"
	Properties="$(SubstitutionTags)"
	OutDir="$(OutDir)"
	Verbose="$(Verbose)"
	DumpLogOnFailure="$(DumpLogOnFailure)"
	AlwaysLoadProject="$(AlwaysLoadProject)"
	ContinueOnError="WarnAndContinue">
```

When you do that, it gets reported as a warning but completes the build.  If you add `/NoWarn:BE0033;MSB4181` to the MSBuild command line, it will suppress the error completely along with the additional MSBuild warning that the task didn't report the failure and it looks like a normal successful build with no issues.

**Comment by BlackyTheDruide** [comment]
Thank you again for the provide information. For now we use the override of the sandcastle build step and setup the option "ContinueOnError="WarnAndContinue" to avoid all the failing builds.

**Comment by legistek** [comment]
This is an issue for me too. I would like to use this only for conceptual topics without actually documenting APIs. So I'm not really sure why you'd say "Without an API to document, there's no help file to produce" because there's no reason we can't just have conceptual topics- much like [your own Help](https://ewsoftware.github.io/SHFB/html/bd1ddb51-1c4f-434f-bb1a-ce2135d3a909.htm). 

Perhaps I should be approaching this differently?

**Comment by EWSoftware** [comment]
@legistek Use the [Additional Content Only plug-in](http://ewsoftware.github.io/SHFB/html/2d483967-30cb-421c-81ff-fdba705e1e6b.htm) to build help consisting only of conceptual content.  The original case related to documenting assemblies with no public API so it didn't apply in that case.

**Comment by legistek** [comment]
Oh marvelous thank you! Wonderful tool you have here btw.
