### ISSUE TITLE
How to change the JQuery version

### ISSUE THREAD

**Issue by Xepher462** [EWSoftware/SHFB#905]
Hi all,
I am inquiring about the ability to change the JQuery version when the project builds.  I am building a SFHB web site and all currently work except I cannot find a way to change the search.html JQuery version.

I did find the in the 'BuildAssembler.config' two places where jquery-3.5.1.min.js was defined and that changed all the generated HTML files but the search.html still have the 3.5.1 in the <header><script type="text/javascript" src="scripts/jquery-3.5.1.min.js"></script></header> tag.

My question, is it possible to change this and have it built with a different version?

Thank you.

**Comment by EWSoftware** [comment]
You'll find those supporting files in the VS2013\Web and VS2013\Web\html folders.  You can replace those files using [stock content replacement](http://ewsoftware.github.io/SHFB/html/77d2d693-db84-4ae3-a84c-e33c71f92e9a.htm).  The files in VS2013\Web can be placed in the root of the project and the files in VS2013\Web\html in a html\ subfolder in the project.  They'll replace the default files when you build the project.

**Comment by Xepher462** [comment]
Perfect!  Thank you.
