### ISSUE TITLE
[Silent Install SHFB]

### ISSUE THREAD

**Issue by mbelhaouz** [EWSoftware/SHFB#907]
Is it possible to install SHFB in a VM using only command line or bash ?

Thanks

**Comment by EWSoftware** [comment]
You can run the installers manually.  They're in the .\InstallResources folder.  The MSI installer has a /quiet option.  The VSIX installer does too but you'll need to locate and run VSIXInstaller.exe to use it.

**Comment by mbelhaouz** [comment]
what do you suggest for the easiest and most stable use, install in cmd the MSI with quiet option or the  VSIX. The idea is that i'm trying to nstall the software on my agent cloud ( on AzureDevOps ) using CMD.

**Comment by EWSoftware** [comment]
The VSIX is only needed for Visual Studio.  Assuming the cloud agent is for builds only, all you'd need is the MSI.  However, SHFB projects support and have [NuGet packages](http://ewsoftware.github.io/SHFB/html/50ad2c8c-5004-4b4c-a77f-97b8c403c9f2.htm) for the tools and reflection file data so you wouldn't even need to install the tools if using the NuGet packages.  That is likely the best option.
