### ISSUE TITLE
PackageReferenceResolver always picks first "targets" child from assets

### ISSUE THREAD

**Issue by ghemberg** [EWSoftware/SHFB#908]
DocumentationSource is a project with the following tags in csproj:

`<TargetFramework>netstandard2.0</TargetFramework>
<TargetFrameworks>net451;net452;net46;net461;net462;net47;net471;net472;net48;netstandard2.0</TargetFrameworks>`

That project has a PackageReference to a NuGet package that exists for the same TargetFrameworks.

SHFB project contains this:

`<FrameworkVersion>.NET Core/.NET Standard/.NET 5.0+</FrameworkVersion>`

It appears SHFB always picks the PackageReference's XML file from the first target (in this case net451) instead of the one from the chosen target (in this case, "netstandard2.0").

In my case, the PackageReference for netstandard2.0 contains components not available in the .NET framework flavors. This results in unresolved references when building the SHFB project.

Tried adding "netstandard2.0" to the documentation source's "Target Framework" in the SHFB project, but that made no difference.

Using SHFB 2022.2.6.0 and Visual Studio Enterprise 2019.

I looked at the source code, and I believe the problem is caused by the [this line](https://github.com/EWSoftware/SHFB/blob/9ea7e584034aca8620532fa45946635a428159ca/SHFB/Source/SandcastleBuilderUtils/MSBuild/PackageReferenceResolver.cs#L150) . Seems to me like the appropriate "targets" child should be chosen for the selected TargetFramework?

**Comment by ghemberg** [comment]
After some further investigation on my part, it turns out specifying both `TargetFramework` and `TargetFrameworks` in a single csproj is probably not the best idea. I removed the `TargetFramework` tag and changed the order of `TargetFrameworks` as follows:

`<TargetFrameworks>netstandard2.0;net48;net472;net471;net47;net462;net461;net46;net452;net451</TargetFrameworks>`

This hasn't, however, resolved the issue: SHFB still does not find/use the netstandard2.0 version of the NuGet dependency. The documentation XML of the NuGet dependency in the SHFB temp folder is still one of the net4?? flavours and I get warnings like the following for every reference to an item in the NuGet dependency:

`1>C:\Program Files (x86)\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(44,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [Methods.T:MyDocumentationSource.UserWebserviceClient] Unknown reference link target 'T:MyNuGetDependency.SomeReferencedItem'. [C:\$HFB.TMP\BuildTopics.proj]`

The order in project.assets.json of the project that serves as documentation source is stil net451 > net452 > net46 > net461 > net462 > net47 > net471 > net472 > net48 > netstandard2.0.

Specifying `targetFramework="netstandard2.0"` on the documentation source in the SHFB project makes no difference.

Specifying `targetFramework="netstandard20"` causes SHFB to look for the documentation source (the csproj) in bin\$(Configuration)\MyDocumentationSource.dll i/o bin\$(Configuration)\netstandard2.0\MyDocumentationSource.dll. This results in a build error (as the DLL does not exist in that folder).

Problem still persists: how do I get SHFB to look for the netstandard2.0 version of the NuGet dependency.

**Comment by ghemberg** [comment]
I realize my rambling gets quite confusing, so I created a test solution to showcase the issue: [SHFBPackageReferenceWrongTargetFrameworkDemo.zip](https://github.com/EWSoftware/SHFB/files/8639547/SHFBPackageReferenceWrongTargetFrameworkDemo.zip).

Steps to reproduce:

1. Build project `MyNuGetDependency` to produce a NuGet package (and then make it available to in a package source; I copied it to a local source).
2. Build project `MyDocumentationSource`.
3. Build `MyDocumentSourceHelp`.

Notice the warnings in the build output:
`C:\Program Files (x86)\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(44,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [T:MyNamespace.UserWebserviceClient] Unknown reference link target 'T:MyNamespace.SomeReferencedItem'. [D:\SHFBPackageReferenceWrongTargetFrameworkDemo\MyDocumentSourceHelp\Help\Working\BuildTopics.proj]`
`C:\Program Files (x86)\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(44,3): warning : BuildAssembler : warning : ResolveReferenceLinksComponent: [P:MyNamespace.UserWebserviceClient.SomeProperty] Unknown reference link target 'T:MyNamespace.SomeOtherReferencedItem'. [D:\SHFBPackageReferenceWrongTargetFrameworkDemo\MyDocumentSourceHelp\Help\Working\BuildTopics.proj]`

Hope this clarifies things somewhat..

**Comment by Zastai** [comment]
You're always going to get warnings about references to types in an undocumented (as far as SHFB knows) assembly.
They will only go away if you also have a relevant documentation source for it. (It's not your code, so SHFB shouldn't include it in your docs, but without a .shfbproj or something to go on, it can't guess how to link to the type's docs from your api docs. So it issues a warning, and doesn't generate hyperlinks for the referenced types.)

Which assembly it picks is _mostly_ irrelevant; SHFB does seem have an implicit assumption that all targets of a project have the same API surface, which is not always true. Of course, if the type you reference exists _only_ in the `netstandard2.0` target, then SHFB might still complain even if you tell it how to find the referenced project's docs, if it bases itself on the `net451` build.

(Side note: why so many targets? You don't need to target `net48`, `net472`, `net471`, `net47` and `net462` explicitly unless you conditionally use APIs introduced specifically in those versions. If you don't, they're all covered by `netstandard2.0`. If you have no conditional compilation at all, just `net451` and `netstandard2.0` will suffice to support almost any target. Also, .NET Framework versions before 4.6.2 are out of support, so it may not make sense to still support them at all.)

**Comment by EWSoftware** [comment]
There may still be an issue with it making an assumption about the the first target being the most appropriate to use from the package.  I haven't had a chance to investigate that yet.  Support for multiple platforms does need improvement and I have plans to address that but I'm working on finishing up changes to the presentation style API first.

**Comment by ghemberg** [comment]
> You're always going to get warnings about references to types in an undocumented (as far as SHFB knows) assembly.

I see your point, I think.
The referenced assembly does come with its own XML documentation (in the NuGet package).
I'll check whether there is a way to add a documentation source for a referenced NuGet package (I thought I checked that and it didn't work if I rember correctly; will check again).

That said, even adding a documentation source to the referenced assembly and its XML doesn't solve it (it still loads the XML from the net451 flavour of the referenced assembly).

> Which assembly it picks is mostly irrelevant

I'm guessing I'm running into the exceptional cases here: netstandard2.0 flavour contains classes that don't exist in the net451 assembly.

> why so many targets?

I would drop unnecessary TargetFrameworks only after testing/verifying everything still works for all dependent projects (not all of which are under my control). This takes time, which my employer does not want me to spend on this.

> I have plans to address that but I'm working on finishing up changes to the presentation style API first.

Perfectly understandable: priorities. Thank you for your time!

**Comment by Zastai** [comment]
I was not suggesting to add the dependency's IntelliSense xml as doc source. That would cause its contents to be documented as part of your docs, which is rarely what you want.

What _should_ be possible is to create a (dummy) .shfbproj for the DLL, and add that as a documentation source in your project. That then treats it as "external" documentation. Note that I have not yet tried to do that myself; I just accept that if I have a public API involving an external type, that type does not get linked to its documentation from mine.

**Comment by ghemberg** [comment]
> I was not suggesting to add the dependency's IntelliSense xml as doc source. That would cause its contents to be documented as part of your docs, which is rarely what you want.

I am producing a help-file (CHM) and there is no website with the compiled help for either my project nor the referenced NuGet package. I didn't check, but I don't really see how I could have links to documentation for the referenced NuGet package, without including it in my project's CHM help file. Hence, I am choosing to include the help for the referenced NuGet package in the help-file for my project. 

That said, I understand this is a special case...

> The Additional Reference Links Plug-In is used to do that. It lets you suppress the reference link warnings for such dependencies.

I'm looking for a way to include the help for the referenced NuGet package in my project's help file. I now understand that requires me to add the NuGet package's DLL+XML as documentation sources and that means I'll need to reference these from the package folder because the DLL+XML aren't present in the build folder for netstandard2.0...

That said, I believe there is still a problem with SHFB using the wrong build of the referenced NuGet package for people who don't want to document dependencies in their help (it just doesn't affect my use-case).

**Comment by ghemberg** [comment]
> You could try adding the `CopyLocalLockFileAssemblies` property to your project ([docs](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#copylocallockfileassemblies)).

That's very useful in my case: thanks!
