### ISSUE TITLE
HTML files not correctly linking to multiple assemblies

### ISSUE THREAD

**Issue by sandyllama** [EWSoftware/SHFB#909]
I am attempting to generate HTML pages through the standalone SHFB GUI.

I'm having an issue where SHFB seemingly only has links to the first assembly when accessing the pages from the generated Index.html page. I know that the rest of my assemblies are outputting HTML files as well (I can see the files in the output dir), but those web pages are not visible when I open the Index.html in my browser.

When generating the CHM file, the output seems perfect; all of my assemblies are available and cross-link as expected. 
Same thing for when I view the webpages through the local web dev server.

Sorry if this is addressed in the FAQ. I've been digging through the docs for a while to no avail.

**Comment by EWSoftware** [comment]
Be sure you're opening website output using the Local Web Dev Server option and not directly from the file system.  If opened from the file system, the browser will block all script from running for security reasons.

**Comment by sandyllama** [comment]
Okay, I see. Thanks.
