### ISSUE TITLE
How to filter types with no members

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#911]
Hi,
We are using SHFB to produce documentation for the runtime classes for our language X#.
We use the XPath filter to filter out certain compiler generated classes from the output.
I am now looking for a syntax to filter out classes that contain no members.
I have struggled with all kind of XPath syntaxes and gave up in the end.
The classname ends with .Functions.

I tried 
`//api[contains(@id,'.Functions') and  contains(@id,"T:") and count(elements/element)= 0]`

I am trying to filter out items like this:

```
<api id="T:VOSystemClasses.Functions">
      <topicdata group="api" />
      <apidata name="Functions" group="type" subgroup="class" />
      <typedata visibility="public" abstract="true" sealed="true" serializable="false" />
      <family>
        <ancestors>
          <type api="T:System.Object" ref="true" />
        </ancestors>
      </family>
      <elements />
      <containers>
        <library assembly="VOSystemClasses" module="VOSystemClasses" kind="DynamicallyLinkedLibrary">
          <assemblydata version="2.12 GA" />
        </library>
        <namespace api="N:VOSystemClasses" />
      </containers>
      <file name="T_VOSystemClasses_Functions" />
    </api>
```

If I remove the count(..) part then the class is removed, but also other classes that DO have elements.

Can you help me with that ?

**Comment by EWSoftware** [comment]
It appears that the path needs to be fully qualified:

```
/reflection/apis/api[starts-with(@id, "T:") and contains(@id, ".Functions") and count(elements/element) = 0]
```

I was able to get that to work in a test case.  However, the other issue you will run into is that for each of the type nodes removed, you'll also need to remove the matching `element` element in the corresponding namespace API node.  I couldn't find a way to do that.  The best bet in this case is probably to create a plug-in that finds the types to remove using the above query and tracks those type name IDs.  It can then run through the set and remove the `element` entries from the related namespace API member nodes.

If it's an option and your compiler can mark the compiler generated types with the `CompilerGeneratedAttribute`, they'd be filtered out automatically.

**Comment by RobertvanderHulst** [comment]
Thanks, and you are right. This will leave the reference in the namespace.
I'll change my approach and will hard code the classes that need to be suppressed in an API Filter.
