### ISSUE TITLE
SHFB: Error BE0065: BUILD FAILED: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ElektroStudios** [EWSoftware/SHFB#917]
## Environment
 - I'm on Windows 10 x64
 - Using SHFB 2022.2.6.0
 - Documentation source: 
    - A dll library file (and its xml documentation file) written in VB.NET, targeting .NET 4.8, AnyCPU, Release.
    - All referenced assemblies were set to '**copy local = true**' to try avoid missing reference issues with SHFB.
    - No project references.
 - The library file was built on Visual Studio 2019 Professional.
 - I have installed Visual Studio 2022 Professional too in my machine. The solution file was not upgraded.
 - I have installed Visual Studio Build Tools 2019 and 2022

Please let me know if I missed any relevant info.

## Issue Description

I'm getting this error when trying to build the help file for my dll library file:

``` 
SHFB: Error BE0065: BUILD FAILED: Object reference not set to an instance of an object. 
``` 
```js
in Sandcastle.Core.Reflection.ApiMember..ctor(XElement apiMember);
in Sandcastle.Core.PresentationStyle.StandardDocumentModel.ApplyDocumentModel(String reflectionDataFile, String docModelReflectionDataFile);
in SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build();
```

I've tried to use the .vbproj file as documentation source as suggested in: https://github.com/EWSoftware/SHFB/issues/380#issuecomment-269664546 - but It throws the same error.

## Full log content 

(note that the stack trace and MSBuild messages are in Spanish, not sure if I can change the language in SHFB settings)

```xml
<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2022.2.6.0" projectFile="C:\Users\Administrador\Desktop\DevCase.shfbproj" started="29/06/2022 14:49:26">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\Program Files (x86)\Sandcastle Help File Builder&#39;
Found HTML Help 1 compiler in &#39;C:\Program Files (x86)\HTML Help Workshop\&#39;
Locating components in the following folder(s):
    C:\Users\Administrador\Desktop
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins
    C:\Program Files (x86)\Sandcastle Help File Builder\Components
Using framework reflection data for &#39;.NET Framework 4.8&#39; located in &#39;C:\Program Files (x86)\Sandcastle Help File Builder\Data\.NETFramework&#39;
Using presentation style &#39;VS2013&#39; located in &#39;C:\Program Files (x86)\Sandcastle Help File Builder\Components\VS2013&#39;
Loading and initializing plug-ins...
Assembly Binding Redirection Version 2022.2.6.0
Copyright &#169; 2006-2022, Eric Woodruff, All Rights Reserved
Lightweight Website Style Version 2022.2.6.0
Copyright &#169; 2006-2022, Eric Woodruff, All Rights Reserved
Portions Copyright &#169; 2014, Sam Harwell, All Rights Reserved
</buildStep>
<buildStep step="ClearWorkFolder">
Clearing working folder...
-------------------------------
Clearing any prior web/markdown output...
</buildStep>
<buildStep step="ValidatingDocumentationSources">
Validating and copying documentation source information
Source: C:\Users\Administrador\Desktop\DevCase for .NET Framework\DevCase\DevCase.vbproj
    Found project &#39;C:\Users\Administrador\Desktop\DevCase for .NET Framework\DevCase\DevCase.vbproj&#39;

Parsing project files
    Found assembly &#39;C:\Users\Administrador\Desktop\DevCase for .NET Framework\DevCase\bin\Release\DevCase.dll&#39; (.NETFramework 4.8)

References to include:
    envdte, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    envdte80, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    Microsoft.VisualStudio.Setup.Configuration.Interop
    NetFwTypeLib
    SHDocVw
    Shell32

Copying XML comments files
    C:\Users\Administrador\Desktop\DevCase for .NET Framework\DevCase\bin\Release\DevCase.xml -&gt; C:\Users\Administrador\Desktop\Help\Working\DevCase.xml
</buildStep>
<buildStep step="GenerateSharedContent">
Generating shared content files (en-US, Ingl&#233;s (Estados Unidos))...
<plugIn name="Lightweight Website Style" behavior="After" priority="1000">
</plugIn>    Last step completed in 00:00:00,0050
</buildStep>
<buildStep step="GenerateApiFilter">
Generating API filter for MRefBuilder...
    Last step completed in 00:00:00,6182
</buildStep>
<buildStep step="GenerateReflectionInfo">
Generating reflection information...
<plugIn name="Assembly Binding Redirection" behavior="Before" priority="1000">
Adding ignored assembly names to assembly resolver configuration:
    BusinessObjects.Licensing.KeycodeDecoder
    Microsoft.VisualStudio.TestTools.UITest.Playback
    System
</plugIn>[C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe - GenerateRefInfo-b19aca71-49d9-4434-89e6-0495325d599a.proj]
Compilaci&#162;n iniciada a las 29/06/2022 14:49:40.
Proyecto &quot;C:\Users\Administrador\Desktop\Help\Working\GenerateRefInfo-b19aca71-49d9-4434-89e6-0495325d599a.proj&quot; en nodo 1 (destinos predeterminados).
PrepareForBuild:
  Creando directorio &quot;obj\Debug\&quot;.
GenerateBindingRedirects:
  No hay redirecciones de enlace sugeridas procedentes de ResolveAssemblyReferences.
GenerateRefInfo:
  Microsoft.Build (v16.11.2+f3225964253d565862806752e54a7608191a9035)
  &#184; Microsoft Corporation. All rights reserved.
  No source code context base path specified.  Source context information is unavailable.
  Loaded 1 assemblies for reflection and 7 dependency assemblies.
  Wrote information on 244 namespaces, 1099 types, and 32908 members
  Merging duplicate type and member information
  Merged 0 duplicate type(s) and 0 duplicate member(s)
Compilaci&#162;n del proyecto terminada &quot;C:\Users\Administrador\Desktop\Help\Working\GenerateRefInfo-b19aca71-49d9-4434-89e6-0495325d599a.proj&quot; (destinos predeterminados).
    Last step completed in 00:00:08,4792
</buildStep>
<buildStep step="ApplyDocumentModel">
Applying document model to reflection output...
    Last step completed in 00:00:00,1030
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0065: BUILD FAILED: Referencia a objeto no establecida como instancia de un objeto.
   en Sandcastle.Core.Reflection.ApiMember..ctor(XElement apiMember)
   en Sandcastle.Core.PresentationStyle.StandardDocumentModel.ApplyDocumentModel(String reflectionDataFile, String docModelReflectionDataFile)
   en SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>
```

**Comment by EWSoftware** [comment]
I think I might have fixed that issue for the upcoming release which is still a few weeks out.  Would it be possible to get the project you are using as the documentation source so that I can test the issue and confirm that it is fixed?  A workaround for the time being would be to use version 2021.4.9.0 which uses an older method of generating the document model.

**Comment by ElektroStudios** [comment]
> I think I might have fixed that issue for the upcoming release which is still a few weeks out. Would it be possible to get the project you are using as the documentation source so that I can test the issue and confirm that it is fixed? A workaround for the time being would be to use version 2021.4.9.0 which uses an older method of generating the document model.

Thanks for supporting this. As you suggested, I tried SHFB v2021.4.9.0 and it worked perfectly. That's enough for my needs.

Anyways, I'll wait some weeks as you said to test the next SHFB release, and if in case of the issue is not solved with that release then it would be okay to send to you the compiled dll + xml file to [Eric@EWoodruff.us](mailto:Eric@EWoodruff.us) if that can help you to test and finally fix the issue?. Note that I can't send the source-code.

Cheers!.

**Comment by EWSoftware** [comment]
That would be fine.

**Comment by EWSoftware** [comment]
The new release is available.  When you get a chance, please try it with your project to see if this is still an issue.  If so and you can supply a test case, I can investigate.

**Comment by ElektroStudios** [comment]
> The new release is available. When you get a chance, please try it with your project to see if this is still an issue. If so and you can supply a test case, I can investigate.

Hi.

With the new SHFB release I was unable to compile the help file due the https://github.com/EWSoftware/SHFB/issues/931 issue. I had to temporarily remove that conflicting member from the source code.

Another problem I found was that I can't compile the help file if in the **Visibility** tab I have checked "**Explicit interface implementations**". This will cause the error of this topic:

> Error BE0065: BUILD FAILED: Object reference not set to an instance of an object. 

There are hundreds of classes in the source-code, not sure which one can be the problematic one. But I hope that this hint can be useful for you to implement a definitive solution to this problem.

Beyond that, I can compile the help file.

I can live with both problems, but... I don't have none of these problems in SHFB v2021.4.9.0

Thanks for all.

**Comment by LordScree** [comment]
I get the same error when attempting to build after updating to SHFB **v2022.8.14.1**.

I was previously on a version from last year (2021.6, possibly). I uninstalled the old version before installing.

I'm on Windows 11 21H2, using Visual Studio 2022 Enterprise v17.3.2. The documentation sources are two VB.NET projects (both targeting .NET 4.6.2).

The full message is as follows, although I have XXX'd out the type name:

error BE0065: BUILD FAILED: TransformComponent: [T:XXXXX] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException: Object reference not set to an instance of an object.

The error only seems to occur for one type, which is an Enum. It looks to me just like any other Enum - it's possible it's the first Enum, as it's in a file with a name near the start of the alphabet.

Let me know if you need more info.

**Comment by EWSoftware** [comment]
@LordScree  Can you supply a test case that I can use to duplicate the issue?

**Comment by EWSoftware** [comment]
@ElektroStudios I've fixed #931 for the next release but haven't been able to duplicate any issues with the explicit implementation option enabled.  Can you supply a test case that demonstrates that problem?

**Comment by msedi** [comment]
I'm having a similar issue with this code:

https://gist.github.com/msedi/d337a8cfdd34ec51426198a11110383c

Maybe it helps to analyse the problem.

**Comment by EWSoftware** [comment]
@msedi The latest updates work with that example too.  I'll likely publish a new release this weekend with those fixes whether or not I get an example from @ElektroStudios to test it.

**Comment by LordScree** [comment]
> @LordScree Can you supply a test case that I can use to duplicate the issue? Also, if you installed 2022.18.14.0, you may need to uninstall it manually as the 2022.18.14.1 release didn't uninstall it.

Sorry, I have been away.

When you publish the new version, I'll confirm if it works with the project I was using. The project itself is not mine to share.

**Comment by MarcelVersteeg** [comment]
@EWSoftware I don't see a new release after 2022.18.14.1 and I am having the same issue as the OP.

I have attached a zip file that reproduces the issue. It is a documentation project in which a referenced project causes the issue. Unzip the zip-file and run the batch file `BuildAll` from a VS Command Prompt.

I have the issue with VS2022 (version 17.3.5) and VS2019 Build Tools (version 16.11.19) installed.

[SandCastle.zip](https://github.com/EWSoftware/SHFB/files/9737191/SandCastle.zip)

**Comment by EWSoftware** [comment]
@MarcelVersteeg  Are you sure this is the same issue or is it related to #941 which you asked about in a post over there.  I've fixed that issue.  Your example is missing assemblies for the additional reference links plug-in but if I remove that, it does build correctly.

**Comment by MarcelVersteeg** [comment]
@EWSoftware The assemblies for the additional reference are part of a NuGet package. I now see I did not give enough information on how to reproduce. The attached zip file is actually a very stripped down version of my own project where I encounter the issue. Using the `BuildAll.cmd` in the zip file, first the NuGet package FreeSpire.Office will be restored and then the documentation build will issue the given error.

As far as I can see, this is not related to #941.

**Comment by EWSoftware** [comment]
@MarcelVersteeg  Using the new info, I was able to duplicate and fix the issue.  In this case it was caused by some missing EII metadata on the private/obfuscated members in the additional reference links project.

**Comment by MarcelVersteeg** [comment]
> Using the new info, I was able to duplicate and fix the issue

That is great news. Can we expect a big fix release shortly?

**Comment by EWSoftware** [comment]
Unless something else comes up that I don't get resolved, I'll try to get it published this weekend.

**Comment by MarcelVersteeg** [comment]
Just to let you know, that it now indeed works again with the latest build (2022.10.15)
