### ISSUE TITLE
How to distinguish similar classes in different namespaces

### ISSUE THREAD

**Issue by RobertvanderHulst** [EWSoftware/SHFB#919]
In our project we have 2 sets of classes (in different namespaces) with the same class names and same method names. When I document these with SHFB then the class names and method names are merged into different branches of the TOC tree. However when I search for a method then I see one entry (as expected):

![image](https://user-images.githubusercontent.com/14240939/178139601-ebc40ba1-8cf2-41f3-a416-0e52ec950b3e.png)

When I select the Append method from the image above I see the following window
![image](https://user-images.githubusercontent.com/14240939/178139634-52831e3b-0300-4fd5-8941-cc987d24a841.png)
Both entries show the name of the (same) help file. 
Can I control the location that is shown in this dialog and for example show the namespace?
Or do I have to document the 2 namespaces in separate CHM files. But if I do that, how can I make sure that references to common classes used by both Append() methods are still working?

**Comment by EWSoftware** [comment]
It's probably a limitation of the Help 1 viewer.  As I recall, it's based on the TOC title which is extracted from the metadata in the topic header.  While you could change the presentation style to fully qualify that, it would also show as fully qualified in the TOC which is likely not what you want.  I don't think there's a way to get the help 1 viewer to use something else.

If you go down the path of documenting them separately, you'd likely have to use the Additional Reference Links component to supply the necessary reference info for each.  It may be more trouble than it's worth.
