### ISSUE TITLE
error MSB6006: "HHC.EXE" 

### ISSUE THREAD

**Issue by arbryant1** [EWSoftware/SHFB#92]
When attempting to build a sandcastle project help file, I get the following error at the very end:

Compiling HTML Help 1 file...
[C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe]
C:\Projects\ArenaChMS\2014.2.100\Deployment\Build\Help\ArenaTest\Working\Build1xHelpFile.proj(41,5): error MSB6006: "HHC.EXE" exited with code -1073741819.

I couldn't find much info on this.  The only suggestion I found was to try uninstalling and reinstalling the HTML Help Workshop, but that didn't work.

This used to work on Windows 7, but this is the first time I've attempted to use SandCastle on Windows 8.  Could that be the issue?

Anybody else seen this?  Any and all help is appreciated.

**Comment by EWSoftware** [comment]
Does your file path contain a ".h" anywhere in it?  SHFB will typically issue a warning if it does.  That has been known to cause the access violation.  Moving the project to another folder with ".h" anywhere in the path should resolve the issue if that is the case.

**Comment by arbryant1** [comment]
Thanks for the response.  I started digging around, and I noticed that the 'Presentation Style' under Project Properties -> Help File was 'Prototype,' but that has been deprecated.  Out of curiosity, I changed the style to 'VS2010' and it finally built.
