### ISSUE TITLE
Use MSBuild, not raw XML processing, to work with SHFB projects

### ISSUE THREAD

**Issue by Zastai** [EWSoftware/SHFB#921]
Currently, we are unable to use the GUI tools to work with our SHFB projects, because those tools treat those projects as XML files and processing them "manually" rather than using the MSBuild.

As a result, documentation projects that build fine from the command line, cannot be loaded into the standalone GUI and/or Visual Studio, and if they are, often get reformatted and broken if modified that way.

For example, we have a setup where a project can potentially build multiple formats, and so a relevant .props file sets

```
  <PropertyGroup>
    <BuildLogFile>$(MainOutputRoot)LastBuild.$(Configuration).$(HelpFileFormat).log</BuildLogFile>
    <OutputPath>$([MSBuild]::NormalizeDirectory('$(MainOutputRoot)', '$(Configuration)', '$(HelpFileFormat)'))</OutputPath>
    <WorkingPath>$([MSBuild]::NormalizeDirectory('$(IntermediateOutputPath)', '$(HelpFileFormat)'))</WorkingPath>
  </PropertyGroup>
```

The standalone GUI then fails to load the project because it fails to parse the `WorkingPath` value.

On a related note, this would ideally also mean restructuring some of the configuration, especially for plugins, where there is a lot of nested XML in use, which is decidedly non-standard in MSBuild context. While not _wrong_, it does make it much harder than necessary to, say, pass an override on the command line, or set things up with `Condition` attributes.

**Comment by EWSoftware** [comment]
The standalone GUI is not intended to replace Visual Studio, it's just a convenient means of editing the projects in its absence.  As such, there are limitations to what it can do.  That said, I don't think Visual Studio does all that well with MSBuild variables like those above in property values even in non-SHFB projects.

SHFB does support target override files which lets you override properties at build time from the command line or on a build server.  It's most useful for the complex properties such as component configurations.  See the [Building Projects Outside the GUI](http://ewsoftware.github.io/SHFB/html/8ffc0d37-0215-4609-b6f8-dba53a6c5063.htm) topic, specifically the info on the `CustomBeforeSHFBTargets` property and the section target overrides files.  Using an override file with that property should let you do what you need.
