### ISSUE TITLE
Possible to hide assembly versions?

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#924]
Is there currently a way to not display the assembly vresion?
![image](https://user-images.githubusercontent.com/367292/181257867-a82cc298-a6b0-4f16-bb8d-04bf90a904fd.png)

**Comment by EWSoftware** [comment]
Yes, you can add a [resource items](http://ewsoftware.github.io/SHFB/html/fcf8e4ac-5b32-4d5f-9bce-2e85c3468fdc.htm) file to the SHFB project, search for the `assemblyNameAndModule` item and remove the version label and parameter from its value.

**Comment by glenncarr** [comment]
Works great - as always, thank you for the quick response.
