### ISSUE TITLE
Error BE0065 with version 2022.8.14.0

### ISSUE THREAD

**Issue by mckool23** [EWSoftware/SHFB#930]
[Remark: This may be related with the problem described in #917 ]

Hello,

I have a help project created using the previous version of SHFB, 2022.2.6.0. After installing the new version of SHFB building the help now fails with following message:

> SHFB: Error BE0065: BUILD FAILED: TransformComponent: [Overload:Documented.Api.MyClass.op_Implicit] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.ApiTopicOperatorTypes(Boolean plainText)
   at Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.ApiTopicTitle(Boolean qualifyMembers, Boolean plainText)
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderHeaderMetadata()
   at Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderTopic()
   at Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.Render(String key, XDocument topic)
   at Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.WriteMessage(String componentName, MessageLevel level, String key, String message)
   at Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentCore.WriteMessage(String key, MessageLevel level, String message, Object[] args)
   at Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)
   at Sandcastle.Tools.BuildComponents.SwitchComponent.Apply(XmlDocument document, String key)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.Apply(IEnumerable`1 topics)
   at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.&lt;BuildTopics&gt;b__27_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Using the new style Standard 2022 fails as well. Any advice to solve this will be appretiated,

Best regards,

**Comment by catester** [comment]
Same error with me. I guess it's something about op_Implicit (implicit operator in a class)

**Comment by EWSoftware** [comment]
#917 is a separate issue with document model generation which was likely fixed already.  This issue was caused by the topic transformation incorrectly generating the title for overloaded implicit operators, something I didn't have in any of my test cases.  It's fixed and the new release is available (v2022.8.14.1).

**Comment by mckool23** [comment]
Unfortunatelly the issue remains after updating to version v2022.8.14.1. 

I did some test:
1. The implicit operator has been replaced with an explicit operator. Result: it leads to the same error.
2. The operator overloading part was removed from the project. Result: another issue appeared, also related with topic transformation.   

> TransformComponent: [M:Documented.Api.MyClass.GetValue(System.UInt16)] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.FormatException: The string &#39;&#39; is not a valid Boolean value.
   at System.Xml.XmlConvert.ToBoolean(String s)

**Comment by catester** [comment]
Well for me, v2022.8.14.1 fixed the error about op_Implicit. Are you sure you updated SHFB correctly? Open SHFB GUI and check About dialog for version.

**Comment by mckool23** [comment]
I did this check as you mention already and saw the version was the new one, before writing in the post.  Nevertheless, I checked this again just now and realized that even when the last version is shown, the core version is still the old one, so something went wrong with the installation. 

![SHFBVersion](https://user-images.githubusercontent.com/102285602/184824829-e43ed279-457f-4357-a36e-355fbff6fa48.PNG)
 
I will uninstall everything, reinstall SHBF and check again.

**Comment by catester** [comment]
Actually my About dialog looks the same. However I noticed this
![image](https://user-images.githubusercontent.com/3868141/184825952-788f59b2-2dc7-48f3-9cf2-e8bfd5c8941e.png)

Normally the new version would overwrite the existing installation in Add/Remove programs.

So maybe uninstalling v2022.8.14.0 and then installing v2022.8.14.1 would work.
Though it worked for me like this. Maybe you had the GUI open while updating and it didn't update? Just guessing.

**Comment by mckool23** [comment]
Yes, I had the same as I first installed it. I then removed the old one and did a "repair" on the v2022.8.14.1 for any case.

**Comment by mckool23** [comment]
> I did this check as you mention already and saw the version was the new one, before writing in the post. Nevertheless, I checked this again just now and realized that even when the last version is shown, the core version is still the old one, so something went wrong with the installation.
> 
> 
> I will uninstall everything, reinstall SHBF and check again.

Complete uninstall and new install did not help.

**Comment by EWSoftware** [comment]
I'm not sure why it didn't uninstall the last release.  It could be because I only changed the version to ".1" and the MSI installer didn't pick up the change.  I thought I'd done that before without issues.  The strong name stayed at 2022.8.14.0 for binary compatibility so that's normal.  I only update that when making a breaking change that requires all third-party build components to be rebuilt against a newer NuGet release of the SHFB assemblies.

@mckool23 Can you supply a test case for your issue related to the member `M:Documented.Api.MyClass.GetValue(System.UInt16)` and the `FormatException` as that appears to be a separate issue.

**Comment by mckool23** [comment]
> @mckool23 Can you supply a test case for your issue related to the member `M:Documented.Api.MyClass.GetValue(System.UInt16)` and the `FormatException` as that appears to be a separate issue.

After doing some tests myself, I have found the problem. I have a reference to another function using the <see> element, having the atribute autoUpgrade empty, instead of setting it to "true" or "1". 
`
///     <para>
///     A <see cref="ForReferencing(ushort)" autoUpgrade="">reference </see>
///     </para>
`
This can be considered a coding error, of course. Nevertheless, this was not throwing any error using the previous version. Here are sample source code and SHFB project:

[TestForIssue.zip](https://github.com/EWSoftware/SHFB/files/9357875/TestForIssue.zip)

**Comment by mckool23** [comment]
> I'm not sure why it didn't uninstall the last release. It could be because I only changed the version to ".1" and the MSI installer didn't pick up the change.

I got this behavior already by installing v2022.8.14.0 over v2022.2.6.0 so  it is not a matter of the build number in my opinion. I  have no experience with the Wix tools you use, but in the installer I use I need to explicitly allow a side by side installation.

I would guess that any of the GUIDs of the setup (product code, upgrade code, etc.) has been changed. This would affect the recognition of older versions and allows side by side installations.

**Comment by mckool23** [comment]
> #917 is a separate issue with document model generation which was likely fixed already. This issue was caused by the topic transformation incorrectly generating the title for overloaded implicit operators, something I didn't have in any of my test cases. It's fixed and the new release is available (v2022.8.14.1).

Just to let you know that v2022.8.14.1 did indeed fix my original issue. After fixing the other issue (autoUpgrade=""), the project now builds successfully. Somehow I must have mixed up the error messages.

Sorry for the inconvenience and thank you for your support.
