### ISSUE TITLE
<list type="table"> introduces one row only in .chm file

### ISSUE THREAD

**Issue by MillWalky** [EWSoftware/SHFB#933]
When using document type <list>, either directly or indirectly (<include file=...>), only the first <listheader> entry will show up in compiled HTML file.

**Comment by EWSoftware** [comment]
Can you provide an example?

**Comment by MillWalky** [comment]
Hello Eric,

 

Sorry for the inconvenience. Problem solved (mixed up <listheader> and <item> tags).

 

Regards,

 

Bart Vermeulen
