### ISSUE TITLE
C# 9 init only setters not supported

### ISSUE THREAD

**Issue by peterjacobi** [EWSoftware/SHFB#934]
I tested with both FW 4.8 and with Core 5.0 projects, but init only setters like

```
public class Class1 { 
    public int SomeProperty {get; init;}
}
```

will be displayed as
`
public int SomeProperty {get; set;}
`
in the SHFB output.

**Comment by EWSoftware** [comment]
I was able to track down where it was storing the metadata indicating that it's an init only setter and have made the necessary changes.  It will be in the next release.
