### ISSUE TITLE
Unable to register MSBuild default

### ISSUE THREAD

**Issue by msedi** [EWSoftware/SHFB#935]
I have installed the latest version of SHFB and I have VS2022 (Preview) installed . When starting the application it shows

![image](https://user-images.githubusercontent.com/8020659/189353922-f9b10eed-fd24-4651-950a-4f48db1f1b06.png)

which would be OK because I haven't installed them. The question is though why it doesn't use the build tools from VS2022. 
Are the MSBuildLocator packages maybe not up to date?

**Comment by msedi** [comment]
Reading helps ;-) https://ewsoftware.github.io/SHFB/html/502f1147-eaa4-4150-813d-a57eb6b521e8.htm

_Due to a breaking change in the version of MSBuild deployed with Visual Studio 2022 17.3, the standalone GUI is restricted to using a version of MSBuild for Visual Studio 2017, 2019, or a version of 2022 less than 17.3. If you do not have Visual Studio 2017 or 2019 installed, install the related version of the build tools instead. See the installation instructions for a link._

**Comment by EWSoftware** [comment]
Visual Studio is not required to run the standalone GUI, just the build tools which can be installed separately.  If you have any supported version of Visual Studio installed, I suggest managing the projects using it.  The standalone GUI is just there for cases when Visual Studio is not available.  It is also convenient to use as the host when developing components and plug-ins.

The change to MSBuild broke some other tools as well, not just SHFB.  I checked and there does appear to be a workaround by explicitly referencing the required version of System.Memory that's causing the issue.  I've put that in place and it does appear to allow the builds to work now so I'm removing the restriction for the next release.

**Comment by msedi** [comment]
@EWSoftware . Understood. Thanks a lot for your feedback.
