### ISSUE TITLE
SHFB: Error BE0029: Unexpected error while executing plug-in 'Website Table of Contents Generator': System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by glenncarr** [EWSoftware/SHFB#936]
Received the following after upgrading to 2022.8.14.1 - anything I'm doing wrong?  Thanks.

```
SHFB: Error BE0029: Unexpected error while executing plug-in 'Website Table of Contents Generator': System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at SandcastleBuilder.PlugIns.WebsiteTableOfContentsGeneratorPlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at SandcastleBuilder.PlugIns.WebsiteTableOfContentsGeneratorPlugIn.Execute(ExecutionContext context)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ExecutePlugIns(ExecutionBehaviors behavior)

```

**Comment by EWSoftware** [comment]
There's a duplicate ID in the toc.xml file for some reason.  Do you have an example I can use to duplicate the issue?  I can fix the plug in to work around it but that wouldn't fix the underlying issue that caused the duplicate in the first place.

**Comment by glenncarr** [comment]
Not finding `toc.xml` - where should it be?

**Comment by EWSoftware** [comment]
It'll be in the working folder after a failed build.

**Comment by glenncarr** [comment]
Sorry for the delay.  I set up another clean environment to test and now get this error after changing the style to Default2022.  I feel like I'm missing something obvious:

```
 Initializing
SHFB : error BE0001: The PresentationStyle property value of 'Default2022' is not recognized as a valid presentation style definition [C:\<redacted>\SDK.shfbproj]
```

The full `LastBuild.log` content:
```<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2022.2.6.0" projectFile="<redacted>\SDK.shfbproj" started="9/19/2022 2:41:33 PM">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\Users\gcarr\.nuget\packages\ewsoftware.shfb\2022.2.6\tools&#39;
Locating components in the following folder(s):
    C:\Users\gcarr\.nuget\packages\ewsoftware.shfb.netframework\
    C:\<redacted>\Source
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins
    C:\Users\gcarr\.nuget\packages\ewsoftware.shfb\2022.2.6\tools\Components
Using framework reflection data for &#39;.NET Framework 4.8&#39; located in &#39;C:\Users\gcarr\.nuget\packages\ewsoftware.shfb.netframework\4.8.0\tools\Data\.NETFramework&#39;
    Last step completed in 00:00:01.0002
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0001: The PresentationStyle property value of &#39;Default2022&#39; is not recognized as a valid presentation style definition
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>
```

**Comment by EWSoftware** [comment]
The older tools folder value is overriding the latest tools folder value.  The SHFBTooling and SHFBBuildProps must be something you've added as they are not standard and likely aren't needed.  Removing them will likely resolve the unrecognized presentation style issue.

**Comment by glenncarr** [comment]
Thanks - that problem is resolved.  Sorry about that, don't remember why I thought that was needed.

There are duplicates in the toc.xml.  Taking a look at the `Content Layout.content`, all of the duplicate topic id's in the toc.xml are titles in the .content file with GUIDs as the id.  For example, "C#" is one of the duplicate title IDs in the toc.xml.  From the .content file:

`<Topic id="5f8c5a1e-679c-4e7b-8633-4a1fb4186c62" visible="True" noFile="true" isExpanded="true" title="C#">`

I tried replacing all of the GUID id's with other IDs, and still keep getting the error.  I also changed all of the titles to be unique, but I'm still getting the error.

There are over 3000 topics, but I have attached the `Content Layout.content` and the `toc.xml`.

[content and toc.zip](https://github.com/EWSoftware/SHFB/files/9612375/content.and.toc.zip)

**Comment by glenncarr** [comment]
I tried to reproduce this in a small project but haven't yet.  I'll try whittling this project down in size.

**Comment by EWSoftware** [comment]
The duplicates all appear to be empty container nodes.  I'll take a look and see why it's using the title rather than the ID for those as I don't recall why it's doing that.

**Comment by EWSoftware** [comment]
It was setting the ID to the title on purpose.  I think this was probably just a leftover requirement of one of the old presentation styles that doesn't exist anymore.  I've removed it so the IDs will remain as they are with their normal unique values.
