### ISSUE TITLE
Typo in SyntaxElementTabbed.RenderDefaultReturnSection

### ISSUE THREAD

**Issue by SnowyWreath** [EWSoftware/SHFB#938]
https://github.com/EWSoftware/SHFB/blob/689a23c355c5e45ddc8a21fb01e435fb8ed65f05/SHFB/Source/SandcastleCore/PresentationStyle/Transformation/Elements/Html/SyntaxElementTabbed.cs#L455

Should be isReadOnlyAttr instead of fixedBufferAttr at line 455.

This is causing a NullReferenceException when you have a read-only method in a struct.

**Comment by EWSoftware** [comment]
Can you supply an example for this?  I'd like to make sure it's working correctly with the fix, but I haven't been able to come up with something that causes it to hit this case.
