### ISSUE TITLE
Unexpected exit code returned from VSIX installer trying to install the package: 2003

### ISSUE THREAD

**Issue by jaypatrick** [EWSoftware/SHFB#942]
Getting this error on the `Sandcastle Help File Builder Visual Studio Package` task in the installation package v 2002.8.14.1 on Windows 11 22H2 Ent with VS 2k22 Ent. The prior packages installed without error, but installation is halted here. I have attached the installer log for review, however, that is generated from the skipping of the VS2k17/2k19 product check screen. The error happens after that error screen.

[dd_VSIXInstaller_20221005141522_a63c.log](https://github.com/EWSoftware/SHFB/files/9718006/dd_VSIXInstaller_20221005141522_a63c.log)

**Comment by EWSoftware** [comment]
It looks like you're trying to install the VS2017/2019 package but don't have either installed.  Are you running it manually or through the guided installer?  If through the guided installer, it may be detecting 2017 or 2019 even though it isn't there for some reason.  Either way, just run the 2022 VSIX installer manually.
