### ISSUE TITLE
How to use html as is don't want to use AML

### ISSUE THREAD

**Issue by OmShrivastava** [EWSoftware/SHFB#943]

**Comment by EWSoftware** [comment]
Add the HTML files to the project and make sure that the build action is set to Content.  If you include an *index.html* file in the root of the SHFB project, it will override the presentation style copy and will be used as the default page.  Add any other supporting resources such as images, scripts, and style sheets used by the HTML as content items as well.  You can use the existing scripts and stylesheets if you don't want to create your own.  Just use the appropriate paths to the resources in your own HTML files.

**Comment by OmShrivastava** [comment]
Thank for quick response Done Add the HTML files to the project and make sure that the build action is set to Content, Build project CHM got generated.
but not able to see my HTML file in CHM

**Comment by EWSoftware** [comment]
You can add a [site map file](http://ewsoftware.github.io/SHFB/html/3dd5fe3b-1bc3-42e5-8900-56165e3f9aed.htm) to add the items to the TOC if they aren't directly linked to from somewhere else and you didn't add a default page.

**Comment by OmShrivastava** [comment]
Thank you Eric Woodruff, This work for me. I am migrating my help file from older version to latest one
