### ISSUE TITLE
Add support to render custom tags

### ISSUE THREAD

**Issue by DominikAmon** [EWSoftware/SHFB#944]
In my project I have custom tags in the XML Documentation of classes such as:

	/// <summary>
	/// Some Summary
	/// </summary>
	/// <author programmer="GivenName Surname" date="2020-08-04"/>
	///	<history>
	///		<log programmer="GivenName Surname" date="2020-08-04">
	///			<event>Event 1</event>
	///		</log>
	///		<log programmer="GivenName Surname" date="2021-02-04">
	///			<event>Event 2</event>
	///		</log>
	///	</history>
	public class MyClass : IMyInterface

With the older versions of sandcastle, I used custom XSL transformations as described in this archive
https://learn.microsoft.com/de-at/archive/blogs/sandcastle/supporting-custom-tags-in-sandcastle

With the recent version, there is no Transforms\main_sandcastle.xsl any longer.  At least I couldn't find an alternative with the new version in the FAQ or docs.

**Comment by EWSoftware** [comment]
All of the same features are still supported regarding custom elements.  It's just done differently.  I still need to update the help topics to reflect all of the information about the new API and provide new templates for implementing a full presentation style.  However, the new API removes the need to do that in most cases.  Most changes only require a plug-in to add the necessary handlers and they'll work across all presentation styles.

The [Creating a Presentation Style Component](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) topic contains basic info on what you can do and a link to a sample project with some common examples such as implementing custom element support.

The [example plug-in code file](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/main/PresentationStyleModsPlugIn/PresentationStyleModsPlugIn.cs) contains examples of how to add various features to the presentation style.  There's also an example [element handler](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/main/PresentationStyleModsPlugIn/CustomElement.cs).

Your custom section looks similar to the existing [revisionHistory](http://ewsoftware.github.io/XMLCommentsGuide/html/2a973959-9c9a-4b3b-abcb-48bb30382400.htm) XML element so you could probably implement a section handler similar to [the one used for it](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/PresentationStyles/Default2022/Default2022Transformation.cs#L2047).

I can provide more information as needed.
