### ISSUE TITLE
Copy same output file to many deployment paths?

### ISSUE THREAD

**Issue by rotorz** [EWSoftware/SHFB#95]
Hi

What is the easiest way to deploy the same CHM file to many different relative paths?

I am able to get 2 paths by using the regular output path + the Output Deployment Plug-in; but I need 4 output paths.

I suspect that I will need to create a custom "Copy Files" plugin, but I wanted to ask first just in case there was already a solution for this.

Many thanks!

**Comment by EWSoftware** [comment]
The simplest approach would be to use the Post Build Event in the project properties.  You can enter script there to copy the files wherever you like.  The only downside is that the results won't appear in the project's build log.

**Comment by rotorz** [comment]
Thanks. I was going to try that, but it says that the pre-build and post-build events only work inside VS or with MSBuild. I am currently using the SHFB UI.

**Comment by EWSoftware** [comment]
That is the case.  The standalone GUI won't execute the pre/post build events.

**Comment by rotorz** [comment]
I've switched to the VS integration; works a treat, thanks!
