### ISSUE TITLE
Conceptual content XML namespace warnings in VS2022

### ISSUE THREAD

**Issue by Peter-Simpson** [EWSoftware/SHFB#950]
Hi,

I'm using some list elements in my conceptual content files and VS2022 displays warnings like the one below, which don't appear in the SHFB stand-alone GUI. These seem to relate to the definitions given in `xmlns="http://ddue.schemas.microsoft.com/authoring/2003/5" `.

Should I be using a different schema that includes elements such as `list` and `legacyBold`, or is there another way to remove these messages?

Here is the start of my conceptual content file:

`<?xml version="1.0" encoding="utf-8"?>
<topic id="d50074a5-fc2e-4a40-a4aa-dec52045953b" revisionNumber="1">
<developerConceptualDocument xmlns="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink">
<introduction>`

Many thanks, Peter

Example warning message:

`Warning		The element 'para' in namespace 'http://ddue.schemas.microsoft.com/authoring/2003/5' has invalid child element 'list' in namespace 'http://ddue.schemas.microsoft.com/authoring/2003/5'. List of possible elements expected: 'quoteInline, date, foreignPhrase, phrase, copyright, corporation, country, notLocalizable, subscript, superscript, legacyBold, legacyItalic, legacyUnderline, dynamicLink, localizedText, embeddedLabel, lineBreak, cite, codeEntityReference, parameterReference, link, legacyLink, mediaLinkInline, externalLink, userInput, userInputLocalizable, application, database, fictitiousUri, localUri, environmentVariable, errorInline, hardware, literal, markup, command, token, codeInline, languageKeyword, computerOutputInline, ui, math, system, newTerm, placeholder, unmanagedCodeEntityReference, sharedContent, conditionalSection' in namespace 'http://ddue.schemas.microsoft.com/authoring/2003/5' as well as any element in namespace '##other'.`

**Comment by EWSoftware** [comment]
The standalone GUI's editor doesn't do any schema validation in the MAML topics.  The schemas are correct and are installed as part of the Visual Studio package.  A `list` element is a block element so it cannot appear within a `para` element which can only contain other inline elements.  The list should be outside the `para` element.  The [list](http://ewsoftware.github.io/MAMLGuide/html/d6c82cde-f889-4ac9-b3a7-7d45fd6fbffc.htm) element documentation contains examples.

See the [MAML Guide](http://ewsoftware.github.io/MAMLGuide/html/303c996a-2911-4c08-b492-6496c82b3edb.htm) for information on all of the various MAML elements.

**Comment by Peter-Simpson** [comment]
Thanks Eric, I can remove all the error messages by moving the `<list>` outside of the `<para>` tag and by adding a `<para>` tag inside each `<listItem>` as you show in your example. Unfortunately, I'm not a fan of the output's appearance because there is quite a lot of white space betwen the end of the paragraph and the start of the list and also between the list items.

What I'm trying to achieve is that the list and its items are associated with the preceding paragraph, and it is trying to work round the default spacing that I ended up with the approach that generates the warning messages.

Perhaps what I need is a tag whose leading or trailing whitespace can be controlled and that works in the places that support `<para>` ? I'm totally new to working with XML schemas, is this something that I can create or is there another way to control white space around the `<para>` tag?

Many thanks, Peter

**Comment by EWSoftware** [comment]
There is no explicit layout or styling in MAML and that's by design.  The presentation style is used to apply all styling to the transformed topic.  That way, you don't have to make changes to the topics if you change to a different presentation style and they will work consistently across different help file formats.

If you're familiar with CSS, you can make a copy of the default stylesheets used in the presentation style, include them in your project in a [like-named folder](http://ewsoftware.github.io/SHFB/html/77d2d693-db84-4ae3-a84c-e33c71f92e9a.htm), and they will override the default stylesheets. You can make changes to the ones in your project to adjust spacing, apply different styles, etc.

If that doesn't provide enough customization, you can implement your own [custom elements or replace the existing handlers](http://ewsoftware.github.io/SHFB/html/baf1dcbc-e9cf-4d71-a770-621e6eaf10a7.htm) to provide support for additional attributes.  It's much easier to do in the latest release as you no longer have to implement the full presentation style.  I can provide more info on that if needed.

**Comment by Peter-Simpson** [comment]
Hi Eric

Thanks for posting the link to the PresentationStyle plugin, which I've downloaded, I just needed to update the target framework from 4.7 to 4.7.2 to get it to compile in VS2022. I also found that the <#inheritdoc> tag on the Render method was causing missing element warnings in the help project so I replaced it with real &lt;summary&gt; and &lt;param&gt; tags.

The help project compiled OK and showed the new custom styles, although I got quite a few warnings like those below., including one that said that the customSection was an invalid element in a developerConceptualContent tag.

Keeping lists outside para tags works well for me, but, if I include para tags inside listItem tags the spacing between bullets is larger than I would like.

It seems that what I need is a tag that can be used inside a listItem and that accepts all of the inline tags like legacyBold, but that has little or no extra white space above or below. (As well as not generating any warnings! 😁) Can the plugin support creation of this kind of tag?

Many thanks, Peter

`Warning ResolveReferenceLinksComponent: [M:PresentationStyleMods.CustomElement.Render(Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore,System.Xml.Linq.XElement)] Unknown reference link target 'T:Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore'.`

`Warning		ResolveReferenceLinksComponent: [T:PresentationStyleMods.CustomElement] Unknown reference link target 'T:Sandcastle.Core.PresentationStyle.Transformation.Elements.Element'.`

`Warning		The element 'developerConceptualDocument' in namespace 'http://ddue.schemas.microsoft.com/authoring/2003/5' has invalid child element 'customSection' in namespace 'http://ddue.schemas.microsoft.com/authoring/2003/5'. List of possible elements expected: 'section, bibliography, relatedTopics' in namespace 'http://ddue.schemas.microsoft.com/authoring/2003/5'.`

`Warning		ResolveReferenceLinksComponent: [P:PresentationStyleMods.PresentationStyleModsPlugIn.ExecutionPoints] Unknown reference link target 'T:SandcastleBuilder.Utils.BuildComponent.ExecutionPoint'.`

**Comment by EWSoftware** [comment]
The reference link warnings are normal as those members are not being documented and there is no link to their topic.  They can be ignored.  The custom MAML elements aren't part of the MAML schema so they will always generate a warning though they can be ignored.

However, your best bet is to start by trying to override and modify the stylesheet as noted above.  It's likely the margin on the `ul` element or some combination of it and the `li` and/or `p` element styling.  You can play with those easily enough by building the output, viewing it, and then editing the stylesheet and forcing a reload of an affected topic in the browser to see the changes until you find what you like.  You can then copy those changes back to the project copy of the stylesheet.

**Comment by Peter-Simpson** [comment]
Hi Eric,

Thanks very much, I’ll try that approach.

Best wishes, Peter
