### ISSUE TITLE
Add support for MSHelpViewer in nuget package

### ISSUE THREAD

**Issue by Andersso** [EWSoftware/SHFB#952]
Hello, I'm currently looking at building our sandcastle projects with NuGet, and we're building following file formats: HtmlHelp1, MSHelpViewer.

Sadly, MSHelpViewer doesn't work with the NuGet package.

The reason it doesn't work is that the builder will assume that the following file exists inside the nuget package (it doesn't):
`tools\Tools\HelpLibraryManagerLauncher.exe`

Copying the exe over to the nuget directory will make it work.

Is is possible to include this exe in the nuget package?
If not, is is possible add the posibility to override the location of this tool with a MSBuild property?

The nuget packages being used:
`EWSoftware.SHFB 2022.10.15`
`EWSoftware.SHFB.NET 5.0.0.2`

Thanks!

**Comment by EWSoftware** [comment]
I pushed a new copy of the package that includes the tool (2022.10.15.1).  It should be available shortly.
