### ISSUE TITLE
SHFB stopps compiling after the first class

### ISSUE THREAD

**Issue by cwieczorrek** [EWSoftware/SHFB#953]
Hello,
I am compiling new help files for several old windows forms projects with version 2022-10-15.
I use the stand-alone exe. I open the old SHFB project file via File/Open. For most of my projects compilation works fine.
In some cases SHFB terminates after processing the first class of the project.

- no crash
- no error message
- for me no hint in the log file

SHFB ends with "Build completed successfully at 09.11.2022 15:45:15.  Total time: 00:00:08,8757".

Deleting the old SHFB project file and create a new project makes no change.
Recompiling the windows forms project works fine but  makes no change.
Changing the framework makes no change.

To illustrate the problem please see attached files:

Image 1 shows the compiled chm file (I think it is not a chm problem, changing the output type makes no difference). Only "SplashScreen1" is referenced.

Image 2 shows the code source folder. There are some classes more listed as in the chm file...

Finaly I added the build log file.

Any help is welcome.
Sincerely
Carsten Wieczorrek

![Screenshot 2022-11-10 084413](https://user-images.githubusercontent.com/62640290/201092855-9b58566a-1b66-40c8-a5e4-cc8a0dd552bb.jpg)
![Screenshot 2022-11-10 084452](https://user-images.githubusercontent.com/62640290/201092920-402335ce-edb7-4211-b0fd-b6e280d4366b.jpg)
[LastBuild.log](https://github.com/EWSoftware/SHFB/files/9980702/LastBuild.log)

**Comment by EWSoftware** [comment]
Most likely, the bulk of the classes are private or internal and are thus not documented by default.  You can change the settings in the Visibility category of the SHFB project to include private and/or internal types and members.  Just be aware that you'll likely get a lot of extra unwanted stuff documented as well.  You can filter out anything you don't want using the API filter.
