### ISSUE TITLE
Help Viewer is not work in 2022.8.14 or 2022.10.15 with Japanese setting

### ISSUE THREAD

**Issue by KIPwfujii** [EWSoftware/SHFB#954]
When creating a file in MS Help Viewer format with SHFB Version 2022.8.14 or 2022.10.15, headings are not displayed in the Contents tab of the side menu.

<img width="862" alt="スクリーンショット 2022-11-11 110302" src="https://user-images.githubusercontent.com/87343827/201246323-e71addd5-2cf9-4aec-ba57-2ccbcc2ae661.png">

Also, when I try to view the page, the following error occurs.

<img width="373" alt="スクリーンショット 2022-11-11 105339" src="https://user-images.githubusercontent.com/87343827/201246383-739e8168-c36e-473e-8ab0-687e9dca884f.png">

```
Error: SetDefaultLanguage is not defined
URL: ms-xhelp:///?method=page&id=N%3ACOLORIZERLIBRARY&locale=ja-JP&vendor=Vendor%20Name&format=html&topicversion=100&topiclocale=EN-US
```

There is no problem with output in Web and HTML Help 1 format.

Help output with SHFB version 2022.2.6 was also fine in Help Viewer.

What is the problem?

I am using `VS2019` and the language setting is Japanese.
Help file language is also Japanese.

**Comment by EWSoftware** [comment]
I was able to duplicate the issue.  The build engine isn't setting the locale in the topic transformation so it's still set to the default en-US in all of the generated topics.  It'll be fixed in the next release.
