### ISSUE TITLE
Unable to install VSIX via guided installer if VS2019 IDE is not installed

### ISSUE THREAD

**Issue by MarcelVersteeg** [EWSoftware/SHFB#956]
Currently I am installing SHFB on a new computer, that only has VS2022 installed using the guided installation (version 2022.10.15.0).

In the step where the Visual Studio Package is installed, this fails, because VS2019 is not installed (only the required VS2019 build tools, and not the IDE). When I click the "Install Package" button, an error is displayed with the text "Unable to locate installer: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VSIXInstaller.exe". This tool is indeed not present, and is only installed when the IDE is installed.

After that I am also not able to install the VS2022 VSIX via the guided installation.

**Comment by EWSoftware** [comment]
I'll add a check and skip it if the VSIX installer isn't present for a version.  For now, you can install it manually.  Just run it from the .\InstallResources folder and skip the step in the guided installer.

**Comment by MarcelVersteeg** [comment]
That is indeed what I already did.

Thank you for fixing this inconvenience in a future version.
