### ISSUE TITLE
SFHB crashes with NullReferenceException

### ISSUE THREAD

**Issue by lellid** [EWSoftware/SHFB#959]
Hi,

in the latest two versions of SHFB I get a crash when creating a class reference of my DLLs. I suspect that it has something to do with the fact that in one of my own DLLs I have a namespace `System.Drawing` in it, and this somehow interferes. Here is the error message:

```
Combining conceptual and API intermediate TOC files...
    Last step completed in 00:00:00,6719
-------------------------------
Merging custom build component configurations
C:\Temp\SandCastleTemp\BuildAssembler.config
  Updating reference topic configurations.
  Updating conceptual topic configurations.
    Removing unused ExampleComponent.
    Last step completed in 00:00:00,0469
-------------------------------
Building help topics...
Loading configuration...
SHFB: Warning BE0066: CopyFromIndexComponent: Entries for the key 'N:System.Drawing' occur in both 'O:\ToolsProgramming\Sandcastle Help File Builder\Data\.NETFramework\System.Drawing.xml' and 'C:\Temp\SandCastleTemp\reflection.xml'. The last entry will be used.
Processing topics...

SHFB: Error BE0065: TransformComponent: [2FD7A20CC4874B8AC0167F6E62AF3C00] An error occurred while attempting to transform the reflection data to a topic. The error message was: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.AutoOutlineElement.InsertAutoOutline(TopicTransformationCore transformation, XElement renderTo, XElement content, String leadIn, AutoOutlineType outlineType, Int32 currentDepth, Int32 maxDepth)
   bei Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.AutoOutlineElement.Render(TopicTransformationCore transformation, XElement element)
   bei Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.RenderNode(XNode node)
   bei Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.RenderChildElements(XElement parent, IEnumerable`1 children)
   bei Sandcastle.Core.PresentationStyle.Transformation.Elements.IntroductionElement.Render(TopicTransformationCore transformation, XElement element)
   bei Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.RenderNode(XNode node)
   bei Sandcastle.Core.PresentationStyle.Transformation.Elements.NonRenderedParentElement.Render(TopicTransformationCore transformation, XElement element)
   bei Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.RenderNode(XNode node)
   bei Sandcastle.Core.PresentationStyle.Transformation.Elements.NonRenderedParentElement.Render(TopicTransformationCore transformation, XElement element)
   bei Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.RenderNode(XNode node)
   bei Sandcastle.PresentationStyles.VS2013.VisualStudio2013Transformation.RenderTopic()
   bei Sandcastle.Tools.BuildComponents.TransformComponent.Apply(XmlDocument document, String key)

```

This message is repeated two more times, then the build process stops. With an older version of SHFB (2022.1.22.0) everything runs fine.

**Comment by EWSoftware** [comment]
The warnings are unrelated.  It's failing while generating an auto-outline.  Do you have MAML topics in the project?  If so, can you supply them as a test project I can use to duplicate the issue?  The ID '2FD7A20CC4874B8AC0167F6E62AF3C00' should be the ID of the failing topic.

**Comment by lellid** [comment]
Hi Eric,

please clone Altaxo: `git clone https://github.com/Altaxo/Altaxo.git`. The topic you mentioned can be found in `HelpContent/IOA-IOL-2FD7A20CC4874B8AC0167F6E.aml`. The root directory contains the SHFB project file (`AltaxoClassRef-Chm.shfbproj`).

Thanks, Dirk

**Comment by EWSoftware** [comment]
I've fixed it for the next release.  For now, you can work around the issue by updating any topics with an `autoOutline` element by adding an empty `title` element to any `section` elements that don't have one.

Also, the project will start to build faster if the SHFB projects and their content are moved to their own subfolder.  As it is right now, when the build starts, it scans the project folder and all subfolders for component assemblies.  With them sitting in the root folder, it's scanning all the build output of the other projects unnecessarily looking for components.  Putting the help projects in their own subfolder will prevent that.

**Comment by lellid** [comment]
Hi Eric,

thank you for fixing it, and these helpful hints!

Dirk
