### ISSUE TITLE
BE0071 when targeting framework 4.6

### ISSUE THREAD

**Issue by SOHODeveloper** [EWSoftware/SHFB#96]
The Frameworks.xml file does not have a .NETFramework 4.6 entry.  It does have one for .NETPortable 4.6.  I tried copying the .NETFramework 4.5.3 to 4.6, (update version, path etc.) but still received the error BE0071.  I also updated my .shfbproj file to use 
```<FrameworkVersion>.NET Framework 4.6</FrameworkVersion>```
 instead of the reference to the .NETPortable library

At this point, I don't really have to have the comments from the BCL assemblies.  I just need to get my comments built.

I am using version 2015.5.2.0

**Comment by EWSoftware** [comment]
Replace the Frameworks.xml file with this one and it should work:

https://raw.githubusercontent.com/EWSoftware/SHFB/DotNET45Migration/SHFB/Source/MRefBuilder/Frameworks.xml

**Comment by SOHODeveloper** [comment]
Yes, the new file worked.  One note.  I had to restart VS to make it work.

Big Thanks
