### ISSUE TITLE
Help Viewer 2.3: Missing text in table of contents

### ISSUE THREAD

**Issue by FrankHileman** [EWSoftware/SHFB#960]
![image](https://user-images.githubusercontent.com/17464368/211231104-d3e37105-a9ad-4f58-b3b0-b0cd666c0185.png)
I have successfully used older releases, but with the latest release, the text is missing in the table of contents in help viewer 2.3. It could be there is something wrong with my installation. I tried creating a new help project from scratch, and it has the same problem.

[DocumentationTest.zip](https://github.com/EWSoftware/SHFB/files/10369991/DocumentationTest.zip)

Looking at the source of the generated files, I don't see a meta element for Title... but it could be something else.

Thanks for all your hard work.

**Comment by FrankHileman** [comment]
A related question.. You said that help viewer is deprecated now. Yet some people still need to view help content without an internet connection. I am providing help content for people that use Visual Studio. I see you use iis express as the web server to view the generated web pages. Is that a viable solution for distributing offline help? Are there any other ideas about providing offline help content? Our main project produces more than 3700 files, so I don't think a pdf or word file is a good solution.

**Comment by EWSoftware** [comment]
It's working for the test project I have but not for yours.  I'll have to compare them and see what's different.

Regarding deprecation, it just means I won't be providing any future improvements to the VS2013 presentation style nor will any new presentation styles like the new Default 2022 style include support for Help 1 or Help Viewer output.  As noted in the release notes, with the end of support for Internet Explorer, it seems unlikely that either of the help viewers for these formats will receive any future support or updates from Microsoft as they both use the Internet Explorer control to display the help content. This makes it difficult if not impossible to support the latest HTML features in the new presentation style.

While the IE controls are still functional, I'll keep support for building their related output in the VS2013 presentation style.  Assuming it ends when IE Mode support ends, that would likely be 2029 but I haven't found anything definitive regarding the help viewers specifically.  IIS would have to be installed to view the help content offline so it probably isn't a viable alternative in your case.

**Comment by FrankHileman** [comment]
I cloned the repo and found a solution, TestDoc, containing TestDoc and TestCaseProject projects. When modified to create a help viewer output, it does work. Is that the one you are thinking that works? I will see if it is the .net framework selection (I use 4.8) or some other property.

**Comment by FrankHileman** [comment]
I isolated the problem. It occurs when Indent HTML is false: `<IndentHtml>False</IndentHtml>`

**Comment by FrankHileman** [comment]
I don't know how to catch the process executing in the debugger yet, but I think the problem must be in `WebsiteTableOfContentsGeneratorPlugIn.Execute`, the last line:
`tocFragment.Save(Path.Combine(tocFolder, id + ".xml"),
    builder.CurrentProject.IndentHtml ? SaveOptions.None : SaveOptions.DisableFormatting);
`

**Comment by EWSoftware** [comment]
It shouldn't make a difference so I'm not sure why it is now.  You don't want it enabled as it's only for testing and will cause code example to be formatted incorrectly.

**Comment by FrankHileman** [comment]
If you give me a hint on how to start the process in visual studio, I can try to debug it. Maybe the formatting affects something downstream.

**Comment by EWSoftware** [comment]
Compared to the older release, the only difference is the order of the metadata elements which has no significance and simply adding or removing whitespace shouldn't cause it to fail to create a TOC in the help viewer.  Internally the help viewer runs the topics through a transformation before displaying them to fix up the link targets etc. so there's likely a bug in that process.  I fixed it by adding text nodes before and after the title element containing nothing but a CR/LF and that works around the issue.
