### ISSUE TITLE
Can't build docs for a toy solution

### ISSUE THREAD

**Issue by amine-aboufirass** [EWSoftware/SHFB#961]
I made a very simple console app  as follows:

```
using System;

namespace TestProject
{
    /// <summary>
    /// The console application class
    /// </summary>
    class Program
    {
        /// <summary>
        /// entry point
        /// </summary>
        /// <param name="args">command line arguments</param>
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

I enabled documentation as explained [here](https://ewsoftware.github.io/XMLCommentsGuide/html/57C91630-95D6-4E3E-AF24-3415CC569AC8.htm), and my project file looks like the following:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\Users\aa\Desktop\TEMP\sandcastle-doc-builder\TestProject\TestProject.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>C:\Users\aa\Desktop\TEMP\sandcastle-doc-builder\TestProject\TestProject.xml</DocumentationFile>
  </PropertyGroup>

</Project>
```

I added the solution containing this project as my documentation source, and ran the build.

Unfortunately, I get the following error:

```
-------------------------------
Generating reflection information...
[C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe - GenerateRefInfo-97cb7ab0-54c7-429a-a8c2-f7374b2fbe54.proj]
Build started 25/01/2023 17:49:05.
Project "C:\Users\aa\Desktop\TEMP\sandcastle-doc-builder\TestProject\Help\Working\GenerateRefInfo-97cb7ab0-54c7-429a-a8c2-f7374b2fbe54.proj" on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.8 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\aa\Desktop\TEMP\sandcastle-doc-builder\TestProject\Help\Working\GenerateRefInfo-97cb7ab0-54c7-429a-a8c2-f7374b2fbe54.proj]
Done Building Project "C:\Users\aa\Desktop\TEMP\sandcastle-doc-builder\TestProject\Help\Working\GenerateRefInfo-97cb7ab0-54c7-429a-a8c2-f7374b2fbe54.proj" (default targets) -- FAILED.
    Last step completed in 00:00:00.6904
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
   at SandcastleBuilder.Utils.BuildEngine.TaskRunner.Run(String processFilename, String targetFile, String arguments)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
```

Any ideas on why this might occur?

**Comment by EWSoftware** [comment]
The error in the output indicates that the .NET 4.8 targeting pack is not installed.  You can install that through the Visual Studio installer.  It likely needs that as part of the steps used to resolve assembly references since it uses the common targets to do so and that's what's generating the error.

**Comment by amine-aboufirass** [comment]
@EWSoftware please excuse my ignorance but in that case I don't quite understand why my code builds and runs without any issues. Here's my output for `dotnet --list-sdks`:

```
3.1.101 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
5.0.411 [C:\Program Files\dotnet\sdk]
```

It seems I have the correct frameworks installed. Is it possible to get SandCastle to build docs for `netcoreapp3.1`? I'm afraid that's what I'm trying to achieve here...

**Comment by EWSoftware** [comment]
Your code isn't using .NET 4.8 and the issue isn't related to it.  There's a dependency in one of the projects that SHFB uses to resolve references to generate reflection information.  It uses the MSBuild common targets for that.  It looks like that has a dependency on the .NET 4.8 targeting pack being installed.  Installing the missing targeting pack should resolve the issue.

**Comment by EWSoftware** [comment]
The targeting pack/development pack installs the reference assemblies used by Visual Studio and other build tools.  It's not the same as the actual framework used by running applications.

You probably don't have IIS Express installed.  It uses that to view the website locally so that the scripts work.  I need to remove the "View the HTML website instead" message as that it is reference to the old file system option that was removed.  If opened from the file system, the browser blocks scripts from running so it needs a web server to view the content properly.

**Comment by amine-aboufirass** [comment]
I installed IIS Express from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48264) and now everything seems to work for my test project.
