### ISSUE TITLE
Building legacy project with older presentation style (vs2010)

### ISSUE THREAD

**Issue by amine-aboufirass** [EWSoftware/SHFB#964]
I have a legacy project that uses `vs2010` as its presentation style. When I try to build this project, I get the following error:

> SHFB : error BE0001: The PresentationStyle property value of 'vs2010' is not recognized as a valid presentation style definition

When I check inside the `Components` directory of `$Env:SHFBROOT` these are the presentation styles that appear to be present.

```
Colorizer
Default2022
Markdown
OpenXml
Shared
SyntaxContent
VS2013
```

I would rather keep the default SHFB file provided with this legacy project and build it with the `vs2010` presentation style. Is there any way I can force that?

**Comment by EWSoftware** [comment]
The latest release uses a new API for the presentation styles that is entirely code-based rather than the old XSL transformations from prior releases.  The VS2010 style was just too old and was close enough to the VS2013 style that it wasn't worth converting it to the new API.  See the [v2022.8.14.0](http://ewsoftware.github.io/SHFB/html/502f1147-eaa4-4150-813d-a57eb6b521e8.htm) release notes for details.

If you can, I suggest switching to the new Default2022 presentation style.  If you can't because you need Help 1 (CHM) or Help Viewer (MSHC) output, you can switch to the VS2013 presentation style which is the only legacy format available now.  If you really must use the VS2010 presentation style, you'll need to drop back to version 2022.2.6.0 which was the last one to contain it.

**Comment by amine-aboufirass** [comment]
I went ahead and installed 2022.2.6.0 and it now doesn't throw the error anymore. Unfortunately I'm getting the error below:

> error BE0043: Unexpected error detected in last build step.

Which .NET targeting framework does 2022.2.6.0 require?

**Comment by EWSoftware** [comment]
What's the error from the build log?  That will tell you what the issue is and will determine how to fix it.

**Comment by amine-aboufirass** [comment]
That is the error. Prior to that there are only `BE0006` warnings.

There are also warnings like the following:

```
...\SandcastleHelpFileBuilder\SandcastleHelpFileBuilder.targets(4
4,3): warning : MRefBuilder : warning : Ignoring unresolved assembly reference: Microsoft.
AspNetCore.Authentication (Microsoft.AspNetCore.Authentication, Version=2.0.0.0, Culture=n
eutral, PublicKeyToken=adb9793829ddae60) required by idunno.Authentication.Basic [...\WorkDir\GenerateRefInfo-5e484250-9a85-4105-ad5f-ecc6ec7547bc.proj] [...\Project.shfbproj]
...\SandcastleHelpFileBuilder\SandcastleHelpFileBuilder.targets(4
4,3): warning : MRefBuilder : warning : Ignoring unresolved assembly reference: System.Sec
urity.Principal.Windows (System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutr
al, PublicKeyToken=b03f5f7f11d50a3a) required by Coordinator[...\WorkDir\GenerateRefInfo-5e484250-9a85-4105-ad5f-ecc6ec7547bc.proj] [...\Project.shfbproj]
```

So it's not very clear from the log what exactly is going wrong.

**Comment by EWSoftware** [comment]
There should be a stack trace in the log.  Can you attach the full log here?

**Comment by amine-aboufirass** [comment]
I'm afraid I can't do that since the entire log contains some implementation details of a commercial code base which doesn't belong to me and which I'm not allowed to share,

I have, however, opened the `LastBuild.log` file and identified the following errors;

```
MRefBuilder : error : Unresolved assembly reference: mscorlib (mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089) required by Microsoft.Practices.Unity [D:\Dev\Flow\drms\Document\WorkDir\GenerateRefInfo-5e484250-9a85-4105-ad5f-ecc6ec7547bc.proj]
SHFB: Error BE0043: Unexpected error detected in last build step.  See build log for details.
```

Perhaps this is already sufficient to identify what exactly is going wrong?

**Comment by amine-aboufirass** [comment]
From the SandCastle UI it appears that the documentation sources are a mix of DLL and XML files. I don't see any SLN files on there, so I think the answer to your question is that the assemblies are used as documentation sources.

The target framework is indicated in the SHFB project file as follows:

`<FrameworkVersion>.NET Framework 4.7.2</FrameworkVersion>`

I have verified and I do have the Microsoft .NET framework 4.7.2 SDK installed locally in my system.

**Comment by EWSoftware** [comment]
Based on the errors, it looks like some of the assemblies used as documentation sources are not .NET Framework assemblies so they may be .NET Core or .NET Standard.  There are issues mixing assemblies from different framework types like that.  These issues are found and reported when using the solution/projects as documentation sources but it can't when using the assemblies directly.  Such mixing of assembly types isn't currently supported.  The only workaround for now is to split them into separate projects by framework type and use the version builder plug-in to combine them.

**Comment by EWSoftware** [comment]
The version builder is added through a [plug-in](https://ewsoftware.github.io/SHFB/html/6c03afba-18d0-4270-b521-c2015c4d97b3.htm) and is available in that version.  See the Plug-Ins category in the SHFB project property pages.

**Comment by EWSoftware** [comment]
Ignore the implementation references to the old tools.  All the tools are built into SHFB now and the plug-in handles everything.  You just have to edit the plug-in configuration once you add it to your SHFB project to tell it how to handle the projects.  It will get executed automatically during the build.
