### ISSUE TITLE
build not possible for .net6.0 SDK only is installed

### ISSUE THREAD

**Issue by tvogel-nid** [EWSoftware/SHFB#965]
I have a project targeting .net60 and can only use a build server that has the following 
`.NET SDK/Runtimes installed(cannot easily be changed):
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.113 [C:\Program Files\dotnet\sdk]
  6.0.308 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
 
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`

It seems that .net7.0 is now required:
[reflection file](https://github.com/EWSoftware/SHFB/blob/master/SHFB/Deploy/Data/.NET/.NETCoreStandardNet50Plus.reflection)

But what happens to people that don't have the newest .net available?

**Comment by EWSoftware** [comment]
The reflection data set is always built off of the latest assemblies and it looks there for the framework XML comments files.  Assembly info for projects using that reflection data set typically comes from the NuGet packages so it won't even look at those.

Are you having an issue with it not building?  What version of SHFB are you using?  A change in the latest release should let it fall back to the nearest available target framework that is present but that's only so it finds the XML comments files for the framework.

**Comment by tvogel-nid** [comment]
Hi,

what I can see on the build machine is this:
`2023-01-31T14:50:34.6750800Z [90m[[0m[31;1mERROR Compile SHFB : error BE0071: Unable to locate information for the project framework version '.NET Core/.NET Standard/.NET 5.0+' or a suitable redirected version on this system.  See error number help topic for details. [C:\agent\w\2\s\Source\CalibrationSupport\VectorCalLib.SandCastle\VectorCalLib.SandCastle.shfbproj]`

It works fine on my local machine, the only obvious difference is that I've additionally installed the .net7:
SDK:
7.0.200-preview.22628.1
Runtimes:
Microsoft.AspNetCore.App 7.0.0
Microsoft.NETCore.App 7.0.0
Microsoft.WindowsDesktop.App 7.0.0

So my guess is that, as my projects I want to document, are targeting .net6.0 that fallback from .net7 to .net6 somehow fails.
```
<TargetFramework>net6.0</TargetFramework>
<PlatformTarget>x64</PlatformTarget>
<GenerateDocumentationFile>True</GenerateDocumentationFile>
```

In the shfbproj I added the following packages to be able to build on the build machine without the need to install all the stuf f that seems to be needed.

  ```
<ItemGroup>
    <PackageReference Include="EWSoftware.Sandcastle.Core">
      <Version>2022.12.30</Version>
    </PackageReference>
    <PackageReference Include="EWSoftware.SandcastleBuilder.Utils">
      <Version>2022.12.30</Version>
    </PackageReference>
    <PackageReference Include="EWSoftware.SHFB">
      <Version>2022.12.30</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by EWSoftware** [comment]
The SHFB.NETCore package is for the older .NET core versions and the SHFB.NETFramework package is for the full framework (.NET 4.8 and lower) so you could remove those from the project.  If you've installed SHFB locally, all the tools and data sets are present.  If building on a server where the tools aren't installed, you need the packages.  They're split into different packages due to size constraints.
