### ISSUE TITLE
Solution with multi target frameworks

### ISSUE THREAD

**Issue by WolfgangHG** [EWSoftware/SHFB#967]
I have a solution where all of the source projects have two target frameworks:

```
    <TargetFrameworks>net48;net6.0-windows</TargetFrameworks>
```

My Sandcastle project file is attached to #962 and declares this framework version:

```
    <FrameworkVersion>.NET Core/.NET Standard/.NET 5.0+</FrameworkVersion>
```

On build, this warning is reported:

`
SHFB(0,0): warning BE0007: A project with a different or higher framework version was found.  Changing project FrameworkVersion property from '.NET Core/.NET Standard/.NET 5.0+' to '.NET Framework 4.8' for the build.
`

As to my understanding, a target framework "net6.0-windows" should match the Sandcastle frameworkversion ".NET 5.0+"?

The switch to framework 4.8 might be relevant if the code has differences for the different target frameworks by using the "#if NET6_0_OR_GREATER" preprocessor directives.

**Comment by EWSoftware** [comment]
It currently uses the first target framework seen in the documentation source project.  To force it to use a specific one, set the TargetFramwork option on the documentation source to the one you want to use.

**Comment by WolfgangHG** [comment]
Thanks. Swapping the "TargetFrameworks" in the source project file so that "net6.0-windows" is the first one generates the doc for the .NET6 version and the warning is gone.
But wouldn't it make sense to detect the matching target framework based on the "FrameworkVersion" declaration in the Sandcastle project file?

Thinking further about this: what about multiple "FrameworkVersions" for the Sandcastle project, each one generating its own help file? But this is not required by me, I am happy that I can create the .NET6 doc.

**Comment by WolfgangHG** [comment]
OK, swapping the target frameworks is only a workaround for building the help file, but no permanent resolution. In my solution, there are also projects that cannot be converted to SDK style must stick with the old project format (e.g. a WordAddin or an old .NETFramework web project, where no SDK style project is available). Those cannot resolve the reference to the .NET48 version of the dll, as they seem to evaluate only the first "TargetFrameworks" entry.

**Comment by EWSoftware** [comment]
You don't have to change your projects, just the [TargetFramework property](http://ewsoftware.github.io/SHFB/html/64f0576f-51b3-4dae-aaac-06568c6c2f68.htm) on the documentation source in the SHFB project to tell it which one to use.  That works regardless of whether the documenation source is an SDK style or older format project.  A set of projects with mixed frameworks and none in common is a known issue (i.e. one that's .NET 6 only and another that's .NET 4.8 only).  Longer term, I do have plans to support multi-targeted and mixed framework documentation sources so that it can produce help for them all from the same SHFB project and include an accurate platforms section, but it will be a while yet before that's done.

**Comment by WolfgangHG** [comment]
Ah, I didn't know about this setting. Many thanks!

Just for the records:
![image](https://user-images.githubusercontent.com/138049/216555473-6f20dc85-b2f3-4b69-ba0e-f897db33ea00.png)

**Comment by WolfgangHG** [comment]
Additional question: one of those projects references a Nuget package (and unfortunately it does so only for one of the two target frameworks). I see this warning:

`C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\SandcastleHelpFileBuilder.targets(44,3): warning : MRefBuilder : warning : Ignoring unresolved assembly reference: Microsoft.CodeAnalysis (Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) required by HG.Tools.VisualBasic [E:\Projekte\Tools\TEST\ToolsDataDoc\Help\Working\GenerateRefInfo-2d701d58-d572-453f-8224-882bfc5da9de.proj]`

The project file snippet looks like this:

```
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="3.6.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0-windows' ">
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.2.0" />
  </ItemGroup>
```

**Comment by EWSoftware** [comment]
It just means it couldn't find that reference and ignored it.  The worst that will happen is that there won't be any inherited members from any types in that assembly and there may be some warnings when generating the help topics that it can't generate a link to the base type or its members if there are any.

**Comment by WolfgangHG** [comment]
So, there is no need to change anything on my side? In this case, you can close this issue.
