### ISSUE TITLE
Include indexed search 'tags'

### ISSUE THREAD

**Issue by mg-cs** [EWSoftware/SHFB#974]
Is there a 'tagging' feature - key phrases in XML comments that aren't included in the documentation output, but _are_ used to build the search index - or a recommended workaround to simulate these kinds of search tags? (E.g. judicious use of `<span style="display: none;">tagging_keyword_here</span>`)

**Comment by EWSoftware** [comment]
There isn't anything available now that would do that.  However, you could implement it with a plug-in that extends the presentation style with a custom element.  For example, it could replace `searchText` elements with a span like you show above.  The code that generates the index just extracts all words from each topic so it should include the search text in the index but they wouldn't be shown in the topic.  That said, if the words already appear naturally within the topic text, adding the search tag would be superfluous so I'm not sure if it's worth it.

You could model it after the example element handler in the Presentation Style Mods example:
[Custom element handler example](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/main/PresentationStyleModsPlugIn/CustomElement.cs)
[Adding it to the presenation style through a plug-in](https://github.com/EWSoftware/PresentationStyleModsPlugIn/blob/main/PresentationStyleModsPlugIn/PresentationStyleModsPlugIn.cs#L192)
