### ISSUE TITLE
Target Framework not supported?

### ISSUE THREAD

**Issue by RobThree** [EWSoftware/SHFB#979]
I have installed the [latest SHFB version](https://github.com/EWSoftware/SHFB/releases/tag/v2023.3.4.0) but whenever I open a solution in VS2022 that includes a SHFB project I get this message:

![image](https://user-images.githubusercontent.com/607888/224291018-329890b3-9f8b-4684-af75-697ee99f1b0c.png)

* When I choose the first option (update target) and click Continue nothing happens; the window closes and that's it. No changes to any files in my solution.
* When I choose the second option (Download .Net Framework 4.0 targeting pack) I get redirected to http://go.microsoft.com/fwlink/?prd=12485&pver=12&sbp=TargetPackMissing&plcid=0x409&o1=.NETFramework,Version=v4.0. I have downloaded and installed the .NET Framework 4.8.1 and some older versions but the ".Net Framework 4.0 targeting pack" is nowhere to be found (which makes sense since it dates 2010 or something).
* The last option (Do not load the project) obviously doesn't load the project (the SHFB project that is, the rest of the solution is loaded correctly).

The SHFB project itself targets .Net core:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="14.0">
  <PropertyGroup>
...
    <FrameworkVersion>Cross-platform (.NET Core/.NET Standard)</FrameworkVersion>
```
Changing to:
```xml
    <FrameworkVersion>.NET Core/.NET Standard/.NET 5.0+</FrameworkVersion>
```
...has no effect.

Is there anything I can do to fix this? What is the first option supposed to do?

**Comment by EWSoftware** [comment]
`FrameworkVersion` is a SHFB property that tells it what reflection data set to use and doesn't affect this issue.  Check the `TargetFrameworkVersion` property which is required by Visual Studio and needs to be set to a framework version that is installed.  Updating that to something that is installed such as "v4.8" should resolve the issue.  Some very old SHFB projects may not contain the property at all.  If that's the case, just add it to the project.

**Comment by RobThree** [comment]
Hi. Sorry for the late reply, got busy and held up elsewhere. I just wanted to let you know, and document for posterity, that adding:

```xml
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
```

indeed worked in my case. Thanks!

**Comment by RobThree** [comment]
> Do you recall if the project was originally created with the standalone GUI?

No, sorry, I don't recall. We're using SHFB in about a dozen projects but most of them have their roots in the 2010-2015 range. I could check versioncontrol, but all I'd see is a commit of the `.shfbproj`, not _how_ it was created. If I _had_ to guess I think the standalone GUI was used, but memory is _very_ hazy on that. Sorry.
