### ISSUE TITLE
codeEntityReference issues in stand-alone SHFB

### ISSUE THREAD

**Issue by RichardJFoster** [EWSoftware/SHFB#98]
I have several assemblies that I am trying to document. There are quite a few public code entities that I would like to reference from within other documents (e.g. walkthroughs). For some reason while the documentation for those entities does appear in the generated output file, they cannot be found by searching in the Entity References panel. In addition, if they are referenced from within a MAML file using the codeEntityReference tag, that tag does not get resolved into the expected hyperlink.

Can you think of any reason why this might be the case?

**Comment by RichardJFoster** [comment]
<Sigh/> Please ignore. This was a simple PEBKAC error. At some point a co-worker had disabled generation of the documentation file for several assemblies. If the documentation files are there, things work so much better!

**Comment by RichardJFoster** [comment]
Although thinking about it... the fact that the documentation files weren't all there should mean that the classes in question should probably not have appeared in the generated help file, but they did. How very strange! Possibly the problem locating the items was because the documentation tree was incomplete (e.g. references for a base class or interface were not available).

**Comment by EWSoftware** [comment]
The members would be in the compiled help file, they just wouldn't have any comments associated with them.  The Entity References window just indexes the comments files rather than performing a full or partial build so if the comments files were missing or out of date, the members wouldn't be found.
