### ISSUE TITLE
Error window "System.Exception" popped up when create a SHFB project in Visual Studio

### ISSUE THREAD

**Issue by ledoen** [EWSoftware/SHFB#980]
visual stidio version: 17.5.0 Preview 6.0
.net 7.2
.net framework 4.8
visual studio running as administrator
Error window "System.Exception" popped up when create a SHFB project in Visual Studio
visual studio and computer restart but still not work
![image](https://user-images.githubusercontent.com/56869320/225836269-34ff2b9c-3e2b-4c7d-8513-520cf1afcb79.png)

**Comment by ledoen** [comment]
I didn't try it in non-preview build of Visual Studio, I think maybe this is the reason.
The message is "An exception of type System.Exception was thrown."
This is indeed uncommon，no result was found in google search, seems I am the only one who has encountered this problem. I'll close this issue.

**Comment by MCC-Masterix** [comment]
> I didn't try it in non-preview build of Visual Studio, I think maybe this is the reason. The message is "An exception of type System.Exception was thrown." This is indeed uncommon，no result was found in google search, seems I am the only one who has encountered this problem. I'll close this issue.

I have the same problem when i want to create a project in Visual studio on Windows 11
