### ISSUE TITLE
Target framework not supported reported when opening solution

### ISSUE THREAD

**Issue by ritchiecarroll** [EWSoftware/SHFB#996]
This is not a showstopper type of issue, more of a nuisance message that pops every time you open a solution with an included `SHFPProject`.

This is only happening from my new laptop with a fresh install of VS2022 and latest SHFB tools, so it looks like the issue is that my new laptop does not have the .NET 4.0 targeting pack (I presume this doesn't happen on my existing systems since they may still have the older .NET 4.0 targeting pack installed). I can certainly install this .NET 4.0 targeting pack, but it's no longer supported by Microsoft and the message text is highly persuasive in the direction you should take.

FYI, I always select the first option: "Update to the target to .NET 4.8 (Recommended)" and I also select the "Remember my choice" checkbox then click "Continue", however, this action seems to be ignored. That said, everything after that continues normally and appears to work fine.

Anyway, just wondering if there's a simple/manual fix that I can apply to my `.shfbproj` files or something in the installed SHFB tools configuration that you aware of that I can apply to keep this message from popping up without installing the .NET 4.0? If so, I'll probably do that for now instead of installing the .NET 4.0 targeting pack to save disk space on my laptop.

Here's a snip of the message:
![image](https://github.com/EWSoftware/SHFB/assets/9202752/117a9d6b-994b-42e3-a7fe-ac0aedb5b0c0)

**Comment by EWSoftware** [comment]
It's been encountered before (#979).  Adding a `TargetFrameworkVersion` property to the project with the value "v4.8" should correct it.

**Comment by ritchiecarroll** [comment]
Adding `<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>` to the `.shfbproj` indeed fixes this issue.
https://github.com/gemstone/common/commit/ae8591691c95365e615d1354467b4e006c574821
