### ISSUE TITLE
ReportProgress Race Condition

### ISSUE THREAD

**Issue by colsonab** [EWSoftware/SHFB#997]
On occasion I have received a race condition error associated with ReportProgress.  In my code I seem to have worked around this by not using the variable list of arguments and only passing an un-interpolated string (e.g., "The value is 1" instead of "The value is {0}")

However, occasionally I still see things like the following (error output during a build):

> CopyFromIndexComponent: "metadata" in-memory cache entries used: 1 of 15.
> ResolveArtLinksComponent: Copying media files...
> CopyFromIndexComponent: "reflection" in-memory cache entries used: 11 of 15.
> CopyFromIndexComponent: "comments" in-memory cache entries used: 4 of 30.
>     Last step completed in 00:01:06.3490
> -------------------------------
> 
> SHFB: Error BE0065: BUILD FAILED: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
>    at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
>    at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ReportProgress(BuildStep step, String message, Object[] args)
>    at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.<BuildTopics>b__27_1()
>    at System.Threading.Tasks.Task.Execute()
> 
> One or more errors occurred.
>    at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.BuildTopics()
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()
> 
> Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
>    at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
>    at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
>    at SandcastleBuilder.Utils.BuildEngine.BuildProcess.ReportProgress(BuildStep step, String message, Object[] args)
>    at SandcastleBuilder.Utils.BuildEngine.BuildAssemblerInternal.<BuildTopics>b__27_1()
>    at System.Threading.Tasks.Task.Execute()

Previous to this output I wrote a debug message to the output via a plugin that I developed.  The message is somewhat long as it spans 3 lines (because of 2 newline characters) and the longest line is about 9,900 characters.  Perhaps the length of time required to write this long messages is contributing to the race condition.  I can look to shorten this message but the problem would still persist.  I must also say that I only encounter this race condition rarely; it is not consistent; therefore, the error might not be readily duplicatable.  To duplicate the error, I would suggest writing a simple plugin to print very long messages.

**Comment by EWSoftware** [comment]
I wasn't able to duplicate it.  It may be something unique to your build component.  The only possible case I could see would be a rare instance where a component such as the Save Component which uses its own task to write out the topics in the background writes a message or raises the component event and the event handler writes a message after all topics have been built but before the message log has been completely flushed.  Under those specific conditions it was possible to try to write a message while the message queue is also trying to do so.  I've added a check for the message queue being empty to prevent that specific case but no guarantees that it will fix it if it's happening under some other conditions I haven't been able to determine.
